In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import os

In [ ]:
source_ml = """
<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10913">하주석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.050</td><td>39</td><td>32</td><td>274.2</td><td>112</td><td>38</td><td>74</td><td>0</td><td>100.0</td><td>3.67</td><td style="">4.52</td><td></td><td>1.52</td><td>1.75</td><td></td><td></td><td></td><td></td><td>7.79</td><td>21.57</td><td>2.52</td><td>10.31</td><td>0.793</td><td style="background-color:#F3F3F3; font-weight:bold;">1.050</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10082">이재원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.553</td><td>70</td><td>25</td><td>296.1</td><td>318</td><td>288</td><td>26</td><td>4</td><td>98.7</td><td>9.54</td><td style="">0.83</td><td></td><td>-1.00</td><td></td><td>0.06</td><td>0.88</td><td>3.09</td><td></td><td>2.93</td><td>6.04</td><td>2.50</td><td>5.43</td><td>0.299</td><td style="background-color:#F3F3F3; font-weight:bold;">0.553</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11334">심우준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.498</td><td>51</td><td>49</td><td>402.2</td><td>210</td><td>76</td><td>128</td><td>6</td><td>97.1</td><td>4.56</td><td style="">1.02</td><td></td><td>1.22</td><td>-0.60</td><td></td><td></td><td></td><td></td><td>1.65</td><td>4.56</td><td>3.24</td><td>4.89</td><td>0.168</td><td style="background-color:#F3F3F3; font-weight:bold;">0.498</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10170">최재훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.372</td><td>76</td><td>66</td><td>509.1</td><td>578</td><td>532</td><td>43</td><td>3</td><td>99.5</td><td>10.16</td><td style="">1.00</td><td></td><td>0.24</td><td></td><td>0.13</td><td>-0.88</td><td>-2.92</td><td></td><td>-1.56</td><td>-2.95</td><td>5.21</td><td>3.65</td><td>-0.159</td><td style="background-color:#F3F3F3; font-weight:bold;">0.372</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11414">이도윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.294</td><td>27</td><td>10</td><td>132.0</td><td>63</td><td>24</td><td>37</td><td>2</td><td>96.8</td><td>4.16</td><td style="">2.19</td><td></td><td>0.73</td><td>-1.15</td><td></td><td></td><td></td><td></td><td>1.77</td><td>3.70</td><td>1.12</td><td>2.89</td><td>0.180</td><td style="background-color:#F3F3F3; font-weight:bold;">0.294</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13138">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.285</td><td>19</td><td>2</td><td>56.1</td><td>18</td><td>17</td><td>0</td><td>1</td><td>94.4</td><td>2.72</td><td style="">3.01</td><td>0.43</td><td>-0.43</td><td></td><td></td><td></td><td></td><td></td><td>3.00</td><td>5.69</td><td>-0.20</td><td>2.80</td><td>0.306</td><td style="background-color:#F3F3F3; font-weight:bold;">0.285</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13138">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.246</td><td>31</td><td>9</td><td>127.1</td><td>29</td><td>27</td><td>2</td><td>0</td><td>100.0</td><td>2.05</td><td style="">2.88</td><td>-0.14</td><td>0.21</td><td></td><td></td><td></td><td></td><td></td><td>2.95</td><td>5.58</td><td>-0.53</td><td>2.42</td><td>0.300</td><td style="background-color:#F3F3F3; font-weight:bold;">0.246</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12539">이진영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.207</td><td>7</td><td>5</td><td>52.0</td><td>15</td><td>14</td><td>1</td><td>0</td><td>100.0</td><td>2.60</td><td style="">1.45</td><td>0.74</td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>2.26</td><td>4.22</td><td>-0.23</td><td>2.03</td><td>0.230</td><td style="background-color:#F3F3F3; font-weight:bold;">0.207</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13138">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.182</td><td>12</td><td>11</td><td>92.0</td><td>23</td><td>23</td><td>0</td><td>0</td><td>100.0</td><td>2.25</td><td style="">1.89</td><td>-0.27</td><td>0.17</td><td></td><td></td><td></td><td></td><td></td><td>1.78</td><td>3.38</td><td>0.00</td><td>1.78</td><td>0.182</td><td style="background-color:#F3F3F3; font-weight:bold;">0.182</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12539">이진영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.181</td><td>66</td><td>63</td><td>488.1</td><td>89</td><td>86</td><td>2</td><td>1</td><td>98.9</td><td>1.62</td><td style="">3.18</td><td>0.62</td><td>0.29</td><td></td><td></td><td></td><td></td><td></td><td>4.10</td><td>7.66</td><td>-2.32</td><td>1.78</td><td>0.417</td><td style="background-color:#F3F3F3; font-weight:bold;">0.181</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12585">김태연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.158</td><td>13</td><td>7</td><td>58.2</td><td>17</td><td>15</td><td>1</td><td>1</td><td>94.1</td><td>2.45</td><td style="">2.53</td><td>-0.28</td><td>-0.41</td><td></td><td></td><td></td><td></td><td></td><td>1.84</td><td>3.58</td><td>-0.29</td><td>1.55</td><td>0.187</td><td style="background-color:#F3F3F3; font-weight:bold;">0.158</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11414">이도윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.073</td><td>43</td><td>30</td><td>239.2</td><td>119</td><td>43</td><td>76</td><td>0</td><td>100.0</td><td>4.47</td><td style="">-1.66</td><td></td><td>0.68</td><td>0.67</td><td></td><td></td><td></td><td></td><td>-0.31</td><td>-0.64</td><td>1.02</td><td>0.71</td><td>-0.031</td><td style="background-color:#F3F3F3; font-weight:bold;">0.073</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11414">이도윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.048</td><td>4</td><td>0</td><td>5.0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>12.60</td><td style="">0.48</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.49</td><td>1.02</td><td>-0.02</td><td>0.47</td><td>0.050</td><td style="background-color:#F3F3F3; font-weight:bold;">0.048</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11414">이도윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.037</td><td>3</td><td>1</td><td>11.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>1.64</td><td style="">0.32</td><td></td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>0.36</td><td>0.75</td><td>0.00</td><td>0.36</td><td>0.037</td><td style="background-color:#F3F3F3; font-weight:bold;">0.037</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14707">최인호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.029</td><td>2</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.02</td><td>0.30</td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.29</td><td>0.70</td><td>0.00</td><td>0.29</td><td>0.029</td><td style="background-color:#F3F3F3; font-weight:bold;">0.029</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15139">이상혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.028</td><td>4</td><td>0</td><td>6.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.50</td><td style="">0.28</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.29</td><td>1.29</td><td>-0.01</td><td>0.28</td><td>0.029</td><td style="background-color:#F3F3F3; font-weight:bold;">0.028</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16312">플로리얼</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.019</td><td>2</td><td>1</td><td>11.0</td><td>4</td><td>3</td><td>1</td><td>0</td><td>100.0</td><td>3.27</td><td style="">-0.65</td><td>0.87</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.24</td><td>0.53</td><td>-0.05</td><td>0.19</td><td>0.024</td><td style="background-color:#F3F3F3; font-weight:bold;">0.019</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12539">이진영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.008</td><td>2</td><td>1</td><td>7.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.29</td><td style="">0.06</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.07</td><td>0.14</td><td>0.00</td><td>0.07</td><td>0.008</td><td style="background-color:#F3F3F3; font-weight:bold;">0.008</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14811">장규현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.006</td><td>1</td><td>0</td><td>2.2</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>10.13</td><td style="">0.00</td><td></td><td>0.01</td><td></td><td></td><td></td><td>0.04</td><td></td><td>0.04</td><td>5.66</td><td>0.02</td><td>0.06</td><td>0.004</td><td style="background-color:#F3F3F3; font-weight:bold;">0.006</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10913">하주석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.001</td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.02</td><td>0.00</td><td>0.01</td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;">0.001</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16311">이민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.005</td><td>1</td><td>1</td><td>5.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.80</td><td style="">0.21</td><td>-0.25</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.02</td><td>-1.18</td><td>-0.02</td><td>-0.04</td><td>-0.003</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.005</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13676">권광민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.005</td><td>3</td><td>0</td><td>6.1</td><td>8</td><td>8</td><td>0</td><td>0</td><td>100.0</td><td>11.37</td><td style="">-0.02</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.01</td><td>-0.32</td><td>-0.04</td><td>-0.05</td><td>-0.001</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.005</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12585">김태연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.007</td><td>35</td><td>16</td><td>183.1</td><td>177</td><td>157</td><td>18</td><td>2</td><td>98.9</td><td>8.59</td><td style="">1.94</td><td></td><td>-0.17</td><td></td><td>-0.20</td><td></td><td></td><td></td><td>1.57</td><td>3.05</td><td>-1.64</td><td>-0.07</td><td>0.160</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.007</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16312">플로리얼</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.010</td><td>63</td><td>62</td><td>537.1</td><td>142</td><td>133</td><td>4</td><td>5</td><td>96.5</td><td>2.29</td><td style="">1.25</td><td>0.21</td><td>-1.55</td><td></td><td></td><td></td><td></td><td></td><td>-0.10</td><td>-0.21</td><td>0.00</td><td>-0.10</td><td>-0.010</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.010</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14126">유로결</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.014</td><td>1</td><td>0</td><td>3.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.13</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.13</td><td>-0.90</td><td>-0.01</td><td>-0.14</td><td>-0.013</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.014</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16396">리베라토</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.026</td><td>16</td><td>16</td><td>134.0</td><td>32</td><td>29</td><td>1</td><td>2</td><td>93.8</td><td>2.01</td><td style="">1.11</td><td>-0.60</td><td>-0.77</td><td></td><td></td><td></td><td></td><td></td><td>-0.26</td><td>-1.94</td><td>0.00</td><td>-0.26</td><td>-0.026</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.026</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10913">하주석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.041</td><td>9</td><td>9</td><td>60.1</td><td>21</td><td>8</td><td>13</td><td>0</td><td>100.0</td><td>3.13</td><td style="">-0.93</td><td></td><td>0.17</td><td>0.05</td><td></td><td></td><td></td><td></td><td>-0.71</td><td>-1.96</td><td>0.31</td><td>-0.40</td><td>-0.072</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.041</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14707">최인호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.053</td><td>5</td><td>0</td><td>13.0</td><td>3</td><td>2</td><td>1</td><td>0</td><td>100.0</td><td>2.08</td><td style="">-0.38</td><td>-0.12</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.48</td><td>-1.18</td><td>-0.04</td><td>-0.52</td><td>-0.049</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.053</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14125">노시환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.056</td><td>90</td><td>90</td><td>797.1</td><td>207</td><td>61</td><td>135</td><td>11</td><td>94.7</td><td>2.21</td><td style="">-1.25</td><td></td><td>0.38</td><td>0.00</td><td>0.33</td><td></td><td></td><td></td><td>-0.55</td><td>-0.86</td><td>0.00</td><td>-0.55</td><td>-0.056</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.056</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14706">임종찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.057</td><td>13</td><td>10</td><td>86.1</td><td>17</td><td>16</td><td>0</td><td>1</td><td>94.1</td><td>1.67</td><td style="">-0.92</td><td>1.06</td><td>-0.37</td><td></td><td></td><td></td><td></td><td></td><td>-0.23</td><td>-1.91</td><td>-0.33</td><td>-0.56</td><td>-0.023</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.057</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14126">유로결</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.080</td><td>2</td><td>1</td><td>13.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>2.08</td><td style="">-0.44</td><td>-0.30</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.72</td><td>-5.20</td><td>-0.06</td><td>-0.78</td><td>-0.074</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.080</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10014">안치홍</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.082</td><td>5</td><td>5</td><td>35.0</td><td>21</td><td>5</td><td>15</td><td>1</td><td>95.2</td><td>5.14</td><td style="">-0.80</td><td></td><td>0.10</td><td>-0.26</td><td></td><td></td><td></td><td></td><td>-0.96</td><td>-3.44</td><td>0.15</td><td>-0.81</td><td>-0.097</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.082</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12589">김인환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.088</td><td>2</td><td>1</td><td>9.0</td><td>11</td><td>10</td><td>0</td><td>1</td><td>90.9</td><td>10.00</td><td style="">-0.30</td><td></td><td>-0.49</td><td></td><td></td><td></td><td></td><td></td><td>-0.79</td><td>-28.34</td><td>-0.08</td><td>-0.87</td><td>-0.080</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.088</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16110">황영묵</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.120</td><td>78</td><td>47</td><td>473.1</td><td>240</td><td>85</td><td>150</td><td>5</td><td>97.9</td><td>4.47</td><td style="">-2.07</td><td></td><td>-0.69</td><td>-0.46</td><td></td><td></td><td></td><td></td><td>-3.22</td><td>-5.72</td><td>2.04</td><td>-1.18</td><td>-0.328</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.120</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15139">이상혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.132</td><td>9</td><td>0</td><td>19.2</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>0.92</td><td style="">-1.60</td><td>0.32</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-1.24</td><td>-5.59</td><td>-0.05</td><td>-1.29</td><td>-0.127</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.132</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14126">유로결</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.161</td><td>4</td><td>0</td><td>13.0</td><td>3</td><td>2</td><td>1</td><td>0</td><td>100.0</td><td>2.08</td><td style="">-1.49</td><td>-0.11</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-1.58</td><td>-11.35</td><td>0.00</td><td>-1.58</td><td>-0.161</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.161</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14707">최인호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.211</td><td>14</td><td>8</td><td>74.1</td><td>9</td><td>9</td><td>0</td><td>0</td><td>100.0</td><td>1.09</td><td style="">-1.62</td><td>-0.20</td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>-1.72</td><td>-4.21</td><td>-0.35</td><td>-2.07</td><td>-0.176</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.211</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15422">문현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.217</td><td>4</td><td>1</td><td>14.0</td><td>4</td><td>3</td><td>1</td><td>0</td><td>100.0</td><td>2.57</td><td style="">-2.22</td><td>0.06</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-2.13</td><td>-3.45</td><td>0.00</td><td>-2.13</td><td>-0.217</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.217</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15422">문현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.371</td><td>53</td><td>52</td><td>438.1</td><td>76</td><td>72</td><td>3</td><td>1</td><td>98.7</td><td>1.54</td><td style="">-1.02</td><td>-0.44</td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>-1.39</td><td>-2.25</td><td>-2.25</td><td>-3.64</td><td>-0.141</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.371</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12585">김태연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.410</td><td>27</td><td>23</td><td>170.1</td><td>30</td><td>28</td><td>1</td><td>1</td><td>96.7</td><td>1.53</td><td style="">-2.95</td><td>0.07</td><td>-0.28</td><td></td><td></td><td></td><td></td><td></td><td>-3.16</td><td>-6.15</td><td>-0.86</td><td>-4.02</td><td>-0.322</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.410</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11215">채은성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-1.035</td><td>75</td><td>74</td><td>607.2</td><td>588</td><td>567</td><td>17</td><td>4</td><td>99.3</td><td>8.65</td><td style="">-3.58</td><td></td><td>-0.41</td><td></td><td>-0.27</td><td></td><td></td><td></td><td>-4.26</td><td>-6.98</td><td>-5.90</td><td>-10.16</td><td>-0.434</td><td style="background-color:#F3F3F3; font-weight:bold;">-1.035</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14196">윤산흠</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>1.1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15421">김서현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>44</td><td>0</td><td>42.2</td><td>6</td><td>0</td><td>6</td><td>0</td><td>100.0</td><td>1.27</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16372">이승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>2.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.29</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.30</td><td>10.76</td><td></td><td></td><td>0.030</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15139">이상혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>8</td><td>0</td><td>12.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>2.25</td><td style="">-1.32</td><td>-0.05</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-1.34</td><td>-6.04</td><td></td><td></td><td>-0.137</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16301">정우주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>29</td><td>0</td><td>25.1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15422">문현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.01</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15015">허인서</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>3</td><td>0</td><td>3.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>12.00</td><td style="">0.00</td><td></td><td>0.01</td><td></td><td></td><td></td><td>-0.21</td><td></td><td>-0.14</td><td>-4.95</td><td></td><td></td><td>-0.014</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16108">조동욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>38</td><td>1</td><td>39.0</td><td>7</td><td>0</td><td>7</td><td>0</td><td>100.0</td><td>1.62</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11117">김종수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>39</td><td>0</td><td>35.0</td><td>5</td><td>2</td><td>3</td><td>0</td><td>100.0</td><td>1.29</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14711">김승일</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>4</td><td>0</td><td>2.2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16372">이승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">25</span> <span><img src="/data/team/ci/2025/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>3.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.22</td><td></td><td></td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>
"""

In [ ]:
soup = BeautifulSoup(source_ml, 'html.parser')

trs = soup.find_all('tr')
pids = []
for tr in trs:
    a_tag = tr.find('a')
    if a_tag:
        pid = a_tag['href'][-5:]
        pids.append(pid)
    else:
        pids.append(None)

pids = pd.Series(pids)
pids

0      None
1      None
2     10913
3     10082
4     11334
5     10170
6     11414
7     13138
8     13138
9     12539
10    13138
11    12539
12    12585
13    11414
14    11414
15    11414
16    14707
17    15139
18    16312
19    12539
20    14811
21    10913
22    16311
23    13676
24    12585
25    16312
26    14126
27    16396
28    10913
29    14707
30    14125
31    14706
32    14126
33    10014
34    12589
35    16110
36    15139
37    14126
38    14707
39    15422
40    15422
41    12585
42    11215
43    14196
44    15421
45    16372
46    15139
47    16301
48    15422
49    15015
50    16108
51    11117
52    14711
53    16372
dtype: object

In [ ]:
eagles_fielding = pd.read_html(source_ml)[0]
eagles_fielding.head()

/tmp/ipython-input-16-241927704.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  eagles_fielding = pd.read_html(source_ml)[0]

  Rank Name   Team      Sort▼   G  GS     IP   TC   PO  Ass  ... 수비 관련 득점 기여도  \
  Rank Name   Team WAAwithPOS   G  GS     IP   TC   PO  Ass  ...       Bt RAA
0    1  하주석  25 SS      1.050  39  32  274.2  112   38   74  ...          NaN
1    2  이재원   25 C      0.553  70  25  296.1  318  288   26  ...         0.06
2    3  심우준  25 SS      0.498  51  49  402.2  210   76  128  ...          NaN
3    4  최재훈   25 C      0.372  76  66  509.1  578  532   43  ...         0.13
4    5  이도윤  25 SS      0.294  27  10  132.0   63   24   37  ...          NaN

                                       POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
  CS RAA Blk RAA Frm RAA 종합 RAA   /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
0    NaN     NaN     NaN   7.79  21.57   2.52      10.31    0.793       1.050
1   0.88    3.09     NaN   2.93   6.04   2.50       5.43    0.299       0.553
2    NaN     NaN     NaN   1.65   4.56   3.24       4.89    0.168       0.498
3  -0.88   -2.92     NaN  -1.56  -2.95   5.21       3.65   -0.159       0.372
4    NaN     NaN     NaN   1.77   3.70   1.12       2.89    0.180       0.294

[5 rows x 27 columns]

In [ ]:
eagles_fielding.shape

(52, 27)

In [ ]:
pids = pids.loc[2:]
pids.reset_index(drop=True, inplace=True)
pids

0     10913
1     10082
2     11334
3     10170
4     11414
5     13138
6     13138
7     12539
8     13138
9     12539
10    12585
11    11414
12    11414
13    11414
14    14707
15    15139
16    16312
17    12539
18    14811
19    10913
20    16311
21    13676
22    12585
23    16312
24    14126
25    16396
26    10913
27    14707
28    14125
29    14706
30    14126
31    10014
32    12589
33    16110
34    15139
35    14126
36    14707
37    15422
38    15422
39    12585
40    11215
41    14196
42    15421
43    16372
44    15139
45    16301
46    15422
47    15015
48    16108
49    11117
50    14711
51    16372
dtype: object

In [ ]:
eagles_fielding['pid'] = pids
eagles_fielding.head()

  Rank Name   Team      Sort▼   G  GS     IP   TC   PO  Ass  ... 수비 관련 득점 기여도  \
  Rank Name   Team WAAwithPOS   G  GS     IP   TC   PO  Ass  ...       CS RAA
0    1  하주석  25 SS      1.050  39  32  274.2  112   38   74  ...          NaN
1    2  이재원   25 C      0.553  70  25  296.1  318  288   26  ...         0.88
2    3  심우준  25 SS      0.498  51  49  402.2  210   76  128  ...          NaN
3    4  최재훈   25 C      0.372  76  66  509.1  578  532   43  ...        -0.88
4    5  이도윤  25 SS      0.294  27  10  132.0   63   24   37  ...          NaN

                                POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼    pid
  Blk RAA Frm RAA 종합 RAA   /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
0     NaN     NaN   7.79  21.57   2.52      10.31    0.793       1.050  10913
1    3.09     NaN   2.93   6.04   2.50       5.43    0.299       0.553  10082
2     NaN     NaN   1.65   4.56   3.24       4.89    0.168       0.498  11334
3   -2.92     NaN  -1.56  -2.95   5.21       3.65   -0.159       0.372  10170
4     NaN     NaN   1.77   3.70   1.12       2.89    0.180       0.294  11414

[5 rows x 28 columns]

In [3]:
def get_team_stats_from_markup(markup):
    soup = BeautifulSoup(markup, 'html.parser')
    table = soup.find('table')
    df = pd.read_html(str(table))[0]
    pids = []
    trs = soup.find_all('tr')
    for tr in trs:
        a_tag = tr.find('a')
        if a_tag:
            pid = a_tag['href'][-5:]
            pids.append(pid)
        else:
            pids.append(None)
    return df,pids

In [ ]:
twins_ml = """<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10475">오지환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.957</td><td>73</td><td>60</td><td>529.1</td><td>242</td><td>82</td><td>156</td><td>4</td><td>98.3</td><td>4.05</td><td style="">1.27</td><td></td><td>2.43</td><td>0.72</td><td></td><td></td><td></td><td></td><td>4.42</td><td>8.49</td><td>4.98</td><td>9.40</td><td>0.450</td><td style="background-color:#F3F3F3; font-weight:bold;">0.957</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10387">박동원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.876</td><td>81</td><td>63</td><td>579.0</td><td>528</td><td>476</td><td>47</td><td>5</td><td>99.1</td><td>8.13</td><td style="">0.31</td><td></td><td>-0.02</td><td></td><td>-0.14</td><td>0.04</td><td>2.40</td><td></td><td>1.86</td><td>3.05</td><td>6.74</td><td>8.61</td><td>0.190</td><td style="background-color:#F3F3F3; font-weight:bold;">0.876</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11190">박해민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.795</td><td>92</td><td>86</td><td>750.1</td><td>199</td><td>195</td><td>3</td><td>1</td><td>99.5</td><td>2.37</td><td style="">6.68</td><td>0.26</td><td>0.86</td><td></td><td></td><td></td><td></td><td></td><td>7.80</td><td>12.21</td><td>0.00</td><td>7.80</td><td>0.795</td><td style="background-color:#F3F3F3; font-weight:bold;">0.795</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14140">구본혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.734</td><td>44</td><td>31</td><td>262.0</td><td>137</td><td>52</td><td>83</td><td>2</td><td>98.5</td><td>4.64</td><td style="">4.18</td><td></td><td>0.95</td><td>-0.16</td><td></td><td></td><td></td><td></td><td>4.97</td><td>8.42</td><td>2.24</td><td>7.21</td><td>0.506</td><td style="background-color:#F3F3F3; font-weight:bold;">0.734</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15084">최원영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.365</td><td>20</td><td>3</td><td>45.0</td><td>18</td><td>18</td><td>0</td><td>0</td><td>100.0</td><td>3.60</td><td style="">2.85</td><td>0.65</td><td>0.08</td><td></td><td></td><td></td><td></td><td></td><td>3.58</td><td>7.16</td><td>0.00</td><td>3.58</td><td>0.365</td><td style="background-color:#F3F3F3; font-weight:bold;">0.365</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14140">구본혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.310</td><td>35</td><td>15</td><td>146.1</td><td>34</td><td>10</td><td>24</td><td>0</td><td>100.0</td><td>2.09</td><td style="">1.42</td><td></td><td>0.54</td><td>0.37</td><td>0.72</td><td></td><td></td><td></td><td>3.05</td><td>5.17</td><td>0.00</td><td>3.05</td><td>0.310</td><td style="background-color:#F3F3F3; font-weight:bold;">0.310</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14680">함창건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.225</td><td>9</td><td>7</td><td>56.0</td><td>17</td><td>17</td><td>0</td><td>0</td><td>100.0</td><td>2.73</td><td style="">1.65</td><td>0.77</td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>2.49</td><td>23.90</td><td>-0.28</td><td>2.21</td><td>0.254</td><td style="background-color:#F3F3F3; font-weight:bold;">0.225</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13112">문성주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.217</td><td>28</td><td>22</td><td>194.0</td><td>49</td><td>49</td><td>0</td><td>0</td><td>100.0</td><td>2.27</td><td style="">2.98</td><td>-0.15</td><td>0.26</td><td></td><td></td><td></td><td></td><td></td><td>3.08</td><td>5.35</td><td>-0.95</td><td>2.13</td><td>0.314</td><td style="background-color:#F3F3F3; font-weight:bold;">0.217</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13109">송찬의</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.155</td><td>23</td><td>12</td><td>122.1</td><td>32</td><td>30</td><td>2</td><td>0</td><td>100.0</td><td>2.35</td><td style="">1.83</td><td>0.12</td><td>0.16</td><td></td><td></td><td></td><td></td><td></td><td>2.11</td><td>4.68</td><td>-0.59</td><td>1.52</td><td>0.215</td><td style="background-color:#F3F3F3; font-weight:bold;">0.155</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13112">문성주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.142</td><td>36</td><td>33</td><td>295.1</td><td>76</td><td>72</td><td>3</td><td>1</td><td>98.7</td><td>2.29</td><td style="">3.24</td><td>-0.36</td><td>-0.02</td><td></td><td></td><td></td><td></td><td></td><td>2.85</td><td>4.95</td><td>-1.46</td><td>1.39</td><td>0.291</td><td style="background-color:#F3F3F3; font-weight:bold;">0.142</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15086">문정빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.135</td><td>9</td><td>2</td><td>26.0</td><td>4</td><td>0</td><td>4</td><td>0</td><td>100.0</td><td>1.38</td><td style="">1.14</td><td></td><td>0.10</td><td>0.09</td><td></td><td></td><td></td><td></td><td>1.32</td><td>9.07</td><td>0.00</td><td>1.32</td><td>0.135</td><td style="background-color:#F3F3F3; font-weight:bold;">0.135</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12545">김주성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.124</td><td>3</td><td>2</td><td>16.0</td><td>23</td><td>21</td><td>2</td><td>0</td><td>100.0</td><td>12.94</td><td style="">1.31</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>1.34</td><td>14.81</td><td>-0.12</td><td>1.22</td><td>0.136</td><td style="background-color:#F3F3F3; font-weight:bold;">0.124</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15084">최원영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.122</td><td>15</td><td>5</td><td>46.1</td><td>13</td><td>13</td><td>0</td><td>0</td><td>100.0</td><td>2.53</td><td style="">1.68</td><td>-0.39</td><td>0.08</td><td></td><td></td><td></td><td></td><td></td><td>1.37</td><td>2.73</td><td>-0.17</td><td>1.20</td><td>0.139</td><td style="background-color:#F3F3F3; font-weight:bold;">0.122</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14783">이영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.106</td><td>12</td><td>2</td><td>34.0</td><td>43</td><td>41</td><td>2</td><td>0</td><td>100.0</td><td>11.38</td><td style="">1.18</td><td></td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>1.24</td><td>4.59</td><td>-0.20</td><td>1.04</td><td>0.127</td><td style="background-color:#F3F3F3; font-weight:bold;">0.106</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13109">송찬의</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.076</td><td>25</td><td>17</td><td>153.0</td><td>29</td><td>29</td><td>0</td><td>0</td><td>100.0</td><td>1.71</td><td style="">1.47</td><td>-0.29</td><td>0.25</td><td></td><td></td><td></td><td></td><td></td><td>1.43</td><td>3.17</td><td>-0.69</td><td>0.74</td><td>0.146</td><td style="background-color:#F3F3F3; font-weight:bold;">0.076</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14140">구본혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.066</td><td>26</td><td>19</td><td>162.0</td><td>88</td><td>39</td><td>48</td><td>1</td><td>98.9</td><td>4.83</td><td style="">-0.67</td><td></td><td>-0.05</td><td>0.67</td><td></td><td></td><td></td><td></td><td>-0.05</td><td>-0.09</td><td>0.70</td><td>0.65</td><td>-0.005</td><td style="background-color:#F3F3F3; font-weight:bold;">0.066</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12931">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.057</td><td>6</td><td>0</td><td>13.0</td><td>4</td><td>0</td><td>4</td><td>0</td><td>100.0</td><td>2.77</td><td style="">0.51</td><td></td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>0.56</td><td>6.22</td><td>0.00</td><td>0.56</td><td>0.057</td><td style="background-color:#F3F3F3; font-weight:bold;">0.057</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14680">함창건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.049</td><td>6</td><td>0</td><td>12.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>2.25</td><td style="">0.50</td><td>-0.02</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.50</td><td>4.77</td><td>-0.02</td><td>0.48</td><td>0.051</td><td style="background-color:#F3F3F3; font-weight:bold;">0.049</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15086">문정빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.033</td><td>2</td><td>2</td><td>7.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>5.14</td><td style="">0.43</td><td>-0.07</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.36</td><td>2.49</td><td>-0.04</td><td>0.32</td><td>0.037</td><td style="background-color:#F3F3F3; font-weight:bold;">0.033</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14606">천성호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.021</td><td>6</td><td>4</td><td>37.0</td><td>36</td><td>32</td><td>4</td><td>0</td><td>100.0</td><td>8.76</td><td style="">0.50</td><td></td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>0.57</td><td>1.75</td><td>-0.36</td><td>0.21</td><td>0.058</td><td style="background-color:#F3F3F3; font-weight:bold;">0.021</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12931">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.021</td><td>7</td><td>2</td><td>27.0</td><td>26</td><td>23</td><td>3</td><td>0</td><td>100.0</td><td>8.67</td><td style="">0.36</td><td></td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>0.41</td><td>4.54</td><td>-0.20</td><td>0.21</td><td>0.042</td><td style="background-color:#F3F3F3; font-weight:bold;">0.021</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14606">천성호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.019</td><td>10</td><td>8</td><td>58.0</td><td>13</td><td>4</td><td>9</td><td>0</td><td>100.0</td><td>2.02</td><td style="">-0.45</td><td></td><td>0.21</td><td>0.42</td><td></td><td></td><td></td><td></td><td>0.18</td><td>0.56</td><td>0.00</td><td>0.18</td><td>0.019</td><td style="background-color:#F3F3F3; font-weight:bold;">0.019</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15081">이주헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.011</td><td>43</td><td>29</td><td>229.1</td><td>218</td><td>206</td><td>10</td><td>2</td><td>99.1</td><td>8.48</td><td style="">-0.53</td><td></td><td>-0.22</td><td></td><td></td><td>-0.04</td><td>-2.24</td><td></td><td>-2.36</td><td>-6.80</td><td>2.47</td><td>0.11</td><td>-0.240</td><td style="background-color:#F3F3F3; font-weight:bold;">0.011</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14187">최승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.008</td><td>1</td><td>0</td><td>2.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>4.50</td><td style="">0.08</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.09</td><td>4.17</td><td>-0.01</td><td>0.08</td><td>0.009</td><td style="background-color:#F3F3F3; font-weight:bold;">0.008</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16014">손용준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.005</td><td>1</td><td>1</td><td>4.0</td><td>6</td><td>6</td><td>0</td><td>0</td><td>100.0</td><td>13.50</td><td style="">0.08</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.09</td><td>3.17</td><td>-0.04</td><td>0.05</td><td>0.009</td><td style="background-color:#F3F3F3; font-weight:bold;">0.005</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12931">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.003</td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.05</td><td>0.02</td><td>0.02</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">0.003</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15084">최원영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.002</td><td>31</td><td>2</td><td>69.2</td><td>14</td><td>14</td><td>0</td><td>0</td><td>100.0</td><td>1.81</td><td style="">0.17</td><td>-0.04</td><td>0.09</td><td></td><td></td><td></td><td></td><td></td><td>0.23</td><td>0.45</td><td>-0.21</td><td>0.02</td><td>0.023</td><td style="background-color:#F3F3F3; font-weight:bold;">0.002</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13056">신민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.001</td><td>2</td><td>1</td><td>6.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.02</td><td>0.00</td><td>0.01</td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;">0.001</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14669">유영찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.000</td><td>16</td><td>0</td><td>18.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>0.50</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">0.000</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15085">김성우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.001</td><td>4</td><td>0</td><td>8.0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>7.88</td><td style="">0.00</td><td></td><td>0.03</td><td></td><td></td><td></td><td>-0.15</td><td></td><td>-0.08</td><td>-2.87</td><td>0.07</td><td>-0.01</td><td>-0.008</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.001</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14783">이영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.002</td><td>2</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.01</td><td>-0.02</td><td>-0.02</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.002</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15086">문정빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.009</td><td>2</td><td>1</td><td>8.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td>-0.07</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.06</td><td>-0.40</td><td>-0.03</td><td>-0.09</td><td>-0.006</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.009</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12545">김주성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.025</td><td>2</td><td>0</td><td>3.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.26</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.25</td><td>-2.79</td><td>0.01</td><td>-0.24</td><td>-0.026</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.025</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15086">문정빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.027</td><td>6</td><td>2</td><td>18.0</td><td>20</td><td>18</td><td>2</td><td>0</td><td>100.0</td><td>10.00</td><td style="">-0.18</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.15</td><td>-1.01</td><td>-0.12</td><td>-0.27</td><td>-0.015</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.027</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13109">송찬의</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.030</td><td>4</td><td>2</td><td>15.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>1.20</td><td style="">-0.37</td><td>0.04</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.30</td><td>-0.66</td><td>0.00</td><td>-0.30</td><td>-0.030</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.030</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13056">신민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.049</td><td>1</td><td>0</td><td>6.0</td><td>2</td><td>0</td><td>2</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-0.58</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.55</td><td>-0.95</td><td>0.06</td><td>-0.49</td><td>-0.056</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.049</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14783">이영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.051</td><td>11</td><td>5</td><td>50.0</td><td>10</td><td>2</td><td>8</td><td>0</td><td>100.0</td><td>1.80</td><td style="">-0.77</td><td></td><td>0.18</td><td>0.09</td><td></td><td></td><td></td><td></td><td>-0.50</td><td>-1.83</td><td>0.00</td><td>-0.50</td><td>-0.051</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.051</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14606">천성호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.051</td><td>1</td><td>0</td><td>6.0</td><td>3</td><td>2</td><td>1</td><td>0</td><td>100.0</td><td>4.50</td><td style="">-0.55</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.53</td><td>-1.62</td><td>0.03</td><td>-0.50</td><td>-0.054</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.051</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14783">이영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.052</td><td>8</td><td>1</td><td>18.0</td><td>6</td><td>1</td><td>5</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-0.22</td><td></td><td>0.10</td><td>-0.56</td><td></td><td></td><td></td><td></td><td>-0.67</td><td>-2.49</td><td>0.16</td><td>-0.51</td><td>-0.069</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.052</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14783">이영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.057</td><td>12</td><td>5</td><td>48.0</td><td>32</td><td>11</td><td>21</td><td>0</td><td>100.0</td><td>6.00</td><td style="">-0.92</td><td></td><td>0.14</td><td>-0.01</td><td></td><td></td><td></td><td></td><td>-0.80</td><td>-2.95</td><td>0.24</td><td>-0.56</td><td>-0.081</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.057</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16014">손용준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.076</td><td>2</td><td>2</td><td>13.0</td><td>5</td><td>1</td><td>3</td><td>1</td><td>80.0</td><td>2.77</td><td style="">-0.62</td><td></td><td>-0.46</td><td>0.33</td><td></td><td></td><td></td><td></td><td>-0.75</td><td>-26.87</td><td>0.00</td><td>-0.75</td><td>-0.076</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.076</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16279">박관우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.081</td><td>1</td><td>0</td><td>2.0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td>-0.28</td><td>-0.50</td><td></td><td></td><td></td><td></td><td></td><td>-0.79</td><td>-18.96</td><td>-0.01</td><td>-0.80</td><td>-0.080</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.081</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10187">김현수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.082</td><td>12</td><td>9</td><td>83.0</td><td>84</td><td>73</td><td>9</td><td>2</td><td>97.6</td><td>8.89</td><td style="">0.32</td><td></td><td>-0.36</td><td></td><td>0.10</td><td></td><td></td><td></td><td>0.06</td><td>0.09</td><td>-0.86</td><td>-0.80</td><td>0.006</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.082</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13109">송찬의</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.101</td><td>3</td><td>0</td><td>6.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-1.01</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.99</td><td>-2.19</td><td>0.00</td><td>-0.99</td><td>-0.101</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.101</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16279">박관우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.102</td><td>2</td><td>1</td><td>6.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-1.02</td><td>0.03</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.98</td><td>-23.52</td><td>-0.02</td><td>-1.00</td><td>-0.100</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.102</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13109">송찬의</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.107</td><td>4</td><td>2</td><td>16.0</td><td>19</td><td>17</td><td>1</td><td>1</td><td>94.7</td><td>10.13</td><td style="">-0.92</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.89</td><td>-1.98</td><td>-0.16</td><td>-1.05</td><td>-0.091</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.107</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12545">김주성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.180</td><td>1</td><td>1</td><td>4.0</td><td>3</td><td>0</td><td>2</td><td>1</td><td>66.7</td><td>4.50</td><td style="">-1.03</td><td></td><td>-0.49</td><td>-0.24</td><td></td><td></td><td></td><td></td><td>-1.77</td><td>-19.56</td><td>0.00</td><td>-1.77</td><td>-0.180</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.180</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12546">홍창기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.202</td><td>38</td><td>36</td><td>296.2</td><td>52</td><td>51</td><td>1</td><td>0</td><td>100.0</td><td>1.58</td><td style="">-1.20</td><td>0.35</td><td>0.49</td><td></td><td></td><td></td><td></td><td></td><td>-0.36</td><td>-1.38</td><td>-1.62</td><td>-1.98</td><td>-0.037</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.202</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15532">오스틴</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.289</td><td>61</td><td>60</td><td>501.1</td><td>501</td><td>455</td><td>42</td><td>4</td><td>99.2</td><td>8.92</td><td style="">2.20</td><td></td><td>-0.10</td><td></td><td>0.28</td><td></td><td></td><td></td><td>2.38</td><td>4.57</td><td>-5.22</td><td>-2.84</td><td>0.243</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.289</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14137">문보경</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.322</td><td>17</td><td>8</td><td>80.0</td><td>87</td><td>80</td><td>5</td><td>2</td><td>97.7</td><td>9.56</td><td style="">-1.67</td><td></td><td>-0.87</td><td></td><td>0.10</td><td></td><td></td><td></td><td>-2.44</td><td>-3.90</td><td>-0.72</td><td>-3.16</td><td>-0.248</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.322</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14137">문보경</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.325</td><td>61</td><td>59</td><td>500.0</td><td>137</td><td>30</td><td>97</td><td>10</td><td>92.7</td><td>2.29</td><td style="">-2.01</td><td></td><td>-0.20</td><td>-1.06</td><td>0.08</td><td></td><td></td><td></td><td>-3.20</td><td>-5.11</td><td>0.00</td><td>-3.20</td><td>-0.325</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.325</td></tr><tr><td style="text-align:center;">52</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10187">김현수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.354</td><td>48</td><td>46</td><td>359.1</td><td>79</td><td>77</td><td>1</td><td>1</td><td>98.7</td><td>1.95</td><td style="">-1.05</td><td>-0.45</td><td>-0.03</td><td></td><td></td><td></td><td></td><td></td><td>-1.54</td><td>-2.43</td><td>-1.94</td><td>-3.48</td><td>-0.157</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.354</td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13056">신민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.471</td><td>81</td><td>68</td><td>597.1</td><td>340</td><td>141</td><td>191</td><td>8</td><td>97.6</td><td>5.00</td><td style="">-4.48</td><td></td><td>-2.37</td><td>-0.66</td><td></td><td></td><td></td><td></td><td>-7.50</td><td>-13.02</td><td>2.88</td><td>-4.62</td><td>-0.764</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.471</td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11164">장현식</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>32</td><td>0</td><td>31.0</td><td>3</td><td>1</td><td>1</td><td>1</td><td>66.7</td><td>0.58</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14816">우강훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>11</td><td>0</td><td>9.2</td><td>2</td><td>0</td><td>2</td><td>0</td><td>100.0</td><td>1.86</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10749">이우찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>23</td><td>0</td><td>19.0</td><td>4</td><td>2</td><td>1</td><td>1</td><td>75.0</td><td>1.42</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16274">김영우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>38</td><td>0</td><td>34.2</td><td>8</td><td>1</td><td>7</td><td>0</td><td>100.0</td><td>2.08</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11166">김진성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>53</td><td>0</td><td>48.1</td><td>10</td><td>1</td><td>9</td><td>0</td><td>100.0</td><td>1.86</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14134">이정용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>14</td><td>0</td><td>13.1</td><td>2</td><td>0</td><td>2</td><td>0</td><td>100.0</td><td>1.35</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14187">최승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.49</td><td>0.12</td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.37</td><td>-17.63</td><td></td><td></td><td>-0.037</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11094">함덕주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>4</td><td>0</td><td>3.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14143">이지강</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>31</td><td>1</td><td>37.2</td><td>6</td><td>3</td><td>3</td><td>0</td><td>100.0</td><td>1.43</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15486">박명근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">25</span> <span><img src="/data/team/ci/2025/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>38</td><td>0</td><td>33.2</td><td>10</td><td>4</td><td>6</td><td>0</td><td>100.0</td><td>2.67</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>"""
twins_fielding, twins_pid = get_team_stats_from_markup(twins_ml)

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

In [ ]:
twins_fielding.shape

(63, 27)

In [ ]:
len(twins_pid)

65

In [ ]:
twins_fielding['pid'] = twins_pid[2:]
twins_fielding.head()

  Rank Name   Team      Sort▼   G  GS     IP   TC   PO  Ass  ... 수비 관련 득점 기여도  \
  Rank Name   Team WAAwithPOS   G  GS     IP   TC   PO  Ass  ...       CS RAA
0    1  오지환  25 SS      0.957  73  60  529.1  242   82  156  ...          NaN
1    2  박동원   25 C      0.876  81  63  579.0  528  476   47  ...         0.04
2    3  박해민  25 CF      0.795  92  86  750.1  199  195    3  ...          NaN
3    4  구본혁  25 SS      0.734  44  31  262.0  137   52   83  ...          NaN
4    5  최원영  25 CF      0.365  20   3   45.0   18   18    0  ...          NaN

                                POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼    pid
  Blk RAA Frm RAA 종합 RAA   /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
0     NaN     NaN   4.42   8.49   4.98       9.40    0.450       0.957  10475
1     2.4     NaN   1.86   3.05   6.74       8.61    0.190       0.876  10387
2     NaN     NaN   7.80  12.21   0.00       7.80    0.795       0.795  11190
3     NaN     NaN   4.97   8.42   2.24       7.21    0.506       0.734  14140
4     NaN     NaN   3.58   7.16   0.00       3.58    0.365       0.365  15084

[5 rows x 28 columns]

In [2]:
from io import StringIO

In [ ]:
giants_table = """<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10753">유강남</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.400</td><td>63</td><td>58</td><td>391.2</td><td>376</td><td>348</td><td>27</td><td>1</td><td>99.7</td><td>8.62</td><td style="">-0.29</td><td></td><td>0.85</td><td></td><td>-0.10</td><td>-0.39</td><td>-1.23</td><td></td><td>-0.80</td><td>-1.56</td><td>4.73</td><td>3.93</td><td>-0.082</td><td style="background-color:#F3F3F3; font-weight:bold;">0.400</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13154">정보근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.364</td><td>70</td><td>30</td><td>339.0</td><td>343</td><td>322</td><td>19</td><td>2</td><td>99.4</td><td>9.05</td><td style="">-0.91</td><td></td><td>0.67</td><td></td><td>-0.13</td><td>0.19</td><td>0.85</td><td></td><td>0.41</td><td>0.84</td><td>3.17</td><td>3.58</td><td>0.041</td><td style="background-color:#F3F3F3; font-weight:bold;">0.364</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13155">장두성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.353</td><td>51</td><td>33</td><td>341.0</td><td>105</td><td>103</td><td>1</td><td>1</td><td>99.0</td><td>2.74</td><td style="">3.24</td><td>0.12</td><td>0.12</td><td></td><td></td><td></td><td></td><td></td><td>3.47</td><td>7.04</td><td>0.00</td><td>3.47</td><td>0.353</td><td style="background-color:#F3F3F3; font-weight:bold;">0.353</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15051">한태양</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.245</td><td>30</td><td>20</td><td>178.1</td><td>96</td><td>43</td><td>52</td><td>1</td><td>99.0</td><td>4.79</td><td style="">1.32</td><td></td><td>0.51</td><td>-0.23</td><td></td><td></td><td></td><td></td><td>1.60</td><td>3.83</td><td>0.81</td><td>2.41</td><td>0.162</td><td style="background-color:#F3F3F3; font-weight:bold;">0.245</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15645">김동혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.219</td><td>20</td><td>14</td><td>130.0</td><td>44</td><td>44</td><td>0</td><td>0</td><td>100.0</td><td>3.05</td><td style="">2.38</td><td>-0.47</td><td>0.24</td><td></td><td></td><td></td><td></td><td></td><td>2.15</td><td>4.99</td><td>0.00</td><td>2.15</td><td>0.219</td><td style="background-color:#F3F3F3; font-weight:bold;">0.219</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14160">고승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.208</td><td>13</td><td>10</td><td>88.0</td><td>80</td><td>73</td><td>7</td><td>0</td><td>100.0</td><td>8.18</td><td style="">2.67</td><td></td><td>0.16</td><td></td><td>0.10</td><td></td><td></td><td></td><td>2.93</td><td>5.93</td><td>-0.88</td><td>2.05</td><td>0.298</td><td style="background-color:#F3F3F3; font-weight:bold;">0.208</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15048">윤동희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.184</td><td>51</td><td>43</td><td>391.1</td><td>92</td><td>89</td><td>1</td><td>2</td><td>97.8</td><td>2.07</td><td style="">4.65</td><td>-0.58</td><td>-0.37</td><td></td><td></td><td></td><td></td><td></td><td>3.70</td><td>9.36</td><td>-1.90</td><td>1.80</td><td>0.377</td><td style="background-color:#F3F3F3; font-weight:bold;">0.184</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14590">손호영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.180</td><td>5</td><td>5</td><td>40.0</td><td>27</td><td>12</td><td>15</td><td>0</td><td>100.0</td><td>6.08</td><td style="">1.45</td><td></td><td>0.11</td><td></td><td></td><td></td><td></td><td></td><td>1.57</td><td>4.25</td><td>0.20</td><td>1.77</td><td>0.159</td><td style="background-color:#F3F3F3; font-weight:bold;">0.180</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10253">정훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.174</td><td>26</td><td>16</td><td>158.1</td><td>173</td><td>158</td><td>14</td><td>1</td><td>99.4</td><td>9.78</td><td style="">3.13</td><td></td><td>-0.22</td><td></td><td>0.20</td><td></td><td></td><td></td><td>3.11</td><td>6.89</td><td>-1.40</td><td>1.71</td><td>0.317</td><td style="background-color:#F3F3F3; font-weight:bold;">0.174</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13155">장두성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.170</td><td>11</td><td>8</td><td>77.0</td><td>19</td><td>18</td><td>0</td><td>1</td><td>94.7</td><td>2.10</td><td style="">2.96</td><td>-0.56</td><td>-0.38</td><td></td><td></td><td></td><td></td><td></td><td>2.02</td><td>4.11</td><td>-0.35</td><td>1.67</td><td>0.206</td><td style="background-color:#F3F3F3; font-weight:bold;">0.170</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15645">김동혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.156</td><td>14</td><td>7</td><td>78.0</td><td>25</td><td>22</td><td>3</td><td>0</td><td>100.0</td><td>2.88</td><td style="">0.38</td><td>1.35</td><td>0.13</td><td></td><td></td><td></td><td></td><td></td><td>1.86</td><td>4.33</td><td>-0.33</td><td>1.53</td><td>0.190</td><td style="background-color:#F3F3F3; font-weight:bold;">0.156</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16270">한승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.138</td><td>2</td><td>1</td><td>9.0</td><td>4</td><td>3</td><td>1</td><td>0</td><td>100.0</td><td>4.00</td><td style="">1.13</td><td>0.21</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>1.36</td><td>13.04</td><td>0.00</td><td>1.36</td><td>0.138</td><td style="background-color:#F3F3F3; font-weight:bold;">0.138</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16270">한승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.129</td><td>8</td><td>3</td><td>29.0</td><td>8</td><td>7</td><td>1</td><td>0</td><td>100.0</td><td>2.48</td><td style="">1.16</td><td>0.15</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>1.37</td><td>13.11</td><td>-0.10</td><td>1.27</td><td>0.139</td><td style="background-color:#F3F3F3; font-weight:bold;">0.129</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14796">손성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.125</td><td>20</td><td>2</td><td>56.0</td><td>40</td><td>37</td><td>3</td><td>0</td><td>100.0</td><td>6.43</td><td style="">-0.09</td><td></td><td>0.19</td><td></td><td></td><td>-0.11</td><td>1.08</td><td></td><td>0.75</td><td>5.15</td><td>0.48</td><td>1.23</td><td>0.077</td><td style="background-color:#F3F3F3; font-weight:bold;">0.125</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10804">박승욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.105</td><td>14</td><td>0</td><td>21.0</td><td>16</td><td>5</td><td>11</td><td>0</td><td>100.0</td><td>6.86</td><td style="">0.73</td><td></td><td>0.06</td><td>0.21</td><td></td><td></td><td></td><td></td><td>1.00</td><td>4.37</td><td>0.03</td><td>1.03</td><td>0.102</td><td style="background-color:#F3F3F3; font-weight:bold;">0.105</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10238">김민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.081</td><td>12</td><td>10</td><td>81.0</td><td>39</td><td>17</td><td>22</td><td>0</td><td>100.0</td><td>4.33</td><td style="">0.52</td><td></td><td>0.23</td><td>-0.35</td><td></td><td></td><td></td><td></td><td>0.39</td><td>0.91</td><td>0.40</td><td>0.79</td><td>0.040</td><td style="background-color:#F3F3F3; font-weight:bold;">0.081</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10804">박승욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.069</td><td>5</td><td>0</td><td>10.2</td><td>9</td><td>8</td><td>1</td><td>0</td><td>100.0</td><td>7.59</td><td style="">0.76</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.77</td><td>3.38</td><td>-0.10</td><td>0.67</td><td>0.079</td><td style="background-color:#F3F3F3; font-weight:bold;">0.069</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13155">장두성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.055</td><td>4</td><td>0</td><td>8.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.13</td><td style="">0.56</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.57</td><td>1.16</td><td>-0.03</td><td>0.54</td><td>0.058</td><td style="background-color:#F3F3F3; font-weight:bold;">0.055</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10804">박승욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.050</td><td>5</td><td>2</td><td>19.0</td><td>5</td><td>1</td><td>4</td><td>0</td><td>100.0</td><td>2.37</td><td style="">0.42</td><td></td><td>0.07</td><td>0.00</td><td></td><td></td><td></td><td></td><td>0.49</td><td>2.14</td><td>0.00</td><td>0.49</td><td>0.050</td><td style="background-color:#F3F3F3; font-weight:bold;">0.050</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14160">고승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.040</td><td>2</td><td>1</td><td>9.1</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>3.86</td><td style="">0.54</td><td>-0.11</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.44</td><td>0.89</td><td>-0.05</td><td>0.39</td><td>0.045</td><td style="background-color:#F3F3F3; font-weight:bold;">0.040</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14160">고승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.033</td><td>54</td><td>52</td><td>406.2</td><td>232</td><td>78</td><td>150</td><td>4</td><td>98.3</td><td>5.05</td><td style="">-2.89</td><td></td><td>0.14</td><td>0.72</td><td></td><td></td><td></td><td></td><td>-2.03</td><td>-4.11</td><td>2.35</td><td>0.32</td><td>-0.206</td><td style="background-color:#F3F3F3; font-weight:bold;">0.033</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13073">전민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.031</td><td>4</td><td>2</td><td>19.0</td><td>11</td><td>7</td><td>4</td><td>0</td><td>100.0</td><td>5.21</td><td style="">0.36</td><td></td><td>0.05</td><td>-0.18</td><td></td><td></td><td></td><td></td><td>0.23</td><td>0.44</td><td>0.07</td><td>0.30</td><td>0.024</td><td style="background-color:#F3F3F3; font-weight:bold;">0.031</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16395">박찬형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.029</td><td>8</td><td>7</td><td>63.0</td><td>13</td><td>5</td><td>8</td><td>0</td><td>100.0</td><td>1.86</td><td style="">-0.56</td><td></td><td>0.23</td><td>0.23</td><td>0.39</td><td></td><td></td><td></td><td>0.29</td><td>2.17</td><td>0.00</td><td>0.29</td><td>0.029</td><td style="background-color:#F3F3F3; font-weight:bold;">0.029</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10253">정훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.018</td><td>2</td><td>1</td><td>10.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>1.80</td><td style="">0.08</td><td>0.11</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.20</td><td>0.45</td><td>-0.03</td><td>0.17</td><td>0.021</td><td style="background-color:#F3F3F3; font-weight:bold;">0.018</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15645">김동혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.010</td><td>17</td><td>0</td><td>20.0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>3.15</td><td style="">0.34</td><td>-0.23</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.14</td><td>0.33</td><td>-0.04</td><td>0.10</td><td>0.014</td><td style="background-color:#F3F3F3; font-weight:bold;">0.010</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16091">이호준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.008</td><td>25</td><td>1</td><td>48.1</td><td>23</td><td>7</td><td>16</td><td>0</td><td>100.0</td><td>4.28</td><td style="">0.02</td><td></td><td>0.14</td><td>-0.18</td><td></td><td></td><td></td><td></td><td>-0.02</td><td>-0.04</td><td>0.10</td><td>0.08</td><td>-0.002</td><td style="background-color:#F3F3F3; font-weight:bold;">0.008</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10810">최항</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.000</td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">-0.01</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.01</td><td>-0.15</td><td>0.01</td><td>0.00</td><td>-0.001</td><td style="background-color:#F3F3F3; font-weight:bold;">0.000</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14160">고승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.001</td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.01</td><td>-0.01</td><td>-0.01</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.001</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13073">전민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.018</td><td>69</td><td>65</td><td>540.1</td><td>236</td><td>78</td><td>146</td><td>12</td><td>94.9</td><td>3.73</td><td style="">-4.20</td><td></td><td>-1.57</td><td>0.47</td><td></td><td></td><td></td><td></td><td>-5.30</td><td>-9.91</td><td>5.12</td><td>-0.18</td><td>-0.540</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.018</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16106">레이예스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.020</td><td>56</td><td>46</td><td>404.1</td><td>77</td><td>77</td><td>0</td><td>0</td><td>100.0</td><td>1.71</td><td style="">1.75</td><td>-0.41</td><td>0.54</td><td></td><td></td><td></td><td></td><td></td><td>1.87</td><td>2.89</td><td>-2.07</td><td>-0.20</td><td>0.190</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.020</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14590">손호영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.028</td><td>48</td><td>47</td><td>408.1</td><td>126</td><td>33</td><td>83</td><td>10</td><td>92.1</td><td>2.56</td><td style="">-1.20</td><td></td><td>0.99</td><td>0.09</td><td>-0.15</td><td></td><td></td><td></td><td>-0.27</td><td>-0.74</td><td>0.00</td><td>-0.27</td><td>-0.028</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.028</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16266">박재엽</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.031</td><td>8</td><td>3</td><td>38.0</td><td>42</td><td>40</td><td>1</td><td>1</td><td>97.6</td><td>9.71</td><td style="">-0.09</td><td></td><td>-0.38</td><td></td><td></td><td>0.32</td><td>-0.70</td><td></td><td>-0.64</td><td>-11.52</td><td>0.34</td><td>-0.30</td><td>-0.065</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.031</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10804">박승욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.033</td><td>13</td><td>7</td><td>61.1</td><td>33</td><td>12</td><td>19</td><td>2</td><td>93.9</td><td>4.55</td><td style="">-1.37</td><td></td><td>0.34</td><td>0.25</td><td></td><td></td><td></td><td></td><td>-0.78</td><td>-3.42</td><td>0.46</td><td>-0.32</td><td>-0.080</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.033</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15051">한태양</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.040</td><td>9</td><td>0</td><td>18.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>0.50</td><td style="">-0.46</td><td></td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>-0.39</td><td>-0.94</td><td>0.00</td><td>-0.39</td><td>-0.040</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.040</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15046">조세진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.040</td><td>4</td><td>1</td><td>4.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.63</td><td>0.24</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.39</td><td>-6.18</td><td>-0.01</td><td>-0.40</td><td>-0.039</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.040</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16091">이호준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.050</td><td>35</td><td>19</td><td>196.0</td><td>87</td><td>27</td><td>54</td><td>6</td><td>93.1</td><td>3.72</td><td style="">-1.40</td><td></td><td>-1.45</td><td>0.82</td><td></td><td></td><td></td><td></td><td>-2.03</td><td>-4.88</td><td>1.54</td><td>-0.49</td><td>-0.207</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.050</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16270">한승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.072</td><td>5</td><td>0</td><td>7.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.83</td><td>0.12</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.70</td><td>-6.68</td><td>-0.01</td><td>-0.71</td><td>-0.071</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.072</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15046">조세진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.073</td><td>1</td><td>1</td><td>8.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>4.50</td><td style="">-0.97</td><td>0.24</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.72</td><td>-11.47</td><td>0.00</td><td>-0.72</td><td>-0.073</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.073</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14642">황성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.100</td><td>1</td><td>0</td><td>3.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-0.98</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.98</td><td>-4.13</td><td>-0.01</td><td>-0.99</td><td>-0.099</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.100</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10238">김민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.103</td><td>8</td><td>1</td><td>17.0</td><td>22</td><td>22</td><td>0</td><td>0</td><td>100.0</td><td>11.65</td><td style="">-0.93</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.89</td><td>-2.08</td><td>-0.12</td><td>-1.01</td><td>-0.091</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.103</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15051">한태양</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.104</td><td>5</td><td>1</td><td>14.0</td><td>12</td><td>5</td><td>6</td><td>1</td><td>91.7</td><td>7.07</td><td style="">-0.85</td><td></td><td>0.08</td><td>-0.39</td><td></td><td></td><td></td><td></td><td>-1.16</td><td>-2.79</td><td>0.14</td><td>-1.02</td><td>-0.118</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.104</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15048">윤동희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.113</td><td>12</td><td>11</td><td>74.0</td><td>23</td><td>23</td><td>0</td><td>0</td><td>100.0</td><td>2.80</td><td style="">-0.53</td><td>-0.71</td><td>0.14</td><td></td><td></td><td></td><td></td><td></td><td>-1.11</td><td>-2.80</td><td>0.00</td><td>-1.11</td><td>-0.113</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.113</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14642">황성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.157</td><td>33</td><td>33</td><td>262.2</td><td>56</td><td>52</td><td>2</td><td>2</td><td>96.4</td><td>1.85</td><td style="">-0.92</td><td>-0.08</td><td>-0.53</td><td></td><td></td><td></td><td></td><td></td><td>-1.54</td><td>-6.52</td><td>0.00</td><td>-1.54</td><td>-0.157</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.157</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16395">박찬형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.186</td><td>5</td><td>3</td><td>28.1</td><td>24</td><td>10</td><td>12</td><td>2</td><td>91.7</td><td>6.99</td><td style="">-1.05</td><td></td><td>-0.93</td><td>0.00</td><td></td><td></td><td></td><td></td><td>-1.98</td><td>-15.02</td><td>0.15</td><td>-1.83</td><td>-0.202</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.186</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16395">박찬형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.214</td><td>2</td><td>1</td><td>13.0</td><td>7</td><td>3</td><td>3</td><td>1</td><td>85.7</td><td>4.15</td><td style="">-0.65</td><td></td><td>-0.44</td><td>-1.16</td><td></td><td></td><td></td><td></td><td>-2.24</td><td>-17.00</td><td>0.14</td><td>-2.10</td><td>-0.228</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.214</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16106">레이예스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.267</td><td>30</td><td>30</td><td>236.0</td><td>46</td><td>45</td><td>0</td><td>1</td><td>97.8</td><td>1.72</td><td style="">-1.22</td><td>-0.03</td><td>-0.12</td><td></td><td></td><td></td><td></td><td></td><td>-1.37</td><td>-2.12</td><td>-1.25</td><td>-2.62</td><td>-0.140</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.267</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13073">전민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.268</td><td>7</td><td>5</td><td>48.0</td><td>22</td><td>8</td><td>13</td><td>1</td><td>95.5</td><td>3.94</td><td style="">-2.05</td><td></td><td>-0.33</td><td></td><td>-0.25</td><td></td><td></td><td></td><td>-2.63</td><td>-4.92</td><td>0.00</td><td>-2.63</td><td>-0.268</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.268</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10238">김민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.418</td><td>42</td><td>32</td><td>268.1</td><td>71</td><td>14</td><td>54</td><td>3</td><td>95.8</td><td>2.28</td><td style="">-3.56</td><td></td><td>-0.03</td><td>-0.31</td><td>-0.20</td><td></td><td></td><td></td><td>-4.11</td><td>-9.54</td><td>0.00</td><td>-4.11</td><td>-0.418</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.418</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10266">전준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.705</td><td>47</td><td>46</td><td>368.0</td><td>69</td><td>66</td><td>3</td><td>0</td><td>100.0</td><td>1.69</td><td style="">-5.03</td><td>-0.42</td><td>0.49</td><td></td><td></td><td></td><td></td><td></td><td>-4.96</td><td>-7.77</td><td>-1.96</td><td>-6.92</td><td>-0.505</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.705</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14797">나승엽</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-1.090</td><td>68</td><td>66</td><td>546.2</td><td>535</td><td>494</td><td>35</td><td>6</td><td>98.9</td><td>8.71</td><td style="">-4.96</td><td></td><td>-0.02</td><td></td><td>-0.19</td><td></td><td></td><td></td><td>-5.17</td><td>-10.19</td><td>-5.54</td><td>-10.71</td><td>-0.526</td><td style="background-color:#F3F3F3; font-weight:bold;">-1.090</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16377">이태경</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.33</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13071">정철원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>48</td><td>0</td><td>46.0</td><td>7</td><td>0</td><td>7</td><td>0</td><td>100.0</td><td>1.37</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16090">정현수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>52</td><td>0</td><td>33.1</td><td>4</td><td>1</td><td>3</td><td>0</td><td>100.0</td><td>1.08</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10427">김상수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>42</td><td>0</td><td>35.2</td><td>5</td><td>4</td><td>1</td><td>0</td><td>100.0</td><td>1.26</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10825">김원중</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>36</td><td>0</td><td>38.1</td><td>11</td><td>1</td><td>10</td><td>0</td><td>100.0</td><td>2.58</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14690">이인한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>2.1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.01</td><td>0.09</td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.09</td><td>3.19</td><td></td><td></td><td>0.008</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16092">박준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>7</td><td>0</td><td>5.2</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>1.59</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10810">최항</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>3</td><td>0</td><td>4.0</td><td>5</td><td>2</td><td>2</td><td>1</td><td>80.0</td><td>9.00</td><td style="">0.31</td><td></td><td>-0.50</td><td></td><td>0.10</td><td></td><td></td><td></td><td>-0.09</td><td>-2.73</td><td></td><td></td><td>-0.010</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14163">박진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>27</td><td>2</td><td>37.1</td><td>7</td><td>4</td><td>3</td><td>0</td><td>100.0</td><td>1.69</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11291">구승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">25</span> <span><img src="/data/team/ci/2025/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>8</td><td>0</td><td>6.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>"""
giants_fielding, giants_pids = get_team_stats_from_markup(giants_table)

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

In [ ]:
giants_fielding.shape

(60, 27)

In [ ]:
len(giants_pids)

62

In [ ]:
giants_fielding['pid'] = giants_pids[2:]

In [20]:
team_names = ['한화 이글스', 'LG 트윈스', '롯데 자이언츠', 'KIA 타이거즈', 'KT 위즈', '삼성 라이온즈','SSG 랜더스', 'NC 다이노스', '두산 베어스','키움 히어로즈']
team_tables = []

In [ ]:
team_tables.append("""
<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10170">최재훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.902</td><td>115</td><td>95</td><td>791.2</td><td>811</td><td>746</td><td>60</td><td>5</td><td>99.4</td><td>9.16</td><td style="">0.35</td><td></td><td>0.35</td><td></td><td>0.19</td><td>1.24</td><td>-0.79</td><td></td><td>1.57</td><td>1.95</td><td>8.30</td><td>9.88</td><td>0.144</td><td style="background-color:#F3F3F3; font-weight:bold;">0.902</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11414">이도윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.611</td><td>112</td><td>89</td><td>784.0</td><td>349</td><td>138</td><td>198</td><td>13</td><td>96.3</td><td>3.86</td><td style="">-2.12</td><td></td><td>0.43</td><td>1.70</td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.01</td><td>6.68</td><td>6.69</td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;">0.611</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16110">황영묵</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.453</td><td>82</td><td>54</td><td>518.0</td><td>325</td><td>143</td><td>174</td><td>8</td><td>97.5</td><td>5.51</td><td style="">3.66</td><td></td><td>-0.88</td><td>-0.34</td><td></td><td></td><td></td><td></td><td>2.44</td><td>2.85</td><td>2.52</td><td>4.96</td><td>0.222</td><td style="background-color:#F3F3F3; font-weight:bold;">0.453</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10082">이재원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.277</td><td>71</td><td>40</td><td>354.0</td><td>332</td><td>304</td><td>27</td><td>1</td><td>99.7</td><td>8.42</td><td style="">-0.33</td><td></td><td>0.78</td><td></td><td>-0.17</td><td>0.17</td><td>-1.33</td><td></td><td>-0.49</td><td>-0.99</td><td>3.53</td><td>3.04</td><td>-0.045</td><td style="background-color:#F3F3F3; font-weight:bold;">0.277</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13138">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.272</td><td>40</td><td>22</td><td>219.0</td><td>62</td><td>62</td><td>0</td><td>0</td><td>100.0</td><td>2.55</td><td style="">2.90</td><td>-0.38</td><td>0.46</td><td></td><td></td><td></td><td></td><td></td><td>2.97</td><td>4.92</td><td>0.00</td><td>2.97</td><td>0.272</td><td style="background-color:#F3F3F3; font-weight:bold;">0.272</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14126">유로결</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.208</td><td>11</td><td>1</td><td>33.1</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>1.89</td><td style="">1.79</td><td>0.54</td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>2.43</td><td>15.19</td><td>-0.15</td><td>2.28</td><td>0.222</td><td style="background-color:#F3F3F3; font-weight:bold;">0.208</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10108">김강민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.196</td><td>31</td><td>15</td><td>153.1</td><td>40</td><td>40</td><td>0</td><td>0</td><td>100.0</td><td>2.35</td><td style="">1.45</td><td>0.38</td><td>0.32</td><td></td><td></td><td></td><td></td><td></td><td>2.14</td><td>7.52</td><td>0.00</td><td>2.14</td><td>0.196</td><td style="background-color:#F3F3F3; font-weight:bold;">0.196</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12539">이진영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.170</td><td>27</td><td>15</td><td>131.0</td><td>46</td><td>46</td><td>0</td><td>0</td><td>100.0</td><td>3.16</td><td style="">1.96</td><td>-0.36</td><td>0.27</td><td></td><td></td><td></td><td></td><td></td><td>1.87</td><td>6.40</td><td>0.00</td><td>1.87</td><td>0.170</td><td style="background-color:#F3F3F3; font-weight:bold;">0.170</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10014">안치홍</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.151</td><td>36</td><td>36</td><td>265.0</td><td>168</td><td>67</td><td>99</td><td>2</td><td>98.8</td><td>5.64</td><td style="">-0.47</td><td></td><td>0.60</td><td>0.16</td><td></td><td></td><td></td><td></td><td>0.29</td><td>0.32</td><td>1.37</td><td>1.66</td><td>0.026</td><td style="background-color:#F3F3F3; font-weight:bold;">0.151</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14706">임종찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.126</td><td>13</td><td>1</td><td>33.0</td><td>6</td><td>6</td><td>0</td><td>0</td><td>100.0</td><td>1.64</td><td style="">1.28</td><td>0.12</td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>1.49</td><td>8.96</td><td>-0.11</td><td>1.38</td><td>0.136</td><td style="background-color:#F3F3F3; font-weight:bold;">0.126</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13676">권광민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.124</td><td>2</td><td>0</td><td>7.0</td><td>9</td><td>9</td><td>0</td><td>0</td><td>100.0</td><td>11.57</td><td style="">1.39</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>1.42</td><td>10.78</td><td>-0.06</td><td>1.36</td><td>0.130</td><td style="background-color:#F3F3F3; font-weight:bold;">0.124</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12583">장진혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.111</td><td>15</td><td>2</td><td>48.1</td><td>12</td><td>12</td><td>0</td><td>0</td><td>100.0</td><td>2.23</td><td style="">1.38</td><td>-0.12</td><td>0.15</td><td></td><td></td><td></td><td></td><td></td><td>1.40</td><td>2.04</td><td>-0.19</td><td>1.21</td><td>0.128</td><td style="background-color:#F3F3F3; font-weight:bold;">0.111</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12587">박상언</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.090</td><td>26</td><td>9</td><td>113.0</td><td>97</td><td>91</td><td>5</td><td>1</td><td>99.0</td><td>7.65</td><td style="">-0.15</td><td></td><td>-0.09</td><td></td><td></td><td>-1.29</td><td>1.99</td><td></td><td>-0.14</td><td>-0.76</td><td>1.13</td><td>0.99</td><td>-0.013</td><td style="background-color:#F3F3F3; font-weight:bold;">0.090</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15422">문현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.087</td><td>16</td><td>13</td><td>119.0</td><td>33</td><td>9</td><td>22</td><td>2</td><td>93.9</td><td>2.34</td><td style="">1.31</td><td></td><td>-0.19</td><td>-0.17</td><td></td><td></td><td></td><td></td><td>0.95</td><td>1.33</td><td>0.00</td><td>0.95</td><td>0.087</td><td style="background-color:#F3F3F3; font-weight:bold;">0.087</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13137">정은원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.085</td><td>10</td><td>9</td><td>70.0</td><td>20</td><td>20</td><td>0</td><td>0</td><td>100.0</td><td>2.57</td><td style="">1.18</td><td>-0.02</td><td>0.08</td><td></td><td></td><td></td><td></td><td></td><td>1.24</td><td>6.60</td><td>-0.31</td><td>0.93</td><td>0.113</td><td style="background-color:#F3F3F3; font-weight:bold;">0.085</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16121">페라자</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.071</td><td>2</td><td>1</td><td>9.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>2.00</td><td style="">0.32</td><td>0.44</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.78</td><td>0.92</td><td>0.00</td><td>0.78</td><td>0.071</td><td style="background-color:#F3F3F3; font-weight:bold;">0.071</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14707">최인호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.068</td><td>62</td><td>46</td><td>401.2</td><td>101</td><td>96</td><td>3</td><td>2</td><td>98.0</td><td>2.22</td><td style="">4.12</td><td>-0.77</td><td>-0.55</td><td></td><td></td><td></td><td></td><td></td><td>2.80</td><td>4.92</td><td>-2.06</td><td>0.74</td><td>0.256</td><td style="background-color:#F3F3F3; font-weight:bold;">0.068</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11414">이도윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.058</td><td>21</td><td>8</td><td>93.0</td><td>56</td><td>25</td><td>29</td><td>2</td><td>96.4</td><td>5.23</td><td style="">1.18</td><td></td><td>-0.44</td><td>-0.43</td><td></td><td></td><td></td><td></td><td>0.31</td><td>0.33</td><td>0.33</td><td>0.64</td><td>0.028</td><td style="background-color:#F3F3F3; font-weight:bold;">0.058</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14707">최인호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.036</td><td>4</td><td>4</td><td>35.0</td><td>7</td><td>6</td><td>1</td><td>0</td><td>100.0</td><td>1.80</td><td style="">0.46</td><td>0.01</td><td>0.11</td><td></td><td></td><td></td><td></td><td></td><td>0.58</td><td>1.02</td><td>-0.19</td><td>0.39</td><td>0.053</td><td style="background-color:#F3F3F3; font-weight:bold;">0.036</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14126">유로결</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.022</td><td>7</td><td>3</td><td>30.0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>2.10</td><td style="">0.08</td><td>0.26</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.37</td><td>2.34</td><td>-0.13</td><td>0.24</td><td>0.034</td><td style="background-color:#F3F3F3; font-weight:bold;">0.022</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15633">한경빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.015</td><td>1</td><td>0</td><td>2.0</td><td>2</td><td>1</td><td>1</td><td>0</td><td>100.0</td><td>9.00</td><td style="">-0.13</td><td></td><td>0.02</td><td>0.25</td><td></td><td></td><td></td><td></td><td>0.14</td><td>20.42</td><td>0.02</td><td>0.16</td><td>0.013</td><td style="background-color:#F3F3F3; font-weight:bold;">0.015</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13137">정은원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.009</td><td>6</td><td>6</td><td>46.0</td><td>13</td><td>12</td><td>0</td><td>1</td><td>92.3</td><td>2.35</td><td style="">0.94</td><td>-0.43</td><td>-0.41</td><td></td><td></td><td></td><td></td><td></td><td>0.10</td><td>0.55</td><td>0.00</td><td>0.10</td><td>0.009</td><td style="background-color:#F3F3F3; font-weight:bold;">0.009</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13676">권광민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.005</td><td>1</td><td>1</td><td>8.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.13</td><td style="">-0.17</td><td>0.21</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.05</td><td>0.39</td><td>0.00</td><td>0.05</td><td>0.005</td><td style="background-color:#F3F3F3; font-weight:bold;">0.005</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14126">유로결</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.002</td><td>2</td><td>2</td><td>18.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>1.00</td><td style="">0.08</td><td>-0.10</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>0.02</td><td>0.12</td><td>0.00</td><td>0.02</td><td>0.002</td><td style="background-color:#F3F3F3; font-weight:bold;">0.002</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12539">이진영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.001</td><td>6</td><td>1</td><td>17.2</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>0.51</td><td style="">-0.49</td><td>0.57</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.10</td><td>0.33</td><td>-0.09</td><td>0.01</td><td>0.009</td><td style="background-color:#F3F3F3; font-weight:bold;">0.001</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13676">권광민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.001</td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.02</td><td>-0.01</td><td>-0.01</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.001</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10913">하주석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.001</td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.01</td><td>-0.02</td><td>-0.02</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.001</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13137">정은원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.007</td><td>4</td><td>4</td><td>31.0</td><td>16</td><td>6</td><td>10</td><td>0</td><td>100.0</td><td>4.65</td><td style="">-0.77</td><td></td><td>0.19</td><td>0.36</td><td></td><td></td><td></td><td></td><td>-0.22</td><td>-1.16</td><td>0.14</td><td>-0.08</td><td>-0.020</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.007</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15422">문현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.009</td><td>1</td><td>0</td><td>2.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">-0.14</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.12</td><td>-0.17</td><td>0.02</td><td>-0.10</td><td>-0.011</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.009</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15139">이상혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.011</td><td>4</td><td>0</td><td>7.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.29</td><td style="">-0.11</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.10</td><td>-0.33</td><td>-0.02</td><td>-0.12</td><td>-0.009</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.011</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15139">이상혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.014</td><td>8</td><td>0</td><td>12.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>1.50</td><td style="">-0.20</td><td>0.01</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-0.15</td><td>-0.50</td><td>-0.01</td><td>-0.16</td><td>-0.014</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.014</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14125">노시환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.024</td><td>126</td><td>125</td><td>1098.1</td><td>302</td><td>97</td><td>196</td><td>9</td><td>97.0</td><td>2.40</td><td style="">-3.43</td><td></td><td>3.03</td><td>0.56</td><td>-0.43</td><td></td><td></td><td></td><td>-0.27</td><td>-0.28</td><td>0.00</td><td>-0.27</td><td>-0.024</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.024</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14811">장규현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.028</td><td>9</td><td>0</td><td>16.0</td><td>10</td><td>8</td><td>1</td><td>1</td><td>90.0</td><td>5.06</td><td style="">0.00</td><td></td><td>-0.44</td><td></td><td></td><td>-0.11</td><td>0.13</td><td></td><td>-0.47</td><td>-7.54</td><td>0.17</td><td>-0.30</td><td>-0.043</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.028</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10913">하주석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.035</td><td>42</td><td>26</td><td>221.2</td><td>120</td><td>43</td><td>74</td><td>3</td><td>97.5</td><td>4.75</td><td style="">-3.03</td><td></td><td>0.46</td><td>0.07</td><td></td><td></td><td></td><td></td><td>-2.50</td><td>-5.62</td><td>2.12</td><td>-0.38</td><td>-0.228</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.035</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11215">채은성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.039</td><td>23</td><td>22</td><td>181.0</td><td>40</td><td>40</td><td>0</td><td>0</td><td>100.0</td><td>1.99</td><td style="">0.99</td><td>-1.06</td><td>0.55</td><td></td><td></td><td></td><td></td><td></td><td>0.47</td><td>0.54</td><td>-0.90</td><td>-0.43</td><td>0.043</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.039</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12583">장진혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.047</td><td>19</td><td>8</td><td>86.0</td><td>23</td><td>23</td><td>0</td><td>0</td><td>100.0</td><td>2.41</td><td style="">-0.99</td><td>0.80</td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>-0.09</td><td>-0.13</td><td>-0.42</td><td>-0.51</td><td>-0.008</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.047</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12539">이진영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.051</td><td>13</td><td>5</td><td>55.0</td><td>13</td><td>12</td><td>0</td><td>1</td><td>92.3</td><td>1.96</td><td style="">0.52</td><td>-0.47</td><td>-0.34</td><td></td><td></td><td></td><td></td><td></td><td>-0.29</td><td>-1.00</td><td>-0.26</td><td>-0.55</td><td>-0.027</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.051</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15422">문현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.059</td><td>53</td><td>38</td><td>337.0</td><td>182</td><td>68</td><td>113</td><td>1</td><td>99.5</td><td>4.83</td><td style="">-4.16</td><td></td><td>1.53</td><td>0.31</td><td></td><td></td><td></td><td></td><td>-2.31</td><td>-3.23</td><td>1.67</td><td>-0.64</td><td>-0.211</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.059</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16110">황영묵</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.068</td><td>46</td><td>29</td><td>265.0</td><td>123</td><td>48</td><td>71</td><td>4</td><td>96.7</td><td>4.04</td><td style="">-1.52</td><td></td><td>0.34</td><td>-2.03</td><td></td><td></td><td></td><td></td><td>-3.20</td><td>-3.75</td><td>2.46</td><td>-0.74</td><td>-0.292</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.068</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13676">권광민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.077</td><td>9</td><td>8</td><td>64.0</td><td>18</td><td>18</td><td>0</td><td>0</td><td>100.0</td><td>2.53</td><td style="">-0.67</td><td>0.12</td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>-0.48</td><td>-3.66</td><td>-0.36</td><td>-0.84</td><td>-0.044</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.077</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12583">장진혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.090</td><td>73</td><td>66</td><td>562.1</td><td>144</td><td>142</td><td>1</td><td>1</td><td>99.3</td><td>2.29</td><td style="">-2.07</td><td>0.42</td><td>0.67</td><td></td><td></td><td></td><td></td><td></td><td>-0.98</td><td>-1.43</td><td>0.00</td><td>-0.98</td><td>-0.090</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.090</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15139">이상혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.092</td><td>6</td><td>1</td><td>22.0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>2.86</td><td style="">-0.33</td><td>-0.72</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>-1.01</td><td>-3.38</td><td>0.00</td><td>-1.01</td><td>-0.092</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.092</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13138">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.095</td><td>14</td><td>2</td><td>40.0</td><td>8</td><td>7</td><td>1</td><td>0</td><td>100.0</td><td>1.80</td><td style="">-0.64</td><td>-0.37</td><td>0.12</td><td></td><td></td><td></td><td></td><td></td><td>-0.88</td><td>-1.46</td><td>-0.16</td><td>-1.04</td><td>-0.081</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.095</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14706">임종찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.170</td><td>16</td><td>15</td><td>105.0</td><td>25</td><td>23</td><td>2</td><td>0</td><td>100.0</td><td>2.14</td><td style="">-1.92</td><td>-0.16</td><td>0.22</td><td></td><td></td><td></td><td></td><td></td><td>-1.86</td><td>-11.17</td><td>0.00</td><td>-1.86</td><td>-0.170</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.170</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13138">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.184</td><td>21</td><td>4</td><td>77.2</td><td>12</td><td>11</td><td>0</td><td>1</td><td>91.7</td><td>1.27</td><td style="">-1.36</td><td>0.07</td><td>-0.41</td><td></td><td></td><td></td><td></td><td></td><td>-1.70</td><td>-2.82</td><td>-0.31</td><td>-2.01</td><td>-0.156</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.184</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12589">김인환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.188</td><td>14</td><td>7</td><td>66.0</td><td>55</td><td>50</td><td>3</td><td>2</td><td>96.4</td><td>7.23</td><td style="">-0.81</td><td></td><td>-0.68</td><td></td><td>0.06</td><td></td><td></td><td></td><td>-1.43</td><td>-4.05</td><td>-0.62</td><td>-2.05</td><td>-0.131</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.188</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10913">하주석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.216</td><td>8</td><td>6</td><td>52.1</td><td>19</td><td>7</td><td>8</td><td>4</td><td>78.9</td><td>2.58</td><td style="">-0.39</td><td></td><td>-1.65</td><td>-0.39</td><td>0.07</td><td></td><td></td><td></td><td>-2.36</td><td>-5.31</td><td>0.00</td><td>-2.36</td><td>-0.216</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.216</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12585">김태연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.244</td><td>6</td><td>4</td><td>30.2</td><td>21</td><td>10</td><td>9</td><td>2</td><td>90.5</td><td>5.58</td><td style="">-1.94</td><td></td><td>-0.82</td><td>-0.07</td><td></td><td></td><td></td><td></td><td>-2.82</td><td>-3.22</td><td>0.15</td><td>-2.67</td><td>-0.258</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.244</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16121">페라자</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.245</td><td>39</td><td>39</td><td>310.0</td><td>82</td><td>72</td><td>3</td><td>7</td><td>91.5</td><td>2.18</td><td style="">2.01</td><td>-0.40</td><td>-2.58</td><td></td><td></td><td></td><td></td><td></td><td>-0.96</td><td>-1.14</td><td>-1.72</td><td>-2.68</td><td>-0.088</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.245</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16121">페라자</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.366</td><td>54</td><td>42</td><td>349.1</td><td>80</td><td>75</td><td>3</td><td>2</td><td>97.5</td><td>2.01</td><td style="">-0.86</td><td>-0.71</td><td>-0.61</td><td></td><td></td><td></td><td></td><td></td><td>-2.18</td><td>-2.57</td><td>-1.83</td><td>-4.01</td><td>-0.199</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.366</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12589">김인환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.396</td><td>27</td><td>23</td><td>170.1</td><td>40</td><td>39</td><td>1</td><td>0</td><td>100.0</td><td>2.11</td><td style="">-4.10</td><td>0.50</td><td>0.19</td><td></td><td></td><td></td><td></td><td></td><td>-3.41</td><td>-9.63</td><td>-0.92</td><td>-4.33</td><td>-0.312</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.396</td></tr><tr><td style="text-align:center;">52</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12585">김태연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.572</td><td>49</td><td>30</td><td>306.1</td><td>284</td><td>253</td><td>26</td><td>5</td><td>98.2</td><td>8.20</td><td style="">-2.39</td><td></td><td>-0.99</td><td></td><td>0.06</td><td></td><td></td><td></td><td>-3.33</td><td>-3.80</td><td>-2.94</td><td>-6.27</td><td>-0.304</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.572</td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10014">안치홍</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.589</td><td>37</td><td>34</td><td>293.0</td><td>268</td><td>240</td><td>24</td><td>4</td><td>98.5</td><td>8.11</td><td style="">-2.95</td><td></td><td>-0.56</td><td></td><td>0.06</td><td></td><td></td><td></td><td>-3.45</td><td>-3.88</td><td>-3.00</td><td>-6.45</td><td>-0.315</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.589</td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12585">김태연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.659</td><td>69</td><td>68</td><td>526.0</td><td>87</td><td>81</td><td>4</td><td>2</td><td>97.7</td><td>1.45</td><td style="">-4.37</td><td>-0.66</td><td>0.59</td><td></td><td></td><td></td><td></td><td></td><td>-4.45</td><td>-5.09</td><td>-2.76</td><td>-7.21</td><td>-0.407</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.659</td></tr><tr><td style="text-align:center;">55</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11215">채은성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.850</td><td>75</td><td>73</td><td>601.1</td><td>578</td><td>548</td><td>23</td><td>7</td><td>98.8</td><td>8.55</td><td style="">-2.79</td><td></td><td>-0.54</td><td></td><td>0.00</td><td></td><td></td><td></td><td>-3.33</td><td>-3.86</td><td>-5.98</td><td>-9.31</td><td>-0.304</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.850</td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10119">이명기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.04</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15421">김서현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>37</td><td>0</td><td>38.1</td><td>5</td><td>0</td><td>5</td><td>0</td><td>100.0</td><td>1.17</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10610">장민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>26</td><td>0</td><td>29.0</td><td>2</td><td>1</td><td>1</td><td>0</td><td>100.0</td><td>0.62</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16110">황영묵</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>3</td><td>0</td><td>3.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>3.00</td><td style="">0.62</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.64</td><td>0.74</td><td></td><td></td><td>0.058</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10119">이명기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.07</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12871">박상원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>64</td><td>0</td><td>66.2</td><td>6</td><td>2</td><td>3</td><td>1</td><td>83.3</td><td>0.68</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11415">주현상</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>62</td><td>0</td><td>71.1</td><td>12</td><td>2</td><td>10</td><td>0</td><td>100.0</td><td>1.51</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11414">이도윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.56</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.54</td><td>-0.58</td><td></td><td></td><td>-0.050</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>
""")

In [ ]:
team_tables.append("""
<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10387">박동원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.975</td><td>124</td><td>109</td><td>944.2</td><td>890</td><td>809</td><td>77</td><td>4</td><td>99.6</td><td>8.44</td><td style="">1.14</td><td></td><td>1.40</td><td></td><td>0.07</td><td>2.15</td><td>8.55</td><td></td><td>10.75</td><td>11.91</td><td>10.87</td><td>21.62</td><td>0.982</td><td style="background-color:#F3F3F3; font-weight:bold;">1.975</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10475">오지환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.027</td><td>107</td><td>97</td><td>858.0</td><td>400</td><td>150</td><td>238</td><td>12</td><td>97.0</td><td>4.07</td><td style="">1.33</td><td></td><td>1.59</td><td>-0.02</td><td></td><td></td><td></td><td></td><td>2.90</td><td>3.86</td><td>8.34</td><td>11.24</td><td>0.265</td><td style="background-color:#F3F3F3; font-weight:bold;">1.027</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11190">박해민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.614</td><td>143</td><td>128</td><td>1127.0</td><td>286</td><td>283</td><td>2</td><td>1</td><td>99.7</td><td>2.28</td><td style="">4.18</td><td>0.71</td><td>1.84</td><td></td><td></td><td></td><td></td><td></td><td>6.72</td><td>6.72</td><td>0.00</td><td>6.72</td><td>0.614</td><td style="background-color:#F3F3F3; font-weight:bold;">0.614</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14140">구본혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.465</td><td>57</td><td>21</td><td>247.0</td><td>79</td><td>21</td><td>55</td><td>3</td><td>96.2</td><td>2.77</td><td style="">4.00</td><td></td><td>0.19</td><td>0.97</td><td>-0.07</td><td></td><td></td><td></td><td>5.09</td><td>5.51</td><td>0.00</td><td>5.09</td><td>0.465</td><td style="background-color:#F3F3F3; font-weight:bold;">0.465</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14140">구본혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.454</td><td>43</td><td>29</td><td>268.0</td><td>160</td><td>65</td><td>93</td><td>2</td><td>98.8</td><td>5.31</td><td style="">2.25</td><td></td><td>0.62</td><td>0.97</td><td></td><td></td><td></td><td></td><td>3.84</td><td>4.15</td><td>1.13</td><td>4.97</td><td>0.351</td><td style="background-color:#F3F3F3; font-weight:bold;">0.454</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14187">최승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.215</td><td>21</td><td>0</td><td>37.0</td><td>14</td><td>13</td><td>1</td><td>0</td><td>100.0</td><td>3.41</td><td style="">2.33</td><td>0.08</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>2.46</td><td>6.21</td><td>-0.10</td><td>2.36</td><td>0.224</td><td style="background-color:#F3F3F3; font-weight:bold;">0.215</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13112">문성주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.186</td><td>62</td><td>51</td><td>445.0</td><td>118</td><td>114</td><td>4</td><td>0</td><td>100.0</td><td>2.39</td><td style="">3.41</td><td>0.42</td><td>0.51</td><td></td><td></td><td></td><td></td><td></td><td>4.34</td><td>6.51</td><td>-2.30</td><td>2.04</td><td>0.396</td><td style="background-color:#F3F3F3; font-weight:bold;">0.186</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11347">안익훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.183</td><td>5</td><td>2</td><td>24.0</td><td>10</td><td>10</td><td>0</td><td>0</td><td>100.0</td><td>3.75</td><td style="">1.90</td><td>0.06</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>2.00</td><td>7.79</td><td>0.00</td><td>2.00</td><td>0.183</td><td style="background-color:#F3F3F3; font-weight:bold;">0.183</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12545">김주성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.138</td><td>5</td><td>1</td><td>14.0</td><td>6</td><td>0</td><td>6</td><td>0</td><td>100.0</td><td>3.86</td><td style="">1.42</td><td></td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>1.51</td><td>18.16</td><td>0.00</td><td>1.51</td><td>0.138</td><td style="background-color:#F3F3F3; font-weight:bold;">0.138</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14783">이영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.119</td><td>5</td><td>2</td><td>19.0</td><td>13</td><td>5</td><td>8</td><td>0</td><td>100.0</td><td>6.16</td><td style="">1.35</td><td></td><td>0.11</td><td>-0.25</td><td></td><td></td><td></td><td></td><td>1.21</td><td>5.64</td><td>0.09</td><td>1.30</td><td>0.111</td><td style="background-color:#F3F3F3; font-weight:bold;">0.119</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15084">최원영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.114</td><td>17</td><td>2</td><td>41.0</td><td>12</td><td>12</td><td>0</td><td>0</td><td>100.0</td><td>2.63</td><td style="">1.38</td><td>-0.18</td><td>0.12</td><td></td><td></td><td></td><td></td><td></td><td>1.32</td><td>3.34</td><td>-0.08</td><td>1.24</td><td>0.121</td><td style="background-color:#F3F3F3; font-weight:bold;">0.114</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11347">안익훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.104</td><td>24</td><td>6</td><td>92.0</td><td>20</td><td>20</td><td>0</td><td>0</td><td>100.0</td><td>1.96</td><td style="">1.51</td><td>-0.17</td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>1.44</td><td>5.60</td><td>-0.30</td><td>1.14</td><td>0.132</td><td style="background-color:#F3F3F3; font-weight:bold;">0.104</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14783">이영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.087</td><td>6</td><td>2</td><td>25.0</td><td>9</td><td>5</td><td>4</td><td>0</td><td>100.0</td><td>3.24</td><td style="">0.45</td><td></td><td>0.22</td><td>0.08</td><td></td><td></td><td></td><td></td><td>0.75</td><td>3.49</td><td>0.20</td><td>0.95</td><td>0.069</td><td style="background-color:#F3F3F3; font-weight:bold;">0.087</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14783">이영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.083</td><td>1</td><td>1</td><td>5.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.80</td><td style="">0.83</td><td>0.10</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.94</td><td>4.38</td><td>-0.03</td><td>0.91</td><td>0.086</td><td style="background-color:#F3F3F3; font-weight:bold;">0.083</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11347">안익훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.082</td><td>4</td><td>1</td><td>14.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>3.21</td><td style="">0.72</td><td>0.18</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>0.94</td><td>3.67</td><td>-0.05</td><td>0.89</td><td>0.086</td><td style="background-color:#F3F3F3; font-weight:bold;">0.082</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16013">김현종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.081</td><td>6</td><td>0</td><td>17.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>2.65</td><td style="">0.88</td><td>-0.03</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>0.89</td><td>7.51</td><td>0.00</td><td>0.89</td><td>0.081</td><td style="background-color:#F3F3F3; font-weight:bold;">0.081</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12546">홍창기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.074</td><td>127</td><td>120</td><td>1037.0</td><td>274</td><td>257</td><td>7</td><td>10</td><td>96.4</td><td>2.29</td><td style="">7.65</td><td>0.69</td><td>-1.89</td><td></td><td></td><td></td><td></td><td></td><td>6.46</td><td>6.69</td><td>-5.65</td><td>0.81</td><td>0.590</td><td style="background-color:#F3F3F3; font-weight:bold;">0.074</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13112">문성주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.060</td><td>25</td><td>17</td><td>137.0</td><td>33</td><td>31</td><td>1</td><td>1</td><td>97.0</td><td>2.10</td><td style="">1.06</td><td>0.40</td><td>-0.09</td><td></td><td></td><td></td><td></td><td></td><td>1.37</td><td>2.05</td><td>-0.71</td><td>0.66</td><td>0.125</td><td style="background-color:#F3F3F3; font-weight:bold;">0.060</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13112">문성주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.046</td><td>1</td><td>0</td><td>2.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>4.50</td><td style="">0.50</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.51</td><td>0.76</td><td>0.00</td><td>0.51</td><td>0.046</td><td style="background-color:#F3F3F3; font-weight:bold;">0.046</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12931">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.025</td><td>9</td><td>2</td><td>29.0</td><td>8</td><td>2</td><td>6</td><td>0</td><td>100.0</td><td>2.48</td><td style="">0.11</td><td></td><td>0.20</td><td>-0.10</td><td>0.07</td><td></td><td></td><td></td><td>0.28</td><td>2.11</td><td>0.00</td><td>0.28</td><td>0.025</td><td style="background-color:#F3F3F3; font-weight:bold;">0.025</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13056">신민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.020</td><td>1</td><td>0</td><td>3.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.23</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.23</td><td>0.26</td><td>-0.02</td><td>0.21</td><td>0.021</td><td style="background-color:#F3F3F3; font-weight:bold;">0.020</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16013">김현종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.010</td><td>1</td><td>0</td><td>3.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.01</td><td>0.12</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.12</td><td>1.02</td><td>-0.01</td><td>0.11</td><td>0.011</td><td style="background-color:#F3F3F3; font-weight:bold;">0.010</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13056">신민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.006</td><td>124</td><td>113</td><td>984.0</td><td>567</td><td>257</td><td>299</td><td>11</td><td>98.1</td><td>5.09</td><td style="">-3.91</td><td></td><td>0.43</td><td>-1.05</td><td></td><td></td><td></td><td></td><td>-4.53</td><td>-5.10</td><td>4.60</td><td>0.07</td><td>-0.414</td><td style="background-color:#F3F3F3; font-weight:bold;">0.006</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14680">함창건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.001</td><td>4</td><td>3</td><td>21.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>2.14</td><td style="">0.11</td><td>-0.05</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.08</td><td>0.77</td><td>-0.07</td><td>0.01</td><td>0.007</td><td style="background-color:#F3F3F3; font-weight:bold;">0.001</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14140">구본혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.001</td><td>54</td><td>43</td><td>368.0</td><td>161</td><td>59</td><td>97</td><td>5</td><td>96.9</td><td>3.82</td><td style="">-3.12</td><td></td><td>0.75</td><td>-0.97</td><td></td><td></td><td></td><td></td><td>-3.33</td><td>-3.61</td><td>3.34</td><td>0.01</td><td>-0.304</td><td style="background-color:#F3F3F3; font-weight:bold;">0.001</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14141">김성진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.001</td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.07</td><td>0.00</td><td>0.01</td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;">0.001</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13009">백승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.000</td><td>33</td><td>0</td><td>26.2</td><td>6</td><td>0</td><td>5</td><td>1</td><td>83.3</td><td>1.69</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">0.000</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14136">정우영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.000</td><td>27</td><td>0</td><td>22.2</td><td>7</td><td>0</td><td>7</td><td>0</td><td>100.0</td><td>2.78</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">0.000</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16013">김현종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.001</td><td>4</td><td>0</td><td>5.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.05</td><td>-0.02</td><td>-0.01</td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.001</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15084">최원영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.011</td><td>14</td><td>5</td><td>45.0</td><td>10</td><td>9</td><td>0</td><td>1</td><td>90.0</td><td>1.80</td><td style="">0.65</td><td>-0.36</td><td>-0.41</td><td></td><td></td><td></td><td></td><td></td><td>-0.12</td><td>-0.29</td><td>0.00</td><td>-0.12</td><td>-0.011</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.011</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13109">송찬의</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.013</td><td>3</td><td>2</td><td>17.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>2.12</td><td style="">0.24</td><td>-0.34</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.08</td><td>-1.17</td><td>-0.06</td><td>-0.14</td><td>-0.007</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.013</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14187">최승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.030</td><td>8</td><td>1</td><td>17.0</td><td>6</td><td>5</td><td>1</td><td>0</td><td>100.0</td><td>3.18</td><td style="">-1.11</td><td>0.77</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>-0.29</td><td>-0.73</td><td>-0.04</td><td>-0.33</td><td>-0.027</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.030</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10187">김현수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.037</td><td>7</td><td>0</td><td>11.0</td><td>8</td><td>8</td><td>0</td><td>0</td><td>100.0</td><td>6.55</td><td style="">-0.34</td><td></td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>-0.28</td><td>-0.30</td><td>-0.12</td><td>-0.40</td><td>-0.026</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.037</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12931">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.040</td><td>4</td><td>0</td><td>12.0</td><td>14</td><td>7</td><td>6</td><td>1</td><td>92.9</td><td>9.75</td><td style="">-1.36</td><td></td><td>-0.40</td><td>1.20</td><td></td><td></td><td></td><td></td><td>-0.56</td><td>-4.23</td><td>0.12</td><td>-0.44</td><td>-0.051</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.040</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15484">김범석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.051</td><td>13</td><td>5</td><td>47.1</td><td>50</td><td>45</td><td>5</td><td>0</td><td>100.0</td><td>9.51</td><td style="">-0.09</td><td></td><td>0.17</td><td></td><td></td><td>-0.26</td><td>-1.26</td><td></td><td>-1.06</td><td>-2.19</td><td>0.50</td><td>-0.56</td><td>-0.097</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.051</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16026">최명경</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.056</td><td>1</td><td>0</td><td>6.0</td><td>2</td><td>1</td><td>1</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-0.41</td><td></td><td>0.04</td><td>-0.24</td><td></td><td></td><td></td><td></td><td>-0.61</td><td>-87.82</td><td>0.00</td><td>-0.61</td><td>-0.056</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.056</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14675">김수인</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.071</td><td>2</td><td>0</td><td>4.0</td><td>5</td><td>1</td><td>3</td><td>1</td><td>80.0</td><td>9.00</td><td style="">-0.65</td><td></td><td>-0.48</td><td>0.33</td><td></td><td></td><td></td><td></td><td>-0.80</td><td>-28.79</td><td>0.02</td><td>-0.78</td><td>-0.073</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.071</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12545">김주성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.073</td><td>5</td><td>2</td><td>14.0</td><td>4</td><td>2</td><td>1</td><td>1</td><td>75.0</td><td>1.93</td><td style="">-0.23</td><td></td><td>-0.38</td><td>-0.28</td><td></td><td></td><td></td><td></td><td>-0.89</td><td>-10.73</td><td>0.10</td><td>-0.79</td><td>-0.082</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.073</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14137">문보경</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.074</td><td>52</td><td>12</td><td>180.0</td><td>165</td><td>146</td><td>16</td><td>3</td><td>98.2</td><td>8.10</td><td style="">1.12</td><td></td><td>-0.62</td><td></td><td>0.19</td><td></td><td></td><td></td><td>0.70</td><td>0.70</td><td>-1.50</td><td>-0.80</td><td>0.064</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.074</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15081">이주헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.077</td><td>3</td><td>1</td><td>14.0</td><td>20</td><td>20</td><td>0</td><td>0</td><td>100.0</td><td>12.86</td><td style="">0.00</td><td></td><td>0.05</td><td></td><td></td><td>-0.42</td><td>-0.88</td><td></td><td>-0.99</td><td>-47.48</td><td>0.14</td><td>-0.85</td><td>-0.090</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.077</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14141">김성진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.079</td><td>8</td><td>2</td><td>14.2</td><td>9</td><td>9</td><td>0</td><td>0</td><td>100.0</td><td>5.52</td><td style="">-0.84</td><td></td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>-0.77</td><td>-7.89</td><td>-0.10</td><td>-0.87</td><td>-0.070</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.079</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12546">홍창기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.100</td><td>12</td><td>9</td><td>61.0</td><td>14</td><td>14</td><td>0</td><td>0</td><td>100.0</td><td>2.07</td><td style="">-1.26</td><td>0.04</td><td>0.13</td><td></td><td></td><td></td><td></td><td></td><td>-1.09</td><td>-1.13</td><td>0.00</td><td>-1.09</td><td>-0.100</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.100</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12931">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.116</td><td>6</td><td>2</td><td>15.0</td><td>13</td><td>12</td><td>0</td><td>1</td><td>92.3</td><td>7.20</td><td style="">-0.72</td><td></td><td>-0.43</td><td></td><td></td><td></td><td></td><td></td><td>-1.15</td><td>-8.72</td><td>-0.12</td><td>-1.27</td><td>-0.105</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.116</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14590">손호영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.117</td><td>1</td><td>0</td><td>3.0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0.0</td><td>0.00</td><td style="">-0.80</td><td></td><td>-0.48</td><td></td><td></td><td></td><td></td><td></td><td>-1.28</td><td>-1.81</td><td>0.00</td><td>-1.28</td><td>-0.117</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.117</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15484">김범석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.119</td><td>26</td><td>16</td><td>131.1</td><td>129</td><td>117</td><td>9</td><td>3</td><td>97.7</td><td>8.63</td><td style="">0.54</td><td></td><td>-0.86</td><td></td><td>0.23</td><td></td><td></td><td></td><td>-0.08</td><td>-0.17</td><td>-1.22</td><td>-1.30</td><td>-0.008</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.119</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15084">최원영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.121</td><td>19</td><td>1</td><td>46.0</td><td>8</td><td>7</td><td>0</td><td>1</td><td>87.5</td><td>1.37</td><td style="">-0.60</td><td>-0.14</td><td>-0.45</td><td></td><td></td><td></td><td></td><td></td><td>-1.18</td><td>-2.99</td><td>-0.14</td><td>-1.32</td><td>-0.108</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.121</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14783">이영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.124</td><td>4</td><td>3</td><td>26.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>1.38</td><td style="">-0.91</td><td>-0.39</td><td>0.08</td><td></td><td></td><td></td><td></td><td></td><td>-1.22</td><td>-5.69</td><td>-0.13</td><td>-1.35</td><td>-0.112</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.124</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15085">김성우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.130</td><td>4</td><td>2</td><td>16.0</td><td>8</td><td>7</td><td>1</td><td>0</td><td>100.0</td><td>4.50</td><td style="">-0.09</td><td></td><td>0.06</td><td></td><td>0.05</td><td>-0.30</td><td>-1.75</td><td></td><td>-1.52</td><td>-54.61</td><td>0.10</td><td>-1.42</td><td>-0.139</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.130</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14137">문보경</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.150</td><td>129</td><td>120</td><td>975.0</td><td>285</td><td>89</td><td>186</td><td>10</td><td>96.5</td><td>2.54</td><td style="">-2.43</td><td></td><td>1.68</td><td>-0.63</td><td>-0.25</td><td></td><td></td><td></td><td>-1.64</td><td>-1.64</td><td>0.00</td><td>-1.64</td><td>-0.150</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.150</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10684">허도환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.195</td><td>58</td><td>27</td><td>250.0</td><td>229</td><td>219</td><td>8</td><td>2</td><td>99.1</td><td>8.17</td><td style="">-0.24</td><td></td><td>-0.10</td><td></td><td></td><td>-1.17</td><td>-4.38</td><td></td><td>-4.58</td><td>-11.18</td><td>2.45</td><td>-2.13</td><td>-0.418</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.195</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14783">이영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.307</td><td>12</td><td>7</td><td>62.0</td><td>62</td><td>56</td><td>5</td><td>1</td><td>98.4</td><td>8.85</td><td style="">-1.94</td><td></td><td>-0.20</td><td></td><td>-0.66</td><td></td><td></td><td></td><td>-2.80</td><td>-13.00</td><td>-0.56</td><td>-3.36</td><td>-0.256</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.307</td></tr><tr><td style="text-align:center;">52</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10187">김현수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.700</td><td>84</td><td>80</td><td>606.0</td><td>119</td><td>115</td><td>4</td><td>0</td><td>100.0</td><td>1.77</td><td style="">-3.75</td><td>-1.32</td><td>0.69</td><td></td><td></td><td></td><td></td><td></td><td>-4.38</td><td>-4.61</td><td>-3.28</td><td>-7.66</td><td>-0.400</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.700</td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15532">오스틴</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.700</td><td>106</td><td>105</td><td>863.0</td><td>810</td><td>728</td><td>74</td><td>8</td><td>99.0</td><td>8.36</td><td style="">1.30</td><td></td><td>0.25</td><td></td><td>-0.01</td><td></td><td></td><td></td><td>1.54</td><td>1.58</td><td>-9.20</td><td>-7.66</td><td>0.141</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.700</td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16016">김대원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>2</td><td>1</td><td>1</td><td>0</td><td>100.0</td><td>18.00</td><td style="">-0.20</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.20</td><td>-1.50</td><td></td><td></td><td>-0.018</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12532">김대현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>35</td><td>0</td><td>35.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>0.26</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14669">유영찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>61</td><td>0</td><td>63.2</td><td>8</td><td>4</td><td>4</td><td>0</td><td>100.0</td><td>1.13</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14143">이지강</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>44</td><td>2</td><td>53.2</td><td>10</td><td>4</td><td>6</td><td>0</td><td>100.0</td><td>1.68</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11094">함덕주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>14</td><td>0</td><td>11.2</td><td>3</td><td>0</td><td>3</td><td>0</td><td>100.0</td><td>2.31</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14783">이영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>18.00</td><td style="">0.87</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.87</td><td>4.06</td><td></td><td></td><td>0.080</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11229">김유영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>52</td><td>2</td><td>47.2</td><td>9</td><td>0</td><td>6</td><td>3</td><td>66.7</td><td>1.13</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14680">함창건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.06</td><td></td><td></td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16015">진우영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>6</td><td>0</td><td>7.2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10535">최동환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>25</td><td>0</td><td>22.0</td><td>7</td><td>4</td><td>3</td><td>0</td><td>100.0</td><td>2.86</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12931">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.10</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.09</td><td>-0.69</td><td></td><td></td><td>-0.008</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14651">이종준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>26</td><td>0</td><td>26.0</td><td>3</td><td>1</td><td>2</td><td>0</td><td>100.0</td><td>1.04</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15486">박명근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>30</td><td>0</td><td>25.1</td><td>2</td><td>0</td><td>2</td><td>0</td><td>100.0</td><td>0.71</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11166">김진성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>70</td><td>0</td><td>70.1</td><td>10</td><td>4</td><td>5</td><td>1</td><td>90.0</td><td>1.15</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14142">임준형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>17</td><td>1</td><td>13.2</td><td>2</td><td>1</td><td>1</td><td>0</td><td>100.0</td><td>1.32</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14675">김수인</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.34</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.32</td><td>-11.65</td><td></td><td></td><td>-0.030</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12864">전준호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>3</td><td>0</td><td>5.0</td><td>5</td><td>4</td><td>1</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.33</td><td></td><td>0.02</td><td></td><td></td><td></td><td>-0.27</td><td></td><td>0.16</td><td>7.49</td><td></td><td></td><td>0.014</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13102">김영준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>14</td><td>0</td><td>15.1</td><td>3</td><td>1</td><td>2</td><td>0</td><td>100.0</td><td>1.76</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10753">유강남</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.500</td><td>50</td><td>42</td><td>324.2</td><td>303</td><td>277</td><td>23</td><td>3</td><td>99.0</td><td>8.32</td><td style="">0.59</td><td></td><td>-0.33</td><td></td><td></td><td>1.00</td><td>0.89</td><td></td><td>1.88</td><td>5.20</td><td>3.60</td><td>5.48</td><td>0.171</td><td style="background-color:#F3F3F3; font-weight:bold;">0.500</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14160">고승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.416</td><td>104</td><td>99</td><td>840.0</td><td>494</td><td>206</td><td>275</td><td>13</td><td>97.4</td><td>5.15</td><td style="">1.94</td><td></td><td>-1.45</td><td>-0.43</td><td></td><td></td><td></td><td></td><td>0.06</td><td>0.07</td><td>4.49</td><td>4.55</td><td>0.005</td><td style="background-color:#F3F3F3; font-weight:bold;">0.416</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15048">윤동희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.380</td><td>88</td><td>81</td><td>696.2</td><td>210</td><td>204</td><td>2</td><td>4</td><td>98.1</td><td>2.66</td><td style="">4.45</td><td>0.26</td><td>-0.56</td><td></td><td></td><td></td><td></td><td></td><td>4.16</td><td>4.25</td><td>0.00</td><td>4.16</td><td>0.380</td><td style="background-color:#F3F3F3; font-weight:bold;">0.380</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10810">최항</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.365</td><td>42</td><td>21</td><td>216.1</td><td>130</td><td>45</td><td>84</td><td>1</td><td>99.2</td><td>5.37</td><td style="">2.30</td><td></td><td>0.81</td><td>-0.08</td><td></td><td></td><td></td><td></td><td>3.03</td><td>6.05</td><td>0.97</td><td>4.00</td><td>0.277</td><td style="background-color:#F3F3F3; font-weight:bold;">0.365</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14169">신윤후</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.363</td><td>25</td><td>6</td><td>84.0</td><td>26</td><td>22</td><td>4</td><td>0</td><td>100.0</td><td>2.79</td><td style="">2.53</td><td>1.46</td><td>0.25</td><td></td><td></td><td></td><td></td><td></td><td>4.25</td><td>15.68</td><td>-0.27</td><td>3.98</td><td>0.388</td><td style="background-color:#F3F3F3; font-weight:bold;">0.363</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13154">정보근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.291</td><td>89</td><td>42</td><td>379.1</td><td>373</td><td>335</td><td>34</td><td>4</td><td>98.9</td><td>8.75</td><td style="">0.41</td><td></td><td>-0.64</td><td></td><td>0.03</td><td>0.39</td><td>-0.49</td><td></td><td>-0.15</td><td>-0.25</td><td>3.34</td><td>3.18</td><td>-0.014</td><td style="background-color:#F3F3F3; font-weight:bold;">0.291</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14796">손성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.228</td><td>86</td><td>52</td><td>445.2</td><td>443</td><td>414</td><td>25</td><td>4</td><td>99.1</td><td>8.87</td><td style="">-1.00</td><td></td><td>-0.40</td><td></td><td>0.22</td><td>-1.43</td><td>1.43</td><td></td><td>-1.61</td><td>-2.70</td><td>4.10</td><td>2.49</td><td>-0.147</td><td style="background-color:#F3F3F3; font-weight:bold;">0.228</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11165">노진혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.212</td><td>18</td><td>10</td><td>97.2</td><td>33</td><td>8</td><td>23</td><td>2</td><td>93.9</td><td>2.86</td><td style="">1.81</td><td></td><td>-0.33</td><td>0.84</td><td></td><td></td><td></td><td></td><td>2.32</td><td>4.57</td><td>0.00</td><td>2.32</td><td>0.212</td><td style="background-color:#F3F3F3; font-weight:bold;">0.212</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14642">황성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.131</td><td>56</td><td>27</td><td>291.2</td><td>62</td><td>58</td><td>2</td><td>2</td><td>96.8</td><td>1.85</td><td style="">4.01</td><td>-0.55</td><td>-0.67</td><td></td><td></td><td></td><td></td><td></td><td>2.79</td><td>3.21</td><td>-1.36</td><td>1.43</td><td>0.255</td><td style="background-color:#F3F3F3; font-weight:bold;">0.131</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13155">장두성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.108</td><td>23</td><td>2</td><td>50.1</td><td>17</td><td>17</td><td>0</td><td>0</td><td>100.0</td><td>3.04</td><td style="">0.97</td><td>0.11</td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>1.18</td><td>2.40</td><td>0.00</td><td>1.18</td><td>0.108</td><td style="background-color:#F3F3F3; font-weight:bold;">0.108</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15443">정대선</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.093</td><td>2</td><td>0</td><td>4.0</td><td>5</td><td>2</td><td>3</td><td>0</td><td>100.0</td><td>11.25</td><td style="">0.62</td><td></td><td>0.02</td><td>0.37</td><td></td><td></td><td></td><td></td><td>1.01</td><td>48.62</td><td>0.01</td><td>1.02</td><td>0.093</td><td style="background-color:#F3F3F3; font-weight:bold;">0.093</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16091">이호준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.080</td><td>4</td><td>0</td><td>7.2</td><td>3</td><td>0</td><td>3</td><td>0</td><td>100.0</td><td>3.52</td><td style="">0.77</td><td></td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>0.84</td><td>10.08</td><td>0.04</td><td>0.88</td><td>0.077</td><td style="background-color:#F3F3F3; font-weight:bold;">0.080</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14590">손호영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.078</td><td>20</td><td>15</td><td>110.1</td><td>58</td><td>24</td><td>34</td><td>0</td><td>100.0</td><td>4.73</td><td style="">-0.97</td><td></td><td>0.67</td><td>0.64</td><td></td><td></td><td></td><td></td><td>0.34</td><td>0.48</td><td>0.52</td><td>0.86</td><td>0.031</td><td style="background-color:#F3F3F3; font-weight:bold;">0.078</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10557">오선진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.076</td><td>14</td><td>1</td><td>41.2</td><td>8</td><td>0</td><td>8</td><td>0</td><td>100.0</td><td>1.73</td><td style="">0.20</td><td></td><td>0.29</td><td>0.35</td><td></td><td></td><td></td><td></td><td>0.83</td><td>4.59</td><td>0.00</td><td>0.83</td><td>0.076</td><td style="background-color:#F3F3F3; font-weight:bold;">0.076</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14819">이주찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.073</td><td>3</td><td>0</td><td>5.0</td><td>4</td><td>1</td><td>3</td><td>0</td><td>100.0</td><td>7.20</td><td style="">0.38</td><td></td><td>0.04</td><td>0.36</td><td></td><td></td><td></td><td></td><td>0.78</td><td>6.64</td><td>0.02</td><td>0.80</td><td>0.072</td><td style="background-color:#F3F3F3; font-weight:bold;">0.073</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10238">김민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.066</td><td>3</td><td>2</td><td>12.0</td><td>8</td><td>1</td><td>7</td><td>0</td><td>100.0</td><td>6.00</td><td style="">0.59</td><td></td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>0.67</td><td>2.74</td><td>0.06</td><td>0.73</td><td>0.061</td><td style="background-color:#F3F3F3; font-weight:bold;">0.066</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10804">박승욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.049</td><td>110</td><td>97</td><td>833.0</td><td>414</td><td>140</td><td>252</td><td>22</td><td>94.7</td><td>4.24</td><td style="">-5.65</td><td></td><td>-3.65</td><td>2.10</td><td></td><td></td><td></td><td></td><td>-7.21</td><td>-7.46</td><td>7.74</td><td>0.53</td><td>-0.658</td><td style="background-color:#F3F3F3; font-weight:bold;">0.049</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14642">황성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.047</td><td>2</td><td>0</td><td>4.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>2.25</td><td style="">0.51</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.53</td><td>0.61</td><td>-0.01</td><td>0.52</td><td>0.048</td><td style="background-color:#F3F3F3; font-weight:bold;">0.047</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14160">고승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.047</td><td>13</td><td>12</td><td>86.0</td><td>19</td><td>17</td><td>2</td><td>0</td><td>100.0</td><td>1.99</td><td style="">0.29</td><td>0.57</td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>0.96</td><td>1.15</td><td>-0.45</td><td>0.51</td><td>0.088</td><td style="background-color:#F3F3F3; font-weight:bold;">0.047</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10557">오선진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.045</td><td>10</td><td>2</td><td>27.0</td><td>10</td><td>3</td><td>7</td><td>0</td><td>100.0</td><td>3.33</td><td style="">0.25</td><td></td><td>0.16</td><td></td><td></td><td></td><td></td><td></td><td>0.41</td><td>2.26</td><td>0.08</td><td>0.49</td><td>0.037</td><td style="background-color:#F3F3F3; font-weight:bold;">0.045</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14160">고승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.038</td><td>6</td><td>3</td><td>31.0</td><td>9</td><td>9</td><td>0</td><td>0</td><td>100.0</td><td>2.61</td><td style="">0.74</td><td>-0.27</td><td>0.09</td><td></td><td></td><td></td><td></td><td></td><td>0.57</td><td>0.68</td><td>-0.15</td><td>0.42</td><td>0.052</td><td style="background-color:#F3F3F3; font-weight:bold;">0.038</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15253">김민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.037</td><td>22</td><td>13</td><td>128.2</td><td>36</td><td>35</td><td>1</td><td>0</td><td>100.0</td><td>2.52</td><td style="">0.93</td><td>-0.09</td><td>0.15</td><td></td><td></td><td></td><td></td><td></td><td>0.98</td><td>3.46</td><td>-0.58</td><td>0.40</td><td>0.090</td><td style="background-color:#F3F3F3; font-weight:bold;">0.037</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14169">신윤후</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.037</td><td>3</td><td>0</td><td>6.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>4.50</td><td style="">0.42</td><td>-0.03</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.40</td><td>1.49</td><td>0.00</td><td>0.40</td><td>0.037</td><td style="background-color:#F3F3F3; font-weight:bold;">0.037</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16106">레이예스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.032</td><td>1</td><td>0</td><td>2.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.35</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.35</td><td>0.35</td><td>0.00</td><td>0.35</td><td>0.032</td><td style="background-color:#F3F3F3; font-weight:bold;">0.032</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10557">오선진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.031</td><td>3</td><td>0</td><td>6.0</td><td>2</td><td>0</td><td>2</td><td>0</td><td>100.0</td><td>3.00</td><td style="">0.24</td><td></td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>0.30</td><td>1.64</td><td>0.04</td><td>0.34</td><td>0.027</td><td style="background-color:#F3F3F3; font-weight:bold;">0.031</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14169">신윤후</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.022</td><td>3</td><td>0</td><td>8.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>1.13</td><td style="">-0.53</td><td>0.78</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.26</td><td>0.97</td><td>-0.02</td><td>0.24</td><td>0.024</td><td style="background-color:#F3F3F3; font-weight:bold;">0.022</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10804">박승욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.012</td><td>18</td><td>4</td><td>54.0</td><td>36</td><td>16</td><td>20</td><td>0</td><td>100.0</td><td>6.00</td><td style="">-0.47</td><td></td><td>0.33</td><td></td><td></td><td></td><td></td><td></td><td>-0.14</td><td>-0.14</td><td>0.27</td><td>0.13</td><td>-0.013</td><td style="background-color:#F3F3F3; font-weight:bold;">0.012</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15645">김동혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.007</td><td>7</td><td>0</td><td>11.2</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>1.54</td><td style="">0.23</td><td>-0.16</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>0.10</td><td>0.37</td><td>-0.02</td><td>0.08</td><td>0.009</td><td style="background-color:#F3F3F3; font-weight:bold;">0.007</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15645">김동혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.007</td><td>20</td><td>0</td><td>44.0</td><td>20</td><td>18</td><td>0</td><td>2</td><td>90.0</td><td>3.68</td><td style="">1.06</td><td>-0.07</td><td>-0.91</td><td></td><td></td><td></td><td></td><td></td><td>0.07</td><td>0.27</td><td>0.00</td><td>0.07</td><td>0.007</td><td style="background-color:#F3F3F3; font-weight:bold;">0.007</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14114">이학주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.000</td><td>3</td><td>2</td><td>5.2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.04</td><td></td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>-0.01</td><td>0.00</td><td>0.00</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">0.000</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10253">정훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.001</td><td>2</td><td>0</td><td>3.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td>-0.01</td><td>-0.01</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.001</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14819">이주찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.001</td><td>1</td><td>0</td><td>2.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>13.50</td><td style=""></td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.08</td><td>-0.02</td><td>-0.01</td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.001</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11388">강태율</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.003</td><td>10</td><td>3</td><td>28.0</td><td>31</td><td>29</td><td>1</td><td>1</td><td>96.8</td><td>9.64</td><td style="">0.00</td><td></td><td>-0.40</td><td></td><td></td><td>-0.12</td><td>0.40</td><td></td><td>-0.25</td><td>-3.55</td><td>0.22</td><td>-0.03</td><td>-0.023</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.003</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11165">노진혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.006</td><td>12</td><td>3</td><td>36.0</td><td>40</td><td>36</td><td>3</td><td>1</td><td>97.5</td><td>9.75</td><td style="">0.53</td><td></td><td>-0.32</td><td></td><td></td><td></td><td></td><td></td><td>0.21</td><td>0.41</td><td>-0.28</td><td>-0.07</td><td>0.019</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.006</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13155">장두성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.011</td><td>19</td><td>0</td><td>30.1</td><td>7</td><td>6</td><td>0</td><td>1</td><td>85.7</td><td>1.78</td><td style="">0.45</td><td>-0.08</td><td>-0.41</td><td></td><td></td><td></td><td></td><td></td><td>-0.04</td><td>-0.08</td><td>-0.08</td><td>-0.12</td><td>-0.003</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.011</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10253">정훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.018</td><td>2</td><td>0</td><td>3.0</td><td>2</td><td>1</td><td>1</td><td>0</td><td>100.0</td><td>6.00</td><td style="">-0.23</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.21</td><td>-0.27</td><td>0.01</td><td>-0.20</td><td>-0.019</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.018</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10238">김민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.020</td><td>29</td><td>19</td><td>162.1</td><td>41</td><td>13</td><td>26</td><td>2</td><td>95.1</td><td>2.16</td><td style="">-1.18</td><td></td><td>0.11</td><td>0.51</td><td>0.34</td><td></td><td></td><td></td><td>-0.21</td><td>-0.88</td><td>0.00</td><td>-0.21</td><td>-0.020</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.020</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12916">이정훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.025</td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.37</td><td>0.10</td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.26</td><td>-0.58</td><td>-0.01</td><td>-0.27</td><td>-0.024</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.025</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16102">강승구</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.027</td><td>5</td><td>0</td><td>7.0</td><td>6</td><td>6</td><td>0</td><td>0</td><td>100.0</td><td>7.71</td><td style="">-0.09</td><td></td><td>0.03</td><td></td><td></td><td></td><td>-0.39</td><td></td><td>-0.34</td><td>-9.82</td><td>0.05</td><td>-0.29</td><td>-0.031</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.027</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15624">서동욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.037</td><td>32</td><td>5</td><td>95.0</td><td>86</td><td>75</td><td>10</td><td>1</td><td>98.8</td><td>8.05</td><td style="">-0.15</td><td></td><td>-0.16</td><td></td><td>0.05</td><td>0.18</td><td>-1.35</td><td></td><td>-1.03</td><td>-4.50</td><td>0.62</td><td>-0.41</td><td>-0.094</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.037</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14169">신윤후</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.038</td><td>2</td><td>0</td><td>5.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>5.40</td><td style="">-0.45</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.42</td><td>-1.55</td><td>0.00</td><td>-0.42</td><td>-0.038</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.038</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10253">정훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.054</td><td>13</td><td>11</td><td>70.1</td><td>22</td><td>5</td><td>16</td><td>1</td><td>95.5</td><td>2.69</td><td style="">0.12</td><td></td><td>-0.02</td><td>-0.45</td><td>-0.24</td><td></td><td></td><td></td><td>-0.60</td><td>-0.79</td><td>0.00</td><td>-0.60</td><td>-0.054</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.054</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16091">이호준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.059</td><td>4</td><td>1</td><td>13.0</td><td>6</td><td>1</td><td>5</td><td>0</td><td>100.0</td><td>4.15</td><td style="">-0.28</td><td></td><td>0.08</td><td>-0.50</td><td></td><td></td><td></td><td></td><td>-0.70</td><td>-8.38</td><td>0.05</td><td>-0.65</td><td>-0.064</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.059</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14160">고승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.060</td><td>6</td><td>0</td><td>13.0</td><td>12</td><td>11</td><td>1</td><td>0</td><td>100.0</td><td>8.31</td><td style="">-0.60</td><td></td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>-0.54</td><td>-0.65</td><td>-0.12</td><td>-0.66</td><td>-0.049</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.060</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10810">최항</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.064</td><td>10</td><td>1</td><td>21.1</td><td>14</td><td>14</td><td>0</td><td>0</td><td>100.0</td><td>5.91</td><td style="">-0.64</td><td></td><td>0.11</td><td></td><td></td><td></td><td></td><td></td><td>-0.54</td><td>-1.08</td><td>-0.16</td><td>-0.70</td><td>-0.049</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.064</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15253">김민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.075</td><td>3</td><td>3</td><td>23.1</td><td>10</td><td>10</td><td>0</td><td>0</td><td>100.0</td><td>3.86</td><td style="">-0.57</td><td>-0.31</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>-0.83</td><td>-2.90</td><td>0.00</td><td>-0.83</td><td>-0.075</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.075</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10810">최항</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.077</td><td>16</td><td>5</td><td>58.0</td><td>19</td><td>5</td><td>13</td><td>1</td><td>94.7</td><td>2.79</td><td style="">-1.21</td><td></td><td>-0.10</td><td>0.46</td><td></td><td></td><td></td><td></td><td>-0.85</td><td>-1.69</td><td>0.00</td><td>-0.85</td><td>-0.077</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.077</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13155">장두성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.096</td><td>11</td><td>1</td><td>25.0</td><td>6</td><td>6</td><td>0</td><td>0</td><td>100.0</td><td>2.16</td><td style="">-0.77</td><td>-0.23</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.97</td><td>-1.96</td><td>-0.08</td><td>-1.05</td><td>-0.088</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.096</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10253">정훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.142</td><td>37</td><td>29</td><td>271.0</td><td>281</td><td>259</td><td>20</td><td>2</td><td>99.3</td><td>9.27</td><td style="">0.42</td><td></td><td>0.34</td><td></td><td>0.29</td><td></td><td></td><td></td><td>1.04</td><td>1.38</td><td>-2.60</td><td>-1.56</td><td>0.095</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.142</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14114">이학주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.166</td><td>40</td><td>25</td><td>238.1</td><td>107</td><td>38</td><td>67</td><td>2</td><td>98.1</td><td>3.97</td><td style="">-3.82</td><td></td><td>1.11</td><td>-1.16</td><td></td><td></td><td></td><td></td><td>-3.88</td><td>-12.99</td><td>2.06</td><td>-1.82</td><td>-0.354</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.166</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10804">박승욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.168</td><td>27</td><td>11</td><td>123.2</td><td>31</td><td>10</td><td>20</td><td>1</td><td>96.8</td><td>2.18</td><td style="">-3.29</td><td></td><td>0.35</td><td>0.65</td><td>0.46</td><td></td><td></td><td></td><td>-1.84</td><td>-1.91</td><td>0.00</td><td>-1.84</td><td>-0.168</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.168</td></tr><tr><td style="text-align:center;">52</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14590">손호영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.217</td><td>6</td><td>4</td><td>39.0</td><td>18</td><td>8</td><td>9</td><td>1</td><td>94.4</td><td>3.92</td><td style="">-2.23</td><td></td><td>-0.16</td><td>-0.38</td><td></td><td></td><td></td><td></td><td>-2.76</td><td>-3.90</td><td>0.38</td><td>-2.38</td><td>-0.252</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.217</td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13145">한동희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.237</td><td>6</td><td>6</td><td>32.1</td><td>10</td><td>1</td><td>7</td><td>2</td><td>80.0</td><td>2.23</td><td style="">-1.75</td><td></td><td>-0.78</td><td>-0.41</td><td>0.34</td><td></td><td></td><td></td><td>-2.60</td><td>-26.73</td><td>0.00</td><td>-2.60</td><td>-0.237</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.237</td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11165">노진혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.268</td><td>29</td><td>18</td><td>150.2</td><td>66</td><td>23</td><td>38</td><td>5</td><td>92.4</td><td>3.64</td><td style="">-2.37</td><td></td><td>-1.17</td><td>-0.91</td><td></td><td></td><td></td><td></td><td>-4.45</td><td>-8.79</td><td>1.52</td><td>-2.93</td><td>-0.407</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.268</td></tr><tr><td style="text-align:center;">55</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15048">윤동희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.342</td><td>61</td><td>54</td><td>455.0</td><td>108</td><td>106</td><td>2</td><td>0</td><td>100.0</td><td>2.14</td><td style="">-3.05</td><td>0.39</td><td>1.37</td><td></td><td></td><td></td><td></td><td></td><td>-1.29</td><td>-1.32</td><td>-2.45</td><td>-3.74</td><td>-0.118</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.342</td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14590">손호영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.388</td><td>79</td><td>74</td><td>637.2</td><td>186</td><td>58</td><td>116</td><td>12</td><td>93.5</td><td>2.46</td><td style="">-1.34</td><td></td><td>-1.64</td><td>-1.12</td><td>-0.14</td><td></td><td></td><td></td><td>-4.25</td><td>-6.00</td><td>0.00</td><td>-4.25</td><td>-0.388</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.388</td></tr><tr><td style="text-align:center;">57</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14642">황성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.418</td><td>65</td><td>58</td><td>453.2</td><td>92</td><td>87</td><td>3</td><td>2</td><td>97.8</td><td>1.79</td><td style="">-4.87</td><td>0.36</td><td>-0.06</td><td></td><td></td><td></td><td></td><td></td><td>-4.57</td><td>-5.27</td><td>0.00</td><td>-4.57</td><td>-0.418</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.418</td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16106">레이예스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.428</td><td>47</td><td>44</td><td>346.0</td><td>81</td><td>79</td><td>2</td><td>0</td><td>100.0</td><td>2.11</td><td style="">-3.14</td><td>0.00</td><td>0.39</td><td></td><td></td><td></td><td></td><td></td><td>-2.75</td><td>-2.75</td><td>-1.94</td><td>-4.69</td><td>-0.251</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.428</td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14819">이주찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.473</td><td>10</td><td>5</td><td>46.1</td><td>16</td><td>3</td><td>9</td><td>4</td><td>75.0</td><td>2.33</td><td style="">-2.67</td><td></td><td>-1.69</td><td>-0.82</td><td></td><td></td><td></td><td></td><td>-5.18</td><td>-43.89</td><td>0.00</td><td>-5.18</td><td>-0.473</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.473</td></tr><tr><td style="text-align:center;">60</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10266">전준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.540</td><td>47</td><td>47</td><td>381.1</td><td>90</td><td>87</td><td>2</td><td>1</td><td>98.9</td><td>2.10</td><td style="">-4.10</td><td>0.30</td><td>-0.07</td><td></td><td></td><td></td><td></td><td></td><td>-3.87</td><td>-5.11</td><td>-2.04</td><td>-5.91</td><td>-0.353</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.540</td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16106">레이예스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.659</td><td>83</td><td>81</td><td>664.2</td><td>130</td><td>126</td><td>0</td><td>4</td><td>96.9</td><td>1.71</td><td style="">-3.49</td><td>-0.17</td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-3.66</td><td>-3.66</td><td>-3.55</td><td>-7.21</td><td>-0.335</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.659</td></tr><tr><td style="text-align:center;">62</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14797">나승엽</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-1.582</td><td>113</td><td>111</td><td>937.1</td><td>891</td><td>813</td><td>67</td><td>11</td><td>98.8</td><td>8.45</td><td style="">-6.90</td><td></td><td>-0.89</td><td></td><td>-0.10</td><td></td><td></td><td></td><td>-7.89</td><td>-9.39</td><td>-9.42</td><td>-17.31</td><td>-0.721</td><td style="background-color:#F3F3F3; font-weight:bold;">-1.582</td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16095">이선우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.66</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.65</td><td>-13.47</td><td></td><td></td><td>-0.058</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12916">이정훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.00</td><td></td><td>0.00</td><td></td><td></td><td></td><td>-0.49</td><td></td><td>-0.34</td><td>-0.76</td><td></td><td></td><td>-0.031</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13271">현도훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>7</td><td>0</td><td>10.0</td><td>3</td><td>1</td><td>2</td><td>0</td><td>100.0</td><td>2.70</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16095">이선우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>2.2</td><td>2</td><td>1</td><td>0</td><td>1</td><td>50.0</td><td>3.38</td><td style="">-1.01</td><td>0.01</td><td>-0.50</td><td></td><td></td><td></td><td></td><td></td><td>-1.49</td><td>-30.66</td><td></td><td></td><td>-0.132</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14819">이주찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.05</td><td></td><td></td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14690">이인한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.07</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16093">강성우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.64</td><td></td><td></td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10427">김상수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>71</td><td>0</td><td>73.2</td><td>15</td><td>1</td><td>13</td><td>1</td><td>93.3</td><td>1.71</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12699">김강현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>24</td><td>0</td><td>25.1</td><td>8</td><td>3</td><td>5</td><td>0</td><td>100.0</td><td>2.84</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15645">김동혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>3.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-0.08</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.07</td><td>-0.27</td><td></td><td></td><td>-0.007</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10825">김원중</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>54</td><td>0</td><td>63.1</td><td>10</td><td>3</td><td>6</td><td>1</td><td>90.0</td><td>1.28</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13094">추재현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>3.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.05</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14690">이인한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.12</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11261">박찬호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.374</td><td>132</td><td>129</td><td>1120.1</td><td>564</td><td>213</td><td>328</td><td>23</td><td>95.9</td><td>4.35</td><td style="">4.92</td><td></td><td>-0.60</td><td>-0.75</td><td></td><td></td><td></td><td></td><td>3.57</td><td>3.83</td><td>11.48</td><td>15.05</td><td>0.326</td><td style="background-color:#F3F3F3; font-weight:bold;">1.374</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10459">김태군</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.858</td><td>101</td><td>82</td><td>640.2</td><td>611</td><td>567</td><td>38</td><td>6</td><td>99.0</td><td>8.50</td><td style="">0.81</td><td></td><td>-0.70</td><td></td><td>0.11</td><td>-1.10</td><td>5.58</td><td></td><td>3.03</td><td>4.15</td><td>6.36</td><td>9.39</td><td>0.277</td><td style="background-color:#F3F3F3; font-weight:bold;">0.858</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13113">한준수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.447</td><td>103</td><td>60</td><td>600.1</td><td>584</td><td>541</td><td>39</td><td>4</td><td>99.3</td><td>8.70</td><td style="">-0.57</td><td></td><td>0.16</td><td></td><td>0.21</td><td>0.75</td><td>-3.09</td><td></td><td>-1.61</td><td>-2.02</td><td>6.50</td><td>4.89</td><td>-0.147</td><td style="background-color:#F3F3F3; font-weight:bold;">0.447</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10855">서건창</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.254</td><td>34</td><td>18</td><td>158.0</td><td>86</td><td>34</td><td>51</td><td>1</td><td>98.8</td><td>4.84</td><td style="">1.28</td><td></td><td>0.45</td><td>0.22</td><td></td><td></td><td></td><td></td><td>1.96</td><td>3.00</td><td>0.82</td><td>2.78</td><td>0.179</td><td style="background-color:#F3F3F3; font-weight:bold;">0.254</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11298">김호령</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.215</td><td>61</td><td>9</td><td>177.0</td><td>64</td><td>62</td><td>0</td><td>2</td><td>96.9</td><td>3.15</td><td style="">3.13</td><td>-0.14</td><td>-0.64</td><td></td><td></td><td></td><td></td><td></td><td>2.36</td><td>5.30</td><td>0.00</td><td>2.36</td><td>0.215</td><td style="background-color:#F3F3F3; font-weight:bold;">0.215</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14996">소크라테스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.212</td><td>52</td><td>47</td><td>366.2</td><td>97</td><td>93</td><td>2</td><td>2</td><td>97.9</td><td>2.33</td><td style="">2.50</td><td>0.06</td><td>-0.24</td><td></td><td></td><td></td><td></td><td></td><td>2.32</td><td>2.39</td><td>0.00</td><td>2.32</td><td>0.212</td><td style="background-color:#F3F3F3; font-weight:bold;">0.212</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12869">박정우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.199</td><td>19</td><td>2</td><td>46.1</td><td>17</td><td>17</td><td>0</td><td>0</td><td>100.0</td><td>3.30</td><td style="">2.24</td><td>0.05</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>2.35</td><td>5.13</td><td>-0.17</td><td>2.18</td><td>0.215</td><td style="background-color:#F3F3F3; font-weight:bold;">0.199</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12869">박정우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.112</td><td>47</td><td>5</td><td>115.1</td><td>33</td><td>29</td><td>2</td><td>2</td><td>93.9</td><td>2.42</td><td style="">2.06</td><td>-0.07</td><td>-0.76</td><td></td><td></td><td></td><td></td><td></td><td>1.23</td><td>2.68</td><td>0.00</td><td>1.23</td><td>0.112</td><td style="background-color:#F3F3F3; font-weight:bold;">0.112</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15058">윤도현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.110</td><td>2</td><td>1</td><td>11.0</td><td>5</td><td>4</td><td>1</td><td>0</td><td>100.0</td><td>4.09</td><td style="">1.01</td><td></td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>1.11</td><td>26.58</td><td>0.10</td><td>1.21</td><td>0.101</td><td style="background-color:#F3F3F3; font-weight:bold;">0.110</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14611">박민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.105</td><td>10</td><td>4</td><td>40.0</td><td>25</td><td>9</td><td>13</td><td>3</td><td>88.0</td><td>4.95</td><td style="">1.01</td><td></td><td>-1.15</td><td>0.99</td><td></td><td></td><td></td><td></td><td>0.85</td><td>7.65</td><td>0.30</td><td>1.15</td><td>0.078</td><td style="background-color:#F3F3F3; font-weight:bold;">0.105</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14124">변우혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.077</td><td>15</td><td>5</td><td>74.0</td><td>22</td><td>6</td><td>15</td><td>1</td><td>95.5</td><td>2.55</td><td style="">1.17</td><td></td><td>0.01</td><td>0.32</td><td>-0.65</td><td></td><td></td><td></td><td>0.84</td><td>1.76</td><td>0.00</td><td>0.84</td><td>0.077</td><td style="background-color:#F3F3F3; font-weight:bold;">0.077</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11233">이창진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.061</td><td>1</td><td>1</td><td>5.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.80</td><td style="">0.54</td><td>0.12</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.67</td><td>0.93</td><td>0.00</td><td>0.67</td><td>0.061</td><td style="background-color:#F3F3F3; font-weight:bold;">0.061</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15058">윤도현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.060</td><td>3</td><td>3</td><td>24.0</td><td>9</td><td>2</td><td>7</td><td>0</td><td>100.0</td><td>3.38</td><td style="">0.10</td><td></td><td>0.15</td><td>0.28</td><td></td><td></td><td></td><td></td><td>0.52</td><td>12.55</td><td>0.13</td><td>0.65</td><td>0.048</td><td style="background-color:#F3F3F3; font-weight:bold;">0.060</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11099">이우성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.047</td><td>8</td><td>5</td><td>33.0</td><td>8</td><td>8</td><td>0</td><td>0</td><td>100.0</td><td>2.18</td><td style="">0.70</td><td>-0.06</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>0.68</td><td>0.88</td><td>-0.17</td><td>0.51</td><td>0.062</td><td style="background-color:#F3F3F3; font-weight:bold;">0.047</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15058">윤도현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.029</td><td>2</td><td>2</td><td>18.0</td><td>5</td><td>2</td><td>3</td><td>0</td><td>100.0</td><td>2.50</td><td style="">0.19</td><td></td><td>0.12</td><td>0.00</td><td></td><td></td><td></td><td></td><td>0.32</td><td>7.62</td><td>0.00</td><td>0.32</td><td>0.029</td><td style="background-color:#F3F3F3; font-weight:bold;">0.029</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12540">김규성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.021</td><td>9</td><td>0</td><td>13.0</td><td>17</td><td>15</td><td>1</td><td>1</td><td>94.1</td><td>11.08</td><td style="">0.73</td><td></td><td>-0.44</td><td></td><td></td><td></td><td></td><td></td><td>0.29</td><td>1.55</td><td>-0.06</td><td>0.23</td><td>0.026</td><td style="background-color:#F3F3F3; font-weight:bold;">0.021</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11407">최정용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.001</td><td>2</td><td>0</td><td>3.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.01</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.19</td><td>0.00</td><td>0.01</td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;">0.001</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12869">박정우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.000</td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">0.000</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16086">김두현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.000</td><td>1</td><td>1</td><td>5.0</td><td>3</td><td>2</td><td>1</td><td>0</td><td>100.0</td><td>5.40</td><td style="">-0.05</td><td></td><td>0.03</td><td>0.00</td><td></td><td></td><td></td><td></td><td>-0.02</td><td>-0.98</td><td>0.02</td><td>0.00</td><td>-0.002</td><td style="background-color:#F3F3F3; font-weight:bold;">0.000</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14612">홍종표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.002</td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.02</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.01</td><td>-0.02</td><td>-0.01</td><td>-0.02</td><td>-0.001</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.002</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14612">홍종표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.003</td><td>17</td><td>9</td><td>81.0</td><td>39</td><td>13</td><td>24</td><td>2</td><td>94.9</td><td>4.11</td><td style="">-1.24</td><td></td><td>-0.29</td><td>0.69</td><td></td><td></td><td></td><td></td><td>-0.83</td><td>-1.20</td><td>0.80</td><td>-0.03</td><td>-0.076</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.003</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12869">박정우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.012</td><td>7</td><td>2</td><td>25.0</td><td>7</td><td>6</td><td>0</td><td>1</td><td>85.7</td><td>2.16</td><td style="">0.79</td><td>-0.38</td><td>-0.43</td><td></td><td></td><td></td><td></td><td></td><td>-0.02</td><td>-0.05</td><td>-0.11</td><td>-0.13</td><td>-0.002</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.012</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14996">소크라테스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.020</td><td>4</td><td>1</td><td>11.0</td><td>5</td><td>4</td><td>0</td><td>1</td><td>80.0</td><td>3.27</td><td style="">0.60</td><td>-0.28</td><td>-0.47</td><td></td><td></td><td></td><td></td><td></td><td>-0.14</td><td>-0.15</td><td>-0.07</td><td>-0.21</td><td>-0.013</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.020</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15056">김도영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.026</td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.32</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.31</td><td>-0.31</td><td>0.02</td><td>-0.29</td><td>-0.028</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.026</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10008">김선빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.034</td><td>2</td><td>0</td><td>4.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.40</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.37</td><td>-0.46</td><td>0.00</td><td>-0.37</td><td>-0.034</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.034</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12534">최원준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.037</td><td>96</td><td>29</td><td>399.0</td><td>72</td><td>69</td><td>3</td><td>0</td><td>100.0</td><td>1.62</td><td style="">-0.13</td><td>0.19</td><td>1.21</td><td></td><td></td><td></td><td></td><td></td><td>1.27</td><td>1.34</td><td>-1.67</td><td>-0.40</td><td>0.116</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.037</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14612">홍종표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.048</td><td>65</td><td>4</td><td>167.0</td><td>99</td><td>36</td><td>61</td><td>2</td><td>98.0</td><td>5.23</td><td style="">-1.80</td><td></td><td>0.01</td><td>0.80</td><td></td><td></td><td></td><td></td><td>-0.99</td><td>-1.43</td><td>0.47</td><td>-0.52</td><td>-0.091</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.048</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12540">김규성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.052</td><td>9</td><td>0</td><td>20.2</td><td>11</td><td>4</td><td>6</td><td>1</td><td>90.9</td><td>4.35</td><td style="">0.64</td><td></td><td>-0.32</td><td>-0.99</td><td></td><td></td><td></td><td></td><td>-0.67</td><td>-3.57</td><td>0.10</td><td>-0.57</td><td>-0.061</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.052</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11306">황대인</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.053</td><td>2</td><td>2</td><td>10.0</td><td>10</td><td>9</td><td>1</td><td>0</td><td>100.0</td><td>9.00</td><td style="">-0.51</td><td></td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>-0.46</td><td>-22.06</td><td>-0.12</td><td>-0.58</td><td>-0.042</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.053</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10008">김선빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.058</td><td>115</td><td>112</td><td>884.0</td><td>500</td><td>206</td><td>284</td><td>10</td><td>98.0</td><td>4.99</td><td style="">-4.31</td><td></td><td>0.32</td><td>-1.27</td><td></td><td></td><td></td><td></td><td>-5.25</td><td>-6.52</td><td>4.62</td><td>-0.63</td><td>-0.480</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.058</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11407">최정용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.088</td><td>4</td><td>2</td><td>21.0</td><td>8</td><td>3</td><td>4</td><td>1</td><td>87.5</td><td>3.00</td><td style="">-0.68</td><td></td><td>-0.37</td><td>0.00</td><td></td><td></td><td></td><td></td><td>-1.06</td><td>-25.40</td><td>0.09</td><td>-0.97</td><td>-0.097</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.088</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10659">고종욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.096</td><td>8</td><td>3</td><td>25.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>1.44</td><td style="">-0.80</td><td>-0.16</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.93</td><td>-4.78</td><td>-0.12</td><td>-1.05</td><td>-0.085</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.096</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12540">김규성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.101</td><td>7</td><td>2</td><td>22.0</td><td>6</td><td>2</td><td>4</td><td>0</td><td>100.0</td><td>2.45</td><td style="">-1.26</td><td></td><td>0.15</td><td>0.00</td><td></td><td></td><td></td><td></td><td>-1.11</td><td>-5.92</td><td>0.00</td><td>-1.11</td><td>-0.101</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.101</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14181">오선우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.121</td><td>2</td><td>1</td><td>11.0</td><td>3</td><td>2</td><td>0</td><td>1</td><td>66.7</td><td>1.64</td><td style="">-0.80</td><td>-0.01</td><td>-0.47</td><td></td><td></td><td></td><td></td><td></td><td>-1.28</td><td>-61.31</td><td>-0.05</td><td>-1.33</td><td>-0.117</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.121</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14611">박민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.144</td><td>4</td><td>4</td><td>28.0</td><td>14</td><td>1</td><td>10</td><td>3</td><td>78.6</td><td>3.54</td><td style="">-0.35</td><td></td><td>-1.34</td><td>-0.03</td><td></td><td></td><td></td><td></td><td>-1.72</td><td>-15.44</td><td>0.14</td><td>-1.58</td><td>-0.157</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.144</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11119">한승택</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.145</td><td>19</td><td>2</td><td>47.0</td><td>52</td><td>43</td><td>7</td><td>2</td><td>96.2</td><td>9.57</td><td style="">0.34</td><td></td><td>-0.83</td><td></td><td></td><td>0.34</td><td>-2.50</td><td></td><td>-1.90</td><td>-13.65</td><td>0.31</td><td>-1.58</td><td>-0.173</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.145</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14612">홍종표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.203</td><td>15</td><td>3</td><td>52.0</td><td>10</td><td>2</td><td>7</td><td>1</td><td>90.0</td><td>1.56</td><td style="">-1.89</td><td></td><td>-0.14</td><td>-0.26</td><td>0.07</td><td></td><td></td><td></td><td>-2.22</td><td>-3.20</td><td>0.00</td><td>-2.22</td><td>-0.203</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.203</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11099">이우성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.222</td><td>25</td><td>22</td><td>162.0</td><td>36</td><td>34</td><td>0</td><td>2</td><td>94.4</td><td>1.89</td><td style="">-0.86</td><td>-0.25</td><td>-0.51</td><td></td><td></td><td></td><td></td><td></td><td>-1.63</td><td>-2.10</td><td>-0.80</td><td>-2.43</td><td>-0.149</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.222</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11233">이창진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.234</td><td>56</td><td>33</td><td>309.1</td><td>85</td><td>85</td><td>0</td><td>0</td><td>100.0</td><td>2.47</td><td style="">-1.32</td><td>-0.17</td><td>0.35</td><td></td><td></td><td></td><td></td><td></td><td>-1.14</td><td>-1.59</td><td>-1.42</td><td>-2.56</td><td>-0.104</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.234</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16086">김두현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.245</td><td>2</td><td>1</td><td>10.0</td><td>5</td><td>0</td><td>3</td><td>2</td><td>60.0</td><td>2.70</td><td style="">-1.88</td><td></td><td>-0.92</td><td>0.05</td><td></td><td></td><td></td><td></td><td>-2.74</td><td>-131.41</td><td>0.06</td><td>-2.68</td><td>-0.250</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.245</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11233">이창진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.288</td><td>38</td><td>22</td><td>175.0</td><td>32</td><td>31</td><td>0</td><td>1</td><td>96.9</td><td>1.59</td><td style="">-1.39</td><td>-0.97</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-2.33</td><td>-3.26</td><td>-0.82</td><td>-3.15</td><td>-0.213</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.288</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12534">최원준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.289</td><td>93</td><td>82</td><td>624.0</td><td>169</td><td>163</td><td>2</td><td>4</td><td>97.6</td><td>2.38</td><td style="">-3.00</td><td>0.55</td><td>-0.71</td><td></td><td></td><td></td><td></td><td></td><td>-3.16</td><td>-3.35</td><td>0.00</td><td>-3.16</td><td>-0.289</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.289</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10344">최형우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.351</td><td>16</td><td>15</td><td>117.0</td><td>16</td><td>14</td><td>0</td><td>2</td><td>87.5</td><td>1.08</td><td style="">-2.74</td><td>0.43</td><td>-0.87</td><td></td><td></td><td></td><td></td><td></td><td>-3.18</td><td>-3.95</td><td>-0.66</td><td>-3.84</td><td>-0.291</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.351</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15056">김도영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.368</td><td>134</td><td>132</td><td>1111.0</td><td>323</td><td>77</td><td>216</td><td>30</td><td>90.7</td><td>2.37</td><td style="">2.77</td><td></td><td>-6.93</td><td>-0.06</td><td>0.19</td><td></td><td></td><td></td><td>-4.03</td><td>-4.11</td><td>0.00</td><td>-4.03</td><td>-0.368</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.368</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11162">나성범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.385</td><td>67</td><td>67</td><td>505.0</td><td>97</td><td>91</td><td>5</td><td>1</td><td>99.0</td><td>1.71</td><td style="">-2.51</td><td>0.08</td><td>1.02</td><td></td><td></td><td></td><td></td><td></td><td>-1.40</td><td>-1.98</td><td>-2.81</td><td>-4.21</td><td>-0.128</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.385</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14124">변우혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.389</td><td>53</td><td>38</td><td>314.0</td><td>290</td><td>277</td><td>11</td><td>2</td><td>99.3</td><td>8.25</td><td style="">-2.41</td><td></td><td>0.55</td><td></td><td>0.39</td><td></td><td></td><td></td><td>-1.48</td><td>-3.08</td><td>-2.78</td><td>-4.26</td><td>-0.135</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.389</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10855">서건창</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.521</td><td>51</td><td>25</td><td>276.2</td><td>275</td><td>241</td><td>30</td><td>4</td><td>98.5</td><td>8.82</td><td style="">-2.19</td><td></td><td>-0.64</td><td></td><td>-0.16</td><td></td><td></td><td></td><td>-2.99</td><td>-4.58</td><td>-2.72</td><td>-5.71</td><td>-0.273</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.521</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14996">소크라테스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.676</td><td>115</td><td>86</td><td>755.1</td><td>174</td><td>168</td><td>4</td><td>2</td><td>98.9</td><td>2.05</td><td style="">-3.34</td><td>-0.04</td><td>-0.14</td><td></td><td></td><td></td><td></td><td></td><td>-3.53</td><td>-3.63</td><td>-3.87</td><td>-7.40</td><td>-0.323</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.676</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11099">이우성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.987</td><td>87</td><td>79</td><td>670.1</td><td>651</td><td>609</td><td>36</td><td>6</td><td>99.1</td><td>8.66</td><td style="">-4.16</td><td></td><td>0.30</td><td></td><td>-0.29</td><td></td><td></td><td></td><td>-4.15</td><td>-5.33</td><td>-6.66</td><td>-10.81</td><td>-0.379</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.987</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11159">이형범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>14</td><td>0</td><td>15.0</td><td>5</td><td>4</td><td>1</td><td>0</td><td>100.0</td><td>3.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11364">김사윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>23</td><td>2</td><td>37.0</td><td>7</td><td>0</td><td>6</td><td>1</td><td>85.7</td><td>1.46</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12540">김규성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>2</td><td>1</td><td>0</td><td>1</td><td>50.0</td><td>9.00</td><td style="">-0.55</td><td></td><td>-0.50</td><td></td><td></td><td></td><td></td><td></td><td>-1.05</td><td>-5.57</td><td></td><td></td><td>-0.095</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16082">김민주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10008">김선빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>18.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.01</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12534">최원준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">-0.60</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.60</td><td>-0.63</td><td></td><td></td><td>-0.055</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12637">김승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>14</td><td>0</td><td>18.0</td><td>5</td><td>0</td><td>3</td><td>2</td><td>60.0</td><td>1.50</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14181">오선우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>2.0</td><td>3</td><td>2</td><td>1</td><td>0</td><td>100.0</td><td>13.50</td><td style="">0.89</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.90</td><td>42.98</td><td></td><td></td><td>0.082</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10008">김선빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>3.0</td><td>3</td><td>1</td><td>2</td><td>0</td><td>100.0</td><td>9.00</td><td style="">-0.15</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.13</td><td>-0.16</td><td></td><td></td><td>-0.012</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12537">전상현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>66</td><td>0</td><td>66.0</td><td>9</td><td>2</td><td>6</td><td>1</td><td>88.9</td><td>1.09</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15063">황동하</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>25</td><td>21</td><td>103.1</td><td>18</td><td>5</td><td>13</td><td>0</td><td>100.0</td><td>1.57</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14611">박민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>3</td><td>0</td><td>4.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.03</td><td>0.25</td><td></td><td></td><td>0.003</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15435">곽도규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>67</td><td>0</td><td>55.2</td><td>13</td><td>3</td><td>7</td><td>3</td><td>76.9</td><td>1.62</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15057">최지민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>54</td><td>0</td><td>46.0</td><td>7</td><td>2</td><td>4</td><td>1</td><td>85.7</td><td>1.17</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14608">정해영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>53</td><td>0</td><td>50.2</td><td>8</td><td>3</td><td>5</td><td>0</td><td>100.0</td><td>1.42</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10235">장성우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.046</td><td>114</td><td>105</td><td>856.1</td><td>838</td><td>780</td><td>56</td><td>2</td><td>99.8</td><td>8.79</td><td style="">-0.84</td><td></td><td>2.09</td><td></td><td>0.32</td><td>-3.44</td><td>3.83</td><td></td><td>0.82</td><td>0.90</td><td>10.63</td><td>11.45</td><td>0.075</td><td style="background-color:#F3F3F3; font-weight:bold;">1.046</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10320">김상수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.690</td><td>78</td><td>71</td><td>581.2</td><td>280</td><td>120</td><td>150</td><td>10</td><td>96.4</td><td>4.18</td><td style="">2.08</td><td></td><td>0.14</td><td>-0.17</td><td></td><td></td><td></td><td></td><td>2.06</td><td>2.62</td><td>5.50</td><td>7.56</td><td>0.188</td><td style="background-color:#F3F3F3; font-weight:bold;">0.690</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11397">오윤석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.553</td><td>64</td><td>47</td><td>422.0</td><td>218</td><td>76</td><td>140</td><td>2</td><td>99.1</td><td>4.61</td><td style="">2.44</td><td></td><td>1.55</td><td>0.23</td><td></td><td></td><td></td><td></td><td>4.21</td><td>8.31</td><td>1.84</td><td>6.05</td><td>0.385</td><td style="background-color:#F3F3F3; font-weight:bold;">0.553</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13177">조대현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.392</td><td>26</td><td>12</td><td>120.0</td><td>111</td><td>100</td><td>11</td><td>0</td><td>100.0</td><td>8.33</td><td style="">-0.15</td><td></td><td>0.43</td><td></td><td>0.05</td><td>2.57</td><td>0.44</td><td></td><td>3.21</td><td>17.79</td><td>1.08</td><td>4.29</td><td>0.293</td><td style="background-color:#F3F3F3; font-weight:bold;">0.392</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10840">신본기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.378</td><td>50</td><td>22</td><td>220.2</td><td>113</td><td>38</td><td>71</td><td>4</td><td>96.5</td><td>4.45</td><td style="">0.44</td><td></td><td>-0.05</td><td>1.93</td><td></td><td></td><td></td><td></td><td>2.32</td><td>3.98</td><td>1.82</td><td>4.14</td><td>0.212</td><td style="background-color:#F3F3F3; font-weight:bold;">0.378</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11334">심우준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.287</td><td>53</td><td>49</td><td>431.2</td><td>227</td><td>93</td><td>126</td><td>8</td><td>96.5</td><td>4.57</td><td style="">1.35</td><td></td><td>-0.19</td><td>-1.82</td><td></td><td></td><td></td><td></td><td>-0.66</td><td>-1.79</td><td>3.80</td><td>3.14</td><td>-0.060</td><td style="background-color:#F3F3F3; font-weight:bold;">0.287</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15519">정준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.227</td><td>33</td><td>18</td><td>168.1</td><td>46</td><td>44</td><td>0</td><td>2</td><td>95.7</td><td>2.35</td><td style="">3.04</td><td>0.53</td><td>-0.50</td><td></td><td></td><td></td><td></td><td></td><td>3.08</td><td>10.32</td><td>-0.60</td><td>2.48</td><td>0.281</td><td style="background-color:#F3F3F3; font-weight:bold;">0.227</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11333">문상철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.148</td><td>88</td><td>78</td><td>638.2</td><td>619</td><td>563</td><td>50</td><td>6</td><td>99.0</td><td>8.64</td><td style="">8.27</td><td></td><td>0.15</td><td></td><td>-0.32</td><td></td><td></td><td></td><td>8.10</td><td>9.34</td><td>-6.48</td><td>1.62</td><td>0.740</td><td style="background-color:#F3F3F3; font-weight:bold;">0.148</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13151">이호연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.142</td><td>11</td><td>5</td><td>43.0</td><td>6</td><td>2</td><td>4</td><td>0</td><td>100.0</td><td>1.26</td><td style="">1.03</td><td></td><td>0.30</td><td>0.23</td><td></td><td></td><td></td><td></td><td>1.55</td><td>8.28</td><td>0.00</td><td>1.55</td><td>0.142</td><td style="background-color:#F3F3F3; font-weight:bold;">0.142</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15097">김병준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.142</td><td>16</td><td>3</td><td>41.0</td><td>15</td><td>13</td><td>2</td><td>0</td><td>100.0</td><td>3.29</td><td style="">1.46</td><td>0.00</td><td>0.09</td><td></td><td></td><td></td><td></td><td></td><td>1.55</td><td>6.38</td><td>0.00</td><td>1.55</td><td>0.142</td><td style="background-color:#F3F3F3; font-weight:bold;">0.142</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12995">로하스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.140</td><td>85</td><td>58</td><td>540.0</td><td>151</td><td>149</td><td>2</td><td>0</td><td>100.0</td><td>2.52</td><td style="">5.33</td><td>-1.50</td><td>0.61</td><td></td><td></td><td></td><td></td><td></td><td>4.44</td><td>4.44</td><td>-2.91</td><td>1.53</td><td>0.406</td><td style="background-color:#F3F3F3; font-weight:bold;">0.140</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12943">조용호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.136</td><td>49</td><td>32</td><td>295.0</td><td>59</td><td>58</td><td>0</td><td>1</td><td>98.3</td><td>1.77</td><td style="">2.16</td><td>0.25</td><td>0.39</td><td></td><td></td><td></td><td></td><td></td><td>2.79</td><td>6.70</td><td>-1.30</td><td>1.49</td><td>0.255</td><td style="background-color:#F3F3F3; font-weight:bold;">0.136</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11214">장준원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.098</td><td>11</td><td>2</td><td>34.0</td><td>15</td><td>9</td><td>6</td><td>0</td><td>100.0</td><td>3.97</td><td style="">0.81</td><td></td><td>0.30</td><td>-0.17</td><td></td><td></td><td></td><td></td><td>0.94</td><td>7.92</td><td>0.14</td><td>1.08</td><td>0.085</td><td style="background-color:#F3F3F3; font-weight:bold;">0.098</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12941">홍현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.097</td><td>9</td><td>0</td><td>17.2</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>2.55</td><td style="">1.02</td><td>0.05</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>1.09</td><td>5.59</td><td>-0.03</td><td>1.06</td><td>0.099</td><td style="background-color:#F3F3F3; font-weight:bold;">0.097</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14606">천성호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.088</td><td>3</td><td>0</td><td>11.0</td><td>5</td><td>1</td><td>4</td><td>0</td><td>100.0</td><td>4.09</td><td style="">0.82</td><td></td><td>0.08</td><td></td><td>0.07</td><td></td><td></td><td></td><td>0.96</td><td>1.85</td><td>0.00</td><td>0.96</td><td>0.088</td><td style="background-color:#F3F3F3; font-weight:bold;">0.088</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11334">심우준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.064</td><td>1</td><td>0</td><td>3.0</td><td>4</td><td>1</td><td>3</td><td>0</td><td>100.0</td><td>12.00</td><td style="">0.68</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.69</td><td>1.89</td><td>0.01</td><td>0.70</td><td>0.063</td><td style="background-color:#F3F3F3; font-weight:bold;">0.064</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13006">안치영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.064</td><td>14</td><td>12</td><td>91.0</td><td>22</td><td>22</td><td>0</td><td>0</td><td>100.0</td><td>2.18</td><td style="">0.87</td><td>-0.36</td><td>0.19</td><td></td><td></td><td></td><td></td><td></td><td>0.70</td><td>3.25</td><td>0.00</td><td>0.70</td><td>0.064</td><td style="background-color:#F3F3F3; font-weight:bold;">0.064</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10835">김준태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.054</td><td>18</td><td>3</td><td>57.1</td><td>41</td><td>39</td><td>2</td><td>0</td><td>100.0</td><td>6.44</td><td style="">-0.01</td><td></td><td>0.21</td><td></td><td></td><td>-0.44</td><td>0.34</td><td></td><td>0.00</td><td>-0.02</td><td>0.60</td><td>0.60</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">0.054</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14110">박민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.050</td><td>2</td><td>0</td><td>5.0</td><td>3</td><td>0</td><td>3</td><td>0</td><td>100.0</td><td>5.40</td><td style="">0.32</td><td></td><td>0.03</td><td>0.19</td><td></td><td></td><td></td><td></td><td>0.55</td><td>3.97</td><td>0.00</td><td>0.55</td><td>0.050</td><td style="background-color:#F3F3F3; font-weight:bold;">0.050</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14777">권동진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.050</td><td>7</td><td>2</td><td>24.1</td><td>13</td><td>6</td><td>7</td><td>0</td><td>100.0</td><td>4.81</td><td style="">0.55</td><td></td><td>0.15</td><td>-0.23</td><td></td><td></td><td></td><td></td><td>0.47</td><td>7.46</td><td>0.08</td><td>0.55</td><td>0.043</td><td style="background-color:#F3F3F3; font-weight:bold;">0.050</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15519">정준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.041</td><td>7</td><td>1</td><td>15.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>2.40</td><td style="">0.56</td><td>-0.09</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.49</td><td>1.62</td><td>-0.04</td><td>0.45</td><td>0.044</td><td style="background-color:#F3F3F3; font-weight:bold;">0.041</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14191">강민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.037</td><td>1</td><td>0</td><td>2.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.42</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.43</td><td>61.21</td><td>-0.02</td><td>0.41</td><td>0.039</td><td style="background-color:#F3F3F3; font-weight:bold;">0.037</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14606">천성호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.028</td><td>7</td><td>4</td><td>33.2</td><td>8</td><td>7</td><td>1</td><td>0</td><td>100.0</td><td>2.14</td><td style="">0.18</td><td>0.23</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>0.45</td><td>0.86</td><td>-0.14</td><td>0.31</td><td>0.041</td><td style="background-color:#F3F3F3; font-weight:bold;">0.028</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11339">김민혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.028</td><td>8</td><td>4</td><td>34.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>1.32</td><td style="">0.50</td><td>-0.14</td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>0.46</td><td>0.58</td><td>-0.16</td><td>0.30</td><td>0.042</td><td style="background-color:#F3F3F3; font-weight:bold;">0.028</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11214">장준원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.026</td><td>4</td><td>3</td><td>23.0</td><td>3</td><td>2</td><td>1</td><td>0</td><td>100.0</td><td>1.17</td><td style="">0.13</td><td></td><td>0.16</td><td></td><td></td><td></td><td></td><td></td><td>0.29</td><td>2.43</td><td>0.00</td><td>0.29</td><td>0.026</td><td style="background-color:#F3F3F3; font-weight:bold;">0.026</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15519">정준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.022</td><td>3</td><td>2</td><td>13.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>2.08</td><td style="">0.52</td><td>-0.31</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.24</td><td>0.79</td><td>0.00</td><td>0.24</td><td>0.022</td><td style="background-color:#F3F3F3; font-weight:bold;">0.022</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11397">오윤석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.015</td><td>5</td><td>0</td><td>7.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>6.43</td><td style="">0.17</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.21</td><td>0.41</td><td>-0.04</td><td>0.17</td><td>0.019</td><td style="background-color:#F3F3F3; font-weight:bold;">0.015</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13006">안치영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.015</td><td>3</td><td>0</td><td>4.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>2.25</td><td style="">0.17</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.18</td><td>0.83</td><td>-0.02</td><td>0.16</td><td>0.016</td><td style="background-color:#F3F3F3; font-weight:bold;">0.015</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11333">문상철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.014</td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.14</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.15</td><td>0.17</td><td>0.00</td><td>0.15</td><td>0.014</td><td style="background-color:#F3F3F3; font-weight:bold;">0.014</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12995">로하스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.005</td><td>6</td><td>2</td><td>27.0</td><td>12</td><td>11</td><td>1</td><td>0</td><td>100.0</td><td>4.00</td><td style="">-0.14</td><td>0.14</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>0.05</td><td>0.05</td><td>0.00</td><td>0.05</td><td>0.005</td><td style="background-color:#F3F3F3; font-weight:bold;">0.005</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14606">천성호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.000</td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">0.000</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13151">이호연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.001</td><td>1</td><td>0</td><td>2.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>18.00</td><td style="">0.00</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.05</td><td>-0.02</td><td>-0.01</td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.001</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13168">강백호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.004</td><td>30</td><td>19</td><td>169.2</td><td>156</td><td>137</td><td>17</td><td>2</td><td>98.7</td><td>8.17</td><td style="">-0.12</td><td></td><td>-0.39</td><td></td><td></td><td>0.95</td><td>-3.71</td><td></td><td>-2.15</td><td>-2.15</td><td>2.11</td><td>-0.04</td><td>-0.197</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.004</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11333">문상철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.006</td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.17</td><td>0.11</td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.06</td><td>-0.07</td><td>-0.01</td><td>-0.07</td><td>-0.005</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.006</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14605">윤준혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.009</td><td>2</td><td>0</td><td>3.0</td><td>3</td><td>1</td><td>1</td><td>1</td><td>66.7</td><td>6.00</td><td style="">0.36</td><td></td><td>-0.48</td><td></td><td></td><td></td><td></td><td></td><td>-0.12</td><td>-1.31</td><td>0.02</td><td>-0.10</td><td>-0.011</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.009</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11339">김민혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.021</td><td>82</td><td>70</td><td>553.0</td><td>131</td><td>128</td><td>1</td><td>2</td><td>98.5</td><td>2.10</td><td style="">3.88</td><td>-0.73</td><td>-0.37</td><td></td><td></td><td></td><td></td><td></td><td>2.77</td><td>3.47</td><td>-3.00</td><td>-0.23</td><td>0.253</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.021</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11342">송민섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.029</td><td>10</td><td>0</td><td>24.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>1.13</td><td style="">-0.25</td><td>-0.11</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>-0.32</td><td>-1.27</td><td>0.00</td><td>-0.32</td><td>-0.029</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.029</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13006">안치영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.037</td><td>13</td><td>1</td><td>30.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>0.90</td><td style="">-0.72</td><td>0.30</td><td>0.09</td><td></td><td></td><td></td><td></td><td></td><td>-0.32</td><td>-1.50</td><td>-0.08</td><td>-0.40</td><td>-0.029</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.037</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14603">강현우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.038</td><td>17</td><td>5</td><td>81.0</td><td>76</td><td>71</td><td>3</td><td>2</td><td>97.4</td><td>8.22</td><td style="">-0.24</td><td></td><td>-0.71</td><td></td><td></td><td>0.35</td><td>-0.90</td><td></td><td>-1.23</td><td>-9.84</td><td>0.82</td><td>-0.41</td><td>-0.112</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.038</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14779">김건형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.045</td><td>12</td><td>9</td><td>66.0</td><td>22</td><td>22</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-0.70</td><td>0.26</td><td>0.20</td><td></td><td></td><td></td><td></td><td></td><td>-0.25</td><td>-2.72</td><td>-0.25</td><td>-0.50</td><td>-0.022</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.045</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10840">신본기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.050</td><td>18</td><td>3</td><td>51.0</td><td>10</td><td>3</td><td>7</td><td>0</td><td>100.0</td><td>1.76</td><td style="">-0.68</td><td></td><td>0.35</td><td>-0.22</td><td></td><td></td><td></td><td></td><td>-0.55</td><td>-0.94</td><td>0.00</td><td>-0.55</td><td>-0.050</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.050</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10469">박경수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.051</td><td>3</td><td>0</td><td>3.1</td><td>2</td><td>1</td><td>1</td><td>0</td><td>100.0</td><td>5.40</td><td style="">-0.58</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.56</td><td>-16.22</td><td>0.01</td><td>-0.55</td><td>-0.051</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.051</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10470">박병호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.075</td><td>32</td><td>23</td><td>227.1</td><td>206</td><td>189</td><td>15</td><td>2</td><td>99.0</td><td>8.08</td><td style="">1.19</td><td></td><td>0.12</td><td></td><td>0.06</td><td></td><td></td><td></td><td>1.36</td><td>1.64</td><td>-2.18</td><td>-0.82</td><td>0.125</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.075</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10320">김상수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.084</td><td>38</td><td>35</td><td>281.1</td><td>165</td><td>72</td><td>89</td><td>4</td><td>97.6</td><td>5.15</td><td style="">-2.13</td><td></td><td>-0.31</td><td>0.12</td><td></td><td></td><td></td><td></td><td>-2.32</td><td>-2.96</td><td>1.41</td><td>-0.91</td><td>-0.212</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.084</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15097">김병준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.093</td><td>10</td><td>1</td><td>20.2</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>3.05</td><td style="">-0.45</td><td>-0.58</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>-0.96</td><td>-3.95</td><td>-0.06</td><td>-1.02</td><td>-0.088</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.093</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15092">안현민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.097</td><td>13</td><td>6</td><td>52.0</td><td>14</td><td>13</td><td>1</td><td>0</td><td>100.0</td><td>2.42</td><td style="">-1.35</td><td>0.46</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>-0.82</td><td>-7.41</td><td>-0.24</td><td>-1.06</td><td>-0.075</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.097</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14777">권동진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.101</td><td>1</td><td>0</td><td>4.0</td><td>2</td><td>0</td><td>1</td><td>1</td><td>50.0</td><td>2.25</td><td style="">-0.64</td><td></td><td>-0.47</td><td></td><td></td><td></td><td></td><td></td><td>-1.11</td><td>-17.76</td><td>0.00</td><td>-1.11</td><td>-0.101</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.101</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14605">윤준혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.107</td><td>8</td><td>4</td><td>36.1</td><td>3</td><td>1</td><td>2</td><td>0</td><td>100.0</td><td>0.74</td><td style="">-1.49</td><td></td><td>0.25</td><td></td><td>0.07</td><td></td><td></td><td></td><td>-1.17</td><td>-12.92</td><td>0.00</td><td>-1.17</td><td>-0.107</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.107</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12941">홍현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.122</td><td>8</td><td>2</td><td>24.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>1.50</td><td style="">-1.50</td><td>0.12</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>-1.33</td><td>-6.86</td><td>0.00</td><td>-1.33</td><td>-0.122</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.122</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11397">오윤석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.135</td><td>8</td><td>1</td><td>25.0</td><td>3</td><td>0</td><td>2</td><td>1</td><td>66.7</td><td>0.72</td><td style="">-1.21</td><td></td><td>-0.33</td><td></td><td>0.07</td><td></td><td></td><td></td><td>-1.47</td><td>-2.91</td><td>0.00</td><td>-1.47</td><td>-0.135</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.135</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14110">박민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.138</td><td>6</td><td>0</td><td>17.0</td><td>6</td><td>3</td><td>2</td><td>1</td><td>83.3</td><td>2.65</td><td style="">-1.20</td><td></td><td>-0.40</td><td></td><td></td><td></td><td></td><td></td><td>-1.60</td><td>-11.49</td><td>0.08</td><td>-1.52</td><td>-0.146</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.138</td></tr><tr><td style="text-align:center;">52</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11339">김민혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.157</td><td>14</td><td>13</td><td>105.1</td><td>29</td><td>28</td><td>0</td><td>1</td><td>96.6</td><td>2.39</td><td style="">-0.88</td><td>-0.56</td><td>-0.28</td><td></td><td></td><td></td><td></td><td></td><td>-1.72</td><td>-2.15</td><td>0.00</td><td>-1.72</td><td>-0.157</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.157</td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14110">박민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.162</td><td>5</td><td>0</td><td>8.1</td><td>5</td><td>1</td><td>2</td><td>2</td><td>60.0</td><td>3.24</td><td style="">-1.08</td><td></td><td>-0.93</td><td>0.19</td><td></td><td></td><td></td><td></td><td>-1.83</td><td>-13.17</td><td>0.06</td><td>-1.77</td><td>-0.167</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.162</td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10840">신본기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.164</td><td>27</td><td>8</td><td>98.0</td><td>56</td><td>21</td><td>32</td><td>3</td><td>94.6</td><td>4.87</td><td style="">-1.31</td><td></td><td>-0.91</td><td></td><td></td><td></td><td></td><td></td><td>-2.23</td><td>-3.82</td><td>0.43</td><td>-1.80</td><td>-0.203</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.164</td></tr><tr><td style="text-align:center;">55</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13151">이호연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.173</td><td>10</td><td>3</td><td>32.0</td><td>17</td><td>6</td><td>11</td><td>0</td><td>100.0</td><td>4.78</td><td style="">-2.10</td><td></td><td>0.19</td><td>-0.12</td><td></td><td></td><td></td><td></td><td>-2.02</td><td>-10.78</td><td>0.13</td><td>-1.89</td><td>-0.185</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.173</td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13168">강백호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.199</td><td>5</td><td>3</td><td>24.0</td><td>4</td><td>2</td><td>0</td><td>2</td><td>50.0</td><td>0.75</td><td style="">-1.05</td><td>-0.03</td><td>-0.93</td><td></td><td></td><td></td><td></td><td></td><td>-2.01</td><td>-2.01</td><td>-0.16</td><td>-2.17</td><td>-0.184</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.199</td></tr><tr><td style="text-align:center;">57</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12941">홍현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.201</td><td>15</td><td>1</td><td>29.0</td><td>9</td><td>8</td><td>0</td><td>1</td><td>88.9</td><td>2.48</td><td style="">-1.76</td><td>0.06</td><td>-0.41</td><td></td><td></td><td></td><td></td><td></td><td>-2.12</td><td>-10.91</td><td>-0.08</td><td>-2.20</td><td>-0.194</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.201</td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12943">조용호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.265</td><td>13</td><td>5</td><td>57.2</td><td>10</td><td>9</td><td>1</td><td>0</td><td>100.0</td><td>1.56</td><td style="">-2.84</td><td>0.14</td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>-2.63</td><td>-6.32</td><td>-0.27</td><td>-2.90</td><td>-0.241</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.265</td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14606">천성호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.269</td><td>55</td><td>49</td><td>403.1</td><td>193</td><td>73</td><td>116</td><td>4</td><td>97.9</td><td>4.22</td><td style="">-5.56</td><td></td><td>0.43</td><td>0.00</td><td></td><td></td><td></td><td></td><td>-5.13</td><td>-9.86</td><td>2.19</td><td>-2.94</td><td>-0.469</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.269</td></tr><tr><td style="text-align:center;">60</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11342">송민섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.279</td><td>24</td><td>0</td><td>42.1</td><td>8</td><td>7</td><td>0</td><td>1</td><td>87.5</td><td>1.49</td><td style="">-2.38</td><td>-0.20</td><td>-0.37</td><td></td><td></td><td></td><td></td><td></td><td>-2.96</td><td>-11.83</td><td>-0.10</td><td>-3.06</td><td>-0.270</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.279</td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10407">황재균</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.280</td><td>135</td><td>128</td><td>1085.0</td><td>268</td><td>83</td><td>171</td><td>14</td><td>94.8</td><td>2.11</td><td style="">-3.29</td><td></td><td>0.42</td><td>-0.21</td><td>0.01</td><td></td><td></td><td></td><td>-3.06</td><td>-3.22</td><td>0.00</td><td>-3.06</td><td>-0.280</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.280</td></tr><tr><td style="text-align:center;">62</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12995">로하스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.532</td><td>80</td><td>75</td><td>575.0</td><td>124</td><td>119</td><td>3</td><td>2</td><td>98.4</td><td>1.91</td><td style="">-3.59</td><td>0.29</td><td>0.73</td><td></td><td></td><td></td><td></td><td></td><td>-2.57</td><td>-2.57</td><td>-3.25</td><td>-5.82</td><td>-0.235</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.532</td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11212">배정대</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.559</td><td>113</td><td>110</td><td>958.0</td><td>276</td><td>266</td><td>3</td><td>7</td><td>97.5</td><td>2.53</td><td style="">-5.70</td><td>1.10</td><td>-1.52</td><td></td><td></td><td></td><td></td><td></td><td>-6.12</td><td>-7.80</td><td>0.00</td><td>-6.12</td><td>-0.559</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.559</td></tr><tr><td style="text-align:center;">64</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10400">오재일</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.783</td><td>55</td><td>43</td><td>406.1</td><td>360</td><td>339</td><td>18</td><td>3</td><td>99.2</td><td>7.91</td><td style="">-4.50</td><td></td><td>0.50</td><td></td><td>-0.42</td><td></td><td></td><td></td><td>-4.41</td><td>-6.05</td><td>-4.16</td><td>-8.57</td><td>-0.403</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.783</td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10737">박시영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>24</td><td>0</td><td>25.1</td><td>5</td><td>2</td><td>3</td><td>0</td><td>100.0</td><td>1.78</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11323">주권</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>48</td><td>1</td><td>58.0</td><td>18</td><td>5</td><td>12</td><td>1</td><td>94.4</td><td>2.64</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14869">김영현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>8</td><td>0</td><td>7.1</td><td>2</td><td>0</td><td>1</td><td>1</td><td>50.0</td><td>1.23</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13167">김민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>70</td><td>1</td><td>77.1</td><td>13</td><td>4</td><td>9</td><td>0</td><td>100.0</td><td>1.51</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14111">이선우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>6</td><td>1</td><td>10.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>1.80</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15097">김병준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>5</td><td>0</td><td>7.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>2.57</td><td style="">-0.12</td><td>-0.37</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.49</td><td>-2.01</td><td></td><td></td><td>-0.045</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11342">송민섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>2.1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>3.86</td><td style="">0.48</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.49</td><td>1.95</td><td></td><td></td><td>0.044</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15089">박영현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>66</td><td>0</td><td>76.2</td><td>10</td><td>4</td><td>5</td><td>1</td><td>90.0</td><td>1.06</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15527">강건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>4</td><td>1</td><td>4.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10407">황재균</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>4</td><td>0</td><td>5.0</td><td>3</td><td>1</td><td>2</td><td>0</td><td>100.0</td><td>5.40</td><td style="">-0.49</td><td></td><td>0.04</td><td>0.05</td><td></td><td></td><td></td><td></td><td>-0.40</td><td>-0.42</td><td></td><td></td><td>-0.036</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12572">박세진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>6</td><td>0</td><td>5.1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14667">성재헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>29</td><td>1</td><td>32.0</td><td>10</td><td>1</td><td>8</td><td>1</td><td>90.0</td><td>2.53</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10523">우규민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>44</td><td>0</td><td>43.1</td><td>7</td><td>1</td><td>5</td><td>1</td><td>85.7</td><td>1.25</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14108">손동현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>41</td><td>0</td><td>47.1</td><td>8</td><td>3</td><td>3</td><td>2</td><td>75.0</td><td>1.14</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10407">황재균</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>18.00</td><td style="">0.85</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.86</td><td>0.90</td><td></td><td></td><td>0.078</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15034">이재현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.529</td><td>107</td><td>99</td><td>862.1</td><td>409</td><td>186</td><td>212</td><td>11</td><td>97.3</td><td>4.15</td><td style="">7.13</td><td></td><td>2.13</td><td>-1.29</td><td></td><td></td><td></td><td></td><td>7.96</td><td>10.52</td><td>8.78</td><td>16.74</td><td>0.727</td><td style="background-color:#F3F3F3; font-weight:bold;">1.529</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10232">강민호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.181</td><td>120</td><td>96</td><td>803.0</td><td>686</td><td>631</td><td>53</td><td>2</td><td>99.7</td><td>7.67</td><td style="">-0.56</td><td></td><td>1.90</td><td></td><td>-0.10</td><td>0.95</td><td>1.84</td><td></td><td>3.47</td><td>3.68</td><td>9.46</td><td>12.93</td><td>0.317</td><td style="background-color:#F3F3F3; font-weight:bold;">1.181</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15035">김영웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.785</td><td>38</td><td>33</td><td>304.2</td><td>157</td><td>70</td><td>82</td><td>5</td><td>96.8</td><td>4.49</td><td style="">3.33</td><td></td><td>0.19</td><td>2.16</td><td></td><td></td><td></td><td></td><td>5.69</td><td>6.50</td><td>2.90</td><td>8.59</td><td>0.520</td><td style="background-color:#F3F3F3; font-weight:bold;">0.785</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14618">김지찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.489</td><td>117</td><td>103</td><td>859.0</td><td>262</td><td>259</td><td>0</td><td>3</td><td>98.9</td><td>2.71</td><td style="">4.85</td><td>0.22</td><td>0.28</td><td></td><td></td><td></td><td></td><td></td><td>5.35</td><td>5.71</td><td>0.00</td><td>5.35</td><td>0.489</td><td style="background-color:#F3F3F3; font-weight:bold;">0.489</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11422">전병우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.386</td><td>48</td><td>30</td><td>267.1</td><td>81</td><td>31</td><td>48</td><td>2</td><td>97.5</td><td>2.66</td><td style="">2.60</td><td></td><td>0.83</td><td>0.96</td><td>-0.17</td><td></td><td></td><td></td><td>4.22</td><td>10.48</td><td>0.00</td><td>4.22</td><td>0.386</td><td style="background-color:#F3F3F3; font-weight:bold;">0.386</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14867">김현준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.359</td><td>40</td><td>24</td><td>218.1</td><td>64</td><td>62</td><td>1</td><td>1</td><td>98.4</td><td>2.60</td><td style="">4.33</td><td>0.45</td><td>0.16</td><td></td><td></td><td></td><td></td><td></td><td>4.94</td><td>9.00</td><td>-1.01</td><td>3.93</td><td>0.451</td><td style="background-color:#F3F3F3; font-weight:bold;">0.359</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12562">이성규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.293</td><td>51</td><td>33</td><td>294.1</td><td>83</td><td>78</td><td>2</td><td>3</td><td>96.4</td><td>2.45</td><td style="">4.91</td><td>0.21</td><td>-0.62</td><td></td><td></td><td></td><td></td><td></td><td>4.50</td><td>5.32</td><td>-1.30</td><td>3.20</td><td>0.411</td><td style="background-color:#F3F3F3; font-weight:bold;">0.293</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14863">김동진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.261</td><td>23</td><td>8</td><td>91.0</td><td>48</td><td>17</td><td>31</td><td>0</td><td>100.0</td><td>4.75</td><td style="">1.90</td><td></td><td>0.55</td><td>0.10</td><td></td><td></td><td></td><td></td><td>2.54</td><td>12.21</td><td>0.31</td><td>2.85</td><td>0.232</td><td style="background-color:#F3F3F3; font-weight:bold;">0.261</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11255">강한울</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.245</td><td>9</td><td>3</td><td>41.0</td><td>15</td><td>1</td><td>14</td><td>0</td><td>100.0</td><td>3.29</td><td style="">2.19</td><td></td><td>0.28</td><td>0.21</td><td></td><td></td><td></td><td></td><td>2.68</td><td>21.46</td><td>0.00</td><td>2.68</td><td>0.245</td><td style="background-color:#F3F3F3; font-weight:bold;">0.245</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14117">이병헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.234</td><td>90</td><td>44</td><td>421.2</td><td>365</td><td>341</td><td>21</td><td>3</td><td>99.2</td><td>7.73</td><td style="">-0.50</td><td></td><td>0.02</td><td></td><td>-0.44</td><td>0.01</td><td>-0.57</td><td></td><td>-1.31</td><td>-1.98</td><td>3.86</td><td>2.56</td><td>-0.119</td><td style="background-color:#F3F3F3; font-weight:bold;">0.234</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16162">디아즈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.206</td><td>18</td><td>18</td><td>151.0</td><td>136</td><td>121</td><td>14</td><td>1</td><td>99.3</td><td>8.05</td><td style="">3.48</td><td></td><td>0.24</td><td></td><td>0.06</td><td></td><td></td><td></td><td>3.78</td><td>18.77</td><td>-1.52</td><td>2.26</td><td>0.345</td><td style="background-color:#F3F3F3; font-weight:bold;">0.206</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15868">김호진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.203</td><td>12</td><td>5</td><td>47.0</td><td>13</td><td>3</td><td>10</td><td>0</td><td>100.0</td><td>2.49</td><td style="">1.50</td><td></td><td>0.32</td><td>0.32</td><td>0.07</td><td></td><td></td><td></td><td>2.22</td><td>12.28</td><td>0.00</td><td>2.22</td><td>0.203</td><td style="background-color:#F3F3F3; font-weight:bold;">0.203</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15036">김재혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.197</td><td>5</td><td>2</td><td>23.0</td><td>10</td><td>10</td><td>0</td><td>0</td><td>100.0</td><td>3.91</td><td style="">2.26</td><td>-0.02</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>2.26</td><td>9.30</td><td>-0.10</td><td>2.16</td><td>0.207</td><td style="background-color:#F3F3F3; font-weight:bold;">0.197</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13161">윤정빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.193</td><td>49</td><td>30</td><td>285.1</td><td>67</td><td>66</td><td>1</td><td>0</td><td>100.0</td><td>2.11</td><td style="">2.24</td><td>0.32</td><td>0.86</td><td></td><td></td><td></td><td></td><td></td><td>3.43</td><td>7.16</td><td>-1.32</td><td>2.11</td><td>0.313</td><td style="background-color:#F3F3F3; font-weight:bold;">0.193</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15035">김영웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.171</td><td>87</td><td>76</td><td>639.1</td><td>187</td><td>62</td><td>115</td><td>10</td><td>94.7</td><td>2.49</td><td style="">3.04</td><td></td><td>-0.13</td><td>-0.53</td><td>-0.52</td><td></td><td></td><td></td><td>1.87</td><td>2.14</td><td>0.00</td><td>1.87</td><td>0.171</td><td style="background-color:#F3F3F3; font-weight:bold;">0.171</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11336">김태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.163</td><td>4</td><td>2</td><td>20.0</td><td>6</td><td>6</td><td>0</td><td>0</td><td>100.0</td><td>2.70</td><td style="">1.60</td><td>0.21</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>1.87</td><td>22.45</td><td>-0.09</td><td>1.78</td><td>0.171</td><td style="background-color:#F3F3F3; font-weight:bold;">0.163</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14116">양우현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.154</td><td>5</td><td>4</td><td>32.0</td><td>18</td><td>7</td><td>11</td><td>0</td><td>100.0</td><td>5.06</td><td style="">0.93</td><td></td><td>0.19</td><td>0.43</td><td></td><td></td><td></td><td></td><td>1.56</td><td>32.05</td><td>0.13</td><td>1.69</td><td>0.142</td><td style="background-color:#F3F3F3; font-weight:bold;">0.154</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15875">양도근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.140</td><td>8</td><td>2</td><td>29.0</td><td>9</td><td>5</td><td>4</td><td>0</td><td>100.0</td><td>2.79</td><td style="">1.03</td><td></td><td>0.26</td><td>0.09</td><td></td><td></td><td></td><td></td><td>1.38</td><td>12.38</td><td>0.16</td><td>1.54</td><td>0.126</td><td style="background-color:#F3F3F3; font-weight:bold;">0.140</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15499">김재상</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.135</td><td>32</td><td>24</td><td>205.1</td><td>101</td><td>36</td><td>63</td><td>2</td><td>98.0</td><td>4.34</td><td style="">0.45</td><td></td><td>0.24</td><td>-0.06</td><td></td><td></td><td></td><td></td><td>0.62</td><td>2.56</td><td>0.85</td><td>1.47</td><td>0.057</td><td style="background-color:#F3F3F3; font-weight:bold;">0.135</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12988">안주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.112</td><td>2</td><td>0</td><td>3.0</td><td>3</td><td>1</td><td>2</td><td>0</td><td>100.0</td><td>9.00</td><td style="">1.20</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>1.22</td><td>2.15</td><td>0.00</td><td>1.22</td><td>0.112</td><td style="background-color:#F3F3F3; font-weight:bold;">0.112</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12936">김성윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.105</td><td>11</td><td>7</td><td>63.1</td><td>15</td><td>14</td><td>1</td><td>0</td><td>100.0</td><td>2.13</td><td style="">2.06</td><td>-0.76</td><td>0.19</td><td></td><td></td><td></td><td></td><td></td><td>1.49</td><td>6.72</td><td>-0.34</td><td>1.15</td><td>0.136</td><td style="background-color:#F3F3F3; font-weight:bold;">0.105</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15503">류승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.088</td><td>4</td><td>0</td><td>7.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>3.86</td><td style="">0.96</td><td>0.01</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.99</td><td>28.43</td><td>-0.02</td><td>0.97</td><td>0.090</td><td style="background-color:#F3F3F3; font-weight:bold;">0.088</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12936">김성윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.085</td><td>24</td><td>9</td><td>105.1</td><td>33</td><td>32</td><td>1</td><td>0</td><td>100.0</td><td>2.82</td><td style="">0.60</td><td>0.11</td><td>0.22</td><td></td><td></td><td></td><td></td><td></td><td>0.93</td><td>4.20</td><td>0.00</td><td>0.93</td><td>0.085</td><td style="background-color:#F3F3F3; font-weight:bold;">0.085</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14866">이창용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.072</td><td>6</td><td>4</td><td>37.0</td><td>32</td><td>29</td><td>2</td><td>1</td><td>96.9</td><td>7.54</td><td style="">1.45</td><td></td><td>-0.32</td><td></td><td></td><td></td><td></td><td></td><td>1.13</td><td>18.12</td><td>-0.34</td><td>0.79</td><td>0.103</td><td style="background-color:#F3F3F3; font-weight:bold;">0.072</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13161">윤정빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.070</td><td>7</td><td>1</td><td>31.0</td><td>22</td><td>21</td><td>1</td><td>0</td><td>100.0</td><td>6.39</td><td style="">0.87</td><td></td><td>0.15</td><td></td><td></td><td></td><td></td><td></td><td>1.02</td><td>2.13</td><td>-0.26</td><td>0.76</td><td>0.093</td><td style="background-color:#F3F3F3; font-weight:bold;">0.070</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15035">김영웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.068</td><td>7</td><td>5</td><td>35.0</td><td>12</td><td>9</td><td>3</td><td>0</td><td>100.0</td><td>3.09</td><td style="">0.69</td><td></td><td>0.21</td><td>-0.34</td><td></td><td></td><td></td><td></td><td>0.57</td><td>0.65</td><td>0.18</td><td>0.75</td><td>0.052</td><td style="background-color:#F3F3F3; font-weight:bold;">0.068</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11422">전병우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.059</td><td>3</td><td>3</td><td>18.0</td><td>14</td><td>13</td><td>0</td><td>1</td><td>92.9</td><td>6.50</td><td style="">1.18</td><td></td><td>-0.41</td><td></td><td></td><td></td><td></td><td></td><td>0.77</td><td>1.90</td><td>-0.12</td><td>0.65</td><td>0.070</td><td style="background-color:#F3F3F3; font-weight:bold;">0.059</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15036">김재혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.059</td><td>4</td><td>4</td><td>31.0</td><td>25</td><td>21</td><td>4</td><td>0</td><td>100.0</td><td>7.26</td><td style="">0.81</td><td></td><td>0.15</td><td></td><td>0.06</td><td></td><td></td><td></td><td>1.02</td><td>4.21</td><td>-0.38</td><td>0.64</td><td>0.094</td><td style="background-color:#F3F3F3; font-weight:bold;">0.059</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10640">김헌곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.048</td><td>48</td><td>38</td><td>300.1</td><td>87</td><td>86</td><td>0</td><td>1</td><td>98.9</td><td>2.58</td><td style="">1.11</td><td>0.44</td><td>0.41</td><td></td><td></td><td></td><td></td><td></td><td>1.96</td><td>2.41</td><td>-1.43</td><td>0.53</td><td>0.179</td><td style="background-color:#F3F3F3; font-weight:bold;">0.048</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15499">김재상</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.042</td><td>2</td><td>0</td><td>3.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>3.00</td><td style="">0.44</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.46</td><td>1.88</td><td>0.00</td><td>0.46</td><td>0.042</td><td style="background-color:#F3F3F3; font-weight:bold;">0.042</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10640">김헌곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.034</td><td>65</td><td>27</td><td>305.0</td><td>76</td><td>76</td><td>0</td><td>0</td><td>100.0</td><td>2.24</td><td style="">1.46</td><td>-0.14</td><td>0.35</td><td></td><td></td><td></td><td></td><td></td><td>1.67</td><td>2.05</td><td>-1.29</td><td>0.38</td><td>0.152</td><td style="background-color:#F3F3F3; font-weight:bold;">0.034</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10892">구자욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.026</td><td>4</td><td>4</td><td>37.1</td><td>13</td><td>13</td><td>0</td><td>0</td><td>100.0</td><td>3.13</td><td style="">0.17</td><td>0.19</td><td>0.11</td><td></td><td></td><td></td><td></td><td></td><td>0.48</td><td>0.53</td><td>-0.19</td><td>0.29</td><td>0.043</td><td style="background-color:#F3F3F3; font-weight:bold;">0.026</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13164">공민규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.026</td><td>2</td><td>0</td><td>5.0</td><td>7</td><td>5</td><td>2</td><td>0</td><td>100.0</td><td>12.60</td><td style="">0.27</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.30</td><td>3.59</td><td>-0.02</td><td>0.28</td><td>0.027</td><td style="background-color:#F3F3F3; font-weight:bold;">0.026</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10894">류지혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.018</td><td>74</td><td>63</td><td>461.0</td><td>222</td><td>104</td><td>113</td><td>5</td><td>97.7</td><td>4.24</td><td style="">-2.21</td><td></td><td>0.78</td><td>-0.64</td><td></td><td></td><td></td><td></td><td>-2.07</td><td>-2.97</td><td>2.26</td><td>0.19</td><td>-0.189</td><td style="background-color:#F3F3F3; font-weight:bold;">0.018</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14116">양우현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.015</td><td>1</td><td>0</td><td>2.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>4.50</td><td style="">0.15</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.16</td><td>3.32</td><td>0.00</td><td>0.16</td><td>0.015</td><td style="background-color:#F3F3F3; font-weight:bold;">0.015</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11266">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.001</td><td>8</td><td>1</td><td>23.0</td><td>14</td><td>12</td><td>2</td><td>0</td><td>100.0</td><td>5.48</td><td style="">-0.09</td><td></td><td>0.08</td><td></td><td></td><td>0.00</td><td>-0.22</td><td></td><td>-0.16</td><td>-2.58</td><td>0.17</td><td>0.01</td><td>-0.015</td><td style="background-color:#F3F3F3; font-weight:bold;">0.001</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16156">카디네스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.001</td><td>1</td><td>1</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.02</td><td>-0.01</td><td>-0.01</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.001</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10894">류지혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.004</td><td>28</td><td>19</td><td>179.1</td><td>48</td><td>20</td><td>26</td><td>2</td><td>95.8</td><td>2.31</td><td style="">0.19</td><td></td><td>0.23</td><td>-0.56</td><td>0.11</td><td></td><td></td><td></td><td>-0.04</td><td>-0.06</td><td>0.00</td><td>-0.04</td><td>-0.004</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.004</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13161">윤정빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.023</td><td>7</td><td>4</td><td>31.2</td><td>8</td><td>8</td><td>0</td><td>0</td><td>100.0</td><td>2.27</td><td style="">-0.21</td><td>0.06</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-0.11</td><td>-0.24</td><td>-0.14</td><td>-0.25</td><td>-0.010</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.023</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14115">김도환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.032</td><td>1</td><td>1</td><td>6.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>7.50</td><td style="">-0.09</td><td></td><td>0.02</td><td></td><td></td><td>-0.14</td><td>-0.30</td><td></td><td>-0.42</td><td>-60.41</td><td>0.07</td><td>-0.35</td><td>-0.038</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.032</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14863">김동진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.038</td><td>6</td><td>2</td><td>25.0</td><td>8</td><td>3</td><td>5</td><td>0</td><td>100.0</td><td>2.88</td><td style="">-0.65</td><td></td><td>0.17</td><td>-0.40</td><td>0.46</td><td></td><td></td><td></td><td>-0.42</td><td>-2.01</td><td>0.00</td><td>-0.42</td><td>-0.038</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.038</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15868">김호진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.040</td><td>2</td><td>0</td><td>6.0</td><td>3</td><td>1</td><td>2</td><td>0</td><td>100.0</td><td>4.50</td><td style="">-0.51</td><td></td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-0.47</td><td>-2.61</td><td>0.03</td><td>-0.44</td><td>-0.043</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.040</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11422">전병우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.047</td><td>2</td><td>1</td><td>7.0</td><td>7</td><td>3</td><td>4</td><td>0</td><td>100.0</td><td>9.00</td><td style="">-0.60</td><td></td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-0.56</td><td>-1.38</td><td>0.04</td><td>-0.52</td><td>-0.051</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.047</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10470">박병호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.049</td><td>31</td><td>29</td><td>248.2</td><td>253</td><td>223</td><td>28</td><td>2</td><td>99.2</td><td>9.08</td><td style="">1.37</td><td></td><td>0.23</td><td></td><td>0.25</td><td></td><td></td><td></td><td>1.85</td><td>2.22</td><td>-2.38</td><td>-0.53</td><td>0.169</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.049</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15868">김호진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.050</td><td>9</td><td>2</td><td>26.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>0.69</td><td style="">-0.95</td><td></td><td>0.23</td><td></td><td></td><td></td><td></td><td></td><td>-0.72</td><td>-4.01</td><td>0.18</td><td>-0.54</td><td>-0.066</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.050</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15862">맥키넌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.055</td><td>50</td><td>49</td><td>423.1</td><td>373</td><td>335</td><td>34</td><td>4</td><td>98.9</td><td>7.84</td><td style="">3.88</td><td></td><td>0.09</td><td></td><td>-0.29</td><td></td><td></td><td></td><td>3.68</td><td>7.35</td><td>-4.28</td><td>-0.60</td><td>0.336</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.055</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14618">김지찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.058</td><td>10</td><td>0</td><td>14.0</td><td>4</td><td>3</td><td>1</td><td>0</td><td>100.0</td><td>2.57</td><td style="">-0.77</td><td></td><td>0.08</td><td></td><td></td><td></td><td></td><td></td><td>-0.69</td><td>-0.73</td><td>0.05</td><td>-0.64</td><td>-0.063</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.058</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15875">양도근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.060</td><td>9</td><td>5</td><td>46.0</td><td>29</td><td>13</td><td>16</td><td>0</td><td>100.0</td><td>5.67</td><td style="">-1.70</td><td></td><td>0.28</td><td>0.57</td><td></td><td></td><td></td><td></td><td>-0.86</td><td>-7.71</td><td>0.20</td><td>-0.66</td><td>-0.078</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.060</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10894">류지혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.080</td><td>13</td><td>3</td><td>44.2</td><td>36</td><td>34</td><td>2</td><td>0</td><td>100.0</td><td>7.25</td><td style="">-0.76</td><td></td><td>0.22</td><td></td><td></td><td></td><td></td><td></td><td>-0.54</td><td>-0.77</td><td>-0.34</td><td>-0.88</td><td>-0.049</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.080</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11336">김태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.082</td><td>3</td><td>0</td><td>11.2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.96</td><td>0.11</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.84</td><td>-10.11</td><td>-0.05</td><td>-0.89</td><td>-0.077</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.082</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11344">김재성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.089</td><td>7</td><td>2</td><td>29.0</td><td>23</td><td>20</td><td>3</td><td>0</td><td>100.0</td><td>7.14</td><td style="">-0.09</td><td></td><td>0.10</td><td></td><td>0.05</td><td>-0.82</td><td>-0.75</td><td></td><td>-1.28</td><td>-18.49</td><td>0.31</td><td>-0.97</td><td>-0.117</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.089</td></tr><tr><td style="text-align:center;">52</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12988">안주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.090</td><td>14</td><td>8</td><td>56.2</td><td>35</td><td>17</td><td>18</td><td>0</td><td>100.0</td><td>5.56</td><td style="">-1.46</td><td></td><td>0.50</td><td>-0.51</td><td></td><td></td><td></td><td></td><td>-1.47</td><td>-2.58</td><td>0.48</td><td>-0.99</td><td>-0.134</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.090</td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11344">김재성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.094</td><td>1</td><td>1</td><td>5.0</td><td>4</td><td>3</td><td>0</td><td>1</td><td>75.0</td><td>5.40</td><td style="">-0.47</td><td></td><td>-0.48</td><td></td><td></td><td></td><td></td><td></td><td>-0.94</td><td>-13.59</td><td>-0.08</td><td>-1.02</td><td>-0.086</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.094</td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14867">김현준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.099</td><td>33</td><td>12</td><td>130.1</td><td>51</td><td>48</td><td>3</td><td>0</td><td>100.0</td><td>3.52</td><td style="">-1.93</td><td>0.57</td><td>0.27</td><td></td><td></td><td></td><td></td><td></td><td>-1.08</td><td>-1.98</td><td>0.00</td><td>-1.08</td><td>-0.099</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.099</td></tr><tr><td style="text-align:center;">55</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10400">오재일</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.102</td><td>12</td><td>11</td><td>84.2</td><td>86</td><td>77</td><td>9</td><td>0</td><td>100.0</td><td>9.14</td><td style="">-0.76</td><td></td><td>0.42</td><td></td><td></td><td></td><td></td><td></td><td>-0.34</td><td>-0.47</td><td>-0.78</td><td>-1.12</td><td>-0.031</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.102</td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14866">이창용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.108</td><td>1</td><td>1</td><td>4.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>2.25</td><td style="">-1.21</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-1.18</td><td>-18.89</td><td>0.00</td><td>-1.18</td><td>-0.108</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.108</td></tr><tr><td style="text-align:center;">57</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12562">이성규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.109</td><td>39</td><td>21</td><td>201.1</td><td>185</td><td>173</td><td>10</td><td>2</td><td>98.9</td><td>8.18</td><td style="">0.68</td><td></td><td>-0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.67</td><td>0.79</td><td>-1.86</td><td>-1.19</td><td>0.061</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.109</td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16156">카디네스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.112</td><td>5</td><td>4</td><td>33.2</td><td>9</td><td>9</td><td>0</td><td>0</td><td>100.0</td><td>2.41</td><td style="">-0.85</td><td>-0.31</td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>-1.05</td><td>-21.67</td><td>-0.17</td><td>-1.22</td><td>-0.096</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.112</td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14867">김현준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.116</td><td>9</td><td>6</td><td>50.1</td><td>10</td><td>10</td><td>0</td><td>0</td><td>100.0</td><td>1.79</td><td style="">-1.13</td><td>0.05</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>-1.02</td><td>-1.87</td><td>-0.25</td><td>-1.27</td><td>-0.094</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.116</td></tr><tr><td style="text-align:center;">60</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15036">김재혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.122</td><td>11</td><td>2</td><td>23.0</td><td>6</td><td>5</td><td>0</td><td>1</td><td>83.3</td><td>1.96</td><td style="">-0.80</td><td>-0.03</td><td>-0.43</td><td></td><td></td><td></td><td></td><td></td><td>-1.26</td><td>-5.19</td><td>-0.07</td><td>-1.33</td><td>-0.115</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.122</td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15036">김재혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.137</td><td>11</td><td>1</td><td>27.0</td><td>6</td><td>6</td><td>0</td><td>0</td><td>100.0</td><td>2.00</td><td style="">-1.24</td><td>-0.32</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>-1.50</td><td>-6.18</td><td>0.00</td><td>-1.50</td><td>-0.137</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.137</td></tr><tr><td style="text-align:center;">62</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10640">김헌곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.138</td><td>5</td><td>1</td><td>16.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>1.69</td><td style="">-1.70</td><td>0.16</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-1.51</td><td>-1.86</td><td>0.00</td><td>-1.51</td><td>-0.138</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.138</td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12562">이성규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.140</td><td>10</td><td>5</td><td>50.0</td><td>12</td><td>12</td><td>0</td><td>0</td><td>100.0</td><td>2.16</td><td style="">-0.96</td><td>-0.41</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>-1.31</td><td>-1.54</td><td>-0.22</td><td>-1.53</td><td>-0.119</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.140</td></tr><tr><td style="text-align:center;">64</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13164">공민규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.142</td><td>9</td><td>4</td><td>33.0</td><td>9</td><td>1</td><td>7</td><td>1</td><td>88.9</td><td>2.18</td><td style="">-1.28</td><td></td><td>-0.28</td><td></td><td></td><td></td><td></td><td></td><td>-1.55</td><td>-18.64</td><td>0.00</td><td>-1.55</td><td>-0.142</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.142</td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12988">안주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.143</td><td>73</td><td>34</td><td>360.1</td><td>190</td><td>76</td><td>111</td><td>3</td><td>98.4</td><td>4.67</td><td style="">-3.52</td><td></td><td>0.67</td><td>-0.06</td><td></td><td></td><td></td><td></td><td>-2.91</td><td>-5.11</td><td>1.34</td><td>-1.57</td><td>-0.266</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.143</td></tr><tr><td style="text-align:center;">66</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15862">맥키넌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.175</td><td>6</td><td>4</td><td>36.2</td><td>7</td><td>3</td><td>3</td><td>1</td><td>85.7</td><td>1.47</td><td style="">-1.73</td><td></td><td>-0.25</td><td></td><td>0.07</td><td></td><td></td><td></td><td>-1.91</td><td>-3.82</td><td>0.00</td><td>-1.91</td><td>-0.175</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.175</td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12936">김성윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.179</td><td>1</td><td>1</td><td>8.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>3.38</td><td style="">-1.63</td><td>-0.31</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-1.93</td><td>-8.67</td><td>-0.03</td><td>-1.96</td><td>-0.176</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.179</td></tr><tr><td style="text-align:center;">68</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11255">강한울</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.190</td><td>8</td><td>0</td><td>25.0</td><td>10</td><td>3</td><td>6</td><td>1</td><td>90.0</td><td>3.24</td><td style="">-1.80</td><td></td><td>-0.35</td><td></td><td></td><td></td><td></td><td></td><td>-2.16</td><td>-17.24</td><td>0.08</td><td>-2.08</td><td>-0.197</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.190</td></tr><tr><td style="text-align:center;">69</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12562">이성규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.264</td><td>27</td><td>18</td><td>145.0</td><td>39</td><td>38</td><td>0</td><td>1</td><td>97.4</td><td>2.36</td><td style="">-1.82</td><td>-0.87</td><td>-0.20</td><td></td><td></td><td></td><td></td><td></td><td>-2.89</td><td>-3.41</td><td>0.00</td><td>-2.89</td><td>-0.264</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.264</td></tr><tr><td style="text-align:center;">70</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10892">구자욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.351</td><td>100</td><td>98</td><td>802.0</td><td>193</td><td>188</td><td>4</td><td>1</td><td>99.5</td><td>2.15</td><td style="">1.01</td><td>-0.93</td><td>0.41</td><td></td><td></td><td></td><td></td><td></td><td>0.49</td><td>0.55</td><td>-4.33</td><td>-3.84</td><td>0.045</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.351</td></tr><tr><td style="text-align:center;">71</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15875">양도근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.12</td><td></td><td></td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">71</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16156">카디네스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>0.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td></td><td style="">-0.88</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.88</td><td>-18.07</td><td></td><td></td><td>-0.080</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">71</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10871">김태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>56</td><td>0</td><td>52.1</td><td>13</td><td>5</td><td>7</td><td>1</td><td>92.3</td><td>2.06</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">71</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12934">최지광</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>34</td><td>0</td><td>36.1</td><td>6</td><td>2</td><td>4</td><td>0</td><td>100.0</td><td>1.49</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">71</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15868">김호진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">71</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11489">김재윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>65</td><td>0</td><td>66.0</td><td>11</td><td>1</td><td>10</td><td>0</td><td>100.0</td><td>1.50</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">71</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15499">김재상</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>2</td><td>0</td><td>2</td><td>0</td><td>100.0</td><td>18.00</td><td style="">-0.26</td><td></td><td>0.01</td><td>-0.20</td><td></td><td></td><td></td><td></td><td>-0.46</td><td>-1.87</td><td></td><td></td><td>-0.042</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">71</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11169">이상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>36</td><td>0</td><td>30.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>0.30</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">71</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10367">오승환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>58</td><td>0</td><td>55.0</td><td>6</td><td>1</td><td>5</td><td>0</td><td>100.0</td><td>0.98</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">71</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10685">김대우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>30</td><td>1</td><td>34.1</td><td>5</td><td>0</td><td>4</td><td>1</td><td>80.0</td><td>1.05</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">71</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11255">강한울</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.04</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">71</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15864">육선엽</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>11</td><td>1</td><td>17.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>1.06</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">71</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11255">강한울</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>3</td><td>0</td><td>3.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-0.03</td><td></td><td>0.03</td><td>-0.25</td><td></td><td></td><td></td><td></td><td>-0.25</td><td>-2.02</td><td></td><td></td><td>-0.023</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10312">이지영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.513</td><td>117</td><td>105</td><td>914.2</td><td>987</td><td>919</td><td>61</td><td>7</td><td>99.3</td><td>9.64</td><td style="">1.20</td><td></td><td>-0.21</td><td></td><td>0.10</td><td>1.67</td><td>5.34</td><td></td><td>6.50</td><td>7.61</td><td>10.06</td><td>16.56</td><td>0.594</td><td style="background-color:#F3F3F3; font-weight:bold;">1.513</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12922">박성한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.059</td><td>135</td><td>128</td><td>1115.0</td><td>564</td><td>209</td><td>332</td><td>23</td><td>95.9</td><td>4.37</td><td style="">1.35</td><td></td><td>-1.65</td><td>0.75</td><td></td><td></td><td></td><td></td><td>0.45</td><td>0.47</td><td>11.14</td><td>11.59</td><td>0.041</td><td style="background-color:#F3F3F3; font-weight:bold;">1.059</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16042">정준재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.358</td><td>57</td><td>48</td><td>384.2</td><td>224</td><td>82</td><td>139</td><td>3</td><td>98.7</td><td>5.17</td><td style="">1.80</td><td></td><td>0.82</td><td>-0.47</td><td></td><td></td><td></td><td></td><td>2.14</td><td>3.51</td><td>1.78</td><td>3.92</td><td>0.196</td><td style="background-color:#F3F3F3; font-weight:bold;">0.358</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10636">김성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.257</td><td>18</td><td>10</td><td>100.1</td><td>30</td><td>8</td><td>22</td><td>0</td><td>100.0</td><td>2.69</td><td style="">2.42</td><td></td><td>0.69</td><td>-0.37</td><td>0.07</td><td></td><td></td><td></td><td>2.81</td><td>5.70</td><td>0.00</td><td>2.81</td><td>0.257</td><td style="background-color:#F3F3F3; font-weight:bold;">0.257</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14151">최경모</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.202</td><td>20</td><td>4</td><td>72.2</td><td>37</td><td>10</td><td>26</td><td>1</td><td>97.3</td><td>4.46</td><td style="">2.07</td><td></td><td>-0.06</td><td>0.02</td><td></td><td></td><td></td><td></td><td>2.02</td><td>5.83</td><td>0.19</td><td>2.21</td><td>0.185</td><td style="background-color:#F3F3F3; font-weight:bold;">0.202</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13195">최상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.160</td><td>14</td><td>1</td><td>26.0</td><td>17</td><td>16</td><td>1</td><td>0</td><td>100.0</td><td>5.88</td><td style="">1.39</td><td>0.31</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>1.75</td><td>5.87</td><td>0.00</td><td>1.75</td><td>0.160</td><td style="background-color:#F3F3F3; font-weight:bold;">0.160</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12622">김찬형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.071</td><td>1</td><td>0</td><td>3.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>6.00</td><td style="">0.73</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.76</td><td>21.83</td><td>0.02</td><td>0.78</td><td>0.069</td><td style="background-color:#F3F3F3; font-weight:bold;">0.071</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10707">김민식</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.064</td><td>40</td><td>30</td><td>264.2</td><td>240</td><td>224</td><td>16</td><td>0</td><td>100.0</td><td>8.16</td><td style="">0.64</td><td></td><td>0.96</td><td></td><td>0.03</td><td>-1.79</td><td>-2.92</td><td></td><td>-2.20</td><td>-7.05</td><td>2.90</td><td>0.70</td><td>-0.201</td><td style="background-color:#F3F3F3; font-weight:bold;">0.064</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16042">정준재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.063</td><td>18</td><td>8</td><td>85.2</td><td>20</td><td>6</td><td>14</td><td>0</td><td>100.0</td><td>2.10</td><td style="">1.13</td><td></td><td>0.59</td><td>-0.37</td><td>-0.65</td><td></td><td></td><td></td><td>0.69</td><td>1.14</td><td>0.00</td><td>0.69</td><td>0.063</td><td style="background-color:#F3F3F3; font-weight:bold;">0.063</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11148">강진성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.057</td><td>2</td><td>1</td><td>9.0</td><td>7</td><td>6</td><td>1</td><td>0</td><td>100.0</td><td>7.00</td><td style="">0.66</td><td></td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>0.70</td><td>6.31</td><td>-0.08</td><td>0.62</td><td>0.064</td><td style="background-color:#F3F3F3; font-weight:bold;">0.057</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13128">최준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.054</td><td>4</td><td>0</td><td>6.0</td><td>4</td><td>1</td><td>3</td><td>0</td><td>100.0</td><td>6.00</td><td style="">0.55</td><td></td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>0.59</td><td>4.70</td><td>0.00</td><td>0.59</td><td>0.054</td><td style="background-color:#F3F3F3; font-weight:bold;">0.054</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16042">정준재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.052</td><td>3</td><td>1</td><td>5.2</td><td>4</td><td>1</td><td>3</td><td>0</td><td>100.0</td><td>6.35</td><td style="">0.45</td><td></td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>0.50</td><td>0.82</td><td>0.06</td><td>0.56</td><td>0.046</td><td style="background-color:#F3F3F3; font-weight:bold;">0.052</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14146">김창평</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.041</td><td>1</td><td>1</td><td>4.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>6.75</td><td style="">0.46</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.47</td><td>11.34</td><td>-0.02</td><td>0.45</td><td>0.043</td><td style="background-color:#F3F3F3; font-weight:bold;">0.041</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15530">에레디아</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.040</td><td>2</td><td>1</td><td>14.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>1.93</td><td style="">0.38</td><td>0.03</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.44</td><td>0.46</td><td>0.00</td><td>0.44</td><td>0.040</td><td style="background-color:#F3F3F3; font-weight:bold;">0.040</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11148">강진성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.040</td><td>1</td><td>0</td><td>3.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">0.45</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.45</td><td>4.08</td><td>-0.02</td><td>0.43</td><td>0.041</td><td style="background-color:#F3F3F3; font-weight:bold;">0.040</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10249">오태곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.023</td><td>2</td><td>0</td><td>5.0</td><td>2</td><td>0</td><td>2</td><td>0</td><td>100.0</td><td>3.60</td><td style="">0.21</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.25</td><td>0.31</td><td>0.00</td><td>0.25</td><td>0.023</td><td style="background-color:#F3F3F3; font-weight:bold;">0.023</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16043">정현승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.015</td><td>12</td><td>3</td><td>40.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>1.13</td><td style="">0.28</td><td>-0.11</td><td>0.12</td><td></td><td></td><td></td><td></td><td></td><td>0.29</td><td>1.80</td><td>-0.12</td><td>0.17</td><td>0.026</td><td style="background-color:#F3F3F3; font-weight:bold;">0.015</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10106">최정</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.013</td><td>121</td><td>116</td><td>954.2</td><td>239</td><td>57</td><td>169</td><td>13</td><td>94.6</td><td>2.13</td><td style="">-1.00</td><td></td><td>0.03</td><td>0.95</td><td>0.16</td><td></td><td></td><td></td><td>0.14</td><td>0.15</td><td>0.00</td><td>0.14</td><td>0.013</td><td style="background-color:#F3F3F3; font-weight:bold;">0.013</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14888">추신수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.009</td><td>6</td><td>5</td><td>35.0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>1.80</td><td style="">0.23</td><td>-0.05</td><td>0.11</td><td></td><td></td><td></td><td></td><td></td><td>0.29</td><td>0.53</td><td>-0.19</td><td>0.10</td><td>0.026</td><td style="background-color:#F3F3F3; font-weight:bold;">0.009</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16043">정현승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.002</td><td>5</td><td>2</td><td>23.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>1.57</td><td style="">-0.22</td><td>0.29</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.10</td><td>0.60</td><td>-0.07</td><td>0.03</td><td>0.009</td><td style="background-color:#F3F3F3; font-weight:bold;">0.002</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14147">하재훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.002</td><td>24</td><td>19</td><td>160.0</td><td>38</td><td>37</td><td>1</td><td>0</td><td>100.0</td><td>2.14</td><td style="">-0.69</td><td>0.38</td><td>0.33</td><td></td><td></td><td></td><td></td><td></td><td>0.02</td><td>0.03</td><td>0.00</td><td>0.02</td><td>0.002</td><td style="background-color:#F3F3F3; font-weight:bold;">0.002</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10783">문승원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.000</td><td>61</td><td>0</td><td>60.0</td><td>11</td><td>2</td><td>9</td><td>0</td><td>100.0</td><td>1.65</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">0.000</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12622">김찬형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.011</td><td>2</td><td>1</td><td>11.0</td><td>5</td><td>4</td><td>1</td><td>0</td><td>100.0</td><td>4.09</td><td style="">-0.21</td><td></td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>-0.15</td><td>-4.26</td><td>0.03</td><td>-0.12</td><td>-0.014</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.011</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12613">안상현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.016</td><td>3</td><td>0</td><td>9.0</td><td>2</td><td>1</td><td>1</td><td>0</td><td>100.0</td><td>2.00</td><td style="">-0.31</td><td></td><td>0.06</td><td></td><td>0.07</td><td></td><td></td><td></td><td>-0.17</td><td>-0.67</td><td>0.00</td><td>-0.17</td><td>-0.016</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.016</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11351">최민창</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.022</td><td>3</td><td>0</td><td>4.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>2.25</td><td style="">-0.54</td><td>0.30</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.23</td><td>-4.64</td><td>-0.01</td><td>-0.24</td><td>-0.021</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.022</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16038">박지환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.027</td><td>54</td><td>46</td><td>406.2</td><td>249</td><td>113</td><td>129</td><td>7</td><td>97.2</td><td>5.36</td><td style="">-2.12</td><td></td><td>-1.06</td><td>0.92</td><td></td><td></td><td></td><td></td><td>-2.26</td><td>-4.28</td><td>1.96</td><td>-0.30</td><td>-0.206</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.027</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10249">오태곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.032</td><td>89</td><td>42</td><td>478.2</td><td>464</td><td>427</td><td>35</td><td>2</td><td>99.6</td><td>8.69</td><td style="">1.91</td><td></td><td>1.36</td><td></td><td>0.29</td><td></td><td></td><td></td><td>3.57</td><td>4.39</td><td>-3.92</td><td>-0.35</td><td>0.326</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.032</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10249">오태곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.064</td><td>12</td><td>4</td><td>44.2</td><td>7</td><td>6</td><td>1</td><td>0</td><td>100.0</td><td>1.41</td><td style="">-1.35</td><td>0.81</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>-0.48</td><td>-0.59</td><td>-0.22</td><td>-0.70</td><td>-0.044</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.064</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10249">오태곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.073</td><td>14</td><td>7</td><td>56.0</td><td>9</td><td>9</td><td>0</td><td>0</td><td>100.0</td><td>1.45</td><td style="">-1.07</td><td>0.15</td><td>0.12</td><td></td><td></td><td></td><td></td><td></td><td>-0.80</td><td>-0.98</td><td>0.00</td><td>-0.80</td><td>-0.073</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.073</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12613">안상현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.074</td><td>3</td><td>1</td><td>8.0</td><td>8</td><td>4</td><td>3</td><td>1</td><td>87.5</td><td>7.88</td><td style="">-0.44</td><td></td><td>-0.43</td><td></td><td></td><td></td><td></td><td></td><td>-0.87</td><td>-3.39</td><td>0.06</td><td>-0.81</td><td>-0.080</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.074</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12622">김찬형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.077</td><td>2</td><td>1</td><td>10.0</td><td>3</td><td>0</td><td>3</td><td>0</td><td>100.0</td><td>2.70</td><td style="">-0.91</td><td></td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>-0.85</td><td>-24.37</td><td>0.00</td><td>-0.85</td><td>-0.077</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.077</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14806">조형우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.077</td><td>19</td><td>9</td><td>90.1</td><td>86</td><td>79</td><td>6</td><td>1</td><td>98.8</td><td>8.47</td><td style="">-0.01</td><td></td><td>-0.18</td><td></td><td></td><td>0.12</td><td>-2.42</td><td></td><td>-1.76</td><td>-13.33</td><td>0.91</td><td>-0.85</td><td>-0.161</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.077</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13195">최상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.084</td><td>20</td><td>0</td><td>32.2</td><td>7</td><td>6</td><td>1</td><td>0</td><td>100.0</td><td>1.93</td><td style="">-1.82</td><td>0.84</td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>-0.88</td><td>-2.95</td><td>-0.04</td><td>-0.92</td><td>-0.081</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.084</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14151">최경모</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.113</td><td>9</td><td>2</td><td>20.0</td><td>3</td><td>0</td><td>2</td><td>1</td><td>66.7</td><td>0.90</td><td style="">-0.55</td><td></td><td>-0.32</td><td>-0.48</td><td></td><td></td><td></td><td></td><td>-1.35</td><td>-3.90</td><td>0.12</td><td>-1.23</td><td>-0.124</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.113</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16043">정현승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.115</td><td>4</td><td>3</td><td>23.0</td><td>6</td><td>6</td><td>0</td><td>0</td><td>100.0</td><td>2.35</td><td style="">-1.29</td><td>-0.02</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>-1.26</td><td>-7.90</td><td>0.00</td><td>-1.26</td><td>-0.115</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.115</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13128">최준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.131</td><td>10</td><td>6</td><td>47.0</td><td>25</td><td>10</td><td>13</td><td>2</td><td>92.0</td><td>4.40</td><td style="">-0.94</td><td></td><td>-0.72</td><td></td><td></td><td></td><td></td><td></td><td>-1.65</td><td>-13.24</td><td>0.22</td><td>-1.43</td><td>-0.151</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.131</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12613">안상현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.150</td><td>28</td><td>22</td><td>176.0</td><td>86</td><td>29</td><td>53</td><td>4</td><td>95.3</td><td>4.19</td><td style="">-1.09</td><td></td><td>-0.94</td><td>-0.28</td><td></td><td></td><td></td><td></td><td>-2.31</td><td>-9.00</td><td>0.67</td><td>-1.64</td><td>-0.211</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.150</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14151">최경모</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.151</td><td>19</td><td>5</td><td>60.0</td><td>13</td><td>4</td><td>7</td><td>2</td><td>84.6</td><td>1.65</td><td style="">-0.85</td><td></td><td>-0.59</td><td>-0.21</td><td></td><td></td><td></td><td></td><td>-1.65</td><td>-4.76</td><td>0.00</td><td>-1.65</td><td>-0.151</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.151</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10249">오태곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.160</td><td>10</td><td>5</td><td>50.0</td><td>19</td><td>16</td><td>1</td><td>2</td><td>89.5</td><td>3.06</td><td style="">-0.79</td><td>0.14</td><td>-0.85</td><td></td><td></td><td></td><td></td><td></td><td>-1.50</td><td>-1.85</td><td>-0.25</td><td>-1.75</td><td>-0.137</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.160</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15530">에레디아</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.161</td><td>117</td><td>115</td><td>975.0</td><td>222</td><td>211</td><td>8</td><td>3</td><td>98.6</td><td>2.02</td><td style="">3.21</td><td>-0.11</td><td>0.11</td><td></td><td></td><td></td><td></td><td></td><td>3.21</td><td>3.40</td><td>-4.97</td><td>-1.76</td><td>0.293</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.161</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14147">하재훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.161</td><td>29</td><td>21</td><td>205.0</td><td>46</td><td>42</td><td>2</td><td>2</td><td>95.7</td><td>1.93</td><td style="">-0.37</td><td>0.27</td><td>-0.77</td><td></td><td></td><td></td><td></td><td></td><td>-0.87</td><td>-1.17</td><td>-0.90</td><td>-1.77</td><td>-0.079</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.161</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10815">한유섬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.182</td><td>3</td><td>2</td><td>11.0</td><td>2</td><td>1</td><td>0</td><td>1</td><td>50.0</td><td>0.82</td><td style="">-1.33</td><td>-0.12</td><td>-0.49</td><td></td><td></td><td></td><td></td><td></td><td>-1.94</td><td>-2.12</td><td>-0.05</td><td>-1.99</td><td>-0.177</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.182</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16038">박지환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.226</td><td>9</td><td>4</td><td>38.0</td><td>7</td><td>2</td><td>4</td><td>1</td><td>85.7</td><td>1.42</td><td style="">-2.24</td><td></td><td>-0.24</td><td></td><td></td><td></td><td></td><td></td><td>-2.48</td><td>-4.70</td><td>0.00</td><td>-2.48</td><td>-0.226</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.226</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10636">김성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.275</td><td>21</td><td>12</td><td>118.0</td><td>54</td><td>19</td><td>32</td><td>3</td><td>94.4</td><td>3.89</td><td style="">-3.27</td><td></td><td>-0.46</td><td>-0.27</td><td></td><td></td><td></td><td></td><td>-4.01</td><td>-8.12</td><td>1.00</td><td>-3.01</td><td>-0.366</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.275</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10636">김성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.289</td><td>39</td><td>17</td><td>171.2</td><td>94</td><td>37</td><td>54</td><td>3</td><td>96.8</td><td>4.77</td><td style="">-3.18</td><td></td><td>-0.47</td><td>-0.19</td><td></td><td></td><td></td><td></td><td>-3.84</td><td>-7.79</td><td>0.68</td><td>-3.16</td><td>-0.351</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.289</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14587">최지훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.297</td><td>119</td><td>113</td><td>989.2</td><td>249</td><td>237</td><td>5</td><td>7</td><td>97.2</td><td>2.20</td><td style="">-2.90</td><td>1.10</td><td>-1.45</td><td></td><td></td><td></td><td></td><td></td><td>-3.25</td><td>-3.74</td><td>0.00</td><td>-3.25</td><td>-0.297</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.297</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14807">고명준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.313</td><td>92</td><td>87</td><td>667.0</td><td>631</td><td>584</td><td>42</td><td>5</td><td>99.2</td><td>8.45</td><td style="">2.23</td><td></td><td>0.79</td><td></td><td>0.06</td><td></td><td></td><td></td><td>3.08</td><td>4.18</td><td>-6.50</td><td>-3.42</td><td>0.281</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.313</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14699">전의산</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.369</td><td>22</td><td>14</td><td>114.0</td><td>102</td><td>91</td><td>9</td><td>2</td><td>98.0</td><td>7.89</td><td style="">-2.40</td><td></td><td>-0.44</td><td></td><td>-0.26</td><td></td><td></td><td></td><td>-3.10</td><td>-13.14</td><td>-0.94</td><td>-4.04</td><td>-0.283</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.369</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10815">한유섬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.850</td><td>101</td><td>97</td><td>802.2</td><td>170</td><td>164</td><td>0</td><td>6</td><td>96.5</td><td>1.84</td><td style="">-4.67</td><td>0.06</td><td>-0.59</td><td></td><td></td><td></td><td></td><td></td><td>-5.20</td><td>-5.67</td><td>-4.11</td><td>-9.31</td><td>-0.475</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.850</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14147">하재훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.982</td><td>47</td><td>33</td><td>301.1</td><td>56</td><td>49</td><td>2</td><td>5</td><td>91.1</td><td>1.52</td><td style="">-7.59</td><td>-0.20</td><td>-1.60</td><td></td><td></td><td></td><td></td><td></td><td>-9.40</td><td>-12.65</td><td>-1.35</td><td>-10.75</td><td>-0.858</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.982</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11351">최민창</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>3.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.04</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15461">이로운</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>58</td><td>0</td><td>56.0</td><td>4</td><td>1</td><td>3</td><td>0</td><td>100.0</td><td>0.64</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10106">최정</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.01</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14805">조병현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>74</td><td>0</td><td>73.0</td><td>10</td><td>6</td><td>2</td><td>2</td><td>80.0</td><td>0.99</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11351">최민창</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.15</td><td>0.03</td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.18</td><td>3.79</td><td></td><td></td><td>0.017</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13195">최상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>4</td><td>0</td><td>5.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.80</td><td style="">0.56</td><td>0.02</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.58</td><td>1.95</td><td></td><td></td><td>0.053</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14807">고명준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.46</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.46</td><td>-0.62</td><td></td><td></td><td>-0.042</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13228">한두솔</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>64</td><td>0</td><td>59.1</td><td>8</td><td>2</td><td>5</td><td>1</td><td>87.5</td><td>1.06</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11236">박민호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>19</td><td>0</td><td>22.2</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>0.40</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14765">김주원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.722</td><td>132</td><td>115</td><td>1023.2</td><td>501</td><td>196</td><td>287</td><td>18</td><td>96.4</td><td>4.25</td><td style="">9.13</td><td></td><td>0.05</td><td>0.26</td><td></td><td></td><td></td><td></td><td>9.43</td><td>10.13</td><td>9.42</td><td>18.85</td><td>0.861</td><td style="background-color:#F3F3F3; font-weight:bold;">1.722</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11137">박민우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.023</td><td>98</td><td>95</td><td>779.1</td><td>402</td><td>186</td><td>210</td><td>6</td><td>98.5</td><td>4.57</td><td style="">4.88</td><td></td><td>1.70</td><td>0.31</td><td></td><td></td><td></td><td></td><td>6.89</td><td>8.20</td><td>4.31</td><td>11.20</td><td>0.629</td><td style="background-color:#F3F3F3; font-weight:bold;">1.023</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13081">김형준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.967</td><td>116</td><td>104</td><td>870.1</td><td>832</td><td>761</td><td>59</td><td>12</td><td>98.6</td><td>8.48</td><td style="">0.42</td><td></td><td>-2.88</td><td></td><td>-0.04</td><td>1.15</td><td>3.15</td><td></td><td>0.86</td><td>1.04</td><td>9.72</td><td>10.58</td><td>0.079</td><td style="background-color:#F3F3F3; font-weight:bold;">0.967</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14221">최정원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.334</td><td>37</td><td>20</td><td>184.1</td><td>76</td><td>74</td><td>0</td><td>2</td><td>97.4</td><td>3.61</td><td style="">4.35</td><td>-0.07</td><td>-0.62</td><td></td><td></td><td></td><td></td><td></td><td>3.66</td><td>8.10</td><td>0.00</td><td>3.66</td><td>0.334</td><td style="background-color:#F3F3F3; font-weight:bold;">0.334</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14785">김휘집</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.298</td><td>52</td><td>42</td><td>381.2</td><td>117</td><td>35</td><td>75</td><td>7</td><td>94.0</td><td>2.59</td><td style="">3.20</td><td></td><td>-0.89</td><td>0.91</td><td>0.05</td><td></td><td></td><td></td><td>3.26</td><td>3.35</td><td>0.00</td><td>3.26</td><td>0.298</td><td style="background-color:#F3F3F3; font-weight:bold;">0.298</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10261">손아섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.278</td><td>20</td><td>17</td><td>130.2</td><td>37</td><td>37</td><td>0</td><td>0</td><td>100.0</td><td>2.55</td><td style="">3.51</td><td>-0.15</td><td>0.39</td><td></td><td></td><td></td><td></td><td></td><td>3.76</td><td>6.44</td><td>-0.71</td><td>3.05</td><td>0.343</td><td style="background-color:#F3F3F3; font-weight:bold;">0.278</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14785">김휘집</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.226</td><td>13</td><td>11</td><td>94.0</td><td>97</td><td>86</td><td>11</td><td>0</td><td>100.0</td><td>9.29</td><td style="">2.93</td><td></td><td>0.46</td><td></td><td>0.06</td><td></td><td></td><td></td><td>3.46</td><td>3.56</td><td>-0.98</td><td>2.48</td><td>0.316</td><td style="background-color:#F3F3F3; font-weight:bold;">0.226</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12560">도태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.210</td><td>28</td><td>12</td><td>128.0</td><td>85</td><td>32</td><td>52</td><td>1</td><td>98.8</td><td>5.91</td><td style="">1.62</td><td></td><td>0.27</td><td>-0.13</td><td></td><td></td><td></td><td></td><td>1.77</td><td>2.55</td><td>0.53</td><td>2.30</td><td>0.162</td><td style="background-color:#F3F3F3; font-weight:bold;">0.210</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14597">박시원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.154</td><td>27</td><td>19</td><td>168.1</td><td>51</td><td>49</td><td>2</td><td>0</td><td>100.0</td><td>2.73</td><td style="">0.71</td><td>0.62</td><td>0.35</td><td></td><td></td><td></td><td></td><td></td><td>1.68</td><td>4.41</td><td>0.00</td><td>1.68</td><td>0.154</td><td style="background-color:#F3F3F3; font-weight:bold;">0.154</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14172">송승환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.139</td><td>2</td><td>1</td><td>9.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>5.00</td><td style="">1.51</td><td>0.01</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>1.55</td><td>74.33</td><td>-0.03</td><td>1.52</td><td>0.141</td><td style="background-color:#F3F3F3; font-weight:bold;">0.139</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10891">박세혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.134</td><td>71</td><td>36</td><td>357.1</td><td>311</td><td>290</td><td>18</td><td>3</td><td>99.0</td><td>7.76</td><td style="">0.41</td><td></td><td>-0.22</td><td></td><td>0.16</td><td>-0.95</td><td>-2.27</td><td></td><td>-2.18</td><td>-3.84</td><td>3.65</td><td>1.46</td><td>-0.200</td><td style="background-color:#F3F3F3; font-weight:bold;">0.134</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14220">서호철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.128</td><td>35</td><td>24</td><td>219.1</td><td>116</td><td>59</td><td>52</td><td>5</td><td>95.7</td><td>4.55</td><td style="">2.18</td><td></td><td>-1.18</td><td>-0.71</td><td></td><td></td><td></td><td></td><td>0.28</td><td>0.29</td><td>1.12</td><td>1.40</td><td>0.026</td><td style="background-color:#F3F3F3; font-weight:bold;">0.128</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14220">서호철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.109</td><td>106</td><td>100</td><td>834.0</td><td>241</td><td>75</td><td>157</td><td>9</td><td>96.3</td><td>2.50</td><td style="">-0.23</td><td></td><td>1.71</td><td>-0.09</td><td>-0.20</td><td></td><td></td><td></td><td>1.19</td><td>1.22</td><td>0.00</td><td>1.19</td><td>0.109</td><td style="background-color:#F3F3F3; font-weight:bold;">0.109</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11172">권희동</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.098</td><td>7</td><td>7</td><td>38.0</td><td>11</td><td>11</td><td>0</td><td>0</td><td>100.0</td><td>2.61</td><td style="">1.23</td><td>-0.24</td><td>0.08</td><td></td><td></td><td></td><td></td><td></td><td>1.07</td><td>1.25</td><td>0.00</td><td>1.07</td><td>0.098</td><td style="background-color:#F3F3F3; font-weight:bold;">0.098</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13082">오영수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.093</td><td>10</td><td>6</td><td>49.2</td><td>53</td><td>49</td><td>4</td><td>0</td><td>100.0</td><td>9.60</td><td style="">1.21</td><td></td><td>0.25</td><td></td><td></td><td></td><td></td><td></td><td>1.46</td><td>10.51</td><td>-0.44</td><td>1.02</td><td>0.133</td><td style="background-color:#F3F3F3; font-weight:bold;">0.093</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12560">도태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.060</td><td>18</td><td>2</td><td>53.2</td><td>22</td><td>4</td><td>17</td><td>1</td><td>95.5</td><td>3.52</td><td style="">1.61</td><td></td><td>-0.13</td><td>-0.82</td><td></td><td></td><td></td><td></td><td>0.66</td><td>0.95</td><td>0.00</td><td>0.66</td><td>0.060</td><td style="background-color:#F3F3F3; font-weight:bold;">0.060</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12903">김수윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.043</td><td>5</td><td>1</td><td>22.0</td><td>23</td><td>22</td><td>1</td><td>0</td><td>100.0</td><td>9.41</td><td style="">0.50</td><td></td><td>0.11</td><td></td><td></td><td></td><td></td><td></td><td>0.61</td><td>9.70</td><td>-0.14</td><td>0.47</td><td>0.055</td><td style="background-color:#F3F3F3; font-weight:bold;">0.043</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16058">김세훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.040</td><td>2</td><td>1</td><td>8.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.13</td><td style="">0.61</td><td></td><td>0.05</td><td>-0.24</td><td></td><td></td><td></td><td></td><td>0.42</td><td>8.59</td><td>0.02</td><td>0.44</td><td>0.038</td><td style="background-color:#F3F3F3; font-weight:bold;">0.040</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13261">천재환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.027</td><td>17</td><td>8</td><td>78.0</td><td>29</td><td>29</td><td>0</td><td>0</td><td>100.0</td><td>3.35</td><td style="">-0.37</td><td>0.50</td><td>0.16</td><td></td><td></td><td></td><td></td><td></td><td>0.29</td><td>0.47</td><td>0.00</td><td>0.29</td><td>0.027</td><td style="background-color:#F3F3F3; font-weight:bold;">0.027</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12560">도태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.009</td><td>57</td><td>17</td><td>215.2</td><td>192</td><td>171</td><td>20</td><td>1</td><td>99.5</td><td>7.97</td><td style="">1.25</td><td></td><td>0.56</td><td></td><td>0.06</td><td></td><td></td><td></td><td>1.87</td><td>2.70</td><td>-1.78</td><td>0.09</td><td>0.171</td><td style="background-color:#F3F3F3; font-weight:bold;">0.009</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15452">신용석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.006</td><td>1</td><td>0</td><td>3.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>12.00</td><td style=""></td><td></td><td>0.01</td><td></td><td></td><td></td><td>0.04</td><td></td><td>0.04</td><td>2.64</td><td>0.02</td><td>0.06</td><td>0.003</td><td style="background-color:#F3F3F3; font-weight:bold;">0.006</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14659">한재환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.001</td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.14</td><td>0.00</td><td>0.01</td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;">0.001</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11329">안중열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.015</td><td>9</td><td>4</td><td>45.0</td><td>42</td><td>39</td><td>3</td><td>0</td><td>100.0</td><td>8.40</td><td style="">0.00</td><td></td><td>0.16</td><td></td><td></td><td>-0.20</td><td>-0.92</td><td></td><td>-0.69</td><td>-9.89</td><td>0.53</td><td>-0.16</td><td>-0.063</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.015</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14716">김한별</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.025</td><td>16</td><td>2</td><td>32.1</td><td>17</td><td>11</td><td>6</td><td>0</td><td>100.0</td><td>4.73</td><td style="">-0.54</td><td></td><td>0.20</td><td></td><td></td><td></td><td></td><td></td><td>-0.35</td><td>-1.24</td><td>0.07</td><td>-0.28</td><td>-0.032</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.025</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14659">한재환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.033</td><td>3</td><td>0</td><td>4.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>6.75</td><td style="">-0.01</td><td></td><td>0.02</td><td></td><td>-0.35</td><td></td><td></td><td></td><td>-0.34</td><td>-6.92</td><td>-0.02</td><td>-0.36</td><td>-0.031</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.033</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13261">천재환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.039</td><td>31</td><td>17</td><td>168.2</td><td>31</td><td>30</td><td>1</td><td>0</td><td>100.0</td><td>1.65</td><td style="">0.23</td><td>-0.09</td><td>0.19</td><td></td><td></td><td></td><td></td><td></td><td>0.34</td><td>0.54</td><td>-0.76</td><td>-0.42</td><td>0.031</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.039</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13250">한석현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.047</td><td>9</td><td>1</td><td>21.2</td><td>8</td><td>6</td><td>2</td><td>0</td><td>100.0</td><td>3.32</td><td style="">-1.43</td><td>0.98</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.43</td><td>-1.55</td><td>-0.08</td><td>-0.51</td><td>-0.039</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.047</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11172">권희동</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.054</td><td>115</td><td>101</td><td>834.2</td><td>229</td><td>216</td><td>11</td><td>2</td><td>99.1</td><td>2.45</td><td style="">3.95</td><td>-0.11</td><td>-0.05</td><td></td><td></td><td></td><td></td><td></td><td>3.79</td><td>4.43</td><td>-4.38</td><td>-0.59</td><td>0.346</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.054</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12903">김수윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.056</td><td>2</td><td>0</td><td>4.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.64</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.61</td><td>-9.74</td><td>0.00</td><td>-0.61</td><td>-0.056</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.056</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14221">최정원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.056</td><td>3</td><td>0</td><td>4.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>2.25</td><td style="">-0.72</td><td>0.11</td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.60</td><td>-1.33</td><td>-0.01</td><td>-0.61</td><td>-0.055</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.056</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10261">손아섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.064</td><td>9</td><td>9</td><td>65.0</td><td>13</td><td>13</td><td>0</td><td>0</td><td>100.0</td><td>1.80</td><td style="">-0.45</td><td>0.05</td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>-0.32</td><td>-0.56</td><td>-0.38</td><td>-0.70</td><td>-0.030</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.064</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16058">김세훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.074</td><td>5</td><td>0</td><td>8.1</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>3.24</td><td style="">-0.70</td><td></td><td>0.07</td><td>-0.24</td><td></td><td></td><td></td><td></td><td>-0.87</td><td>-17.82</td><td>0.06</td><td>-0.81</td><td>-0.079</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.074</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13250">한석현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.082</td><td>22</td><td>8</td><td>100.1</td><td>20</td><td>18</td><td>2</td><td>0</td><td>100.0</td><td>1.79</td><td style="">-1.18</td><td>0.39</td><td>0.30</td><td></td><td></td><td></td><td></td><td></td><td>-0.48</td><td>-1.74</td><td>-0.41</td><td>-0.89</td><td>-0.044</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.082</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14785">김휘집</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.082</td><td>24</td><td>22</td><td>162.2</td><td>72</td><td>29</td><td>40</td><td>3</td><td>95.8</td><td>3.82</td><td style="">-2.56</td><td></td><td>-0.06</td><td>0.13</td><td></td><td></td><td></td><td></td><td>-2.50</td><td>-2.57</td><td>1.60</td><td>-0.90</td><td>-0.228</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.082</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11153">김성욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.091</td><td>18</td><td>3</td><td>52.1</td><td>15</td><td>14</td><td>1</td><td>0</td><td>100.0</td><td>2.58</td><td style="">-0.95</td><td>0.11</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>-0.77</td><td>-0.86</td><td>-0.22</td><td>-0.99</td><td>-0.071</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.091</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14661">박영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.107</td><td>2</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-1.18</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-1.17</td><td>-8.88</td><td>0.00</td><td>-1.17</td><td>-0.107</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.107</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14661">박영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.124</td><td>9</td><td>0</td><td>16.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>0.56</td><td style="">-1.35</td><td>0.03</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-1.30</td><td>-9.83</td><td>-0.06</td><td>-1.36</td><td>-0.118</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.124</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11153">김성욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.125</td><td>102</td><td>83</td><td>743.0</td><td>203</td><td>197</td><td>5</td><td>1</td><td>99.5</td><td>2.45</td><td style="">-2.84</td><td>0.42</td><td>1.04</td><td></td><td></td><td></td><td></td><td></td><td>-1.37</td><td>-1.53</td><td>0.00</td><td>-1.37</td><td>-0.125</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.125</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14221">최정원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.135</td><td>20</td><td>10</td><td>107.2</td><td>64</td><td>33</td><td>30</td><td>1</td><td>98.4</td><td>5.27</td><td style="">-2.96</td><td></td><td>0.15</td><td>0.77</td><td></td><td></td><td></td><td></td><td>-2.04</td><td>-4.51</td><td>0.56</td><td>-1.48</td><td>-0.186</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.135</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10189">박건우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.151</td><td>3</td><td>2</td><td>15.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>2.40</td><td style="">-1.41</td><td>-0.27</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-1.65</td><td>-2.67</td><td>0.00</td><td>-1.65</td><td>-0.151</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.151</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11172">권희동</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.165</td><td>7</td><td>5</td><td>42.1</td><td>11</td><td>11</td><td>0</td><td>0</td><td>100.0</td><td>2.34</td><td style="">-1.70</td><td>-0.01</td><td>0.13</td><td></td><td></td><td></td><td></td><td></td><td>-1.58</td><td>-1.85</td><td>-0.23</td><td>-1.81</td><td>-0.144</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.165</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14716">김한별</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.178</td><td>21</td><td>7</td><td>80.0</td><td>31</td><td>9</td><td>21</td><td>1</td><td>96.8</td><td>3.38</td><td style="">-2.71</td><td></td><td>0.21</td><td>-0.15</td><td></td><td></td><td></td><td></td><td>-2.65</td><td>-9.53</td><td>0.70</td><td>-1.95</td><td>-0.242</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.178</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11153">김성욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.194</td><td>24</td><td>8</td><td>80.0</td><td>15</td><td>15</td><td>0</td><td>0</td><td>100.0</td><td>1.69</td><td style="">-1.14</td><td>-0.88</td><td>0.24</td><td></td><td></td><td></td><td></td><td></td><td>-1.79</td><td>-1.99</td><td>-0.34</td><td>-2.13</td><td>-0.163</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.194</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13250">한석현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.211</td><td>8</td><td>5</td><td>47.0</td><td>16</td><td>15</td><td>1</td><td>0</td><td>100.0</td><td>3.06</td><td style="">-2.05</td><td>-0.36</td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>-2.31</td><td>-8.33</td><td>0.00</td><td>-2.31</td><td>-0.211</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.211</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15451">박한결</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.259</td><td>21</td><td>13</td><td>110.1</td><td>21</td><td>20</td><td>0</td><td>1</td><td>95.2</td><td>1.63</td><td style="">-1.96</td><td>0.01</td><td>-0.38</td><td></td><td></td><td></td><td></td><td></td><td>-2.32</td><td>-11.93</td><td>-0.52</td><td>-2.84</td><td>-0.212</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.259</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13261">천재환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.389</td><td>48</td><td>26</td><td>248.0</td><td>44</td><td>41</td><td>1</td><td>2</td><td>95.5</td><td>1.52</td><td style="">-3.37</td><td>0.48</td><td>-0.25</td><td></td><td></td><td></td><td></td><td></td><td>-3.15</td><td>-5.10</td><td>-1.11</td><td>-4.26</td><td>-0.288</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.389</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10189">박건우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.398</td><td>68</td><td>67</td><td>522.0</td><td>108</td><td>104</td><td>3</td><td>1</td><td>99.1</td><td>1.84</td><td style="">-2.73</td><td>0.02</td><td>1.08</td><td></td><td></td><td></td><td></td><td></td><td>-1.63</td><td>-2.64</td><td>-2.72</td><td>-4.35</td><td>-0.149</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.398</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14597">박시원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.407</td><td>24</td><td>12</td><td>143.1</td><td>29</td><td>24</td><td>3</td><td>2</td><td>93.1</td><td>1.70</td><td style="">-3.12</td><td>-0.11</td><td>-0.57</td><td></td><td></td><td></td><td></td><td></td><td>-3.80</td><td>-9.94</td><td>-0.66</td><td>-4.46</td><td>-0.347</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.407</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16066">데이비슨</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-1.160</td><td>109</td><td>109</td><td>890.1</td><td>813</td><td>733</td><td>69</td><td>11</td><td>98.6</td><td>8.11</td><td style="">-2.26</td><td></td><td>-1.12</td><td></td><td>0.08</td><td></td><td></td><td></td><td>-3.29</td><td>-3.62</td><td>-9.40</td><td>-12.69</td><td>-0.301</td><td style="background-color:#F3F3F3; font-weight:bold;">-1.160</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14222">김범준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>3.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.03</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.03</td><td>-0.78</td><td></td><td></td><td>-0.002</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14716">김한별</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>1.1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.03</td><td></td><td></td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11355">류진욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>49</td><td>0</td><td>42.1</td><td>12</td><td>6</td><td>5</td><td>1</td><td>91.7</td><td>2.34</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14764">한재승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>49</td><td>0</td><td>45.1</td><td>8</td><td>2</td><td>5</td><td>1</td><td>87.5</td><td>1.39</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12903">김수윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0.0</td><td>0.00</td><td style="">-0.85</td><td></td><td>-0.50</td><td></td><td></td><td></td><td></td><td></td><td>-1.34</td><td>-21.48</td><td></td><td></td><td>-0.123</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14155">송명기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>32</td><td>0</td><td>38.1</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>0.23</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12560">도태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.04</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.03</td><td>-0.05</td><td></td><td></td><td>-0.003</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14747">김재열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>68</td><td>0</td><td>68.2</td><td>10</td><td>3</td><td>5</td><td>2</td><td>80.0</td><td>1.05</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13088">김영규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>42</td><td>0</td><td>45.2</td><td>11</td><td>2</td><td>8</td><td>1</td><td>90.9</td><td>1.97</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td></td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11087">강승호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.923</td><td>124</td><td>118</td><td>988.0</td><td>532</td><td>234</td><td>286</td><td>12</td><td>97.7</td><td>4.74</td><td style="">5.31</td><td></td><td>-0.05</td><td>-0.06</td><td></td><td></td><td></td><td></td><td>5.20</td><td>5.35</td><td>4.90</td><td>10.10</td><td>0.475</td><td style="background-color:#F3F3F3; font-weight:bold;">0.923</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12549">김기연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.895</td><td>84</td><td>61</td><td>579.0</td><td>501</td><td>474</td><td>25</td><td>2</td><td>99.6</td><td>7.76</td><td style="">-0.24</td><td></td><td>1.09</td><td></td><td>-0.26</td><td>1.28</td><td>2.43</td><td></td><td>3.56</td><td>5.40</td><td>6.24</td><td>9.80</td><td>0.325</td><td style="background-color:#F3F3F3; font-weight:bold;">0.895</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12522">박준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.863</td><td>57</td><td>50</td><td>434.2</td><td>222</td><td>83</td><td>135</td><td>4</td><td>98.2</td><td>4.51</td><td style="">2.93</td><td></td><td>1.85</td><td>0.74</td><td></td><td></td><td></td><td></td><td>5.52</td><td>12.24</td><td>3.92</td><td>9.44</td><td>0.505</td><td style="background-color:#F3F3F3; font-weight:bold;">0.863</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10165">양의지</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.517</td><td>76</td><td>74</td><td>608.1</td><td>579</td><td>551</td><td>24</td><td>4</td><td>99.3</td><td>8.51</td><td style="">0.03</td><td></td><td>0.19</td><td></td><td>-0.17</td><td>-0.93</td><td>-1.50</td><td></td><td>-1.93</td><td>-2.33</td><td>7.58</td><td>5.66</td><td>-0.176</td><td style="background-color:#F3F3F3; font-weight:bold;">0.517</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13073">전민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.510</td><td>64</td><td>43</td><td>395.0</td><td>180</td><td>74</td><td>102</td><td>4</td><td>97.8</td><td>4.01</td><td style="">1.94</td><td></td><td>1.50</td><td>-1.40</td><td></td><td></td><td></td><td></td><td>2.04</td><td>2.94</td><td>3.54</td><td>5.58</td><td>0.187</td><td style="background-color:#F3F3F3; font-weight:bold;">0.510</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10195">정수빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.471</td><td>133</td><td>131</td><td>1114.0</td><td>319</td><td>313</td><td>5</td><td>1</td><td>99.7</td><td>2.57</td><td style="">2.03</td><td>1.31</td><td>1.82</td><td></td><td></td><td></td><td></td><td></td><td>5.15</td><td>5.46</td><td>0.00</td><td>5.15</td><td>0.471</td><td style="background-color:#F3F3F3; font-weight:bold;">0.471</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10184">허경민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.334</td><td>110</td><td>109</td><td>883.0</td><td>225</td><td>77</td><td>143</td><td>5</td><td>97.8</td><td>2.24</td><td style="">-0.33</td><td></td><td>3.55</td><td>0.48</td><td>-0.05</td><td></td><td></td><td></td><td>3.66</td><td>4.58</td><td>0.00</td><td>3.66</td><td>0.334</td><td style="background-color:#F3F3F3; font-weight:bold;">0.334</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12894">이유찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.320</td><td>39</td><td>12</td><td>156.2</td><td>96</td><td>37</td><td>59</td><td>0</td><td>100.0</td><td>5.51</td><td style="">1.47</td><td></td><td>0.95</td><td>0.42</td><td></td><td></td><td></td><td></td><td>2.83</td><td>3.96</td><td>0.67</td><td>3.50</td><td>0.258</td><td style="background-color:#F3F3F3; font-weight:bold;">0.320</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12894">이유찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.274</td><td>20</td><td>11</td><td>103.0</td><td>47</td><td>22</td><td>25</td><td>0</td><td>100.0</td><td>4.11</td><td style="">1.26</td><td></td><td>0.91</td><td>-0.01</td><td></td><td></td><td></td><td></td><td>2.16</td><td>3.02</td><td>0.84</td><td>3.00</td><td>0.198</td><td style="background-color:#F3F3F3; font-weight:bold;">0.274</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13073">전민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.266</td><td>34</td><td>10</td><td>129.0</td><td>40</td><td>20</td><td>19</td><td>1</td><td>97.5</td><td>2.72</td><td style="">2.65</td><td></td><td>0.38</td><td>-0.19</td><td>0.06</td><td></td><td></td><td></td><td>2.91</td><td>4.19</td><td>0.00</td><td>2.91</td><td>0.266</td><td style="background-color:#F3F3F3; font-weight:bold;">0.266</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12894">이유찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.256</td><td>27</td><td>20</td><td>174.0</td><td>56</td><td>17</td><td>37</td><td>2</td><td>96.4</td><td>2.79</td><td style="">2.17</td><td></td><td>0.19</td><td>-0.05</td><td>0.49</td><td></td><td></td><td></td><td>2.81</td><td>3.92</td><td>0.00</td><td>2.81</td><td>0.256</td><td style="background-color:#F3F3F3; font-weight:bold;">0.256</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12524">조수행</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.246</td><td>43</td><td>30</td><td>274.1</td><td>72</td><td>71</td><td>1</td><td>0</td><td>100.0</td><td>2.36</td><td style="">3.09</td><td>-0.03</td><td>0.83</td><td></td><td></td><td></td><td></td><td></td><td>3.90</td><td>4.32</td><td>-1.20</td><td>2.70</td><td>0.356</td><td style="background-color:#F3F3F3; font-weight:bold;">0.246</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12524">조수행</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.191</td><td>70</td><td>52</td><td>491.1</td><td>146</td><td>143</td><td>2</td><td>1</td><td>99.3</td><td>2.66</td><td style="">4.35</td><td>-0.26</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>4.15</td><td>4.59</td><td>-2.05</td><td>2.10</td><td>0.379</td><td style="background-color:#F3F3F3; font-weight:bold;">0.191</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14170">김대한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.149</td><td>29</td><td>12</td><td>124.0</td><td>35</td><td>34</td><td>0</td><td>1</td><td>97.1</td><td>2.47</td><td style="">2.46</td><td>-0.23</td><td>-0.13</td><td></td><td></td><td></td><td></td><td></td><td>2.10</td><td>4.96</td><td>-0.47</td><td>1.63</td><td>0.192</td><td style="background-color:#F3F3F3; font-weight:bold;">0.149</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14738">양찬열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.085</td><td>7</td><td>2</td><td>28.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>1.29</td><td style="">0.98</td><td>-0.03</td><td>0.08</td><td></td><td></td><td></td><td></td><td></td><td>1.03</td><td>13.53</td><td>-0.10</td><td>0.93</td><td>0.094</td><td style="background-color:#F3F3F3; font-weight:bold;">0.085</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12522">박준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.076</td><td>9</td><td>2</td><td>27.0</td><td>7</td><td>4</td><td>3</td><td>0</td><td>100.0</td><td>2.33</td><td style="">0.29</td><td></td><td>0.19</td><td>0.29</td><td>0.07</td><td></td><td></td><td></td><td>0.83</td><td>1.85</td><td>0.00</td><td>0.83</td><td>0.076</td><td style="background-color:#F3F3F3; font-weight:bold;">0.076</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11087">강승호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.063</td><td>32</td><td>13</td><td>143.2</td><td>145</td><td>126</td><td>18</td><td>1</td><td>99.3</td><td>9.02</td><td style="">1.74</td><td></td><td>0.21</td><td></td><td>0.06</td><td></td><td></td><td></td><td>2.01</td><td>2.06</td><td>-1.32</td><td>0.69</td><td>0.183</td><td style="background-color:#F3F3F3; font-weight:bold;">0.063</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12523">서예일</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.062</td><td>15</td><td>2</td><td>46.0</td><td>13</td><td>3</td><td>9</td><td>1</td><td>92.3</td><td>2.35</td><td style="">1.16</td><td></td><td>-0.19</td><td>-0.29</td><td></td><td></td><td></td><td></td><td>0.68</td><td>4.09</td><td>0.00</td><td>0.68</td><td>0.062</td><td style="background-color:#F3F3F3; font-weight:bold;">0.062</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12894">이유찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.048</td><td>5</td><td>3</td><td>17.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>1.59</td><td style="">0.47</td><td>0.12</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>0.64</td><td>0.89</td><td>-0.11</td><td>0.53</td><td>0.058</td><td style="background-color:#F3F3F3; font-weight:bold;">0.048</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16069">임종성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.046</td><td>1</td><td>1</td><td>9.0</td><td>2</td><td>0</td><td>2</td><td>0</td><td>100.0</td><td>2.00</td><td style="">0.44</td><td></td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>0.50</td><td>72.24</td><td>0.00</td><td>0.50</td><td>0.046</td><td style="background-color:#F3F3F3; font-weight:bold;">0.046</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12606">홍성호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.030</td><td>3</td><td>0</td><td>5.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.32</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.34</td><td>3.23</td><td>-0.01</td><td>0.33</td><td>0.031</td><td style="background-color:#F3F3F3; font-weight:bold;">0.030</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12523">서예일</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.027</td><td>4</td><td>0</td><td>6.0</td><td>2</td><td>0</td><td>2</td><td>0</td><td>100.0</td><td>3.00</td><td style="">0.23</td><td></td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>0.28</td><td>1.69</td><td>0.02</td><td>0.30</td><td>0.026</td><td style="background-color:#F3F3F3; font-weight:bold;">0.027</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11328">안승한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.025</td><td>2</td><td>1</td><td>9.1</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>6.75</td><td style="">0.00</td><td></td><td>0.03</td><td></td><td></td><td>-0.14</td><td>0.45</td><td></td><td>0.20</td><td>7.37</td><td>0.07</td><td>0.28</td><td>0.019</td><td style="background-color:#F3F3F3; font-weight:bold;">0.025</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11097">장승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.015</td><td>9</td><td>7</td><td>58.0</td><td>59</td><td>57</td><td>2</td><td>0</td><td>100.0</td><td>9.16</td><td style="">-0.24</td><td></td><td>0.21</td><td></td><td>0.05</td><td>-0.21</td><td>-0.27</td><td></td><td>-0.38</td><td>-6.16</td><td>0.55</td><td>0.17</td><td>-0.035</td><td style="background-color:#F3F3F3; font-weight:bold;">0.015</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12894">이유찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.015</td><td>2</td><td>0</td><td>3.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>6.00</td><td style="">0.20</td><td>-0.05</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.16</td><td>0.22</td><td>0.00</td><td>0.16</td><td>0.015</td><td style="background-color:#F3F3F3; font-weight:bold;">0.015</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14570">장규빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.009</td><td>3</td><td>0</td><td>7.0</td><td>9</td><td>8</td><td>1</td><td>0</td><td>100.0</td><td>11.57</td><td style="">-0.09</td><td></td><td>0.03</td><td></td><td></td><td></td><td>0.13</td><td></td><td>0.02</td><td>1.11</td><td>0.07</td><td>0.10</td><td>0.002</td><td style="background-color:#F3F3F3; font-weight:bold;">0.009</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16076">류현준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.007</td><td>1</td><td>0</td><td>3.0</td><td>4</td><td>3</td><td>1</td><td>0</td><td>100.0</td><td>12.00</td><td style="">0.00</td><td></td><td>0.01</td><td></td><td></td><td></td><td>0.07</td><td></td><td>0.06</td><td>4.18</td><td>0.02</td><td>0.08</td><td>0.005</td><td style="background-color:#F3F3F3; font-weight:bold;">0.007</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16068">여동건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.006</td><td>5</td><td>2</td><td>21.0</td><td>13</td><td>5</td><td>8</td><td>0</td><td>100.0</td><td>5.57</td><td style="">0.14</td><td></td><td>0.13</td><td>-0.29</td><td></td><td></td><td></td><td></td><td>-0.02</td><td>-0.40</td><td>0.09</td><td>0.07</td><td>-0.002</td><td style="background-color:#F3F3F3; font-weight:bold;">0.006</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13665">권휘</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.000</td><td>8</td><td>0</td><td>9.0</td><td>3</td><td>1</td><td>1</td><td>1</td><td>66.7</td><td>2.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">0.000</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12606">홍성호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.001</td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.01</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>-0.03</td><td>-0.01</td><td>-0.01</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.001</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12606">홍성호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.002</td><td>3</td><td>0</td><td>5.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.00</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.02</td><td>0.20</td><td>-0.04</td><td>-0.02</td><td>0.002</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.002</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14175">김태근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.003</td><td>10</td><td>0</td><td>19.2</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>2.29</td><td style="">0.67</td><td>-0.73</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>-0.01</td><td>-0.03</td><td>-0.03</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.003</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15515">박민준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.008</td><td>4</td><td>1</td><td>10.0</td><td>10</td><td>10</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.00</td><td></td><td>0.04</td><td></td><td></td><td></td><td>-0.28</td><td></td><td>-0.16</td><td>-4.65</td><td>0.07</td><td>-0.09</td><td>-0.015</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.008</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16072">전다민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.008</td><td>5</td><td>1</td><td>16.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>2.25</td><td style="">0.34</td><td>-0.46</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.09</td><td>-0.53</td><td>0.00</td><td>-0.09</td><td>-0.008</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.008</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16072">전다민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.010</td><td>2</td><td>0</td><td>8.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.13</td><td style="">0.16</td><td>-0.28</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.09</td><td>-0.53</td><td>-0.02</td><td>-0.11</td><td>-0.008</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.010</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14738">양찬열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.022</td><td>3</td><td>0</td><td>6.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.24</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.23</td><td>-3.03</td><td>-0.01</td><td>-0.24</td><td>-0.021</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.022</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16072">전다민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.039</td><td>7</td><td>4</td><td>38.2</td><td>4</td><td>3</td><td>1</td><td>0</td><td>100.0</td><td>0.93</td><td style="">-0.52</td><td>0.21</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-0.27</td><td>-1.53</td><td>-0.16</td><td>-0.43</td><td>-0.024</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.039</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15512">윤준호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.056</td><td>3</td><td>0</td><td>9.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>5.00</td><td style="">0.00</td><td></td><td>0.03</td><td></td><td></td><td></td><td>-1.02</td><td></td><td>-0.68</td><td>-32.69</td><td>0.07</td><td>-0.61</td><td>-0.062</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.056</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14170">김대한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.056</td><td>5</td><td>0</td><td>10.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>3.60</td><td style="">-0.63</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.61</td><td>-1.45</td><td>0.00</td><td>-0.61</td><td>-0.056</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.056</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10174">김재호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.063</td><td>52</td><td>38</td><td>326.0</td><td>148</td><td>65</td><td>76</td><td>7</td><td>95.3</td><td>3.89</td><td style="">-3.93</td><td></td><td>-0.62</td><td>0.89</td><td></td><td></td><td></td><td></td><td>-3.66</td><td>-9.26</td><td>2.98</td><td>-0.68</td><td>-0.335</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.063</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11098">김인태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.068</td><td>1</td><td>1</td><td>6.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-0.72</td><td>0.01</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.70</td><td>-10.07</td><td>-0.04</td><td>-0.74</td><td>-0.064</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.068</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11198">박계범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.076</td><td>13</td><td>1</td><td>24.0</td><td>8</td><td>3</td><td>5</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-1.22</td><td></td><td>0.15</td><td>0.19</td><td></td><td></td><td></td><td></td><td>-0.89</td><td>-5.32</td><td>0.05</td><td>-0.84</td><td>-0.081</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.076</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14175">김태근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.077</td><td>16</td><td>4</td><td>53.2</td><td>15</td><td>15</td><td>0</td><td>0</td><td>100.0</td><td>2.52</td><td style="">-0.97</td><td>0.24</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>-0.67</td><td>-2.25</td><td>-0.17</td><td>-0.84</td><td>-0.061</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.077</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11098">김인태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.104</td><td>7</td><td>5</td><td>38.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>1.18</td><td style="">-1.48</td><td>0.47</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-0.96</td><td>-13.85</td><td>-0.18</td><td>-1.14</td><td>-0.088</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.104</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13073">전민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.120</td><td>3</td><td>1</td><td>10.0</td><td>10</td><td>9</td><td>0</td><td>1</td><td>90.0</td><td>8.10</td><td style="">-0.80</td><td></td><td>-0.45</td><td></td><td></td><td></td><td></td><td></td><td>-1.25</td><td>-1.80</td><td>-0.06</td><td>-1.31</td><td>-0.114</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.120</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16158">제러드</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.125</td><td>2</td><td>0</td><td>5.0</td><td>5</td><td>4</td><td>0</td><td>1</td><td>80.0</td><td>7.20</td><td style="">-1.36</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-1.33</td><td>-5.05</td><td>-0.04</td><td>-1.37</td><td>-0.122</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.125</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14175">김태근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.137</td><td>7</td><td>1</td><td>21.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>1.29</td><td style="">-1.07</td><td>-0.48</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-1.50</td><td>-5.03</td><td>0.00</td><td>-1.50</td><td>-0.137</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.137</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12524">조수행</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.158</td><td>22</td><td>11</td><td>119.2</td><td>34</td><td>33</td><td>1</td><td>0</td><td>100.0</td><td>2.56</td><td style="">-1.98</td><td>0.00</td><td>0.25</td><td></td><td></td><td></td><td></td><td></td><td>-1.73</td><td>-1.92</td><td>0.00</td><td>-1.73</td><td>-0.158</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.158</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13073">전민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.164</td><td>14</td><td>11</td><td>93.0</td><td>60</td><td>20</td><td>38</td><td>2</td><td>96.7</td><td>5.61</td><td style="">-1.51</td><td></td><td>-0.44</td><td>-0.26</td><td></td><td></td><td></td><td></td><td>-2.21</td><td>-3.18</td><td>0.41</td><td>-1.80</td><td>-0.202</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.164</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14170">김대한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.172</td><td>25</td><td>6</td><td>87.0</td><td>16</td><td>16</td><td>0</td><td>0</td><td>100.0</td><td>1.66</td><td style="">-2.06</td><td>0.36</td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>-1.60</td><td>-3.78</td><td>-0.28</td><td>-1.88</td><td>-0.146</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.172</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11198">박계범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.194</td><td>3</td><td>2</td><td>19.0</td><td>13</td><td>1</td><td>10</td><td>2</td><td>84.6</td><td>5.21</td><td style="">-1.21</td><td></td><td>-0.84</td><td>-0.23</td><td></td><td></td><td></td><td></td><td>-2.28</td><td>-13.69</td><td>0.16</td><td>-2.12</td><td>-0.208</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.194</td></tr><tr><td style="text-align:center;">52</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16158">제러드</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.196</td><td>18</td><td>17</td><td>147.0</td><td>36</td><td>34</td><td>2</td><td>0</td><td>100.0</td><td>2.20</td><td style="">-1.65</td><td>-0.14</td><td>0.44</td><td></td><td></td><td></td><td></td><td></td><td>-1.35</td><td>-5.10</td><td>-0.80</td><td>-2.15</td><td>-0.123</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.196</td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11198">박계범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.227</td><td>10</td><td>0</td><td>15.2</td><td>5</td><td>2</td><td>2</td><td>1</td><td>80.0</td><td>2.30</td><td style="">-1.85</td><td></td><td>-0.39</td><td>-0.24</td><td></td><td></td><td></td><td></td><td>-2.49</td><td>-14.94</td><td>0.00</td><td>-2.49</td><td>-0.227</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.227</td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16158">제러드</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.303</td><td>15</td><td>14</td><td>118.1</td><td>23</td><td>23</td><td>0</td><td>0</td><td>100.0</td><td>1.75</td><td style="">-2.58</td><td>-0.23</td><td>0.13</td><td></td><td></td><td></td><td></td><td></td><td>-2.68</td><td>-10.16</td><td>-0.63</td><td>-3.31</td><td>-0.245</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.303</td></tr><tr><td style="text-align:center;">55</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10643">김재환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.437</td><td>45</td><td>43</td><td>335.1</td><td>71</td><td>71</td><td>0</td><td>0</td><td>100.0</td><td>1.91</td><td style="">-3.11</td><td>-0.27</td><td>0.38</td><td></td><td></td><td></td><td></td><td></td><td>-3.00</td><td>-3.18</td><td>-1.78</td><td>-4.78</td><td>-0.274</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.437</td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12894">이유찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.473</td><td>17</td><td>16</td><td>113.1</td><td>17</td><td>16</td><td>0</td><td>1</td><td>94.1</td><td>1.27</td><td style="">-3.51</td><td>-0.70</td><td>-0.37</td><td></td><td></td><td></td><td></td><td></td><td>-4.58</td><td>-6.40</td><td>-0.60</td><td>-5.18</td><td>-0.418</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.473</td></tr><tr><td style="text-align:center;">57</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15000">라모스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.490</td><td>79</td><td>79</td><td>654.2</td><td>131</td><td>123</td><td>4</td><td>4</td><td>96.9</td><td>1.75</td><td style="">-1.65</td><td>-0.24</td><td>-0.03</td><td></td><td></td><td></td><td></td><td></td><td>-1.92</td><td>-3.46</td><td>-3.44</td><td>-5.36</td><td>-0.175</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.490</td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11213">양석환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.711</td><td>131</td><td>130</td><td>1118.0</td><td>1038</td><td>943</td><td>85</td><td>10</td><td>99.0</td><td>8.28</td><td style="">2.55</td><td></td><td>0.51</td><td></td><td>0.21</td><td></td><td></td><td></td><td>3.27</td><td>3.32</td><td>-11.06</td><td>-7.79</td><td>0.299</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.711</td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10690">김강률</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>52</td><td>0</td><td>42.0</td><td>9</td><td>4</td><td>5</td><td>0</td><td>100.0</td><td>1.93</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12850">박치국</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>50</td><td>0</td><td>48.0</td><td>10</td><td>1</td><td>8</td><td>1</td><td>90.0</td><td>1.69</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13071">정철원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>33</td><td>0</td><td>32.1</td><td>2</td><td>0</td><td>2</td><td>0</td><td>100.0</td><td>0.56</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14737">오명진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.28</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.27</td><td>-19.42</td><td></td><td></td><td>-0.025</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14173">이교훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>32</td><td>0</td><td>35.1</td><td>7</td><td>5</td><td>2</td><td>0</td><td>100.0</td><td>1.78</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14769">김동주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>14</td><td>9</td><td>50.0</td><td>5</td><td>2</td><td>3</td><td>0</td><td>100.0</td><td>0.90</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12568">이영하</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>56</td><td>1</td><td>65.1</td><td>12</td><td>4</td><td>6</td><td>2</td><td>83.3</td><td>1.38</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13268">김호준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>15</td><td>1</td><td>13.1</td><td>2</td><td>0</td><td>2</td><td>0</td><td>100.0</td><td>1.35</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15099">이병헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>76</td><td>0</td><td>65.1</td><td>16</td><td>2</td><td>13</td><td>1</td><td>93.8</td><td>2.07</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10696">홍건희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>64</td><td>0</td><td>59.1</td><td>14</td><td>1</td><td>12</td><td>1</td><td>92.9</td><td>1.97</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13072">김민규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>12</td><td>4</td><td>25.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11300">박정수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>28</td><td>1</td><td>29.2</td><td>3</td><td>0</td><td>2</td><td>1</td><td>66.7</td><td>0.61</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14770">최승용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>12</td><td>6</td><td>27.0</td><td>4</td><td>0</td><td>4</td><td>0</td><td>100.0</td><td>1.33</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11198">박계범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.03</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12847">김명신</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>32</td><td>0</td><td>32.2</td><td>5</td><td>2</td><td>3</td><td>0</td><td>100.0</td><td>1.38</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12970">김민혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.12</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15127">최지강</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>52</td><td>0</td><td>50.0</td><td>12</td><td>2</td><td>9</td><td>1</td><td>91.7</td><td>1.98</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16067">김택연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>60</td><td>0</td><td>65.0</td><td>7</td><td>1</td><td>6</td><td>0</td><td>100.0</td><td>0.97</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12905">김혜성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.142</td><td>119</td><td>118</td><td>1015.0</td><td>616</td><td>258</td><td>342</td><td>16</td><td>97.4</td><td>5.32</td><td style="">8.60</td><td></td><td>-1.90</td><td>0.48</td><td></td><td></td><td></td><td></td><td>7.18</td><td>8.15</td><td>5.32</td><td>12.50</td><td>0.656</td><td style="background-color:#F3F3F3; font-weight:bold;">1.142</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11244">김태진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.895</td><td>57</td><td>33</td><td>346.0</td><td>171</td><td>64</td><td>104</td><td>3</td><td>98.2</td><td>4.37</td><td style="">4.68</td><td></td><td>1.56</td><td>0.57</td><td></td><td></td><td></td><td></td><td>6.82</td><td>12.12</td><td>2.98</td><td>9.80</td><td>0.623</td><td style="background-color:#F3F3F3; font-weight:bold;">0.895</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10870">김재현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.787</td><td>109</td><td>85</td><td>758.1</td><td>682</td><td>627</td><td>48</td><td>7</td><td>99.0</td><td>8.01</td><td style="">-1.18</td><td></td><td>-0.78</td><td></td><td>-0.12</td><td>2.21</td><td>0.98</td><td></td><td>0.81</td><td>1.06</td><td>7.80</td><td>8.61</td><td>0.074</td><td style="background-color:#F3F3F3; font-weight:bold;">0.787</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11376">송성문</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.417</td><td>97</td><td>86</td><td>773.0</td><td>208</td><td>66</td><td>135</td><td>7</td><td>96.6</td><td>2.34</td><td style="">2.67</td><td></td><td>1.80</td><td>0.12</td><td>-0.03</td><td></td><td></td><td></td><td>4.56</td><td>4.63</td><td>0.00</td><td>4.56</td><td>0.417</td><td style="background-color:#F3F3F3; font-weight:bold;">0.417</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15472">김건희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.296</td><td>66</td><td>49</td><td>431.2</td><td>295</td><td>267</td><td>24</td><td>4</td><td>98.6</td><td>6.07</td><td style="">-0.32</td><td></td><td>-0.45</td><td></td><td>-0.37</td><td>-1.12</td><td>0.91</td><td></td><td>-1.63</td><td>-2.83</td><td>4.87</td><td>3.24</td><td>-0.149</td><td style="background-color:#F3F3F3; font-weight:bold;">0.296</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14785">김휘집</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.266</td><td>44</td><td>40</td><td>338.1</td><td>163</td><td>51</td><td>106</td><td>6</td><td>96.3</td><td>4.18</td><td style="">-1.54</td><td></td><td>-0.01</td><td>1.39</td><td></td><td></td><td></td><td></td><td>-0.17</td><td>-0.17</td><td>3.08</td><td>2.91</td><td>-0.015</td><td style="background-color:#F3F3F3; font-weight:bold;">0.266</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11376">송성문</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.227</td><td>19</td><td>19</td><td>151.2</td><td>85</td><td>36</td><td>47</td><td>2</td><td>97.6</td><td>4.93</td><td style="">2.15</td><td></td><td>-0.09</td><td>-0.39</td><td></td><td></td><td></td><td></td><td>1.68</td><td>1.70</td><td>0.80</td><td>2.48</td><td>0.154</td><td style="background-color:#F3F3F3; font-weight:bold;">0.227</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13223">변상권</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.174</td><td>9</td><td>5</td><td>51.2</td><td>18</td><td>18</td><td>0</td><td>0</td><td>100.0</td><td>3.14</td><td style="">2.51</td><td>-0.55</td><td>0.16</td><td></td><td></td><td></td><td></td><td></td><td>2.12</td><td>3.96</td><td>-0.21</td><td>1.91</td><td>0.193</td><td style="background-color:#F3F3F3; font-weight:bold;">0.174</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14591">이주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.172</td><td>48</td><td>40</td><td>341.0</td><td>104</td><td>102</td><td>1</td><td>1</td><td>99.0</td><td>2.72</td><td style="">2.02</td><td>-0.34</td><td>0.21</td><td></td><td></td><td></td><td></td><td></td><td>1.88</td><td>2.36</td><td>0.00</td><td>1.88</td><td>0.172</td><td style="background-color:#F3F3F3; font-weight:bold;">0.172</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16136">원성준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.169</td><td>7</td><td>1</td><td>20.0</td><td>8</td><td>7</td><td>1</td><td>0</td><td>100.0</td><td>3.60</td><td style="">1.06</td><td>0.85</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>1.93</td><td>5.45</td><td>-0.08</td><td>1.85</td><td>0.176</td><td style="background-color:#F3F3F3; font-weight:bold;">0.169</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11244">김태진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.138</td><td>8</td><td>3</td><td>35.0</td><td>11</td><td>11</td><td>0</td><td>0</td><td>100.0</td><td>2.83</td><td style="">1.54</td><td>0.10</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>1.68</td><td>2.98</td><td>-0.16</td><td>1.52</td><td>0.153</td><td style="background-color:#F3F3F3; font-weight:bold;">0.138</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15132">박수종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.138</td><td>21</td><td>10</td><td>93.1</td><td>33</td><td>33</td><td>0</td><td>0</td><td>100.0</td><td>3.18</td><td style="">1.15</td><td>0.65</td><td>0.11</td><td></td><td></td><td></td><td></td><td></td><td>1.90</td><td>3.43</td><td>-0.39</td><td>1.51</td><td>0.174</td><td style="background-color:#F3F3F3; font-weight:bold;">0.138</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11226">임병욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.131</td><td>12</td><td>8</td><td>74.0</td><td>16</td><td>16</td><td>0</td><td>0</td><td>100.0</td><td>1.95</td><td style="">1.61</td><td>-0.09</td><td>0.22</td><td></td><td></td><td></td><td></td><td></td><td>1.74</td><td>5.97</td><td>-0.31</td><td>1.43</td><td>0.159</td><td style="background-color:#F3F3F3; font-weight:bold;">0.131</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14214">김주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.100</td><td>16</td><td>4</td><td>56.2</td><td>32</td><td>13</td><td>18</td><td>1</td><td>96.9</td><td>4.92</td><td style="">0.26</td><td></td><td>0.00</td><td>0.45</td><td></td><td></td><td></td><td></td><td>0.71</td><td>4.65</td><td>0.38</td><td>1.09</td><td>0.065</td><td style="background-color:#F3F3F3; font-weight:bold;">0.100</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10035">이용규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.085</td><td>13</td><td>10</td><td>94.0</td><td>26</td><td>25</td><td>0</td><td>1</td><td>96.2</td><td>2.39</td><td style="">1.76</td><td>-0.17</td><td>-0.22</td><td></td><td></td><td></td><td></td><td></td><td>1.37</td><td>3.28</td><td>-0.44</td><td>0.93</td><td>0.125</td><td style="background-color:#F3F3F3; font-weight:bold;">0.085</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16128">고영우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.084</td><td>10</td><td>4</td><td>45.0</td><td>30</td><td>13</td><td>16</td><td>1</td><td>96.7</td><td>5.80</td><td style="">0.97</td><td></td><td>-0.23</td><td></td><td></td><td></td><td></td><td></td><td>0.74</td><td>1.14</td><td>0.18</td><td>0.92</td><td>0.068</td><td style="background-color:#F3F3F3; font-weight:bold;">0.084</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14133">주성원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.083</td><td>16</td><td>11</td><td>93.0</td><td>34</td><td>31</td><td>1</td><td>2</td><td>94.1</td><td>3.10</td><td style="">1.61</td><td>0.42</td><td>-0.72</td><td></td><td></td><td></td><td></td><td></td><td>1.31</td><td>6.99</td><td>-0.40</td><td>0.91</td><td>0.120</td><td style="background-color:#F3F3F3; font-weight:bold;">0.083</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15132">박수종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.072</td><td>56</td><td>23</td><td>253.1</td><td>88</td><td>84</td><td>0</td><td>4</td><td>95.5</td><td>2.98</td><td style="">2.65</td><td>-0.37</td><td>-1.48</td><td></td><td></td><td></td><td></td><td></td><td>0.79</td><td>1.42</td><td>0.00</td><td>0.79</td><td>0.072</td><td style="background-color:#F3F3F3; font-weight:bold;">0.072</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13223">변상권</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.072</td><td>37</td><td>32</td><td>278.0</td><td>77</td><td>76</td><td>0</td><td>1</td><td>98.7</td><td>2.46</td><td style="">2.99</td><td>-0.71</td><td>-0.19</td><td></td><td></td><td></td><td></td><td></td><td>2.09</td><td>3.91</td><td>-1.30</td><td>0.79</td><td>0.191</td><td style="background-color:#F3F3F3; font-weight:bold;">0.072</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14580">박주홍</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.058</td><td>4</td><td>1</td><td>9.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">0.63</td><td>0.01</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.67</td><td>3.88</td><td>-0.04</td><td>0.63</td><td>0.062</td><td style="background-color:#F3F3F3; font-weight:bold;">0.058</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14784">장재영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.043</td><td>20</td><td>19</td><td>157.1</td><td>44</td><td>42</td><td>2</td><td>0</td><td>100.0</td><td>2.52</td><td style="">0.36</td><td>0.42</td><td>0.48</td><td></td><td></td><td></td><td></td><td></td><td>1.25</td><td>4.73</td><td>-0.78</td><td>0.47</td><td>0.114</td><td style="background-color:#F3F3F3; font-weight:bold;">0.043</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14580">박주홍</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.041</td><td>17</td><td>13</td><td>99.0</td><td>26</td><td>25</td><td>1</td><td>0</td><td>100.0</td><td>2.36</td><td style="">0.90</td><td>-0.16</td><td>0.11</td><td></td><td></td><td></td><td></td><td></td><td>0.85</td><td>4.91</td><td>-0.40</td><td>0.45</td><td>0.078</td><td style="background-color:#F3F3F3; font-weight:bold;">0.041</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11244">김태진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.036</td><td>10</td><td>1</td><td>28.0</td><td>19</td><td>7</td><td>11</td><td>1</td><td>94.7</td><td>5.79</td><td style="">0.38</td><td></td><td>-0.33</td><td>0.24</td><td></td><td></td><td></td><td></td><td>0.29</td><td>0.51</td><td>0.10</td><td>0.39</td><td>0.026</td><td style="background-color:#F3F3F3; font-weight:bold;">0.036</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14851">김시앙</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.034</td><td>6</td><td>2</td><td>19.1</td><td>20</td><td>20</td><td>0</td><td>0</td><td>100.0</td><td>9.31</td><td style="">-0.09</td><td></td><td>0.07</td><td></td><td></td><td></td><td>0.32</td><td></td><td>0.20</td><td>4.86</td><td>0.17</td><td>0.37</td><td>0.019</td><td style="background-color:#F3F3F3; font-weight:bold;">0.034</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14580">박주홍</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.027</td><td>3</td><td>1</td><td>10.0</td><td>11</td><td>11</td><td>0</td><td>0</td><td>100.0</td><td>9.90</td><td style="">0.33</td><td></td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>0.38</td><td>2.17</td><td>-0.08</td><td>0.30</td><td>0.034</td><td style="background-color:#F3F3F3; font-weight:bold;">0.027</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14785">김휘집</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.027</td><td>9</td><td>6</td><td>53.0</td><td>11</td><td>2</td><td>9</td><td>0</td><td>100.0</td><td>1.87</td><td style="">-0.32</td><td></td><td>0.36</td><td>0.24</td><td></td><td></td><td></td><td></td><td>0.29</td><td>0.30</td><td>0.00</td><td>0.29</td><td>0.027</td><td style="background-color:#F3F3F3; font-weight:bold;">0.027</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14591">이주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.015</td><td>58</td><td>50</td><td>431.1</td><td>113</td><td>108</td><td>3</td><td>2</td><td>98.2</td><td>2.32</td><td style="">1.81</td><td>0.46</td><td>0.30</td><td></td><td></td><td></td><td></td><td></td><td>2.57</td><td>3.21</td><td>-2.40</td><td>0.17</td><td>0.234</td><td style="background-color:#F3F3F3; font-weight:bold;">0.015</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12516">이형종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.007</td><td>29</td><td>26</td><td>218.2</td><td>60</td><td>59</td><td>0</td><td>1</td><td>98.3</td><td>2.43</td><td style="">0.87</td><td>-0.05</td><td>0.16</td><td></td><td></td><td></td><td></td><td></td><td>0.98</td><td>4.03</td><td>-1.06</td><td>-0.08</td><td>0.090</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.007</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14214">김주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.009</td><td>5</td><td>0</td><td>11.0</td><td>6</td><td>3</td><td>2</td><td>1</td><td>83.3</td><td>4.09</td><td style="">0.28</td><td></td><td>-0.44</td><td></td><td></td><td></td><td></td><td></td><td>-0.15</td><td>-0.99</td><td>0.05</td><td>-0.10</td><td>-0.014</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.009</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14577">김병휘</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.009</td><td>22</td><td>19</td><td>146.2</td><td>58</td><td>17</td><td>39</td><td>2</td><td>96.6</td><td>3.44</td><td style="">-2.29</td><td></td><td>0.30</td><td>0.61</td><td></td><td></td><td></td><td></td><td>-1.38</td><td>-7.12</td><td>1.28</td><td>-0.10</td><td>-0.126</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.009</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16130">송지후</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.012</td><td>1</td><td>0</td><td>3.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.16</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.14</td><td>-10.10</td><td>0.01</td><td>-0.13</td><td>-0.013</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.012</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16136">원성준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.017</td><td>7</td><td>4</td><td>41.0</td><td>8</td><td>7</td><td>1</td><td>0</td><td>100.0</td><td>1.76</td><td style="">-0.99</td><td>0.87</td><td>0.12</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td>-0.19</td><td>-0.19</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.017</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14133">주성원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.034</td><td>4</td><td>2</td><td>21.2</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>2.08</td><td style="">-0.39</td><td>0.10</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.27</td><td>-1.42</td><td>-0.11</td><td>-0.38</td><td>-0.024</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.034</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13093">예진원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.041</td><td>6</td><td>1</td><td>19.0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>3.32</td><td style="">-0.15</td><td>-0.26</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.39</td><td>-2.52</td><td>-0.06</td><td>-0.45</td><td>-0.035</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.041</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11244">김태진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.041</td><td>2</td><td>0</td><td>6.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.33</td><td>-0.11</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.42</td><td>-0.74</td><td>-0.03</td><td>-0.45</td><td>-0.038</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.041</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15479">박성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.047</td><td>12</td><td>4</td><td>37.0</td><td>27</td><td>24</td><td>2</td><td>1</td><td>96.3</td><td>6.32</td><td style="">0.00</td><td></td><td>-0.37</td><td></td><td></td><td>-0.12</td><td>-0.38</td><td></td><td>-0.76</td><td>-9.08</td><td>0.24</td><td>-0.52</td><td>-0.069</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.047</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11226">임병욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.065</td><td>1</td><td>1</td><td>9.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.00</td><td style="">-0.68</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.67</td><td>-2.29</td><td>-0.04</td><td>-0.71</td><td>-0.061</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.065</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16128">고영우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.069</td><td>14</td><td>7</td><td>67.0</td><td>26</td><td>5</td><td>20</td><td>1</td><td>96.2</td><td>3.36</td><td style="">-1.55</td><td></td><td>0.09</td><td>0.04</td><td></td><td></td><td></td><td></td><td>-1.41</td><td>-2.16</td><td>0.66</td><td>-0.75</td><td>-0.129</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.069</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15652">도슨</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.072</td><td>63</td><td>57</td><td>495.0</td><td>134</td><td>132</td><td>0</td><td>2</td><td>98.5</td><td>2.40</td><td style="">2.31</td><td>-0.02</td><td>-0.44</td><td></td><td></td><td></td><td></td><td></td><td>1.84</td><td>2.79</td><td>-2.63</td><td>-0.79</td><td>0.168</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.072</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10035">이용규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.087</td><td>21</td><td>18</td><td>159.2</td><td>44</td><td>44</td><td>0</td><td>0</td><td>100.0</td><td>2.48</td><td style="">-0.36</td><td>0.07</td><td>0.18</td><td></td><td></td><td></td><td></td><td></td><td>-0.11</td><td>-0.26</td><td>-0.85</td><td>-0.96</td><td>-0.010</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.087</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14211">박준형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.094</td><td>4</td><td>2</td><td>12.1</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>5.11</td><td style="">0.00</td><td></td><td>0.04</td><td></td><td></td><td>-0.24</td><td>-1.36</td><td></td><td>-1.15</td><td>-41.35</td><td>0.12</td><td>-1.03</td><td>-0.105</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.094</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15652">도슨</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.110</td><td>25</td><td>22</td><td>185.2</td><td>58</td><td>58</td><td>0</td><td>0</td><td>100.0</td><td>2.81</td><td style="">-1.11</td><td>-0.48</td><td>0.39</td><td></td><td></td><td></td><td></td><td></td><td>-1.20</td><td>-1.82</td><td>0.00</td><td>-1.20</td><td>-0.110</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.110</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14577">김병휘</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.112</td><td>5</td><td>2</td><td>18.0</td><td>9</td><td>3</td><td>6</td><td>0</td><td>100.0</td><td>4.50</td><td style="">-1.06</td><td></td><td>0.11</td><td>-0.34</td><td></td><td></td><td></td><td></td><td>-1.29</td><td>-6.64</td><td>0.07</td><td>-1.22</td><td>-0.118</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.112</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11225">임지열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.112</td><td>8</td><td>5</td><td>39.0</td><td>9</td><td>9</td><td>0</td><td>0</td><td>100.0</td><td>2.08</td><td style="">-1.45</td><td>0.34</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-1.06</td><td>-6.96</td><td>-0.16</td><td>-1.22</td><td>-0.097</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.112</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10035">이용규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.118</td><td>26</td><td>20</td><td>171.1</td><td>49</td><td>49</td><td>0</td><td>0</td><td>100.0</td><td>2.57</td><td style="">-1.65</td><td>0.00</td><td>0.36</td><td></td><td></td><td></td><td></td><td></td><td>-1.29</td><td>-3.10</td><td>0.00</td><td>-1.29</td><td>-0.118</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.118</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15473">김동헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.123</td><td>2</td><td>2</td><td>14.0</td><td>11</td><td>10</td><td>0</td><td>1</td><td>90.9</td><td>6.43</td><td style="">0.00</td><td></td><td>-0.45</td><td></td><td></td><td>-0.73</td><td>-0.47</td><td></td><td>-1.51</td><td>-109.07</td><td>0.17</td><td>-1.35</td><td>-0.138</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.123</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15132">박수종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.134</td><td>8</td><td>0</td><td>14.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>1.93</td><td style="">-1.57</td><td>0.09</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-1.44</td><td>-2.59</td><td>-0.02</td><td>-1.46</td><td>-0.132</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.134</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14591">이주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.135</td><td>1</td><td>1</td><td>4.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-1.42</td><td>-0.05</td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-1.46</td><td>-1.82</td><td>-0.02</td><td>-1.48</td><td>-0.133</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.135</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11226">임병욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.172</td><td>20</td><td>13</td><td>107.0</td><td>26</td><td>25</td><td>0</td><td>1</td><td>96.2</td><td>2.10</td><td style="">-1.30</td><td>-0.31</td><td>-0.28</td><td></td><td></td><td></td><td></td><td></td><td>-1.88</td><td>-6.46</td><td>0.00</td><td>-1.88</td><td>-0.172</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.172</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13093">예진원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.176</td><td>5</td><td>1</td><td>16.2</td><td>9</td><td>9</td><td>0</td><td>0</td><td>100.0</td><td>4.86</td><td style="">-1.52</td><td>-0.39</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>-1.85</td><td>-12.14</td><td>-0.07</td><td>-1.92</td><td>-0.169</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.176</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14784">장재영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.178</td><td>17</td><td>16</td><td>126.1</td><td>25</td><td>24</td><td>1</td><td>0</td><td>100.0</td><td>1.78</td><td style="">-1.73</td><td>-0.48</td><td>0.26</td><td></td><td></td><td></td><td></td><td></td><td>-1.95</td><td>-7.39</td><td>0.00</td><td>-1.95</td><td>-0.178</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.178</td></tr><tr><td style="text-align:center;">52</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13093">예진원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.188</td><td>11</td><td>1</td><td>23.0</td><td>6</td><td>6</td><td>0</td><td>0</td><td>100.0</td><td>2.35</td><td style="">-1.28</td><td>-0.82</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>-2.05</td><td>-13.45</td><td>0.00</td><td>-2.05</td><td>-0.188</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.188</td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11225">임지열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.207</td><td>9</td><td>9</td><td>66.0</td><td>10</td><td>10</td><td>0</td><td>0</td><td>100.0</td><td>1.36</td><td style="">-1.85</td><td>-0.30</td><td>0.20</td><td></td><td></td><td></td><td></td><td></td><td>-1.94</td><td>-12.73</td><td>-0.32</td><td>-2.26</td><td>-0.178</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.207</td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15476">이승원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.240</td><td>18</td><td>13</td><td>96.0</td><td>48</td><td>20</td><td>25</td><td>3</td><td>93.8</td><td>4.22</td><td style="">-1.84</td><td></td><td>-0.65</td><td>-0.87</td><td></td><td></td><td></td><td></td><td>-3.36</td><td>-24.22</td><td>0.74</td><td>-2.62</td><td>-0.307</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.240</td></tr><tr><td style="text-align:center;">55</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10180">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.254</td><td>12</td><td>12</td><td>87.0</td><td>91</td><td>85</td><td>4</td><td>2</td><td>97.8</td><td>9.21</td><td style="">-1.45</td><td></td><td>-0.57</td><td></td><td></td><td></td><td></td><td></td><td>-2.02</td><td>-7.46</td><td>-0.76</td><td>-2.78</td><td>-0.185</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.254</td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16136">원성준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.285</td><td>10</td><td>9</td><td>65.0</td><td>20</td><td>19</td><td>0</td><td>1</td><td>95.0</td><td>2.63</td><td style="">-2.18</td><td>-0.57</td><td>-0.37</td><td></td><td></td><td></td><td></td><td></td><td>-3.11</td><td>-8.79</td><td>0.00</td><td>-3.11</td><td>-0.285</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.285</td></tr><tr><td style="text-align:center;">57</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11376">송성문</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.296</td><td>32</td><td>15</td><td>148.0</td><td>138</td><td>130</td><td>7</td><td>1</td><td>99.3</td><td>8.33</td><td style="">-2.05</td><td></td><td>0.23</td><td></td><td>0.06</td><td></td><td></td><td></td><td>-1.76</td><td>-1.78</td><td>-1.48</td><td>-3.24</td><td>-0.161</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.296</td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16124">이재상</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.344</td><td>35</td><td>28</td><td>221.0</td><td>98</td><td>44</td><td>50</td><td>4</td><td>95.9</td><td>3.83</td><td style="">-3.25</td><td></td><td>-0.05</td><td>-2.19</td><td></td><td></td><td></td><td></td><td>-5.49</td><td>-21.96</td><td>1.72</td><td>-3.77</td><td>-0.501</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.344</td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10182">최주환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.499</td><td>122</td><td>116</td><td>1027.2</td><td>972</td><td>906</td><td>60</td><td>6</td><td>99.4</td><td>8.46</td><td style="">2.39</td><td></td><td>2.07</td><td></td><td>0.29</td><td></td><td></td><td></td><td>4.75</td><td>5.26</td><td>-10.22</td><td>-5.47</td><td>0.434</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.499</td></tr><tr><td style="text-align:center;">60</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16128">고영우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.524</td><td>65</td><td>52</td><td>442.2</td><td>128</td><td>37</td><td>81</td><td>10</td><td>92.2</td><td>2.40</td><td style="">-3.34</td><td></td><td>-1.98</td><td>-0.37</td><td>-0.05</td><td></td><td></td><td></td><td>-5.74</td><td>-8.79</td><td>0.00</td><td>-5.74</td><td>-0.524</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.524</td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16123">김윤하</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>18</td><td>12</td><td>79.0</td><td>12</td><td>2</td><td>9</td><td>1</td><td>91.7</td><td>1.25</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13092">김선기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>41</td><td>6</td><td>76.1</td><td>11</td><td>0</td><td>11</td><td>0</td><td>100.0</td><td>1.30</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15476">이승원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.04</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10437">문성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>39</td><td>0</td><td>38.1</td><td>3</td><td>2</td><td>1</td><td>0</td><td>100.0</td><td>0.70</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14214">김주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.04</td><td></td><td></td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12860">오석주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>16</td><td>0</td><td>17.0</td><td>2</td><td>0</td><td>2</td><td>0</td><td>100.0</td><td>1.06</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td></td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14131">윤정현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>3.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14577">김병휘</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>2.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>4.50</td><td style="">0.43</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.45</td><td>2.29</td><td></td><td></td><td>0.041</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14681">김동욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>37</td><td>0</td><td>36.0</td><td>5</td><td>2</td><td>3</td><td>0</td><td>100.0</td><td>1.25</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11244">김태진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.01</td><td></td><td></td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12854">양지율</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>20</td><td>0</td><td>18.2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16133">박범준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>5</td><td>0</td><td>5.1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14695">신준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>1.15</td><td></td><td></td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16127">김연주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>33</td><td>0</td><td>31.1</td><td>6</td><td>2</td><td>4</td><td>0</td><td>100.0</td><td>1.72</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11161">원종현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>4</td><td>0</td><td>3.2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12858">김재웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>26</td><td>0</td><td>23.2</td><td>5</td><td>0</td><td>5</td><td>0</td><td>100.0</td><td>1.90</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15067">주승우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>55</td><td>0</td><td>51.2</td><td>13</td><td>3</td><td>10</td><td>0</td><td>100.0</td><td>2.26</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>""")

In [ ]:
len(team_tables)

10

In [ ]:
fielding = pd.DataFrame()
for i in range(len(team_tables)):
    name = team_names[i]
    team = team_tables[i]
    print(name)
    df, pids = get_team_stats_from_markup(StringIO(str(team)))
    df['팀'] = name
    df['pid'] = pids[2:]
    print(df.shape)
    print(len(pids))
    fielding = pd.concat([fielding, df])
    display(fielding.tail())

한화 이글스
(63, 29)
65

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team      Sort▼   G GS    IP  TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G GS    IP  TC PO Ass  ...      Blk RAA
58   56  황영묵  24 3B        NaN   3  0   3.0   1  0   1  ...          NaN
59   56  이명기  24 CF        NaN   1  0   1.0   0  0   0  ...          NaN
60   56  박상원   24 P        NaN  64  0  66.2   6  2   3  ...          NaN
61   56  주현상   24 P        NaN  62  0  71.1  12  2  10  ...          NaN
62   56  이도윤  24 3B        NaN   2  0   2.0   0  0   0  ...          NaN

                        POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼       팀    pid
   Frm RAA 종합 RAA  /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
58     NaN   0.64  0.74    NaN        NaN    0.058         NaN  한화 이글스  16110
59     NaN   0.00  0.07    NaN        NaN    0.000         NaN  한화 이글스  10119
60     NaN   0.00  0.00    NaN        NaN    0.000         NaN  한화 이글스  12871
61     NaN   0.00  0.00    NaN        NaN    0.000         NaN  한화 이글스  11415
62     NaN  -0.54 -0.58    NaN        NaN   -0.050         NaN  한화 이글스  11414

[5 rows x 29 columns]

LG 트윈스

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(71, 29)
73

   Rank Name   Team      Sort▼   G GS    IP  TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G GS    IP  TC PO Ass  ...      Blk RAA
66   54  김진성   24 P        NaN  70  0  70.1  10  4   5  ...          NaN
67   54  임준형   24 P        NaN  17  1  13.2   2  1   1  ...          NaN
68   54  김수인  24 3B        NaN   1  0   2.0   0  0   0  ...          NaN
69   54  전준호   24 C        NaN   3  0   5.0   5  4   1  ...        -0.27
70   54  김영준   24 P        NaN  14  0  15.1   3  1   2  ...          NaN

                         POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼       팀    pid
   Frm RAA 종합 RAA   /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
66     NaN   0.00   0.00    NaN        NaN    0.000         NaN  LG 트윈스  11166
67     NaN   0.00   0.00    NaN        NaN    0.000         NaN  LG 트윈스  14142
68     NaN  -0.32 -11.65    NaN        NaN   -0.030         NaN  LG 트윈스  14675
69     NaN   0.16   7.49    NaN        NaN    0.014         NaN  LG 트윈스  12864
70     NaN   0.00   0.00    NaN        NaN    0.000         NaN  LG 트윈스  13102

[5 rows x 29 columns]

롯데 자이언츠

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(75, 29)
77

   Rank Name   Team      Sort▼   G GS    IP  TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G GS    IP  TC PO Ass  ...      Blk RAA
70   63  김강현   24 P        NaN  24  0  25.1   8  3   5  ...          NaN
71   63  김동혁  24 LF        NaN   2  0   3.0   1  1   0  ...          NaN
72   63  김원중   24 P        NaN  54  0  63.1  10  3   6  ...          NaN
73   63  추재현  24 LF        NaN   2  0   3.0   0  0   0  ...          NaN
74   63  이인한  24 CF        NaN   1  0   2.0   0  0   0  ...          NaN

                        POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼        팀    pid
   Frm RAA 종합 RAA  /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
70     NaN   0.00  0.00    NaN        NaN    0.000         NaN  롯데 자이언츠  12699
71     NaN  -0.07 -0.27    NaN        NaN   -0.007         NaN  롯데 자이언츠  15645
72     NaN   0.00  0.00    NaN        NaN    0.000         NaN  롯데 자이언츠  10825
73     NaN   0.00  0.05    NaN        NaN    0.000         NaN  롯데 자이언츠  13094
74     NaN   0.00  0.12    NaN        NaN    0.000         NaN  롯데 자이언츠  14690

[5 rows x 29 columns]

KIA 타이거즈
(64, 29)
66

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team      Sort▼   G  GS     IP  TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G  GS     IP  TC PO Ass  ...      Blk RAA
59   50  황동하   24 P        NaN  25  21  103.1  18  5  13  ...          NaN
60   50   박민  24 3B        NaN   3   0    4.0   0  0   0  ...          NaN
61   50  곽도규   24 P        NaN  67   0   55.2  13  3   7  ...          NaN
62   50  최지민   24 P        NaN  54   0   46.0   7  2   4  ...          NaN
63   50  정해영   24 P        NaN  53   0   50.2   8  3   5  ...          NaN

                        POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼         팀  \
   Frm RAA 종합 RAA  /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
59     NaN   0.00  0.00    NaN        NaN    0.000         NaN  KIA 타이거즈
60     NaN   0.03  0.25    NaN        NaN    0.003         NaN  KIA 타이거즈
61     NaN   0.00  0.00    NaN        NaN    0.000         NaN  KIA 타이거즈
62     NaN   0.00  0.00    NaN        NaN    0.000         NaN  KIA 타이거즈
63     NaN   0.00  0.00    NaN        NaN    0.000         NaN  KIA 타이거즈

      pid

59  15063
60  14611
61  15435
62  15057
63  14608

[5 rows x 29 columns]

KT 위즈
(79, 29)
81

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team      Sort▼   G GS    IP  TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G GS    IP  TC PO Ass  ...      Blk RAA
74   65  박세진   24 P        NaN   6  0   5.1   0  0   0  ...          NaN
75   65  성재헌   24 P        NaN  29  1  32.0  10  1   8  ...          NaN
76   65  우규민   24 P        NaN  44  0  43.1   7  1   5  ...          NaN
77   65  손동현   24 P        NaN  41  0  47.1   8  3   3  ...          NaN
78   65  황재균  24 1B        NaN   1  0   1.0   2  2   0  ...          NaN

                       POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼      팀    pid
   Frm RAA 종합 RAA /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
74     NaN   0.00  0.0    NaN        NaN    0.000         NaN  KT 위즈  12572
75     NaN   0.00  0.0    NaN        NaN    0.000         NaN  KT 위즈  14667
76     NaN   0.00  0.0    NaN        NaN    0.000         NaN  KT 위즈  10523
77     NaN   0.00  0.0    NaN        NaN    0.000         NaN  KT 위즈  14108
78     NaN   0.86  0.9    NaN        NaN    0.078         NaN  KT 위즈  10407

[5 rows x 29 columns]

삼성 라이온즈

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(83, 29)
85

   Rank Name   Team      Sort▼   G GS    IP TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G GS    IP TC PO Ass  ...      Blk RAA
78   71  오승환   24 P        NaN  58  0  55.0  6  1   5  ...          NaN
79   71  김대우   24 P        NaN  30  1  34.1  5  0   4  ...          NaN
80   71  강한울  24 1B        NaN   1  0   1.0  1  1   0  ...          NaN
81   71  육선엽   24 P        NaN  11  1  17.0  2  2   0  ...          NaN
82   71  강한울  24 SS        NaN   3  0   3.0  1  1   0  ...          NaN

                        POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼        팀    pid
   Frm RAA 종합 RAA  /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
78     NaN   0.00  0.00    NaN        NaN    0.000         NaN  삼성 라이온즈  10367
79     NaN   0.00  0.00    NaN        NaN    0.000         NaN  삼성 라이온즈  10685
80     NaN   0.00  0.04    NaN        NaN    0.000         NaN  삼성 라이온즈  11255
81     NaN   0.00  0.00    NaN        NaN    0.000         NaN  삼성 라이온즈  15864
82     NaN  -0.25 -2.02    NaN        NaN   -0.023         NaN  삼성 라이온즈  11255

[5 rows x 29 columns]

SSG 랜더스
(59, 29)
61

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team      Sort▼   G GS    IP TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G GS    IP TC PO Ass  ...      Blk RAA
54   51  최민창  24 CF        NaN   1  0   1.0  1  1   0  ...          NaN
55   51  최상민  24 LF        NaN   4  0   5.0  1  1   0  ...          NaN
56   51  고명준  24 3B        NaN   1  0   1.0  0  0   0  ...          NaN
57   51  한두솔   24 P        NaN  64  0  59.1  8  2   5  ...          NaN
58   51  박민호   24 P        NaN  19  0  22.2  1  0   1  ...          NaN

                        POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼        팀    pid
   Frm RAA 종합 RAA  /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
54     NaN   0.18  3.79    NaN        NaN    0.017         NaN  SSG 랜더스  11351
55     NaN   0.58  1.95    NaN        NaN    0.053         NaN  SSG 랜더스  13195
56     NaN  -0.46 -0.62    NaN        NaN   -0.042         NaN  SSG 랜더스  14807
57     NaN   0.00  0.00    NaN        NaN    0.000         NaN  SSG 랜더스  13228
58     NaN   0.00  0.00    NaN        NaN    0.000         NaN  SSG 랜더스  11236

[5 rows x 29 columns]

NC 다이노스
(58, 29)
60

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team      Sort▼   G GS    IP  TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G GS    IP  TC PO Ass  ...      Blk RAA
53   50  김수윤  24 2B        NaN   1  0   1.0   1  0   0  ...          NaN
54   50  송명기   24 P        NaN  32  0  38.1   1  0   1  ...          NaN
55   50  도태훈  24 SS        NaN   1  0   1.0   0  0   0  ...          NaN
56   50  김재열   24 P        NaN  68  0  68.2  10  3   5  ...          NaN
57   50  김영규   24 P        NaN  42  0  45.2  11  2   8  ...          NaN

                         POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼        팀  \
   Frm RAA 종합 RAA   /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
53     NaN  -1.34 -21.48    NaN        NaN   -0.123         NaN  NC 다이노스
54     NaN   0.00   0.00    NaN        NaN    0.000         NaN  NC 다이노스
55     NaN  -0.03  -0.05    NaN        NaN   -0.003         NaN  NC 다이노스
56     NaN   0.00   0.00    NaN        NaN    0.000         NaN  NC 다이노스
57     NaN   0.00    NaN    NaN        NaN    0.000         NaN  NC 다이노스

      pid

53  12903
54  14155
55  12560
56  14747
57  13088

[5 rows x 29 columns]

두산 베어스

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(76, 29)
78

   Rank Name   Team      Sort▼   G GS    IP  TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G GS    IP  TC PO Ass  ...      Blk RAA
71   59  박계범  24 1B        NaN   1  0   1.0   0  0   0  ...          NaN
72   59  김명신   24 P        NaN  32  0  32.2   5  2   3  ...          NaN
73   59  김민혁  24 1B        NaN   1  0   1.0   0  0   0  ...          NaN
74   59  최지강   24 P        NaN  52  0  50.0  12  2   9  ...          NaN
75   59  김택연   24 P        NaN  60  0  65.0   7  1   6  ...          NaN

                        POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼       팀    pid
   Frm RAA 종합 RAA  /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
71     NaN    0.0  0.03    NaN        NaN      0.0         NaN  두산 베어스  11198
72     NaN    0.0  0.00    NaN        NaN      0.0         NaN  두산 베어스  12847
73     NaN    0.0  0.12    NaN        NaN      0.0         NaN  두산 베어스  12970
74     NaN    0.0  0.00    NaN        NaN      0.0         NaN  두산 베어스  15127
75     NaN    0.0  0.00    NaN        NaN      0.0         NaN  두산 베어스  16067

[5 rows x 29 columns]

키움 히어로즈

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(77, 29)
79

   Rank Name   Team      Sort▼   G GS    IP  TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G GS    IP  TC PO Ass  ...      Blk RAA
72   61  신준우  24 SS        NaN   1  0   1.0   0  0   0  ...          NaN
73   61  김연주   24 P        NaN  33  0  31.1   6  2   4  ...          NaN
74   61  원종현   24 P        NaN   4  0   3.2   0  0   0  ...          NaN
75   61  김재웅   24 P        NaN  26  0  23.2   5  0   5  ...          NaN
76   61  주승우   24 P        NaN  55  0  51.2  13  3  10  ...          NaN

                        POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼        팀    pid
   Frm RAA 종합 RAA  /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
72     NaN   0.01  1.15    NaN        NaN    0.001         NaN  키움 히어로즈  14695
73     NaN   0.00  0.00    NaN        NaN    0.000         NaN  키움 히어로즈  16127
74     NaN   0.00  0.00    NaN        NaN    0.000         NaN  키움 히어로즈  11161
75     NaN   0.00  0.00    NaN        NaN    0.000         NaN  키움 히어로즈  12858
76     NaN   0.00  0.00    NaN        NaN    0.000         NaN  키움 히어로즈  15067

[5 rows x 29 columns]

In [ ]:
fielding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 705 entries, 0 to 76
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   (Rank, Rank)                705 non-null    int64
 1   (Name, Name)                705 non-null    object
 2   (Team, Team)                705 non-null    object
 3   (Sort▼, WAAwithPOS)         570 non-null    float64
 4   (G, G)                      705 non-null    int64
 5   (GS, GS)                    705 non-null    int64
 6   (IP, IP)                    705 non-null    float64
 7   (TC, TC)                    705 non-null    int64
 8   (PO, PO)                    705 non-null    int64
 9   (Ass, Ass)                  705 non-null    int64
 10  (E, E)                      705 non-null    int64
 11  (F%, F%)                    705 non-null    float64
 12  (RF9, RF9)                  704 non-null    float64
 13  (수비 관련 득점 기여도, Range RAA)   594 non-null    float64
 14  (수비 관련 득점 기여도, Arm RAA)     236 non-null    float64
 15  (수비 관련 득점 기여도, Err RAA)     617 non-null    float64
 16  (수비 관련 득점 기여도, DP RAA)      150 non-null    float64
 17  (수비 관련 득점 기여도, Bt RAA)      89 non-null     float64
 18  (수비 관련 득점 기여도, CS RAA)      42 non-null     float64
 19  (수비 관련 득점 기여도, Blk RAA)     51 non-null     float64
 20  (수비 관련 득점 기여도, Frm RAA)     0 non-null      float64
 21  (수비 관련 득점 기여도, 종합 RAA)      705 non-null    float64
 22  (수비 관련 득점 기여도, /144)        703 non-null    float64
 23  (POSAdj, POSAdj)            570 non-null    float64
 24  (RAAwithPOS, RAAwithPOS)    570 non-null    float64
 25  (WAAwoPOS, WAAwoPOS)        705 non-null    float64
 26  (WAAwithPOS▼, WAAwithPOS▼)  570 non-null    float64
 27  (팀, )                       705 non-null    object
 28  (pid, )                     705 non-null    object
dtypes: float64(18), int64(7), object(4)
memory usage: 165.2+ KB

In [ ]:
fielding.isna().sum()

Rank          Rank             0
Name          Name             0
Team          Team             0
Sort▼         WAAwithPOS     135
G             G                0
GS            GS               0
IP            IP               0
TC            TC               0
PO            PO               0
Ass           Ass              0
E             E                0
F%            F%               0
RF9           RF9              1
수비 관련 득점 기여도  Range RAA      111
              Arm RAA        469
              Err RAA         88
              DP RAA         555
              Bt RAA         616
              CS RAA         663
              Blk RAA        654
              Frm RAA        705
              종합 RAA           0
              /144             2
POSAdj        POSAdj         135
RAAwithPOS    RAAwithPOS     135
WAAwoPOS      WAAwoPOS         0
WAAwithPOS▼   WAAwithPOS▼    135
팀                              0
pid                            0
dtype: int64

In [ ]:
fielding['팀'].value_counts()

팀
삼성 라이온즈     83
KT 위즈       79
키움 히어로즈     77
두산 베어스      76
롯데 자이언츠     75
LG 트윈스      71
KIA 타이거즈    64
한화 이글스      63
SSG 랜더스     59
NC 다이노스     58
Name: count, dtype: int64

In [ ]:
fielding.to_csv('2024_수비_statiz.csv', index=False)

In [ ]:
team_tables = []

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14125">노시환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.41</td><td>136</td><td>2.50</td><td>-0.08</td><td>601</td><td>597</td><td>526</td><td>88</td><td>143</td><td>20</td><td>2</td><td>24</td><td>239</td><td>89</td><td>6</td><td>0</td><td>60</td><td>11</td><td>9</td><td>129</td><td>10</td><td>0</td><td>4</td><td style="">0.272</td><td>0.356</td><td>0.454</td><td>0.810</td><td>0.145</td><td>106.5</td><td style="background-color:#F3F3F3; font-weight:bold;">2.41</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16121">페라자</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.13</td><td>122</td><td>2.27</td><td>-0.14</td><td>522</td><td>518</td><td>455</td><td>75</td><td>125</td><td>24</td><td>0</td><td>24</td><td>221</td><td>70</td><td>7</td><td>5</td><td>63</td><td>2</td><td>5</td><td>129</td><td>6</td><td>0</td><td>2</td><td style="">0.275</td><td>0.364</td><td>0.486</td><td>0.850</td><td>0.158</td><td>116.7</td><td style="background-color:#F3F3F3; font-weight:bold;">2.13</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10170">최재훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.82</td><td>116</td><td>1.69</td><td>0.13</td><td>348</td><td>340</td><td>280</td><td>34</td><td>72</td><td>10</td><td>0</td><td>4</td><td>94</td><td>37</td><td>0</td><td>0</td><td>33</td><td>21</td><td>0</td><td>58</td><td>10</td><td>8</td><td>6</td><td style="">0.257</td><td>0.371</td><td>0.336</td><td>0.707</td><td>0.131</td><td>96.6</td><td style="background-color:#F3F3F3; font-weight:bold;">1.82</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16110">황영묵</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.39</td><td>123</td><td>1.38</td><td>0.01</td><td>389</td><td>386</td><td>349</td><td>52</td><td>105</td><td>8</td><td>4</td><td>3</td><td>130</td><td>35</td><td>4</td><td>7</td><td>31</td><td>5</td><td>0</td><td>56</td><td>6</td><td>3</td><td>1</td><td style="">0.301</td><td>0.365</td><td>0.372</td><td>0.737</td><td>0.129</td><td>95.1</td><td style="background-color:#F3F3F3; font-weight:bold;">1.39</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10014">안치홍</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.33</td><td>128</td><td>1.65</td><td>-0.31</td><td>533</td><td>531</td><td>473</td><td>64</td><td>142</td><td>21</td><td>0</td><td>13</td><td>202</td><td>66</td><td>3</td><td>2</td><td>49</td><td>6</td><td>1</td><td>70</td><td>10</td><td>1</td><td>4</td><td style="">0.300</td><td>0.370</td><td>0.427</td><td>0.797</td><td>0.146</td><td>107.9</td><td style="background-color:#F3F3F3; font-weight:bold;">1.33</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14707">최인호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.18</td><td>82</td><td>0.86</td><td>0.32</td><td>244</td><td>240</td><td>210</td><td>37</td><td>60</td><td>13</td><td>2</td><td>2</td><td>83</td><td>22</td><td>3</td><td>0</td><td>25</td><td>3</td><td>0</td><td>31</td><td>3</td><td>4</td><td>2</td><td style="">0.286</td><td>0.367</td><td>0.395</td><td>0.762</td><td>0.139</td><td>102.2</td><td style="background-color:#F3F3F3; font-weight:bold;">1.18</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11215">채은성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.14</td><td>124</td><td>1.32</td><td>-0.18</td><td>498</td><td>498</td><td>436</td><td>61</td><td>118</td><td>24</td><td>0</td><td>20</td><td>202</td><td>83</td><td>1</td><td>1</td><td>49</td><td>8</td><td>1</td><td>83</td><td>12</td><td>0</td><td>5</td><td style="">0.271</td><td>0.351</td><td>0.463</td><td>0.814</td><td>0.147</td><td>108.9</td><td style="background-color:#F3F3F3; font-weight:bold;">1.14</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12585">김태연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.61</td><td>126</td><td>1.43</td><td>-0.82</td><td>472</td><td>466</td><td>413</td><td>59</td><td>120</td><td>24</td><td>0</td><td>12</td><td>180</td><td>61</td><td>5</td><td>2</td><td>45</td><td>4</td><td>0</td><td>89</td><td>9</td><td>6</td><td>4</td><td style="">0.291</td><td>0.363</td><td>0.436</td><td>0.799</td><td>0.145</td><td>106.5</td><td style="background-color:#F3F3F3; font-weight:bold;">0.61</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11414">이도윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.59</td><td>134</td><td>0.74</td><td>-0.14</td><td>374</td><td>368</td><td>336</td><td>49</td><td>93</td><td>10</td><td>3</td><td>1</td><td>112</td><td>46</td><td>6</td><td>4</td><td>26</td><td>3</td><td>0</td><td>56</td><td>5</td><td>6</td><td>3</td><td style="">0.277</td><td>0.332</td><td>0.333</td><td>0.665</td><td>0.098</td><td>72.4</td><td style="background-color:#F3F3F3; font-weight:bold;">0.59</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12583">장진혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.58</td><td>99</td><td>0.57</td><td>0.00</td><td>327</td><td>322</td><td>289</td><td>56</td><td>76</td><td>16</td><td>0</td><td>9</td><td>119</td><td>44</td><td>14</td><td>6</td><td>29</td><td>3</td><td>0</td><td>72</td><td>6</td><td>5</td><td>1</td><td style="">0.263</td><td>0.335</td><td>0.412</td><td>0.747</td><td>0.125</td><td>91.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.58</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15422">문현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.50</td><td>103</td><td>0.63</td><td>-0.14</td><td>289</td><td>287</td><td>260</td><td>29</td><td>72</td><td>16</td><td>2</td><td>5</td><td>107</td><td>47</td><td>3</td><td>5</td><td>24</td><td>2</td><td>1</td><td>53</td><td>9</td><td>1</td><td>2</td><td style="">0.277</td><td>0.340</td><td>0.412</td><td>0.752</td><td>0.126</td><td>93.2</td><td style="background-color:#F3F3F3; font-weight:bold;">0.50</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12587">박상언</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.47</td><td>27</td><td>0.48</td><td>-0.02</td><td>52</td><td>52</td><td>42</td><td>4</td><td>12</td><td>3</td><td>0</td><td>0</td><td>15</td><td>4</td><td>1</td><td>0</td><td>9</td><td>1</td><td>0</td><td>12</td><td>0</td><td>0</td><td>0</td><td style="">0.286</td><td>0.423</td><td>0.357</td><td>0.780</td><td>0.166</td><td>119.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.47</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13676">권광민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.40</td><td>19</td><td>0.31</td><td>0.09</td><td>51</td><td>51</td><td>48</td><td>10</td><td>13</td><td>3</td><td>0</td><td>4</td><td>28</td><td>9</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>17</td><td>0</td><td>0</td><td>0</td><td style="">0.271</td><td>0.314</td><td>0.583</td><td>0.897</td><td>0.160</td><td>119.1</td><td style="background-color:#F3F3F3; font-weight:bold;">0.40</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10913">하주석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.25</td><td>64</td><td>0.70</td><td>-0.45</td><td>151</td><td>149</td><td>137</td><td>16</td><td>40</td><td>9</td><td>1</td><td>1</td><td>54</td><td>11</td><td>1</td><td>2</td><td>10</td><td>2</td><td>0</td><td>33</td><td>1</td><td>2</td><td>0</td><td style="">0.292</td><td>0.349</td><td>0.394</td><td>0.743</td><td>0.127</td><td>94.7</td><td style="background-color:#F3F3F3; font-weight:bold;">0.25</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13137">정은원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.06</td><td>27</td><td>-0.04</td><td>0.09</td><td>78</td><td>77</td><td>64</td><td>10</td><td>11</td><td>3</td><td>1</td><td>1</td><td>19</td><td>6</td><td>2</td><td>0</td><td>13</td><td>0</td><td>0</td><td>16</td><td>0</td><td>1</td><td>0</td><td style="">0.172</td><td>0.312</td><td>0.297</td><td>0.609</td><td>0.088</td><td>64.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.06</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10108">김강민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.02</td><td>41</td><td>-0.17</td><td>0.19</td><td>87</td><td>87</td><td>76</td><td>5</td><td>17</td><td>0</td><td>0</td><td>1</td><td>20</td><td>7</td><td>0</td><td>0</td><td>8</td><td>3</td><td>0</td><td>21</td><td>1</td><td>0</td><td>0</td><td style="">0.224</td><td>0.322</td><td>0.263</td><td>0.585</td><td>0.080</td><td>58.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.02</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14126">유로결</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.01</td><td>23</td><td>-0.23</td><td>0.24</td><td>39</td><td>39</td><td>36</td><td>6</td><td>8</td><td>1</td><td>0</td><td>0</td><td>9</td><td>4</td><td>0</td><td>1</td><td>3</td><td>0</td><td>0</td><td>11</td><td>4</td><td>0</td><td>0</td><td style="">0.222</td><td>0.282</td><td>0.250</td><td>0.532</td><td>0.047</td><td>34.4</td><td style="background-color:#F3F3F3; font-weight:bold;">0.01</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10610">장민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12871">박상원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11415">주현상</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15421">김서현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15633">한경빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>1</td><td>-0.02</td><td>0.01</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-151.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14811">장규현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.14</td><td>9</td><td>-0.10</td><td>-0.04</td><td>7</td><td>7</td><td>6</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.143</td><td>0.000</td><td>0.143</td><td>-0.086</td><td>-63.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.14</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12539">이진영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.15</td><td>42</td><td>-0.30</td><td>0.15</td><td>103</td><td>103</td><td>93</td><td>20</td><td>19</td><td>6</td><td>0</td><td>1</td><td>28</td><td>13</td><td>0</td><td>1</td><td>8</td><td>2</td><td>0</td><td>27</td><td>3</td><td>0</td><td>0</td><td style="">0.204</td><td>0.282</td><td>0.301</td><td>0.583</td><td>0.067</td><td>50.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.15</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15139">이상혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.21</td><td>43</td><td>-0.09</td><td>-0.12</td><td>15</td><td>15</td><td>13</td><td>13</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>5</td><td>2</td><td>2</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td style="">0.154</td><td>0.267</td><td>0.154</td><td>0.421</td><td>0.019</td><td>13.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.21</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13138">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.21</td><td>87</td><td>-0.24</td><td>0.03</td><td>154</td><td>152</td><td>133</td><td>26</td><td>31</td><td>4</td><td>1</td><td>0</td><td>37</td><td>13</td><td>8</td><td>2</td><td>16</td><td>2</td><td>0</td><td>32</td><td>3</td><td>2</td><td>1</td><td style="">0.233</td><td>0.322</td><td>0.278</td><td>0.600</td><td>0.082</td><td>61.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.21</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10119">이명기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.21</td><td>4</td><td>-0.21</td><td>0.00</td><td>8</td><td>7</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>1</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-132.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.21</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14706">임종찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.24</td><td>24</td><td>-0.20</td><td>-0.03</td><td>64</td><td>64</td><td>57</td><td>10</td><td>9</td><td>3</td><td>2</td><td>0</td><td>16</td><td>7</td><td>0</td><td>1</td><td>6</td><td>1</td><td>0</td><td>19</td><td>2</td><td>0</td><td>0</td><td style="">0.158</td><td>0.250</td><td>0.281</td><td>0.531</td><td>0.048</td><td>35.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.24</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10082">이재원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.29</td><td>72</td><td>-0.24</td><td>-0.05</td><td>152</td><td>150</td><td>134</td><td>10</td><td>32</td><td>4</td><td>0</td><td>1</td><td>39</td><td>16</td><td>0</td><td>0</td><td>7</td><td>4</td><td>1</td><td>21</td><td>4</td><td>2</td><td>5</td><td style="">0.239</td><td>0.287</td><td>0.291</td><td>0.578</td><td>0.059</td><td>44.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.29</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12589">김인환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.99</td><td>51</td><td>-0.58</td><td>-0.41</td><td>143</td><td>143</td><td>131</td><td>11</td><td>31</td><td>2</td><td>0</td><td>1</td><td>36</td><td>7</td><td>0</td><td>0</td><td>10</td><td>2</td><td>0</td><td>32</td><td>5</td><td>0</td><td>0</td><td style="">0.237</td><td>0.301</td><td>0.275</td><td>0.576</td><td>0.066</td><td>48.1</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.99</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15532">오스틴</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.06</td><td>140</td><td>4.90</td><td>0.17</td><td>604</td><td>600</td><td>527</td><td>99</td><td>168</td><td>32</td><td>3</td><td>32</td><td>302</td><td>132</td><td>12</td><td>8</td><td>61</td><td>3</td><td>6</td><td>82</td><td>9</td><td>0</td><td>13</td><td style="">0.319</td><td>0.384</td><td>0.573</td><td>0.957</td><td>0.192</td><td>147.8</td><td style="background-color:#F3F3F3; font-weight:bold;">5.06</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12546">홍창기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.06</td><td>139</td><td>4.48</td><td>0.59</td><td>637</td><td>635</td><td>524</td><td>96</td><td>176</td><td>18</td><td>3</td><td>5</td><td>215</td><td>73</td><td>10</td><td>11</td><td>96</td><td>12</td><td>3</td><td>93</td><td>8</td><td>1</td><td>4</td><td style="">0.336</td><td>0.447</td><td>0.410</td><td>0.857</td><td>0.185</td><td>142.3</td><td style="background-color:#F3F3F3; font-weight:bold;">5.06</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10387">박동원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.40</td><td>130</td><td>3.43</td><td>0.96</td><td>498</td><td>495</td><td>434</td><td>58</td><td>118</td><td>22</td><td>0</td><td>20</td><td>200</td><td>80</td><td>1</td><td>0</td><td>55</td><td>0</td><td>2</td><td>112</td><td>14</td><td>2</td><td>7</td><td style="">0.272</td><td>0.349</td><td>0.461</td><td>0.810</td><td>0.144</td><td>111.0</td><td style="background-color:#F3F3F3; font-weight:bold;">4.40</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14137">문보경</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.32</td><td>144</td><td>4.47</td><td>-0.15</td><td>602</td><td>597</td><td>519</td><td>80</td><td>156</td><td>35</td><td>3</td><td>22</td><td>263</td><td>101</td><td>7</td><td>6</td><td>65</td><td>2</td><td>3</td><td>112</td><td>14</td><td>3</td><td>13</td><td style="">0.301</td><td>0.372</td><td>0.507</td><td>0.879</td><td>0.169</td><td>130.4</td><td style="background-color:#F3F3F3; font-weight:bold;">4.32</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10475">오지환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.00</td><td>108</td><td>2.67</td><td>0.33</td><td>428</td><td>426</td><td>370</td><td>67</td><td>94</td><td>24</td><td>2</td><td>10</td><td>152</td><td>59</td><td>17</td><td>4</td><td>51</td><td>4</td><td>0</td><td>106</td><td>8</td><td>2</td><td>1</td><td style="">0.254</td><td>0.350</td><td>0.411</td><td>0.761</td><td>0.136</td><td>104.5</td><td style="background-color:#F3F3F3; font-weight:bold;">3.00</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13056">신민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.64</td><td>128</td><td>3.11</td><td>-0.47</td><td>474</td><td>459</td><td>387</td><td>78</td><td>115</td><td>11</td><td>6</td><td>0</td><td>138</td><td>40</td><td>32</td><td>11</td><td>64</td><td>5</td><td>1</td><td>47</td><td>7</td><td>15</td><td>3</td><td style="">0.297</td><td>0.401</td><td>0.357</td><td>0.758</td><td>0.148</td><td>114.2</td><td style="background-color:#F3F3F3; font-weight:bold;">2.64</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13112">문성주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.41</td><td>96</td><td>1.85</td><td>0.56</td><td>361</td><td>360</td><td>305</td><td>47</td><td>96</td><td>16</td><td>2</td><td>0</td><td>116</td><td>48</td><td>13</td><td>7</td><td>49</td><td>3</td><td>0</td><td>38</td><td>4</td><td>1</td><td>3</td><td style="">0.315</td><td>0.411</td><td>0.380</td><td>0.791</td><td>0.158</td><td>120.8</td><td style="background-color:#F3F3F3; font-weight:bold;">2.41</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11190">박해민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.03</td><td>144</td><td>1.44</td><td>0.59</td><td>553</td><td>548</td><td>482</td><td>72</td><td>127</td><td>16</td><td>6</td><td>6</td><td>173</td><td>56</td><td>43</td><td>13</td><td>46</td><td>11</td><td>0</td><td>101</td><td>3</td><td>5</td><td>9</td><td style="">0.263</td><td>0.336</td><td>0.359</td><td>0.695</td><td>0.112</td><td>86.1</td><td style="background-color:#F3F3F3; font-weight:bold;">2.03</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14140">구본혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.29</td><td>133</td><td>0.73</td><td>0.56</td><td>389</td><td>385</td><td>339</td><td>48</td><td>87</td><td>14</td><td>2</td><td>2</td><td>111</td><td>43</td><td>8</td><td>4</td><td>38</td><td>4</td><td>0</td><td>51</td><td>7</td><td>4</td><td>4</td><td style="">0.257</td><td>0.335</td><td>0.327</td><td>0.662</td><td>0.101</td><td>77.6</td><td style="background-color:#F3F3F3; font-weight:bold;">1.29</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10187">김현수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.06</td><td>137</td><td>1.49</td><td>-0.43</td><td>583</td><td>582</td><td>517</td><td>61</td><td>152</td><td>36</td><td>2</td><td>8</td><td>216</td><td>69</td><td>6</td><td>1</td><td>47</td><td>9</td><td>1</td><td>76</td><td>10</td><td>1</td><td>9</td><td style="">0.294</td><td>0.357</td><td>0.418</td><td>0.775</td><td>0.136</td><td>104.7</td><td style="background-color:#F3F3F3; font-weight:bold;">1.06</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15084">최원영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.17</td><td>57</td><td>0.17</td><td>0.00</td><td>41</td><td>41</td><td>37</td><td>18</td><td>10</td><td>2</td><td>0</td><td>1</td><td>15</td><td>5</td><td>6</td><td>4</td><td>1</td><td>3</td><td>0</td><td>7</td><td>0</td><td>0</td><td>0</td><td style="">0.270</td><td>0.341</td><td>0.405</td><td>0.746</td><td>0.134</td><td>102.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.17</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15081">이주헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.13</td><td>3</td><td>0.22</td><td>-0.09</td><td>6</td><td>6</td><td>6</td><td>0</td><td>4</td><td>2</td><td>0</td><td>0</td><td>6</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.667</td><td>0.667</td><td>1.000</td><td>1.667</td><td>0.487</td><td>367.5</td><td style="background-color:#F3F3F3; font-weight:bold;">0.13</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12545">김주성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.12</td><td>12</td><td>0.07</td><td>0.05</td><td>9</td><td>9</td><td>6</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">0.167</td><td>0.444</td><td>0.167</td><td>0.611</td><td>0.145</td><td>110.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.12</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16013">김현종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.06</td><td>17</td><td>-0.03</td><td>0.09</td><td>16</td><td>16</td><td>15</td><td>8</td><td>3</td><td>1</td><td>0</td><td>0</td><td>4</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td style="">0.200</td><td>0.250</td><td>0.267</td><td>0.517</td><td>0.042</td><td>31.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.06</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16016">김대원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.04</td><td>19</td><td>0.06</td><td>-0.02</td><td>4</td><td>4</td><td>4</td><td>5</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.500</td><td>0.500</td><td>0.500</td><td>1.000</td><td>0.229</td><td>174.5</td><td style="background-color:#F3F3F3; font-weight:bold;">0.04</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11229">김유영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14142">임준형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16015">진우영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14669">유영찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>7</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14651">이종준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13102">김영준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11166">김진성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>3</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11094">함덕주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15486">박명근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12532">김대현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14143">이지강</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>3</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10535">최동환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12864">전준호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>3</td><td>-0.03</td><td>0.01</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-134.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11347">안익훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.02</td><td>37</td><td>-0.42</td><td>0.40</td><td>56</td><td>54</td><td>49</td><td>8</td><td>9</td><td>1</td><td>0</td><td>0</td><td>10</td><td>3</td><td>2</td><td>0</td><td>4</td><td>0</td><td>0</td><td>13</td><td>2</td><td>2</td><td>1</td><td style="">0.184</td><td>0.241</td><td>0.204</td><td>0.445</td><td>0.010</td><td>7.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.02</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13009">백승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>3</td><td>-0.03</td><td>0.00</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-151.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14136">정우영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>1</td><td>-0.03</td><td>0.00</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-127.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16026">최명경</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.06</td><td>1</td><td>0.00</td><td>-0.06</td><td>3</td><td>3</td><td>3</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.333</td><td>0.333</td><td>0.333</td><td>0.666</td><td>0.089</td><td>63.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.06</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14141">김성진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>14</td><td>0.01</td><td>-0.07</td><td>16</td><td>16</td><td>15</td><td>1</td><td>4</td><td>0</td><td>0</td><td>1</td><td>7</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td style="">0.267</td><td>0.313</td><td>0.467</td><td>0.780</td><td>0.123</td><td>94.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14187">최승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.09</td><td>57</td><td>-0.29</td><td>0.20</td><td>16</td><td>15</td><td>13</td><td>20</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>11</td><td>7</td><td>2</td><td>0</td><td>0</td><td>3</td><td>0</td><td>1</td><td>0</td><td style="">0.077</td><td>0.200</td><td>0.077</td><td>0.277</td><td>-0.037</td><td>-28.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.09</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13109">송찬의</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.13</td><td>10</td><td>-0.12</td><td>-0.01</td><td>21</td><td>20</td><td>15</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>1</td><td>0</td><td>3</td><td>1</td><td>0</td><td>6</td><td>0</td><td>1</td><td>1</td><td style="">0.067</td><td>0.250</td><td>0.067</td><td>0.317</td><td>0.003</td><td>2.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.13</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14675">김수인</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.13</td><td>4</td><td>-0.08</td><td>-0.06</td><td>3</td><td>3</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-136.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.13</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14783">이영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.18</td><td>31</td><td>-0.13</td><td>-0.05</td><td>71</td><td>69</td><td>63</td><td>11</td><td>14</td><td>2</td><td>0</td><td>2</td><td>22</td><td>12</td><td>0</td><td>1</td><td>4</td><td>0</td><td>0</td><td>20</td><td>0</td><td>2</td><td>2</td><td style="">0.222</td><td>0.261</td><td>0.349</td><td>0.610</td><td>0.059</td><td>45.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.18</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14590">손호영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.19</td><td>2</td><td>-0.07</td><td>-0.12</td><td>2</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-151.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.19</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14680">함창건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.19</td><td>15</td><td>-0.20</td><td>0.01</td><td>17</td><td>16</td><td>14</td><td>3</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>3</td><td>1</td><td>1</td><td>0</td><td style="">0.143</td><td>0.250</td><td>0.143</td><td>0.393</td><td>0.006</td><td>4.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.19</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15085">김성우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.26</td><td>4</td><td>-0.12</td><td>-0.14</td><td>5</td><td>5</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-139.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.26</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12931">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.33</td><td>19</td><td>-0.22</td><td>-0.11</td><td>22</td><td>22</td><td>20</td><td>1</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td style="">0.150</td><td>0.227</td><td>0.150</td><td>0.377</td><td>-0.004</td><td>-3.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.33</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15484">김범석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.33</td><td>70</td><td>-0.25</td><td>-0.08</td><td>180</td><td>179</td><td>162</td><td>14</td><td>39</td><td>4</td><td>0</td><td>6</td><td>61</td><td>24</td><td>0</td><td>0</td><td>14</td><td>2</td><td>2</td><td>49</td><td>4</td><td>0</td><td>2</td><td style="">0.241</td><td>0.306</td><td>0.377</td><td>0.683</td><td>0.095</td><td>71.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.33</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10684">허도환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.64</td><td>59</td><td>-0.22</td><td>-0.42</td><td>105</td><td>100</td><td>80</td><td>10</td><td>11</td><td>2</td><td>0</td><td>0</td><td>13</td><td>11</td><td>0</td><td>1</td><td>9</td><td>10</td><td>0</td><td>26</td><td>4</td><td>5</td><td>1</td><td style="">0.138</td><td>0.300</td><td>0.163</td><td>0.463</td><td>0.059</td><td>44.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.64</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16106">레이예스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.40</td><td>144</td><td>3.98</td><td>-0.58</td><td>632</td><td>631</td><td>574</td><td>88</td><td>202</td><td>40</td><td>3</td><td>15</td><td>293</td><td>111</td><td>5</td><td>0</td><td>46</td><td>1</td><td>2</td><td>82</td><td>16</td><td>0</td><td>11</td><td style="">0.352</td><td>0.394</td><td>0.510</td><td>0.904</td><td>0.179</td><td>127.5</td><td style="background-color:#F3F3F3; font-weight:bold;">3.40</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15048">윤동희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.13</td><td>141</td><td>2.90</td><td>0.23</td><td>613</td><td>610</td><td>532</td><td>97</td><td>156</td><td>35</td><td>4</td><td>14</td><td>241</td><td>85</td><td>7</td><td>8</td><td>67</td><td>7</td><td>1</td><td>114</td><td>10</td><td>2</td><td>5</td><td style="">0.293</td><td>0.376</td><td>0.453</td><td>0.829</td><td>0.159</td><td>113.1</td><td style="background-color:#F3F3F3; font-weight:bold;">3.13</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14160">고승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.08</td><td>120</td><td>2.96</td><td>0.12</td><td>532</td><td>531</td><td>481</td><td>79</td><td>148</td><td>27</td><td>6</td><td>14</td><td>229</td><td>87</td><td>5</td><td>4</td><td>41</td><td>1</td><td>0</td><td>78</td><td>10</td><td>1</td><td>8</td><td style="">0.308</td><td>0.358</td><td>0.476</td><td>0.834</td><td>0.152</td><td>107.9</td><td style="background-color:#F3F3F3; font-weight:bold;">3.08</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14590">손호영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.40</td><td>100</td><td>2.96</td><td>-0.57</td><td>428</td><td>425</td><td>396</td><td>70</td><td>126</td><td>26</td><td>4</td><td>18</td><td>214</td><td>78</td><td>7</td><td>4</td><td>17</td><td>9</td><td>2</td><td>65</td><td>5</td><td>1</td><td>5</td><td style="">0.318</td><td>0.356</td><td>0.540</td><td>0.896</td><td>0.170</td><td>121.7</td><td style="background-color:#F3F3F3; font-weight:bold;">2.40</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14642">황성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.33</td><td>125</td><td>2.46</td><td>-0.13</td><td>406</td><td>400</td><td>366</td><td>94</td><td>117</td><td>15</td><td>8</td><td>4</td><td>160</td><td>26</td><td>51</td><td>10</td><td>31</td><td>2</td><td>0</td><td>56</td><td>3</td><td>6</td><td>1</td><td style="">0.320</td><td>0.375</td><td>0.437</td><td>0.812</td><td>0.153</td><td>109.0</td><td style="background-color:#F3F3F3; font-weight:bold;">2.33</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14797">나승엽</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.22</td><td>121</td><td>2.83</td><td>-0.61</td><td>489</td><td>486</td><td>407</td><td>59</td><td>127</td><td>35</td><td>4</td><td>7</td><td>191</td><td>66</td><td>1</td><td>0</td><td>69</td><td>4</td><td>1</td><td>83</td><td>4</td><td>2</td><td>7</td><td style="">0.312</td><td>0.411</td><td>0.469</td><td>0.880</td><td>0.182</td><td>129.7</td><td style="background-color:#F3F3F3; font-weight:bold;">2.22</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10266">전준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.80</td><td>109</td><td>2.15</td><td>-0.36</td><td>483</td><td>482</td><td>423</td><td>57</td><td>124</td><td>26</td><td>2</td><td>17</td><td>205</td><td>82</td><td>3</td><td>1</td><td>49</td><td>5</td><td>0</td><td>84</td><td>11</td><td>1</td><td>5</td><td style="">0.293</td><td>0.369</td><td>0.485</td><td>0.854</td><td>0.163</td><td>115.7</td><td style="background-color:#F3F3F3; font-weight:bold;">1.80</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10804">박승욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.01</td><td>139</td><td>1.65</td><td>-0.64</td><td>468</td><td>463</td><td>405</td><td>57</td><td>106</td><td>19</td><td>1</td><td>7</td><td>148</td><td>53</td><td>4</td><td>5</td><td>47</td><td>10</td><td>3</td><td>120</td><td>7</td><td>3</td><td>3</td><td style="">0.262</td><td>0.351</td><td>0.365</td><td>0.716</td><td>0.121</td><td>86.4</td><td style="background-color:#F3F3F3; font-weight:bold;">1.01</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10253">정훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.76</td><td>109</td><td>0.76</td><td>0.00</td><td>325</td><td>324</td><td>285</td><td>31</td><td>76</td><td>20</td><td>0</td><td>9</td><td>123</td><td>47</td><td>1</td><td>1</td><td>35</td><td>0</td><td>0</td><td>63</td><td>3</td><td>1</td><td>4</td><td style="">0.267</td><td>0.343</td><td>0.432</td><td>0.775</td><td>0.133</td><td>94.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.76</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10557">오선진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.16</td><td>26</td><td>0.04</td><td>0.12</td><td>29</td><td>24</td><td>20</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>8</td><td>0</td><td>5</td><td>0</td><td style="">0.200</td><td>0.333</td><td>0.250</td><td>0.583</td><td>0.095</td><td>67.4</td><td style="background-color:#F3F3F3; font-weight:bold;">0.16</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15645">김동혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.16</td><td>39</td><td>0.15</td><td>0.01</td><td>17</td><td>17</td><td>15</td><td>8</td><td>3</td><td>0</td><td>1</td><td>0</td><td>5</td><td>1</td><td>3</td><td>1</td><td>2</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td style="">0.200</td><td>0.294</td><td>0.333</td><td>0.627</td><td>0.086</td><td>60.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.16</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12916">이정훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.14</td><td>65</td><td>0.19</td><td>-0.06</td><td>116</td><td>114</td><td>100</td><td>10</td><td>30</td><td>8</td><td>0</td><td>0</td><td>38</td><td>18</td><td>0</td><td>0</td><td>13</td><td>0</td><td>1</td><td>21</td><td>4</td><td>1</td><td>2</td><td style="">0.300</td><td>0.374</td><td>0.380</td><td>0.754</td><td>0.133</td><td>94.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.14</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14169">신윤후</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.12</td><td>39</td><td>-0.29</td><td>0.41</td><td>35</td><td>34</td><td>31</td><td>5</td><td>5</td><td>0</td><td>0</td><td>0</td><td>5</td><td>1</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>8</td><td>1</td><td>1</td><td>0</td><td style="">0.161</td><td>0.235</td><td>0.161</td><td>0.396</td><td>0.004</td><td>2.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.12</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16091">이호준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.11</td><td>12</td><td>0.10</td><td>0.01</td><td>7</td><td>7</td><td>6</td><td>5</td><td>2</td><td>1</td><td>1</td><td>0</td><td>5</td><td>3</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.333</td><td>0.429</td><td>0.833</td><td>1.262</td><td>0.307</td><td>214.0</td><td style="background-color:#F3F3F3; font-weight:bold;">0.11</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14690">이인한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.10</td><td>5</td><td>0.10</td><td>0.00</td><td>5</td><td>5</td><td>4</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.500</td><td>0.600</td><td>0.500</td><td>1.100</td><td>0.313</td><td>217.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.10</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10238">김민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.10</td><td>35</td><td>0.06</td><td>0.03</td><td>84</td><td>84</td><td>70</td><td>6</td><td>14</td><td>5</td><td>0</td><td>2</td><td>25</td><td>8</td><td>0</td><td>1</td><td>10</td><td>3</td><td>0</td><td>18</td><td>1</td><td>0</td><td>1</td><td style="">0.200</td><td>0.321</td><td>0.357</td><td>0.678</td><td>0.109</td><td>79.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.10</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10753">유강남</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.08</td><td>52</td><td>-0.08</td><td>0.16</td><td>155</td><td>153</td><td>136</td><td>11</td><td>26</td><td>3</td><td>0</td><td>5</td><td>44</td><td>20</td><td>0</td><td>0</td><td>9</td><td>7</td><td>0</td><td>25</td><td>4</td><td>2</td><td>1</td><td style="">0.191</td><td>0.275</td><td>0.324</td><td>0.599</td><td>0.071</td><td>50.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.08</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14796">손성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.08</td><td>86</td><td>0.19</td><td>-0.11</td><td>171</td><td>170</td><td>152</td><td>24</td><td>30</td><td>6</td><td>2</td><td>6</td><td>58</td><td>21</td><td>0</td><td>0</td><td>13</td><td>3</td><td>0</td><td>38</td><td>3</td><td>1</td><td>2</td><td style="">0.197</td><td>0.271</td><td>0.382</td><td>0.653</td><td>0.082</td><td>58.7</td><td style="background-color:#F3F3F3; font-weight:bold;">0.08</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15443">정대선</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.04</td><td>3</td><td>-0.05</td><td>0.09</td><td>2</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-142.1</td><td style="background-color:#F3F3F3; font-weight:bold;">0.04</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13094">추재현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10427">김상수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10825">김원중</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13271">현도훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12699">김강현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16093">강성우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>3</td><td>2</td><td>2</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td style="">0.500</td><td>0.500</td><td>0.500</td><td>1.000</td><td>0.229</td><td>173.1</td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16101">백두산</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.02</td><td>1</td><td>-0.02</td><td>0.00</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-127.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.02</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16102">강승구</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.08</td><td>5</td><td>-0.05</td><td>-0.03</td><td>2</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-127.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.08</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13155">장두성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.12</td><td>71</td><td>-0.14</td><td>0.01</td><td>37</td><td>37</td><td>32</td><td>23</td><td>5</td><td>0</td><td>0</td><td>0</td><td>5</td><td>1</td><td>14</td><td>3</td><td>3</td><td>2</td><td>0</td><td>9</td><td>2</td><td>0</td><td>0</td><td style="">0.156</td><td>0.270</td><td>0.156</td><td>0.426</td><td>0.028</td><td>19.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.12</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14114">이학주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.15</td><td>43</td><td>0.25</td><td>-0.40</td><td>105</td><td>103</td><td>95</td><td>13</td><td>25</td><td>2</td><td>2</td><td>2</td><td>37</td><td>4</td><td>0</td><td>1</td><td>6</td><td>2</td><td>0</td><td>44</td><td>0</td><td>2</td><td>0</td><td style="">0.263</td><td>0.320</td><td>0.389</td><td>0.709</td><td>0.111</td><td>79.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.15</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16095">이선우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.20</td><td>7</td><td>-0.02</td><td>-0.18</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">-0.20</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11388">강태율</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.26</td><td>10</td><td>-0.24</td><td>-0.02</td><td>10</td><td>10</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-132.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.26</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11165">노진혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.26</td><td>73</td><td>-0.18</td><td>-0.08</td><td>157</td><td>154</td><td>137</td><td>13</td><td>30</td><td>6</td><td>0</td><td>2</td><td>42</td><td>13</td><td>0</td><td>0</td><td>15</td><td>1</td><td>1</td><td>39</td><td>1</td><td>2</td><td>2</td><td style="">0.219</td><td>0.297</td><td>0.307</td><td>0.604</td><td>0.072</td><td>51.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.26</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10810">최항</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.31</td><td>72</td><td>-0.41</td><td>0.10</td><td>143</td><td>143</td><td>132</td><td>17</td><td>33</td><td>3</td><td>1</td><td>0</td><td>38</td><td>12</td><td>0</td><td>1</td><td>10</td><td>1</td><td>0</td><td>32</td><td>3</td><td>0</td><td>0</td><td style="">0.250</td><td>0.308</td><td>0.288</td><td>0.596</td><td>0.073</td><td>51.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.31</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15253">김민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.41</td><td>41</td><td>-0.42</td><td>0.01</td><td>83</td><td>82</td><td>76</td><td>14</td><td>16</td><td>3</td><td>1</td><td>0</td><td>21</td><td>6</td><td>3</td><td>1</td><td>2</td><td>4</td><td>0</td><td>20</td><td>4</td><td>1</td><td>0</td><td style="">0.211</td><td>0.268</td><td>0.276</td><td>0.544</td><td>0.054</td><td>38.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.41</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14819">이주찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.43</td><td>17</td><td>-0.11</td><td>-0.32</td><td>25</td><td>25</td><td>24</td><td>7</td><td>4</td><td>1</td><td>0</td><td>1</td><td>8</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>9</td><td>1</td><td>0</td><td>0</td><td style="">0.167</td><td>0.200</td><td>0.333</td><td>0.533</td><td>0.025</td><td>17.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.43</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15624">서동욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.45</td><td>33</td><td>-0.35</td><td>-0.10</td><td>27</td><td>27</td><td>26</td><td>2</td><td>3</td><td>1</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>8</td><td>1</td><td>0</td><td>0</td><td style="">0.115</td><td>0.148</td><td>0.154</td><td>0.302</td><td>-0.052</td><td>-37.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.45</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13145">한동희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.55</td><td>14</td><td>-0.31</td><td>-0.25</td><td>36</td><td>36</td><td>35</td><td>1</td><td>9</td><td>2</td><td>0</td><td>0</td><td>11</td><td>3</td><td>0</td><td>0</td><td>1</td><td>0</td><td>1</td><td>9</td><td>1</td><td>0</td><td>0</td><td style="">0.257</td><td>0.278</td><td>0.314</td><td>0.592</td><td>0.052</td><td>37.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.55</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13154">정보근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.63</td><td>89</td><td>-0.61</td><td>-0.02</td><td>140</td><td>136</td><td>133</td><td>9</td><td>30</td><td>0</td><td>1</td><td>2</td><td>38</td><td>7</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>31</td><td>5</td><td>4</td><td>0</td><td style="">0.226</td><td>0.243</td><td>0.286</td><td>0.529</td><td>0.030</td><td>21.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.63</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15056">김도영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">8.32</td><td>141</td><td>8.51</td><td>-0.18</td><td>625</td><td>619</td><td>544</td><td>143</td><td>189</td><td>29</td><td>10</td><td>38</td><td>352</td><td>109</td><td>40</td><td>4</td><td>66</td><td>7</td><td>7</td><td>110</td><td>10</td><td>1</td><td>7</td><td style="">0.347</td><td>0.420</td><td>0.647</td><td>1.067</td><td>0.232</td><td>172.5</td><td style="background-color:#F3F3F3; font-weight:bold;">8.32</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14996">소크라테스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.42</td><td>140</td><td>3.52</td><td>-0.10</td><td>602</td><td>599</td><td>552</td><td>92</td><td>171</td><td>30</td><td>3</td><td>26</td><td>285</td><td>97</td><td>13</td><td>5</td><td>41</td><td>4</td><td>4</td><td>91</td><td>7</td><td>0</td><td>5</td><td style="">0.310</td><td>0.359</td><td>0.516</td><td>0.875</td><td>0.163</td><td>121.2</td><td style="background-color:#F3F3F3; font-weight:bold;">3.42</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11261">박찬호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.78</td><td>134</td><td>2.58</td><td>0.20</td><td>577</td><td>570</td><td>515</td><td>86</td><td>158</td><td>24</td><td>1</td><td>5</td><td>199</td><td>61</td><td>20</td><td>13</td><td>48</td><td>1</td><td>1</td><td>44</td><td>9</td><td>7</td><td>6</td><td style="">0.307</td><td>0.363</td><td>0.386</td><td>0.749</td><td>0.129</td><td>95.7</td><td style="background-color:#F3F3F3; font-weight:bold;">2.78</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10008">김선빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.38</td><td>116</td><td>2.98</td><td>-0.60</td><td>466</td><td>458</td><td>423</td><td>48</td><td>139</td><td>23</td><td>0</td><td>9</td><td>189</td><td>57</td><td>5</td><td>1</td><td>30</td><td>5</td><td>0</td><td>39</td><td>13</td><td>7</td><td>0</td><td style="">0.329</td><td>0.380</td><td>0.447</td><td>0.827</td><td>0.156</td><td>117.4</td><td style="background-color:#F3F3F3; font-weight:bold;">2.38</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12534">최원준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.17</td><td>136</td><td>2.43</td><td>-0.26</td><td>508</td><td>501</td><td>438</td><td>75</td><td>128</td><td>23</td><td>3</td><td>9</td><td>184</td><td>56</td><td>21</td><td>9</td><td>50</td><td>8</td><td>0</td><td>66</td><td>6</td><td>7</td><td>5</td><td style="">0.292</td><td>0.371</td><td>0.420</td><td>0.791</td><td>0.147</td><td>110.1</td><td style="background-color:#F3F3F3; font-weight:bold;">2.17</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11162">나성범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.73</td><td>102</td><td>1.89</td><td>-0.16</td><td>424</td><td>422</td><td>374</td><td>51</td><td>109</td><td>17</td><td>1</td><td>21</td><td>191</td><td>80</td><td>0</td><td>0</td><td>38</td><td>4</td><td>1</td><td>98</td><td>8</td><td>0</td><td>7</td><td style="">0.291</td><td>0.357</td><td>0.511</td><td>0.868</td><td>0.160</td><td>118.4</td><td style="background-color:#F3F3F3; font-weight:bold;">1.73</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10344">최형우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.54</td><td>116</td><td>1.83</td><td>-0.29</td><td>487</td><td>486</td><td>425</td><td>67</td><td>119</td><td>23</td><td>2</td><td>22</td><td>212</td><td>109</td><td>1</td><td>1</td><td>52</td><td>5</td><td>4</td><td>86</td><td>5</td><td>0</td><td>5</td><td style="">0.280</td><td>0.361</td><td>0.499</td><td>0.860</td><td>0.161</td><td>119.0</td><td style="background-color:#F3F3F3; font-weight:bold;">1.54</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13113">한준수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.54</td><td>115</td><td>1.66</td><td>-0.12</td><td>316</td><td>316</td><td>287</td><td>39</td><td>88</td><td>22</td><td>0</td><td>7</td><td>131</td><td>41</td><td>0</td><td>0</td><td>21</td><td>2</td><td>1</td><td>48</td><td>7</td><td>0</td><td>6</td><td style="">0.307</td><td>0.351</td><td>0.456</td><td>0.807</td><td>0.141</td><td>105.2</td><td style="background-color:#F3F3F3; font-weight:bold;">1.54</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10855">서건창</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.51</td><td>94</td><td>1.54</td><td>-0.02</td><td>248</td><td>245</td><td>203</td><td>40</td><td>63</td><td>14</td><td>1</td><td>1</td><td>82</td><td>26</td><td>3</td><td>1</td><td>36</td><td>3</td><td>0</td><td>31</td><td>2</td><td>3</td><td>3</td><td style="">0.310</td><td>0.416</td><td>0.404</td><td>0.820</td><td>0.169</td><td>124.5</td><td style="background-color:#F3F3F3; font-weight:bold;">1.51</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10459">김태군</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.13</td><td>105</td><td>0.81</td><td>0.32</td><td>270</td><td>259</td><td>235</td><td>24</td><td>62</td><td>7</td><td>0</td><td>7</td><td>90</td><td>34</td><td>0</td><td>0</td><td>12</td><td>11</td><td>0</td><td>24</td><td>14</td><td>11</td><td>1</td><td style="">0.264</td><td>0.328</td><td>0.383</td><td>0.711</td><td>0.115</td><td>85.3</td><td style="background-color:#F3F3F3; font-weight:bold;">1.13</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14124">변우혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.72</td><td>69</td><td>0.77</td><td>-0.04</td><td>187</td><td>187</td><td>168</td><td>22</td><td>51</td><td>9</td><td>2</td><td>5</td><td>79</td><td>21</td><td>1</td><td>0</td><td>16</td><td>2</td><td>0</td><td>48</td><td>8</td><td>0</td><td>1</td><td style="">0.304</td><td>0.369</td><td>0.470</td><td>0.839</td><td>0.159</td><td>119.0</td><td style="background-color:#F3F3F3; font-weight:bold;">0.72</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11233">이창진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.54</td><td>103</td><td>0.80</td><td>-0.26</td><td>247</td><td>242</td><td>191</td><td>36</td><td>50</td><td>10</td><td>0</td><td>1</td><td>63</td><td>18</td><td>4</td><td>3</td><td>45</td><td>2</td><td>0</td><td>36</td><td>6</td><td>5</td><td>4</td><td style="">0.262</td><td>0.401</td><td>0.330</td><td>0.731</td><td>0.144</td><td>107.0</td><td style="background-color:#F3F3F3; font-weight:bold;">0.54</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15058">윤도현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.50</td><td>6</td><td>0.33</td><td>0.16</td><td>27</td><td>27</td><td>27</td><td>5</td><td>11</td><td>2</td><td>0</td><td>1</td><td>16</td><td>8</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9</td><td>0</td><td>0</td><td>0</td><td style="">0.407</td><td>0.407</td><td>0.593</td><td>1.000</td><td>0.212</td><td>154.7</td><td style="background-color:#F3F3F3; font-weight:bold;">0.50</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12869">박정우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.42</td><td>66</td><td>0.05</td><td>0.37</td><td>69</td><td>69</td><td>65</td><td>17</td><td>20</td><td>3</td><td>1</td><td>0</td><td>25</td><td>11</td><td>0</td><td>1</td><td>4</td><td>0</td><td>0</td><td>14</td><td>3</td><td>0</td><td>0</td><td style="">0.308</td><td>0.348</td><td>0.385</td><td>0.733</td><td>0.121</td><td>89.2</td><td style="background-color:#F3F3F3; font-weight:bold;">0.42</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11099">이우성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.18</td><td>112</td><td>0.73</td><td>-0.55</td><td>449</td><td>449</td><td>399</td><td>56</td><td>115</td><td>16</td><td>1</td><td>9</td><td>160</td><td>54</td><td>7</td><td>1</td><td>44</td><td>3</td><td>0</td><td>89</td><td>17</td><td>0</td><td>3</td><td style="">0.288</td><td>0.361</td><td>0.401</td><td>0.762</td><td>0.134</td><td>99.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.18</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14612">홍종표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.16</td><td>100</td><td>0.48</td><td>-0.32</td><td>115</td><td>112</td><td>105</td><td>27</td><td>31</td><td>4</td><td>3</td><td>0</td><td>41</td><td>11</td><td>5</td><td>2</td><td>6</td><td>1</td><td>0</td><td>31</td><td>0</td><td>3</td><td>0</td><td style="">0.295</td><td>0.339</td><td>0.390</td><td>0.729</td><td>0.120</td><td>89.0</td><td style="background-color:#F3F3F3; font-weight:bold;">0.16</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12537">전상현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16082">김민주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15435">곽도규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15063">황동하</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11364">김사윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12637">김승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11159">이형범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14608">정해영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15057">최지민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14611">박민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>16</td><td>0.00</td><td>-0.01</td><td>30</td><td>30</td><td>29</td><td>5</td><td>8</td><td>4</td><td>0</td><td>0</td><td>12</td><td>2</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>0</td><td style="">0.276</td><td>0.300</td><td>0.414</td><td>0.714</td><td>0.105</td><td>77.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10659">고종욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.02</td><td>28</td><td>0.06</td><td>-0.09</td><td>36</td><td>36</td><td>32</td><td>3</td><td>8</td><td>2</td><td>0</td><td>1</td><td>13</td><td>4</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>6</td><td>2</td><td>0</td><td>0</td><td style="">0.250</td><td>0.333</td><td>0.406</td><td>0.739</td><td>0.122</td><td>92.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.02</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11306">황대인</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.05</td><td>3</td><td>-0.01</td><td>-0.04</td><td>7</td><td>7</td><td>7</td><td>1</td><td>2</td><td>1</td><td>0</td><td>0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.286</td><td>0.286</td><td>0.429</td><td>0.715</td><td>0.100</td><td>74.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.05</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14181">오선우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>3</td><td>-0.03</td><td>-0.04</td><td>7</td><td>7</td><td>7</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td style="">0.286</td><td>0.286</td><td>0.286</td><td>0.572</td><td>0.049</td><td>36.1</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11119">한승택</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>20</td><td>0.11</td><td>-0.17</td><td>15</td><td>15</td><td>11</td><td>2</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3</td><td>2</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.273</td><td>0.467</td><td>0.273</td><td>0.740</td><td>0.171</td><td>128.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16086">김두현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.15</td><td>3</td><td>0.10</td><td>-0.26</td><td>6</td><td>6</td><td>5</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">0.400</td><td>0.500</td><td>0.400</td><td>0.900</td><td>0.229</td><td>164.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.15</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12540">김규성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.19</td><td>27</td><td>0.05</td><td>-0.25</td><td>15</td><td>14</td><td>12</td><td>5</td><td>3</td><td>1</td><td>0</td><td>0</td><td>4</td><td>2</td><td>1</td><td>0</td><td>2</td><td>0</td><td>0</td><td>4</td><td>0</td><td>1</td><td>0</td><td style="">0.250</td><td>0.357</td><td>0.333</td><td>0.690</td><td>0.119</td><td>88.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.19</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11407">최정용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.20</td><td>6</td><td>-0.10</td><td>-0.10</td><td>12</td><td>12</td><td>11</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td style="">0.182</td><td>0.250</td><td>0.182</td><td>0.432</td><td>0.010</td><td>7.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.20</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11298">김호령</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.23</td><td>64</td><td>-0.44</td><td>0.21</td><td>67</td><td>67</td><td>59</td><td>12</td><td>8</td><td>2</td><td>0</td><td>1</td><td>13</td><td>4</td><td>3</td><td>2</td><td>8</td><td>0</td><td>0</td><td>25</td><td>1</td><td>0</td><td>0</td><td style="">0.136</td><td>0.239</td><td>0.220</td><td>0.459</td><td>0.021</td><td>16.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.23</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12995">로하스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">6.50</td><td>144</td><td>6.34</td><td>0.16</td><td>670</td><td>664</td><td>572</td><td>108</td><td>188</td><td>39</td><td>1</td><td>32</td><td>325</td><td>112</td><td>2</td><td>1</td><td>88</td><td>6</td><td>9</td><td>115</td><td>10</td><td>0</td><td>4</td><td style="">0.329</td><td>0.421</td><td>0.568</td><td>0.989</td><td>0.211</td><td>153.3</td><td style="background-color:#F3F3F3; font-weight:bold;">6.50</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10235">장성우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.23</td><td>131</td><td>3.13</td><td>0.10</td><td>489</td><td>486</td><td>418</td><td>53</td><td>112</td><td>19</td><td>0</td><td>19</td><td>188</td><td>81</td><td>5</td><td>0</td><td>60</td><td>1</td><td>1</td><td>86</td><td>8</td><td>2</td><td>8</td><td style="">0.268</td><td>0.355</td><td>0.450</td><td>0.805</td><td>0.144</td><td>104.2</td><td style="background-color:#F3F3F3; font-weight:bold;">3.23</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11339">김민혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.20</td><td>115</td><td>2.08</td><td>0.12</td><td>393</td><td>389</td><td>351</td><td>47</td><td>124</td><td>14</td><td>3</td><td>1</td><td>147</td><td>34</td><td>4</td><td>2</td><td>35</td><td>1</td><td>1</td><td>45</td><td>9</td><td>3</td><td>3</td><td style="">0.353</td><td>0.410</td><td>0.419</td><td>0.829</td><td>0.164</td><td>118.0</td><td style="background-color:#F3F3F3; font-weight:bold;">2.20</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13168">강백호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.12</td><td>144</td><td>2.46</td><td>-0.34</td><td>614</td><td>612</td><td>550</td><td>92</td><td>159</td><td>27</td><td>0</td><td>26</td><td>264</td><td>96</td><td>6</td><td>2</td><td>59</td><td>3</td><td>4</td><td>127</td><td>6</td><td>0</td><td>2</td><td style="">0.289</td><td>0.360</td><td>0.480</td><td>0.840</td><td>0.154</td><td>112.3</td><td style="background-color:#F3F3F3; font-weight:bold;">2.12</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10320">김상수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.89</td><td>113</td><td>1.77</td><td>0.13</td><td>420</td><td>413</td><td>369</td><td>60</td><td>102</td><td>18</td><td>4</td><td>4</td><td>140</td><td>45</td><td>3</td><td>2</td><td>37</td><td>6</td><td>0</td><td>59</td><td>12</td><td>7</td><td>1</td><td style="">0.276</td><td>0.351</td><td>0.379</td><td>0.730</td><td>0.126</td><td>91.5</td><td style="background-color:#F3F3F3; font-weight:bold;">1.89</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11333">문상철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.64</td><td>125</td><td>0.96</td><td>0.68</td><td>403</td><td>401</td><td>347</td><td>50</td><td>89</td><td>11</td><td>0</td><td>17</td><td>151</td><td>58</td><td>6</td><td>1</td><td>45</td><td>7</td><td>2</td><td>86</td><td>8</td><td>1</td><td>3</td><td style="">0.256</td><td>0.351</td><td>0.435</td><td>0.786</td><td>0.139</td><td>101.7</td><td style="background-color:#F3F3F3; font-weight:bold;">1.64</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11397">오윤석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.52</td><td>73</td><td>1.36</td><td>0.16</td><td>201</td><td>198</td><td>174</td><td>33</td><td>51</td><td>12</td><td>2</td><td>6</td><td>85</td><td>27</td><td>0</td><td>1</td><td>18</td><td>4</td><td>0</td><td>41</td><td>7</td><td>3</td><td>2</td><td style="">0.293</td><td>0.369</td><td>0.489</td><td>0.858</td><td>0.166</td><td>120.7</td><td style="background-color:#F3F3F3; font-weight:bold;">1.52</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11212">배정대</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.88</td><td>113</td><td>1.41</td><td>-0.52</td><td>473</td><td>464</td><td>404</td><td>49</td><td>111</td><td>25</td><td>1</td><td>7</td><td>159</td><td>59</td><td>9</td><td>7</td><td>50</td><td>4</td><td>1</td><td>114</td><td>5</td><td>8</td><td>7</td><td style="">0.275</td><td>0.355</td><td>0.394</td><td>0.749</td><td>0.129</td><td>94.1</td><td style="background-color:#F3F3F3; font-weight:bold;">0.88</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10840">신본기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.82</td><td>84</td><td>0.84</td><td>-0.02</td><td>152</td><td>143</td><td>122</td><td>18</td><td>34</td><td>3</td><td>0</td><td>3</td><td>46</td><td>19</td><td>2</td><td>0</td><td>16</td><td>3</td><td>0</td><td>28</td><td>3</td><td>9</td><td>2</td><td style="">0.279</td><td>0.371</td><td>0.377</td><td>0.748</td><td>0.135</td><td>97.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.82</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11334">심우준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.64</td><td>53</td><td>0.65</td><td>-0.01</td><td>192</td><td>187</td><td>169</td><td>22</td><td>45</td><td>4</td><td>0</td><td>3</td><td>58</td><td>28</td><td>7</td><td>1</td><td>17</td><td>1</td><td>0</td><td>29</td><td>3</td><td>5</td><td>0</td><td style="">0.266</td><td>0.337</td><td>0.343</td><td>0.680</td><td>0.105</td><td>75.5</td><td style="background-color:#F3F3F3; font-weight:bold;">0.64</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13177">조대현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.46</td><td>26</td><td>0.17</td><td>0.29</td><td>45</td><td>40</td><td>36</td><td>2</td><td>11</td><td>2</td><td>0</td><td>0</td><td>13</td><td>3</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>12</td><td>1</td><td>5</td><td>1</td><td style="">0.306</td><td>0.350</td><td>0.361</td><td>0.711</td><td>0.113</td><td>81.4</td><td style="background-color:#F3F3F3; font-weight:bold;">0.46</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14603">강현우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.34</td><td>18</td><td>0.46</td><td>-0.12</td><td>36</td><td>34</td><td>26</td><td>4</td><td>8</td><td>1</td><td>0</td><td>1</td><td>12</td><td>8</td><td>0</td><td>0</td><td>8</td><td>0</td><td>0</td><td>10</td><td>0</td><td>2</td><td>0</td><td style="">0.308</td><td>0.471</td><td>0.462</td><td>0.933</td><td>0.216</td><td>161.1</td><td style="background-color:#F3F3F3; font-weight:bold;">0.34</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14606">천성호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.30</td><td>75</td><td>0.63</td><td>-0.33</td><td>255</td><td>254</td><td>234</td><td>41</td><td>69</td><td>8</td><td>3</td><td>1</td><td>86</td><td>17</td><td>7</td><td>0</td><td>18</td><td>1</td><td>0</td><td>43</td><td>5</td><td>1</td><td>1</td><td style="">0.295</td><td>0.346</td><td>0.368</td><td>0.714</td><td>0.116</td><td>84.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.30</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15519">정준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.17</td><td>43</td><td>-0.17</td><td>0.34</td><td>74</td><td>71</td><td>62</td><td>9</td><td>14</td><td>2</td><td>0</td><td>0</td><td>16</td><td>3</td><td>0</td><td>0</td><td>8</td><td>1</td><td>0</td><td>16</td><td>1</td><td>3</td><td>0</td><td style="">0.226</td><td>0.324</td><td>0.258</td><td>0.582</td><td>0.079</td><td>57.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.17</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15097">김병준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.16</td><td>35</td><td>0.15</td><td>0.01</td><td>16</td><td>16</td><td>14</td><td>9</td><td>5</td><td>0</td><td>0</td><td>0</td><td>5</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.357</td><td>0.438</td><td>0.357</td><td>0.795</td><td>0.162</td><td>121.4</td><td style="background-color:#F3F3F3; font-weight:bold;">0.16</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10835">김준태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.15</td><td>23</td><td>0.15</td><td>0.00</td><td>30</td><td>30</td><td>25</td><td>6</td><td>6</td><td>2</td><td>0</td><td>0</td><td>8</td><td>3</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>0</td><td style="">0.240</td><td>0.367</td><td>0.320</td><td>0.687</td><td>0.122</td><td>91.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.15</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10469">박경수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.05</td><td>5</td><td>0.11</td><td>-0.05</td><td>3</td><td>3</td><td>3</td><td>2</td><td>2</td><td>1</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.667</td><td>0.667</td><td>1.000</td><td>1.667</td><td>0.487</td><td>354.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.05</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14191">강민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.01</td><td>1</td><td>-0.03</td><td>0.04</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-127.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.01</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14108">손동현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14869">김영현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15527">강건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13167">김민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14111">이선우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>3</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14667">성재헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12572">박세진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10737">박시영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11323">주권</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15089">박영현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>5</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10523">우규민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11214">장준원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.04</td><td>17</td><td>-0.13</td><td>0.09</td><td>18</td><td>18</td><td>14</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td style="">0.071</td><td>0.278</td><td>0.071</td><td>0.349</td><td>0.018</td><td>13.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.04</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15092">안현민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>16</td><td>0.01</td><td>-0.08</td><td>29</td><td>29</td><td>25</td><td>5</td><td>5</td><td>0</td><td>1</td><td>1</td><td>10</td><td>2</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>10</td><td>0</td><td>0</td><td>1</td><td style="">0.200</td><td>0.276</td><td>0.400</td><td>0.676</td><td>0.091</td><td>67.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14777">권동진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.09</td><td>9</td><td>-0.03</td><td>-0.07</td><td>10</td><td>10</td><td>9</td><td>3</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.222</td><td>0.300</td><td>0.222</td><td>0.522</td><td>0.050</td><td>37.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.09</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10470">박병호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.13</td><td>44</td><td>-0.31</td><td>0.17</td><td>121</td><td>121</td><td>101</td><td>10</td><td>20</td><td>2</td><td>0</td><td>3</td><td>31</td><td>10</td><td>1</td><td>0</td><td>16</td><td>4</td><td>0</td><td>38</td><td>8</td><td>0</td><td>0</td><td style="">0.198</td><td>0.331</td><td>0.307</td><td>0.638</td><td>0.101</td><td>72.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.13</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12941">홍현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.18</td><td>28</td><td>0.04</td><td>-0.22</td><td>22</td><td>21</td><td>18</td><td>5</td><td>4</td><td>0</td><td>1</td><td>0</td><td>6</td><td>2</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>7</td><td>0</td><td>1</td><td>0</td><td style="">0.222</td><td>0.333</td><td>0.333</td><td>0.666</td><td>0.108</td><td>78.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.18</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11342">송민섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.18</td><td>36</td><td>0.08</td><td>-0.26</td><td>20</td><td>19</td><td>14</td><td>8</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>1</td><td>3</td><td>2</td><td>0</td><td>6</td><td>0</td><td>1</td><td>0</td><td style="">0.214</td><td>0.421</td><td>0.214</td><td>0.635</td><td>0.145</td><td>105.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.18</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13006">안치영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.22</td><td>31</td><td>-0.26</td><td>0.05</td><td>48</td><td>46</td><td>44</td><td>12</td><td>11</td><td>0</td><td>0</td><td>0</td><td>11</td><td>3</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>12</td><td>0</td><td>2</td><td>0</td><td style="">0.250</td><td>0.283</td><td>0.250</td><td>0.533</td><td>0.042</td><td>30.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.22</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14605">윤준혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.23</td><td>13</td><td>-0.15</td><td>-0.08</td><td>18</td><td>18</td><td>17</td><td>3</td><td>3</td><td>2</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>0</td><td style="">0.176</td><td>0.222</td><td>0.294</td><td>0.516</td><td>0.030</td><td>21.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.23</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10407">황재균</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.30</td><td>137</td><td>0.02</td><td>-0.32</td><td>536</td><td>531</td><td>493</td><td>60</td><td>128</td><td>22</td><td>0</td><td>13</td><td>189</td><td>58</td><td>4</td><td>6</td><td>34</td><td>2</td><td>0</td><td>95</td><td>16</td><td>5</td><td>2</td><td style="">0.260</td><td>0.309</td><td>0.383</td><td>0.692</td><td>0.099</td><td>72.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.30</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14110">박민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.31</td><td>20</td><td>-0.14</td><td>-0.18</td><td>14</td><td>14</td><td>14</td><td>6</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>0</td><td style="">0.214</td><td>0.214</td><td>0.214</td><td>0.428</td><td>-0.010</td><td>-7.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.31</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14779">김건형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.38</td><td>13</td><td>-0.35</td><td>-0.03</td><td>25</td><td>25</td><td>24</td><td>2</td><td>3</td><td>1</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>8</td><td>0</td><td>0</td><td>0</td><td style="">0.125</td><td>0.160</td><td>0.167</td><td>0.327</td><td>-0.046</td><td>-34.1</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.38</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10400">오재일</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.45</td><td>83</td><td>-0.01</td><td>-0.43</td><td>272</td><td>272</td><td>232</td><td>27</td><td>57</td><td>13</td><td>0</td><td>8</td><td>94</td><td>37</td><td>0</td><td>0</td><td>30</td><td>2</td><td>0</td><td>70</td><td>3</td><td>0</td><td>8</td><td style="">0.246</td><td>0.327</td><td>0.405</td><td>0.732</td><td>0.116</td><td>84.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.45</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12943">조용호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.52</td><td>60</td><td>-0.53</td><td>0.01</td><td>165</td><td>162</td><td>149</td><td>17</td><td>37</td><td>5</td><td>0</td><td>0</td><td>42</td><td>13</td><td>5</td><td>1</td><td>13</td><td>0</td><td>0</td><td>25</td><td>5</td><td>3</td><td>0</td><td style="">0.248</td><td>0.309</td><td>0.282</td><td>0.591</td><td>0.071</td><td>51.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.52</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13151">이호연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.61</td><td>27</td><td>-0.55</td><td>-0.06</td><td>43</td><td>42</td><td>41</td><td>3</td><td>6</td><td>1</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>12</td><td>2</td><td>1</td><td>0</td><td style="">0.146</td><td>0.167</td><td>0.171</td><td>0.338</td><td>-0.044</td><td>-32.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.61</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10892">구자욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.69</td><td>129</td><td>5.61</td><td>0.08</td><td>568</td><td>563</td><td>493</td><td>92</td><td>169</td><td>39</td><td>1</td><td>33</td><td>309</td><td>115</td><td>13</td><td>4</td><td>55</td><td>12</td><td>4</td><td>73</td><td>6</td><td>2</td><td>6</td><td style="">0.343</td><td>0.417</td><td>0.627</td><td>1.044</td><td>0.228</td><td>162.3</td><td style="background-color:#F3F3F3; font-weight:bold;">5.69</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14618">김지찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.98</td><td>135</td><td>3.58</td><td>0.41</td><td>535</td><td>521</td><td>453</td><td>102</td><td>143</td><td>16</td><td>3</td><td>3</td><td>174</td><td>36</td><td>42</td><td>4</td><td>60</td><td>9</td><td>2</td><td>40</td><td>5</td><td>12</td><td>1</td><td style="">0.316</td><td>0.405</td><td>0.384</td><td>0.789</td><td>0.157</td><td>112.7</td><td style="background-color:#F3F3F3; font-weight:bold;">3.98</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10232">강민호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.32</td><td>136</td><td>3.02</td><td>0.30</td><td>452</td><td>450</td><td>403</td><td>48</td><td>122</td><td>19</td><td>1</td><td>19</td><td>200</td><td>77</td><td>3</td><td>0</td><td>35</td><td>8</td><td>2</td><td>52</td><td>17</td><td>0</td><td>6</td><td style="">0.303</td><td>0.365</td><td>0.496</td><td>0.861</td><td>0.161</td><td>115.6</td><td style="background-color:#F3F3F3; font-weight:bold;">3.32</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15034">이재현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.03</td><td>109</td><td>2.43</td><td>0.60</td><td>458</td><td>457</td><td>389</td><td>71</td><td>101</td><td>18</td><td>1</td><td>14</td><td>163</td><td>66</td><td>2</td><td>1</td><td>58</td><td>8</td><td>1</td><td>83</td><td>8</td><td>0</td><td>3</td><td style="">0.260</td><td>0.365</td><td>0.419</td><td>0.784</td><td>0.146</td><td>104.8</td><td style="background-color:#F3F3F3; font-weight:bold;">3.03</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15035">김영웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.29</td><td>126</td><td>1.59</td><td>0.71</td><td>509</td><td>508</td><td>456</td><td>65</td><td>115</td><td>16</td><td>3</td><td>28</td><td>221</td><td>79</td><td>9</td><td>2</td><td>45</td><td>3</td><td>0</td><td>155</td><td>2</td><td>1</td><td>4</td><td style="">0.252</td><td>0.321</td><td>0.485</td><td>0.806</td><td>0.137</td><td>97.8</td><td style="background-color:#F3F3F3; font-weight:bold;">2.29</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12562">이성규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.11</td><td>122</td><td>1.02</td><td>0.08</td><td>355</td><td>351</td><td>302</td><td>56</td><td>73</td><td>10</td><td>1</td><td>22</td><td>151</td><td>57</td><td>9</td><td>2</td><td>31</td><td>15</td><td>0</td><td>109</td><td>5</td><td>4</td><td>3</td><td style="">0.242</td><td>0.339</td><td>0.500</td><td>0.839</td><td>0.149</td><td>106.1</td><td style="background-color:#F3F3F3; font-weight:bold;">1.11</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10640">김헌곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.05</td><td>117</td><td>0.87</td><td>0.18</td><td>311</td><td>307</td><td>281</td><td>43</td><td>85</td><td>8</td><td>1</td><td>9</td><td>122</td><td>34</td><td>4</td><td>2</td><td>22</td><td>3</td><td>0</td><td>50</td><td>5</td><td>4</td><td>1</td><td style="">0.302</td><td>0.358</td><td>0.434</td><td>0.792</td><td>0.142</td><td>101.0</td><td style="background-color:#F3F3F3; font-weight:bold;">1.05</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13161">윤정빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.05</td><td>69</td><td>0.67</td><td>0.38</td><td>188</td><td>188</td><td>161</td><td>26</td><td>46</td><td>4</td><td>1</td><td>7</td><td>73</td><td>20</td><td>1</td><td>3</td><td>22</td><td>3</td><td>0</td><td>47</td><td>1</td><td>0</td><td>2</td><td style="">0.286</td><td>0.378</td><td>0.453</td><td>0.831</td><td>0.159</td><td>113.7</td><td style="background-color:#F3F3F3; font-weight:bold;">1.05</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10470">박병호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.53</td><td>76</td><td>0.40</td><td>0.13</td><td>285</td><td>285</td><td>249</td><td>42</td><td>61</td><td>5</td><td>0</td><td>20</td><td>126</td><td>60</td><td>3</td><td>0</td><td>31</td><td>3</td><td>0</td><td>83</td><td>5</td><td>0</td><td>2</td><td style="">0.245</td><td>0.333</td><td>0.506</td><td>0.839</td><td>0.149</td><td>106.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.53</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16162">디아즈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.53</td><td>29</td><td>0.21</td><td>0.32</td><td>118</td><td>118</td><td>110</td><td>14</td><td>31</td><td>5</td><td>0</td><td>7</td><td>57</td><td>19</td><td>0</td><td>0</td><td>6</td><td>2</td><td>0</td><td>25</td><td>2</td><td>0</td><td>0</td><td style="">0.282</td><td>0.331</td><td>0.518</td><td>0.849</td><td>0.152</td><td>107.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.53</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15862">맥키넌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.51</td><td>72</td><td>0.35</td><td>0.17</td><td>315</td><td>313</td><td>272</td><td>28</td><td>80</td><td>13</td><td>0</td><td>4</td><td>105</td><td>36</td><td>1</td><td>0</td><td>39</td><td>1</td><td>3</td><td>33</td><td>6</td><td>0</td><td>3</td><td style="">0.294</td><td>0.381</td><td>0.386</td><td>0.767</td><td>0.135</td><td>96.5</td><td style="background-color:#F3F3F3; font-weight:bold;">0.51</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11422">전병우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.30</td><td>58</td><td>-0.07</td><td>0.36</td><td>128</td><td>128</td><td>111</td><td>17</td><td>25</td><td>5</td><td>0</td><td>5</td><td>45</td><td>14</td><td>0</td><td>1</td><td>14</td><td>1</td><td>0</td><td>42</td><td>3</td><td>0</td><td>2</td><td style="">0.225</td><td>0.313</td><td>0.405</td><td>0.718</td><td>0.110</td><td>77.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.30</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15503">류승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.13</td><td>5</td><td>0.04</td><td>0.09</td><td>3</td><td>3</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.667</td><td>0.000</td><td>0.667</td><td>0.294</td><td>226.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.13</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14117">이병헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.10</td><td>95</td><td>0.23</td><td>-0.13</td><td>166</td><td>164</td><td>145</td><td>9</td><td>36</td><td>4</td><td>0</td><td>1</td><td>43</td><td>9</td><td>0</td><td>0</td><td>17</td><td>2</td><td>0</td><td>48</td><td>0</td><td>2</td><td>0</td><td style="">0.248</td><td>0.335</td><td>0.297</td><td>0.632</td><td>0.094</td><td>66.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.10</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10894">류지혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.09</td><td>100</td><td>0.42</td><td>-0.34</td><td>348</td><td>343</td><td>302</td><td>43</td><td>78</td><td>9</td><td>1</td><td>3</td><td>98</td><td>36</td><td>11</td><td>4</td><td>33</td><td>6</td><td>0</td><td>70</td><td>7</td><td>5</td><td>2</td><td style="">0.258</td><td>0.341</td><td>0.325</td><td>0.666</td><td>0.106</td><td>76.0</td><td style="background-color:#F3F3F3; font-weight:bold;">0.09</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11266">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.07</td><td>9</td><td>0.09</td><td>-0.02</td><td>8</td><td>8</td><td>8</td><td>1</td><td>2</td><td>0</td><td>0</td><td>1</td><td>5</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.250</td><td>0.250</td><td>0.625</td><td>0.875</td><td>0.136</td><td>99.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.07</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15875">양도근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.04</td><td>16</td><td>0.01</td><td>0.03</td><td>29</td><td>28</td><td>23</td><td>5</td><td>4</td><td>0</td><td>1</td><td>0</td><td>6</td><td>2</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>8</td><td>0</td><td>1</td><td>0</td><td style="">0.174</td><td>0.321</td><td>0.261</td><td>0.582</td><td>0.085</td><td>58.1</td><td style="background-color:#F3F3F3; font-weight:bold;">0.04</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10367">오승환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10871">김태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10685">김대우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11489">김재윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>3</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15864">육선엽</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11169">이상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12934">최지광</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12936">김성윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>32</td><td>-0.07</td><td>0.04</td><td>89</td><td>86</td><td>74</td><td>15</td><td>18</td><td>4</td><td>0</td><td>0</td><td>22</td><td>6</td><td>3</td><td>1</td><td>9</td><td>1</td><td>0</td><td>16</td><td>1</td><td>3</td><td>2</td><td style="">0.243</td><td>0.326</td><td>0.297</td><td>0.623</td><td>0.088</td><td>65.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15499">김재상</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>35</td><td>-0.08</td><td>0.05</td><td>91</td><td>90</td><td>84</td><td>13</td><td>20</td><td>4</td><td>0</td><td>2</td><td>30</td><td>12</td><td>4</td><td>0</td><td>5</td><td>0</td><td>0</td><td>23</td><td>0</td><td>1</td><td>1</td><td style="">0.238</td><td>0.278</td><td>0.357</td><td>0.635</td><td>0.073</td><td>51.1</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11336">김태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.05</td><td>12</td><td>-0.14</td><td>0.09</td><td>21</td><td>21</td><td>20</td><td>2</td><td>4</td><td>1</td><td>0</td><td>0</td><td>5</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td style="">0.200</td><td>0.238</td><td>0.250</td><td>0.488</td><td>0.027</td><td>18.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.05</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16156">카디네스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.06</td><td>7</td><td>0.11</td><td>-0.18</td><td>25</td><td>25</td><td>24</td><td>2</td><td>8</td><td>2</td><td>0</td><td>2</td><td>16</td><td>5</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>6</td><td>1</td><td>0</td><td>0</td><td style="">0.333</td><td>0.360</td><td>0.667</td><td>1.027</td><td>0.210</td><td>145.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.06</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14115">김도환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.11</td><td>1</td><td>-0.07</td><td>-0.04</td><td>3</td><td>3</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-151.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.11</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13164">공민규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.16</td><td>12</td><td>-0.08</td><td>-0.08</td><td>17</td><td>17</td><td>14</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td><td>4</td><td>2</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>9</td><td>1</td><td>0</td><td>0</td><td style="">0.071</td><td>0.235</td><td>0.286</td><td>0.521</td><td>0.056</td><td>39.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.16</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14116">양우현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.17</td><td>7</td><td>-0.32</td><td>0.15</td><td>15</td><td>14</td><td>13</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>6</td><td>1</td><td>1</td><td>0</td><td style="">0.000</td><td>0.071</td><td>0.000</td><td>0.071</td><td>-0.138</td><td>-92.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.17</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14866">이창용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.24</td><td>9</td><td>-0.23</td><td>-0.01</td><td>21</td><td>21</td><td>21</td><td>1</td><td>4</td><td>1</td><td>0</td><td>0</td><td>5</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td style="">0.190</td><td>0.190</td><td>0.238</td><td>0.428</td><td>-0.013</td><td>-9.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.24</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11344">김재성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.24</td><td>10</td><td>-0.08</td><td>-0.16</td><td>23</td><td>23</td><td>20</td><td>3</td><td>4</td><td>1</td><td>0</td><td>0</td><td>5</td><td>1</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>5</td><td>1</td><td>0</td><td>0</td><td style="">0.200</td><td>0.304</td><td>0.250</td><td>0.554</td><td>0.066</td><td>47.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.24</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10400">오재일</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.27</td><td>22</td><td>-0.22</td><td>-0.05</td><td>71</td><td>71</td><td>64</td><td>6</td><td>15</td><td>5</td><td>1</td><td>3</td><td>31</td><td>8</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>18</td><td>4</td><td>0</td><td>1</td><td style="">0.234</td><td>0.296</td><td>0.484</td><td>0.780</td><td>0.123</td><td>87.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.27</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12548">김동엽</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.29</td><td>8</td><td>-0.29</td><td>0.00</td><td>21</td><td>20</td><td>18</td><td>1</td><td>2</td><td>1</td><td>0</td><td>0</td><td>3</td><td>2</td><td>0</td><td>0</td><td>1</td><td>1</td><td>1</td><td>5</td><td>0</td><td>0</td><td>1</td><td style="">0.111</td><td>0.190</td><td>0.167</td><td>0.357</td><td>-0.031</td><td>-21.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.29</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14863">김동진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.31</td><td>30</td><td>-0.47</td><td>0.17</td><td>42</td><td>40</td><td>37</td><td>5</td><td>4</td><td>0</td><td>0</td><td>1</td><td>7</td><td>2</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>10</td><td>1</td><td>2</td><td>0</td><td style="">0.108</td><td>0.175</td><td>0.189</td><td>0.364</td><td>-0.028</td><td>-20.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.31</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15868">김호진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.40</td><td>26</td><td>-0.47</td><td>0.07</td><td>32</td><td>32</td><td>29</td><td>4</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>3</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>11</td><td>1</td><td>0</td><td>1</td><td style="">0.069</td><td>0.125</td><td>0.069</td><td>0.194</td><td>-0.088</td><td>-60.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.40</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11255">강한울</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.47</td><td>18</td><td>-0.47</td><td>0.01</td><td>25</td><td>22</td><td>21</td><td>1</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td><td>1</td><td>3</td><td>1</td><td style="">0.095</td><td>0.091</td><td>0.095</td><td>0.186</td><td>-0.114</td><td>-81.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.47</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15036">김재혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.49</td><td>35</td><td>-0.53</td><td>0.04</td><td>54</td><td>54</td><td>49</td><td>6</td><td>9</td><td>2</td><td>1</td><td>0</td><td>13</td><td>6</td><td>2</td><td>2</td><td>3</td><td>0</td><td>0</td><td>19</td><td>2</td><td>0</td><td>2</td><td style="">0.184</td><td>0.222</td><td>0.265</td><td>0.487</td><td>0.017</td><td>11.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.49</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14867">김현준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.58</td><td>79</td><td>-0.83</td><td>0.25</td><td>205</td><td>201</td><td>183</td><td>23</td><td>41</td><td>10</td><td>1</td><td>0</td><td>53</td><td>11</td><td>2</td><td>0</td><td>11</td><td>4</td><td>0</td><td>49</td><td>4</td><td>4</td><td>3</td><td style="">0.224</td><td>0.279</td><td>0.290</td><td>0.569</td><td>0.059</td><td>41.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.58</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12988">안주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.92</td><td>82</td><td>-0.57</td><td>-0.35</td><td>166</td><td>154</td><td>142</td><td>24</td><td>31</td><td>2</td><td>0</td><td>0</td><td>33</td><td>8</td><td>4</td><td>2</td><td>11</td><td>1</td><td>0</td><td>39</td><td>3</td><td>12</td><td>0</td><td style="">0.218</td><td>0.279</td><td>0.232</td><td>0.511</td><td>0.041</td><td>29.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.92</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10106">최정</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.55</td><td>129</td><td>4.65</td><td>-0.09</td><td>550</td><td>550</td><td>468</td><td>93</td><td>136</td><td>27</td><td>2</td><td>37</td><td>278</td><td>107</td><td>5</td><td>1</td><td>55</td><td>20</td><td>1</td><td>114</td><td>10</td><td>0</td><td>7</td><td style="">0.291</td><td>0.384</td><td>0.594</td><td>0.978</td><td>0.202</td><td>145.9</td><td style="background-color:#F3F3F3; font-weight:bold;">4.55</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15530">에레디아</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.42</td><td>136</td><td>4.09</td><td>0.33</td><td>591</td><td>588</td><td>541</td><td>82</td><td>195</td><td>31</td><td>1</td><td>21</td><td>291</td><td>118</td><td>4</td><td>3</td><td>28</td><td>13</td><td>3</td><td>73</td><td>12</td><td>0</td><td>9</td><td style="">0.360</td><td>0.399</td><td>0.538</td><td>0.937</td><td>0.191</td><td>137.2</td><td style="background-color:#F3F3F3; font-weight:bold;">4.42</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12922">박성한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.60</td><td>137</td><td>3.50</td><td>0.10</td><td>564</td><td>559</td><td>489</td><td>78</td><td>147</td><td>24</td><td>0</td><td>10</td><td>201</td><td>67</td><td>13</td><td>3</td><td>64</td><td>2</td><td>3</td><td>86</td><td>11</td><td>3</td><td>6</td><td style="">0.301</td><td>0.380</td><td>0.411</td><td>0.791</td><td>0.145</td><td>104.0</td><td style="background-color:#F3F3F3; font-weight:bold;">3.60</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16042">정준재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.80</td><td>88</td><td>1.52</td><td>0.28</td><td>240</td><td>237</td><td>215</td><td>40</td><td>66</td><td>8</td><td>5</td><td>1</td><td>87</td><td>23</td><td>16</td><td>5</td><td>19</td><td>3</td><td>0</td><td>49</td><td>3</td><td>3</td><td>0</td><td style="">0.307</td><td>0.371</td><td>0.405</td><td>0.776</td><td>0.143</td><td>103.2</td><td style="background-color:#F3F3F3; font-weight:bold;">1.80</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14587">최지훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.76</td><td>125</td><td>2.03</td><td>-0.27</td><td>543</td><td>537</td><td>483</td><td>89</td><td>133</td><td>22</td><td>7</td><td>11</td><td>202</td><td>49</td><td>32</td><td>5</td><td>50</td><td>2</td><td>0</td><td>71</td><td>5</td><td>6</td><td>2</td><td style="">0.275</td><td>0.345</td><td>0.418</td><td>0.763</td><td>0.128</td><td>92.2</td><td style="background-color:#F3F3F3; font-weight:bold;">1.76</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10312">이지영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.53</td><td>123</td><td>0.96</td><td>0.57</td><td>432</td><td>425</td><td>398</td><td>45</td><td>111</td><td>11</td><td>1</td><td>5</td><td>139</td><td>50</td><td>8</td><td>1</td><td>18</td><td>7</td><td>0</td><td>35</td><td>10</td><td>7</td><td>2</td><td style="">0.279</td><td>0.320</td><td>0.349</td><td>0.669</td><td>0.097</td><td>70.1</td><td style="background-color:#F3F3F3; font-weight:bold;">1.53</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10249">오태곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.29</td><td>117</td><td>1.19</td><td>0.09</td><td>288</td><td>281</td><td>247</td><td>43</td><td>68</td><td>16</td><td>0</td><td>9</td><td>111</td><td>36</td><td>27</td><td>4</td><td>31</td><td>1</td><td>2</td><td>73</td><td>4</td><td>6</td><td>3</td><td style="">0.275</td><td>0.355</td><td>0.449</td><td>0.804</td><td>0.143</td><td>102.4</td><td style="background-color:#F3F3F3; font-weight:bold;">1.29</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14888">추신수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.67</td><td>78</td><td>0.64</td><td>0.02</td><td>302</td><td>300</td><td>253</td><td>40</td><td>71</td><td>14</td><td>1</td><td>5</td><td>102</td><td>37</td><td>5</td><td>1</td><td>37</td><td>4</td><td>0</td><td>68</td><td>2</td><td>2</td><td>6</td><td style="">0.281</td><td>0.373</td><td>0.403</td><td>0.776</td><td>0.143</td><td>102.0</td><td style="background-color:#F3F3F3; font-weight:bold;">0.67</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13128">최준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.17</td><td>18</td><td>0.28</td><td>-0.11</td><td>34</td><td>34</td><td>25</td><td>2</td><td>6</td><td>2</td><td>0</td><td>0</td><td>8</td><td>5</td><td>0</td><td>0</td><td>9</td><td>0</td><td>0</td><td>8</td><td>0</td><td>0</td><td>0</td><td style="">0.240</td><td>0.441</td><td>0.320</td><td>0.761</td><td>0.171</td><td>126.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.17</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13195">최상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.12</td><td>43</td><td>-0.01</td><td>0.13</td><td>13</td><td>13</td><td>12</td><td>9</td><td>2</td><td>2</td><td>0</td><td>0</td><td>4</td><td>1</td><td>2</td><td>1</td><td>0</td><td>1</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td style="">0.167</td><td>0.231</td><td>0.333</td><td>0.564</td><td>0.058</td><td>42.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.12</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16038">박지환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.09</td><td>76</td><td>0.49</td><td>-0.40</td><td>249</td><td>246</td><td>228</td><td>33</td><td>63</td><td>9</td><td>2</td><td>4</td><td>88</td><td>21</td><td>8</td><td>3</td><td>12</td><td>3</td><td>0</td><td>61</td><td>3</td><td>3</td><td>3</td><td style="">0.276</td><td>0.317</td><td>0.386</td><td>0.703</td><td>0.106</td><td>75.2</td><td style="background-color:#F3F3F3; font-weight:bold;">0.09</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13228">한두솔</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14805">조병현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>3</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11236">박민호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15461">이로운</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>3</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14153">채현우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14584">현원회</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.02</td><td>1</td><td>-0.02</td><td>0.00</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-130.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.02</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10783">문승원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>6</td><td>-0.03</td><td>0.00</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-140.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14586">류효승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.05</td><td>1</td><td>-0.05</td><td>0.00</td><td>2</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-146.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.05</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14146">김창평</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.06</td><td>6</td><td>-0.10</td><td>0.04</td><td>9</td><td>9</td><td>7</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>2</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.222</td><td>0.000</td><td>0.222</td><td>-0.029</td><td>-22.1</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.06</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11351">최민창</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>7</td><td>-0.06</td><td>0.00</td><td>3</td><td>3</td><td>3</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-133.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12541">신범수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>11</td><td>-0.07</td><td>0.00</td><td>29</td><td>29</td><td>27</td><td>4</td><td>6</td><td>3</td><td>0</td><td>0</td><td>9</td><td>2</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td style="">0.222</td><td>0.276</td><td>0.333</td><td>0.609</td><td>0.074</td><td>51.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14806">조형우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.08</td><td>19</td><td>0.08</td><td>-0.16</td><td>38</td><td>38</td><td>33</td><td>4</td><td>8</td><td>0</td><td>0</td><td>0</td><td>8</td><td>4</td><td>0</td><td>0</td><td>1</td><td>4</td><td>0</td><td>6</td><td>0</td><td>0</td><td>0</td><td style="">0.242</td><td>0.342</td><td>0.242</td><td>0.584</td><td>0.094</td><td>66.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.08</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11148">강진성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.16</td><td>16</td><td>-0.26</td><td>0.10</td><td>31</td><td>30</td><td>27</td><td>4</td><td>5</td><td>0</td><td>0</td><td>0</td><td>5</td><td>2</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>5</td><td>0</td><td>1</td><td>0</td><td style="">0.185</td><td>0.267</td><td>0.185</td><td>0.452</td><td>0.022</td><td>16.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.16</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14151">최경모</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.21</td><td>50</td><td>-0.17</td><td>-0.04</td><td>50</td><td>43</td><td>35</td><td>12</td><td>6</td><td>0</td><td>0</td><td>0</td><td>6</td><td>0</td><td>6</td><td>3</td><td>8</td><td>0</td><td>0</td><td>7</td><td>2</td><td>7</td><td>0</td><td style="">0.171</td><td>0.326</td><td>0.171</td><td>0.497</td><td>0.062</td><td>45.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.21</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10815">한유섬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.23</td><td>132</td><td>0.43</td><td>-0.67</td><td>523</td><td>519</td><td>464</td><td>64</td><td>109</td><td>29</td><td>0</td><td>24</td><td>210</td><td>87</td><td>0</td><td>1</td><td>46</td><td>9</td><td>3</td><td>142</td><td>2</td><td>1</td><td>3</td><td style="">0.235</td><td>0.314</td><td>0.453</td><td>0.767</td><td>0.125</td><td>89.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.23</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16043">정현승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.25</td><td>23</td><td>-0.17</td><td>-0.08</td><td>31</td><td>31</td><td>29</td><td>1</td><td>7</td><td>0</td><td>0</td><td>1</td><td>10</td><td>4</td><td>1</td><td>0</td><td>2</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>0</td><td style="">0.241</td><td>0.290</td><td>0.345</td><td>0.635</td><td>0.076</td><td>53.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.25</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12622">김찬형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.26</td><td>5</td><td>-0.23</td><td>-0.03</td><td>9</td><td>9</td><td>9</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-139.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.26</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10707">김민식</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.26</td><td>45</td><td>-0.05</td><td>-0.21</td><td>126</td><td>122</td><td>106</td><td>10</td><td>22</td><td>5</td><td>0</td><td>1</td><td>30</td><td>10</td><td>0</td><td>0</td><td>16</td><td>0</td><td>0</td><td>33</td><td>2</td><td>4</td><td>0</td><td style="">0.208</td><td>0.311</td><td>0.283</td><td>0.594</td><td>0.079</td><td>56.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.26</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10636">김성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.49</td><td>71</td><td>0.03</td><td>-0.53</td><td>167</td><td>162</td><td>141</td><td>21</td><td>32</td><td>3</td><td>1</td><td>1</td><td>40</td><td>15</td><td>2</td><td>0</td><td>16</td><td>4</td><td>0</td><td>28</td><td>7</td><td>5</td><td>1</td><td style="">0.227</td><td>0.321</td><td>0.284</td><td>0.605</td><td>0.085</td><td>60.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.49</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14147">하재훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.74</td><td>107</td><td>0.11</td><td>-0.85</td><td>317</td><td>315</td><td>290</td><td>40</td><td>72</td><td>19</td><td>0</td><td>10</td><td>121</td><td>36</td><td>15</td><td>2</td><td>18</td><td>2</td><td>0</td><td>90</td><td>5</td><td>2</td><td>5</td><td style="">0.248</td><td>0.292</td><td>0.417</td><td>0.709</td><td>0.102</td><td>73.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.74</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14807">고명준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.76</td><td>106</td><td>-0.97</td><td>0.21</td><td>366</td><td>366</td><td>340</td><td>33</td><td>85</td><td>13</td><td>0</td><td>11</td><td>131</td><td>45</td><td>3</td><td>4</td><td>25</td><td>1</td><td>0</td><td>90</td><td>4</td><td>0</td><td>0</td><td style="">0.250</td><td>0.303</td><td>0.385</td><td>0.688</td><td>0.095</td><td>68.1</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.76</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12613">안상현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.80</td><td>37</td><td>-0.58</td><td>-0.22</td><td>75</td><td>74</td><td>70</td><td>3</td><td>12</td><td>1</td><td>0</td><td>0</td><td>13</td><td>2</td><td>1</td><td>1</td><td>4</td><td>0</td><td>0</td><td>14</td><td>0</td><td>1</td><td>0</td><td style="">0.171</td><td>0.216</td><td>0.186</td><td>0.402</td><td>-0.010</td><td>-7.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.80</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14699">전의산</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-1.35</td><td>34</td><td>-1.09</td><td>-0.26</td><td>63</td><td>63</td><td>57</td><td>3</td><td>5</td><td>0</td><td>0</td><td>1</td><td>8</td><td>3</td><td>0</td><td>1</td><td>5</td><td>0</td><td>0</td><td>15</td><td>3</td><td>0</td><td>1</td><td style="">0.088</td><td>0.159</td><td>0.140</td><td>0.299</td><td>-0.051</td><td>-37.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-1.35</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11137">박민우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.70</td><td>121</td><td>4.11</td><td>0.58</td><td>528</td><td>520</td><td>457</td><td>75</td><td>150</td><td>26</td><td>2</td><td>8</td><td>204</td><td>50</td><td>32</td><td>7</td><td>54</td><td>9</td><td>4</td><td>79</td><td>5</td><td>4</td><td>4</td><td style="">0.328</td><td>0.406</td><td>0.446</td><td>0.852</td><td>0.172</td><td>129.6</td><td style="background-color:#F3F3F3; font-weight:bold;">4.70</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16066">데이비슨</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.98</td><td>131</td><td>4.26</td><td>-0.28</td><td>567</td><td>565</td><td>504</td><td>90</td><td>154</td><td>25</td><td>1</td><td>46</td><td>319</td><td>119</td><td>0</td><td>1</td><td>39</td><td>17</td><td>5</td><td>142</td><td>12</td><td>0</td><td>7</td><td style="">0.306</td><td>0.370</td><td>0.633</td><td>1.003</td><td>0.203</td><td>153.9</td><td style="background-color:#F3F3F3; font-weight:bold;">3.98</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11172">권희동</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.77</td><td>123</td><td>3.48</td><td>0.29</td><td>511</td><td>509</td><td>416</td><td>66</td><td>125</td><td>22</td><td>1</td><td>13</td><td>188</td><td>77</td><td>4</td><td>0</td><td>77</td><td>10</td><td>1</td><td>63</td><td>10</td><td>2</td><td>6</td><td style="">0.300</td><td>0.417</td><td>0.452</td><td>0.869</td><td>0.182</td><td>137.9</td><td style="background-color:#F3F3F3; font-weight:bold;">3.77</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14765">김주원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.75</td><td>134</td><td>3.07</td><td>0.68</td><td>475</td><td>466</td><td>385</td><td>61</td><td>97</td><td>18</td><td>2</td><td>9</td><td>146</td><td>49</td><td>16</td><td>6</td><td>51</td><td>25</td><td>1</td><td>111</td><td>5</td><td>9</td><td>5</td><td style="">0.252</td><td>0.371</td><td>0.379</td><td>0.750</td><td>0.143</td><td>108.4</td><td style="background-color:#F3F3F3; font-weight:bold;">3.75</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10189">박건우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.64</td><td>89</td><td>2.96</td><td>-0.32</td><td>362</td><td>360</td><td>323</td><td>58</td><td>111</td><td>23</td><td>1</td><td>13</td><td>175</td><td>53</td><td>4</td><td>0</td><td>33</td><td>4</td><td>3</td><td>54</td><td>7</td><td>0</td><td>2</td><td style="">0.344</td><td>0.409</td><td>0.542</td><td>0.951</td><td>0.198</td><td>150.1</td><td style="background-color:#F3F3F3; font-weight:bold;">2.64</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14785">김휘집</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.99</td><td>89</td><td>1.52</td><td>0.47</td><td>366</td><td>364</td><td>314</td><td>54</td><td>86</td><td>15</td><td>0</td><td>11</td><td>134</td><td>48</td><td>4</td><td>3</td><td>37</td><td>7</td><td>0</td><td>70</td><td>7</td><td>2</td><td>6</td><td style="">0.274</td><td>0.357</td><td>0.427</td><td>0.784</td><td>0.141</td><td>106.3</td><td style="background-color:#F3F3F3; font-weight:bold;">1.99</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14220">서호철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.39</td><td>141</td><td>1.28</td><td>0.11</td><td>567</td><td>561</td><td>512</td><td>68</td><td>146</td><td>19</td><td>3</td><td>10</td><td>201</td><td>61</td><td>1</td><td>3</td><td>30</td><td>16</td><td>0</td><td>101</td><td>15</td><td>6</td><td>3</td><td style="">0.285</td><td>0.342</td><td>0.393</td><td>0.735</td><td>0.123</td><td>93.3</td><td style="background-color:#F3F3F3; font-weight:bold;">1.39</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14221">최정원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.62</td><td>65</td><td>0.55</td><td>0.06</td><td>155</td><td>154</td><td>131</td><td>33</td><td>37</td><td>5</td><td>0</td><td>1</td><td>45</td><td>14</td><td>7</td><td>3</td><td>17</td><td>4</td><td>0</td><td>34</td><td>1</td><td>1</td><td>2</td><td style="">0.282</td><td>0.377</td><td>0.344</td><td>0.721</td><td>0.131</td><td>99.0</td><td style="background-color:#F3F3F3; font-weight:bold;">0.62</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10891">박세혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.48</td><td>82</td><td>0.69</td><td>-0.21</td><td>171</td><td>166</td><td>148</td><td>21</td><td>39</td><td>9</td><td>0</td><td>1</td><td>51</td><td>10</td><td>4</td><td>0</td><td>14</td><td>3</td><td>0</td><td>43</td><td>3</td><td>5</td><td>1</td><td style="">0.264</td><td>0.337</td><td>0.345</td><td>0.682</td><td>0.108</td><td>82.4</td><td style="background-color:#F3F3F3; font-weight:bold;">0.48</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13081">김형준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.42</td><td>119</td><td>0.31</td><td>0.11</td><td>414</td><td>407</td><td>354</td><td>39</td><td>69</td><td>12</td><td>0</td><td>17</td><td>132</td><td>50</td><td>0</td><td>0</td><td>45</td><td>2</td><td>0</td><td>144</td><td>6</td><td>7</td><td>6</td><td style="">0.195</td><td>0.285</td><td>0.373</td><td>0.658</td><td>0.086</td><td>64.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.42</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13261">천재환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.37</td><td>89</td><td>0.56</td><td>-0.20</td><td>236</td><td>233</td><td>215</td><td>31</td><td>61</td><td>9</td><td>1</td><td>5</td><td>87</td><td>33</td><td>8</td><td>2</td><td>13</td><td>4</td><td>0</td><td>52</td><td>7</td><td>3</td><td>1</td><td style="">0.284</td><td>0.335</td><td>0.405</td><td>0.740</td><td>0.121</td><td>91.5</td><td style="background-color:#F3F3F3; font-weight:bold;">0.37</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11329">안중열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.23</td><td>10</td><td>0.29</td><td>-0.06</td><td>25</td><td>25</td><td>21</td><td>5</td><td>6</td><td>1</td><td>0</td><td>2</td><td>13</td><td>4</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>1</td><td style="">0.286</td><td>0.360</td><td>0.619</td><td>0.979</td><td>0.187</td><td>138.4</td><td style="background-color:#F3F3F3; font-weight:bold;">0.23</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14172">송승환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.09</td><td>3</td><td>-0.05</td><td>0.14</td><td>5</td><td>5</td><td>5</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.200</td><td>0.200</td><td>0.200</td><td>0.400</td><td>-0.022</td><td>-16.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.09</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13082">오영수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.08</td><td>20</td><td>-0.04</td><td>0.12</td><td>34</td><td>34</td><td>30</td><td>4</td><td>6</td><td>0</td><td>0</td><td>3</td><td>15</td><td>5</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>6</td><td>0</td><td>0</td><td>1</td><td style="">0.200</td><td>0.265</td><td>0.500</td><td>0.765</td><td>0.108</td><td>80.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.08</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10261">손아섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.08</td><td>84</td><td>-0.23</td><td>0.31</td><td>355</td><td>353</td><td>333</td><td>45</td><td>95</td><td>16</td><td>0</td><td>7</td><td>132</td><td>50</td><td>6</td><td>2</td><td>16</td><td>0</td><td>0</td><td>65</td><td>1</td><td>2</td><td>4</td><td style="">0.285</td><td>0.314</td><td>0.396</td><td>0.710</td><td>0.103</td><td>78.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.08</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12560">도태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.06</td><td>100</td><td>-0.24</td><td>0.30</td><td>181</td><td>177</td><td>145</td><td>20</td><td>31</td><td>4</td><td>0</td><td>0</td><td>35</td><td>15</td><td>1</td><td>0</td><td>24</td><td>6</td><td>0</td><td>29</td><td>5</td><td>4</td><td>2</td><td style="">0.214</td><td>0.345</td><td>0.241</td><td>0.586</td><td>0.092</td><td>69.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.06</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14155">송명기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14764">한재승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14747">김재열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11355">류진욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13088">김영규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>0</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15452">신용석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.06</td><td>2</td><td>-0.07</td><td>0.00</td><td>2</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-136.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.06</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14716">김한별</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>40</td><td>0.24</td><td>-0.31</td><td>50</td><td>50</td><td>44</td><td>8</td><td>14</td><td>1</td><td>0</td><td>0</td><td>15</td><td>3</td><td>0</td><td>0</td><td>2</td><td>4</td><td>0</td><td>9</td><td>2</td><td>0</td><td>0</td><td style="">0.318</td><td>0.400</td><td>0.341</td><td>0.741</td><td>0.148</td><td>109.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14659">한재환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.08</td><td>7</td><td>-0.05</td><td>-0.03</td><td>9</td><td>9</td><td>9</td><td>1</td><td>2</td><td>1</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td style="">0.222</td><td>0.222</td><td>0.333</td><td>0.555</td><td>0.036</td><td>26.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.08</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14661">박영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.09</td><td>19</td><td>0.13</td><td>-0.23</td><td>7</td><td>7</td><td>6</td><td>3</td><td>3</td><td>2</td><td>0</td><td>0</td><td>5</td><td>1</td><td>2</td><td>1</td><td>1</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td style="">0.500</td><td>0.571</td><td>0.833</td><td>1.404</td><td>0.374</td><td>278.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.09</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16058">김세훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.10</td><td>7</td><td>-0.06</td><td>-0.05</td><td>5</td><td>5</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.200</td><td>0.000</td><td>0.200</td><td>-0.045</td><td>-35.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.10</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14222">김범준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.15</td><td>5</td><td>-0.15</td><td>0.00</td><td>5</td><td>5</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-142.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.15</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12903">김수윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.16</td><td>9</td><td>-0.07</td><td>-0.08</td><td>10</td><td>10</td><td>9</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td style="">0.222</td><td>0.300</td><td>0.222</td><td>0.522</td><td>0.050</td><td>37.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.16</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15451">박한결</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.28</td><td>28</td><td>-0.07</td><td>-0.21</td><td>71</td><td>71</td><td>65</td><td>8</td><td>12</td><td>1</td><td>0</td><td>7</td><td>34</td><td>14</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>29</td><td>1</td><td>0</td><td>0</td><td style="">0.185</td><td>0.254</td><td>0.523</td><td>0.777</td><td>0.110</td><td>84.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.28</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14597">박시원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.46</td><td>55</td><td>-0.26</td><td>-0.20</td><td>158</td><td>156</td><td>141</td><td>17</td><td>33</td><td>5</td><td>1</td><td>2</td><td>46</td><td>17</td><td>3</td><td>0</td><td>14</td><td>0</td><td>0</td><td>46</td><td>2</td><td>2</td><td>1</td><td style="">0.234</td><td>0.301</td><td>0.326</td><td>0.627</td><td>0.080</td><td>60.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.46</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11153">김성욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.49</td><td>129</td><td>-0.10</td><td>-0.38</td><td>412</td><td>409</td><td>358</td><td>55</td><td>73</td><td>8</td><td>2</td><td>17</td><td>136</td><td>60</td><td>10</td><td>4</td><td>31</td><td>15</td><td>0</td><td>79</td><td>7</td><td>3</td><td>5</td><td style="">0.204</td><td>0.291</td><td>0.380</td><td>0.671</td><td>0.095</td><td>71.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.49</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13250">한석현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.52</td><td>40</td><td>-0.22</td><td>-0.30</td><td>76</td><td>76</td><td>73</td><td>10</td><td>18</td><td>4</td><td>1</td><td>0</td><td>24</td><td>3</td><td>2</td><td>1</td><td>2</td><td>1</td><td>0</td><td>22</td><td>2</td><td>0</td><td>0</td><td style="">0.247</td><td>0.276</td><td>0.329</td><td>0.605</td><td>0.067</td><td>50.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.52</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11087">강승호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.71</td><td>140</td><td>2.90</td><td>0.81</td><td>566</td><td>561</td><td>521</td><td>81</td><td>146</td><td>34</td><td>7</td><td>18</td><td>248</td><td>81</td><td>16</td><td>5</td><td>32</td><td>7</td><td>4</td><td>158</td><td>8</td><td>2</td><td>4</td><td style="">0.280</td><td>0.328</td><td>0.476</td><td>0.804</td><td>0.136</td><td>104.3</td><td style="background-color:#F3F3F3; font-weight:bold;">3.71</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10165">양의지</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.21</td><td>119</td><td>3.40</td><td>-0.19</td><td>485</td><td>482</td><td>430</td><td>57</td><td>135</td><td>18</td><td>1</td><td>17</td><td>206</td><td>94</td><td>2</td><td>1</td><td>40</td><td>9</td><td>5</td><td>56</td><td>13</td><td>0</td><td>6</td><td style="">0.314</td><td>0.379</td><td>0.479</td><td>0.858</td><td>0.164</td><td>125.3</td><td style="background-color:#F3F3F3; font-weight:bold;">3.21</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10184">허경민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.20</td><td>115</td><td>2.99</td><td>0.21</td><td>477</td><td>477</td><td>417</td><td>69</td><td>129</td><td>28</td><td>0</td><td>7</td><td>178</td><td>61</td><td>5</td><td>1</td><td>36</td><td>18</td><td>0</td><td>25</td><td>8</td><td>0</td><td>6</td><td style="">0.309</td><td>0.384</td><td>0.427</td><td>0.811</td><td>0.160</td><td>122.0</td><td style="background-color:#F3F3F3; font-weight:bold;">3.20</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10643">김재환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.09</td><td>136</td><td>3.37</td><td>-0.28</td><td>552</td><td>549</td><td>474</td><td>78</td><td>134</td><td>28</td><td>0</td><td>29</td><td>249</td><td>92</td><td>1</td><td>1</td><td>63</td><td>6</td><td>3</td><td>168</td><td>8</td><td>0</td><td>9</td><td style="">0.283</td><td>0.368</td><td>0.525</td><td>0.893</td><td>0.173</td><td>132.0</td><td style="background-color:#F3F3F3; font-weight:bold;">3.09</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10195">정수빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.97</td><td>136</td><td>2.52</td><td>0.45</td><td>608</td><td>598</td><td>510</td><td>95</td><td>145</td><td>21</td><td>3</td><td>4</td><td>184</td><td>47</td><td>52</td><td>13</td><td>71</td><td>9</td><td>1</td><td>72</td><td>8</td><td>10</td><td>8</td><td style="">0.284</td><td>0.376</td><td>0.361</td><td>0.737</td><td>0.131</td><td>100.2</td><td style="background-color:#F3F3F3; font-weight:bold;">2.97</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11213">양석환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.17</td><td>142</td><td>1.79</td><td>0.37</td><td>593</td><td>592</td><td>533</td><td>83</td><td>131</td><td>25</td><td>1</td><td>34</td><td>260</td><td>107</td><td>5</td><td>3</td><td>49</td><td>7</td><td>1</td><td>128</td><td>15</td><td>1</td><td>3</td><td style="">0.246</td><td>0.316</td><td>0.488</td><td>0.804</td><td>0.136</td><td>104.5</td><td style="background-color:#F3F3F3; font-weight:bold;">2.17</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15000">라모스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.68</td><td>80</td><td>1.90</td><td>-0.22</td><td>348</td><td>346</td><td>311</td><td>43</td><td>95</td><td>19</td><td>3</td><td>10</td><td>150</td><td>48</td><td>3</td><td>3</td><td>27</td><td>3</td><td>1</td><td>60</td><td>5</td><td>1</td><td>6</td><td style="">0.305</td><td>0.360</td><td>0.482</td><td>0.842</td><td>0.154</td><td>119.6</td><td style="background-color:#F3F3F3; font-weight:bold;">1.68</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16158">제러드</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.59</td><td>38</td><td>2.09</td><td>-0.50</td><td>169</td><td>169</td><td>144</td><td>29</td><td>47</td><td>16</td><td>1</td><td>10</td><td>95</td><td>39</td><td>4</td><td>0</td><td>21</td><td>3</td><td>0</td><td>35</td><td>0</td><td>0</td><td>1</td><td style="">0.326</td><td>0.420</td><td>0.660</td><td>1.080</td><td>0.241</td><td>183.7</td><td style="background-color:#F3F3F3; font-weight:bold;">1.59</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12522">박준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.47</td><td>65</td><td>0.91</td><td>0.56</td><td>212</td><td>211</td><td>186</td><td>25</td><td>42</td><td>9</td><td>2</td><td>7</td><td>76</td><td>28</td><td>2</td><td>0</td><td>21</td><td>3</td><td>0</td><td>58</td><td>3</td><td>1</td><td>1</td><td style="">0.226</td><td>0.313</td><td>0.409</td><td>0.722</td><td>0.114</td><td>86.6</td><td style="background-color:#F3F3F3; font-weight:bold;">1.47</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12549">김기연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.16</td><td>95</td><td>0.85</td><td>0.31</td><td>283</td><td>279</td><td>252</td><td>31</td><td>70</td><td>10</td><td>0</td><td>5</td><td>95</td><td>31</td><td>0</td><td>2</td><td>22</td><td>2</td><td>0</td><td>47</td><td>5</td><td>4</td><td>3</td><td style="">0.278</td><td>0.337</td><td>0.377</td><td>0.714</td><td>0.113</td><td>86.7</td><td style="background-color:#F3F3F3; font-weight:bold;">1.16</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12894">이유찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.01</td><td>103</td><td>0.67</td><td>0.33</td><td>262</td><td>255</td><td>231</td><td>39</td><td>64</td><td>11</td><td>0</td><td>3</td><td>84</td><td>23</td><td>16</td><td>6</td><td>22</td><td>1</td><td>0</td><td>51</td><td>9</td><td>7</td><td>1</td><td style="">0.277</td><td>0.341</td><td>0.364</td><td>0.705</td><td>0.115</td><td>87.9</td><td style="background-color:#F3F3F3; font-weight:bold;">1.01</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12524">조수행</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.97</td><td>130</td><td>0.40</td><td>0.57</td><td>382</td><td>368</td><td>328</td><td>60</td><td>87</td><td>5</td><td>2</td><td>0</td><td>96</td><td>30</td><td>64</td><td>8</td><td>33</td><td>3</td><td>1</td><td>53</td><td>2</td><td>14</td><td>4</td><td style="">0.265</td><td>0.334</td><td>0.293</td><td>0.627</td><td>0.085</td><td>65.5</td><td style="background-color:#F3F3F3; font-weight:bold;">0.97</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10174">김재호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.68</td><td>57</td><td>0.99</td><td>-0.31</td><td>154</td><td>147</td><td>126</td><td>20</td><td>38</td><td>5</td><td>0</td><td>1</td><td>46</td><td>11</td><td>0</td><td>0</td><td>19</td><td>1</td><td>0</td><td>23</td><td>4</td><td>7</td><td>1</td><td style="">0.302</td><td>0.395</td><td>0.365</td><td>0.760</td><td>0.144</td><td>112.2</td><td style="background-color:#F3F3F3; font-weight:bold;">0.68</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16072">전다민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.30</td><td>25</td><td>0.34</td><td>-0.04</td><td>34</td><td>34</td><td>27</td><td>10</td><td>9</td><td>2</td><td>0</td><td>0</td><td>11</td><td>1</td><td>1</td><td>1</td><td>7</td><td>0</td><td>0</td><td>8</td><td>0</td><td>0</td><td>0</td><td style="">0.333</td><td>0.471</td><td>0.407</td><td>0.878</td><td>0.202</td><td>156.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.30</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12970">김민혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.19</td><td>5</td><td>0.19</td><td>0.00</td><td>8</td><td>8</td><td>5</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td><td>4</td><td>2</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td style="">0.200</td><td>0.500</td><td>0.800</td><td>1.300</td><td>0.303</td><td>237.7</td><td style="background-color:#F3F3F3; font-weight:bold;">0.19</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16076">류현준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.12</td><td>2</td><td>0.11</td><td>0.01</td><td>3</td><td>3</td><td>3</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">0.667</td><td>0.667</td><td>1.000</td><td>1.667</td><td>0.487</td><td>380.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.12</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14738">양찬열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.09</td><td>11</td><td>0.02</td><td>0.07</td><td>12</td><td>12</td><td>8</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.125</td><td>0.417</td><td>0.125</td><td>0.542</td><td>0.122</td><td>96.2</td><td style="background-color:#F3F3F3; font-weight:bold;">0.09</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12606">홍성호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.07</td><td>15</td><td>0.03</td><td>0.03</td><td>15</td><td>15</td><td>14</td><td>0</td><td>4</td><td>2</td><td>0</td><td>0</td><td>6</td><td>1</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>0</td><td style="">0.286</td><td>0.333</td><td>0.429</td><td>0.762</td><td>0.129</td><td>100.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.07</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12523">서예일</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.03</td><td>24</td><td>-0.09</td><td>0.12</td><td>20</td><td>20</td><td>18</td><td>2</td><td>4</td><td>0</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td style="">0.222</td><td>0.300</td><td>0.222</td><td>0.522</td><td>0.050</td><td>38.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.03</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16067">김택연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14770">최승용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12847">김명신</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>3</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13072">김민규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14173">이교훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>4</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14769">김동주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13071">정철원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12568">이영하</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15127">최지강</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11300">박정수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15099">이병헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10696">홍건희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>4</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13268">김호준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10690">김강률</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12850">박치국</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>3</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14737">오명진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>2</td><td>0.01</td><td>-0.02</td><td>2</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.500</td><td>0.000</td><td>0.500</td><td>0.173</td><td>130.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16069">임종성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>1</td><td>-0.06</td><td>0.04</td><td>4</td><td>4</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.250</td><td>0.000</td><td>0.250</td><td>-0.008</td><td>-6.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14570">장규빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.02</td><td>3</td><td>-0.02</td><td>0.00</td><td>4</td><td>4</td><td>4</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.250</td><td>0.250</td><td>0.250</td><td>0.500</td><td>0.020</td><td>15.1</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.02</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13665">권휘</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>1</td><td>-0.03</td><td>0.00</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-140.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11328">안승한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>4</td><td>-0.05</td><td>0.02</td><td>5</td><td>5</td><td>5</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.200</td><td>0.200</td><td>0.200</td><td>0.400</td><td>-0.022</td><td>-17.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16068">여동건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>9</td><td>-0.02</td><td>-0.01</td><td>11</td><td>11</td><td>10</td><td>2</td><td>4</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>3</td><td>0</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.400</td><td>0.455</td><td>0.400</td><td>0.855</td><td>0.181</td><td>140.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15512">윤준호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.08</td><td>3</td><td>-0.02</td><td>-0.06</td><td>4</td><td>4</td><td>4</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.250</td><td>0.250</td><td>0.250</td><td>0.500</td><td>0.020</td><td>15.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.08</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11097">장승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.10</td><td>9</td><td>-0.07</td><td>-0.04</td><td>23</td><td>22</td><td>20</td><td>1</td><td>4</td><td>2</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>5</td><td>0</td><td>1</td><td>0</td><td style="">0.200</td><td>0.273</td><td>0.300</td><td>0.573</td><td>0.061</td><td>43.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.10</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15515">박민준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.14</td><td>5</td><td>-0.12</td><td>-0.01</td><td>5</td><td>5</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-144.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.14</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13073">전민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.32</td><td>100</td><td>-0.39</td><td>0.07</td><td>276</td><td>272</td><td>248</td><td>34</td><td>61</td><td>5</td><td>1</td><td>2</td><td>74</td><td>32</td><td>7</td><td>3</td><td>17</td><td>4</td><td>1</td><td>53</td><td>8</td><td>4</td><td>3</td><td style="">0.246</td><td>0.301</td><td>0.298</td><td>0.599</td><td>0.071</td><td>54.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.32</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11198">박계범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.33</td><td>24</td><td>0.11</td><td>-0.44</td><td>20</td><td>20</td><td>15</td><td>5</td><td>3</td><td>1</td><td>0</td><td>0</td><td>4</td><td>0</td><td>1</td><td>0</td><td>5</td><td>0</td><td>0</td><td>7</td><td>2</td><td>0</td><td>0</td><td style="">0.200</td><td>0.400</td><td>0.267</td><td>0.667</td><td>0.135</td><td>102.1</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.33</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11098">김인태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.39</td><td>10</td><td>-0.24</td><td>-0.15</td><td>26</td><td>26</td><td>23</td><td>3</td><td>4</td><td>0</td><td>0</td><td>1</td><td>7</td><td>2</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>7</td><td>1</td><td>0</td><td>1</td><td style="">0.174</td><td>0.231</td><td>0.304</td><td>0.535</td><td>0.031</td><td>22.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.39</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14170">김대한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.69</td><td>61</td><td>-0.70</td><td>0.01</td><td>89</td><td>87</td><td>75</td><td>10</td><td>10</td><td>1</td><td>0</td><td>1</td><td>14</td><td>7</td><td>1</td><td>1</td><td>8</td><td>2</td><td>0</td><td>26</td><td>1</td><td>2</td><td>2</td><td style="">0.133</td><td>0.230</td><td>0.187</td><td>0.417</td><td>0.007</td><td>5.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.69</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14175">김태근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.70</td><td>43</td><td>-0.50</td><td>-0.20</td><td>27</td><td>26</td><td>23</td><td>7</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>1</td><td>0</td><td>3</td><td>0</td><td>10</td><td>0</td><td>1</td><td>0</td><td style="">0.087</td><td>0.192</td><td>0.087</td><td>0.279</td><td>-0.028</td><td>-21.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.70</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11376">송성문</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">6.13</td><td>142</td><td>5.83</td><td>0.29</td><td>602</td><td>601</td><td>527</td><td>88</td><td>179</td><td>29</td><td>4</td><td>19</td><td>273</td><td>104</td><td>21</td><td>0</td><td>64</td><td>3</td><td>2</td><td>82</td><td>5</td><td>0</td><td>8</td><td style="">0.340</td><td>0.409</td><td>0.518</td><td>0.927</td><td>0.191</td><td>148.9</td><td style="background-color:#F3F3F3; font-weight:bold;">6.13</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12905">김혜성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.16</td><td>127</td><td>4.47</td><td>0.69</td><td>567</td><td>565</td><td>509</td><td>90</td><td>166</td><td>26</td><td>4</td><td>11</td><td>233</td><td>75</td><td>30</td><td>6</td><td>47</td><td>4</td><td>2</td><td>62</td><td>6</td><td>0</td><td>7</td><td style="">0.326</td><td>0.383</td><td>0.458</td><td>0.841</td><td>0.160</td><td>124.1</td><td style="background-color:#F3F3F3; font-weight:bold;">5.16</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15652">도슨</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.17</td><td>95</td><td>3.07</td><td>0.10</td><td>429</td><td>429</td><td>382</td><td>69</td><td>126</td><td>31</td><td>2</td><td>11</td><td>194</td><td>57</td><td>2</td><td>2</td><td>39</td><td>6</td><td>0</td><td>54</td><td>10</td><td>0</td><td>2</td><td style="">0.330</td><td>0.399</td><td>0.508</td><td>0.907</td><td>0.187</td><td>145.9</td><td style="background-color:#F3F3F3; font-weight:bold;">3.17</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14591">이주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.96</td><td>115</td><td>1.72</td><td>0.25</td><td>537</td><td>536</td><td>473</td><td>82</td><td>126</td><td>19</td><td>3</td><td>13</td><td>190</td><td>60</td><td>6</td><td>0</td><td>49</td><td>14</td><td>1</td><td>119</td><td>4</td><td>0</td><td>1</td><td style="">0.266</td><td>0.352</td><td>0.402</td><td>0.754</td><td>0.133</td><td>103.6</td><td style="background-color:#F3F3F3; font-weight:bold;">1.96</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10035">이용규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.42</td><td>60</td><td>1.43</td><td>-0.01</td><td>227</td><td>224</td><td>183</td><td>27</td><td>56</td><td>5</td><td>2</td><td>1</td><td>68</td><td>12</td><td>2</td><td>2</td><td>31</td><td>9</td><td>0</td><td>33</td><td>4</td><td>3</td><td>1</td><td style="">0.306</td><td>0.429</td><td>0.372</td><td>0.801</td><td>0.172</td><td>136.7</td><td style="background-color:#F3F3F3; font-weight:bold;">1.42</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12516">이형종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.36</td><td>35</td><td>0.28</td><td>0.08</td><td>126</td><td>125</td><td>102</td><td>19</td><td>22</td><td>3</td><td>0</td><td>4</td><td>37</td><td>19</td><td>1</td><td>0</td><td>22</td><td>1</td><td>1</td><td>27</td><td>1</td><td>1</td><td>0</td><td style="">0.216</td><td>0.360</td><td>0.363</td><td>0.723</td><td>0.128</td><td>100.7</td><td style="background-color:#F3F3F3; font-weight:bold;">0.36</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15472">김건희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.22</td><td>83</td><td>0.37</td><td>-0.16</td><td>283</td><td>283</td><td>261</td><td>27</td><td>67</td><td>15</td><td>0</td><td>9</td><td>109</td><td>38</td><td>0</td><td>0</td><td>18</td><td>0</td><td>0</td><td>82</td><td>7</td><td>0</td><td>4</td><td style="">0.257</td><td>0.300</td><td>0.418</td><td>0.718</td><td>0.103</td><td>79.2</td><td style="background-color:#F3F3F3; font-weight:bold;">0.22</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14785">김휘집</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.20</td><td>51</td><td>0.10</td><td>0.10</td><td>196</td><td>193</td><td>174</td><td>24</td><td>40</td><td>9</td><td>1</td><td>5</td><td>66</td><td>25</td><td>0</td><td>0</td><td>15</td><td>3</td><td>1</td><td>49</td><td>9</td><td>2</td><td>2</td><td style="">0.230</td><td>0.299</td><td>0.379</td><td>0.678</td><td>0.095</td><td>73.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.20</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15132">박수종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.05</td><td>80</td><td>-0.05</td><td>0.11</td><td>148</td><td>144</td><td>129</td><td>23</td><td>33</td><td>5</td><td>1</td><td>0</td><td>40</td><td>6</td><td>3</td><td>0</td><td>13</td><td>2</td><td>0</td><td>17</td><td>4</td><td>4</td><td>0</td><td style="">0.256</td><td>0.333</td><td>0.310</td><td>0.643</td><td>0.097</td><td>73.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.05</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14695">신준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16127">김연주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>4</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12860">오석주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>0</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10437">문성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12858">김재웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16123">김윤하</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16133">박범준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12854">양지율</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14681">김동욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15067">주승우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>5</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13092">김선기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11161">원종현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14131">윤정현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16135">심휘윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>1</td><td>-0.01</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15479">박성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.02</td><td>12</td><td>0.05</td><td>-0.07</td><td>11</td><td>11</td><td>9</td><td>1</td><td>2</td><td>1</td><td>0</td><td>0</td><td>3</td><td>2</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.222</td><td>0.364</td><td>0.333</td><td>0.697</td><td>0.137</td><td>110.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.02</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10182">최주환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>130</td><td>-0.32</td><td>0.30</td><td>544</td><td>544</td><td>482</td><td>49</td><td>124</td><td>23</td><td>1</td><td>13</td><td>188</td><td>84</td><td>0</td><td>1</td><td>47</td><td>6</td><td>2</td><td>92</td><td>12</td><td>0</td><td>9</td><td style="">0.257</td><td>0.325</td><td>0.390</td><td>0.715</td><td>0.111</td><td>86.1</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11244">김태진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.04</td><td>81</td><td>-0.77</td><td>0.73</td><td>202</td><td>197</td><td>189</td><td>26</td><td>42</td><td>6</td><td>3</td><td>0</td><td>54</td><td>10</td><td>0</td><td>0</td><td>7</td><td>0</td><td>1</td><td>27</td><td>1</td><td>5</td><td>1</td><td style="">0.222</td><td>0.249</td><td>0.286</td><td>0.535</td><td>0.035</td><td>27.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.04</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16130">송지후</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.05</td><td>2</td><td>-0.03</td><td>-0.01</td><td>1</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-151.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.05</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14851">김시앙</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>6</td><td>-0.09</td><td>0.02</td><td>7</td><td>7</td><td>7</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.143</td><td>0.143</td><td>0.143</td><td>0.286</td><td>-0.070</td><td>-52.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10870">김재현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>110</td><td>-0.18</td><td>0.10</td><td>326</td><td>316</td><td>288</td><td>27</td><td>70</td><td>11</td><td>0</td><td>0</td><td>81</td><td>26</td><td>1</td><td>1</td><td>14</td><td>10</td><td>0</td><td>63</td><td>8</td><td>10</td><td>4</td><td style="">0.243</td><td>0.297</td><td>0.281</td><td>0.578</td><td>0.067</td><td>52.1</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13096">김수환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.08</td><td>2</td><td>-0.08</td><td>0.00</td><td>3</td><td>3</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-154.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.08</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15473">김동헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.10</td><td>2</td><td>0.04</td><td>-0.14</td><td>7</td><td>7</td><td>5</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">0.200</td><td>0.429</td><td>0.200</td><td>0.629</td><td>0.153</td><td>115.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.10</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14214">김주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.12</td><td>22</td><td>-0.19</td><td>0.07</td><td>25</td><td>24</td><td>20</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3</td><td>2</td><td>0</td><td>1</td><td>1</td><td>3</td><td>0</td><td>9</td><td>0</td><td>1</td><td>0</td><td style="">0.150</td><td>0.292</td><td>0.150</td><td>0.442</td><td>0.050</td><td>37.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.12</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14133">주성원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.13</td><td>27</td><td>-0.23</td><td>0.09</td><td>62</td><td>61</td><td>55</td><td>7</td><td>11</td><td>1</td><td>0</td><td>1</td><td>15</td><td>5</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>18</td><td>2</td><td>1</td><td>0</td><td style="">0.200</td><td>0.279</td><td>0.273</td><td>0.552</td><td>0.054</td><td>42.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.13</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11226">임병욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.16</td><td>42</td><td>-0.13</td><td>-0.03</td><td>92</td><td>92</td><td>87</td><td>14</td><td>21</td><td>3</td><td>0</td><td>3</td><td>33</td><td>10</td><td>1</td><td>0</td><td>4</td><td>0</td><td>0</td><td>32</td><td>1</td><td>0</td><td>1</td><td style="">0.241</td><td>0.272</td><td>0.379</td><td>0.651</td><td>0.075</td><td>57.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.16</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14577">김병휘</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.19</td><td>28</td><td>0.03</td><td>-0.21</td><td>71</td><td>70</td><td>59</td><td>6</td><td>10</td><td>3</td><td>0</td><td>1</td><td>16</td><td>3</td><td>0</td><td>0</td><td>6</td><td>5</td><td>0</td><td>26</td><td>0</td><td>1</td><td>0</td><td style="">0.169</td><td>0.300</td><td>0.271</td><td>0.571</td><td>0.081</td><td>61.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.19</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13223">변상권</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.20</td><td>77</td><td>-0.58</td><td>0.38</td><td>232</td><td>232</td><td>219</td><td>16</td><td>55</td><td>3</td><td>1</td><td>5</td><td>75</td><td>21</td><td>0</td><td>0</td><td>11</td><td>1</td><td>0</td><td>51</td><td>4</td><td>0</td><td>1</td><td style="">0.251</td><td>0.289</td><td>0.342</td><td>0.631</td><td>0.075</td><td>57.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.20</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14211">박준형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.22</td><td>4</td><td>-0.12</td><td>-0.11</td><td>5</td><td>5</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.190</td><td>-154.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.22</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16136">원성준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.22</td><td>51</td><td>-0.16</td><td>-0.07</td><td>125</td><td>124</td><td>112</td><td>12</td><td>28</td><td>5</td><td>0</td><td>2</td><td>39</td><td>11</td><td>2</td><td>0</td><td>10</td><td>0</td><td>0</td><td>36</td><td>2</td><td>1</td><td>2</td><td style="">0.250</td><td>0.306</td><td>0.348</td><td>0.654</td><td>0.087</td><td>67.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.22</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14580">박주홍</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.27</td><td>25</td><td>-0.44</td><td>0.17</td><td>59</td><td>59</td><td>49</td><td>5</td><td>5</td><td>2</td><td>0</td><td>0</td><td>7</td><td>1</td><td>2</td><td>0</td><td>10</td><td>0</td><td>0</td><td>17</td><td>1</td><td>0</td><td>0</td><td style="">0.102</td><td>0.254</td><td>0.143</td><td>0.397</td><td>0.016</td><td>12.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.27</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14784">장재영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.33</td><td>38</td><td>-0.25</td><td>-0.07</td><td>139</td><td>139</td><td>119</td><td>14</td><td>20</td><td>3</td><td>0</td><td>4</td><td>35</td><td>13</td><td>0</td><td>0</td><td>17</td><td>3</td><td>0</td><td>64</td><td>2</td><td>0</td><td>0</td><td style="">0.168</td><td>0.288</td><td>0.294</td><td>0.582</td><td>0.072</td><td>55.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.33</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12503">김웅빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.40</td><td>12</td><td>-0.40</td><td>0.00</td><td>38</td><td>37</td><td>32</td><td>2</td><td>4</td><td>0</td><td>0</td><td>0</td><td>4</td><td>2</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>15</td><td>1</td><td>1</td><td>0</td><td style="">0.125</td><td>0.243</td><td>0.125</td><td>0.368</td><td>0.002</td><td>1.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.40</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16128">고영우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.42</td><td>94</td><td>0.01</td><td>-0.43</td><td>290</td><td>286</td><td>254</td><td>21</td><td>65</td><td>12</td><td>2</td><td>0</td><td>81</td><td>35</td><td>0</td><td>0</td><td>28</td><td>1</td><td>0</td><td>71</td><td>5</td><td>4</td><td>3</td><td style="">0.256</td><td>0.329</td><td>0.319</td><td>0.648</td><td>0.094</td><td>73.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.42</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13093">예진원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.50</td><td>22</td><td>-0.10</td><td>-0.39</td><td>21</td><td>21</td><td>19</td><td>2</td><td>4</td><td>1</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>8</td><td>1</td><td>0</td><td>0</td><td style="">0.211</td><td>0.286</td><td>0.263</td><td>0.549</td><td>0.056</td><td>42.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.50</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10180">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.53</td><td>39</td><td>-0.33</td><td>-0.20</td><td>109</td><td>109</td><td>91</td><td>5</td><td>20</td><td>4</td><td>0</td><td>0</td><td>24</td><td>8</td><td>0</td><td>0</td><td>14</td><td>2</td><td>0</td><td>18</td><td>2</td><td>0</td><td>2</td><td style="">0.220</td><td>0.330</td><td>0.264</td><td>0.594</td><td>0.085</td><td>66.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.53</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15476">이승원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.74</td><td>20</td><td>-0.53</td><td>-0.20</td><td>41</td><td>39</td><td>37</td><td>3</td><td>4</td><td>1</td><td>0</td><td>0</td><td>5</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>13</td><td>2</td><td>2</td><td>0</td><td style="">0.108</td><td>0.154</td><td>0.135</td><td>0.289</td><td>-0.058</td><td>-43.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.74</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11225">임지열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.87</td><td>22</td><td>-0.59</td><td>-0.28</td><td>57</td><td>57</td><td>49</td><td>4</td><td>5</td><td>0</td><td>0</td><td>1</td><td>8</td><td>5</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>16</td><td>2</td><td>0</td><td>1</td><td style="">0.102</td><td>0.211</td><td>0.163</td><td>0.374</td><td>-0.011</td><td>-8.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.87</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16124">이재상</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-1.04</td><td>36</td><td>-0.55</td><td>-0.49</td><td>89</td><td>88</td><td>84</td><td>7</td><td>16</td><td>1</td><td>0</td><td>1</td><td>20</td><td>5</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>33</td><td>0</td><td>1</td><td>0</td><td style="">0.190</td><td>0.227</td><td>0.238</td><td>0.465</td><td>0.013</td><td>9.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-1.04</td></tr>			</tbody>
		</table>""")

In [ ]:
len(team_tables)

10

In [ ]:
batting = pd.DataFrame()
for i in range(len(team_tables)):
    name = team_names[i]
    team = team_tables[i]
    print(name)
    df, pids = get_team_stats_from_markup(StringIO(str(team)))
    df['팀'] = name
    df['pid'] = pids[2:]
    print(df.shape)
    print(len(pids))
    batting = pd.concat([batting, df])
    display(batting.tail())

한화 이글스
(30, 35)
32

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team Sort▼   G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank Name   Team   WAR   G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
25   26  이원석  24 CF -0.21  87 -0.24  0.03  154  152  133  ...  1  0.233
26   27  이명기  24 DH -0.21   4 -0.21  0.00    8    7    7  ...  0  0.000
27   28  임종찬  24 CF -0.24  24 -0.20 -0.03   64   64   57  ...  0  0.158
28   29  이재원   24 C -0.29  72 -0.24 -0.05  152  150  134  ...  5  0.239
29   30  김인환  24 LF -0.99  51 -0.58 -0.41  143  143  131  ...  0  0.237

                                       WAR▼       팀    pid
      OBP    SLG    OPS  R/ePA   wRC+  WAR▼
25  0.322  0.278  0.600  0.082   61.5 -0.21  한화 이글스  13138
26  0.000  0.000  0.000 -0.190 -132.5 -0.21  한화 이글스  10119
27  0.250  0.281  0.531  0.048   35.5 -0.24  한화 이글스  14706
28  0.287  0.291  0.578  0.059   44.0 -0.29  한화 이글스  10082
29  0.301  0.275  0.576  0.066   48.1 -0.99  한화 이글스  12589

[5 rows x 35 columns]

LG 트윈스

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(43, 35)
45

   Rank Name   Team Sort▼   G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank Name   Team   WAR   G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
38   39  함창건  24 LF -0.19  15 -0.20  0.01   17   16   14  ...  0  0.143
39   40  김성우   24 C -0.26   4 -0.12 -0.14    5    5    5  ...  0  0.000
40   41  김민수  24 3B -0.33  19 -0.22 -0.11   22   22   20  ...  0  0.150
41   42  김범석  24 DH -0.33  70 -0.25 -0.08  180  179  162  ...  2  0.241
42   43  허도환   24 C -0.64  59 -0.22 -0.42  105  100   80  ...  1  0.138

                                       WAR▼       팀    pid
      OBP    SLG    OPS  R/ePA   wRC+  WAR▼
38  0.250  0.143  0.393  0.006    4.4 -0.19  LG 트윈스  14680
39  0.000  0.000  0.000 -0.190 -139.9 -0.26  LG 트윈스  15085
40  0.227  0.150  0.377 -0.004   -3.4 -0.33  LG 트윈스  12931
41  0.306  0.377  0.683  0.095   71.7 -0.33  LG 트윈스  15484
42  0.300  0.163  0.463  0.059   44.6 -0.64  LG 트윈스  10684

[5 rows x 35 columns]

롯데 자이언츠
(38, 35)
40

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team Sort▼   G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank Name   Team   WAR   G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
33   34  김민석  24 LF -0.41  41 -0.42  0.01   83   82   76  ...  0  0.211
34   35  이주찬  24 3B -0.43  17 -0.11 -0.32   25   25   24  ...  0  0.167
35   36  서동욱   24 C -0.45  33 -0.35 -0.10   27   27   26  ...  0  0.115
36   37  한동희  24 DH -0.55  14 -0.31 -0.25   36   36   35  ...  0  0.257
37   38  정보근   24 C -0.63  89 -0.61 -0.02  140  136  133  ...  0  0.226

                                      WAR▼        팀    pid
      OBP    SLG    OPS  R/ePA  wRC+  WAR▼
33  0.268  0.276  0.544  0.054  38.9 -0.41  롯데 자이언츠  15253
34  0.200  0.333  0.533  0.025  17.0 -0.43  롯데 자이언츠  14819
35  0.148  0.154  0.302 -0.052 -37.8 -0.45  롯데 자이언츠  15624
36  0.278  0.314  0.592  0.052  37.4 -0.55  롯데 자이언츠  13145
37  0.243  0.286  0.529  0.030  21.4 -0.63  롯데 자이언츠  13154

[5 rows x 35 columns]

KIA 타이거즈
(34, 35)
36

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team Sort▼   G  oWAR  dWAR  PA ePA  AB  ... SF     비율         \
   Rank Name   Team   WAR   G  oWAR  dWAR  PA ePA  AB  ... SF    AVG    OBP
29   30  한승택   24 C -0.07  20  0.11 -0.17  15  15  11  ...  0  0.273  0.467
30   31  김두현  24 SS -0.15   3  0.10 -0.26   6   6   5  ...  0  0.400  0.500
31   32  김규성  24 3B -0.19  27  0.05 -0.25  15  14  12  ...  0  0.250  0.357
32   33  최정용  24 2B -0.20   6 -0.10 -0.10  12  12  11  ...  0  0.182  0.250
33   34  김호령  24 CF -0.23  64 -0.44  0.21  67  67  59  ...  0  0.136  0.239

                                WAR▼         팀    pid
      SLG    OPS  R/ePA   wRC+  WAR▼
29  0.273  0.740  0.171  128.3 -0.07  KIA 타이거즈  11119
30  0.400  0.900  0.229  164.9 -0.15  KIA 타이거즈  16086
31  0.333  0.690  0.119   88.3 -0.19  KIA 타이거즈  12540
32  0.182  0.432  0.010    7.5 -0.20  KIA 타이거즈  11407
33  0.220  0.459  0.021   16.0 -0.23  KIA 타이거즈  11298

[5 rows x 35 columns]

KT 위즈
(43, 35)
45

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team Sort▼   G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank Name   Team   WAR   G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
38   39  박민석  24 2B -0.31  20 -0.14 -0.18   14   14   14  ...  0  0.214
39   40  김건형  24 RF -0.38  13 -0.35 -0.03   25   25   24  ...  0  0.125
40   41  오재일  24 1B -0.45  83 -0.01 -0.43  272  272  232  ...  8  0.246
41   42  조용호  24 RF -0.52  60 -0.53  0.01  165  162  149  ...  0  0.248
42   43  이호연  24 3B -0.61  27 -0.55 -0.06   43   42   41  ...  0  0.146

                                      WAR▼      팀    pid
      OBP    SLG    OPS  R/ePA  wRC+  WAR▼
38  0.214  0.214  0.428 -0.010  -7.4 -0.31  KT 위즈  14110
39  0.160  0.167  0.327 -0.046 -34.1 -0.38  KT 위즈  14779
40  0.327  0.405  0.732  0.116  84.3 -0.45  KT 위즈  10400
41  0.309  0.282  0.591  0.071  51.9 -0.52  KT 위즈  12943
42  0.167  0.171  0.338 -0.044 -32.6 -0.61  KT 위즈  13151

[5 rows x 35 columns]

삼성 라이온즈
(41, 35)
43

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team Sort▼   G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank Name   Team   WAR   G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
36   37  김호진  24 3B -0.40  26 -0.47  0.07   32   32   29  ...  1  0.069
37   38  강한울  24 3B -0.47  18 -0.47  0.01   25   22   21  ...  1  0.095
38   39  김재혁  24 1B -0.49  35 -0.53  0.04   54   54   49  ...  2  0.184
39   40  김현준  24 RF -0.58  79 -0.83  0.25  205  201  183  ...  3  0.224
40   41  안주형  24 2B -0.92  82 -0.57 -0.35  166  154  142  ...  0  0.218

                                      WAR▼        팀    pid
      OBP    SLG    OPS  R/ePA  wRC+  WAR▼
36  0.125  0.069  0.194 -0.088 -60.7 -0.40  삼성 라이온즈  15868
37  0.091  0.095  0.186 -0.114 -81.5 -0.47  삼성 라이온즈  11255
38  0.222  0.265  0.487  0.017  11.6 -0.49  삼성 라이온즈  15036
39  0.279  0.290  0.569  0.059  41.4 -0.58  삼성 라이온즈  14867
40  0.279  0.232  0.511  0.041  29.2 -0.92  삼성 라이온즈  12988

[5 rows x 35 columns]

SSG 랜더스
(34, 35)
36

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team Sort▼    G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank Name   Team   WAR    G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
29   30  김성현  24 2B -0.49   71  0.03 -0.53  167  162  141  ...  1  0.227
30   31  하재훈  24 RF -0.74  107  0.11 -0.85  317  315  290  ...  5  0.248
31   32  고명준  24 1B -0.76  106 -0.97  0.21  366  366  340  ...  0  0.250
32   33  안상현  24 2B -0.80   37 -0.58 -0.22   75   74   70  ...  0  0.171
33   34  전의산  24 1B -1.35   34 -1.09 -0.26   63   63   57  ...  1  0.088

                                      WAR▼        팀    pid
      OBP    SLG    OPS  R/ePA  wRC+  WAR▼
29  0.321  0.284  0.605  0.085  60.3 -0.49  SSG 랜더스  10636
30  0.292  0.417  0.709  0.102  73.9 -0.74  SSG 랜더스  14147
31  0.303  0.385  0.688  0.095  68.1 -0.76  SSG 랜더스  14807
32  0.216  0.186  0.402 -0.010  -7.2 -0.80  SSG 랜더스  12613
33  0.159  0.140  0.299 -0.051 -37.6 -1.35  SSG 랜더스  14699

[5 rows x 35 columns]

NC 다이노스
(32, 35)
34

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team Sort▼    G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank Name   Team   WAR    G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
27   28  김수윤  24 1B -0.16    9 -0.07 -0.08   10   10    9  ...  0  0.222
28   29  박한결  24 LF -0.28   28 -0.07 -0.21   71   71   65  ...  0  0.185
29   30  박시원  24 CF -0.46   55 -0.26 -0.20  158  156  141  ...  1  0.234
30   31  김성욱  24 CF -0.49  129 -0.10 -0.38  412  409  358  ...  5  0.204
31   32  한석현  24 RF -0.52   40 -0.22 -0.30   76   76   73  ...  0  0.247

                                      WAR▼        팀    pid
      OBP    SLG    OPS  R/ePA  wRC+  WAR▼
27  0.300  0.222  0.522  0.050  37.3 -0.16  NC 다이노스  12903
28  0.254  0.523  0.777  0.110  84.6 -0.28  NC 다이노스  15451
29  0.301  0.326  0.627  0.080  60.9 -0.46  NC 다이노스  14597
30  0.291  0.380  0.671  0.095  71.4 -0.49  NC 다이노스  11153
31  0.276  0.329  0.605  0.067  50.3 -0.52  NC 다이노스  13250

[5 rows x 35 columns]

두산 베어스

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(48, 35)
50

   Rank Name   Team Sort▼    G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank Name   Team   WAR    G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
43   44  전민재  24 SS -0.32  100 -0.39  0.07  276  272  248  ...  3  0.246
44   45  박계범  24 2B -0.33   24  0.11 -0.44   20   20   15  ...  0  0.200
45   46  김인태  24 LF -0.39   10 -0.24 -0.15   26   26   23  ...  1  0.174
46   47  김대한  24 RF -0.69   61 -0.70  0.01   89   87   75  ...  2  0.133
47   48  김태근  24 LF -0.70   43 -0.50 -0.20   27   26   23  ...  0  0.087

                                       WAR▼       팀    pid
      OBP    SLG    OPS  R/ePA   wRC+  WAR▼
43  0.301  0.298  0.599  0.071   54.5 -0.32  두산 베어스  13073
44  0.400  0.267  0.667  0.135  102.1 -0.33  두산 베어스  11198
45  0.231  0.304  0.535  0.031   22.0 -0.39  두산 베어스  11098
46  0.230  0.187  0.417  0.007    5.6 -0.69  두산 베어스  14170
47  0.192  0.087  0.279 -0.028  -21.7 -0.70  두산 베어스  14175

[5 rows x 35 columns]

키움 히어로즈
(47, 35)
49

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team Sort▼   G  oWAR  dWAR   PA  ePA  AB  ... SF     비율         \
   Rank Name   Team   WAR   G  oWAR  dWAR   PA  ePA  AB  ... SF    AVG    OBP
42   43  예진원  24 CF -0.50  22 -0.10 -0.39   21   21  19  ...  0  0.211  0.286
43   44  이원석  24 DH -0.53  39 -0.33 -0.20  109  109  91  ...  2  0.220  0.330
44   45  이승원  24 SS -0.74  20 -0.53 -0.20   41   39  37  ...  0  0.108  0.154
45   46  임지열  24 RF -0.87  22 -0.59 -0.28   57   57  49  ...  1  0.102  0.211
46   47  이재상  24 SS -1.04  36 -0.55 -0.49   89   88  84  ...  0  0.190  0.227

                               WAR▼        팀    pid
      SLG    OPS  R/ePA  wRC+  WAR▼
42  0.263  0.549  0.056  42.8 -0.50  키움 히어로즈  13093
43  0.264  0.594  0.085  66.4 -0.53  키움 히어로즈  10180
44  0.135  0.289 -0.058 -43.9 -0.74  키움 히어로즈  15476
45  0.163  0.374 -0.011  -8.3 -0.87  키움 히어로즈  11225
46  0.238  0.465  0.013   9.9 -1.04  키움 히어로즈  16124

[5 rows x 35 columns]

In [ ]:
batting.info()

<class 'pandas.core.frame.DataFrame'>
Index: 390 entries, 0 to 46
Data columns (total 35 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   (Rank, Rank)  390 non-null    int64
 1   (Name, Name)  390 non-null    object
 2   (Team, Team)  390 non-null    object
 3   (Sort▼, WAR)  390 non-null    float64
 4   (G, G)        390 non-null    int64
 5   (oWAR, oWAR)  390 non-null    float64
 6   (dWAR, dWAR)  390 non-null    float64
 7   (PA, PA)      390 non-null    int64
 8   (ePA, ePA)    390 non-null    int64
 9   (AB, AB)      390 non-null    int64
 10  (R, R)        390 non-null    int64
 11  (H, H)        390 non-null    int64
 12  (2B, 2B)      390 non-null    int64
 13  (3B, 3B)      390 non-null    int64
 14  (HR, HR)      390 non-null    int64
 15  (TB, TB)      390 non-null    int64
 16  (RBI, RBI)    390 non-null    int64
 17  (SB, SB)      390 non-null    int64
 18  (CS, CS)      390 non-null    int64
 19  (BB, BB)      390 non-null    int64
 20  (HP, HP)      390 non-null    int64
 21  (IB, IB)      390 non-null    int64
 22  (SO, SO)      390 non-null    int64
 23  (GDP, GDP)    390 non-null    int64
 24  (SH, SH)      390 non-null    int64
 25  (SF, SF)      390 non-null    int64
 26  (비율, AVG)     302 non-null    float64
 27  (비율, OBP)     302 non-null    float64
 28  (비율, SLG)     302 non-null    float64
 29  (비율, OPS)     302 non-null    float64
 30  (비율, R/ePA)   302 non-null    float64
 31  (비율, wRC+)    302 non-null    float64
 32  (WAR▼, WAR▼)  390 non-null    float64
 33  (팀, )         390 non-null    object
 34  (pid, )       390 non-null    object
dtypes: float64(10), int64(21), object(4)
memory usage: 109.7+ KB

In [ ]:
batting.isna().sum()

Rank   Rank      0
Name   Name      0
Team   Team      0
Sort▼  WAR       0
G      G         0
oWAR   oWAR      0
dWAR   dWAR      0
PA     PA        0
ePA    ePA       0
AB     AB        0
R      R         0
H      H         0
2B     2B        0
3B     3B        0
HR     HR        0
TB     TB        0
RBI    RBI       0
SB     SB        0
CS     CS        0
BB     BB        0
HP     HP        0
IB     IB        0
SO     SO        0
GDP    GDP       0
SH     SH        0
SF     SF        0
비율     AVG      88
       OBP      88
       SLG      88
       OPS      88
       R/ePA    88
       wRC+     88
WAR▼   WAR▼      0
팀                0
pid              0
dtype: int64

In [ ]:
batting['Team'].value_counts()

Team
24 P     87
24 C     50
24 2B    38
24 RF    37
24 SS    32
24 LF    32
24 1B    30
24 CF    30
24 DH    27
24 3B    27
Name: count, dtype: int64

In [ ]:
batting.to_csv('2024_타격_statiz.csv', index=False)
team_tables = []

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10590">류현진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.44</td><td>28</td><td>28</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td><td>8</td><td>0</td><td>0</td><td>158.1</td><td>68</td><td>78</td><td>76.95</td><td>679</td><td>182</td><td>22</td><td>1</td><td>12</td><td>33</td><td>3</td><td>0</td><td>135</td><td>10</td><td>0</td><td>1</td><td>3.87</td><td>4.43</td><td>4.37</td><td>4.41</td><td>3.67</td><td>1.36</td><td style="background-color:#F3F3F3; font-weight:bold;">4.44</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11415">주현상</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.13</td><td>65</td><td>0</td><td>65</td><td>51</td><td>0</td><td>0</td><td>8</td><td>4</td><td>23</td><td>2</td><td>71.1</td><td>21</td><td>22</td><td>24.75</td><td>267</td><td>52</td><td>8</td><td>2</td><td>9</td><td>8</td><td>1</td><td>0</td><td>64</td><td>0</td><td>0</td><td>1</td><td>2.65</td><td>2.78</td><td>3.12</td><td>3.09</td><td>3.85</td><td>0.84</td><td style="background-color:#F3F3F3; font-weight:bold;">3.13</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16153">와이스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.92</td><td>16</td><td>16</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>91.2</td><td>38</td><td>43</td><td>41.95</td><td>384</td><td>77</td><td>13</td><td>5</td><td>8</td><td>29</td><td>3</td><td>0</td><td>98</td><td>7</td><td>0</td><td>6</td><td>3.73</td><td>4.22</td><td>4.12</td><td>4.06</td><td>3.65</td><td>1.16</td><td style="background-color:#F3F3F3; font-weight:bold;">2.92</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15013">문동주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.77</td><td>21</td><td>21</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>111.1</td><td>64</td><td>71</td><td>69.60</td><td>502</td><td>148</td><td>25</td><td>3</td><td>14</td><td>38</td><td>4</td><td>1</td><td>96</td><td>4</td><td>1</td><td>8</td><td>5.17</td><td>5.74</td><td>5.63</td><td>5.61</td><td>4.71</td><td>1.67</td><td style="background-color:#F3F3F3; font-weight:bold;">1.77</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16150">바리아</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.69</td><td>20</td><td>19</td><td>1</td><td>0</td><td>0</td><td>0</td><td>6</td><td>7</td><td>0</td><td>0</td><td>92.2</td><td>53</td><td>58</td><td>56.60</td><td>405</td><td>114</td><td>20</td><td>1</td><td>10</td><td>18</td><td>0</td><td>0</td><td>83</td><td>7</td><td>0</td><td>6</td><td>5.15</td><td>5.63</td><td>5.50</td><td>5.39</td><td>3.85</td><td>1.42</td><td style="background-color:#F3F3F3; font-weight:bold;">1.69</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15643">산체스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.48</td><td>11</td><td>11</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>3</td><td>0</td><td>0</td><td>53.1</td><td>25</td><td>28</td><td>25.80</td><td>245</td><td>60</td><td>9</td><td>1</td><td>2</td><td>21</td><td>10</td><td>1</td><td>56</td><td>4</td><td>1</td><td>2</td><td>4.22</td><td>4.73</td><td>4.35</td><td>4.43</td><td>3.82</td><td>1.52</td><td style="background-color:#F3F3F3; font-weight:bold;">1.48</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16107">황준서</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.24</td><td>36</td><td>11</td><td>25</td><td>6</td><td>0</td><td>0</td><td>2</td><td>8</td><td>0</td><td>1</td><td>72.0</td><td>43</td><td>44</td><td>44.05</td><td>341</td><td>80</td><td>16</td><td>0</td><td>9</td><td>51</td><td>5</td><td>0</td><td>70</td><td>1</td><td>1</td><td>3</td><td>5.38</td><td>5.50</td><td>5.51</td><td>5.42</td><td>5.67</td><td>1.82</td><td style="background-color:#F3F3F3; font-weight:bold;">1.24</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12871">박상원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.11</td><td>65</td><td>0</td><td>65</td><td>9</td><td>0</td><td>0</td><td>3</td><td>3</td><td>2</td><td>16</td><td>66.2</td><td>34</td><td>38</td><td>38.25</td><td>278</td><td>57</td><td>18</td><td>0</td><td>2</td><td>22</td><td>7</td><td>0</td><td>65</td><td>3</td><td>0</td><td>8</td><td>4.59</td><td>5.13</td><td>5.16</td><td>5.12</td><td>3.47</td><td>1.19</td><td style="background-color:#F3F3F3; font-weight:bold;">1.11</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13003">이민우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.99</td><td>64</td><td>0</td><td>64</td><td>7</td><td>0</td><td>0</td><td>2</td><td>1</td><td>1</td><td>10</td><td>55.0</td><td>23</td><td>25</td><td>31.35</td><td>235</td><td>56</td><td>10</td><td>2</td><td>5</td><td>23</td><td>1</td><td>0</td><td>49</td><td>2</td><td>0</td><td>1</td><td>3.76</td><td>4.09</td><td>5.13</td><td>4.97</td><td>4.41</td><td>1.44</td><td style="background-color:#F3F3F3; font-weight:bold;">0.99</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10812">한승혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.94</td><td>70</td><td>0</td><td>70</td><td>4</td><td>0</td><td>0</td><td>5</td><td>5</td><td>0</td><td>19</td><td>62.2</td><td>35</td><td>39</td><td>37.10</td><td>289</td><td>63</td><td>7</td><td>1</td><td>2</td><td>38</td><td>6</td><td>2</td><td>64</td><td>2</td><td>0</td><td>6</td><td>5.03</td><td>5.60</td><td>5.33</td><td>5.27</td><td>4.20</td><td>1.61</td><td style="background-color:#F3F3F3; font-weight:bold;">0.94</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10610">장민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.74</td><td>26</td><td>0</td><td>26</td><td>9</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>29.0</td><td>10</td><td>10</td><td>12.75</td><td>138</td><td>46</td><td>7</td><td>0</td><td>2</td><td>7</td><td>1</td><td>0</td><td>17</td><td>0</td><td>0</td><td>5</td><td>3.10</td><td>3.10</td><td>3.96</td><td>3.88</td><td>4.41</td><td>1.83</td><td style="background-color:#F3F3F3; font-weight:bold;">0.74</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15421">김서현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.71</td><td>37</td><td>0</td><td>37</td><td>5</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>10</td><td>38.1</td><td>16</td><td>20</td><td>20.15</td><td>178</td><td>31</td><td>6</td><td>2</td><td>0</td><td>32</td><td>4</td><td>0</td><td>43</td><td>2</td><td>0</td><td>3</td><td>3.76</td><td>4.70</td><td>4.73</td><td>4.93</td><td>4.31</td><td>1.64</td><td style="background-color:#F3F3F3; font-weight:bold;">0.71</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11410">김민우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.62</td><td>3</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>12.1</td><td>3</td><td>3</td><td>3.00</td><td>49</td><td>7</td><td>0</td><td>0</td><td>2</td><td>6</td><td>0</td><td>0</td><td>13</td><td>1</td><td>0</td><td>0</td><td>2.19</td><td>2.19</td><td>2.19</td><td>2.44</td><td>5.00</td><td>1.05</td><td style="background-color:#F3F3F3; font-weight:bold;">0.62</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13245">이상규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.48</td><td>21</td><td>3</td><td>18</td><td>4</td><td>0</td><td>0</td><td>1</td><td>4</td><td>0</td><td>0</td><td>32.0</td><td>20</td><td>20</td><td>18.95</td><td>149</td><td>39</td><td>7</td><td>1</td><td>5</td><td>15</td><td>1</td><td>1</td><td>27</td><td>0</td><td>0</td><td>1</td><td>5.63</td><td>5.63</td><td>5.33</td><td>5.29</td><td>5.40</td><td>1.69</td><td style="background-color:#F3F3F3; font-weight:bold;">0.48</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14808">김기중</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.33</td><td>27</td><td>11</td><td>16</td><td>4</td><td>0</td><td>0</td><td>5</td><td>4</td><td>0</td><td>0</td><td>59.0</td><td>43</td><td>44</td><td>42.60</td><td>286</td><td>83</td><td>12</td><td>1</td><td>8</td><td>27</td><td>6</td><td>0</td><td>39</td><td>2</td><td>0</td><td>2</td><td>6.56</td><td>6.71</td><td>6.50</td><td>6.56</td><td>5.89</td><td>1.86</td><td style="background-color:#F3F3F3; font-weight:bold;">0.33</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10453">장시환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.28</td><td>30</td><td>0</td><td>30</td><td>2</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>2</td><td>33.1</td><td>19</td><td>27</td><td>22.05</td><td>156</td><td>34</td><td>6</td><td>1</td><td>3</td><td>22</td><td>1</td><td>0</td><td>28</td><td>5</td><td>0</td><td>0</td><td>5.13</td><td>7.29</td><td>5.95</td><td>5.96</td><td>5.31</td><td>1.68</td><td style="background-color:#F3F3F3; font-weight:bold;">0.28</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15146">페냐</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.26</td><td>9</td><td>9</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>5</td><td>0</td><td>0</td><td>37.1</td><td>26</td><td>28</td><td>27.30</td><td>171</td><td>41</td><td>6</td><td>0</td><td>6</td><td>20</td><td>0</td><td>0</td><td>29</td><td>1</td><td>0</td><td>1</td><td>6.27</td><td>6.75</td><td>6.58</td><td>6.62</td><td>5.83</td><td>1.63</td><td style="background-color:#F3F3F3; font-weight:bold;">0.26</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14711">김승일</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.12</td><td>3</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.0</td><td>1</td><td>1</td><td>0.30</td><td>13</td><td>4</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td>3.00</td><td>3.00</td><td>0.90</td><td>0.90</td><td>3.57</td><td>1.33</td><td style="background-color:#F3F3F3; font-weight:bold;">0.12</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14619">남지민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.12</td><td>2</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4.0</td><td>0</td><td>0</td><td>1.20</td><td>17</td><td>2</td><td>1</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>3</td><td>0</td><td>0</td><td>1</td><td>0.00</td><td>0.00</td><td>2.70</td><td>2.70</td><td>4.65</td><td>1.00</td><td style="background-color:#F3F3F3; font-weight:bold;">0.12</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11411">김범수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.08</td><td>39</td><td>0</td><td>39</td><td>6</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>34.0</td><td>20</td><td>20</td><td>25.10</td><td>157</td><td>33</td><td>2</td><td>0</td><td>11</td><td>20</td><td>5</td><td>1</td><td>38</td><td>2</td><td>0</td><td>3</td><td>5.29</td><td>5.29</td><td>6.64</td><td>6.53</td><td>7.44</td><td>1.56</td><td style="background-color:#F3F3F3; font-weight:bold;">0.08</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14871">김규연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.01</td><td>58</td><td>1</td><td>57</td><td>12</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>4</td><td>59.0</td><td>46</td><td>50</td><td>46.95</td><td>270</td><td>66</td><td>10</td><td>1</td><td>6</td><td>28</td><td>4</td><td>1</td><td>40</td><td>3</td><td>0</td><td>3</td><td>7.02</td><td>7.63</td><td>7.16</td><td>7.05</td><td>5.40</td><td>1.59</td><td style="background-color:#F3F3F3; font-weight:bold;">0.01</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16108">조동욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>21</td><td>8</td><td>13</td><td>6</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>41.0</td><td>29</td><td>34</td><td>35.90</td><td>198</td><td>57</td><td>10</td><td>0</td><td>5</td><td>14</td><td>6</td><td>0</td><td>32</td><td>3</td><td>1</td><td>1</td><td>6.37</td><td>7.46</td><td>7.88</td><td>7.68</td><td>5.21</td><td>1.73</td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14158">배민서</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.08</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.2</td><td>3</td><td>3</td><td>3.00</td><td>11</td><td>4</td><td>1</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>16.20</td><td>16.20</td><td>16.20</td><td>16.17</td><td>8.28</td><td>4.20</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.08</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16118">김도빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.11</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0.1</td><td>2</td><td>2</td><td>2.00</td><td>5</td><td>1</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>54.00</td><td>54.00</td><td>54.00</td><td>54.00</td><td>24.60</td><td>12.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.11</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11116">이충호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.12</td><td>3</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.1</td><td>1</td><td>1</td><td>3.05</td><td>13</td><td>4</td><td>1</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3.86</td><td>3.86</td><td>11.76</td><td>11.02</td><td>4.97</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.12</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14178">장지수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.14</td><td>13</td><td>0</td><td>13</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>14.0</td><td>17</td><td>18</td><td>14.75</td><td>75</td><td>23</td><td>5</td><td>2</td><td>0</td><td>10</td><td>2</td><td>2</td><td>11</td><td>1</td><td>0</td><td>2</td><td>10.93</td><td>11.57</td><td>9.48</td><td>9.15</td><td>4.45</td><td>2.36</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.14</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11110">윤대경</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.26</td><td>7</td><td>0</td><td>7</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7.2</td><td>9</td><td>9</td><td>10.20</td><td>40</td><td>10</td><td>3</td><td>0</td><td>1</td><td>6</td><td>1</td><td>1</td><td>7</td><td>0</td><td>0</td><td>0</td><td>10.57</td><td>10.57</td><td>11.97</td><td>11.77</td><td>6.30</td><td>2.09</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.26</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10609">이태양</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.50</td><td>10</td><td>1</td><td>9</td><td>3</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>9.1</td><td>12</td><td>13</td><td>14.20</td><td>48</td><td>17</td><td>3</td><td>0</td><td>4</td><td>2</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>11.57</td><td>12.54</td><td>13.69</td><td>13.89</td><td>9.43</td><td>2.04</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.50</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14621">한승주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.95</td><td>18</td><td>0</td><td>18</td><td>6</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>22.0</td><td>28</td><td>31</td><td>30.15</td><td>120</td><td>45</td><td>6</td><td>1</td><td>2</td><td>10</td><td>3</td><td>0</td><td>14</td><td>2</td><td>0</td><td>1</td><td>11.45</td><td>12.68</td><td>12.33</td><td>12.50</td><td>5.52</td><td>2.50</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.95</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10156">정우람</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">24</span> <span><img src="/data/team/ci/2024/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0</td><td>0</td><td>0.00</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td></td><td></td><td></td><td></td><td>4.20</td><td>99.99</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10652">임찬규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.46</td><td>25</td><td>24</td><td>1</td><td>0</td><td>0</td><td>0</td><td>10</td><td>6</td><td>0</td><td>1</td><td>134.0</td><td>57</td><td>58</td><td>56.10</td><td>577</td><td>144</td><td>29</td><td>1</td><td>12</td><td>42</td><td>5</td><td>1</td><td>136</td><td>0</td><td>0</td><td>1</td><td>3.83</td><td>3.90</td><td>3.77</td><td>3.94</td><td>3.79</td><td>1.39</td><td style="background-color:#F3F3F3; font-weight:bold;">4.46</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16023">엔스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.33</td><td>30</td><td>30</td><td>0</td><td>0</td><td>0</td><td>0</td><td>13</td><td>6</td><td>0</td><td>0</td><td>167.2</td><td>78</td><td>84</td><td>83.65</td><td>714</td><td>169</td><td>29</td><td>3</td><td>16</td><td>50</td><td>6</td><td>0</td><td>157</td><td>9</td><td>0</td><td>4</td><td>4.19</td><td>4.51</td><td>4.49</td><td>4.64</td><td>4.03</td><td>1.31</td><td style="background-color:#F3F3F3; font-weight:bold;">4.33</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12908">손주영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.31</td><td>28</td><td>27</td><td>1</td><td>0</td><td>0</td><td>0</td><td>9</td><td>10</td><td>0</td><td>1</td><td>144.2</td><td>61</td><td>71</td><td>65.30</td><td>637</td><td>157</td><td>16</td><td>0</td><td>11</td><td>54</td><td>10</td><td>0</td><td>112</td><td>9</td><td>0</td><td>6</td><td>3.79</td><td>4.42</td><td>4.06</td><td>4.26</td><td>4.54</td><td>1.46</td><td style="background-color:#F3F3F3; font-weight:bold;">4.31</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11379">최원태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.30</td><td>24</td><td>23</td><td>1</td><td>0</td><td>0</td><td>0</td><td>9</td><td>7</td><td>0</td><td>0</td><td>126.2</td><td>60</td><td>66</td><td>62.20</td><td>554</td><td>126</td><td>20</td><td>1</td><td>10</td><td>57</td><td>5</td><td>0</td><td>103</td><td>6</td><td>0</td><td>5</td><td>4.26</td><td>4.69</td><td>4.42</td><td>4.58</td><td>4.62</td><td>1.44</td><td style="background-color:#F3F3F3; font-weight:bold;">3.30</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13934">켈리</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.20</td><td>19</td><td>19</td><td>0</td><td>2</td><td>2</td><td>1</td><td>5</td><td>8</td><td>0</td><td>0</td><td>113.2</td><td>57</td><td>65</td><td>65.00</td><td>495</td><td>131</td><td>18</td><td>1</td><td>13</td><td>25</td><td>6</td><td>0</td><td>69</td><td>4</td><td>0</td><td>9</td><td>4.51</td><td>5.15</td><td>5.15</td><td>5.28</td><td>4.89</td><td>1.37</td><td style="background-color:#F3F3F3; font-weight:bold;">2.20</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16160">에르난데스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.59</td><td>11</td><td>9</td><td>2</td><td>1</td><td>0</td><td>0</td><td>3</td><td>2</td><td>1</td><td>1</td><td>47.0</td><td>21</td><td>21</td><td>19.45</td><td>195</td><td>41</td><td>6</td><td>1</td><td>5</td><td>16</td><td>2</td><td>0</td><td>55</td><td>1</td><td>0</td><td>1</td><td>4.02</td><td>4.02</td><td>3.72</td><td>3.92</td><td>3.73</td><td>1.21</td><td style="background-color:#F3F3F3; font-weight:bold;">1.59</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11166">김진성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.23</td><td>71</td><td>0</td><td>71</td><td>6</td><td>0</td><td>0</td><td>3</td><td>3</td><td>1</td><td>27</td><td>70.1</td><td>31</td><td>34</td><td>38.35</td><td>294</td><td>62</td><td>11</td><td>1</td><td>11</td><td>23</td><td>7</td><td>3</td><td>61</td><td>4</td><td>0</td><td>2</td><td>3.97</td><td>4.35</td><td>4.91</td><td>5.13</td><td>5.17</td><td>1.21</td><td style="background-color:#F3F3F3; font-weight:bold;">1.23</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14669">유영찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.06</td><td>62</td><td>0</td><td>62</td><td>50</td><td>0</td><td>0</td><td>7</td><td>5</td><td>26</td><td>1</td><td>63.2</td><td>21</td><td>24</td><td>35.50</td><td>286</td><td>61</td><td>15</td><td>0</td><td>2</td><td>30</td><td>3</td><td>3</td><td>77</td><td>3</td><td>2</td><td>5</td><td>2.97</td><td>3.39</td><td>5.02</td><td>5.22</td><td>3.06</td><td>1.43</td><td style="background-color:#F3F3F3; font-weight:bold;">1.06</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11229">김유영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.84</td><td>53</td><td>2</td><td>51</td><td>6</td><td>0</td><td>0</td><td>1</td><td>2</td><td>1</td><td>6</td><td>47.2</td><td>20</td><td>27</td><td>25.70</td><td>212</td><td>50</td><td>7</td><td>0</td><td>2</td><td>16</td><td>4</td><td>0</td><td>42</td><td>8</td><td>1</td><td>3</td><td>3.78</td><td>5.10</td><td>4.85</td><td>4.99</td><td>3.80</td><td>1.38</td><td style="background-color:#F3F3F3; font-weight:bold;">0.84</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14135">이상영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.53</td><td>8</td><td>3</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>1</td><td>16.1</td><td>6</td><td>6</td><td>7.05</td><td>75</td><td>15</td><td>0</td><td>0</td><td>1</td><td>8</td><td>4</td><td>0</td><td>8</td><td>0</td><td>0</td><td>2</td><td>3.31</td><td>3.31</td><td>3.88</td><td>4.20</td><td>5.98</td><td>1.41</td><td style="background-color:#F3F3F3; font-weight:bold;">0.53</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14651">이종준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.52</td><td>27</td><td>0</td><td>27</td><td>13</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>1</td><td>26.0</td><td>12</td><td>13</td><td>12.65</td><td>119</td><td>26</td><td>5</td><td>0</td><td>4</td><td>16</td><td>0</td><td>0</td><td>28</td><td>1</td><td>0</td><td>1</td><td>4.15</td><td>4.50</td><td>4.38</td><td>4.50</td><td>5.25</td><td>1.62</td><td style="background-color:#F3F3F3; font-weight:bold;">0.52</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11094">함덕주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.32</td><td>15</td><td>0</td><td>15</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>3</td><td>11.2</td><td>7</td><td>7</td><td>4.95</td><td>54</td><td>13</td><td>0</td><td>1</td><td>2</td><td>7</td><td>1</td><td>0</td><td>8</td><td>0</td><td>0</td><td>0</td><td>5.40</td><td>5.40</td><td>3.82</td><td>4.02</td><td>6.65</td><td>1.71</td><td style="background-color:#F3F3F3; font-weight:bold;">0.32</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14816">우강훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.27</td><td>13</td><td>0</td><td>13</td><td>5</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>11.2</td><td>3</td><td>5</td><td>5.20</td><td>54</td><td>11</td><td>1</td><td>0</td><td>0</td><td>6</td><td>5</td><td>0</td><td>10</td><td>0</td><td>0</td><td>2</td><td>2.31</td><td>3.86</td><td>4.01</td><td>4.11</td><td>4.98</td><td>1.46</td><td style="background-color:#F3F3F3; font-weight:bold;">0.27</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14142">임준형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.19</td><td>18</td><td>1</td><td>17</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>13.2</td><td>10</td><td>10</td><td>7.95</td><td>62</td><td>16</td><td>4</td><td>0</td><td>2</td><td>4</td><td>3</td><td>0</td><td>13</td><td>0</td><td>0</td><td>0</td><td>6.59</td><td>6.59</td><td>5.24</td><td>5.48</td><td>5.15</td><td>1.46</td><td style="background-color:#F3F3F3; font-weight:bold;">0.19</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16015">진우영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.12</td><td>6</td><td>0</td><td>6</td><td>6</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7.2</td><td>4</td><td>4</td><td>4.00</td><td>35</td><td>8</td><td>3</td><td>0</td><td>1</td><td>4</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>2</td><td>4.70</td><td>4.70</td><td>4.70</td><td>4.89</td><td>5.41</td><td>1.57</td><td style="background-color:#F3F3F3; font-weight:bold;">0.12</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12532">김대현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.11</td><td>37</td><td>0</td><td>37</td><td>8</td><td>0</td><td>0</td><td>2</td><td>0</td><td>1</td><td>1</td><td>35.0</td><td>21</td><td>21</td><td>25.00</td><td>155</td><td>33</td><td>6</td><td>1</td><td>6</td><td>18</td><td>2</td><td>0</td><td>30</td><td>0</td><td>0</td><td>5</td><td>5.40</td><td>5.40</td><td>6.43</td><td>6.56</td><td>5.87</td><td>1.46</td><td style="background-color:#F3F3F3; font-weight:bold;">0.11</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11170">윤호솔</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.11</td><td>7</td><td>0</td><td>7</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4.1</td><td>2</td><td>2</td><td>1.65</td><td>24</td><td>4</td><td>0</td><td>0</td><td>0</td><td>8</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td>4.15</td><td>4.15</td><td>3.43</td><td>3.44</td><td>7.04</td><td>2.77</td><td style="background-color:#F3F3F3; font-weight:bold;">0.11</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14143">이지강</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.11</td><td>46</td><td>2</td><td>44</td><td>6</td><td>0</td><td>0</td><td>2</td><td>3</td><td>1</td><td>1</td><td>53.2</td><td>27</td><td>35</td><td>38.75</td><td>250</td><td>61</td><td>9</td><td>0</td><td>5</td><td>26</td><td>2</td><td>0</td><td>39</td><td>5</td><td>0</td><td>5</td><td>4.53</td><td>5.87</td><td>6.50</td><td>6.69</td><td>5.11</td><td>1.62</td><td style="background-color:#F3F3F3; font-weight:bold;">0.11</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14136">정우영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.09</td><td>27</td><td>0</td><td>27</td><td>2</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>3</td><td>22.2</td><td>12</td><td>15</td><td>15.00</td><td>108</td><td>31</td><td>6</td><td>0</td><td>0</td><td>11</td><td>6</td><td>0</td><td>17</td><td>1</td><td>0</td><td>3</td><td>4.76</td><td>5.96</td><td>5.96</td><td>6.38</td><td>4.65</td><td>1.85</td><td style="background-color:#F3F3F3; font-weight:bold;">0.09</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14781">김진수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.09</td><td>7</td><td>0</td><td>7</td><td>3</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>13.1</td><td>10</td><td>10</td><td>9.15</td><td>58</td><td>17</td><td>2</td><td>0</td><td>3</td><td>4</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>0</td><td>6.75</td><td>6.75</td><td>6.18</td><td>6.15</td><td>6.68</td><td>1.58</td><td style="background-color:#F3F3F3; font-weight:bold;">0.09</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13103">성동현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.08</td><td>2</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0.00</td><td>8</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>7.60</td><td>1.50</td><td style="background-color:#F3F3F3; font-weight:bold;">0.08</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14780">강효종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.10</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.1</td><td>3</td><td>3</td><td>3.00</td><td>9</td><td>2</td><td>0</td><td>0</td><td>1</td><td>3</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>20.25</td><td>20.25</td><td>20.25</td><td>18.46</td><td>16.35</td><td>3.75</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.10</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14588">김윤식</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.11</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.0</td><td>4</td><td>4</td><td>4.00</td><td>17</td><td>7</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>12.00</td><td>12.00</td><td>12.00</td><td>12.94</td><td>4.40</td><td>2.67</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.11</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10535">최동환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.23</td><td>26</td><td>0</td><td>26</td><td>7</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>2</td><td>22.0</td><td>17</td><td>18</td><td>19.70</td><td>105</td><td>35</td><td>6</td><td>0</td><td>4</td><td>9</td><td>0</td><td>0</td><td>14</td><td>1</td><td>0</td><td>0</td><td>6.95</td><td>7.36</td><td>8.06</td><td>8.52</td><td>6.04</td><td>2.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.23</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14847">이믿음</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.27</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>4.0</td><td>7</td><td>7</td><td>7.00</td><td>27</td><td>11</td><td>2</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>15.75</td><td>15.75</td><td>15.75</td><td>16.98</td><td>6.05</td><td>3.75</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.27</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13102">김영준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.33</td><td>14</td><td>0</td><td>14</td><td>5</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>15.1</td><td>14</td><td>17</td><td>16.65</td><td>76</td><td>21</td><td>3</td><td>0</td><td>2</td><td>9</td><td>0</td><td>1</td><td>11</td><td>3</td><td>0</td><td>2</td><td>8.22</td><td>9.98</td><td>9.77</td><td>10.23</td><td>5.58</td><td>1.96</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.33</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15486">박명근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.34</td><td>33</td><td>0</td><td>33</td><td>3</td><td>0</td><td>0</td><td>2</td><td>2</td><td>1</td><td>8</td><td>25.1</td><td>18</td><td>20</td><td>20.65</td><td>120</td><td>29</td><td>4</td><td>0</td><td>6</td><td>12</td><td>3</td><td>0</td><td>13</td><td>3</td><td>0</td><td>0</td><td>6.39</td><td>7.11</td><td>7.34</td><td>7.79</td><td>7.57</td><td>1.62</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.34</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16017">정지헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.41</td><td>17</td><td>0</td><td>17</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>12.1</td><td>16</td><td>18</td><td>15.65</td><td>69</td><td>19</td><td>2</td><td>0</td><td>2</td><td>11</td><td>3</td><td>0</td><td>11</td><td>2</td><td>0</td><td>3</td><td>11.68</td><td>13.14</td><td>11.42</td><td>11.87</td><td>7.42</td><td>2.43</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.41</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13009">백승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.50</td><td>36</td><td>0</td><td>36</td><td>7</td><td>0</td><td>0</td><td>2</td><td>1</td><td>2</td><td>1</td><td>26.2</td><td>27</td><td>28</td><td>25.60</td><td>135</td><td>33</td><td>7</td><td>0</td><td>3</td><td>22</td><td>2</td><td>2</td><td>14</td><td>0</td><td>0</td><td>1</td><td>9.11</td><td>9.45</td><td>8.64</td><td>8.92</td><td>6.90</td><td>2.06</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.50</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10749">이우찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">24</span> <span><img src="/data/team/ci/2024/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.73</td><td>42</td><td>1</td><td>41</td><td>3</td><td>0</td><td>0</td><td>3</td><td>2</td><td>0</td><td>6</td><td>33.2</td><td>33</td><td>35</td><td>33.15</td><td>172</td><td>42</td><td>6</td><td>1</td><td>2</td><td>30</td><td>1</td><td>0</td><td>31</td><td>4</td><td>1</td><td>6</td><td>8.82</td><td>9.36</td><td>8.86</td><td>8.94</td><td>5.46</td><td>2.14</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.73</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12295">윌커슨</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">6.81</td><td>32</td><td>32</td><td>0</td><td>1</td><td>1</td><td>1</td><td>12</td><td>8</td><td>0</td><td>0</td><td>196.2</td><td>84</td><td>90</td><td>88.80</td><td>816</td><td>210</td><td>37</td><td>3</td><td>18</td><td>27</td><td>2</td><td>0</td><td>167</td><td>13</td><td>0</td><td>3</td><td>3.84</td><td>4.12</td><td>4.06</td><td>3.91</td><td>3.62</td><td>1.21</td><td style="background-color:#F3F3F3; font-weight:bold;">6.81</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15011">반즈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">6.43</td><td>25</td><td>25</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9</td><td>6</td><td>0</td><td>0</td><td>150.2</td><td>56</td><td>59</td><td>55.90</td><td>624</td><td>140</td><td>17</td><td>4</td><td>18</td><td>46</td><td>5</td><td>0</td><td>171</td><td>8</td><td>0</td><td>6</td><td>3.35</td><td>3.52</td><td>3.34</td><td>3.18</td><td>3.83</td><td>1.23</td><td style="background-color:#F3F3F3; font-weight:bold;">6.43</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11310">박세웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.06</td><td>30</td><td>30</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td><td>11</td><td>0</td><td>0</td><td>173.1</td><td>92</td><td>103</td><td>97.65</td><td>759</td><td>188</td><td>33</td><td>0</td><td>13</td><td>56</td><td>11</td><td>0</td><td>124</td><td>12</td><td>0</td><td>10</td><td>4.78</td><td>5.35</td><td>5.07</td><td>4.97</td><td>4.50</td><td>1.41</td><td style="background-color:#F3F3F3; font-weight:bold;">4.06</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10825">김원중</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.44</td><td>56</td><td>0</td><td>56</td><td>42</td><td>0</td><td>0</td><td>3</td><td>6</td><td>25</td><td>0</td><td>63.1</td><td>25</td><td>27</td><td>28.50</td><td>277</td><td>59</td><td>8</td><td>0</td><td>4</td><td>31</td><td>1</td><td>7</td><td>68</td><td>2</td><td>0</td><td>5</td><td>3.55</td><td>3.84</td><td>4.05</td><td>3.85</td><td>3.64</td><td>1.42</td><td style="background-color:#F3F3F3; font-weight:bold;">2.44</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14792">김진욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.02</td><td>19</td><td>18</td><td>1</td><td>0</td><td>0</td><td>0</td><td>4</td><td>3</td><td>0</td><td>0</td><td>84.2</td><td>50</td><td>54</td><td>49.85</td><td>388</td><td>89</td><td>21</td><td>3</td><td>13</td><td>44</td><td>3</td><td>0</td><td>87</td><td>6</td><td>0</td><td>5</td><td>5.31</td><td>5.74</td><td>5.30</td><td>5.04</td><td>5.18</td><td>1.57</td><td style="background-color:#F3F3F3; font-weight:bold;">2.02</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10863">한현희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.58</td><td>57</td><td>5</td><td>52</td><td>5</td><td>0</td><td>0</td><td>5</td><td>3</td><td>0</td><td>8</td><td>76.1</td><td>44</td><td>45</td><td>44.45</td><td>342</td><td>92</td><td>18</td><td>1</td><td>7</td><td>24</td><td>10</td><td>1</td><td>70</td><td>3</td><td>0</td><td>4</td><td>5.19</td><td>5.31</td><td>5.24</td><td>4.97</td><td>4.38</td><td>1.52</td><td style="background-color:#F3F3F3; font-weight:bold;">1.58</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14163">박진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.12</td><td>38</td><td>3</td><td>35</td><td>11</td><td>0</td><td>0</td><td>2</td><td>4</td><td>1</td><td>0</td><td>49.1</td><td>24</td><td>28</td><td>27.65</td><td>214</td><td>60</td><td>9</td><td>1</td><td>4</td><td>11</td><td>2</td><td>0</td><td>35</td><td>0</td><td>0</td><td>4</td><td>4.38</td><td>5.11</td><td>5.04</td><td>4.72</td><td>4.21</td><td>1.44</td><td style="background-color:#F3F3F3; font-weight:bold;">1.12</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10427">김상수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.12</td><td>74</td><td>0</td><td>74</td><td>10</td><td>0</td><td>0</td><td>8</td><td>4</td><td>2</td><td>17</td><td>73.2</td><td>34</td><td>40</td><td>45.40</td><td>322</td><td>71</td><td>11</td><td>1</td><td>5</td><td>26</td><td>5</td><td>2</td><td>56</td><td>6</td><td>1</td><td>6</td><td>4.15</td><td>4.89</td><td>5.55</td><td>5.38</td><td>4.33</td><td>1.32</td><td style="background-color:#F3F3F3; font-weight:bold;">1.12</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16090">정현수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.83</td><td>18</td><td>4</td><td>14</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td><td>23.2</td><td>12</td><td>12</td><td>10.75</td><td>104</td><td>20</td><td>7</td><td>0</td><td>0</td><td>12</td><td>2</td><td>0</td><td>25</td><td>1</td><td>0</td><td>0</td><td>4.56</td><td>4.56</td><td>4.09</td><td>3.85</td><td>3.39</td><td>1.35</td><td style="background-color:#F3F3F3; font-weight:bold;">0.83</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12699">김강현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.53</td><td>26</td><td>0</td><td>26</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>25.1</td><td>10</td><td>13</td><td>13.70</td><td>123</td><td>28</td><td>4</td><td>0</td><td>2</td><td>18</td><td>2</td><td>1</td><td>24</td><td>3</td><td>0</td><td>3</td><td>3.55</td><td>4.62</td><td>4.87</td><td>4.54</td><td>5.10</td><td>1.82</td><td style="background-color:#F3F3F3; font-weight:bold;">0.53</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16089">전미르</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.42</td><td>36</td><td>0</td><td>36</td><td>6</td><td>0</td><td>0</td><td>1</td><td>5</td><td>1</td><td>5</td><td>33.2</td><td>22</td><td>28</td><td>22.50</td><td>155</td><td>33</td><td>10</td><td>0</td><td>4</td><td>21</td><td>1</td><td>2</td><td>34</td><td>4</td><td>0</td><td>3</td><td>5.88</td><td>7.49</td><td>6.01</td><td>5.62</td><td>5.02</td><td>1.60</td><td style="background-color:#F3F3F3; font-weight:bold;">0.42</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11425">박진형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.21</td><td>7</td><td>0</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6.1</td><td>3</td><td>3</td><td>2.65</td><td>24</td><td>6</td><td>1</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>4</td><td>0</td><td>0</td><td>1</td><td>4.26</td><td>4.26</td><td>3.77</td><td>3.76</td><td>3.60</td><td>1.11</td><td style="background-color:#F3F3F3; font-weight:bold;">0.21</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11291">구승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.19</td><td>66</td><td>0</td><td>66</td><td>7</td><td>0</td><td>0</td><td>5</td><td>3</td><td>0</td><td>13</td><td>57.2</td><td>31</td><td>37</td><td>42.70</td><td>279</td><td>68</td><td>10</td><td>0</td><td>6</td><td>35</td><td>6</td><td>1</td><td>62</td><td>5</td><td>0</td><td>7</td><td>4.84</td><td>5.77</td><td>6.66</td><td>6.44</td><td>4.90</td><td>1.79</td><td style="background-color:#F3F3F3; font-weight:bold;">0.19</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14624">최준용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.17</td><td>27</td><td>0</td><td>27</td><td>4</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>3</td><td>21.2</td><td>13</td><td>13</td><td>15.55</td><td>105</td><td>28</td><td>2</td><td>1</td><td>2</td><td>14</td><td>1</td><td>1</td><td>12</td><td>1</td><td>0</td><td>1</td><td>5.40</td><td>5.40</td><td>6.46</td><td>6.02</td><td>5.92</td><td>1.94</td><td style="background-color:#F3F3F3; font-weight:bold;">0.17</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15045">이민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.07</td><td>18</td><td>5</td><td>13</td><td>5</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>1</td><td>31.0</td><td>25</td><td>27</td><td>25.60</td><td>153</td><td>38</td><td>5</td><td>3</td><td>3</td><td>25</td><td>2</td><td>0</td><td>20</td><td>1</td><td>0</td><td>1</td><td>7.26</td><td>7.84</td><td>7.43</td><td>7.14</td><td>6.44</td><td>2.03</td><td style="background-color:#F3F3F3; font-weight:bold;">0.07</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10795">임준섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.06</td><td>24</td><td>0</td><td>24</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>11.1</td><td>10</td><td>11</td><td>8.95</td><td>56</td><td>12</td><td>2</td><td>1</td><td>0</td><td>11</td><td>3</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>7.94</td><td>8.74</td><td>7.11</td><td>6.62</td><td>7.37</td><td>2.03</td><td style="background-color:#F3F3F3; font-weight:bold;">0.06</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15047">진승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.03</td><td>7</td><td>0</td><td>7</td><td>3</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>6.1</td><td>6</td><td>6</td><td>5.00</td><td>32</td><td>7</td><td>3</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>5</td><td>2</td><td>0</td><td>0</td><td>8.53</td><td>8.53</td><td>7.11</td><td>6.48</td><td>4.67</td><td>1.89</td><td style="background-color:#F3F3F3; font-weight:bold;">0.03</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14795">정우준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.03</td><td>8</td><td>0</td><td>8</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8.1</td><td>4</td><td>4</td><td>6.60</td><td>40</td><td>10</td><td>2</td><td>0</td><td>2</td><td>7</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td>4.32</td><td>4.32</td><td>7.13</td><td>6.76</td><td>8.16</td><td>2.04</td><td style="background-color:#F3F3F3; font-weight:bold;">0.03</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16092">박준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>2</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.0</td><td>2</td><td>2</td><td>2.00</td><td>10</td><td>3</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>9.00</td><td>9.00</td><td>9.00</td><td>9.03</td><td>4.50</td><td>2.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14816">우강훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>1</td><td>1</td><td>0.65</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>99.99</td><td>99.99</td><td>23.00</td><td>21.79</td><td>9304.20</td><td>99.99</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13148">김도규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>5</td><td>0</td><td>5</td><td>3</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>4.0</td><td>4</td><td>4</td><td>3.30</td><td>25</td><td>5</td><td>1</td><td>0</td><td>0</td><td>6</td><td>2</td><td>1</td><td>5</td><td>0</td><td>1</td><td>0</td><td>9.00</td><td>9.00</td><td>7.43</td><td>8.06</td><td>7.27</td><td>2.75</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14625">홍민기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.06</td><td>3</td><td>1</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.2</td><td>5</td><td>7</td><td>5.15</td><td>24</td><td>8</td><td>3</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>2</td><td>2</td><td>0</td><td>3</td><td>12.27</td><td>17.18</td><td>12.64</td><td>11.95</td><td>5.37</td><td>2.45</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.06</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10075">진해수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.17</td><td>54</td><td>0</td><td>54</td><td>3</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>5</td><td>27.2</td><td>19</td><td>21</td><td>23.55</td><td>128</td><td>36</td><td>3</td><td>0</td><td>5</td><td>10</td><td>3</td><td>1</td><td>22</td><td>0</td><td>0</td><td>2</td><td>6.18</td><td>6.83</td><td>7.66</td><td>7.29</td><td>5.82</td><td>1.66</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.17</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12928">윤성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.21</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1.0</td><td>5</td><td>5</td><td>4.30</td><td>9</td><td>4</td><td>1</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>45.00</td><td>45.00</td><td>38.70</td><td>36.04</td><td>19.80</td><td>6.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.21</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13271">현도훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.30</td><td>8</td><td>0</td><td>8</td><td>5</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>10.0</td><td>10</td><td>11</td><td>12.05</td><td>50</td><td>15</td><td>3</td><td>1</td><td>2</td><td>6</td><td>0</td><td>0</td><td>8</td><td>2</td><td>0</td><td>1</td><td>9.00</td><td>9.90</td><td>10.85</td><td>9.99</td><td>6.44</td><td>2.10</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.30</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11232">이인복</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.31</td><td>8</td><td>6</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>33.0</td><td>35</td><td>35</td><td>36.05</td><td>159</td><td>49</td><td>14</td><td>0</td><td>10</td><td>13</td><td>3</td><td>0</td><td>20</td><td>1</td><td>0</td><td>4</td><td>9.55</td><td>9.55</td><td>9.83</td><td>9.35</td><td>7.79</td><td>1.88</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.31</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14794">송재영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.36</td><td>19</td><td>0</td><td>19</td><td>4</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>3</td><td>8.1</td><td>10</td><td>10</td><td>10.40</td><td>40</td><td>9</td><td>3</td><td>0</td><td>2</td><td>5</td><td>1</td><td>0</td><td>9</td><td>0</td><td>1</td><td>1</td><td>10.80</td><td>10.80</td><td>11.23</td><td>10.38</td><td>6.59</td><td>1.68</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.36</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12930">나균안</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.64</td><td>26</td><td>14</td><td>12</td><td>4</td><td>0</td><td>0</td><td>4</td><td>7</td><td>0</td><td>0</td><td>73.0</td><td>69</td><td>73</td><td>73.50</td><td>380</td><td>114</td><td>19</td><td>0</td><td>15</td><td>47</td><td>5</td><td>0</td><td>74</td><td>2</td><td>0</td><td>10</td><td>8.51</td><td>9.00</td><td>9.06</td><td>8.73</td><td>6.32</td><td>2.21</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.64</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13169">최이준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">24</span> <span><img src="/data/team/ci/2024/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.70</td><td>23</td><td>0</td><td>23</td><td>11</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>24.2</td><td>20</td><td>22</td><td>27.85</td><td>126</td><td>40</td><td>6</td><td>1</td><td>3</td><td>16</td><td>1</td><td>1</td><td>17</td><td>1</td><td>0</td><td>1</td><td>7.30</td><td>8.03</td><td>10.16</td><td>9.76</td><td>6.06</td><td>2.27</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.70</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10058">양현종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.01</td><td>29</td><td>29</td><td>0</td><td>3</td><td>3</td><td>0</td><td>11</td><td>5</td><td>0</td><td>0</td><td>171.1</td><td>78</td><td>86</td><td>83.10</td><td>727</td><td>174</td><td>37</td><td>6</td><td>21</td><td>41</td><td>6</td><td>0</td><td>129</td><td>11</td><td>0</td><td>2</td><td>4.10</td><td>4.52</td><td>4.37</td><td>4.37</td><td>4.63</td><td>1.25</td><td style="background-color:#F3F3F3; font-weight:bold;">5.01</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16088">네일</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.90</td><td>26</td><td>26</td><td>0</td><td>0</td><td>0</td><td>0</td><td>12</td><td>5</td><td>0</td><td>0</td><td>149.1</td><td>42</td><td>69</td><td>67.30</td><td>642</td><td>154</td><td>27</td><td>1</td><td>11</td><td>35</td><td>9</td><td>0</td><td>138</td><td>17</td><td>1</td><td>3</td><td>2.53</td><td>4.16</td><td>4.06</td><td>4.04</td><td>3.68</td><td>1.27</td><td style="background-color:#F3F3F3; font-weight:bold;">4.90</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14608">정해영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.44</td><td>53</td><td>0</td><td>53</td><td>44</td><td>0</td><td>0</td><td>2</td><td>3</td><td>31</td><td>1</td><td>50.2</td><td>14</td><td>14</td><td>16.90</td><td>210</td><td>47</td><td>5</td><td>1</td><td>8</td><td>16</td><td>1</td><td>2</td><td>50</td><td>1</td><td>0</td><td>0</td><td>2.49</td><td>2.49</td><td>3.00</td><td>2.98</td><td>4.59</td><td>1.24</td><td style="background-color:#F3F3F3; font-weight:bold;">2.44</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15432">윤영철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.18</td><td>18</td><td>18</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>4</td><td>0</td><td>0</td><td>81.2</td><td>38</td><td>44</td><td>42.65</td><td>362</td><td>82</td><td>14</td><td>1</td><td>8</td><td>43</td><td>1</td><td>0</td><td>58</td><td>7</td><td>0</td><td>1</td><td>4.19</td><td>4.85</td><td>4.70</td><td>4.61</td><td>5.26</td><td>1.53</td><td style="background-color:#F3F3F3; font-weight:bold;">2.18</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15063">황동하</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.13</td><td>25</td><td>21</td><td>4</td><td>4</td><td>0</td><td>0</td><td>5</td><td>7</td><td>0</td><td>0</td><td>103.1</td><td>51</td><td>64</td><td>59.55</td><td>464</td><td>109</td><td>18</td><td>0</td><td>13</td><td>44</td><td>8</td><td>0</td><td>81</td><td>7</td><td>0</td><td>5</td><td>4.44</td><td>5.57</td><td>5.19</td><td>5.19</td><td>5.30</td><td>1.48</td><td style="background-color:#F3F3F3; font-weight:bold;">2.13</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11164">장현식</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.94</td><td>75</td><td>0</td><td>75</td><td>6</td><td>0</td><td>0</td><td>5</td><td>4</td><td>0</td><td>16</td><td>75.1</td><td>33</td><td>41</td><td>37.40</td><td>331</td><td>75</td><td>16</td><td>0</td><td>8</td><td>34</td><td>2</td><td>2</td><td>75</td><td>5</td><td>0</td><td>4</td><td>3.94</td><td>4.90</td><td>4.47</td><td>4.43</td><td>4.37</td><td>1.45</td><td style="background-color:#F3F3F3; font-weight:bold;">1.94</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12537">전상현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.64</td><td>66</td><td>0</td><td>66</td><td>16</td><td>0</td><td>0</td><td>10</td><td>5</td><td>7</td><td>19</td><td>66.0</td><td>30</td><td>32</td><td>33.75</td><td>272</td><td>55</td><td>7</td><td>2</td><td>5</td><td>20</td><td>5</td><td>1</td><td>54</td><td>1</td><td>0</td><td>2</td><td>4.09</td><td>4.36</td><td>4.60</td><td>4.70</td><td>4.18</td><td>1.14</td><td style="background-color:#F3F3F3; font-weight:bold;">1.64</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16151">알드레드</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.37</td><td>9</td><td>9</td><td>0</td><td>1</td><td>1</td><td>1</td><td>3</td><td>2</td><td>0</td><td>0</td><td>43.2</td><td>22</td><td>24</td><td>20.35</td><td>184</td><td>38</td><td>4</td><td>0</td><td>4</td><td>17</td><td>2</td><td>0</td><td>52</td><td>4</td><td>0</td><td>1</td><td>4.53</td><td>4.95</td><td>4.19</td><td>4.18</td><td>3.66</td><td>1.26</td><td style="background-color:#F3F3F3; font-weight:bold;">1.37</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15435">곽도규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.33</td><td>71</td><td>0</td><td>71</td><td>3</td><td>0</td><td>0</td><td>4</td><td>2</td><td>2</td><td>16</td><td>55.2</td><td>22</td><td>24</td><td>28.60</td><td>248</td><td>43</td><td>7</td><td>0</td><td>4</td><td>34</td><td>4</td><td>1</td><td>64</td><td>5</td><td>0</td><td>7</td><td>3.56</td><td>3.88</td><td>4.62</td><td>4.56</td><td>4.24</td><td>1.38</td><td style="background-color:#F3F3F3; font-weight:bold;">1.33</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16087">크로우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.25</td><td>8</td><td>8</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>1</td><td>0</td><td>0</td><td>40.1</td><td>16</td><td>19</td><td>18.00</td><td>172</td><td>41</td><td>7</td><td>0</td><td>2</td><td>12</td><td>1</td><td>1</td><td>43</td><td>1</td><td>0</td><td>0</td><td>3.57</td><td>4.24</td><td>4.02</td><td>4.21</td><td>3.05</td><td>1.31</td><td style="background-color:#F3F3F3; font-weight:bold;">1.25</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14128">김도현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.23</td><td>35</td><td>10</td><td>25</td><td>6</td><td>0</td><td>0</td><td>4</td><td>6</td><td>0</td><td>3</td><td>75.0</td><td>41</td><td>45</td><td>45.85</td><td>345</td><td>87</td><td>11</td><td>1</td><td>9</td><td>31</td><td>9</td><td>0</td><td>59</td><td>2</td><td>0</td><td>4</td><td>4.92</td><td>5.40</td><td>5.50</td><td>5.42</td><td>5.31</td><td>1.57</td><td style="background-color:#F3F3F3; font-weight:bold;">1.23</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16161">라우어</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.89</td><td>7</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>34.2</td><td>19</td><td>19</td><td>17.80</td><td>150</td><td>35</td><td>7</td><td>1</td><td>3</td><td>12</td><td>3</td><td>0</td><td>37</td><td>0</td><td>0</td><td>0</td><td>4.93</td><td>4.93</td><td>4.62</td><td>4.70</td><td>3.90</td><td>1.36</td><td style="background-color:#F3F3F3; font-weight:bold;">0.89</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11303">이준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.42</td><td>56</td><td>0</td><td>56</td><td>5</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>9</td><td>35.0</td><td>15</td><td>21</td><td>22.15</td><td>160</td><td>37</td><td>8</td><td>0</td><td>5</td><td>17</td><td>2</td><td>3</td><td>33</td><td>4</td><td>0</td><td>0</td><td>3.86</td><td>5.40</td><td>5.70</td><td>5.64</td><td>4.96</td><td>1.54</td><td style="background-color:#F3F3F3; font-weight:bold;">0.42</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15057">최지민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.41</td><td>56</td><td>0</td><td>56</td><td>4</td><td>0</td><td>0</td><td>3</td><td>3</td><td>3</td><td>12</td><td>46.0</td><td>26</td><td>28</td><td>29.90</td><td>225</td><td>44</td><td>10</td><td>1</td><td>2</td><td>40</td><td>4</td><td>0</td><td>37</td><td>4</td><td>0</td><td>6</td><td>5.09</td><td>5.48</td><td>5.85</td><td>5.88</td><td>5.67</td><td>1.83</td><td style="background-color:#F3F3F3; font-weight:bold;">0.41</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16163">스타우트</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.33</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>16.0</td><td>9</td><td>10</td><td>9.50</td><td>73</td><td>17</td><td>3</td><td>1</td><td>2</td><td>5</td><td>3</td><td>0</td><td>20</td><td>1</td><td>0</td><td>1</td><td>5.06</td><td>5.63</td><td>5.34</td><td>5.22</td><td>4.11</td><td>1.38</td><td style="background-color:#F3F3F3; font-weight:bold;">0.33</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12637">김승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.20</td><td>14</td><td>0</td><td>14</td><td>4</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>18.0</td><td>8</td><td>12</td><td>11.95</td><td>85</td><td>23</td><td>5</td><td>1</td><td>3</td><td>7</td><td>0</td><td>0</td><td>11</td><td>2</td><td>0</td><td>0</td><td>4.00</td><td>6.00</td><td>5.98</td><td>5.85</td><td>5.86</td><td>1.67</td><td style="background-color:#F3F3F3; font-weight:bold;">0.20</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12914">유승철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.13</td><td>5</td><td>0</td><td>5</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5.0</td><td>3</td><td>3</td><td>1.80</td><td>23</td><td>3</td><td>1</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>2</td><td>5.40</td><td>5.40</td><td>3.24</td><td>3.54</td><td>6.54</td><td>2.00</td><td style="background-color:#F3F3F3; font-weight:bold;">0.13</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14788">이의리</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.07</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>13.1</td><td>8</td><td>10</td><td>10.00</td><td>69</td><td>17</td><td>3</td><td>0</td><td>3</td><td>14</td><td>0</td><td>0</td><td>14</td><td>1</td><td>0</td><td>0</td><td>5.40</td><td>6.75</td><td>6.75</td><td>6.90</td><td>7.51</td><td>2.33</td><td style="background-color:#F3F3F3; font-weight:bold;">0.07</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14176">김기훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.06</td><td>17</td><td>0</td><td>17</td><td>4</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>19.2</td><td>11</td><td>13</td><td>14.60</td><td>95</td><td>16</td><td>4</td><td>1</td><td>1</td><td>15</td><td>3</td><td>0</td><td>17</td><td>3</td><td>1</td><td>1</td><td>5.03</td><td>5.95</td><td>6.68</td><td>6.71</td><td>5.48</td><td>1.58</td><td style="background-color:#F3F3F3; font-weight:bold;">0.06</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14657">장재혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.06</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.1</td><td>0</td><td>0</td><td>0.00</td><td>7</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>6.52</td><td>2.25</td><td style="background-color:#F3F3F3; font-weight:bold;">0.06</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12869">박정우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.04</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0.00</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>-0.80</td><td>0.00</td><td style="background-color:#F3F3F3; font-weight:bold;">0.04</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11364">김사윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>23</td><td>2</td><td>21</td><td>10</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>37.0</td><td>19</td><td>29</td><td>30.05</td><td>173</td><td>40</td><td>6</td><td>2</td><td>2</td><td>25</td><td>5</td><td>0</td><td>36</td><td>1</td><td>0</td><td>4</td><td>4.62</td><td>7.05</td><td>7.31</td><td>7.29</td><td>4.92</td><td>1.76</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11070">박준표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>8</td><td>0</td><td>8</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>6.0</td><td>4</td><td>4</td><td>5.20</td><td>29</td><td>10</td><td>2</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>6.00</td><td>6.00</td><td>7.80</td><td>7.71</td><td>4.60</td><td>2.17</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14607">유지성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.04</td><td>3</td><td>0</td><td>3</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.1</td><td>2</td><td>4</td><td>2.80</td><td>14</td><td>5</td><td>0</td><td>0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>7.71</td><td>15.43</td><td>10.80</td><td>10.82</td><td>7.41</td><td>2.14</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.04</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16082">김민주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.13</td><td>2</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.0</td><td>1</td><td>2</td><td>2.85</td><td>8</td><td>3</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>1</td><td>9.00</td><td>18.00</td><td>25.65</td><td>25.68</td><td>2.30</td><td>4.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.13</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16083">김민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.15</td><td>4</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4.0</td><td>7</td><td>7</td><td>7.00</td><td>22</td><td>9</td><td>0</td><td>0</td><td>3</td><td>1</td><td>1</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>15.75</td><td>15.75</td><td>15.75</td><td>14.94</td><td>12.80</td><td>2.50</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.15</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10909">임기영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.16</td><td>37</td><td>3</td><td>34</td><td>3</td><td>0</td><td>0</td><td>6</td><td>2</td><td>0</td><td>2</td><td>45.2</td><td>32</td><td>35</td><td>37.20</td><td>218</td><td>61</td><td>12</td><td>0</td><td>8</td><td>17</td><td>1</td><td>1</td><td>36</td><td>4</td><td>1</td><td>1</td><td>6.31</td><td>6.90</td><td>7.33</td><td>7.37</td><td>5.47</td><td>1.71</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.16</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12944">김건국</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.23</td><td>20</td><td>3</td><td>17</td><td>3</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>34.1</td><td>30</td><td>33</td><td>31.10</td><td>165</td><td>48</td><td>8</td><td>0</td><td>5</td><td>14</td><td>2</td><td>0</td><td>20</td><td>3</td><td>0</td><td>3</td><td>7.86</td><td>8.65</td><td>8.15</td><td>8.14</td><td>5.92</td><td>1.81</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.23</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11159">이형범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.30</td><td>16</td><td>0</td><td>16</td><td>5</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>2</td><td>15.0</td><td>13</td><td>17</td><td>15.80</td><td>83</td><td>26</td><td>4</td><td>0</td><td>2</td><td>7</td><td>5</td><td>1</td><td>9</td><td>2</td><td>0</td><td>0</td><td>7.80</td><td>10.20</td><td>9.48</td><td>9.66</td><td>6.77</td><td>2.20</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.30</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14162">김현수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.31</td><td>5</td><td>0</td><td>5</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5.0</td><td>10</td><td>10</td><td>10.15</td><td>28</td><td>7</td><td>4</td><td>0</td><td>0</td><td>5</td><td>1</td><td>0</td><td>4</td><td>0</td><td>0</td><td>2</td><td>18.00</td><td>18.00</td><td>18.27</td><td>18.33</td><td>5.92</td><td>2.40</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.31</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10706">김대유</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.61</td><td>37</td><td>0</td><td>37</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8</td><td>25.0</td><td>23</td><td>23</td><td>26.45</td><td>122</td><td>35</td><td>5</td><td>0</td><td>4</td><td>12</td><td>2</td><td>0</td><td>26</td><td>0</td><td>0</td><td>1</td><td>8.28</td><td>8.28</td><td>9.52</td><td>9.57</td><td>5.24</td><td>1.88</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.61</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13122">윤중현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">24</span> <span><img src="/data/team/ci/2024/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.82</td><td>11</td><td>0</td><td>11</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10.1</td><td>16</td><td>17</td><td>19.25</td><td>62</td><td>22</td><td>2</td><td>1</td><td>4</td><td>9</td><td>3</td><td>1</td><td>4</td><td>1</td><td>0</td><td>0</td><td>13.94</td><td>14.81</td><td>16.77</td><td>16.88</td><td>11.14</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.82</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13942">쿠에바스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.06</td><td>31</td><td>31</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>12</td><td>0</td><td>0</td><td>173.1</td><td>79</td><td>86</td><td>86.00</td><td>737</td><td>158</td><td>36</td><td>3</td><td>17</td><td>59</td><td>7</td><td>4</td><td>154</td><td>11</td><td>1</td><td>11</td><td>4.10</td><td>4.47</td><td>4.47</td><td>4.34</td><td>4.25</td><td>1.25</td><td style="background-color:#F3F3F3; font-weight:bold;">5.06</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11318">엄상백</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.93</td><td>29</td><td>29</td><td>0</td><td>0</td><td>0</td><td>0</td><td>13</td><td>10</td><td>0</td><td>0</td><td>156.2</td><td>85</td><td>88</td><td>85.40</td><td>675</td><td>164</td><td>26</td><td>3</td><td>26</td><td>42</td><td>7</td><td>0</td><td>159</td><td>3</td><td>0</td><td>2</td><td>4.88</td><td>5.06</td><td>4.91</td><td>4.74</td><td>4.61</td><td>1.31</td><td style="background-color:#F3F3F3; font-weight:bold;">3.93</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15143">벤자민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.19</td><td>28</td><td>28</td><td>0</td><td>0</td><td>0</td><td>0</td><td>11</td><td>8</td><td>0</td><td>0</td><td>149.2</td><td>77</td><td>90</td><td>86.65</td><td>639</td><td>141</td><td>25</td><td>4</td><td>28</td><td>48</td><td>4</td><td>2</td><td>156</td><td>12</td><td>0</td><td>4</td><td>4.63</td><td>5.41</td><td>5.21</td><td>5.11</td><td>4.88</td><td>1.26</td><td style="background-color:#F3F3F3; font-weight:bold;">3.19</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15089">박영현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.72</td><td>66</td><td>0</td><td>66</td><td>52</td><td>0</td><td>0</td><td>10</td><td>2</td><td>25</td><td>0</td><td>76.2</td><td>30</td><td>31</td><td>32.85</td><td>310</td><td>63</td><td>7</td><td>1</td><td>12</td><td>22</td><td>0</td><td>2</td><td>87</td><td>3</td><td>0</td><td>1</td><td>3.52</td><td>3.64</td><td>3.86</td><td>3.82</td><td>4.07</td><td>1.11</td><td style="background-color:#F3F3F3; font-weight:bold;">2.72</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13167">김민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.10</td><td>71</td><td>1</td><td>70</td><td>5</td><td>0</td><td>0</td><td>8</td><td>4</td><td>0</td><td>21</td><td>77.1</td><td>37</td><td>38</td><td>36.45</td><td>336</td><td>84</td><td>13</td><td>0</td><td>5</td><td>27</td><td>2</td><td>3</td><td>77</td><td>3</td><td>0</td><td>5</td><td>4.31</td><td>4.42</td><td>4.24</td><td>4.20</td><td>3.60</td><td>1.44</td><td style="background-color:#F3F3F3; font-weight:bold;">2.10</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11308">고영표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.86</td><td>18</td><td>17</td><td>1</td><td>0</td><td>0</td><td>0</td><td>6</td><td>8</td><td>0</td><td>0</td><td>100.0</td><td>55</td><td>61</td><td>59.80</td><td>456</td><td>141</td><td>27</td><td>4</td><td>6</td><td>14</td><td>11</td><td>0</td><td>79</td><td>4</td><td>1</td><td>2</td><td>4.95</td><td>5.49</td><td>5.38</td><td>5.31</td><td>3.71</td><td>1.55</td><td style="background-color:#F3F3F3; font-weight:bold;">1.86</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10523">우규민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.48</td><td>45</td><td>0</td><td>45</td><td>15</td><td>0</td><td>0</td><td>4</td><td>1</td><td>1</td><td>4</td><td>43.1</td><td>12</td><td>14</td><td>15.90</td><td>181</td><td>47</td><td>7</td><td>2</td><td>1</td><td>2</td><td>2</td><td>0</td><td>39</td><td>4</td><td>0</td><td>0</td><td>2.49</td><td>2.91</td><td>3.30</td><td>3.15</td><td>2.51</td><td>1.13</td><td style="background-color:#F3F3F3; font-weight:bold;">1.48</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11317">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.70</td><td>75</td><td>0</td><td>75</td><td>6</td><td>0</td><td>0</td><td>5</td><td>3</td><td>0</td><td>12</td><td>81.1</td><td>47</td><td>56</td><td>54.45</td><td>358</td><td>84</td><td>13</td><td>5</td><td>8</td><td>33</td><td>1</td><td>2</td><td>75</td><td>8</td><td>0</td><td>3</td><td>5.20</td><td>6.20</td><td>6.03</td><td>5.92</td><td>4.28</td><td>1.44</td><td style="background-color:#F3F3F3; font-weight:bold;">0.70</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16028">육청명</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.61</td><td>13</td><td>10</td><td>3</td><td>1</td><td>0</td><td>0</td><td>1</td><td>5</td><td>0</td><td>0</td><td>44.2</td><td>27</td><td>31</td><td>28.95</td><td>208</td><td>52</td><td>13</td><td>1</td><td>6</td><td>20</td><td>6</td><td>2</td><td>20</td><td>6</td><td>0</td><td>3</td><td>5.44</td><td>6.25</td><td>5.83</td><td>5.85</td><td>6.41</td><td>1.61</td><td style="background-color:#F3F3F3; font-weight:bold;">0.61</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11284">조이현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.55</td><td>16</td><td>9</td><td>7</td><td>2</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>40.0</td><td>28</td><td>29</td><td>27.40</td><td>184</td><td>53</td><td>11</td><td>1</td><td>9</td><td>10</td><td>1</td><td>1</td><td>19</td><td>1</td><td>0</td><td>1</td><td>6.30</td><td>6.53</td><td>6.17</td><td>5.93</td><td>6.46</td><td>1.58</td><td style="background-color:#F3F3F3; font-weight:bold;">0.55</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10737">박시영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.36</td><td>26</td><td>0</td><td>26</td><td>5</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>4</td><td>25.1</td><td>13</td><td>13</td><td>15.40</td><td>110</td><td>27</td><td>8</td><td>1</td><td>4</td><td>7</td><td>1</td><td>1</td><td>23</td><td>0</td><td>0</td><td>3</td><td>4.62</td><td>4.62</td><td>5.47</td><td>5.36</td><td>4.67</td><td>1.34</td><td style="background-color:#F3F3F3; font-weight:bold;">0.36</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14600">소형준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.33</td><td>6</td><td>0</td><td>6</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>8.1</td><td>3</td><td>3</td><td>2.50</td><td>30</td><td>7</td><td>2</td><td>0</td><td>1</td><td>1</td><td>1</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3.24</td><td>3.24</td><td>2.70</td><td>2.59</td><td>5.47</td><td>0.96</td><td style="background-color:#F3F3F3; font-weight:bold;">0.33</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14108">손동현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.28</td><td>42</td><td>0</td><td>42</td><td>10</td><td>0</td><td>0</td><td>1</td><td>2</td><td>1</td><td>4</td><td>47.1</td><td>28</td><td>31</td><td>33.05</td><td>214</td><td>50</td><td>6</td><td>1</td><td>5</td><td>20</td><td>1</td><td>2</td><td>27</td><td>3</td><td>0</td><td>3</td><td>5.32</td><td>5.89</td><td>6.28</td><td>6.24</td><td>5.34</td><td>1.48</td><td style="background-color:#F3F3F3; font-weight:bold;">0.28</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14111">이선우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.14</td><td>6</td><td>1</td><td>5</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10.0</td><td>6</td><td>6</td><td>5.35</td><td>45</td><td>10</td><td>0</td><td>0</td><td>0</td><td>4</td><td>2</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>5.40</td><td>5.40</td><td>4.82</td><td>5.05</td><td>5.06</td><td>1.40</td><td style="background-color:#F3F3F3; font-weight:bold;">0.14</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16027">원상현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.04</td><td>22</td><td>10</td><td>12</td><td>3</td><td>0</td><td>0</td><td>2</td><td>5</td><td>0</td><td>1</td><td>65.1</td><td>51</td><td>54</td><td>52.80</td><td>324</td><td>105</td><td>18</td><td>2</td><td>6</td><td>31</td><td>2</td><td>0</td><td>59</td><td>3</td><td>1</td><td>7</td><td>7.03</td><td>7.44</td><td>7.27</td><td>7.30</td><td>4.60</td><td>2.08</td><td style="background-color:#F3F3F3; font-weight:bold;">0.04</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14869">김영현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.02</td><td>8</td><td>0</td><td>8</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7.1</td><td>4</td><td>6</td><td>6.35</td><td>39</td><td>9</td><td>2</td><td>0</td><td>1</td><td>7</td><td>1</td><td>0</td><td>8</td><td>1</td><td>0</td><td>1</td><td>4.91</td><td>7.36</td><td>7.79</td><td>7.47</td><td>6.48</td><td>2.18</td><td style="background-color:#F3F3F3; font-weight:bold;">0.02</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14109">이상동</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.01</td><td>29</td><td>0</td><td>29</td><td>8</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>3</td><td>32.0</td><td>19</td><td>20</td><td>24.45</td><td>152</td><td>42</td><td>9</td><td>0</td><td>3</td><td>14</td><td>3</td><td>1</td><td>30</td><td>0</td><td>1</td><td>4</td><td>5.34</td><td>5.63</td><td>6.88</td><td>6.95</td><td>4.62</td><td>1.75</td><td style="background-color:#F3F3F3; font-weight:bold;">0.01</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10304">하준호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.0</td><td>2</td><td>2</td><td>2.00</td><td>11</td><td>5</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9.00</td><td>9.00</td><td>9.00</td><td>8.38</td><td>5.75</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12572">박세진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.09</td><td>6</td><td>0</td><td>6</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5.1</td><td>2</td><td>4</td><td>6.20</td><td>25</td><td>7</td><td>1</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>3.38</td><td>6.75</td><td>10.46</td><td>10.37</td><td>5.59</td><td>2.06</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.09</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14667">성재헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.09</td><td>30</td><td>1</td><td>29</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>32.0</td><td>26</td><td>29</td><td>27.90</td><td>159</td><td>46</td><td>13</td><td>2</td><td>1</td><td>16</td><td>5</td><td>2</td><td>20</td><td>3</td><td>1</td><td>2</td><td>7.31</td><td>8.16</td><td>7.85</td><td>7.73</td><td>4.85</td><td>1.94</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.09</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13130">이채호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.13</td><td>9</td><td>0</td><td>9</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6.2</td><td>7</td><td>7</td><td>7.00</td><td>37</td><td>13</td><td>0</td><td>1</td><td>2</td><td>3</td><td>1</td><td>0</td><td>5</td><td>0</td><td>0</td><td>1</td><td>9.45</td><td>9.45</td><td>9.45</td><td>9.51</td><td>7.75</td><td>2.40</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.13</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11323">주권</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.18</td><td>48</td><td>1</td><td>47</td><td>13</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>58.0</td><td>43</td><td>48</td><td>49.90</td><td>254</td><td>78</td><td>14</td><td>2</td><td>7</td><td>11</td><td>3</td><td>0</td><td>31</td><td>2</td><td>0</td><td>0</td><td>6.67</td><td>7.45</td><td>7.74</td><td>7.60</td><td>5.05</td><td>1.53</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.18</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15527">강건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.18</td><td>4</td><td>1</td><td>3</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>4.0</td><td>5</td><td>5</td><td>5.85</td><td>24</td><td>8</td><td>0</td><td>1</td><td>1</td><td>4</td><td>1</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>11.25</td><td>11.25</td><td>13.16</td><td>13.69</td><td>9.17</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.18</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14106">전용주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.22</td><td>4</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.2</td><td>2</td><td>3</td><td>3.15</td><td>11</td><td>2</td><td>0</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>10.80</td><td>16.20</td><td>17.01</td><td>17.02</td><td>5.64</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.22</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14776">한차현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.24</td><td>10</td><td>5</td><td>5</td><td>2</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>19.0</td><td>21</td><td>22</td><td>19.70</td><td>103</td><td>29</td><td>4</td><td>1</td><td>4</td><td>18</td><td>0</td><td>0</td><td>17</td><td>1</td><td>0</td><td>2</td><td>9.95</td><td>10.42</td><td>9.33</td><td>9.40</td><td>7.40</td><td>2.47</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.24</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12885">문용익</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">24</span> <span><img src="/data/team/ci/2024/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.79</td><td>12</td><td>0</td><td>12</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>17.0</td><td>23</td><td>27</td><td>28.55</td><td>99</td><td>23</td><td>4</td><td>0</td><td>2</td><td>22</td><td>2</td><td>0</td><td>17</td><td>3</td><td>0</td><td>2</td><td>12.18</td><td>14.29</td><td>15.11</td><td>15.15</td><td>7.48</td><td>2.65</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.79</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15860">코너</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.95</td><td>28</td><td>28</td><td>0</td><td>1</td><td>1</td><td>1</td><td>11</td><td>6</td><td>0</td><td>0</td><td>160.0</td><td>61</td><td>67</td><td>65.45</td><td>663</td><td>135</td><td>17</td><td>3</td><td>21</td><td>40</td><td>19</td><td>0</td><td>158</td><td>4</td><td>0</td><td>9</td><td>3.43</td><td>3.77</td><td>3.68</td><td>3.54</td><td>4.44</td><td>1.09</td><td style="background-color:#F3F3F3; font-weight:bold;">5.95</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14113">원태인</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.87</td><td>28</td><td>28</td><td>0</td><td>1</td><td>1</td><td>0</td><td>15</td><td>6</td><td>0</td><td>0</td><td>159.2</td><td>65</td><td>68</td><td>67.30</td><td>670</td><td>150</td><td>29</td><td>3</td><td>17</td><td>42</td><td>7</td><td>1</td><td>119</td><td>5</td><td>0</td><td>3</td><td>3.66</td><td>3.83</td><td>3.79</td><td>3.58</td><td>4.55</td><td>1.20</td><td style="background-color:#F3F3F3; font-weight:bold;">5.87</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15861">레예스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.06</td><td>26</td><td>26</td><td>0</td><td>0</td><td>0</td><td>0</td><td>11</td><td>4</td><td>0</td><td>0</td><td>144.0</td><td>61</td><td>65</td><td>62.55</td><td>617</td><td>159</td><td>21</td><td>3</td><td>15</td><td>30</td><td>7</td><td>0</td><td>114</td><td>5</td><td>0</td><td>4</td><td>3.81</td><td>4.06</td><td>3.91</td><td>3.72</td><td>4.26</td><td>1.31</td><td style="background-color:#F3F3F3; font-weight:bold;">5.06</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14798">이승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.70</td><td>17</td><td>17</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td><td>4</td><td>0</td><td>0</td><td>87.1</td><td>41</td><td>44</td><td>41.90</td><td>384</td><td>88</td><td>11</td><td>1</td><td>9</td><td>37</td><td>6</td><td>0</td><td>68</td><td>3</td><td>0</td><td>4</td><td>4.23</td><td>4.53</td><td>4.32</td><td>4.11</td><td>5.01</td><td>1.43</td><td style="background-color:#F3F3F3; font-weight:bold;">2.70</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10452">임창민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.97</td><td>60</td><td>0</td><td>60</td><td>6</td><td>0</td><td>0</td><td>2</td><td>1</td><td>1</td><td>28</td><td>54.1</td><td>24</td><td>26</td><td>23.30</td><td>253</td><td>60</td><td>10</td><td>0</td><td>4</td><td>30</td><td>2</td><td>2</td><td>50</td><td>3</td><td>0</td><td>5</td><td>3.98</td><td>4.31</td><td>3.86</td><td>3.61</td><td>4.49</td><td>1.66</td><td style="background-color:#F3F3F3; font-weight:bold;">1.97</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12934">최지광</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.63</td><td>35</td><td>0</td><td>35</td><td>1</td><td>0</td><td>0</td><td>3</td><td>2</td><td>0</td><td>7</td><td>36.1</td><td>9</td><td>9</td><td>12.25</td><td>154</td><td>22</td><td>6</td><td>1</td><td>1</td><td>21</td><td>4</td><td>2</td><td>38</td><td>0</td><td>1</td><td>2</td><td>2.23</td><td>2.23</td><td>3.03</td><td>2.85</td><td>3.96</td><td>1.18</td><td style="background-color:#F3F3F3; font-weight:bold;">1.63</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11489">김재윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.42</td><td>65</td><td>0</td><td>65</td><td>21</td><td>0</td><td>0</td><td>4</td><td>8</td><td>11</td><td>25</td><td>66.0</td><td>30</td><td>37</td><td>37.45</td><td>284</td><td>58</td><td>9</td><td>1</td><td>13</td><td>25</td><td>1</td><td>5</td><td>51</td><td>5</td><td>0</td><td>2</td><td>4.09</td><td>5.05</td><td>5.11</td><td>4.81</td><td>5.69</td><td>1.26</td><td style="background-color:#F3F3F3; font-weight:bold;">1.42</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10871">김태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.32</td><td>56</td><td>0</td><td>56</td><td>8</td><td>0</td><td>0</td><td>3</td><td>2</td><td>0</td><td>23</td><td>52.1</td><td>23</td><td>24</td><td>25.55</td><td>225</td><td>49</td><td>8</td><td>1</td><td>6</td><td>19</td><td>4</td><td>1</td><td>37</td><td>2</td><td>1</td><td>2</td><td>3.96</td><td>4.13</td><td>4.39</td><td>4.34</td><td>5.16</td><td>1.30</td><td style="background-color:#F3F3F3; font-weight:bold;">1.32</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14615">황동재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.18</td><td>15</td><td>6</td><td>9</td><td>2</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>42.0</td><td>19</td><td>20</td><td>20.00</td><td>180</td><td>38</td><td>9</td><td>1</td><td>2</td><td>18</td><td>4</td><td>0</td><td>30</td><td>0</td><td>0</td><td>5</td><td>4.07</td><td>4.29</td><td>4.29</td><td>4.25</td><td>4.60</td><td>1.33</td><td style="background-color:#F3F3F3; font-weight:bold;">1.18</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10527">이승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.17</td><td>60</td><td>0</td><td>60</td><td>9</td><td>0</td><td>0</td><td>6</td><td>2</td><td>1</td><td>9</td><td>60.1</td><td>30</td><td>31</td><td>34.15</td><td>265</td><td>68</td><td>14</td><td>2</td><td>6</td><td>23</td><td>3</td><td>0</td><td>51</td><td>1</td><td>0</td><td>2</td><td>4.48</td><td>4.62</td><td>5.09</td><td>4.82</td><td>4.61</td><td>1.51</td><td style="background-color:#F3F3F3; font-weight:bold;">1.17</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10363">백정현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.05</td><td>17</td><td>15</td><td>2</td><td>1</td><td>0</td><td>0</td><td>6</td><td>5</td><td>0</td><td>0</td><td>78.2</td><td>52</td><td>56</td><td>54.80</td><td>360</td><td>104</td><td>15</td><td>2</td><td>13</td><td>27</td><td>1</td><td>1</td><td>56</td><td>4</td><td>0</td><td>0</td><td>5.95</td><td>6.41</td><td>6.27</td><td>5.83</td><td>5.45</td><td>1.67</td><td style="background-color:#F3F3F3; font-weight:bold;">1.05</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11169">이상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.94</td><td>37</td><td>0</td><td>37</td><td>6</td><td>0</td><td>0</td><td>2</td><td>1</td><td>1</td><td>8</td><td>30.0</td><td>13</td><td>13</td><td>11.60</td><td>121</td><td>31</td><td>5</td><td>0</td><td>2</td><td>6</td><td>4</td><td>0</td><td>12</td><td>0</td><td>0</td><td>2</td><td>3.90</td><td>3.90</td><td>3.48</td><td>3.52</td><td>5.03</td><td>1.23</td><td style="background-color:#F3F3F3; font-weight:bold;">0.94</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10137">송은범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.38</td><td>9</td><td>0</td><td>9</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>8.1</td><td>1</td><td>1</td><td>1.50</td><td>32</td><td>8</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1.08</td><td>1.08</td><td>1.62</td><td>1.51</td><td>3.97</td><td>1.08</td><td style="background-color:#F3F3F3; font-weight:bold;">0.38</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13152">최하늘</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.32</td><td>27</td><td>0</td><td>27</td><td>4</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td><td>32.0</td><td>19</td><td>20</td><td>20.85</td><td>139</td><td>26</td><td>4</td><td>0</td><td>2</td><td>16</td><td>4</td><td>0</td><td>18</td><td>3</td><td>0</td><td>2</td><td>5.34</td><td>5.63</td><td>5.86</td><td>5.72</td><td>5.47</td><td>1.31</td><td style="background-color:#F3F3F3; font-weight:bold;">0.32</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10685">김대우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.31</td><td>32</td><td>1</td><td>31</td><td>13</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>34.1</td><td>21</td><td>24</td><td>23.20</td><td>157</td><td>42</td><td>9</td><td>0</td><td>4</td><td>9</td><td>3</td><td>2</td><td>23</td><td>3</td><td>0</td><td>1</td><td>5.50</td><td>6.29</td><td>6.08</td><td>5.90</td><td>4.81</td><td>1.49</td><td style="background-color:#F3F3F3; font-weight:bold;">0.31</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15864">육선엽</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.14</td><td>11</td><td>1</td><td>10</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>17.0</td><td>10</td><td>11</td><td>12.55</td><td>87</td><td>19</td><td>2</td><td>0</td><td>3</td><td>17</td><td>2</td><td>0</td><td>11</td><td>1</td><td>0</td><td>1</td><td>5.29</td><td>5.82</td><td>6.64</td><td>6.46</td><td>8.15</td><td>2.12</td><td style="background-color:#F3F3F3; font-weight:bold;">0.14</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10367">오승환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.09</td><td>58</td><td>0</td><td>58</td><td>42</td><td>0</td><td>0</td><td>3</td><td>9</td><td>27</td><td>2</td><td>55.0</td><td>30</td><td>36</td><td>40.35</td><td>262</td><td>75</td><td>17</td><td>2</td><td>9</td><td>18</td><td>3</td><td>3</td><td>42</td><td>3</td><td>0</td><td>5</td><td>4.91</td><td>5.89</td><td>6.60</td><td>6.17</td><td>5.31</td><td>1.69</td><td style="background-color:#F3F3F3; font-weight:bold;">0.09</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14614">홍원표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.08</td><td>4</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6.1</td><td>3</td><td>3</td><td>4.20</td><td>28</td><td>4</td><td>1</td><td>0</td><td>1</td><td>6</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td>4.26</td><td>4.26</td><td>5.97</td><td>5.43</td><td>7.04</td><td>1.58</td><td style="background-color:#F3F3F3; font-weight:bold;">0.08</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10851">최성훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.08</td><td>28</td><td>0</td><td>28</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>3</td><td>13.0</td><td>10</td><td>10</td><td>9.30</td><td>61</td><td>14</td><td>1</td><td>0</td><td>1</td><td>9</td><td>1</td><td>1</td><td>10</td><td>0</td><td>0</td><td>2</td><td>6.92</td><td>6.92</td><td>6.44</td><td>6.07</td><td>5.34</td><td>1.77</td><td style="background-color:#F3F3F3; font-weight:bold;">0.08</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10730">양현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.02</td><td>18</td><td>0</td><td>18</td><td>4</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>2</td><td>13.0</td><td>11</td><td>11</td><td>10.35</td><td>64</td><td>21</td><td>2</td><td>0</td><td>4</td><td>5</td><td>1</td><td>0</td><td>10</td><td>0</td><td>0</td><td>0</td><td>7.62</td><td>7.62</td><td>7.17</td><td>6.71</td><td>7.37</td><td>2.00</td><td style="background-color:#F3F3F3; font-weight:bold;">0.02</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15496">이호성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.04</td><td>16</td><td>12</td><td>4</td><td>0</td><td>0</td><td>0</td><td>2</td><td>4</td><td>0</td><td>0</td><td>45.0</td><td>37</td><td>39</td><td>39.20</td><td>224</td><td>66</td><td>13</td><td>1</td><td>9</td><td>26</td><td>2</td><td>0</td><td>28</td><td>0</td><td>0</td><td>3</td><td>7.40</td><td>7.80</td><td>7.84</td><td>7.39</td><td>6.95</td><td>2.04</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.04</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13156">최채흥</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.04</td><td>14</td><td>1</td><td>13</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>20.0</td><td>14</td><td>15</td><td>16.55</td><td>96</td><td>24</td><td>5</td><td>1</td><td>4</td><td>12</td><td>0</td><td>0</td><td>14</td><td>2</td><td>0</td><td>1</td><td>6.30</td><td>6.75</td><td>7.45</td><td>7.37</td><td>6.69</td><td>1.80</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.04</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11404">장필준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.16</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.1</td><td>5</td><td>5</td><td>3.95</td><td>6</td><td>5</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>99.99</td><td>99.99</td><td>106.65</td><td>102.27</td><td>4.20</td><td>15.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.16</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15882">김대호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.17</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>4.0</td><td>5</td><td>6</td><td>6.00</td><td>22</td><td>7</td><td>2</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>11.25</td><td>13.50</td><td>13.50</td><td>13.55</td><td>8.10</td><td>2.25</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.17</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13242">홍정우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.18</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.0</td><td>5</td><td>5</td><td>5.00</td><td>9</td><td>5</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>45.00</td><td>45.00</td><td>45.00</td><td>40.80</td><td>16.70</td><td>6.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.18</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13162">김윤수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.24</td><td>4</td><td>0</td><td>4</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5.1</td><td>6</td><td>6</td><td>6.70</td><td>26</td><td>6</td><td>0</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td>10.13</td><td>10.13</td><td>11.31</td><td>10.93</td><td>7.33</td><td>2.44</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.24</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14616">이승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.33</td><td>25</td><td>8</td><td>17</td><td>6</td><td>0</td><td>0</td><td>1</td><td>4</td><td>0</td><td>0</td><td>47.1</td><td>45</td><td>48</td><td>45.25</td><td>237</td><td>71</td><td>8</td><td>1</td><td>14</td><td>26</td><td>3</td><td>0</td><td>23</td><td>5</td><td>0</td><td>1</td><td>8.56</td><td>9.13</td><td>8.60</td><td>8.27</td><td>8.40</td><td>2.05</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.33</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13244">이재익</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">24</span> <span><img src="/data/team/ci/2024/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.76</td><td>9</td><td>0</td><td>9</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>9.2</td><td>19</td><td>19</td><td>17.75</td><td>58</td><td>29</td><td>3</td><td>0</td><td>2</td><td>4</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>0</td><td>17.69</td><td>17.69</td><td>16.53</td><td>17.15</td><td>6.39</td><td>3.41</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.76</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15644">엘리아스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.09</td><td>22</td><td>21</td><td>1</td><td>0</td><td>0</td><td>0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>123.2</td><td>56</td><td>59</td><td>55.90</td><td>525</td><td>126</td><td>14</td><td>0</td><td>13</td><td>30</td><td>6</td><td>0</td><td>104</td><td>10</td><td>0</td><td>3</td><td>4.08</td><td>4.29</td><td>4.07</td><td>3.92</td><td>4.25</td><td>1.26</td><td style="background-color:#F3F3F3; font-weight:bold;">4.09</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16146">앤더슨</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.86</td><td>24</td><td>23</td><td>1</td><td>0</td><td>0</td><td>0</td><td>11</td><td>3</td><td>0</td><td>0</td><td>115.2</td><td>50</td><td>55</td><td>53.80</td><td>496</td><td>98</td><td>13</td><td>1</td><td>11</td><td>53</td><td>8</td><td>0</td><td>158</td><td>4</td><td>1</td><td>5</td><td>3.89</td><td>4.28</td><td>4.19</td><td>3.93</td><td>3.55</td><td>1.31</td><td style="background-color:#F3F3F3; font-weight:bold;">3.86</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10126">김광현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.42</td><td>31</td><td>31</td><td>0</td><td>0</td><td>0</td><td>0</td><td>12</td><td>10</td><td>0</td><td>0</td><td>162.1</td><td>89</td><td>95</td><td>94.65</td><td>709</td><td>162</td><td>29</td><td>0</td><td>24</td><td>73</td><td>6</td><td>1</td><td>154</td><td>6</td><td>0</td><td>8</td><td>4.93</td><td>5.27</td><td>5.25</td><td>5.08</td><td>5.10</td><td>1.45</td><td style="background-color:#F3F3F3; font-weight:bold;">3.42</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10203">노경은</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.95</td><td>77</td><td>0</td><td>77</td><td>7</td><td>0</td><td>0</td><td>8</td><td>5</td><td>0</td><td>38</td><td>83.2</td><td>27</td><td>30</td><td>36.00</td><td>350</td><td>71</td><td>10</td><td>1</td><td>10</td><td>32</td><td>4</td><td>4</td><td>71</td><td>2</td><td>0</td><td>3</td><td>2.90</td><td>3.23</td><td>3.87</td><td>3.75</td><td>4.69</td><td>1.23</td><td style="background-color:#F3F3F3; font-weight:bold;">2.95</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14581">오원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.67</td><td>29</td><td>25</td><td>4</td><td>1</td><td>0</td><td>0</td><td>6</td><td>9</td><td>0</td><td>1</td><td>121.2</td><td>68</td><td>72</td><td>68.70</td><td>550</td><td>122</td><td>14</td><td>1</td><td>17</td><td>65</td><td>13</td><td>1</td><td>112</td><td>6</td><td>0</td><td>3</td><td>5.03</td><td>5.33</td><td>5.08</td><td>4.96</td><td>5.52</td><td>1.54</td><td style="background-color:#F3F3F3; font-weight:bold;">2.67</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14805">조병현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.37</td><td>76</td><td>0</td><td>76</td><td>27</td><td>0</td><td>0</td><td>4</td><td>6</td><td>12</td><td>12</td><td>73.0</td><td>29</td><td>34</td><td>32.65</td><td>302</td><td>52</td><td>10</td><td>0</td><td>8</td><td>31</td><td>2</td><td>3</td><td>96</td><td>5</td><td>0</td><td>5</td><td>3.58</td><td>4.19</td><td>4.03</td><td>3.80</td><td>3.53</td><td>1.14</td><td style="background-color:#F3F3F3; font-weight:bold;">2.37</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10783">문승원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.06</td><td>62</td><td>0</td><td>62</td><td>37</td><td>0</td><td>0</td><td>6</td><td>1</td><td>20</td><td>6</td><td>60.0</td><td>30</td><td>33</td><td>35.75</td><td>265</td><td>67</td><td>7</td><td>0</td><td>10</td><td>24</td><td>1</td><td>3</td><td>53</td><td>3</td><td>0</td><td>2</td><td>4.50</td><td>4.95</td><td>5.36</td><td>5.05</td><td>5.16</td><td>1.52</td><td style="background-color:#F3F3F3; font-weight:bold;">1.06</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15462">송영진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.04</td><td>26</td><td>20</td><td>6</td><td>2</td><td>0</td><td>0</td><td>5</td><td>10</td><td>0</td><td>0</td><td>99.1</td><td>64</td><td>74</td><td>68.15</td><td>456</td><td>112</td><td>19</td><td>2</td><td>10</td><td>51</td><td>1</td><td>0</td><td>67</td><td>7</td><td>2</td><td>8</td><td>5.80</td><td>6.70</td><td>6.17</td><td>6.06</td><td>5.33</td><td>1.64</td><td style="background-color:#F3F3F3; font-weight:bold;">1.04</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13228">한두솔</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.86</td><td>69</td><td>0</td><td>69</td><td>8</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>3</td><td>59.1</td><td>33</td><td>40</td><td>35.90</td><td>273</td><td>62</td><td>10</td><td>2</td><td>3</td><td>31</td><td>3</td><td>2</td><td>68</td><td>5</td><td>0</td><td>1</td><td>5.01</td><td>6.07</td><td>5.45</td><td>5.24</td><td>3.61</td><td>1.57</td><td style="background-color:#F3F3F3; font-weight:bold;">0.86</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15028">이기순</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.47</td><td>10</td><td>2</td><td>8</td><td>2</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>19.2</td><td>8</td><td>10</td><td>9.15</td><td>94</td><td>12</td><td>1</td><td>0</td><td>2</td><td>23</td><td>1</td><td>0</td><td>24</td><td>0</td><td>0</td><td>1</td><td>3.66</td><td>4.58</td><td>4.19</td><td>4.12</td><td>6.14</td><td>1.78</td><td style="background-color:#F3F3F3; font-weight:bold;">0.47</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16148">시라카와</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.47</td><td>5</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>23.0</td><td>13</td><td>16</td><td>14.30</td><td>106</td><td>29</td><td>4</td><td>0</td><td>3</td><td>9</td><td>1</td><td>0</td><td>27</td><td>1</td><td>0</td><td>0</td><td>5.09</td><td>6.26</td><td>5.60</td><td>5.15</td><td>4.16</td><td>1.65</td><td style="background-color:#F3F3F3; font-weight:bold;">0.47</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15461">이로운</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.30</td><td>62</td><td>0</td><td>62</td><td>14</td><td>0</td><td>0</td><td>1</td><td>3</td><td>1</td><td>9</td><td>56.0</td><td>37</td><td>43</td><td>40.10</td><td>277</td><td>67</td><td>9</td><td>2</td><td>4</td><td>43</td><td>3</td><td>4</td><td>41</td><td>3</td><td>0</td><td>3</td><td>5.95</td><td>6.91</td><td>6.44</td><td>6.22</td><td>5.65</td><td>1.96</td><td style="background-color:#F3F3F3; font-weight:bold;">0.30</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10131">박종훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.20</td><td>10</td><td>9</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td><td>4</td><td>0</td><td>0</td><td>35.0</td><td>27</td><td>28</td><td>26.10</td><td>164</td><td>37</td><td>7</td><td>0</td><td>7</td><td>21</td><td>8</td><td>0</td><td>34</td><td>0</td><td>0</td><td>3</td><td>6.94</td><td>7.20</td><td>6.71</td><td>6.68</td><td>6.72</td><td>1.66</td><td style="background-color:#F3F3F3; font-weight:bold;">0.20</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11236">박민호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.15</td><td>19</td><td>0</td><td>19</td><td>8</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>22.2</td><td>12</td><td>14</td><td>17.10</td><td>98</td><td>25</td><td>3</td><td>0</td><td>4</td><td>7</td><td>2</td><td>1</td><td>10</td><td>1</td><td>0</td><td>0</td><td>4.76</td><td>5.56</td><td>6.79</td><td>6.27</td><td>6.29</td><td>1.41</td><td style="background-color:#F3F3F3; font-weight:bold;">0.15</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14687">박시후</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.12</td><td>11</td><td>0</td><td>11</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>14.2</td><td>11</td><td>11</td><td>10.65</td><td>70</td><td>18</td><td>1</td><td>0</td><td>1</td><td>7</td><td>2</td><td>0</td><td>11</td><td>1</td><td>0</td><td>0</td><td>6.75</td><td>6.75</td><td>6.54</td><td>6.34</td><td>5.04</td><td>1.70</td><td style="background-color:#F3F3F3; font-weight:bold;">0.12</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16044">박성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.10</td><td>3</td><td>0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.1</td><td>0</td><td>0</td><td>0.00</td><td>9</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>3.38</td><td>0.43</td><td style="background-color:#F3F3F3; font-weight:bold;">0.10</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12571">정동윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.06</td><td>3</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.2</td><td>0</td><td>0</td><td>0.35</td><td>7</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0.00</td><td>1.89</td><td>1.76</td><td>3.06</td><td>1.20</td><td style="background-color:#F3F3F3; font-weight:bold;">0.06</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11373">김택형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.05</td><td>6</td><td>0</td><td>6</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>7.0</td><td>7</td><td>7</td><td>6.15</td><td>37</td><td>10</td><td>1</td><td>0</td><td>1</td><td>6</td><td>1</td><td>1</td><td>1</td><td>0</td><td>1</td><td>1</td><td>9.00</td><td>9.00</td><td>7.91</td><td>7.90</td><td>8.64</td><td>2.29</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.05</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14804">장지훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.09</td><td>18</td><td>0</td><td>18</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>21.1</td><td>16</td><td>16</td><td>18.40</td><td>101</td><td>29</td><td>6</td><td>0</td><td>3</td><td>10</td><td>1</td><td>0</td><td>10</td><td>1</td><td>0</td><td>0</td><td>6.75</td><td>6.75</td><td>7.76</td><td>7.62</td><td>6.30</td><td>1.83</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.09</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14145">백승건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.12</td><td>10</td><td>0</td><td>10</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9.1</td><td>8</td><td>9</td><td>11.05</td><td>51</td><td>13</td><td>2</td><td>0</td><td>2</td><td>9</td><td>0</td><td>0</td><td>5</td><td>2</td><td>0</td><td>1</td><td>7.71</td><td>8.68</td><td>10.66</td><td>10.05</td><td>8.40</td><td>2.36</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.12</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16041">최현석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.16</td><td>2</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.2</td><td>4</td><td>4</td><td>4.00</td><td>10</td><td>5</td><td>0</td><td>0</td><td>1</td><td>3</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>54.00</td><td>54.00</td><td>54.00</td><td>53.38</td><td>32.25</td><td>12.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.16</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10124">고효준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.16</td><td>26</td><td>0</td><td>26</td><td>2</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>5</td><td>22.0</td><td>20</td><td>21</td><td>19.25</td><td>109</td><td>23</td><td>4</td><td>0</td><td>4</td><td>20</td><td>1</td><td>1</td><td>27</td><td>1</td><td>0</td><td>2</td><td>8.18</td><td>8.59</td><td>7.88</td><td>7.36</td><td>6.25</td><td>1.95</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.16</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15024">신헌민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.21</td><td>3</td><td>0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.0</td><td>6</td><td>7</td><td>7.00</td><td>18</td><td>7</td><td>2</td><td>0</td><td>2</td><td>3</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>18.00</td><td>21.00</td><td>21.00</td><td>20.88</td><td>16.27</td><td>3.33</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.21</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13057">김주온</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.26</td><td>2</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4.2</td><td>8</td><td>8</td><td>9.55</td><td>25</td><td>8</td><td>1</td><td>0</td><td>2</td><td>3</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>15.43</td><td>15.43</td><td>18.42</td><td>18.21</td><td>9.15</td><td>2.36</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.26</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10784">서진용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.35</td><td>51</td><td>0</td><td>51</td><td>3</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>6</td><td>47.0</td><td>29</td><td>34</td><td>40.85</td><td>211</td><td>52</td><td>11</td><td>1</td><td>5</td><td>26</td><td>0</td><td>2</td><td>38</td><td>3</td><td>0</td><td>4</td><td>5.55</td><td>6.51</td><td>7.82</td><td>7.52</td><td>5.09</td><td>1.66</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.35</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11242">이건욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.58</td><td>10</td><td>2</td><td>8</td><td>1</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>19.0</td><td>24</td><td>25</td><td>24.30</td><td>106</td><td>34</td><td>4</td><td>0</td><td>5</td><td>15</td><td>2</td><td>0</td><td>17</td><td>2</td><td>0</td><td>3</td><td>11.37</td><td>11.84</td><td>11.51</td><td>11.46</td><td>7.87</td><td>2.58</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.58</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13126">최민준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.67</td><td>32</td><td>0</td><td>32</td><td>3</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>39.1</td><td>34</td><td>36</td><td>41.20</td><td>202</td><td>61</td><td>9</td><td>1</td><td>9</td><td>24</td><td>3</td><td>1</td><td>40</td><td>2</td><td>0</td><td>1</td><td>7.78</td><td>8.24</td><td>9.43</td><td>9.17</td><td>6.43</td><td>2.16</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.67</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16141">더거</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">24</span> <span><img src="/data/team/ci/2024/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.84</td><td>6</td><td>6</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>22.2</td><td>32</td><td>33</td><td>33.00</td><td>116</td><td>37</td><td>7</td><td>3</td><td>2</td><td>10</td><td>3</td><td>0</td><td>18</td><td>1</td><td>0</td><td>0</td><td>12.71</td><td>13.10</td><td>13.10</td><td>12.80</td><td>5.04</td><td>2.07</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.84</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16065">하트</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">6.93</td><td>26</td><td>26</td><td>0</td><td>0</td><td>0</td><td>0</td><td>13</td><td>3</td><td>0</td><td>0</td><td>157.0</td><td>47</td><td>51</td><td>51.00</td><td>631</td><td>124</td><td>16</td><td>1</td><td>11</td><td>38</td><td>11</td><td>0</td><td>182</td><td>7</td><td>0</td><td>2</td><td>2.69</td><td>2.92</td><td>2.92</td><td>3.00</td><td>3.10</td><td>1.03</td><td style="background-color:#F3F3F3; font-weight:bold;">6.93</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13085">신민혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.14</td><td>25</td><td>24</td><td>1</td><td>1</td><td>0</td><td>0</td><td>8</td><td>9</td><td>0</td><td>0</td><td>121.0</td><td>58</td><td>67</td><td>61.30</td><td>524</td><td>140</td><td>24</td><td>3</td><td>20</td><td>16</td><td>7</td><td>0</td><td>74</td><td>8</td><td>1</td><td>2</td><td>4.31</td><td>4.98</td><td>4.56</td><td>4.67</td><td>5.23</td><td>1.29</td><td style="background-color:#F3F3F3; font-weight:bold;">3.14</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14747">김재열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.42</td><td>69</td><td>0</td><td>69</td><td>16</td><td>0</td><td>0</td><td>1</td><td>5</td><td>2</td><td>12</td><td>68.2</td><td>19</td><td>20</td><td>25.45</td><td>284</td><td>58</td><td>15</td><td>1</td><td>4</td><td>29</td><td>0</td><td>3</td><td>67</td><td>2</td><td>1</td><td>1</td><td>2.49</td><td>2.62</td><td>3.34</td><td>3.46</td><td>3.72</td><td>1.27</td><td style="background-color:#F3F3F3; font-weight:bold;">2.42</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13080">김시훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.31</td><td>39</td><td>18</td><td>21</td><td>0</td><td>0</td><td>0</td><td>3</td><td>4</td><td>0</td><td>5</td><td>107.1</td><td>54</td><td>60</td><td>57.45</td><td>477</td><td>110</td><td>25</td><td>1</td><td>7</td><td>59</td><td>3</td><td>0</td><td>74</td><td>7</td><td>1</td><td>1</td><td>4.53</td><td>5.03</td><td>4.82</td><td>4.98</td><td>5.04</td><td>1.57</td><td style="background-color:#F3F3F3; font-weight:bold;">2.31</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16064">카스타노</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.26</td><td>19</td><td>19</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8</td><td>6</td><td>0</td><td>0</td><td>111.2</td><td>54</td><td>65</td><td>63.45</td><td>476</td><td>117</td><td>23</td><td>4</td><td>11</td><td>25</td><td>7</td><td>0</td><td>89</td><td>7</td><td>1</td><td>0</td><td>4.35</td><td>5.24</td><td>5.11</td><td>5.20</td><td>4.27</td><td>1.27</td><td style="background-color:#F3F3F3; font-weight:bold;">2.26</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13088">김영규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.74</td><td>42</td><td>0</td><td>42</td><td>4</td><td>0</td><td>0</td><td>4</td><td>2</td><td>1</td><td>14</td><td>45.2</td><td>16</td><td>19</td><td>17.20</td><td>183</td><td>40</td><td>4</td><td>0</td><td>3</td><td>14</td><td>1</td><td>0</td><td>48</td><td>2</td><td>0</td><td>1</td><td>3.15</td><td>3.74</td><td>3.39</td><td>3.53</td><td>3.37</td><td>1.18</td><td style="background-color:#F3F3F3; font-weight:bold;">1.74</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10220">이재학</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.45</td><td>21</td><td>21</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>12</td><td>0</td><td>0</td><td>104.1</td><td>64</td><td>68</td><td>66.25</td><td>462</td><td>108</td><td>27</td><td>3</td><td>17</td><td>42</td><td>4</td><td>0</td><td>97</td><td>3</td><td>0</td><td>2</td><td>5.52</td><td>5.87</td><td>5.71</td><td>5.86</td><td>5.18</td><td>1.44</td><td style="background-color:#F3F3F3; font-weight:bold;">1.45</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14764">한재승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.88</td><td>51</td><td>0</td><td>51</td><td>12</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>6</td><td>45.1</td><td>20</td><td>21</td><td>24.20</td><td>201</td><td>37</td><td>7</td><td>1</td><td>2</td><td>27</td><td>3</td><td>0</td><td>44</td><td>2</td><td>0</td><td>6</td><td>3.97</td><td>4.17</td><td>4.80</td><td>4.84</td><td>4.35</td><td>1.41</td><td style="background-color:#F3F3F3; font-weight:bold;">0.88</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11168">임정호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.85</td><td>65</td><td>0</td><td>65</td><td>10</td><td>0</td><td>0</td><td>1</td><td>6</td><td>2</td><td>9</td><td>55.0</td><td>27</td><td>32</td><td>31.65</td><td>243</td><td>54</td><td>8</td><td>1</td><td>3</td><td>25</td><td>3</td><td>3</td><td>46</td><td>3</td><td>0</td><td>0</td><td>4.42</td><td>5.24</td><td>5.18</td><td>5.28</td><td>4.22</td><td>1.44</td><td style="background-color:#F3F3F3; font-weight:bold;">0.85</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13940">요키시</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.22</td><td>8</td><td>8</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>4</td><td>0</td><td>0</td><td>39.1</td><td>25</td><td>29</td><td>28.65</td><td>189</td><td>51</td><td>11</td><td>2</td><td>5</td><td>20</td><td>2</td><td>0</td><td>32</td><td>3</td><td>0</td><td>2</td><td>5.72</td><td>6.64</td><td>6.56</td><td>6.86</td><td>5.41</td><td>1.81</td><td style="background-color:#F3F3F3; font-weight:bold;">0.22</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16056">최우석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.16</td><td>9</td><td>0</td><td>9</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8.2</td><td>3</td><td>3</td><td>4.20</td><td>37</td><td>7</td><td>2</td><td>0</td><td>2</td><td>6</td><td>0</td><td>0</td><td>8</td><td>0</td><td>0</td><td>1</td><td>3.12</td><td>3.12</td><td>4.36</td><td>4.59</td><td>6.78</td><td>1.50</td><td style="background-color:#F3F3F3; font-weight:bold;">0.16</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14763">이용준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.12</td><td>9</td><td>9</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>3</td><td>0</td><td>0</td><td>33.2</td><td>25</td><td>28</td><td>25.40</td><td>157</td><td>42</td><td>6</td><td>2</td><td>5</td><td>14</td><td>1</td><td>0</td><td>26</td><td>3</td><td>0</td><td>1</td><td>6.68</td><td>7.49</td><td>6.79</td><td>7.10</td><td>5.42</td><td>1.66</td><td style="background-color:#F3F3F3; font-weight:bold;">0.12</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14155">송명기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.04</td><td>33</td><td>0</td><td>33</td><td>5</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>4</td><td>38.1</td><td>25</td><td>27</td><td>28.70</td><td>173</td><td>40</td><td>7</td><td>1</td><td>4</td><td>17</td><td>3</td><td>1</td><td>31</td><td>2</td><td>0</td><td>7</td><td>5.87</td><td>6.34</td><td>6.74</td><td>6.82</td><td>4.96</td><td>1.49</td><td style="background-color:#F3F3F3; font-weight:bold;">0.04</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13175">박주현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.04</td><td>3</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.0</td><td>2</td><td>2</td><td>2.00</td><td>13</td><td>3</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>6.00</td><td>6.00</td><td>6.00</td><td>5.44</td><td>5.87</td><td>1.33</td><td style="background-color:#F3F3F3; font-weight:bold;">0.04</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12897">김진호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.1</td><td>2</td><td>2</td><td>2.00</td><td>12</td><td>3</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>7.71</td><td>7.71</td><td>7.71</td><td>8.07</td><td>3.64</td><td>2.14</td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11355">류진욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>50</td><td>0</td><td>50</td><td>5</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>10</td><td>42.1</td><td>27</td><td>30</td><td>31.90</td><td>194</td><td>52</td><td>8</td><td>0</td><td>4</td><td>19</td><td>2</td><td>0</td><td>37</td><td>1</td><td>0</td><td>3</td><td>5.74</td><td>6.38</td><td>6.78</td><td>6.70</td><td>4.68</td><td>1.68</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16057">손주환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>4</td><td>1</td><td>3</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>3.2</td><td>4</td><td>4</td><td>2.80</td><td>16</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>9.82</td><td>9.82</td><td>6.87</td><td>6.90</td><td>4.01</td><td>1.09</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16053">임상현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>12</td><td>7</td><td>5</td><td>1</td><td>0</td><td>0</td><td>1</td><td>5</td><td>0</td><td>0</td><td>40.1</td><td>29</td><td>35</td><td>34.50</td><td>181</td><td>46</td><td>13</td><td>0</td><td>5</td><td>23</td><td>2</td><td>0</td><td>21</td><td>1</td><td>0</td><td>1</td><td>6.47</td><td>7.81</td><td>7.70</td><td>7.64</td><td>6.29</td><td>1.71</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12565">최성영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.05</td><td>24</td><td>4</td><td>20</td><td>7</td><td>0</td><td>0</td><td>2</td><td>0</td><td>1</td><td>1</td><td>46.2</td><td>30</td><td>37</td><td>37.50</td><td>218</td><td>65</td><td>10</td><td>0</td><td>7</td><td>17</td><td>0</td><td>0</td><td>29</td><td>3</td><td>0</td><td>0</td><td>5.79</td><td>7.14</td><td>7.23</td><td>7.25</td><td>5.30</td><td>1.76</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.05</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11387">채원후</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.06</td><td>3</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.0</td><td>4</td><td>4</td><td>4.00</td><td>18</td><td>6</td><td>2</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>2</td><td>12.00</td><td>12.00</td><td>12.00</td><td>11.86</td><td>5.63</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.06</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11248">배재환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>20</td><td>0</td><td>20</td><td>5</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>19.2</td><td>16</td><td>17</td><td>16.50</td><td>91</td><td>20</td><td>2</td><td>0</td><td>5</td><td>15</td><td>0</td><td>1</td><td>13</td><td>0</td><td>0</td><td>0</td><td>7.32</td><td>7.78</td><td>7.55</td><td>7.56</td><td>7.94</td><td>1.78</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16049">김민규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>7</td><td>0</td><td>7</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6.1</td><td>4</td><td>4</td><td>6.05</td><td>30</td><td>8</td><td>1</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td>5.68</td><td>5.68</td><td>8.60</td><td>8.90</td><td>4.88</td><td>1.74</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12574">서의태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.08</td><td>11</td><td>0</td><td>11</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>7.2</td><td>8</td><td>8</td><td>7.30</td><td>34</td><td>5</td><td>1</td><td>0</td><td>1</td><td>8</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>1</td><td>9.39</td><td>9.39</td><td>8.57</td><td>8.78</td><td>6.70</td><td>1.70</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.08</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15450">신영우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.13</td><td>4</td><td>2</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>9.1</td><td>11</td><td>11</td><td>10.15</td><td>52</td><td>9</td><td>3</td><td>0</td><td>0</td><td>15</td><td>2</td><td>0</td><td>6</td><td>0</td><td>0</td><td>1</td><td>10.61</td><td>10.61</td><td>9.79</td><td>9.54</td><td>8.24</td><td>2.57</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.13</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12900">소이현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.15</td><td>4</td><td>0</td><td>4</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.1</td><td>5</td><td>7</td><td>5.95</td><td>19</td><td>6</td><td>3</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>13.50</td><td>18.90</td><td>16.07</td><td>16.65</td><td>5.31</td><td>2.10</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.15</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12898">김태현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.20</td><td>11</td><td>0</td><td>11</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10.0</td><td>8</td><td>10</td><td>11.20</td><td>50</td><td>14</td><td>4</td><td>0</td><td>3</td><td>7</td><td>0</td><td>0</td><td>3</td><td>2</td><td>0</td><td>1</td><td>7.20</td><td>9.00</td><td>10.08</td><td>10.43</td><td>9.19</td><td>2.10</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.20</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15453">목지훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.26</td><td>3</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>9.0</td><td>12</td><td>12</td><td>11.15</td><td>52</td><td>15</td><td>6</td><td>0</td><td>1</td><td>10</td><td>2</td><td>0</td><td>3</td><td>1</td><td>0</td><td>1</td><td>12.00</td><td>12.00</td><td>11.15</td><td>11.79</td><td>8.82</td><td>2.78</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.26</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14156">전사민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.45</td><td>17</td><td>0</td><td>17</td><td>9</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>23.2</td><td>25</td><td>25</td><td>26.05</td><td>128</td><td>39</td><td>6</td><td>1</td><td>3</td><td>17</td><td>3</td><td>0</td><td>17</td><td>0</td><td>2</td><td>4</td><td>9.51</td><td>9.51</td><td>9.91</td><td>10.02</td><td>6.53</td><td>2.37</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.45</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14171">전루건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.45</td><td>6</td><td>0</td><td>6</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5.2</td><td>14</td><td>14</td><td>14.15</td><td>44</td><td>15</td><td>3</td><td>0</td><td>0</td><td>9</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>22.24</td><td>22.24</td><td>22.47</td><td>21.89</td><td>11.31</td><td>4.24</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.45</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15455">이준호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.62</td><td>38</td><td>2</td><td>36</td><td>12</td><td>0</td><td>0</td><td>3</td><td>5</td><td>0</td><td>2</td><td>49.1</td><td>41</td><td>41</td><td>46.40</td><td>243</td><td>71</td><td>11</td><td>0</td><td>7</td><td>26</td><td>3</td><td>0</td><td>42</td><td>1</td><td>0</td><td>0</td><td>7.48</td><td>7.48</td><td>8.46</td><td>8.64</td><td>5.58</td><td>1.97</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.62</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10217">이용찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">24</span> <span><img src="/data/team/ci/2024/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-1.14</td><td>57</td><td>0</td><td>57</td><td>36</td><td>0</td><td>0</td><td>3</td><td>9</td><td>16</td><td>2</td><td>54.1</td><td>37</td><td>48</td><td>46.50</td><td>262</td><td>82</td><td>20</td><td>3</td><td>6</td><td>21</td><td>2</td><td>1</td><td>49</td><td>5</td><td>0</td><td>6</td><td>6.13</td><td>7.95</td><td>7.70</td><td>8.00</td><td>4.57</td><td>1.90</td><td style="background-color:#F3F3F3; font-weight:bold;">-1.14</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13061">곽빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.00</td><td>30</td><td>30</td><td>0</td><td>0</td><td>0</td><td>0</td><td>15</td><td>9</td><td>0</td><td>0</td><td>167.2</td><td>79</td><td>83</td><td>76.70</td><td>716</td><td>142</td><td>29</td><td>1</td><td>11</td><td>76</td><td>6</td><td>0</td><td>154</td><td>5</td><td>1</td><td>11</td><td>4.24</td><td>4.46</td><td>4.12</td><td>4.25</td><td>4.13</td><td>1.30</td><td style="background-color:#F3F3F3; font-weight:bold;">5.00</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16067">김택연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.23</td><td>60</td><td>0</td><td>60</td><td>32</td><td>0</td><td>0</td><td>3</td><td>2</td><td>19</td><td>4</td><td>65.0</td><td>15</td><td>17</td><td>18.90</td><td>277</td><td>51</td><td>11</td><td>0</td><td>2</td><td>31</td><td>4</td><td>1</td><td>78</td><td>1</td><td>0</td><td>3</td><td>2.08</td><td>2.35</td><td>2.62</td><td>2.67</td><td>3.19</td><td>1.26</td><td style="background-color:#F3F3F3; font-weight:bold;">3.23</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15153">브랜든</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.47</td><td>14</td><td>14</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>4</td><td>0</td><td>0</td><td>75.0</td><td>26</td><td>34</td><td>31.75</td><td>315</td><td>75</td><td>11</td><td>2</td><td>3</td><td>11</td><td>4</td><td>0</td><td>75</td><td>9</td><td>0</td><td>2</td><td>3.12</td><td>4.08</td><td>3.81</td><td>3.96</td><td>2.80</td><td>1.15</td><td style="background-color:#F3F3F3; font-weight:bold;">2.47</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15099">이병헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.91</td><td>77</td><td>0</td><td>77</td><td>6</td><td>0</td><td>0</td><td>6</td><td>1</td><td>1</td><td>22</td><td>65.1</td><td>21</td><td>25</td><td>29.90</td><td>285</td><td>61</td><td>7</td><td>1</td><td>3</td><td>34</td><td>3</td><td>1</td><td>57</td><td>1</td><td>1</td><td>2</td><td>2.89</td><td>3.44</td><td>4.12</td><td>4.21</td><td>4.27</td><td>1.45</td><td style="background-color:#F3F3F3; font-weight:bold;">1.91</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10690">김강률</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.78</td><td>53</td><td>0</td><td>53</td><td>3</td><td>0</td><td>0</td><td>2</td><td>2</td><td>1</td><td>12</td><td>42.0</td><td>14</td><td>16</td><td>11.15</td><td>187</td><td>41</td><td>7</td><td>0</td><td>1</td><td>21</td><td>2</td><td>0</td><td>33</td><td>1</td><td>0</td><td>1</td><td>3.00</td><td>3.43</td><td>2.39</td><td>2.48</td><td>4.22</td><td>1.48</td><td style="background-color:#F3F3F3; font-weight:bold;">1.78</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10696">홍건희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.59</td><td>65</td><td>0</td><td>65</td><td>18</td><td>0</td><td>0</td><td>4</td><td>3</td><td>9</td><td>11</td><td>59.1</td><td>18</td><td>22</td><td>27.65</td><td>264</td><td>55</td><td>6</td><td>1</td><td>5</td><td>33</td><td>5</td><td>4</td><td>45</td><td>2</td><td>0</td><td>5</td><td>2.73</td><td>3.34</td><td>4.19</td><td>4.36</td><td>5.19</td><td>1.48</td><td style="background-color:#F3F3F3; font-weight:bold;">1.59</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16155">발라조빅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.44</td><td>12</td><td>11</td><td>1</td><td>0</td><td>0</td><td>0</td><td>2</td><td>6</td><td>0</td><td>1</td><td>57.0</td><td>27</td><td>29</td><td>28.00</td><td>250</td><td>54</td><td>13</td><td>1</td><td>3</td><td>28</td><td>2</td><td>0</td><td>69</td><td>1</td><td>0</td><td>2</td><td>4.26</td><td>4.58</td><td>4.42</td><td>4.67</td><td>3.22</td><td>1.44</td><td style="background-color:#F3F3F3; font-weight:bold;">1.44</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12852">최원준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.42</td><td>24</td><td>24</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td><td>7</td><td>0</td><td>0</td><td>110.0</td><td>79</td><td>79</td><td>70.35</td><td>490</td><td>125</td><td>24</td><td>2</td><td>21</td><td>34</td><td>10</td><td>1</td><td>72</td><td>3</td><td>0</td><td>1</td><td>6.46</td><td>6.46</td><td>5.76</td><td>5.94</td><td>6.07</td><td>1.45</td><td style="background-color:#F3F3F3; font-weight:bold;">1.42</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15508">최준호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.40</td><td>17</td><td>15</td><td>2</td><td>0</td><td>0</td><td>0</td><td>3</td><td>6</td><td>0</td><td>0</td><td>72.1</td><td>41</td><td>44</td><td>41.70</td><td>314</td><td>69</td><td>8</td><td>2</td><td>11</td><td>30</td><td>4</td><td>0</td><td>58</td><td>2</td><td>0</td><td>6</td><td>5.10</td><td>5.47</td><td>5.19</td><td>5.24</td><td>5.46</td><td>1.37</td><td style="background-color:#F3F3F3; font-weight:bold;">1.40</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13941">알칸타라</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.36</td><td>12</td><td>12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>64.1</td><td>34</td><td>35</td><td>34.65</td><td>270</td><td>58</td><td>8</td><td>3</td><td>10</td><td>22</td><td>2</td><td>0</td><td>34</td><td>3</td><td>0</td><td>0</td><td>4.76</td><td>4.90</td><td>4.85</td><td>5.09</td><td>5.88</td><td>1.24</td><td style="background-color:#F3F3F3; font-weight:bold;">1.36</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15127">최지강</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.26</td><td>55</td><td>0</td><td>55</td><td>4</td><td>0</td><td>0</td><td>3</td><td>1</td><td>1</td><td>15</td><td>50.0</td><td>18</td><td>19</td><td>24.55</td><td>222</td><td>48</td><td>7</td><td>2</td><td>6</td><td>24</td><td>6</td><td>2</td><td>45</td><td>2</td><td>0</td><td>3</td><td>3.24</td><td>3.42</td><td>4.42</td><td>4.52</td><td>5.18</td><td>1.44</td><td style="background-color:#F3F3F3; font-weight:bold;">1.26</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13072">김민규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.75</td><td>13</td><td>4</td><td>9</td><td>4</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>25.0</td><td>12</td><td>14</td><td>12.15</td><td>117</td><td>23</td><td>7</td><td>2</td><td>4</td><td>19</td><td>4</td><td>0</td><td>19</td><td>1</td><td>0</td><td>3</td><td>4.32</td><td>5.04</td><td>4.37</td><td>4.30</td><td>7.06</td><td>1.68</td><td style="background-color:#F3F3F3; font-weight:bold;">0.75</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12568">이영하</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.60</td><td>59</td><td>1</td><td>58</td><td>8</td><td>0</td><td>0</td><td>5</td><td>4</td><td>2</td><td>5</td><td>65.1</td><td>29</td><td>34</td><td>41.05</td><td>298</td><td>62</td><td>9</td><td>3</td><td>4</td><td>36</td><td>2</td><td>1</td><td>59</td><td>6</td><td>0</td><td>7</td><td>3.99</td><td>4.68</td><td>5.65</td><td>5.85</td><td>4.47</td><td>1.50</td><td style="background-color:#F3F3F3; font-weight:bold;">0.60</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16148">시라카와</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.26</td><td>7</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>3</td><td>0</td><td>0</td><td>34.1</td><td>23</td><td>25</td><td>23.45</td><td>158</td><td>30</td><td>2</td><td>1</td><td>3</td><td>24</td><td>2</td><td>0</td><td>19</td><td>3</td><td>0</td><td>5</td><td>6.03</td><td>6.55</td><td>6.15</td><td>6.57</td><td>6.20</td><td>1.57</td><td style="background-color:#F3F3F3; font-weight:bold;">0.26</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15509">김유성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.23</td><td>17</td><td>7</td><td>10</td><td>1</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>28.0</td><td>20</td><td>23</td><td>19.20</td><td>139</td><td>28</td><td>10</td><td>0</td><td>1</td><td>24</td><td>4</td><td>0</td><td>29</td><td>1</td><td>0</td><td>2</td><td>6.43</td><td>7.39</td><td>6.17</td><td>6.50</td><td>5.13</td><td>1.86</td><td style="background-color:#F3F3F3; font-weight:bold;">0.23</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13070">박신지</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.22</td><td>6</td><td>1</td><td>5</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>8.2</td><td>2</td><td>3</td><td>4.05</td><td>41</td><td>8</td><td>2</td><td>0</td><td>0</td><td>8</td><td>1</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>2.08</td><td>3.12</td><td>4.21</td><td>4.18</td><td>6.55</td><td>1.85</td><td style="background-color:#F3F3F3; font-weight:bold;">0.22</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11300">박정수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.20</td><td>29</td><td>1</td><td>28</td><td>7</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>4</td><td>29.2</td><td>17</td><td>18</td><td>19.90</td><td>137</td><td>38</td><td>4</td><td>1</td><td>2</td><td>12</td><td>2</td><td>0</td><td>22</td><td>0</td><td>0</td><td>2</td><td>5.16</td><td>5.46</td><td>6.04</td><td>6.18</td><td>4.61</td><td>1.69</td><td style="background-color:#F3F3F3; font-weight:bold;">0.20</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14733">최종인</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.20</td><td>11</td><td>0</td><td>11</td><td>4</td><td>0</td><td>0</td><td>1</td><td>0</td><td>1</td><td>2</td><td>9.2</td><td>4</td><td>4</td><td>5.00</td><td>42</td><td>8</td><td>0</td><td>0</td><td>2</td><td>5</td><td>0</td><td>0</td><td>8</td><td>0</td><td>0</td><td>0</td><td>3.72</td><td>3.72</td><td>4.66</td><td>4.71</td><td>6.20</td><td>1.34</td><td style="background-color:#F3F3F3; font-weight:bold;">0.20</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14770">최승용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.14</td><td>12</td><td>6</td><td>6</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td>27.0</td><td>18</td><td>19</td><td>20.40</td><td>124</td><td>37</td><td>5</td><td>2</td><td>6</td><td>7</td><td>0</td><td>0</td><td>21</td><td>2</td><td>0</td><td>0</td><td>6.00</td><td>6.33</td><td>6.80</td><td>6.85</td><td>5.70</td><td>1.63</td><td style="background-color:#F3F3F3; font-weight:bold;">0.14</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16071">박지호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.10</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0.2</td><td>0</td><td>0</td><td>0.00</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>1.35</td><td>1.50</td><td style="background-color:#F3F3F3; font-weight:bold;">0.10</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12850">박치국</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.03</td><td>52</td><td>0</td><td>52</td><td>15</td><td>0</td><td>0</td><td>2</td><td>3</td><td>1</td><td>3</td><td>48.0</td><td>34</td><td>34</td><td>35.05</td><td>222</td><td>59</td><td>6</td><td>0</td><td>8</td><td>18</td><td>10</td><td>1</td><td>35</td><td>1</td><td>1</td><td>1</td><td>6.38</td><td>6.38</td><td>6.57</td><td>6.70</td><td>6.10</td><td>1.60</td><td style="background-color:#F3F3F3; font-weight:bold;">0.03</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14768">김도윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>2</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.1</td><td>1</td><td>2</td><td>2.00</td><td>12</td><td>2</td><td>1</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>3.86</td><td>7.71</td><td>7.71</td><td>8.32</td><td>7.11</td><td>1.71</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11491">박소준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>4.0</td><td>5</td><td>5</td><td>5.00</td><td>20</td><td>6</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td>11.25</td><td>11.25</td><td>11.25</td><td>10.20</td><td>10.45</td><td>2.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13665">권휘</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.10</td><td>8</td><td>0</td><td>8</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9.0</td><td>11</td><td>11</td><td>8.80</td><td>49</td><td>15</td><td>3</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>11</td><td>0</td><td>0</td><td>1</td><td>11.00</td><td>11.00</td><td>8.80</td><td>9.22</td><td>3.55</td><td>2.44</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.10</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13071">정철원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.11</td><td>36</td><td>0</td><td>36</td><td>14</td><td>0</td><td>0</td><td>2</td><td>1</td><td>6</td><td>1</td><td>32.1</td><td>23</td><td>24</td><td>25.55</td><td>165</td><td>39</td><td>7</td><td>2</td><td>5</td><td>26</td><td>5</td><td>0</td><td>39</td><td>1</td><td>0</td><td>0</td><td>6.40</td><td>6.68</td><td>7.11</td><td>7.01</td><td>6.00</td><td>2.01</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.11</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13124">김정우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.13</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.1</td><td>3</td><td>3</td><td>2.50</td><td>4</td><td>3</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>81.00</td><td>81.00</td><td>67.50</td><td>72.77</td><td>4.20</td><td>9.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.13</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14769">김동주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.25</td><td>14</td><td>9</td><td>5</td><td>3</td><td>1</td><td>0</td><td>1</td><td>3</td><td>0</td><td>0</td><td>50.0</td><td>38</td><td>46</td><td>42.45</td><td>244</td><td>67</td><td>12</td><td>3</td><td>6</td><td>21</td><td>4</td><td>0</td><td>35</td><td>3</td><td>1</td><td>7</td><td>6.84</td><td>8.28</td><td>7.64</td><td>7.90</td><td>5.43</td><td>1.76</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.25</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13268">김호준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.31</td><td>16</td><td>1</td><td>15</td><td>6</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>13.1</td><td>13</td><td>14</td><td>15.00</td><td>68</td><td>22</td><td>6</td><td>1</td><td>1</td><td>4</td><td>5</td><td>0</td><td>6</td><td>0</td><td>0</td><td>0</td><td>8.78</td><td>9.45</td><td>10.13</td><td>9.94</td><td>6.06</td><td>1.95</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.31</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14173">이교훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.56</td><td>33</td><td>0</td><td>33</td><td>7</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td><td>35.1</td><td>29</td><td>32</td><td>32.65</td><td>166</td><td>43</td><td>11</td><td>1</td><td>7</td><td>17</td><td>2</td><td>0</td><td>27</td><td>2</td><td>0</td><td>0</td><td>7.39</td><td>8.15</td><td>8.32</td><td>8.78</td><td>6.31</td><td>1.70</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.56</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12847">김명신</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">24</span> <span><img src="/data/team/ci/2024/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-1.42</td><td>35</td><td>0</td><td>35</td><td>5</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>4</td><td>32.2</td><td>34</td><td>34</td><td>38.50</td><td>168</td><td>63</td><td>7</td><td>0</td><td>8</td><td>8</td><td>2</td><td>0</td><td>25</td><td>1</td><td>0</td><td>1</td><td>9.37</td><td>9.37</td><td>10.61</td><td>11.17</td><td>6.15</td><td>2.17</td><td style="background-color:#F3F3F3; font-weight:bold;">-1.42</td></tr>			</tbody>
		</table>""")

In [ ]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15531">후라도</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">6.61</td><td>30</td><td>30</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td><td>8</td><td>0</td><td>0</td><td>190.1</td><td>71</td><td>78</td><td>76.95</td><td>779</td><td>185</td><td>27</td><td>4</td><td>19</td><td>32</td><td>9</td><td>0</td><td>169</td><td>12</td><td>1</td><td>3</td><td>3.36</td><td>3.69</td><td>3.64</td><td>3.78</td><td>3.84</td><td>1.14</td><td style="background-color:#F3F3F3; font-weight:bold;">6.61</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16138">헤이수스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.09</td><td>30</td><td>30</td><td>0</td><td>0</td><td>0</td><td>0</td><td>13</td><td>11</td><td>0</td><td>0</td><td>171.1</td><td>70</td><td>78</td><td>75.75</td><td>728</td><td>171</td><td>31</td><td>2</td><td>22</td><td>44</td><td>14</td><td>1</td><td>178</td><td>8</td><td>1</td><td>6</td><td>3.68</td><td>4.10</td><td>3.98</td><td>4.24</td><td>4.11</td><td>1.25</td><td style="background-color:#F3F3F3; font-weight:bold;">5.09</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11222">하영민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.25</td><td>28</td><td>28</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9</td><td>8</td><td>0</td><td>0</td><td>150.1</td><td>73</td><td>82</td><td>79.25</td><td>671</td><td>168</td><td>33</td><td>6</td><td>8</td><td>58</td><td>5</td><td>0</td><td>101</td><td>9</td><td>0</td><td>7</td><td>4.37</td><td>4.91</td><td>4.74</td><td>5.02</td><td>4.45</td><td>1.50</td><td style="background-color:#F3F3F3; font-weight:bold;">3.25</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15067">주승우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.98</td><td>55</td><td>0</td><td>55</td><td>35</td><td>0</td><td>0</td><td>4</td><td>6</td><td>14</td><td>5</td><td>51.2</td><td>25</td><td>25</td><td>26.55</td><td>225</td><td>50</td><td>14</td><td>1</td><td>4</td><td>18</td><td>5</td><td>5</td><td>43</td><td>2</td><td>0</td><td>1</td><td>4.35</td><td>4.35</td><td>4.62</td><td>4.94</td><td>4.18</td><td>1.32</td><td style="background-color:#F3F3F3; font-weight:bold;">0.98</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11126">조상우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.87</td><td>44</td><td>0</td><td>44</td><td>7</td><td>0</td><td>0</td><td>0</td><td>1</td><td>6</td><td>9</td><td>39.2</td><td>14</td><td>17</td><td>18.85</td><td>171</td><td>40</td><td>6</td><td>0</td><td>2</td><td>20</td><td>0</td><td>1</td><td>36</td><td>0</td><td>0</td><td>1</td><td>3.18</td><td>3.86</td><td>4.28</td><td>4.66</td><td>4.02</td><td>1.51</td><td style="background-color:#F3F3F3; font-weight:bold;">0.87</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14480">김인범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.79</td><td>19</td><td>14</td><td>5</td><td>4</td><td>0</td><td>0</td><td>2</td><td>7</td><td>0</td><td>0</td><td>63.1</td><td>38</td><td>40</td><td>39.30</td><td>297</td><td>75</td><td>8</td><td>1</td><td>9</td><td>31</td><td>8</td><td>0</td><td>27</td><td>2</td><td>1</td><td>3</td><td>5.40</td><td>5.68</td><td>5.58</td><td>5.77</td><td>6.73</td><td>1.67</td><td style="background-color:#F3F3F3; font-weight:bold;">0.79</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12918">김성민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.65</td><td>46</td><td>0</td><td>46</td><td>4</td><td>0</td><td>0</td><td>3</td><td>4</td><td>0</td><td>14</td><td>45.2</td><td>22</td><td>24</td><td>25.15</td><td>188</td><td>45</td><td>4</td><td>0</td><td>5</td><td>17</td><td>1</td><td>0</td><td>34</td><td>0</td><td>1</td><td>3</td><td>4.34</td><td>4.73</td><td>4.96</td><td>5.33</td><td>4.86</td><td>1.36</td><td style="background-color:#F3F3F3; font-weight:bold;">0.65</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16123">김윤하</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.54</td><td>19</td><td>12</td><td>7</td><td>0</td><td>0</td><td>0</td><td>1</td><td>6</td><td>0</td><td>2</td><td>79.0</td><td>53</td><td>57</td><td>54.95</td><td>363</td><td>93</td><td>22</td><td>2</td><td>6</td><td>35</td><td>4</td><td>0</td><td>43</td><td>4</td><td>1</td><td>3</td><td>6.04</td><td>6.49</td><td>6.26</td><td>6.67</td><td>5.27</td><td>1.62</td><td style="background-color:#F3F3F3; font-weight:bold;">0.54</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12858">김재웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.54</td><td>26</td><td>0</td><td>26</td><td>1</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>7</td><td>23.2</td><td>9</td><td>9</td><td>11.25</td><td>107</td><td>24</td><td>3</td><td>1</td><td>2</td><td>12</td><td>1</td><td>1</td><td>19</td><td>3</td><td>0</td><td>1</td><td>3.42</td><td>3.42</td><td>4.28</td><td>4.63</td><td>4.90</td><td>1.52</td><td style="background-color:#F3F3F3; font-weight:bold;">0.54</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13092">김선기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.31</td><td>42</td><td>6</td><td>36</td><td>4</td><td>0</td><td>0</td><td>6</td><td>4</td><td>0</td><td>0</td><td>76.1</td><td>47</td><td>51</td><td>53.60</td><td>357</td><td>91</td><td>18</td><td>0</td><td>13</td><td>30</td><td>6</td><td>1</td><td>43</td><td>6</td><td>0</td><td>6</td><td>5.54</td><td>6.01</td><td>6.32</td><td>6.50</td><td>6.28</td><td>1.59</td><td style="background-color:#F3F3F3; font-weight:bold;">0.31</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14681">김동욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.22</td><td>37</td><td>0</td><td>37</td><td>11</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>3</td><td>36.0</td><td>20</td><td>20</td><td>23.45</td><td>146</td><td>33</td><td>9</td><td>1</td><td>4</td><td>6</td><td>2</td><td>1</td><td>18</td><td>1</td><td>0</td><td>1</td><td>5.00</td><td>5.00</td><td>5.86</td><td>6.22</td><td>4.96</td><td>1.08</td><td style="background-color:#F3F3F3; font-weight:bold;">0.22</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12854">양지율</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.16</td><td>21</td><td>0</td><td>21</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>3</td><td>18.2</td><td>13</td><td>13</td><td>11.30</td><td>83</td><td>16</td><td>4</td><td>0</td><td>1</td><td>13</td><td>2</td><td>0</td><td>7</td><td>0</td><td>0</td><td>0</td><td>6.27</td><td>6.27</td><td>5.45</td><td>5.92</td><td>6.39</td><td>1.55</td><td style="background-color:#F3F3F3; font-weight:bold;">0.16</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12989">박승주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.10</td><td>15</td><td>0</td><td>15</td><td>6</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>17.1</td><td>13</td><td>13</td><td>11.95</td><td>74</td><td>16</td><td>2</td><td>0</td><td>2</td><td>9</td><td>1</td><td>0</td><td>13</td><td>0</td><td>0</td><td>3</td><td>6.75</td><td>6.75</td><td>6.20</td><td>6.56</td><td>5.49</td><td>1.44</td><td style="background-color:#F3F3F3; font-weight:bold;">0.10</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11161">원종현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.10</td><td>4</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.2</td><td>2</td><td>2</td><td>2.00</td><td>18</td><td>4</td><td>1</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>2</td><td>4.91</td><td>4.91</td><td>4.91</td><td>4.45</td><td>4.01</td><td>1.91</td><td style="background-color:#F3F3F3; font-weight:bold;">0.10</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15475">박윤성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.09</td><td>17</td><td>0</td><td>17</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>18.2</td><td>12</td><td>12</td><td>13.40</td><td>81</td><td>14</td><td>5</td><td>0</td><td>5</td><td>9</td><td>0</td><td>0</td><td>14</td><td>2</td><td>0</td><td>2</td><td>5.79</td><td>5.79</td><td>6.46</td><td>6.62</td><td>7.01</td><td>1.23</td><td style="background-color:#F3F3F3; font-weight:bold;">0.09</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10533">정찬헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.03</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>16.0</td><td>14</td><td>14</td><td>13.30</td><td>74</td><td>26</td><td>5</td><td>0</td><td>3</td><td>3</td><td>1</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td>7.88</td><td>7.88</td><td>7.48</td><td>7.26</td><td>6.42</td><td>1.81</td><td style="background-color:#F3F3F3; font-weight:bold;">0.03</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14131">윤정현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.02</td><td>2</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.0</td><td>3</td><td>3</td><td>3.00</td><td>15</td><td>4</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>9.00</td><td>9.00</td><td>9.00</td><td>9.41</td><td>5.43</td><td>2.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.02</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15485">김동규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>2</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.1</td><td>2</td><td>2</td><td>1.30</td><td>4</td><td>1</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>54.00</td><td>54.00</td><td>35.10</td><td>32.69</td><td>22.80</td><td>9.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10437">문성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.09</td><td>42</td><td>0</td><td>42</td><td>12</td><td>0</td><td>0</td><td>1</td><td>2</td><td>3</td><td>2</td><td>38.1</td><td>28</td><td>28</td><td>29.55</td><td>189</td><td>54</td><td>6</td><td>2</td><td>3</td><td>25</td><td>2</td><td>0</td><td>31</td><td>1</td><td>0</td><td>2</td><td>6.57</td><td>6.57</td><td>6.94</td><td>7.26</td><td>5.29</td><td>2.06</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.09</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16127">김연주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.11</td><td>34</td><td>0</td><td>34</td><td>11</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td><td>31.1</td><td>23</td><td>24</td><td>24.50</td><td>148</td><td>34</td><td>10</td><td>0</td><td>5</td><td>17</td><td>5</td><td>1</td><td>18</td><td>0</td><td>0</td><td>2</td><td>6.61</td><td>6.89</td><td>7.04</td><td>7.43</td><td>6.74</td><td>1.63</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.11</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16125">손현기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.11</td><td>6</td><td>2</td><td>4</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>14.1</td><td>12</td><td>14</td><td>13.30</td><td>69</td><td>17</td><td>3</td><td>1</td><td>2</td><td>8</td><td>3</td><td>0</td><td>9</td><td>0</td><td>0</td><td>3</td><td>7.53</td><td>8.79</td><td>8.35</td><td>8.66</td><td>6.67</td><td>1.74</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.11</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14576">이종민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.12</td><td>12</td><td>9</td><td>3</td><td>0</td><td>0</td><td>0</td><td>1</td><td>8</td><td>0</td><td>0</td><td>43.2</td><td>37</td><td>39</td><td>36.10</td><td>212</td><td>56</td><td>10</td><td>2</td><td>9</td><td>22</td><td>5</td><td>2</td><td>21</td><td>2</td><td>1</td><td>0</td><td>7.63</td><td>8.04</td><td>7.44</td><td>7.72</td><td>7.22</td><td>1.79</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.12</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16133">박범준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.19</td><td>5</td><td>0</td><td>5</td><td>3</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>5.1</td><td>8</td><td>8</td><td>7.30</td><td>28</td><td>7</td><td>2</td><td>0</td><td>1</td><td>4</td><td>1</td><td>0</td><td>8</td><td>0</td><td>0</td><td>2</td><td>13.50</td><td>13.50</td><td>12.32</td><td>11.88</td><td>5.59</td><td>2.06</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.19</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15073">이명종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.30</td><td>10</td><td>0</td><td>10</td><td>7</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>11.0</td><td>10</td><td>10</td><td>13.30</td><td>58</td><td>20</td><td>2</td><td>0</td><td>4</td><td>5</td><td>0</td><td>1</td><td>4</td><td>1</td><td>0</td><td>1</td><td>8.18</td><td>8.18</td><td>10.88</td><td>11.51</td><td>8.74</td><td>2.27</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.30</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=16122">전준표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.35</td><td>18</td><td>5</td><td>13</td><td>4</td><td>0</td><td>0</td><td>2</td><td>4</td><td>0</td><td>0</td><td>27.2</td><td>21</td><td>28</td><td>27.00</td><td>144</td><td>35</td><td>4</td><td>0</td><td>4</td><td>20</td><td>5</td><td>0</td><td>18</td><td>4</td><td>0</td><td>4</td><td>6.83</td><td>9.11</td><td>8.78</td><td>8.93</td><td>7.09</td><td>1.99</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.35</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12860">오석주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.50</td><td>17</td><td>0</td><td>17</td><td>7</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>17.0</td><td>21</td><td>21</td><td>20.15</td><td>92</td><td>28</td><td>4</td><td>1</td><td>0</td><td>11</td><td>3</td><td>1</td><td>16</td><td>1</td><td>0</td><td>2</td><td>11.12</td><td>11.12</td><td>10.67</td><td>11.22</td><td>4.40</td><td>2.29</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.50</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14132">조영건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.55</td><td>25</td><td>3</td><td>22</td><td>3</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>1</td><td>39.1</td><td>35</td><td>39</td><td>35.55</td><td>197</td><td>51</td><td>10</td><td>1</td><td>7</td><td>24</td><td>1</td><td>0</td><td>31</td><td>3</td><td>0</td><td>3</td><td>8.01</td><td>8.92</td><td>8.13</td><td>8.83</td><td>6.01</td><td>1.91</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.55</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15071">윤석원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.66</td><td>11</td><td>1</td><td>10</td><td>3</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>17.1</td><td>22</td><td>24</td><td>24.20</td><td>88</td><td>31</td><td>11</td><td>0</td><td>3</td><td>7</td><td>2</td><td>0</td><td>1</td><td>2</td><td>1</td><td>3</td><td>11.42</td><td>12.46</td><td>12.57</td><td>12.91</td><td>7.72</td><td>2.19</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.66</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14674">김동혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">24</span> <span><img src="/data/team/ci/2024/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.72</td><td>17</td><td>0</td><td>17</td><td>8</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>22.1</td><td>17</td><td>21</td><td>23.75</td><td>102</td><td>27</td><td>5</td><td>1</td><td>7</td><td>10</td><td>2</td><td>0</td><td>9</td><td>1</td><td>0</td><td>0</td><td>6.85</td><td>8.46</td><td>9.57</td><td>9.86</td><td>8.59</td><td>1.66</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.72</td></tr>			</tbody>
		</table>""")

In [ ]:
len(team_tables)

10

In [ ]:
pitching = pd.DataFrame()
for i in range(len(team_tables)):
    name = team_names[i]
    team = team_tables[i]
    print(name)
    df, pids = get_team_stats_from_markup(StringIO(str(team)))
    df['팀'] = name
    df['pid'] = pids[2:]
    print(df.shape)
    print(len(pids))
    pitching = pd.concat([pitching, df])
    display(pitching.tail())

한화 이글스
(30, 39)
32

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
25,26,장지수,24 P,-0.14,13,0,13,7,0,0,...,2,10.93,11.57,9.48,9.15,4.45,2.36,-0.14,한화 이글스,14178
26,27,윤대경,24 P,-0.26,7,0,7,1,0,0,...,0,10.57,10.57,11.97,11.77,6.30,2.09,-0.26,한화 이글스,11110
27,28,이태양,24 P,-0.50,10,1,9,3,0,0,...,0,11.57,12.54,13.69,13.89,9.43,2.04,-0.50,한화 이글스,10609
28,29,한승주,24 P,-0.95,18,0,18,6,0,0,...,1,11.45,12.68,12.33,12.50,5.52,2.50,-0.95,한화 이글스,14621
29,30,정우람,24 P,NaN,1,1,0,0,0,0,...,0,NaN,NaN,NaN,NaN,4.20,99.99,NaN,한화 이글스,10156

LG 트윈스
(30, 39)
32

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
25,26,김영준,24 P,-0.33,14,0,14,5,0,0,...,2,8.22,9.98,9.77,10.23,5.58,1.96,-0.33,LG 트윈스,13102
26,27,박명근,24 P,-0.34,33,0,33,3,0,0,...,0,6.39,7.11,7.34,7.79,7.57,1.62,-0.34,LG 트윈스,15486
27,28,정지헌,24 P,-0.41,17,0,17,4,0,0,...,3,11.68,13.14,11.42,11.87,7.42,2.43,-0.41,LG 트윈스,16017
28,29,백승현,24 P,-0.50,36,0,36,7,0,0,...,1,9.11,9.45,8.64,8.92,6.90,2.06,-0.50,LG 트윈스,13009
29,30,이우찬,24 P,-0.73,42,1,41,3,0,0,...,6,8.82,9.36,8.86,8.94,5.46,2.14,-0.73,LG 트윈스,10749

롯데 자이언츠
(29, 39)
31

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
24,25,현도훈,24 P,-0.30,8,0,8,5,0,0,...,1,9.00,9.90,10.85,9.99,6.44,2.10,-0.30,롯데 자이언츠,13271
25,26,이인복,24 P,-0.31,8,6,2,1,0,0,...,4,9.55,9.55,9.83,9.35,7.79,1.88,-0.31,롯데 자이언츠,11232
26,27,송재영,24 P,-0.36,19,0,19,4,0,0,...,1,10.80,10.80,11.23,10.38,6.59,1.68,-0.36,롯데 자이언츠,14794
27,28,나균안,24 P,-0.64,26,14,12,4,0,0,...,10,8.51,9.00,9.06,8.73,6.32,2.21,-0.64,롯데 자이언츠,12930
28,29,최이준,24 P,-0.70,23,0,23,11,0,0,...,1,7.30,8.03,10.16,9.76,6.06,2.27,-0.70,롯데 자이언츠,13169

KIA 타이거즈
(32, 39)
34

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
27,28,김건국,24 P,-0.23,20,3,17,3,0,0,...,3,7.86,8.65,8.15,8.14,5.92,1.81,-0.23,KIA 타이거즈,12944
28,29,이형범,24 P,-0.30,16,0,16,5,0,0,...,0,7.80,10.20,9.48,9.66,6.77,2.20,-0.30,KIA 타이거즈,11159
29,30,김현수,24 P,-0.31,5,0,5,4,0,0,...,2,18.00,18.00,18.27,18.33,5.92,2.40,-0.31,KIA 타이거즈,14162
30,31,김대유,24 P,-0.61,37,0,37,5,0,0,...,1,8.28,8.28,9.52,9.57,5.24,1.88,-0.61,KIA 타이거즈,10706
31,32,윤중현,24 P,-0.82,11,0,11,4,0,0,...,0,13.94,14.81,16.77,16.88,11.14,3.00,-0.82,KIA 타이거즈,13122

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

KT 위즈
(26, 39)
28

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
21,22,주권,24 P,-0.18,48,1,47,13,0,0,...,0,6.67,7.45,7.74,7.60,5.05,1.53,-0.18,KT 위즈,11323
22,23,강건,24 P,-0.18,4,1,3,2,0,0,...,0,11.25,11.25,13.16,13.69,9.17,3.00,-0.18,KT 위즈,15527
23,24,전용주,24 P,-0.22,4,0,4,0,0,0,...,0,10.80,16.20,17.01,17.02,5.64,3.00,-0.22,KT 위즈,14106
24,25,한차현,24 P,-0.24,10,5,5,2,0,0,...,2,9.95,10.42,9.33,9.40,7.40,2.47,-0.24,KT 위즈,14776
25,26,문용익,24 P,-0.79,12,0,12,4,0,0,...,2,12.18,14.29,15.11,15.15,7.48,2.65,-0.79,KT 위즈,12885

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

삼성 라이온즈
(28, 39)
30

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
23,24,김대호,24 P,-0.17,1,1,0,0,0,0,...,0,11.25,13.50,13.50,13.55,8.10,2.25,-0.17,삼성 라이온즈,15882
24,25,홍정우,24 P,-0.18,1,0,1,1,0,0,...,0,45.00,45.00,45.00,40.80,16.70,6.00,-0.18,삼성 라이온즈,13242
25,26,김윤수,24 P,-0.24,4,0,4,2,0,0,...,1,10.13,10.13,11.31,10.93,7.33,2.44,-0.24,삼성 라이온즈,13162
26,27,이승민,24 P,-0.33,25,8,17,6,0,0,...,1,8.56,9.13,8.60,8.27,8.40,2.05,-0.33,삼성 라이온즈,14616
27,28,이재익,24 P,-0.76,9,0,9,1,0,0,...,0,17.69,17.69,16.53,17.15,6.39,3.41,-0.76,삼성 라이온즈,13244

SSG 랜더스

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(28, 39)
30

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
23,24,김주온,24 P,-0.26,2,0,2,2,0,0,...,0,15.43,15.43,18.42,18.21,9.15,2.36,-0.26,SSG 랜더스,13057
24,25,서진용,24 P,-0.35,51,0,51,3,0,0,...,4,5.55,6.51,7.82,7.52,5.09,1.66,-0.35,SSG 랜더스,10784
25,26,이건욱,24 P,-0.58,10,2,8,1,0,0,...,3,11.37,11.84,11.51,11.46,7.87,2.58,-0.58,SSG 랜더스,11242
26,27,최민준,24 P,-0.67,32,0,32,3,0,0,...,1,7.78,8.24,9.43,9.17,6.43,2.16,-0.67,SSG 랜더스,13126
27,28,더거,24 P,-0.84,6,6,0,0,0,0,...,0,12.71,13.10,13.10,12.80,5.04,2.07,-0.84,SSG 랜더스,16141

NC 다이노스
(31, 39)
33

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
26,27,목지훈,24 P,-0.26,3,3,0,0,0,0,...,1,12.00,12.00,11.15,11.79,8.82,2.78,-0.26,NC 다이노스,15453
27,28,전사민,24 P,-0.45,17,0,17,9,0,0,...,4,9.51,9.51,9.91,10.02,6.53,2.37,-0.45,NC 다이노스,14156
28,29,전루건,24 P,-0.45,6,0,6,1,0,0,...,0,22.24,22.24,22.47,21.89,11.31,4.24,-0.45,NC 다이노스,14171
29,30,이준호,24 P,-0.62,38,2,36,12,0,0,...,0,7.48,7.48,8.46,8.64,5.58,1.97,-0.62,NC 다이노스,15455
30,31,이용찬,24 P,-1.14,57,0,57,36,0,0,...,6,6.13,7.95,7.70,8.00,4.57,1.90,-1.14,NC 다이노스,10217

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

두산 베어스
(30, 39)
32

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
25,26,김정우,24 P,-0.13,1,0,1,0,0,0,...,0,81.00,81.00,67.50,72.77,4.20,9.00,-0.13,두산 베어스,13124
26,27,김동주,24 P,-0.25,14,9,5,3,1,0,...,7,6.84,8.28,7.64,7.90,5.43,1.76,-0.25,두산 베어스,14769
27,28,김호준,24 P,-0.31,16,1,15,6,0,0,...,0,8.78,9.45,10.13,9.94,6.06,1.95,-0.31,두산 베어스,13268
28,29,이교훈,24 P,-0.56,33,0,33,7,0,0,...,0,7.39,8.15,8.32,8.78,6.31,1.70,-0.56,두산 베어스,14173
29,30,김명신,24 P,-1.42,35,0,35,5,0,0,...,1,9.37,9.37,10.61,11.17,6.15,2.17,-1.42,두산 베어스,12847

키움 히어로즈

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(29, 39)
31

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
24,25,전준표,24 P,-0.35,18,5,13,4,0,0,...,4,6.83,9.11,8.78,8.93,7.09,1.99,-0.35,키움 히어로즈,16122
25,26,오석주,24 P,-0.50,17,0,17,7,0,0,...,2,11.12,11.12,10.67,11.22,4.40,2.29,-0.50,키움 히어로즈,12860
26,27,조영건,24 P,-0.55,25,3,22,3,0,0,...,3,8.01,8.92,8.13,8.83,6.01,1.91,-0.55,키움 히어로즈,14132
27,28,윤석원,24 P,-0.66,11,1,10,3,0,0,...,3,11.42,12.46,12.57,12.91,7.72,2.19,-0.66,키움 히어로즈,15071
28,29,김동혁,24 P,-0.72,17,0,17,8,0,0,...,0,6.85,8.46,9.57,9.86,8.59,1.66,-0.72,키움 히어로즈,14674

In [ ]:
pitching.describe()

,Rank,Sort▼,G,GS,GR,GF,CG,SHO,W,L,...,ROE,BK,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼
,Rank,WAR,G,GS,GR,GF,CG,SHO,W,L,...,ROE,BK,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼
count,293.000000,292.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,293.000000,...,293.000000,293.000000,293.000000,292.000000,292.000000,292.000000,292.000000,293.000000,293.000000,292.000000
mean,15.194539,0.768938,24.102389,4.914676,19.187713,4.914676,0.034130,0.013652,2.423208,2.423208,...,2.252560,0.143345,2.102389,7.821747,8.412671,8.131404,8.089692,37.560410,2.607782,0.768938
std,8.543585,1.502978,20.201801,8.621188,22.143266,8.166266,0.245917,0.116239,3.330804,2.780511,...,2.803686,0.379164,2.317982,11.051041,11.043583,9.270039,9.106612,543.225193,8.213841,1.502978
min,1.000000,-1.420000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.800000,0.000000,-1.420000
25%,8.000000,-0.110000,8.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,4.090000,4.517500,4.485000,4.605000,4.400000,1.410000,-0.110000
50%,15.000000,0.140000,19.000000,0.000000,9.000000,3.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,1.000000,5.390000,5.955000,6.170000,6.110000,5.300000,1.650000,0.140000
75%,22.000000,1.192500,34.000000,6.000000,33.000000,6.000000,0.000000,0.000000,3.000000,4.000000,...,3.000000,0.000000,3.000000,7.710000,8.477500,8.377500,8.645000,6.420000,2.040000,1.192500
max,32.000000,6.930000,77.000000,32.000000,77.000000,52.000000,3.000000,1.000000,15.000000,12.000000,...,17.000000,2.000000,11.000000,99.990000,99.990000,106.650000,102.270000,9304.200000,99.990000,6.930000

In [ ]:
pitching.isna().sum()

Rank    Rank      0
Name    Name      0
Team    Team      0
Sort▼   WAR       1
G       G         0
GS      GS        0
GR      GR        0
GF      GF        0
CG      CG        0
SHO     SHO       0
W       W         0
L       L         0
S       S         0
HD      HD        0
IP      IP        0
ER      ER        0
R       R         0
rRA     rRA       0
TBF     TBF       0
H       H         0
2B      2B        0
3B      3B        0
HR      HR        0
BB      BB        0
HP      HP        0
IB      IB        0
SO      SO        0
ROE     ROE       0
BK      BK        0
WP      WP        0
ERA     ERA       1
RA9     RA9       1
rRA9    rRA9      1
rRA9pf  rRA9pf    1
FIP     FIP       0
WHIP    WHIP      0
WAR▼    WAR▼      1
팀                 0
pid               0
dtype: int64

In [ ]:
pitching['Team'].value_counts()

Team
24 P     292
24 CF      1
Name: count, dtype: int64

In [ ]:
pitching.to_csv('2024_투구_statiz.csv', index=False)

In [ ]:
team_tables = []

In [ ]:
team_tables.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=10590">류현진</a></td><td>250,000</td><td>4.56</td><td>54,775</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11215">채은성</a></td><td>100,000</td><td>1.40</td><td>71,340</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15146">페냐</a></td><td>65,000</td><td>0.35</td><td>187,034</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16121">페라자</a></td><td>60,000</td><td>2.90</td><td>20,686</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10170">최재훈</a></td><td>60,000</td><td>1.68</td><td>35,760</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10609">이태양</a></td><td>50,000</td><td>-0.29</td><td>-170,710</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10014">안치홍</a></td><td>50,000</td><td>1.97</td><td>25,319</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15643">산체스</a></td><td>50,000</td><td>1.58</td><td>31,615</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16150">바리아</a></td><td>48,000</td><td>1.75</td><td>27,382</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14125">노시환</a></td><td>35,000</td><td>2.92</td><td>11,985</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10453">장시환</a></td><td>20,000</td><td>0.21</td><td>97,084</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12871">박상원</a></td><td>19,500</td><td>1.00</td><td>19,491</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11411">김범수</a></td><td>19,300</td><td>0.14</td><td>134,337</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13137">정은원</a></td><td>17,800</td><td>0.14</td><td>130,324</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11410">김민우</a></td><td>16,700</td><td>0.62</td><td>26,890</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10610">장민재</a></td><td>15,000</td><td>0.66</td><td>22,587</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10108">김강민</a></td><td>11,000</td><td>0.08</td><td>142,068</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11415">주현상</a></td><td>11,000</td><td>3.16</td><td>3,479</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11110">윤대경</a></td><td>11,000</td><td>-0.13</td><td>-85,456</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10156">정우람</a></td><td>10,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15013">문동주</a></td><td>10,000</td><td>1.93</td><td>5,191</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15422">문현빈</a></td><td>8,000</td><td>0.24</td><td>33,324</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12585">김태연</a></td><td>7,800</td><td>0.47</td><td>16,566</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11414">이도윤</a></td><td>7,500</td><td>1.14</td><td>6,585</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12539">이진영</a></td><td>7,000</td><td>0.03</td><td>205,441</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10913">하주석</a></td><td>7,000</td><td>0.23</td><td>30,579</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12589">김인환</a></td><td>6,900</td><td>-1.27</td><td>-5,425</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11117">김종수</a></td><td>6,800</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12583">장진혁</a></td><td>5,800</td><td>0.76</td><td>7,644</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13003">이민우</a></td><td>5,600</td><td>0.90</td><td>6,199</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14158">배민서</a></td><td>5,100</td><td>-0.03</td><td>-178,322</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10119">이명기</a></td><td>5,000</td><td>-0.09</td><td>-53,323</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10082">이재원</a></td><td>5,000</td><td>-0.25</td><td>-19,618</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10812">한승혁</a></td><td>4,900</td><td>0.96</td><td>5,130</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16153">와이스</a></td><td>4,800</td><td>3.16</td><td>1,521</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14707">최인호</a></td><td>4,800</td><td>2.03</td><td>2,359</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14621">한승주</a></td><td>4,500</td><td>-0.48</td><td>-9,304</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13245">이상규</a></td><td>4,400</td><td>0.38</td><td>11,481</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14808">김기중</a></td><td>4,400</td><td>0.38</td><td>11,587</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12587">박상언</a></td><td>4,200</td><td>0.53</td><td>7,988</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14871">김규연</a></td><td>4,100</td><td>0.07</td><td>59,451</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14619">남지민</a></td><td>4,000</td><td>0.10</td><td>38,156</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14210">조한민</a></td><td>3,800</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13138">이원석</a></td><td>3,600</td><td>0.19</td><td>18,675</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11116">이충호</a></td><td>3,400</td><td>-0.05</td><td>-68,741</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14706">임종찬</a></td><td>3,400</td><td>-0.22</td><td>-15,452</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15421">김서현</a></td><td>3,300</td><td>0.65</td><td>5,071</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13676">권광민</a></td><td>3,300</td><td>0.53</td><td>6,250</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14204">허관회</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14126">유로결</a></td><td>3,300</td><td>-0.06</td><td>-59,189</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14811">장규현</a></td><td>3,200</td><td>-0.13</td><td>-23,948</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14209">김건</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14178">장지수</a></td><td>3,200</td><td>-0.08</td><td>-39,864</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12902">이재용</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15139">이상혁</a></td><td>3,100</td><td>-0.11</td><td>-28,290</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15423">이민준</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16120">서정훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16119">김선동</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16118">김도빈</a></td><td>3,000</td><td>-0.02</td><td>-128,266</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16117">권동욱</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16116">승지환</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16115">권현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16114">원종혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16113">이승현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16112">최준서</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16111">이기창</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16110">황영묵</a></td><td>3,000</td><td>1.83</td><td>1,642</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16109">정안석</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16108">조동욱</a></td><td>3,000</td><td>0.08</td><td>35,359</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16107">황준서</a></td><td>3,000</td><td>1.31</td><td>2,288</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13144">김진욱</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15019">이성민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14127">정이황</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14810">조은</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15633">한경빈</a></td><td>3,000</td><td>0.00</td><td>-629,368</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15631">성지훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14711">김승일</a></td><td>3,000</td><td>0.13</td><td>23,229</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14812">송호정</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16011">신우재</a></td><td>-</td><td>-</td><td>-</td></tr>							</tbody>
						</table>""")

In [ ]:
team_tables.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=10387">박동원</a></td><td>250,000</td><td>4.75</td><td>52,599</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10187">김현수</a></td><td>100,000</td><td>1.01</td><td>99,083</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13934">켈리</a></td><td>80,000</td><td>1.73</td><td>46,128</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15532">오스틴</a></td><td>80,000</td><td>5.62</td><td>14,229</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16023">엔스</a></td><td>60,000</td><td>3.76</td><td>15,962</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11190">박해민</a></td><td>60,000</td><td>2.71</td><td>22,112</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12546">홍창기</a></td><td>51,000</td><td>6.29</td><td>8,112</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16160">에르난데스</a></td><td>44,000</td><td>1.33</td><td>32,988</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11379">최원태</a></td><td>40,000</td><td>2.78</td><td>14,390</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14136">정우영</a></td><td>32,000</td><td>-0.02</td><td>-2,063,305</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14137">문보경</a></td><td>30,000</td><td>4.30</td><td>6,972</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10475">오지환</a></td><td>30,000</td><td>3.12</td><td>9,616</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13112">문성주</a></td><td>20,000</td><td>2.89</td><td>6,928</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11094">함덕주</a></td><td>20,000</td><td>0.26</td><td>78,097</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11166">김진성</a></td><td>20,000</td><td>0.57</td><td>35,046</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10652">임찬규</a></td><td>20,000</td><td>3.98</td><td>5,029</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10535">최동환</a></td><td>13,000</td><td>-0.22</td><td>-58,350</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10749">이우찬</a></td><td>12,500</td><td>-0.64</td><td>-19,685</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14588">김윤식</a></td><td>12,000</td><td>-0.07</td><td>-163,067</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13056">신민재</a></td><td>11,500</td><td>2.36</td><td>4,876</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10684">허도환</a></td><td>10,000</td><td>-0.76</td><td>-13,118</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13009">백승현</a></td><td>9,200</td><td>-0.40</td><td>-22,725</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14669">유영찬</a></td><td>8,500</td><td>0.66</td><td>12,856</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14140">구본혁</a></td><td>7,000</td><td>1.57</td><td>4,471</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11170">윤호솔</a></td><td>7,000</td><td>0.10</td><td>69,777</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13104">이재원</a></td><td>7,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14143">이지강</a></td><td>6,800</td><td>-0.09</td><td>-76,140</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11229">김유영</a></td><td>6,700</td><td>0.56</td><td>11,926</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15486">박명근</a></td><td>6,500</td><td>-0.34</td><td>-19,027</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12931">김민수</a></td><td>6,000</td><td>-0.36</td><td>-16,868</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12697">배재준</a></td><td>6,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12532">김대현</a></td><td>5,700</td><td>0.03</td><td>216,389</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11347">안익훈</a></td><td>5,500</td><td>0.01</td><td>689,157</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14783">이영빈</a></td><td>5,500</td><td>0.00</td><td>2,305,239</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14135">이상영</a></td><td>5,000</td><td>0.50</td><td>9,955</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14142">임준형</a></td><td>4,800</td><td>0.13</td><td>37,733</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12908">손주영</a></td><td>4,300</td><td>3.68</td><td>1,168</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14187">최승민</a></td><td>4,000</td><td>-0.02</td><td>-251,300</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14780">강효종</a></td><td>3,800</td><td>-0.06</td><td>-66,747</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13102">김영준</a></td><td>3,600</td><td>-0.23</td><td>-15,448</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13109">송찬의</a></td><td>3,600</td><td>-0.12</td><td>-29,631</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12545">김주성</a></td><td>3,500</td><td>0.17</td><td>20,427</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15484">김범석</a></td><td>3,300</td><td>-0.31</td><td>-10,590</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12864">전준호</a></td><td>3,300</td><td>-0.02</td><td>-155,746</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13103">성동현</a></td><td>3,200</td><td>0.08</td><td>37,930</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14781">김진수</a></td><td>3,200</td><td>0.02</td><td>204,366</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15085">김성우</a></td><td>3,100</td><td>-0.24</td><td>-12,863</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14816">우강훈</a></td><td>3,100</td><td>0.15</td><td>20,274</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14141">김성진</a></td><td>3,100</td><td>-0.04</td><td>-73,680</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16013">김현종</a></td><td>3,000</td><td>0.17</td><td>17,163</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16014">손용준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16015">진우영</a></td><td>3,000</td><td>0.08</td><td>36,767</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16018">배강</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16026">최명경</a></td><td>3,000</td><td>-0.04</td><td>-68,830</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16025">이태겸</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16024">오승윤</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16022">심규빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16021">김도윤</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16020">강석현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16016">김대원</a></td><td>3,000</td><td>0.07</td><td>44,048</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16017">정지헌</a></td><td>3,000</td><td>-0.24</td><td>-12,395</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16019">김종우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14604">한지용</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14651">이종준</a></td><td>3,000</td><td>0.35</td><td>8,545</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15086">문정빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15084">최원영</a></td><td>3,000</td><td>0.25</td><td>11,916</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14782">조건희</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13108">김의준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15081">이주헌</a></td><td>3,000</td><td>0.10</td><td>29,869</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14841">김단우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14842">김유민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14844">김형욱</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14845">박민호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14885">전진영</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14847">이믿음</a></td><td>3,000</td><td>-0.16</td><td>-18,953</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13174">백선기</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14671">하영진</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13057">김주온</a></td><td>3,000</td><td>-0.11</td><td>-27,713</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14680">함창건</a></td><td>3,000</td><td>-0.19</td><td>-15,608</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14660">강민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14675">김수인</a></td><td>3,000</td><td>-0.15</td><td>-20,407</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15491">허용주</a></td><td>3,000</td><td>-</td><td>-</td></tr>							</tbody>
						</table>""")

In [ ]:
team_tables.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=11310">박세웅</a></td><td>135,000</td><td>4.69</td><td>28,778</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10266">전준우</a></td><td>130,000</td><td>1.95</td><td>66,702</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10753">유강남</a></td><td>100,000</td><td>0.02</td><td>5,859,879</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15011">반즈</a></td><td>85,000</td><td>6.81</td><td>12,473</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16106">레이예스</a></td><td>60,000</td><td>3.72</td><td>16,111</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12295">윌커슨</a></td><td>60,000</td><td>7.42</td><td>8,084</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11165">노진혁</a></td><td>60,000</td><td>-0.23</td><td>-260,317</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10825">김원중</a></td><td>50,000</td><td>2.65</td><td>18,866</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11291">구승민</a></td><td>45,000</td><td>0.24</td><td>188,098</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10253">정훈</a></td><td>30,000</td><td>1.18</td><td>25,494</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10863">한현희</a></td><td>30,000</td><td>1.66</td><td>18,041</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10238">김민성</a></td><td>20,000</td><td>0.13</td><td>150,016</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12930">나균안</a></td><td>17,000</td><td>-0.30</td><td>-56,322</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14624">최준용</a></td><td>16,300</td><td>0.13</td><td>121,606</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13145">한동희</a></td><td>16,200</td><td>-0.57</td><td>-28,421</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10427">김상수</a></td><td>16,000</td><td>1.22</td><td>13,126</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10075">진해수</a></td><td>15,000</td><td>0.02</td><td>609,489</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10804">박승욱</a></td><td>13,500</td><td>-0.10</td><td>-135,107</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11232">이인복</a></td><td>10,000</td><td>-0.10</td><td>-101,025</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10557">오선진</a></td><td>10,000</td><td>0.18</td><td>54,627</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11311">심재민</a></td><td>9,400</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14114">이학주</a></td><td>9,200</td><td>-0.19</td><td>-48,785</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15048">윤동희</a></td><td>9,000</td><td>3.72</td><td>2,419</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11425">박진형</a></td><td>8,600</td><td>0.21</td><td>40,344</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15253">김민석</a></td><td>8,500</td><td>-0.32</td><td>-26,589</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14160">고승민</a></td><td>8,000</td><td>3.49</td><td>2,294</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13148">김도규</a></td><td>8,000</td><td>-0.01</td><td>-706,658</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10516">신정락</a></td><td>8,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14642">황성빈</a></td><td>7,600</td><td>2.15</td><td>3,532</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13154">정보근</a></td><td>7,500</td><td>-0.54</td><td>-13,918</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12916">이정훈</a></td><td>6,000</td><td>0.49</td><td>12,178</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14792">김진욱</a></td><td>6,000</td><td>2.38</td><td>2,524</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11413">지시완</a></td><td>5,800</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14169">신윤후</a></td><td>5,200</td><td>0.30</td><td>17,392</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14796">손성빈</a></td><td>5,000</td><td>0.24</td><td>21,042</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14590">손호영</a></td><td>4,500</td><td>2.83</td><td>1,587</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15047">진승현</a></td><td>4,300</td><td>0.02</td><td>177,767</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10795">임준섭</a></td><td>4,000</td><td>0.11</td><td>37,866</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13155">장두성</a></td><td>4,000</td><td>-0.22</td><td>-17,905</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11276">최설우</a></td><td>4,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14797">나승엽</a></td><td>4,000</td><td>1.44</td><td>2,783</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13147">정성종</a></td><td>3,900</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13169">최이준</a></td><td>3,800</td><td>-0.36</td><td>-10,553</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15045">이민석</a></td><td>3,800</td><td>0.10</td><td>36,348</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11388">강태율</a></td><td>3,600</td><td>-0.27</td><td>-13,194</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14163">박진</a></td><td>3,300</td><td>1.15</td><td>2,860</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15624">서동욱</a></td><td>3,300</td><td>-0.48</td><td>-6,922</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15443">정대선</a></td><td>3,200</td><td>0.04</td><td>89,444</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12699">김강현</a></td><td>3,200</td><td>0.52</td><td>6,205</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13271">현도훈</a></td><td>3,200</td><td>-0.13</td><td>-24,338</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14622">박명현</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15441">이진하</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15444">이태연</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10810">최항</a></td><td>3,100</td><td>-0.18</td><td>-17,554</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12928">윤성빈</a></td><td>3,100</td><td>-0.06</td><td>-49,968</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15645">김동혁</a></td><td>3,100</td><td>0.21</td><td>14,524</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13173">신병률</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14819">이주찬</a></td><td>3,100</td><td>-0.49</td><td>-6,332</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14795">정우준</a></td><td>3,100</td><td>0.04</td><td>78,951</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14794">송재영</a></td><td>3,100</td><td>-0.17</td><td>-18,291</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14625">홍민기</a></td><td>3,100</td><td>-0.01</td><td>-245,954</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16096">안우진</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16095">이선우</a></td><td>3,000</td><td>-0.20</td><td>-14,708</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16094">박성준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16093">강성우</a></td><td>3,000</td><td>-0.01</td><td>-577,736</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16092">박준우</a></td><td>3,000</td><td>0.00</td><td>3,037,969</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16091">이호준</a></td><td>3,000</td><td>0.12</td><td>25,827</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16090">정현수</a></td><td>3,000</td><td>0.89</td><td>3,373</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16089">전미르</a></td><td>3,000</td><td>0.45</td><td>6,734</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16097">소한빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16098">전하원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16099">유제모</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16105">기민성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16104">김대현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16103">고경표</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16102">강승구</a></td><td>3,000</td><td>-0.08</td><td>-39,274</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16101">백두산</a></td><td>3,000</td><td>-0.02</td><td>-150,583</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16100">배세종</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15050">하혜성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14817">이병준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14818">최우인</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14690">이인한</a></td><td>3,000</td><td>0.12</td><td>24,573</td></tr>							</tbody>
						</table>""")

In [ ]:
team_tables.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=10344">최형우</a></td><td>100,000</td><td>2.09</td><td>47,887</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11162">나성범</a></td><td>80,000</td><td>1.84</td><td>43,391</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10459">김태군</a></td><td>70,000</td><td>1.00</td><td>70,094</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10008">김선빈</a></td><td>60,000</td><td>2.11</td><td>28,379</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16087">크로우</a></td><td>60,000</td><td>1.28</td><td>47,041</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14996">소크라테스</a></td><td>50,000</td><td>4.06</td><td>12,324</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10058">양현종</a></td><td>50,000</td><td>4.99</td><td>10,026</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16088">네일</a></td><td>35,000</td><td>5.02</td><td>6,975</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11261">박찬호</a></td><td>30,000</td><td>4.03</td><td>7,451</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16151">알드레드</a></td><td>30,000</td><td>1.45</td><td>20,711</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16161">라우어</a></td><td>30,000</td><td>0.88</td><td>33,923</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10909">임기영</a></td><td>25,000</td><td>-0.20</td><td>-125,138</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12534">최원준</a></td><td>22,000</td><td>2.35</td><td>9,351</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14608">정해영</a></td><td>20,000</td><td>2.35</td><td>8,510</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12537">전상현</a></td><td>17,000</td><td>1.49</td><td>11,445</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14788">이의리</a></td><td>17,000</td><td>0.09</td><td>183,155</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11164">장현식</a></td><td>16,000</td><td>1.69</td><td>9,468</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10659">고종욱</a></td><td>15,000</td><td>0.09</td><td>165,595</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11303">이준영</a></td><td>14,000</td><td>0.38</td><td>36,780</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11099">이우성</a></td><td>13,000</td><td>-0.10</td><td>-128,006</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11233">이창진</a></td><td>12,000</td><td>0.64</td><td>18,738</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10706">김대유</a></td><td>11,000</td><td>-0.35</td><td>-31,834</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15057">최지민</a></td><td>10,000</td><td>0.38</td><td>25,990</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15056">김도영</a></td><td>10,000</td><td>8.52</td><td>1,174</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11298">김호령</a></td><td>9,000</td><td>-0.07</td><td>-126,775</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15432">윤영철</a></td><td>9,000</td><td>2.11</td><td>4,261</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11070">박준표</a></td><td>8,000</td><td>-0.04</td><td>-194,862</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11306">황대인</a></td><td>8,000</td><td>-0.02</td><td>-349,722</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11159">이형범</a></td><td>7,000</td><td>-0.19</td><td>-36,107</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11119">한승택</a></td><td>6,500</td><td>-0.10</td><td>-64,995</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13122">윤중현</a></td><td>6,500</td><td>-0.35</td><td>-18,821</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14124">변우혁</a></td><td>6,000</td><td>0.64</td><td>9,336</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12540">김규성</a></td><td>5,500</td><td>-0.18</td><td>-30,087</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10855">서건창</a></td><td>5,000</td><td>1.61</td><td>3,106</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13113">한준수</a></td><td>5,000</td><td>1.80</td><td>2,774</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16163">스타우트</a></td><td>4,500</td><td>0.33</td><td>13,448</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14162">김현수</a></td><td>4,500</td><td>-0.12</td><td>-38,109</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12567">주효상</a></td><td>4,400</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11407">최정용</a></td><td>4,300</td><td>-0.18</td><td>-23,881</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13114">김유신</a></td><td>4,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12637">김승현</a></td><td>4,100</td><td>0.12</td><td>34,777</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14176">김기훈</a></td><td>4,000</td><td>0.05</td><td>75,404</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13093">예진원</a></td><td>4,000</td><td>-0.53</td><td>-7,559</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12944">김건국</a></td><td>4,000</td><td>-0.20</td><td>-19,538</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12917">김석환</a></td><td>4,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12869">박정우</a></td><td>3,800</td><td>0.42</td><td>8,953</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12914">유승철</a></td><td>3,600</td><td>0.12</td><td>31,245</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14612">홍종표</a></td><td>3,500</td><td>0.26</td><td>13,612</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15063">황동하</a></td><td>3,500</td><td>2.12</td><td>1,652</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14789">장민기</a></td><td>3,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14611">박민</a></td><td>3,500</td><td>-0.03</td><td>-103,627</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14128">김도현</a></td><td>3,500</td><td>1.18</td><td>2,957</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11364">김사윤</a></td><td>3,400</td><td>-0.10</td><td>-32,496</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14181">오선우</a></td><td>3,300</td><td>-0.03</td><td>-95,565</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15435">곽도규</a></td><td>3,300</td><td>1.27</td><td>2,592</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12612">임석진</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14790">권혁경</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12618">최수빈</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13171">고명성</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15433">정해원</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14786">박건우</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14607">유지성</a></td><td>3,100</td><td>-0.02</td><td>-128,033</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16079">김태윤</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16078">이상준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16077">조대현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16157">박시온</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14657">장재혁</a></td><td>3,000</td><td>0.06</td><td>50,100</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16086">김두현</a></td><td>3,000</td><td>-0.21</td><td>-13,982</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16085">성영탁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16084">강민제</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16083">김민재</a></td><td>3,000</td><td>-0.06</td><td>-46,670</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16082">김민주</a></td><td>3,000</td><td>-0.04</td><td>-82,061</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16081">최지웅</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14655">오규석</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16080">강동훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15125">박상준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14177">홍원빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15440">김재현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15439">김도월</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15437">이도현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15436">이송찬</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14791">김원경</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13117">오정환</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15061">이성주</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15060">김찬민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15058">윤도현</a></td><td>3,000</td><td>0.51</td><td>5,916</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14824">장시현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14826">이영재</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12866">강이준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14183">김민수</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14823">이준범</a></td><td>-</td><td>-</td><td>-</td></tr>							</tbody>
						</table>""")

In [ ]:
team_tables.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=11308">고영표</a></td><td>200,000</td><td>1.89</td><td>105,830</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10407">황재균</a></td><td>100,000</td><td>-0.19</td><td>-536,924</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13942">쿠에바스</a></td><td>100,000</td><td>4.93</td><td>20,280</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15143">벤자민</a></td><td>90,000</td><td>3.07</td><td>29,362</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12995">로하스</a></td><td>50,000</td><td>7.26</td><td>6,889</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10235">장성우</a></td><td>50,000</td><td>3.51</td><td>14,254</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10400">오재일</a></td><td>50,000</td><td>-0.84</td><td>-59,474</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11212">배정대</a></td><td>32,000</td><td>0.77</td><td>41,600</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10320">김상수</a></td><td>30,000</td><td>1.95</td><td>15,374</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11334">심우준</a></td><td>29,000</td><td>0.90</td><td>32,170</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13168">강백호</a></td><td>29,000</td><td>2.75</td><td>10,546</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11318">엄상백</a></td><td>25,000</td><td>3.95</td><td>6,335</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11339">김민혁</a></td><td>24,000</td><td>2.70</td><td>8,893</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10523">우규민</a></td><td>22,000</td><td>1.34</td><td>16,466</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14600">소형준</a></td><td>22,000</td><td>0.31</td><td>70,608</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11323">주권</a></td><td>20,000</td><td>-0.17</td><td>-118,929</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10469">박경수</a></td><td>20,000</td><td>0.08</td><td>260,169</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15089">박영현</a></td><td>16,000</td><td>2.43</td><td>6,581</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11317">김민수</a></td><td>16,000</td><td>0.51</td><td>31,184</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12943">조용호</a></td><td>15,000</td><td>-0.42</td><td>-35,436</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11397">오윤석</a></td><td>14,000</td><td>1.57</td><td>8,907</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10840">신본기</a></td><td>13,000</td><td>0.83</td><td>15,636</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14108">손동현</a></td><td>12,000</td><td>0.13</td><td>88,905</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11333">문상철</a></td><td>11,000</td><td>3.43</td><td>3,206</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10835">김준태</a></td><td>10,000</td><td>0.19</td><td>52,689</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10737">박시영</a></td><td>9,000</td><td>0.29</td><td>30,622</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13151">이호연</a></td><td>8,500</td><td>-0.65</td><td>-13,160</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11342">송민섭</a></td><td>6,500</td><td>-0.27</td><td>-24,314</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12885">문용익</a></td><td>6,300</td><td>-0.34</td><td>-18,391</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14109">이상동</a></td><td>6,000</td><td>-0.03</td><td>-179,748</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11284">조이현</a></td><td>6,000</td><td>0.51</td><td>11,721</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11214">장준원</a></td><td>5,300</td><td>-0.03</td><td>-171,447</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13130">이채호</a></td><td>5,300</td><td>-0.11</td><td>-50,284</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14603">강현우</a></td><td>5,000</td><td>0.38</td><td>13,279</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13006">안치영</a></td><td>5,000</td><td>-0.07</td><td>-71,312</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13167">김민</a></td><td>5,000</td><td>1.84</td><td>2,712</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14777">권동진</a></td><td>4,600</td><td>-0.07</td><td>-64,146</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14606">천성호</a></td><td>4,500</td><td>0.08</td><td>54,946</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12941">홍현빈</a></td><td>4,500</td><td>-0.16</td><td>-29,019</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10304">하준호</a></td><td>4,500</td><td>0.00</td><td>-1,497,604</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15519">정준영</a></td><td>4,200</td><td>0.41</td><td>10,337</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14869">김영현</a></td><td>4,100</td><td>0.00</td><td>2,704,271</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14111">이선우</a></td><td>4,000</td><td>0.15</td><td>26,897</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14191">강민성</a></td><td>3,600</td><td>0.01</td><td>427,911</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15527">강건</a></td><td>3,500</td><td>-0.13</td><td>-27,776</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12577">김태오</a></td><td>3,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12937">이정현</a></td><td>3,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12572">박세진</a></td><td>3,500</td><td>-0.05</td><td>-71,550</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14106">전용주</a></td><td>3,200</td><td>-0.09</td><td>-35,628</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13233">양승혁</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15523">류현인</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14110">박민석</a></td><td>3,100</td><td>-0.42</td><td>-7,327</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13177">조대현</a></td><td>3,100</td><td>0.49</td><td>6,355</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15518">김정운</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15097">김병준</a></td><td>3,100</td><td>0.27</td><td>11,466</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14776">한차현</a></td><td>3,100</td><td>-0.25</td><td>-12,239</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16037">김지민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16034">이승현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16033">박태완</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16032">박정현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16031">신호준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16030">최윤서</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16029">김민성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16028">육청명</a></td><td>3,000</td><td>0.63</td><td>4,742</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16027">원상현</a></td><td>3,000</td><td>0.04</td><td>70,898</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16035">김민석</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16036">이승언</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14605">윤준혁</a></td><td>3,000</td><td>-0.24</td><td>-12,470</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16159">이현민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16144">한민우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14658">최용준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14179">이태규</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13170">박시윤</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15092">안현민</a></td><td>3,000</td><td>-0.10</td><td>-29,490</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14779">김건형</a></td><td>3,000</td><td>-0.21</td><td>-14,433</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15254">이근혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14884">김규대</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14870">최성민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13172">윤강찬</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14833">김주완</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15619">최정태</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12938">이종혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15526">이준명</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15525">정진호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15524">황의준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15522">이준희</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15521">김건웅</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14667">성재헌</a></td><td>3,000</td><td>-0.07</td><td>-45,935</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14670">조용근</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14774">신범준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13083">김철호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14723">김성균</a></td><td>3,000</td><td>-</td><td>-</td></tr>							</tbody>
						</table>""")

In [ ]:
team_tables.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=10892">구자욱</a></td><td>200,000</td><td>6.19</td><td>32,316</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15862">맥키넌</a></td><td>90,000</td><td>1.16</td><td>77,659</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15860">코너</a></td><td>80,000</td><td>4.85</td><td>16,504</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10470">박병호</a></td><td>70,000</td><td>0.25</td><td>283,380</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15861">레예스</a></td><td>50,000</td><td>4.16</td><td>12,032</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14113">원태인</a></td><td>43,000</td><td>4.90</td><td>8,780</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10232">강민호</a></td><td>40,000</td><td>3.50</td><td>11,445</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10367">오승환</a></td><td>40,000</td><td>-0.40</td><td>-101,083</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10363">백정현</a></td><td>40,000</td><td>0.72</td><td>55,812</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11489">김재윤</a></td><td>40,000</td><td>0.70</td><td>56,762</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16156">카디네스</a></td><td>32,700</td><td>0.00</td><td>11,890,996</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10452">임창민</a></td><td>20,000</td><td>1.51</td><td>13,278</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10894">류지혁</a></td><td>20,000</td><td>0.34</td><td>58,607</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10527">이승현</a></td><td>17,000</td><td>0.62</td><td>27,425</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10871">김태훈</a></td><td>17,000</td><td>0.81</td><td>20,971</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14618">김지찬</a></td><td>16,000</td><td>4.59</td><td>3,485</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13156">최채흥</a></td><td>15,000</td><td>-0.07</td><td>-217,492</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15034">이재현</a></td><td>14,000</td><td>4.27</td><td>3,282</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14867">김현준</a></td><td>14,000</td><td>0.04</td><td>396,434</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12934">최지광</a></td><td>14,000</td><td>1.35</td><td>10,404</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10685">김대우</a></td><td>10,000</td><td>0.09</td><td>116,914</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12936">김성윤</a></td><td>10,000</td><td>0.09</td><td>114,787</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11255">강한울</a></td><td>10,000</td><td>-0.32</td><td>-30,994</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10851">최성훈</a></td><td>10,000</td><td>0.03</td><td>294,346</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10730">양현</a></td><td>9,000</td><td>-0.03</td><td>-268,540</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13244">이재익</a></td><td>8,200</td><td>-0.32</td><td>-25,416</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12548">김동엽</a></td><td>8,000</td><td>-0.23</td><td>-34,732</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13162">김윤수</a></td><td>7,000</td><td>-0.14</td><td>-50,854</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11404">장필준</a></td><td>7,000</td><td>-0.01</td><td>-580,359</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14798">이승현</a></td><td>7,000</td><td>2.22</td><td>3,154</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11344">김재성</a></td><td>7,000</td><td>-0.23</td><td>-30,485</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11169">이상민</a></td><td>6,500</td><td>0.72</td><td>8,977</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11422">전병우</a></td><td>6,000</td><td>0.46</td><td>13,079</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13242">홍정우</a></td><td>6,000</td><td>-0.03</td><td>-173,429</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10640">김헌곤</a></td><td>6,000</td><td>1.59</td><td>3,781</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12562">이성규</a></td><td>6,000</td><td>1.86</td><td>3,233</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12988">안주형</a></td><td>5,200</td><td>-0.61</td><td>-8,499</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10137">송은범</a></td><td>5,000</td><td>0.34</td><td>14,521</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16162">디아즈</a></td><td>5,000</td><td>0.80</td><td>6,268</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14115">김도환</a></td><td>5,000</td><td>-0.11</td><td>-47,156</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12530">최충연</a></td><td>4,700</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11266">김민수</a></td><td>4,600</td><td>0.08</td><td>55,703</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14863">김동진</a></td><td>4,500</td><td>-0.15</td><td>-29,034</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11151">이민호</a></td><td>4,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14616">이승민</a></td><td>4,100</td><td>-0.46</td><td>-8,960</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14615">황동재</a></td><td>4,100</td><td>0.92</td><td>4,471</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11336">김태훈</a></td><td>4,100</td><td>-0.02</td><td>-247,030</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13152">최하늘</a></td><td>4,100</td><td>0.05</td><td>77,956</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13164">공민규</a></td><td>4,100</td><td>-0.22</td><td>-18,498</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14117">이병헌</a></td><td>4,000</td><td>0.18</td><td>22,023</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15035">김영웅</a></td><td>3,800</td><td>3.23</td><td>1,177</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12932">김시현</a></td><td>3,700</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14116">양우현</a></td><td>3,700</td><td>-0.13</td><td>-28,450</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13161">윤정빈</a></td><td>3,700</td><td>1.74</td><td>2,126</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15503">류승민</a></td><td>3,500</td><td>0.13</td><td>27,229</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14800">홍무원</a></td><td>3,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14864">홍승원</a></td><td>3,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15039">김서준</a></td><td>3,400</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13158">김태우</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14801">오현석</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15043">장재혁</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14664">한연욱</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14614">홍원표</a></td><td>3,300</td><td>0.03</td><td>130,454</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15496">이호성</a></td><td>3,200</td><td>-0.17</td><td>-18,415</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15499">김재상</a></td><td>3,200</td><td>0.01</td><td>628,099</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14698">정진수</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15497">박권후</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15504">김민호</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15506">박장민</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15874">김동현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15875">양도근</a></td><td>3,000</td><td>0.02</td><td>188,861</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15882">김대호</a></td><td>3,000</td><td>-0.10</td><td>-30,999</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15873">유병선</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14802">주한울</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14866">이창용</a></td><td>3,000</td><td>-0.19</td><td>-16,055</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15036">김재혁</a></td><td>3,000</td><td>-0.22</td><td>-13,581</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14865">김세민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15872">김재형</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15871">이재호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15870">이현준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15869">신경민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15868">김호진</a></td><td>3,000</td><td>-0.26</td><td>-11,618</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15867">김성경</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15866">정민성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15865">박준용</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15864">육선엽</a></td><td>3,000</td><td>0.06</td><td>53,207</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15507">박진우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15505">박시원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15498">서현원</a></td><td>3,000</td><td>-</td><td>-</td></tr>							</tbody>
						</table>""")

In [ ]:
team_tables.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=15530">에레디아</a></td><td>115,000</td><td>4.89</td><td>23,509</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10131">박종훈</a></td><td>110,000</td><td>0.29</td><td>373,407</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10106">최정</a></td><td>100,000</td><td>4.68</td><td>21,383</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10126">김광현</a></td><td>100,000</td><td>3.91</td><td>25,582</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10815">한유섬</a></td><td>90,000</td><td>-0.20</td><td>-439,861</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15644">엘리아스</a></td><td>65,000</td><td>4.36</td><td>14,904</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16141">더거</a></td><td>65,000</td><td>-0.52</td><td>-124,987</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16146">앤더슨</a></td><td>57,000</td><td>4.13</td><td>13,786</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10784">서진용</a></td><td>45,000</td><td>-0.12</td><td>-374,931</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10203">노경은</a></td><td>35,000</td><td>3.10</td><td>11,275</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12922">박성한</a></td><td>30,000</td><td>4.02</td><td>7,462</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14587">최지훈</a></td><td>25,000</td><td>2.05</td><td>12,167</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10249">오태곤</a></td><td>25,000</td><td>1.43</td><td>17,510</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11373">김택형</a></td><td>20,500</td><td>-0.03</td><td>-795,943</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10636">김성현</a></td><td>20,000</td><td>-0.69</td><td>-29,017</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10312">이지영</a></td><td>20,000</td><td>2.01</td><td>9,951</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10783">문승원</a></td><td>18,000</td><td>1.07</td><td>16,888</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10124">고효준</a></td><td>15,300</td><td>-0.05</td><td>-304,187</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10707">김민식</a></td><td>15,000</td><td>-0.16</td><td>-93,228</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13126">최민준</a></td><td>14,400</td><td>-0.35</td><td>-41,178</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14581">오원석</a></td><td>14,000</td><td>3.03</td><td>4,622</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14804">장지훈</a></td><td>13,000</td><td>-0.07</td><td>-194,203</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14147">하재훈</a></td><td>10,000</td><td>-1.59</td><td>-6,309</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11148">강진성</a></td><td>8,500</td><td>-0.04</td><td>-196,132</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14699">전의산</a></td><td>8,000</td><td>-1.38</td><td>-5,800</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15461">이로운</a></td><td>7,400</td><td>0.36</td><td>20,420</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14806">조형우</a></td><td>6,300</td><td>-0.13</td><td>-46,892</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11242">이건욱</a></td><td>6,100</td><td>-0.39</td><td>-15,776</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11236">박민호</a></td><td>6,000</td><td>0.17</td><td>34,772</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12622">김찬형</a></td><td>5,000</td><td>-0.26</td><td>-18,964</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12541">신범수</a></td><td>5,000</td><td>-0.03</td><td>-169,613</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14145">백승건</a></td><td>4,600</td><td>-0.06</td><td>-76,710</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15462">송영진</a></td><td>4,500</td><td>1.33</td><td>3,383</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13128">최준우</a></td><td>4,500</td><td>0.23</td><td>19,938</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12613">안상현</a></td><td>4,000</td><td>-0.61</td><td>-6,545</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11246">박대온</a></td><td>4,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14151">최경모</a></td><td>3,700</td><td>-0.08</td><td>-46,643</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13129">전경원</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14152">서상준</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13228">한두솔</a></td><td>3,200</td><td>0.84</td><td>3,820</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15024">신헌민</a></td><td>3,200</td><td>-0.07</td><td>-45,619</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13195">최상민</a></td><td>3,200</td><td>0.15</td><td>21,232</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13194">이정범</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15030">김태윤</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11321">정성곤</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15028">이기순</a></td><td>3,100</td><td>0.47</td><td>6,635</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14146">김창평</a></td><td>3,100</td><td>-0.07</td><td>-46,732</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14586">류효승</a></td><td>3,100</td><td>-0.05</td><td>-60,836</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14584">현원회</a></td><td>3,000</td><td>-0.02</td><td>-183,183</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16048">변건우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16047">김규민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16046">윤성보</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16045">백준서</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16044">박성빈</a></td><td>3,000</td><td>0.11</td><td>27,432</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16043">정현승</a></td><td>3,000</td><td>-0.24</td><td>-12,319</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16042">정준재</a></td><td>3,000</td><td>2.01</td><td>1,493</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16041">최현석</a></td><td>3,000</td><td>-0.02</td><td>-139,212</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16040">박기호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16039">이승민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16038">박지환</a></td><td>3,000</td><td>-0.26</td><td>-11,519</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11351">최민창</a></td><td>3,000</td><td>-0.03</td><td>-105,694</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14585">김성민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12571">정동윤</a></td><td>3,000</td><td>0.05</td><td>54,717</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16140">김지현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16139">허진</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14803">김건우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14149">허민혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14805">조병현</a></td><td>3,000</td><td>2.50</td><td>1,201</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14148">최수호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14807">고명준</a></td><td>3,000</td><td>0.30</td><td>10,078</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14153">채현우</a></td><td>3,000</td><td>0.00</td><td>-2,247,444</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14888">추신수</a></td><td>3,000</td><td>0.94</td><td>3,179</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14862">박정빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15033">최유빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14687">박시후</a></td><td>3,000</td><td>0.11</td><td>28,325</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12909">이찬혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15469">이승훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15468">류현곤</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15467">김민준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15466">박세직</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15464">안현서</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15463">김정민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15470">김건이</a></td><td>3,000</td><td>-</td><td>-</td></tr>							</tbody>
						</table>""")

In [ ]:
team_tables.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=11137">박민우</a></td><td>100,000</td><td>5.55</td><td>18,022</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10189">박건우</a></td><td>80,000</td><td>2.94</td><td>27,245</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10891">박세혁</a></td><td>70,000</td><td>0.59</td><td>118,283</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16066">데이비슨</a></td><td>56,000</td><td>4.27</td><td>13,108</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16064">카스타노</a></td><td>52,000</td><td>1.83</td><td>28,476</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16065">하트</a></td><td>50,000</td><td>6.22</td><td>8,035</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10261">손아섭</a></td><td>50,000</td><td>1.03</td><td>48,314</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10217">이용찬</a></td><td>40,000</td><td>-1.02</td><td>-39,294</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13088">김영규</a></td><td>22,500</td><td>1.48</td><td>15,219</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10220">이재학</a></td><td>20,000</td><td>1.16</td><td>17,183</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13085">신민혁</a></td><td>18,000</td><td>2.76</td><td>6,531</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11355">류진욱</a></td><td>16,500</td><td>-0.13</td><td>-122,398</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14765">김주원</a></td><td>16,000</td><td>5.43</td><td>2,945</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11172">권희동</a></td><td>15,000</td><td>4.11</td><td>3,647</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11168">임정호</a></td><td>13,500</td><td>0.59</td><td>22,735</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14155">송명기</a></td><td>13,500</td><td>-0.16</td><td>-83,813</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14220">서호철</a></td><td>12,000</td><td>2.00</td><td>6,001</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13080">김시훈</a></td><td>11,000</td><td>1.91</td><td>5,771</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14785">김휘집</a></td><td>11,000</td><td>2.42</td><td>4,548</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13940">요키시</a></td><td>10,000</td><td>0.08</td><td>131,961</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11153">김성욱</a></td><td>9,500</td><td>-0.37</td><td>-25,964</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10720">심창민</a></td><td>8,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12565">최성영</a></td><td>8,300</td><td>-0.03</td><td>-322,111</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12560">도태훈</a></td><td>8,000</td><td>0.48</td><td>16,655</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13082">오영수</a></td><td>7,200</td><td>0.23</td><td>30,943</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11329">안중열</a></td><td>7,100</td><td>0.33</td><td>21,755</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14763">이용준</a></td><td>6,700</td><td>0.04</td><td>185,028</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14221">최정원</a></td><td>6,600</td><td>0.82</td><td>8,096</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11135">윤형준</a></td><td>6,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11248">배재환</a></td><td>6,300</td><td>-0.11</td><td>-55,843</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14747">김재열</a></td><td>6,000</td><td>1.98</td><td>3,034</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12897">김진호</a></td><td>6,000</td><td>0.00</td><td>11,747,269</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13081">김형준</a></td><td>5,800</td><td>0.50</td><td>11,489</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13261">천재환</a></td><td>5,000</td><td>0.31</td><td>16,080</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15455">이준호</a></td><td>4,500</td><td>-0.68</td><td>-6,645</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14659">한재환</a></td><td>4,000</td><td>-0.08</td><td>-50,935</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12898">김태현</a></td><td>4,000</td><td>-0.13</td><td>-31,557</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13250">한석현</a></td><td>3,900</td><td>-0.47</td><td>-8,230</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14716">김한별</a></td><td>3,800</td><td>-0.23</td><td>-16,588</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11387">채원후</a></td><td>3,500</td><td>-0.03</td><td>-101,895</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14172">송승환</a></td><td>3,500</td><td>0.13</td><td>26,594</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14764">한재승</a></td><td>3,400</td><td>0.59</td><td>5,789</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14156">전사민</a></td><td>3,400</td><td>-0.30</td><td>-11,353</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14171">전루건</a></td><td>3,200</td><td>-0.14</td><td>-22,406</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14661">박영빈</a></td><td>3,200</td><td>-0.12</td><td>-27,206</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11360">이우석</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12900">소이현</a></td><td>3,200</td><td>-0.06</td><td>-53,577</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12903">김수윤</a></td><td>3,200</td><td>-0.10</td><td>-31,236</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13087">최보성</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13227">문상인</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14877">조현진</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15451">박한결</a></td><td>3,100</td><td>-0.31</td><td>-9,935</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14219">박주찬</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16063">김준원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16062">김재민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16054">김민균</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16061">고승완</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16060">조현민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16055">홍유원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16059">원종해</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16058">김세훈</a></td><td>3,000</td><td>-0.11</td><td>-27,852</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16057">손주환</a></td><td>3,000</td><td>-0.04</td><td>-73,787</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16056">최우석</a></td><td>3,000</td><td>0.12</td><td>25,298</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12621">최우재</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16053">임상현</a></td><td>3,000</td><td>-0.02</td><td>-121,956</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16052">김휘건</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16051">박인우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16050">김태호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16049">김민규</a></td><td>3,000</td><td>-0.08</td><td>-39,480</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12574">서의태</a></td><td>3,000</td><td>-0.06</td><td>-52,157</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14598">안인산</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14597">박시원</a></td><td>3,000</td><td>-0.27</td><td>-11,284</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14594">임형원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14650">박지한</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15117">이현우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15112">박동수</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15453">목지훈</a></td><td>3,000</td><td>-0.21</td><td>-14,190</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15452">신용석</a></td><td>3,000</td><td>-0.10</td><td>-30,908</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15450">신영우</a></td><td>3,000</td><td>-0.13</td><td>-22,821</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13175">박주현</a></td><td>3,000</td><td>0.03</td><td>109,982</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15456">신성호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15622">김택우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15458">서동욱</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14222">김범준</a></td><td>3,000</td><td>-0.15</td><td>-19,963</td></tr>							</tbody>
						</table>""")

In [ ]:
team_tables.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=10643">김재환</a></td><td>150,000</td><td>3.07</td><td>48,839</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13941">알칸타라</a></td><td>80,000</td><td>1.24</td><td>64,510</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15153">브랜든</a></td><td>75,000</td><td>2.32</td><td>32,269</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10184">허경민</a></td><td>60,000</td><td>3.66</td><td>16,390</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10195">정수빈</a></td><td>60,000</td><td>3.13</td><td>19,197</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15000">라모스</a></td><td>55,000</td><td>2.37</td><td>23,179</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10165">양의지</a></td><td>50,000</td><td>3.38</td><td>14,814</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16158">제러드</a></td><td>30,000</td><td>1.52</td><td>19,800</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11213">양석환</a></td><td>30,000</td><td>2.31</td><td>13,009</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10696">홍건희</a></td><td>30,000</td><td>1.24</td><td>24,103</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10174">김재호</a></td><td>30,000</td><td>0.56</td><td>53,904</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11087">강승호</a></td><td>25,500</td><td>4.39</td><td>5,809</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12852">최원준</a></td><td>25,000</td><td>1.12</td><td>22,333</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16155">발라조빅</a></td><td>25,000</td><td>1.35</td><td>18,513</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12847">김명신</a></td><td>22,500</td><td>-0.89</td><td>-25,412</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13061">곽빈</a></td><td>21,000</td><td>4.65</td><td>4,518</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13071">정철원</a></td><td>16,500</td><td>-0.20</td><td>-82,583</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10690">김강률</a></td><td>15,000</td><td>1.64</td><td>9,119</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12850">박치국</a></td><td>13,000</td><td>-0.15</td><td>-86,277</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14770">최승용</a></td><td>10,200</td><td>0.11</td><td>91,504</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12568">이영하</a></td><td>10,000</td><td>0.36</td><td>27,768</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12524">조수행</a></td><td>9,500</td><td>1.83</td><td>5,194</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11098">김인태</a></td><td>9,000</td><td>-0.40</td><td>-22,487</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11198">박계범</a></td><td>8,500</td><td>-0.47</td><td>-18,168</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12894">이유찬</a></td><td>8,500</td><td>0.73</td><td>11,604</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12522">박준영</a></td><td>7,000</td><td>1.58</td><td>4,436</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11097">장승현</a></td><td>6,000</td><td>-0.07</td><td>-83,501</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14769">김동주</a></td><td>5,500</td><td>-0.31</td><td>-17,809</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12678">이승진</a></td><td>5,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11300">박정수</a></td><td>5,500</td><td>0.06</td><td>87,154</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11328">안승한</a></td><td>5,500</td><td>-0.01</td><td>-514,952</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13072">김민규</a></td><td>5,000</td><td>0.66</td><td>7,629</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14738">양찬열</a></td><td>4,000</td><td>0.09</td><td>42,199</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12549">김기연</a></td><td>4,000</td><td>1.49</td><td>2,689</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12970">김민혁</a></td><td>3,800</td><td>0.22</td><td>17,536</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14170">김대한</a></td><td>3,700</td><td>-0.51</td><td>-7,286</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14736">박지훈</a></td><td>3,600</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15099">이병헌</a></td><td>3,600</td><td>1.75</td><td>2,060</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16148">시라카와</a></td><td>3,600</td><td>0.76</td><td>4,715</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13070">박신지</a></td><td>3,500</td><td>0.15</td><td>22,678</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13073">전민재</a></td><td>3,400</td><td>0.32</td><td>10,606</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14175">김태근</a></td><td>3,400</td><td>-0.72</td><td>-4,729</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12523">서예일</a></td><td>3,400</td><td>-0.01</td><td>-437,733</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15127">최지강</a></td><td>3,400</td><td>1.01</td><td>3,377</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14173">이교훈</a></td><td>3,300</td><td>-0.40</td><td>-8,167</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11491">박소준</a></td><td>3,300</td><td>-0.07</td><td>-47,751</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12606">홍성호</a></td><td>3,300</td><td>0.10</td><td>31,759</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13268">김호준</a></td><td>3,100</td><td>-0.22</td><td>-14,260</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15514">백승우</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13124">김정우</a></td><td>3,100</td><td>-0.01</td><td>-222,415</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13079">권민석</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14732">조제영</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14737">오명진</a></td><td>3,100</td><td>0.01</td><td>261,758</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14768">김도윤</a></td><td>3,100</td><td>0.00</td><td>-2,232,770</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14574">최세창</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12848">문원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16076">류현준</a></td><td>3,000</td><td>0.15</td><td>19,631</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16075">김태완</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16074">손율기</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16073">김무빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16072">전다민</a></td><td>3,000</td><td>0.35</td><td>8,557</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16071">박지호</a></td><td>3,000</td><td>0.11</td><td>27,911</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16070">강태완</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16069">임종성</a></td><td>3,000</td><td>-0.02</td><td>-130,003</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16068">여동건</a></td><td>3,000</td><td>-0.02</td><td>-186,306</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16067">김택연</a></td><td>3,000</td><td>2.97</td><td>1,010</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14652">전형근</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16142">장원호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15106">강동형</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15104">윤태호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15101">이원재</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15100">김동준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14174">이민혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14840">양현진</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13665">권휘</a></td><td>3,000</td><td>-0.05</td><td>-55,129</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14836">이상연</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14573">제환유</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14572">이주엽</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15517">남율</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15516">김문수</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15515">박민준</a></td><td>3,000</td><td>-0.13</td><td>-22,413</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14570">장규빈</a></td><td>3,000</td><td>0.00</td><td>-1,208,352</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14773">강현구</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14733">최종인</a></td><td>3,000</td><td>0.18</td><td>17,066</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15508">최준호</a></td><td>3,000</td><td>1.21</td><td>2,476</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15509">김유성</a></td><td>3,000</td><td>0.21</td><td>14,316</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15511">임서준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15512">윤준호</a></td><td>3,000</td><td>-0.07</td><td>-41,257</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15513">한충희</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13074">배창현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10641">니퍼트</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15129">이민석</a></td><td>-</td><td>-</td><td>-</td></tr>							</tbody>
						</table>""")

In [ ]:
team_tables.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=15531">후라도</a></td><td>120,000</td><td>6.13</td><td>19,581</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12516">이형종</a></td><td>68,000</td><td>0.66</td><td>103,358</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12905">김혜성</a></td><td>65,000</td><td>6.72</td><td>9,677</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10182">최주환</a></td><td>65,000</td><td>0.35</td><td>184,816</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16138">헤이수스</a></td><td>60,000</td><td>4.65</td><td>12,907</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15652">도슨</a></td><td>55,000</td><td>3.42</td><td>16,102</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11161">원종현</a></td><td>50,000</td><td>0.09</td><td>563,411</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10180">이원석</a></td><td>40,000</td><td>-0.47</td><td>-84,662</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11126">조상우</a></td><td>34,000</td><td>0.65</td><td>52,414</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10035">이용규</a></td><td>20,000</td><td>1.54</td><td>12,962</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10533">정찬헌</a></td><td>20,000</td><td>-0.01</td><td>-2,847,960</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12858">김재웅</a></td><td>19,000</td><td>0.38</td><td>49,496</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11376">송성문</a></td><td>13,000</td><td>6.87</td><td>1,892</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11244">김태진</a></td><td>11,000</td><td>0.89</td><td>12,361</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12918">김성민</a></td><td>9,000</td><td>0.48</td><td>18,900</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11222">하영민</a></td><td>8,000</td><td>2.95</td><td>2,711</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10437">문성현</a></td><td>7,500</td><td>-0.12</td><td>-64,581</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11225">임지열</a></td><td>7,200</td><td>-0.74</td><td>-9,765</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13092">김선기</a></td><td>7,000</td><td>0.10</td><td>67,435</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11226">임병욱</a></td><td>7,000</td><td>0.02</td><td>412,726</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14591">이주형</a></td><td>6,600</td><td>2.51</td><td>2,634</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14674">김동혁</a></td><td>6,000</td><td>-0.52</td><td>-11,522</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15073">이명종</a></td><td>6,000</td><td>-0.17</td><td>-36,311</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10870">김재현</a></td><td>5,500</td><td>0.10</td><td>57,006</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12503">김웅빈</a></td><td>5,000</td><td>-0.40</td><td>-12,581</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13223">변상권</a></td><td>4,800</td><td>0.24</td><td>19,811</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13096">김수환</a></td><td>4,700</td><td>-0.10</td><td>-48,994</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12989">박승주</a></td><td>4,500</td><td>0.02</td><td>281,711</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14214">김주형</a></td><td>4,500</td><td>-0.08</td><td>-58,698</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15071">윤석원</a></td><td>4,300</td><td>-0.31</td><td>-14,096</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14695">신준우</a></td><td>4,200</td><td>0.00</td><td>5,235,680</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14784">장재영</a></td><td>4,000</td><td>-0.41</td><td>-9,657</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12860">오석주</a></td><td>4,000</td><td>-0.32</td><td>-12,697</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15132">박수종</a></td><td>4,000</td><td>0.25</td><td>15,819</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15068">박찬혁</a></td><td>4,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15473">김동헌</a></td><td>4,000</td><td>-0.12</td><td>-34,516</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14131">윤정현</a></td><td>4,000</td><td>-0.01</td><td>-316,216</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14132">조영건</a></td><td>4,000</td><td>-0.52</td><td>-7,628</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14848">김준형</a></td><td>3,700</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14580">박주홍</a></td><td>3,600</td><td>-0.24</td><td>-14,893</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14851">김시앙</a></td><td>3,600</td><td>-0.05</td><td>-76,364</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14133">주성원</a></td><td>3,500</td><td>0.01</td><td>375,377</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14480">김인범</a></td><td>3,300</td><td>0.68</td><td>4,864</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15474">오상원</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14577">김병휘</a></td><td>3,300</td><td>-0.34</td><td>-9,846</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15472">김건희</a></td><td>3,200</td><td>0.60</td><td>5,377</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15067">주승우</a></td><td>3,200</td><td>0.74</td><td>4,312</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14576">이종민</a></td><td>3,200</td><td>-0.15</td><td>-21,098</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15485">김동규</a></td><td>3,100</td><td>-0.01</td><td>-234,222</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13125">조성훈</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15476">이승원</a></td><td>3,100</td><td>-0.96</td><td>-3,239</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15477">송재선</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12854">양지율</a></td><td>3,000</td><td>0.07</td><td>40,694</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16134">박승호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16133">박범준</a></td><td>3,000</td><td>-0.11</td><td>-28,239</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16132">박채울</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16131">김지성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16130">송지후</a></td><td>3,000</td><td>0.04</td><td>73,695</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16129">김주훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16128">고영우</a></td><td>3,000</td><td>-0.59</td><td>-5,117</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16127">김연주</a></td><td>3,000</td><td>-0.13</td><td>-22,558</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16126">이우현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16125">손현기</a></td><td>3,000</td><td>-0.10</td><td>-29,484</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16124">이재상</a></td><td>3,000</td><td>-1.20</td><td>-2,497</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16123">김윤하</a></td><td>3,000</td><td>0.45</td><td>6,688</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16122">전준표</a></td><td>3,000</td><td>-0.30</td><td>-10,074</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16135">심휘윤</a></td><td>3,000</td><td>-0.01</td><td>-273,154</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16136">원성준</a></td><td>3,000</td><td>-0.25</td><td>-11,991</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15027">노운현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15072">주승빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14681">김동욱</a></td><td>3,000</td><td>0.11</td><td>26,713</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15482">안겸</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15481">변헌성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15480">이호열</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15479">박성빈</a></td><td>3,000</td><td>-0.03</td><td>-101,587</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15478">우승원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14211">박준형</a></td><td>3,000</td><td>-0.25</td><td>-12,108</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15475">박윤성</a></td><td>3,000</td><td>0.04</td><td>72,014</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15483">서유신</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14212">이명기</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16137">신효수</a></td><td>1,500</td><td>-</td><td>-</td></tr>							</tbody>
						</table>""")

In [ ]:
team_names

['한화 이글스',
 'LG 트윈스',
 '롯데 자이언츠',
 'KIA 타이거즈',
 'KT 위즈',
 '삼성 라이온즈',
 'SSG 랜더스',
 'NC 다이노스',
 '두산 베어스',
 '키움 히어로즈']

In [ ]:
earning = pd.DataFrame()
for i in range(len(team_tables)):
    name = team_names[i]
    team = team_tables[i]
    print(name)
    df, pids = get_team_stats_from_markup(StringIO(str(team)))
    df['팀'] = name
    df['pid'] = pids[1:]
    print(df.shape)
    print(len(pids))
    earning = pd.concat([earning, df])
    display(earning.tail())

한화 이글스
(79, 6)
80

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

     선수 연봉(만원)   WAR  WAR당 연봉       팀    pid
74  한경빈   3000  0.00  -629368  한화 이글스  15633
75  성지훈   3000     -        -  한화 이글스  15631
76  김승일   3000  0.13    23229  한화 이글스  14711
77  송호정      -     -        -  한화 이글스  14812
78  신우재      -     -        -  한화 이글스  16011

LG 트윈스
(82, 6)
83

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

     선수 연봉(만원)    WAR WAR당 연봉       팀    pid
77  김주온   3000  -0.11  -27713  LG 트윈스  13057
78  함창건   3000  -0.19  -15608  LG 트윈스  14680
79   강민   3000      -       -  LG 트윈스  14660
80  김수인   3000  -0.15  -20407  LG 트윈스  14675
81  허용주   3000      -       -  LG 트윈스  15491

롯데 자이언츠
(82, 6)
83

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

     선수 연봉(만원)   WAR WAR당 연봉        팀    pid
77  배세종   3000     -       -  롯데 자이언츠  16100
78  하혜성   3000     -       -  롯데 자이언츠  15050
79  이병준   3000     -       -  롯데 자이언츠  14817
80  최우인   3000     -       -  롯데 자이언츠  14818
81  이인한   3000  0.12   24573  롯데 자이언츠  14690

KIA 타이거즈
(91, 6)
92

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

     선수 연봉(만원) WAR WAR당 연봉         팀    pid
86  장시현   3000   -       -  KIA 타이거즈  14824
87  이영재   3000   -       -  KIA 타이거즈  14826
88  강이준   3000   -       -  KIA 타이거즈  12866
89  김민수   3000   -       -  KIA 타이거즈  14183
90  이준범      -   -       -  KIA 타이거즈  14823

KT 위즈

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(92, 6)
93

     선수 연봉(만원)    WAR WAR당 연봉      팀    pid
87  성재헌   3000  -0.07  -45935  KT 위즈  14667
88  조용근   3000      -       -  KT 위즈  14670
89  신범준   3000      -       -  KT 위즈  14774
90  김철호   3000      -       -  KT 위즈  13083
91  김성균   3000      -       -  KT 위즈  14723

삼성 라이온즈

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(89, 6)
90

     선수 연봉(만원)   WAR WAR당 연봉        팀    pid
84  박준용   3000     -       -  삼성 라이온즈  15865
85  육선엽   3000  0.06   53207  삼성 라이온즈  15864
86  박진우   3000     -       -  삼성 라이온즈  15507
87  박시원   3000     -       -  삼성 라이온즈  15505
88  서현원   3000     -       -  삼성 라이온즈  15498

SSG 랜더스
(83, 6)
84

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

     선수 연봉(만원) WAR WAR당 연봉        팀    pid
78  김민준   3000   -       -  SSG 랜더스  15467
79  박세직   3000   -       -  SSG 랜더스  15466
80  안현서   3000   -       -  SSG 랜더스  15464
81  김정민   3000   -       -  SSG 랜더스  15463
82  김건이   3000   -       -  SSG 랜더스  15470

NC 다이노스

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(84, 6)
85

     선수 연봉(만원)    WAR WAR당 연봉        팀    pid
79  박주현   3000   0.03  109982  NC 다이노스  13175
80  신성호   3000      -       -  NC 다이노스  15456
81  김택우   3000      -       -  NC 다이노스  15622
82  서동욱   3000      -       -  NC 다이노스  15458
83  김범준   3000  -0.15  -19963  NC 다이노스  14222

두산 베어스

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(92, 6)
93

     선수 연봉(만원)    WAR WAR당 연봉       팀    pid
87  윤준호   3000  -0.07  -41257  두산 베어스  15512
88  한충희   3000      -       -  두산 베어스  15513
89  배창현   3000      -       -  두산 베어스  13074
90  니퍼트      -      -       -  두산 베어스  10641
91  이민석      -      -       -  두산 베어스  15129

키움 히어로즈
(81, 6)
82

/tmp/ipython-input-22-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

     선수 연봉(만원)    WAR WAR당 연봉        팀    pid
76  박준형   3000  -0.25  -12108  키움 히어로즈  14211
77  박윤성   3000   0.04   72014  키움 히어로즈  15475
78  서유신   3000      -       -  키움 히어로즈  15483
79  이명기   3000      -       -  키움 히어로즈  14212
80  신효수   1500      -       -  키움 히어로즈  16137

In [ ]:
earning.isna().sum()

선수         0
연봉(만원)     0
WAR        0
WAR당 연봉    0
팀          0
pid        0
dtype: int64

In [ ]:
earning.to_csv('2024_연봉_statiz.csv', index=False)

In [4]:
team_tables = []

In [21]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14125">노시환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">6.53</td><td>131</td><td>6.17</td><td>0.35</td><td>595</td><td>590</td><td>514</td><td>85</td><td>153</td><td>30</td><td>1</td><td>31</td><td>278</td><td>101</td><td>2</td><td>1</td><td>74</td><td>4</td><td>5</td><td>118</td><td>13</td><td>0</td><td>3</td><td style="">0.298</td><td>0.388</td><td>0.541</td><td>0.929</td><td>0.188</td><td>160.0</td><td style="background-color:#F3F3F3; font-weight:bold;">6.53</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10170">최재훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.23</td><td>125</td><td>3.03</td><td>0.20</td><td>417</td><td>407</td><td>327</td><td>23</td><td>81</td><td>12</td><td>0</td><td>1</td><td>96</td><td>33</td><td>1</td><td>1</td><td>56</td><td>23</td><td>1</td><td>48</td><td>9</td><td>9</td><td>2</td><td style="">0.248</td><td>0.392</td><td>0.294</td><td>0.686</td><td>0.131</td><td>111.6</td><td style="background-color:#F3F3F3; font-weight:bold;">3.23</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12539">이진영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.44</td><td>121</td><td>2.06</td><td>0.38</td><td>422</td><td>418</td><td>358</td><td>57</td><td>89</td><td>22</td><td>0</td><td>10</td><td>141</td><td>50</td><td>5</td><td>0</td><td>53</td><td>2</td><td>0</td><td>127</td><td>4</td><td>4</td><td>5</td><td style="">0.249</td><td>0.344</td><td>0.394</td><td>0.738</td><td>0.129</td><td>109.2</td><td style="background-color:#F3F3F3; font-weight:bold;">2.44</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11215">채은성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.79</td><td>137</td><td>1.95</td><td>-0.16</td><td>596</td><td>593</td><td>521</td><td>71</td><td>137</td><td>17</td><td>0</td><td>23</td><td>223</td><td>84</td><td>0</td><td>0</td><td>52</td><td>20</td><td>8</td><td>102</td><td>16</td><td>0</td><td>3</td><td style="">0.263</td><td>0.351</td><td>0.428</td><td>0.779</td><td>0.138</td><td>117.0</td><td style="background-color:#F3F3F3; font-weight:bold;">1.79</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11414">이도윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.64</td><td>106</td><td>0.91</td><td>0.73</td><td>346</td><td>331</td><td>309</td><td>36</td><td>78</td><td>13</td><td>2</td><td>1</td><td>98</td><td>13</td><td>11</td><td>3</td><td>18</td><td>4</td><td>1</td><td>55</td><td>6</td><td>15</td><td>0</td><td style="">0.252</td><td>0.302</td><td>0.317</td><td>0.619</td><td>0.082</td><td>70.0</td><td style="background-color:#F3F3F3; font-weight:bold;">1.64</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15422">문현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.38</td><td>137</td><td>1.49</td><td>-0.11</td><td>481</td><td>470</td><td>428</td><td>47</td><td>114</td><td>22</td><td>2</td><td>5</td><td>155</td><td>49</td><td>5</td><td>1</td><td>33</td><td>6</td><td>2</td><td>84</td><td>7</td><td>9</td><td>5</td><td style="">0.266</td><td>0.324</td><td>0.362</td><td>0.686</td><td>0.106</td><td>89.6</td><td style="background-color:#F3F3F3; font-weight:bold;">1.38</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12585">김태연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.16</td><td>91</td><td>0.60</td><td>0.56</td><td>280</td><td>278</td><td>245</td><td>25</td><td>64</td><td>13</td><td>0</td><td>4</td><td>89</td><td>25</td><td>5</td><td>1</td><td>27</td><td>3</td><td>1</td><td>59</td><td>3</td><td>1</td><td>4</td><td style="">0.261</td><td>0.337</td><td>0.363</td><td>0.700</td><td>0.113</td><td>96.6</td><td style="background-color:#F3F3F3; font-weight:bold;">1.16</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14707">최인호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.11</td><td>41</td><td>0.82</td><td>0.28</td><td>148</td><td>146</td><td>131</td><td>23</td><td>39</td><td>5</td><td>3</td><td>2</td><td>56</td><td>11</td><td>1</td><td>0</td><td>10</td><td>4</td><td>0</td><td>22</td><td>2</td><td>2</td><td>1</td><td style="">0.298</td><td>0.363</td><td>0.427</td><td>0.790</td><td>0.146</td><td>125.0</td><td style="background-color:#F3F3F3; font-weight:bold;">1.11</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13137">정은원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.74</td><td>122</td><td>0.83</td><td>-0.09</td><td>459</td><td>453</td><td>388</td><td>50</td><td>86</td><td>12</td><td>0</td><td>2</td><td>104</td><td>30</td><td>6</td><td>3</td><td>62</td><td>3</td><td>1</td><td>73</td><td>4</td><td>5</td><td>1</td><td style="">0.222</td><td>0.333</td><td>0.268</td><td>0.601</td><td>0.089</td><td>76.1</td><td style="background-color:#F3F3F3; font-weight:bold;">0.74</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15423">이민준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.07</td><td>4</td><td>0.02</td><td>0.05</td><td>2</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.500</td><td>0.000</td><td>0.500</td><td>0.166</td><td>136.1</td><td style="background-color:#F3F3F3; font-weight:bold;">0.07</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12902">이재용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.03</td><td>2</td><td>-0.01</td><td>0.03</td><td>2</td><td>2</td><td>2</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.500</td><td>0.500</td><td>0.500</td><td>1.000</td><td>0.222</td><td>173.2</td><td style="background-color:#F3F3F3; font-weight:bold;">0.03</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14708">강재민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>0</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12871">박상원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>3</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15421">김서현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10156">정우람</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>0</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11110">윤대경</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10609">이태양</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15014">박준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13138">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>81</td><td>-0.18</td><td>0.17</td><td>138</td><td>138</td><td>116</td><td>20</td><td>22</td><td>1</td><td>1</td><td>0</td><td>25</td><td>8</td><td>13</td><td>3</td><td>21</td><td>1</td><td>0</td><td>33</td><td>3</td><td>0</td><td>0</td><td style="">0.190</td><td>0.319</td><td>0.216</td><td>0.535</td><td>0.071</td><td>60.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15141">유상빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>3</td><td>-0.03</td><td>0.02</td><td>8</td><td>8</td><td>6</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.250</td><td>0.000</td><td>0.250</td><td>0.005</td><td>4.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10557">오선진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.04</td><td>90</td><td>0.25</td><td>-0.29</td><td>199</td><td>196</td><td>165</td><td>17</td><td>38</td><td>6</td><td>0</td><td>0</td><td>44</td><td>14</td><td>2</td><td>0</td><td>24</td><td>5</td><td>0</td><td>34</td><td>7</td><td>3</td><td>2</td><td style="">0.230</td><td>0.342</td><td>0.267</td><td>0.609</td><td>0.095</td><td>80.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.04</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11268">노수광</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.08</td><td>30</td><td>-0.08</td><td>0.00</td><td>94</td><td>92</td><td>77</td><td>6</td><td>17</td><td>5</td><td>0</td><td>0</td><td>22</td><td>4</td><td>2</td><td>1</td><td>13</td><td>0</td><td>0</td><td>27</td><td>3</td><td>2</td><td>2</td><td style="">0.221</td><td>0.326</td><td>0.286</td><td>0.612</td><td>0.091</td><td>76.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.08</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11122">장운호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.10</td><td>4</td><td>0.03</td><td>-0.13</td><td>11</td><td>11</td><td>9</td><td>1</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.222</td><td>0.364</td><td>0.222</td><td>0.586</td><td>0.096</td><td>82.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.10</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14880">장지승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.11</td><td>3</td><td>-0.08</td><td>-0.04</td><td>3</td><td>3</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-145.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.11</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12589">김인환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.18</td><td>112</td><td>-0.36</td><td>0.18</td><td>365</td><td>365</td><td>325</td><td>34</td><td>73</td><td>16</td><td>0</td><td>7</td><td>110</td><td>42</td><td>1</td><td>0</td><td>35</td><td>2</td><td>2</td><td>91</td><td>4</td><td>0</td><td>3</td><td style="">0.225</td><td>0.301</td><td>0.338</td><td>0.639</td><td>0.089</td><td>75.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.18</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15139">이상혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.18</td><td>7</td><td>-0.08</td><td>-0.10</td><td>2</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-130.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.18</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11206">이성곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.25</td><td>8</td><td>-0.21</td><td>-0.04</td><td>16</td><td>15</td><td>14</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>3</td><td>0</td><td>1</td><td>0</td><td style="">0.143</td><td>0.200</td><td>0.143</td><td>0.343</td><td>-0.019</td><td>-15.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.25</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14209">김건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.33</td><td>7</td><td>-0.16</td><td>-0.17</td><td>12</td><td>12</td><td>12</td><td>1</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8</td><td>0</td><td>0</td><td>0</td><td style="">0.167</td><td>0.167</td><td>0.167</td><td>0.334</td><td>-0.037</td><td>-31.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.33</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14204">허관회</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.34</td><td>10</td><td>-0.19</td><td>-0.15</td><td>7</td><td>7</td><td>7</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-139.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.34</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12587">박상언</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.35</td><td>86</td><td>-0.34</td><td>-0.01</td><td>161</td><td>158</td><td>145</td><td>13</td><td>29</td><td>5</td><td>1</td><td>1</td><td>39</td><td>13</td><td>1</td><td>2</td><td>10</td><td>1</td><td>0</td><td>38</td><td>6</td><td>3</td><td>2</td><td style="">0.200</td><td>0.253</td><td>0.269</td><td>0.522</td><td>0.045</td><td>37.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.35</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10119">이명기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.37</td><td>14</td><td>-0.39</td><td>0.02</td><td>42</td><td>42</td><td>40</td><td>2</td><td>7</td><td>1</td><td>0</td><td>0</td><td>8</td><td>5</td><td>1</td><td>0</td><td>2</td><td>0</td><td>0</td><td>9</td><td>0</td><td>0</td><td>0</td><td style="">0.175</td><td>0.214</td><td>0.200</td><td>0.414</td><td>0.003</td><td>2.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.37</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10913">하주석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.53</td><td>25</td><td>-0.31</td><td>-0.22</td><td>38</td><td>38</td><td>35</td><td>4</td><td>4</td><td>1</td><td>0</td><td>0</td><td>5</td><td>2</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>10</td><td>0</td><td>0</td><td>0</td><td style="">0.114</td><td>0.184</td><td>0.143</td><td>0.327</td><td>-0.022</td><td>-18.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.53</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14704">박정현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.54</td><td>53</td><td>-0.35</td><td>-0.18</td><td>113</td><td>110</td><td>105</td><td>12</td><td>19</td><td>6</td><td>0</td><td>2</td><td>31</td><td>4</td><td>0</td><td>0</td><td>3</td><td>2</td><td>0</td><td>36</td><td>2</td><td>3</td><td>0</td><td style="">0.181</td><td>0.218</td><td>0.295</td><td>0.513</td><td>0.036</td><td>30.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.54</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15647">윌리엄스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.63</td><td>68</td><td>-0.15</td><td>-0.48</td><td>273</td><td>273</td><td>258</td><td>29</td><td>63</td><td>14</td><td>0</td><td>9</td><td>104</td><td>45</td><td>1</td><td>1</td><td>8</td><td>4</td><td>0</td><td>63</td><td>6</td><td>0</td><td>3</td><td style="">0.244</td><td>0.275</td><td>0.403</td><td>0.678</td><td>0.093</td><td>78.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.63</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14126">유로결</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.63</td><td>27</td><td>-0.65</td><td>0.02</td><td>53</td><td>52</td><td>48</td><td>5</td><td>7</td><td>1</td><td>0</td><td>0</td><td>8</td><td>5</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>10</td><td>3</td><td>1</td><td>2</td><td style="">0.146</td><td>0.173</td><td>0.167</td><td>0.340</td><td>-0.029</td><td>-24.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.63</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12583">장진혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.65</td><td>68</td><td>-0.49</td><td>-0.16</td><td>178</td><td>178</td><td>162</td><td>24</td><td>36</td><td>5</td><td>1</td><td>0</td><td>43</td><td>12</td><td>5</td><td>4</td><td>15</td><td>0</td><td>0</td><td>41</td><td>3</td><td>0</td><td>1</td><td style="">0.222</td><td>0.287</td><td>0.265</td><td>0.552</td><td>0.061</td><td>52.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.65</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13676">권광민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.84</td><td>66</td><td>-0.45</td><td>-0.38</td><td>81</td><td>80</td><td>73</td><td>11</td><td>11</td><td>1</td><td>1</td><td>2</td><td>20</td><td>9</td><td>2</td><td>0</td><td>6</td><td>1</td><td>0</td><td>24</td><td>2</td><td>1</td><td>0</td><td style="">0.151</td><td>0.225</td><td>0.274</td><td>0.499</td><td>0.036</td><td>30.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.84</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15541">오그레디</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.98</td><td>22</td><td>-0.93</td><td>-0.05</td><td>86</td><td>86</td><td>80</td><td>3</td><td>10</td><td>3</td><td>0</td><td>0</td><td>13</td><td>8</td><td>1</td><td>0</td><td>5</td><td>0</td><td>0</td><td>40</td><td>0</td><td>0</td><td>1</td><td style="">0.125</td><td>0.174</td><td>0.163</td><td>0.337</td><td>-0.025</td><td>-20.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.98</td></tr>			</tbody>
		</table>""")

In [22]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12546">홍창기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">6.67</td><td>141</td><td>5.74</td><td>0.93</td><td>643</td><td>638</td><td>524</td><td>109</td><td>174</td><td>35</td><td>2</td><td>1</td><td>216</td><td>65</td><td>23</td><td>23</td><td>88</td><td>22</td><td>3</td><td>83</td><td>6</td><td>3</td><td>6</td><td style="">0.332</td><td>0.444</td><td>0.412</td><td>0.856</td><td>0.183</td><td>161.3</td><td style="background-color:#F3F3F3; font-weight:bold;">6.67</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10475">오지환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.01</td><td>126</td><td>4.66</td><td>0.35</td><td>502</td><td>498</td><td>422</td><td>65</td><td>113</td><td>24</td><td>3</td><td>8</td><td>167</td><td>62</td><td>16</td><td>7</td><td>64</td><td>8</td><td>0</td><td>82</td><td>4</td><td>4</td><td>4</td><td style="">0.268</td><td>0.371</td><td>0.396</td><td>0.767</td><td>0.144</td><td>127.0</td><td style="background-color:#F3F3F3; font-weight:bold;">5.01</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15532">오스틴</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.97</td><td>139</td><td>4.90</td><td>0.07</td><td>583</td><td>583</td><td>520</td><td>87</td><td>163</td><td>29</td><td>4</td><td>23</td><td>269</td><td>95</td><td>7</td><td>3</td><td>53</td><td>3</td><td>2</td><td>75</td><td>11</td><td>0</td><td>7</td><td style="">0.313</td><td>0.376</td><td>0.517</td><td>0.893</td><td>0.175</td><td>153.9</td><td style="background-color:#F3F3F3; font-weight:bold;">4.97</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10387">박동원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.13</td><td>130</td><td>4.02</td><td>0.11</td><td>481</td><td>471</td><td>409</td><td>54</td><td>102</td><td>17</td><td>1</td><td>20</td><td>181</td><td>75</td><td>0</td><td>1</td><td>49</td><td>7</td><td>3</td><td>90</td><td>7</td><td>8</td><td>8</td><td style="">0.249</td><td>0.334</td><td>0.443</td><td>0.777</td><td>0.134</td><td>117.7</td><td style="background-color:#F3F3F3; font-weight:bold;">4.13</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14137">문보경</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.99</td><td>131</td><td>4.32</td><td>-0.33</td><td>542</td><td>533</td><td>469</td><td>77</td><td>141</td><td>29</td><td>5</td><td>10</td><td>210</td><td>72</td><td>9</td><td>8</td><td>58</td><td>2</td><td>2</td><td>83</td><td>5</td><td>9</td><td>4</td><td style="">0.301</td><td>0.377</td><td>0.448</td><td>0.825</td><td>0.158</td><td>138.5</td><td style="background-color:#F3F3F3; font-weight:bold;">3.99</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13112">문성주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.58</td><td>136</td><td>2.86</td><td>0.72</td><td>534</td><td>528</td><td>449</td><td>77</td><td>132</td><td>21</td><td>4</td><td>2</td><td>167</td><td>57</td><td>24</td><td>14</td><td>67</td><td>8</td><td>0</td><td>34</td><td>10</td><td>6</td><td>4</td><td style="">0.294</td><td>0.392</td><td>0.372</td><td>0.764</td><td>0.146</td><td>129.1</td><td style="background-color:#F3F3F3; font-weight:bold;">3.58</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11190">박해민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.35</td><td>144</td><td>2.43</td><td>0.92</td><td>558</td><td>534</td><td>485</td><td>80</td><td>138</td><td>14</td><td>2</td><td>6</td><td>174</td><td>59</td><td>26</td><td>12</td><td>45</td><td>3</td><td>0</td><td>74</td><td>7</td><td>24</td><td>1</td><td style="">0.285</td><td>0.348</td><td>0.359</td><td>0.707</td><td>0.117</td><td>103.4</td><td style="background-color:#F3F3F3; font-weight:bold;">3.35</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10187">김현수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.64</td><td>133</td><td>1.71</td><td>-0.07</td><td>556</td><td>555</td><td>488</td><td>53</td><td>143</td><td>22</td><td>2</td><td>6</td><td>187</td><td>88</td><td>2</td><td>1</td><td>58</td><td>1</td><td>4</td><td>53</td><td>10</td><td>1</td><td>8</td><td style="">0.293</td><td>0.364</td><td>0.383</td><td>0.747</td><td>0.130</td><td>114.4</td><td style="background-color:#F3F3F3; font-weight:bold;">1.64</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10238">김민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.62</td><td>112</td><td>1.14</td><td>0.48</td><td>316</td><td>307</td><td>273</td><td>34</td><td>68</td><td>11</td><td>0</td><td>8</td><td>103</td><td>41</td><td>2</td><td>1</td><td>25</td><td>7</td><td>0</td><td>58</td><td>7</td><td>9</td><td>2</td><td style="">0.249</td><td>0.326</td><td>0.377</td><td>0.703</td><td>0.114</td><td>100.7</td><td style="background-color:#F3F3F3; font-weight:bold;">1.62</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13056">신민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.21</td><td>122</td><td>0.98</td><td>0.24</td><td>331</td><td>314</td><td>282</td><td>47</td><td>78</td><td>5</td><td>2</td><td>0</td><td>87</td><td>28</td><td>37</td><td>17</td><td>29</td><td>1</td><td>0</td><td>34</td><td>5</td><td>17</td><td>2</td><td style="">0.277</td><td>0.344</td><td>0.309</td><td>0.653</td><td>0.100</td><td>87.7</td><td style="background-color:#F3F3F3; font-weight:bold;">1.21</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10935">이천웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.13</td><td>4</td><td>0.16</td><td>-0.03</td><td>3</td><td>3</td><td>3</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">1.000</td><td>1.000</td><td>1.000</td><td>2.000</td><td>0.612</td><td>520.1</td><td style="background-color:#F3F3F3; font-weight:bold;">0.13</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11347">안익훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.05</td><td>11</td><td>0.04</td><td>0.01</td><td>23</td><td>23</td><td>22</td><td>1</td><td>7</td><td>1</td><td>0</td><td>0</td><td>8</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.318</td><td>0.348</td><td>0.364</td><td>0.712</td><td>0.117</td><td>103.7</td><td style="background-color:#F3F3F3; font-weight:bold;">0.05</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13104">이재원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.05</td><td>57</td><td>0.17</td><td>-0.13</td><td>129</td><td>128</td><td>112</td><td>15</td><td>24</td><td>5</td><td>0</td><td>4</td><td>41</td><td>18</td><td>4</td><td>2</td><td>12</td><td>2</td><td>2</td><td>40</td><td>1</td><td>0</td><td>3</td><td style="">0.214</td><td>0.295</td><td>0.366</td><td>0.661</td><td>0.091</td><td>80.4</td><td style="background-color:#F3F3F3; font-weight:bold;">0.05</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14134">이정용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12532">김대현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11387">채지선</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12860">오석주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10535">최동환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>3</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15486">박명근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15485">김동규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12907">고우석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12864">전준호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.02</td><td>2</td><td>-0.02</td><td>0.00</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-140.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.02</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10684">허도환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>47</td><td>-0.04</td><td>0.01</td><td>81</td><td>74</td><td>64</td><td>8</td><td>9</td><td>3</td><td>0</td><td>2</td><td>18</td><td>10</td><td>0</td><td>0</td><td>3</td><td>6</td><td>0</td><td>20</td><td>3</td><td>7</td><td>1</td><td style="">0.141</td><td>0.243</td><td>0.281</td><td>0.524</td><td>0.053</td><td>46.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12545">김주성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.06</td><td>11</td><td>0.06</td><td>-0.12</td><td>7</td><td>7</td><td>5</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.200</td><td>0.429</td><td>0.200</td><td>0.629</td><td>0.141</td><td>123.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.06</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14591">이주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.10</td><td>18</td><td>0.07</td><td>-0.17</td><td>16</td><td>16</td><td>15</td><td>2</td><td>4</td><td>2</td><td>0</td><td>0</td><td>6</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td style="">0.267</td><td>0.313</td><td>0.400</td><td>0.713</td><td>0.118</td><td>104.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.10</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15492">송대현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.16</td><td>4</td><td>-0.07</td><td>-0.09</td><td>3</td><td>3</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-150.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.16</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14187">최승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.19</td><td>38</td><td>-0.20</td><td>0.01</td><td>15</td><td>15</td><td>14</td><td>10</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>8</td><td>3</td><td>1</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td style="">0.071</td><td>0.133</td><td>0.071</td><td>0.204</td><td>-0.071</td><td>-63.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.19</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13109">송찬의</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.32</td><td>19</td><td>-0.22</td><td>-0.10</td><td>22</td><td>22</td><td>18</td><td>2</td><td>1</td><td>1</td><td>0</td><td>0</td><td>2</td><td>1</td><td>1</td><td>0</td><td>4</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>0</td><td style="">0.056</td><td>0.227</td><td>0.111</td><td>0.338</td><td>0.006</td><td>5.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.32</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14590">손호영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.36</td><td>27</td><td>-0.23</td><td>-0.14</td><td>45</td><td>45</td><td>44</td><td>8</td><td>9</td><td>0</td><td>0</td><td>1</td><td>12</td><td>6</td><td>2</td><td>1</td><td>1</td><td>0</td><td>0</td><td>12</td><td>5</td><td>0</td><td>0</td><td style="">0.205</td><td>0.222</td><td>0.273</td><td>0.495</td><td>0.025</td><td>21.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.36</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15484">김범석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.47</td><td>10</td><td>-0.26</td><td>-0.21</td><td>29</td><td>29</td><td>27</td><td>3</td><td>3</td><td>1</td><td>0</td><td>1</td><td>7</td><td>4</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>5</td><td>1</td><td>0</td><td>1</td><td style="">0.111</td><td>0.138</td><td>0.259</td><td>0.397</td><td>-0.018</td><td>-15.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.47</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12549">김기연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.67</td><td>28</td><td>-0.21</td><td>-0.46</td><td>40</td><td>39</td><td>34</td><td>3</td><td>4</td><td>0</td><td>0</td><td>0</td><td>4</td><td>2</td><td>1</td><td>0</td><td>5</td><td>0</td><td>0</td><td>10</td><td>0</td><td>1</td><td>0</td><td style="">0.118</td><td>0.231</td><td>0.118</td><td>0.349</td><td>-0.002</td><td>-1.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.67</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10480">정주현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.88</td><td>89</td><td>-0.02</td><td>-0.85</td><td>101</td><td>98</td><td>88</td><td>17</td><td>24</td><td>2</td><td>0</td><td>1</td><td>29</td><td>12</td><td>1</td><td>5</td><td>9</td><td>0</td><td>0</td><td>16</td><td>1</td><td>2</td><td>1</td><td style="">0.273</td><td>0.337</td><td>0.330</td><td>0.667</td><td>0.099</td><td>87.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.88</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10855">서건창</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.90</td><td>44</td><td>-0.44</td><td>-0.46</td><td>126</td><td>123</td><td>110</td><td>14</td><td>22</td><td>5</td><td>2</td><td>0</td><td>31</td><td>12</td><td>3</td><td>3</td><td>10</td><td>0</td><td>0</td><td>14</td><td>5</td><td>3</td><td>3</td><td style="">0.200</td><td>0.260</td><td>0.282</td><td>0.542</td><td>0.053</td><td>46.1</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.90</td></tr>			</tbody>
		</table>""")

In [23]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10266">전준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.41</td><td>138</td><td>3.75</td><td>-0.34</td><td>559</td><td>556</td><td>493</td><td>80</td><td>154</td><td>21</td><td>3</td><td>17</td><td>232</td><td>77</td><td>9</td><td>2</td><td>52</td><td>7</td><td>4</td><td>65</td><td>12</td><td>0</td><td>7</td><td style="">0.312</td><td>0.381</td><td>0.471</td><td>0.852</td><td>0.163</td><td>134.5</td><td style="background-color:#F3F3F3; font-weight:bold;">3.41</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10753">유강남</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.34</td><td>121</td><td>2.33</td><td>0.00</td><td>403</td><td>401</td><td>352</td><td>45</td><td>92</td><td>13</td><td>0</td><td>10</td><td>135</td><td>55</td><td>1</td><td>1</td><td>37</td><td>8</td><td>1</td><td>64</td><td>13</td><td>2</td><td>4</td><td style="">0.261</td><td>0.342</td><td>0.384</td><td>0.726</td><td>0.122</td><td>100.9</td><td style="background-color:#F3F3F3; font-weight:bold;">2.34</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11165">노진혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.32</td><td>113</td><td>2.36</td><td>-0.04</td><td>390</td><td>386</td><td>334</td><td>43</td><td>86</td><td>26</td><td>1</td><td>4</td><td>126</td><td>51</td><td>7</td><td>2</td><td>45</td><td>3</td><td>1</td><td>84</td><td>3</td><td>4</td><td>4</td><td style="">0.257</td><td>0.347</td><td>0.377</td><td>0.724</td><td>0.125</td><td>103.2</td><td style="background-color:#F3F3F3; font-weight:bold;">2.32</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10014">안치홍</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.30</td><td>121</td><td>2.77</td><td>-0.46</td><td>494</td><td>487</td><td>425</td><td>57</td><td>124</td><td>20</td><td>1</td><td>8</td><td>170</td><td>63</td><td>3</td><td>3</td><td>49</td><td>10</td><td>3</td><td>53</td><td>14</td><td>5</td><td>5</td><td style="">0.292</td><td>0.374</td><td>0.400</td><td>0.774</td><td>0.142</td><td>117.5</td><td style="background-color:#F3F3F3; font-weight:bold;">2.30</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10804">박승욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.82</td><td>123</td><td>2.04</td><td>-0.22</td><td>338</td><td>327</td><td>290</td><td>37</td><td>83</td><td>18</td><td>3</td><td>0</td><td>107</td><td>30</td><td>15</td><td>4</td><td>35</td><td>1</td><td>0</td><td>87</td><td>5</td><td>11</td><td>1</td><td style="">0.286</td><td>0.364</td><td>0.369</td><td>0.733</td><td>0.131</td><td>108.7</td><td style="background-color:#F3F3F3; font-weight:bold;">1.82</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13154">정보근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.33</td><td>55</td><td>1.37</td><td>-0.05</td><td>101</td><td>97</td><td>81</td><td>11</td><td>27</td><td>6</td><td>1</td><td>1</td><td>38</td><td>13</td><td>1</td><td>0</td><td>14</td><td>1</td><td>0</td><td>13</td><td>1</td><td>4</td><td>1</td><td style="">0.333</td><td>0.433</td><td>0.469</td><td>0.902</td><td>0.193</td><td>158.9</td><td style="background-color:#F3F3F3; font-weight:bold;">1.33</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14571">안권수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.99</td><td>95</td><td>0.42</td><td>0.57</td><td>309</td><td>302</td><td>268</td><td>42</td><td>72</td><td>6</td><td>1</td><td>2</td><td>86</td><td>29</td><td>16</td><td>7</td><td>30</td><td>1</td><td>1</td><td>40</td><td>4</td><td>7</td><td>3</td><td style="">0.269</td><td>0.341</td><td>0.321</td><td>0.662</td><td>0.102</td><td>84.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.99</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10253">정훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.75</td><td>80</td><td>1.24</td><td>-0.49</td><td>233</td><td>228</td><td>201</td><td>40</td><td>56</td><td>14</td><td>0</td><td>6</td><td>88</td><td>31</td><td>2</td><td>0</td><td>26</td><td>0</td><td>1</td><td>39</td><td>4</td><td>4</td><td>2</td><td style="">0.279</td><td>0.358</td><td>0.438</td><td>0.796</td><td>0.145</td><td>118.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.75</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15651">구드럼</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.39</td><td>50</td><td>1.15</td><td>-0.75</td><td>201</td><td>201</td><td>173</td><td>16</td><td>51</td><td>14</td><td>1</td><td>0</td><td>67</td><td>28</td><td>0</td><td>0</td><td>23</td><td>1</td><td>1</td><td>46</td><td>6</td><td>0</td><td>4</td><td style="">0.295</td><td>0.373</td><td>0.387</td><td>0.760</td><td>0.138</td><td>115.0</td><td style="background-color:#F3F3F3; font-weight:bold;">0.39</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15048">윤동희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.35</td><td>107</td><td>0.34</td><td>0.01</td><td>423</td><td>421</td><td>387</td><td>45</td><td>111</td><td>18</td><td>1</td><td>2</td><td>137</td><td>41</td><td>3</td><td>6</td><td>28</td><td>1</td><td>0</td><td>69</td><td>10</td><td>2</td><td>5</td><td style="">0.287</td><td>0.333</td><td>0.354</td><td>0.687</td><td>0.106</td><td>88.0</td><td style="background-color:#F3F3F3; font-weight:bold;">0.35</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14796">손성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.29</td><td>45</td><td>0.08</td><td>0.21</td><td>80</td><td>78</td><td>76</td><td>13</td><td>20</td><td>3</td><td>0</td><td>1</td><td>26</td><td>15</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>10</td><td>3</td><td>2</td><td>0</td><td style="">0.263</td><td>0.282</td><td>0.342</td><td>0.624</td><td>0.076</td><td>63.7</td><td style="background-color:#F3F3F3; font-weight:bold;">0.29</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15625">배영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.21</td><td>18</td><td>0.25</td><td>-0.04</td><td>18</td><td>17</td><td>16</td><td>2</td><td>5</td><td>2</td><td>0</td><td>0</td><td>7</td><td>0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>1</td><td>0</td><td style="">0.313</td><td>0.353</td><td>0.438</td><td>0.791</td><td>0.144</td><td>123.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.21</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13155">장두성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.17</td><td>25</td><td>-0.03</td><td>0.20</td><td>15</td><td>14</td><td>13</td><td>7</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>2</td><td>0</td><td>1</td><td>0</td><td>0</td><td>3</td><td>1</td><td>1</td><td>0</td><td style="">0.154</td><td>0.214</td><td>0.154</td><td>0.368</td><td>-0.008</td><td>-6.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.17</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15152">렉스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.12</td><td>55</td><td>0.40</td><td>-0.28</td><td>234</td><td>233</td><td>203</td><td>20</td><td>50</td><td>4</td><td>2</td><td>4</td><td>70</td><td>30</td><td>0</td><td>1</td><td>28</td><td>1</td><td>2</td><td>54</td><td>3</td><td>0</td><td>2</td><td style="">0.246</td><td>0.338</td><td>0.345</td><td>0.683</td><td>0.108</td><td>88.5</td><td style="background-color:#F3F3F3; font-weight:bold;">0.12</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15253">김민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.10</td><td>129</td><td>0.73</td><td>-0.63</td><td>454</td><td>441</td><td>400</td><td>53</td><td>102</td><td>24</td><td>0</td><td>3</td><td>135</td><td>39</td><td>16</td><td>3</td><td>31</td><td>6</td><td>1</td><td>112</td><td>6</td><td>12</td><td>5</td><td style="">0.255</td><td>0.314</td><td>0.338</td><td>0.652</td><td>0.095</td><td>78.1</td><td style="background-color:#F3F3F3; font-weight:bold;">0.10</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14160">고승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.08</td><td>94</td><td>0.21</td><td>-0.13</td><td>308</td><td>301</td><td>255</td><td>35</td><td>57</td><td>14</td><td>2</td><td>2</td><td>81</td><td>24</td><td>8</td><td>3</td><td>42</td><td>1</td><td>3</td><td>64</td><td>2</td><td>6</td><td>4</td><td style="">0.224</td><td>0.331</td><td>0.318</td><td>0.649</td><td>0.100</td><td>82.5</td><td style="background-color:#F3F3F3; font-weight:bold;">0.08</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12916">이정훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.08</td><td>59</td><td>0.38</td><td>-0.30</td><td>171</td><td>171</td><td>152</td><td>17</td><td>45</td><td>7</td><td>0</td><td>1</td><td>55</td><td>17</td><td>1</td><td>1</td><td>13</td><td>3</td><td>0</td><td>28</td><td>1</td><td>0</td><td>3</td><td style="">0.296</td><td>0.357</td><td>0.362</td><td>0.719</td><td>0.122</td><td>101.2</td><td style="background-color:#F3F3F3; font-weight:bold;">0.08</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14642">황성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.08</td><td>74</td><td>-0.63</td><td>0.71</td><td>191</td><td>183</td><td>170</td><td>22</td><td>36</td><td>5</td><td>2</td><td>0</td><td>45</td><td>8</td><td>9</td><td>5</td><td>12</td><td>1</td><td>0</td><td>27</td><td>1</td><td>8</td><td>0</td><td style="">0.212</td><td>0.268</td><td>0.265</td><td>0.533</td><td>0.051</td><td>42.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.08</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15645">김동혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.01</td><td>15</td><td>-0.07</td><td>0.07</td><td>9</td><td>9</td><td>7</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>2</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.222</td><td>0.000</td><td>0.222</td><td>-0.019</td><td>-15.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.01</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10825">김원중</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>3</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=0"><b style="font-weight:bold;color:red;">0</b></a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span></span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10427">김상수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11276">최영환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11413">지시완</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>6</td><td>-0.14</td><td>0.13</td><td>10</td><td>8</td><td>8</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>0</td><td>2</td><td>0</td><td style="">0.125</td><td>0.125</td><td>0.125</td><td>0.250</td><td>-0.070</td><td>-57.2</td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14861">박형준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>1</td><td>-0.03</td><td>0.00</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-140.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10172">국해성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.04</td><td>6</td><td>-0.05</td><td>0.01</td><td>10</td><td>10</td><td>8</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td style="">0.250</td><td>0.400</td><td>0.250</td><td>0.650</td><td>0.122</td><td>100.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.04</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15627">윤수녕</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.05</td><td>3</td><td>-0.03</td><td>-0.02</td><td>4</td><td>4</td><td>4</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.250</td><td>0.250</td><td>0.250</td><td>0.500</td><td>0.028</td><td>23.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.05</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15624">서동욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.12</td><td>13</td><td>-0.15</td><td>0.03</td><td>20</td><td>20</td><td>17</td><td>2</td><td>2</td><td>1</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>5</td><td>1</td><td>0</td><td>0</td><td style="">0.118</td><td>0.250</td><td>0.176</td><td>0.426</td><td>0.029</td><td>24.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.12</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14114">이학주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.17</td><td>104</td><td>0.14</td><td>-0.31</td><td>122</td><td>122</td><td>110</td><td>22</td><td>23</td><td>2</td><td>0</td><td>3</td><td>34</td><td>13</td><td>4</td><td>1</td><td>11</td><td>1</td><td>0</td><td>31</td><td>2</td><td>0</td><td>0</td><td style="">0.209</td><td>0.287</td><td>0.309</td><td>0.596</td><td>0.075</td><td>61.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.17</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12931">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.26</td><td>25</td><td>-0.04</td><td>-0.22</td><td>51</td><td>50</td><td>43</td><td>4</td><td>9</td><td>1</td><td>1</td><td>0</td><td>12</td><td>2</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>17</td><td>2</td><td>1</td><td>0</td><td style="">0.209</td><td>0.320</td><td>0.279</td><td>0.599</td><td>0.088</td><td>71.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.26</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14169">신윤후</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.38</td><td>28</td><td>-0.43</td><td>0.05</td><td>27</td><td>27</td><td>25</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>8</td><td>0</td><td>0</td><td>0</td><td style="">0.040</td><td>0.111</td><td>0.040</td><td>0.151</td><td>-0.086</td><td>-72.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.38</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15443">정대선</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.54</td><td>19</td><td>-0.36</td><td>-0.18</td><td>47</td><td>46</td><td>40</td><td>5</td><td>6</td><td>1</td><td>0</td><td>0</td><td>7</td><td>6</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>8</td><td>0</td><td>1</td><td>2</td><td style="">0.150</td><td>0.217</td><td>0.175</td><td>0.392</td><td>0.002</td><td>2.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.54</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13145">한동희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-1.81</td><td>108</td><td>-0.94</td><td>-0.88</td><td>353</td><td>351</td><td>319</td><td>30</td><td>71</td><td>11</td><td>0</td><td>5</td><td>97</td><td>32</td><td>1</td><td>3</td><td>26</td><td>1</td><td>0</td><td>58</td><td>16</td><td>2</td><td>5</td><td style="">0.223</td><td>0.279</td><td>0.304</td><td>0.583</td><td>0.067</td><td>55.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-1.81</td></tr>			</tbody>
		</table>""")

In [24]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11261">박찬호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.09</td><td>130</td><td>3.64</td><td>0.46</td><td>507</td><td>500</td><td>452</td><td>73</td><td>136</td><td>18</td><td>4</td><td>3</td><td>171</td><td>52</td><td>30</td><td>8</td><td>40</td><td>2</td><td>0</td><td>56</td><td>13</td><td>7</td><td>6</td><td style="">0.301</td><td>0.356</td><td>0.378</td><td>0.734</td><td>0.127</td><td>109.5</td><td style="background-color:#F3F3F3; font-weight:bold;">4.09</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14996">소크라테스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.88</td><td>142</td><td>3.51</td><td>0.37</td><td>608</td><td>606</td><td>547</td><td>91</td><td>156</td><td>31</td><td>3</td><td>20</td><td>253</td><td>96</td><td>15</td><td>6</td><td>52</td><td>1</td><td>4</td><td>80</td><td>13</td><td>0</td><td>8</td><td style="">0.285</td><td>0.344</td><td>0.463</td><td>0.807</td><td>0.144</td><td>125.0</td><td style="background-color:#F3F3F3; font-weight:bold;">3.88</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10344">최형우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.73</td><td>121</td><td>4.11</td><td>-0.38</td><td>508</td><td>508</td><td>431</td><td>64</td><td>130</td><td>27</td><td>1</td><td>17</td><td>210</td><td>81</td><td>0</td><td>0</td><td>65</td><td>8</td><td>1</td><td>83</td><td>5</td><td>0</td><td>4</td><td style="">0.302</td><td>0.400</td><td>0.487</td><td>0.887</td><td>0.183</td><td>159.4</td><td style="background-color:#F3F3F3; font-weight:bold;">3.73</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15056">김도영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.64</td><td>84</td><td>3.14</td><td>0.50</td><td>385</td><td>382</td><td>340</td><td>72</td><td>103</td><td>20</td><td>5</td><td>7</td><td>154</td><td>47</td><td>25</td><td>4</td><td>38</td><td>1</td><td>1</td><td>62</td><td>14</td><td>2</td><td>4</td><td style="">0.303</td><td>0.371</td><td>0.453</td><td>0.824</td><td>0.156</td><td>134.4</td><td style="background-color:#F3F3F3; font-weight:bold;">3.64</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11162">나성범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.57</td><td>58</td><td>3.88</td><td>-0.31</td><td>253</td><td>253</td><td>222</td><td>51</td><td>81</td><td>12</td><td>1</td><td>18</td><td>149</td><td>57</td><td>0</td><td>0</td><td>26</td><td>1</td><td>0</td><td>36</td><td>1</td><td>0</td><td>4</td><td style="">0.365</td><td>0.427</td><td>0.671</td><td>1.098</td><td>0.243</td><td>209.8</td><td style="background-color:#F3F3F3; font-weight:bold;">3.57</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10008">김선빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.62</td><td>119</td><td>2.83</td><td>-0.21</td><td>473</td><td>465</td><td>419</td><td>41</td><td>134</td><td>16</td><td>0</td><td>0</td><td>150</td><td>48</td><td>3</td><td>1</td><td>38</td><td>5</td><td>0</td><td>26</td><td>10</td><td>8</td><td>3</td><td style="">0.320</td><td>0.381</td><td>0.358</td><td>0.739</td><td>0.132</td><td>114.9</td><td style="background-color:#F3F3F3; font-weight:bold;">2.62</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11099">이우성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.30</td><td>126</td><td>1.92</td><td>0.38</td><td>400</td><td>393</td><td>355</td><td>39</td><td>107</td><td>17</td><td>0</td><td>8</td><td>148</td><td>58</td><td>8</td><td>1</td><td>31</td><td>5</td><td>4</td><td>81</td><td>10</td><td>6</td><td>3</td><td style="">0.301</td><td>0.363</td><td>0.417</td><td>0.780</td><td>0.141</td><td>122.4</td><td style="background-color:#F3F3F3; font-weight:bold;">2.30</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11233">이창진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.36</td><td>104</td><td>1.37</td><td>-0.01</td><td>284</td><td>282</td><td>244</td><td>35</td><td>66</td><td>11</td><td>3</td><td>4</td><td>95</td><td>29</td><td>9</td><td>2</td><td>34</td><td>2</td><td>1</td><td>44</td><td>6</td><td>2</td><td>2</td><td style="">0.270</td><td>0.362</td><td>0.389</td><td>0.751</td><td>0.135</td><td>117.7</td><td style="background-color:#F3F3F3; font-weight:bold;">1.36</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10659">고종욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.56</td><td>114</td><td>0.68</td><td>-0.12</td><td>286</td><td>286</td><td>270</td><td>35</td><td>80</td><td>17</td><td>0</td><td>3</td><td>106</td><td>39</td><td>2</td><td>2</td><td>14</td><td>0</td><td>0</td><td>58</td><td>3</td><td>0</td><td>2</td><td style="">0.296</td><td>0.329</td><td>0.393</td><td>0.722</td><td>0.115</td><td>99.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.56</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13113">한준수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.52</td><td>48</td><td>0.32</td><td>0.20</td><td>94</td><td>93</td><td>86</td><td>9</td><td>22</td><td>4</td><td>0</td><td>2</td><td>32</td><td>12</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>26</td><td>2</td><td>1</td><td>0</td><td style="">0.256</td><td>0.312</td><td>0.372</td><td>0.684</td><td>0.104</td><td>89.2</td><td style="background-color:#F3F3F3; font-weight:bold;">0.52</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12540">김규성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.52</td><td>99</td><td>0.32</td><td>0.20</td><td>177</td><td>172</td><td>158</td><td>29</td><td>37</td><td>6</td><td>1</td><td>2</td><td>51</td><td>11</td><td>6</td><td>2</td><td>13</td><td>1</td><td>0</td><td>43</td><td>2</td><td>5</td><td>0</td><td style="">0.234</td><td>0.297</td><td>0.323</td><td>0.620</td><td>0.083</td><td>71.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.52</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12534">최원준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.35</td><td>67</td><td>0.45</td><td>-0.10</td><td>274</td><td>270</td><td>239</td><td>37</td><td>61</td><td>11</td><td>2</td><td>1</td><td>79</td><td>23</td><td>13</td><td>5</td><td>31</td><td>0</td><td>0</td><td>39</td><td>5</td><td>4</td><td>0</td><td style="">0.255</td><td>0.341</td><td>0.331</td><td>0.672</td><td>0.109</td><td>94.2</td><td style="background-color:#F3F3F3; font-weight:bold;">0.35</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12869">박정우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.24</td><td>21</td><td>0.03</td><td>0.20</td><td>12</td><td>9</td><td>9</td><td>2</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>3</td><td>0</td><td style="">0.333</td><td>0.333</td><td>0.333</td><td>0.666</td><td>0.093</td><td>80.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.24</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11298">김호령</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.19</td><td>76</td><td>-0.36</td><td>0.55</td><td>107</td><td>104</td><td>95</td><td>16</td><td>17</td><td>7</td><td>0</td><td>0</td><td>24</td><td>6</td><td>1</td><td>0</td><td>8</td><td>1</td><td>0</td><td>38</td><td>1</td><td>3</td><td>0</td><td style="">0.179</td><td>0.250</td><td>0.253</td><td>0.503</td><td>0.043</td><td>37.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.19</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11407">최정용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.16</td><td>56</td><td>-0.16</td><td>0.32</td><td>41</td><td>38</td><td>36</td><td>17</td><td>6</td><td>1</td><td>0</td><td>0</td><td>7</td><td>1</td><td>4</td><td>0</td><td>2</td><td>0</td><td>0</td><td>9</td><td>0</td><td>3</td><td>0</td><td style="">0.167</td><td>0.211</td><td>0.194</td><td>0.405</td><td>0.001</td><td>0.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.16</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14612">홍종표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.11</td><td>40</td><td>0.06</td><td>0.05</td><td>12</td><td>11</td><td>7</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>1</td><td>0</td><td>1</td><td>0</td><td style="">0.000</td><td>0.364</td><td>0.000</td><td>0.364</td><td>0.079</td><td>64.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.11</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14822">김선우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.02</td><td>5</td><td>-0.08</td><td>0.10</td><td>7</td><td>7</td><td>7</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.143</td><td>0.143</td><td>0.143</td><td>0.286</td><td>-0.056</td><td>-48.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.02</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14608">정해영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14176">김기훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11070">박준표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13122">윤중현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15063">황동하</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10894">류지혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>66</td><td>0.60</td><td>-0.62</td><td>253</td><td>250</td><td>220</td><td>28</td><td>59</td><td>6</td><td>1</td><td>0</td><td>67</td><td>17</td><td>4</td><td>2</td><td>27</td><td>3</td><td>1</td><td>43</td><td>5</td><td>2</td><td>1</td><td style="">0.268</td><td>0.355</td><td>0.305</td><td>0.660</td><td>0.106</td><td>93.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15058">윤도현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.06</td><td>1</td><td>-0.03</td><td>-0.04</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-149.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.06</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10459">김태군</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.21</td><td>65</td><td>-0.09</td><td>-0.12</td><td>203</td><td>198</td><td>186</td><td>17</td><td>48</td><td>6</td><td>0</td><td>0</td><td>54</td><td>24</td><td>2</td><td>1</td><td>5</td><td>4</td><td>0</td><td>19</td><td>9</td><td>5</td><td>3</td><td style="">0.258</td><td>0.288</td><td>0.290</td><td>0.578</td><td>0.064</td><td>54.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.21</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12541">신범수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.21</td><td>36</td><td>-0.25</td><td>0.04</td><td>100</td><td>98</td><td>88</td><td>7</td><td>15</td><td>3</td><td>0</td><td>2</td><td>24</td><td>10</td><td>0</td><td>0</td><td>7</td><td>2</td><td>0</td><td>19</td><td>3</td><td>2</td><td>1</td><td style="">0.170</td><td>0.245</td><td>0.273</td><td>0.518</td><td>0.042</td><td>37.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.21</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14181">오선우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.23</td><td>33</td><td>-0.13</td><td>-0.10</td><td>31</td><td>31</td><td>28</td><td>2</td><td>5</td><td>0</td><td>0</td><td>2</td><td>11</td><td>5</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>15</td><td>0</td><td>0</td><td>0</td><td style="">0.179</td><td>0.258</td><td>0.393</td><td>0.651</td><td>0.084</td><td>73.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.23</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11306">황대인</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.27</td><td>60</td><td>-0.48</td><td>0.21</td><td>199</td><td>198</td><td>174</td><td>19</td><td>37</td><td>4</td><td>0</td><td>5</td><td>56</td><td>26</td><td>0</td><td>0</td><td>18</td><td>4</td><td>2</td><td>50</td><td>6</td><td>0</td><td>3</td><td style="">0.213</td><td>0.296</td><td>0.322</td><td>0.618</td><td>0.081</td><td>70.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.27</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14124">변우혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.33</td><td>83</td><td>0.11</td><td>-0.44</td><td>226</td><td>226</td><td>200</td><td>23</td><td>45</td><td>4</td><td>0</td><td>7</td><td>70</td><td>24</td><td>0</td><td>0</td><td>23</td><td>3</td><td>1</td><td>74</td><td>4</td><td>0</td><td>0</td><td style="">0.225</td><td>0.314</td><td>0.350</td><td>0.664</td><td>0.100</td><td>88.1</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.33</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12917">김석환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.43</td><td>12</td><td>-0.30</td><td>-0.14</td><td>26</td><td>25</td><td>23</td><td>1</td><td>3</td><td>1</td><td>0</td><td>0</td><td>4</td><td>3</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>9</td><td>1</td><td>1</td><td>0</td><td style="">0.130</td><td>0.200</td><td>0.174</td><td>0.374</td><td>-0.006</td><td>-4.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.43</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12567">주효상</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.53</td><td>19</td><td>-0.53</td><td>0.00</td><td>36</td><td>34</td><td>32</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>10</td><td>1</td><td>2</td><td>0</td><td style="">0.063</td><td>0.118</td><td>0.063</td><td>0.181</td><td>-0.082</td><td>-72.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.53</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11119">한승택</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.58</td><td>49</td><td>-0.48</td><td>-0.11</td><td>104</td><td>98</td><td>85</td><td>6</td><td>11</td><td>2</td><td>0</td><td>0</td><td>13</td><td>3</td><td>0</td><td>0</td><td>11</td><td>2</td><td>0</td><td>32</td><td>1</td><td>6</td><td>0</td><td style="">0.129</td><td>0.245</td><td>0.153</td><td>0.398</td><td>0.017</td><td>15.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.58</td></tr>			</tbody>
		</table>""")

In [25]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15144">알포드</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.85</td><td>133</td><td>3.45</td><td>0.40</td><td>547</td><td>546</td><td>491</td><td>83</td><td>142</td><td>31</td><td>3</td><td>15</td><td>224</td><td>70</td><td>17</td><td>4</td><td>47</td><td>6</td><td>1</td><td>140</td><td>6</td><td>0</td><td>3</td><td style="">0.289</td><td>0.356</td><td>0.456</td><td>0.812</td><td>0.150</td><td>123.5</td><td style="background-color:#F3F3F3; font-weight:bold;">3.85</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10235">장성우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.29</td><td>131</td><td>3.15</td><td>0.14</td><td>464</td><td>460</td><td>410</td><td>37</td><td>118</td><td>22</td><td>0</td><td>11</td><td>173</td><td>65</td><td>1</td><td>1</td><td>42</td><td>2</td><td>1</td><td>70</td><td>12</td><td>3</td><td>7</td><td style="">0.288</td><td>0.351</td><td>0.422</td><td>0.773</td><td>0.136</td><td>110.5</td><td style="background-color:#F3F3F3; font-weight:bold;">3.29</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10407">황재균</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.14</td><td>109</td><td>2.70</td><td>0.44</td><td>457</td><td>454</td><td>407</td><td>62</td><td>120</td><td>26</td><td>2</td><td>6</td><td>168</td><td>49</td><td>3</td><td>3</td><td>45</td><td>1</td><td>1</td><td>64</td><td>15</td><td>3</td><td>1</td><td style="">0.295</td><td>0.366</td><td>0.413</td><td>0.779</td><td>0.142</td><td>116.0</td><td style="background-color:#F3F3F3; font-weight:bold;">3.14</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10470">박병호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.66</td><td>132</td><td>1.91</td><td>0.75</td><td>493</td><td>493</td><td>431</td><td>53</td><td>122</td><td>15</td><td>0</td><td>18</td><td>191</td><td>87</td><td>2</td><td>0</td><td>46</td><td>8</td><td>2</td><td>114</td><td>9</td><td>0</td><td>8</td><td style="">0.283</td><td>0.357</td><td>0.443</td><td>0.800</td><td>0.144</td><td>118.2</td><td style="background-color:#F3F3F3; font-weight:bold;">2.66</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11339">김민혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.55</td><td>113</td><td>1.79</td><td>0.76</td><td>448</td><td>441</td><td>397</td><td>68</td><td>118</td><td>20</td><td>3</td><td>3</td><td>153</td><td>41</td><td>11</td><td>4</td><td>36</td><td>3</td><td>0</td><td>48</td><td>4</td><td>7</td><td>5</td><td style="">0.297</td><td>0.356</td><td>0.385</td><td>0.741</td><td>0.128</td><td>104.9</td><td style="background-color:#F3F3F3; font-weight:bold;">2.55</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10320">김상수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.28</td><td>129</td><td>2.70</td><td>-0.43</td><td>512</td><td>504</td><td>443</td><td>58</td><td>120</td><td>19</td><td>1</td><td>3</td><td>150</td><td>56</td><td>5</td><td>6</td><td>55</td><td>3</td><td>0</td><td>68</td><td>9</td><td>8</td><td>3</td><td style="">0.271</td><td>0.353</td><td>0.339</td><td>0.692</td><td>0.116</td><td>95.3</td><td style="background-color:#F3F3F3; font-weight:bold;">2.28</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11212">배정대</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.67</td><td>97</td><td>1.66</td><td>0.01</td><td>361</td><td>356</td><td>311</td><td>48</td><td>86</td><td>16</td><td>0</td><td>2</td><td>108</td><td>38</td><td>13</td><td>3</td><td>38</td><td>3</td><td>1</td><td>76</td><td>2</td><td>4</td><td>5</td><td style="">0.277</td><td>0.356</td><td>0.347</td><td>0.703</td><td>0.118</td><td>96.8</td><td style="background-color:#F3F3F3; font-weight:bold;">1.67</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13151">이호연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.99</td><td>85</td><td>0.77</td><td>0.22</td><td>234</td><td>233</td><td>212</td><td>28</td><td>59</td><td>5</td><td>1</td><td>3</td><td>75</td><td>17</td><td>4</td><td>2</td><td>16</td><td>4</td><td>0</td><td>41</td><td>6</td><td>1</td><td>1</td><td style="">0.278</td><td>0.339</td><td>0.354</td><td>0.693</td><td>0.111</td><td>90.4</td><td style="background-color:#F3F3F3; font-weight:bold;">0.99</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13168">강백호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.74</td><td>71</td><td>0.85</td><td>-0.12</td><td>271</td><td>269</td><td>238</td><td>32</td><td>63</td><td>10</td><td>1</td><td>8</td><td>99</td><td>39</td><td>3</td><td>0</td><td>31</td><td>0</td><td>4</td><td>55</td><td>1</td><td>0</td><td>2</td><td style="">0.265</td><td>0.347</td><td>0.416</td><td>0.763</td><td>0.131</td><td>106.5</td><td style="background-color:#F3F3F3; font-weight:bold;">0.74</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11397">오윤석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.55</td><td>82</td><td>0.35</td><td>0.21</td><td>223</td><td>216</td><td>199</td><td>24</td><td>50</td><td>13</td><td>1</td><td>4</td><td>77</td><td>17</td><td>3</td><td>1</td><td>13</td><td>5</td><td>1</td><td>44</td><td>7</td><td>6</td><td>0</td><td style="">0.251</td><td>0.313</td><td>0.387</td><td>0.700</td><td>0.110</td><td>90.7</td><td style="background-color:#F3F3F3; font-weight:bold;">0.55</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15519">정준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.38</td><td>34</td><td>0.16</td><td>0.22</td><td>55</td><td>51</td><td>48</td><td>6</td><td>14</td><td>2</td><td>0</td><td>0</td><td>16</td><td>6</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>11</td><td>1</td><td>4</td><td>0</td><td style="">0.292</td><td>0.333</td><td>0.333</td><td>0.666</td><td>0.100</td><td>80.7</td><td style="background-color:#F3F3F3; font-weight:bold;">0.38</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10840">신본기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.28</td><td>40</td><td>0.23</td><td>0.05</td><td>75</td><td>74</td><td>54</td><td>8</td><td>11</td><td>2</td><td>0</td><td>1</td><td>16</td><td>7</td><td>0</td><td>1</td><td>14</td><td>2</td><td>0</td><td>8</td><td>3</td><td>1</td><td>4</td><td style="">0.204</td><td>0.365</td><td>0.296</td><td>0.661</td><td>0.117</td><td>94.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.28</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10469">박경수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.20</td><td>107</td><td>0.32</td><td>-0.12</td><td>221</td><td>216</td><td>185</td><td>12</td><td>37</td><td>13</td><td>0</td><td>1</td><td>53</td><td>12</td><td>0</td><td>0</td><td>30</td><td>1</td><td>1</td><td>46</td><td>2</td><td>5</td><td>0</td><td style="">0.200</td><td>0.315</td><td>0.286</td><td>0.601</td><td>0.087</td><td>71.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.20</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11342">송민섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.19</td><td>69</td><td>-0.23</td><td>0.42</td><td>25</td><td>25</td><td>23</td><td>6</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>3</td><td>1</td><td>1</td><td>1</td><td>0</td><td>8</td><td>0</td><td>0</td><td>0</td><td style="">0.130</td><td>0.200</td><td>0.130</td><td>0.330</td><td>-0.018</td><td>-15.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.19</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14191">강민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.18</td><td>12</td><td>0.01</td><td>0.17</td><td>27</td><td>26</td><td>22</td><td>2</td><td>4</td><td>1</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>10</td><td>0</td><td>1</td><td>0</td><td style="">0.182</td><td>0.308</td><td>0.227</td><td>0.535</td><td>0.069</td><td>56.4</td><td style="background-color:#F3F3F3; font-weight:bold;">0.18</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11214">장준원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.16</td><td>69</td><td>-0.06</td><td>0.22</td><td>104</td><td>101</td><td>87</td><td>10</td><td>15</td><td>2</td><td>1</td><td>1</td><td>22</td><td>10</td><td>3</td><td>0</td><td>12</td><td>1</td><td>0</td><td>25</td><td>1</td><td>3</td><td>1</td><td style="">0.172</td><td>0.277</td><td>0.253</td><td>0.530</td><td>0.058</td><td>48.0</td><td style="background-color:#F3F3F3; font-weight:bold;">0.16</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12941">홍현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.15</td><td>44</td><td>0.19</td><td>-0.05</td><td>86</td><td>86</td><td>73</td><td>15</td><td>17</td><td>2</td><td>0</td><td>0</td><td>19</td><td>1</td><td>2</td><td>0</td><td>13</td><td>0</td><td>0</td><td>21</td><td>2</td><td>0</td><td>0</td><td style="">0.233</td><td>0.349</td><td>0.260</td><td>0.609</td><td>0.096</td><td>78.2</td><td style="background-color:#F3F3F3; font-weight:bold;">0.15</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13006">안치영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.14</td><td>76</td><td>0.24</td><td>-0.10</td><td>136</td><td>133</td><td>124</td><td>20</td><td>36</td><td>3</td><td>1</td><td>0</td><td>41</td><td>9</td><td>7</td><td>1</td><td>6</td><td>2</td><td>0</td><td>35</td><td>1</td><td>3</td><td>1</td><td style="">0.290</td><td>0.331</td><td>0.331</td><td>0.662</td><td>0.098</td><td>79.7</td><td style="background-color:#F3F3F3; font-weight:bold;">0.14</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13227">문상인</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.02</td><td>1</td><td>0.05</td><td>-0.02</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td>1.000</td><td></td><td></td><td>0.498</td><td>387.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.02</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15097">김병준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.02</td><td>3</td><td>-0.08</td><td>0.10</td><td>2</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-131.7</td><td style="background-color:#F3F3F3; font-weight:bold;">0.02</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10835">김준태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.01</td><td>69</td><td>0.26</td><td>-0.25</td><td>136</td><td>135</td><td>115</td><td>10</td><td>24</td><td>4</td><td>0</td><td>3</td><td>37</td><td>23</td><td>1</td><td>0</td><td>19</td><td>1</td><td>0</td><td>32</td><td>3</td><td>1</td><td>0</td><td style="">0.209</td><td>0.326</td><td>0.322</td><td>0.648</td><td>0.102</td><td>85.1</td><td style="background-color:#F3F3F3; font-weight:bold;">0.01</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15520">손민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>9</td><td>-0.04</td><td>0.04</td><td>12</td><td>12</td><td>10</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td style="">0.100</td><td>0.250</td><td>0.100</td><td>0.350</td><td>0.013</td><td>10.1</td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14111">이선우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10304">하준호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15089">박영현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>3</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11489">김재윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>5</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14869">김영현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13130">이채호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14109">이상동</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13167">김민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14110">박민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.08</td><td>4</td><td>-0.02</td><td>-0.06</td><td>4</td><td>4</td><td>4</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td style="">0.250</td><td>0.250</td><td>0.250</td><td>0.500</td><td>0.028</td><td>21.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.08</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11330">김병희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.09</td><td>5</td><td>-0.15</td><td>0.06</td><td>9</td><td>9</td><td>8</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.111</td><td>0.000</td><td>0.111</td><td>-0.093</td><td>-73.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.09</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12943">조용호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.12</td><td>63</td><td>0.00</td><td>-0.13</td><td>184</td><td>184</td><td>161</td><td>20</td><td>40</td><td>2</td><td>0</td><td>0</td><td>42</td><td>7</td><td>4</td><td>0</td><td>23</td><td>0</td><td>0</td><td>25</td><td>3</td><td>0</td><td>0</td><td style="">0.248</td><td>0.342</td><td>0.261</td><td>0.603</td><td>0.089</td><td>73.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.12</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14720">문상준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.25</td><td>2</td><td>-0.05</td><td>-0.20</td><td>5</td><td>5</td><td>5</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td style="">0.200</td><td>0.200</td><td>0.200</td><td>0.400</td><td>-0.011</td><td>-9.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.25</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11333">문상철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.26</td><td>112</td><td>0.15</td><td>-0.41</td><td>330</td><td>328</td><td>304</td><td>30</td><td>79</td><td>20</td><td>0</td><td>9</td><td>126</td><td>46</td><td>3</td><td>1</td><td>16</td><td>3</td><td>1</td><td>81</td><td>4</td><td>1</td><td>6</td><td style="">0.260</td><td>0.298</td><td>0.414</td><td>0.712</td><td>0.106</td><td>87.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.26</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14603">강현우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.27</td><td>53</td><td>-0.26</td><td>-0.02</td><td>111</td><td>110</td><td>103</td><td>11</td><td>20</td><td>6</td><td>0</td><td>1</td><td>29</td><td>11</td><td>0</td><td>1</td><td>6</td><td>1</td><td>0</td><td>17</td><td>3</td><td>1</td><td>0</td><td style="">0.194</td><td>0.245</td><td>0.282</td><td>0.527</td><td>0.046</td><td>38.1</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.27</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12526">이시원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.33</td><td>29</td><td>-0.35</td><td>0.02</td><td>32</td><td>31</td><td>29</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>6</td><td>0</td><td>1</td><td>0</td><td style="">0.138</td><td>0.194</td><td>0.138</td><td>0.332</td><td>-0.024</td><td>-18.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.33</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15523">류현인</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.46</td><td>17</td><td>-0.27</td><td>-0.19</td><td>24</td><td>24</td><td>23</td><td>6</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td style="">0.130</td><td>0.167</td><td>0.130</td><td>0.297</td><td>-0.042</td><td>-34.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.46</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11147">이상호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.64</td><td>63</td><td>-0.56</td><td>-0.08</td><td>60</td><td>56</td><td>54</td><td>15</td><td>8</td><td>1</td><td>0</td><td>0</td><td>9</td><td>5</td><td>2</td><td>0</td><td>2</td><td>0</td><td>0</td><td>9</td><td>2</td><td>4</td><td>0</td><td style="">0.148</td><td>0.179</td><td>0.167</td><td>0.346</td><td>-0.025</td><td>-21.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.64</td></tr>			</tbody>
		</table>""")

In [26]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10892">구자욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.26</td><td>119</td><td>4.85</td><td>0.41</td><td>515</td><td>511</td><td>453</td><td>65</td><td>152</td><td>37</td><td>1</td><td>11</td><td>224</td><td>71</td><td>12</td><td>4</td><td>53</td><td>4</td><td>2</td><td>81</td><td>5</td><td>2</td><td>3</td><td style="">0.336</td><td>0.407</td><td>0.494</td><td>0.901</td><td>0.185</td><td>154.3</td><td style="background-color:#F3F3F3; font-weight:bold;">5.26</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10232">강민호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.30</td><td>125</td><td>3.60</td><td>-0.30</td><td>495</td><td>492</td><td>434</td><td>60</td><td>126</td><td>19</td><td>0</td><td>16</td><td>193</td><td>77</td><td>6</td><td>1</td><td>49</td><td>6</td><td>4</td><td>65</td><td>17</td><td>1</td><td>5</td><td style="">0.290</td><td>0.366</td><td>0.445</td><td>0.811</td><td>0.149</td><td>123.5</td><td style="background-color:#F3F3F3; font-weight:bold;">3.30</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15034">이재현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.65</td><td>143</td><td>2.43</td><td>0.22</td><td>538</td><td>522</td><td>458</td><td>61</td><td>114</td><td>19</td><td>2</td><td>12</td><td>173</td><td>60</td><td>5</td><td>4</td><td>52</td><td>6</td><td>0</td><td>89</td><td>9</td><td>16</td><td>6</td><td style="">0.249</td><td>0.330</td><td>0.378</td><td>0.708</td><td>0.115</td><td>95.9</td><td style="background-color:#F3F3F3; font-weight:bold;">2.65</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14618">김지찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.40</td><td>99</td><td>2.91</td><td>-0.51</td><td>355</td><td>348</td><td>291</td><td>59</td><td>85</td><td>4</td><td>2</td><td>1</td><td>96</td><td>18</td><td>13</td><td>1</td><td>48</td><td>9</td><td>0</td><td>36</td><td>1</td><td>7</td><td>0</td><td style="">0.292</td><td>0.408</td><td>0.330</td><td>0.738</td><td>0.144</td><td>119.3</td><td style="background-color:#F3F3F3; font-weight:bold;">2.40</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12936">김성윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.93</td><td>101</td><td>1.44</td><td>0.49</td><td>272</td><td>268</td><td>245</td><td>40</td><td>77</td><td>4</td><td>6</td><td>2</td><td>99</td><td>28</td><td>20</td><td>4</td><td>14</td><td>4</td><td>0</td><td>35</td><td>2</td><td>4</td><td>5</td><td style="">0.314</td><td>0.354</td><td>0.404</td><td>0.758</td><td>0.130</td><td>109.0</td><td style="background-color:#F3F3F3; font-weight:bold;">1.93</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10180">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.97</td><td>19</td><td>1.01</td><td>-0.04</td><td>72</td><td>72</td><td>58</td><td>6</td><td>21</td><td>4</td><td>0</td><td>1</td><td>28</td><td>10</td><td>0</td><td>1</td><td>14</td><td>0</td><td>0</td><td>8</td><td>1</td><td>0</td><td>0</td><td style="">0.362</td><td>0.486</td><td>0.483</td><td>0.969</td><td>0.223</td><td>188.4</td><td style="background-color:#F3F3F3; font-weight:bold;">0.97</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14863">김동진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.73</td><td>44</td><td>0.31</td><td>0.41</td><td>137</td><td>134</td><td>122</td><td>14</td><td>32</td><td>7</td><td>0</td><td>0</td><td>39</td><td>8</td><td>3</td><td>0</td><td>9</td><td>1</td><td>0</td><td>26</td><td>4</td><td>3</td><td>2</td><td style="">0.262</td><td>0.313</td><td>0.320</td><td>0.633</td><td>0.088</td><td>73.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.73</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14757">피렐라</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.64</td><td>139</td><td>1.60</td><td>-0.96</td><td>605</td><td>605</td><td>557</td><td>66</td><td>159</td><td>28</td><td>1</td><td>16</td><td>237</td><td>80</td><td>6</td><td>4</td><td>42</td><td>4</td><td>5</td><td>69</td><td>20</td><td>0</td><td>2</td><td style="">0.285</td><td>0.339</td><td>0.425</td><td>0.764</td><td>0.130</td><td>107.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.64</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14867">김현준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.63</td><td>109</td><td>0.85</td><td>-0.23</td><td>479</td><td>471</td><td>433</td><td>62</td><td>119</td><td>10</td><td>6</td><td>3</td><td>150</td><td>46</td><td>5</td><td>5</td><td>30</td><td>5</td><td>0</td><td>84</td><td>5</td><td>8</td><td>3</td><td style="">0.275</td><td>0.327</td><td>0.346</td><td>0.673</td><td>0.102</td><td>85.2</td><td style="background-color:#F3F3F3; font-weight:bold;">0.63</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11344">김재성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.45</td><td>57</td><td>0.32</td><td>0.13</td><td>125</td><td>123</td><td>99</td><td>7</td><td>19</td><td>3</td><td>0</td><td>1</td><td>25</td><td>7</td><td>0</td><td>1</td><td>19</td><td>5</td><td>1</td><td>31</td><td>4</td><td>2</td><td>0</td><td style="">0.192</td><td>0.350</td><td>0.253</td><td>0.603</td><td>0.100</td><td>82.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.45</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10894">류지혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.41</td><td>66</td><td>0.41</td><td>0.00</td><td>269</td><td>261</td><td>235</td><td>35</td><td>63</td><td>5</td><td>0</td><td>2</td><td>74</td><td>28</td><td>22</td><td>0</td><td>19</td><td>3</td><td>0</td><td>30</td><td>7</td><td>8</td><td>4</td><td style="">0.268</td><td>0.326</td><td>0.315</td><td>0.641</td><td>0.092</td><td>76.7</td><td style="background-color:#F3F3F3; font-weight:bold;">0.41</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10459">김태군</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.38</td><td>49</td><td>0.18</td><td>0.20</td><td>143</td><td>139</td><td>125</td><td>7</td><td>32</td><td>4</td><td>1</td><td>1</td><td>41</td><td>18</td><td>0</td><td>0</td><td>10</td><td>4</td><td>1</td><td>11</td><td>8</td><td>3</td><td>1</td><td style="">0.256</td><td>0.329</td><td>0.328</td><td>0.657</td><td>0.099</td><td>82.2</td><td style="background-color:#F3F3F3; font-weight:bold;">0.38</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10400">오재일</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.30</td><td>106</td><td>-0.29</td><td>0.59</td><td>364</td><td>364</td><td>315</td><td>31</td><td>64</td><td>15</td><td>0</td><td>11</td><td>112</td><td>54</td><td>1</td><td>0</td><td>43</td><td>3</td><td>1</td><td>110</td><td>1</td><td>0</td><td>3</td><td style="">0.203</td><td>0.302</td><td>0.356</td><td>0.658</td><td>0.098</td><td>81.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.30</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15035">김영웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.09</td><td>55</td><td>-0.22</td><td>0.32</td><td>103</td><td>100</td><td>91</td><td>11</td><td>17</td><td>6</td><td>0</td><td>2</td><td>29</td><td>12</td><td>1</td><td>0</td><td>8</td><td>0</td><td>0</td><td>28</td><td>2</td><td>3</td><td>1</td><td style="">0.187</td><td>0.250</td><td>0.319</td><td>0.569</td><td>0.060</td><td>49.1</td><td style="background-color:#F3F3F3; font-weight:bold;">0.09</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14121">이해승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.03</td><td>9</td><td>-0.02</td><td>0.05</td><td>4</td><td>4</td><td>4</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.250</td><td>0.250</td><td>0.500</td><td>0.750</td><td>0.119</td><td>104.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.03</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10871">김태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10367">오승환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>3</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10685">김대우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10527">이승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14798">이승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15039">김서준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13244">이재익</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15499">김재상</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.02</td><td>17</td><td>-0.03</td><td>0.01</td><td>22</td><td>22</td><td>20</td><td>1</td><td>3</td><td>0</td><td>0</td><td>1</td><td>6</td><td>2</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td style="">0.150</td><td>0.227</td><td>0.300</td><td>0.527</td><td>0.043</td><td>35.1</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.02</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11169">이상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>1</td><td>-0.03</td><td>0.00</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-147.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11266">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.04</td><td>2</td><td>-0.02</td><td>-0.01</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-133.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.04</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14115">김도환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>9</td><td>-0.08</td><td>0.02</td><td>8</td><td>8</td><td>7</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">0.143</td><td>0.250</td><td>0.143</td><td>0.393</td><td>0.014</td><td>11.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13161">윤정빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>28</td><td>-0.03</td><td>-0.04</td><td>43</td><td>43</td><td>34</td><td>5</td><td>5</td><td>0</td><td>0</td><td>1</td><td>8</td><td>3</td><td>1</td><td>0</td><td>7</td><td>2</td><td>0</td><td>12</td><td>1</td><td>0</td><td>0</td><td style="">0.147</td><td>0.326</td><td>0.235</td><td>0.561</td><td>0.087</td><td>72.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15501">강준서</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>10</td><td>-0.06</td><td>-0.01</td><td>15</td><td>15</td><td>14</td><td>2</td><td>3</td><td>1</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.214</td><td>0.267</td><td>0.286</td><td>0.553</td><td>0.058</td><td>48.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11200">송준석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>7</td><td>-0.05</td><td>-0.02</td><td>8</td><td>8</td><td>8</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">0.250</td><td>0.250</td><td>0.250</td><td>0.500</td><td>0.028</td><td>24.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10640">김헌곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.20</td><td>6</td><td>-0.10</td><td>-0.10</td><td>4</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-151.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.20</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13160">이태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.21</td><td>12</td><td>-0.06</td><td>-0.15</td><td>14</td><td>14</td><td>13</td><td>1</td><td>3</td><td>1</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>0</td><td style="">0.231</td><td>0.286</td><td>0.308</td><td>0.594</td><td>0.074</td><td>59.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.21</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12548">김동엽</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.22</td><td>69</td><td>0.02</td><td>-0.25</td><td>182</td><td>182</td><td>165</td><td>20</td><td>42</td><td>7</td><td>0</td><td>5</td><td>64</td><td>18</td><td>1</td><td>1</td><td>13</td><td>2</td><td>0</td><td>29</td><td>8</td><td>0</td><td>2</td><td style="">0.255</td><td>0.313</td><td>0.388</td><td>0.701</td><td>0.108</td><td>88.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.22</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12562">이성규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.23</td><td>109</td><td>-0.49</td><td>0.26</td><td>162</td><td>158</td><td>145</td><td>23</td><td>30</td><td>10</td><td>1</td><td>1</td><td>45</td><td>18</td><td>4</td><td>3</td><td>8</td><td>3</td><td>0</td><td>42</td><td>4</td><td>4</td><td>2</td><td style="">0.207</td><td>0.259</td><td>0.310</td><td>0.569</td><td>0.062</td><td>51.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.23</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14117">이병헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.30</td><td>23</td><td>-0.24</td><td>-0.06</td><td>33</td><td>32</td><td>28</td><td>3</td><td>4</td><td>0</td><td>0</td><td>0</td><td>4</td><td>2</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>11</td><td>0</td><td>1</td><td>1</td><td style="">0.143</td><td>0.219</td><td>0.143</td><td>0.362</td><td>-0.007</td><td>-5.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.30</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15040">조민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.32</td><td>15</td><td>-0.35</td><td>0.03</td><td>29</td><td>29</td><td>29</td><td>1</td><td>6</td><td>2</td><td>0</td><td>0</td><td>8</td><td>5</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>6</td><td>1</td><td>0</td><td>0</td><td style="">0.207</td><td>0.207</td><td>0.276</td><td>0.483</td><td>0.019</td><td>15.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.32</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12988">안주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.34</td><td>53</td><td>0.03</td><td>-0.37</td><td>91</td><td>90</td><td>79</td><td>12</td><td>19</td><td>2</td><td>0</td><td>1</td><td>24</td><td>10</td><td>0</td><td>0</td><td>10</td><td>0</td><td>0</td><td>20</td><td>3</td><td>1</td><td>1</td><td style="">0.241</td><td>0.322</td><td>0.304</td><td>0.626</td><td>0.090</td><td>74.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.34</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11255">강한울</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.37</td><td>72</td><td>-0.66</td><td>0.29</td><td>240</td><td>234</td><td>212</td><td>30</td><td>46</td><td>7</td><td>2</td><td>0</td><td>57</td><td>10</td><td>1</td><td>3</td><td>20</td><td>0</td><td>1</td><td>54</td><td>4</td><td>6</td><td>2</td><td style="">0.217</td><td>0.282</td><td>0.269</td><td>0.551</td><td>0.059</td><td>48.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.37</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13164">공민규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.39</td><td>22</td><td>-0.22</td><td>-0.16</td><td>33</td><td>33</td><td>31</td><td>0</td><td>6</td><td>1</td><td>1</td><td>0</td><td>9</td><td>2</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>13</td><td>1</td><td>0</td><td>0</td><td style="">0.194</td><td>0.242</td><td>0.290</td><td>0.532</td><td>0.047</td><td>39.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.39</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15042">김상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.39</td><td>8</td><td>-0.15</td><td>-0.24</td><td>13</td><td>13</td><td>12</td><td>3</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td style="">0.083</td><td>0.154</td><td>0.083</td><td>0.237</td><td>-0.056</td><td>-45.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.39</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13240">김호재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.44</td><td>75</td><td>-0.47</td><td>0.03</td><td>127</td><td>122</td><td>116</td><td>6</td><td>25</td><td>7</td><td>0</td><td>0</td><td>32</td><td>9</td><td>2</td><td>0</td><td>6</td><td>0</td><td>0</td><td>17</td><td>4</td><td>5</td><td>0</td><td style="">0.216</td><td>0.254</td><td>0.276</td><td>0.530</td><td>0.046</td><td>38.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.44</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11336">김태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.46</td><td>11</td><td>-0.45</td><td>-0.01</td><td>22</td><td>21</td><td>21</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>9</td><td>1</td><td>1</td><td>0</td><td style="">0.095</td><td>0.095</td><td>0.143</td><td>0.238</td><td>-0.075</td><td>-61.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.46</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15503">류승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.50</td><td>24</td><td>-0.25</td><td>-0.25</td><td>57</td><td>55</td><td>52</td><td>5</td><td>11</td><td>3</td><td>0</td><td>0</td><td>14</td><td>5</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>19</td><td>0</td><td>2</td><td>0</td><td style="">0.212</td><td>0.255</td><td>0.269</td><td>0.524</td><td>0.046</td><td>37.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.50</td></tr>			</tbody>
		</table>""")

In [27]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10106">최정</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.25</td><td>128</td><td>5.51</td><td>-0.26</td><td>552</td><td>547</td><td>471</td><td>94</td><td>140</td><td>31</td><td>0</td><td>29</td><td>258</td><td>87</td><td>7</td><td>3</td><td>59</td><td>15</td><td>6</td><td>87</td><td>12</td><td>1</td><td>6</td><td style="">0.297</td><td>0.388</td><td>0.548</td><td>0.936</td><td>0.189</td><td>157.6</td><td style="background-color:#F3F3F3; font-weight:bold;">5.25</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15530">에레디아</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.82</td><td>122</td><td>3.61</td><td>0.21</td><td>523</td><td>519</td><td>473</td><td>76</td><td>153</td><td>29</td><td>0</td><td>12</td><td>218</td><td>76</td><td>12</td><td>8</td><td>39</td><td>9</td><td>4</td><td>75</td><td>13</td><td>1</td><td>1</td><td style="">0.323</td><td>0.385</td><td>0.461</td><td>0.846</td><td>0.163</td><td>135.9</td><td style="background-color:#F3F3F3; font-weight:bold;">3.82</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12922">박성한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.54</td><td>128</td><td>3.17</td><td>0.37</td><td>529</td><td>521</td><td>459</td><td>53</td><td>122</td><td>19</td><td>0</td><td>9</td><td>168</td><td>47</td><td>4</td><td>1</td><td>58</td><td>1</td><td>1</td><td>56</td><td>7</td><td>7</td><td>4</td><td style="">0.266</td><td>0.347</td><td>0.366</td><td>0.713</td><td>0.120</td><td>99.7</td><td style="background-color:#F3F3F3; font-weight:bold;">3.54</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14147">하재훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.44</td><td>77</td><td>2.12</td><td>0.33</td><td>229</td><td>226</td><td>201</td><td>35</td><td>61</td><td>10</td><td>1</td><td>7</td><td>94</td><td>35</td><td>11</td><td>0</td><td>19</td><td>5</td><td>1</td><td>53</td><td>0</td><td>2</td><td>2</td><td style="">0.303</td><td>0.374</td><td>0.468</td><td>0.842</td><td>0.161</td><td>134.0</td><td style="background-color:#F3F3F3; font-weight:bold;">2.44</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14888">추신수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.72</td><td>112</td><td>1.94</td><td>-0.21</td><td>462</td><td>462</td><td>382</td><td>65</td><td>97</td><td>17</td><td>1</td><td>12</td><td>152</td><td>41</td><td>6</td><td>4</td><td>65</td><td>13</td><td>1</td><td>79</td><td>8</td><td>0</td><td>2</td><td style="">0.254</td><td>0.379</td><td>0.398</td><td>0.777</td><td>0.149</td><td>124.2</td><td style="background-color:#F3F3F3; font-weight:bold;">1.72</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10707">김민식</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.33</td><td>122</td><td>0.84</td><td>0.49</td><td>318</td><td>300</td><td>266</td><td>28</td><td>58</td><td>9</td><td>1</td><td>5</td><td>84</td><td>34</td><td>0</td><td>0</td><td>31</td><td>2</td><td>1</td><td>57</td><td>6</td><td>17</td><td>2</td><td style="">0.218</td><td>0.302</td><td>0.316</td><td>0.618</td><td>0.085</td><td>70.5</td><td style="background-color:#F3F3F3; font-weight:bold;">1.33</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14587">최지훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.26</td><td>117</td><td>1.61</td><td>-0.36</td><td>503</td><td>495</td><td>462</td><td>65</td><td>124</td><td>19</td><td>8</td><td>2</td><td>165</td><td>30</td><td>21</td><td>2</td><td>29</td><td>3</td><td>0</td><td>50</td><td>3</td><td>8</td><td>1</td><td style="">0.268</td><td>0.315</td><td>0.357</td><td>0.672</td><td>0.101</td><td>83.4</td><td style="background-color:#F3F3F3; font-weight:bold;">1.26</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10636">김성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.19</td><td>112</td><td>1.06</td><td>0.14</td><td>354</td><td>341</td><td>310</td><td>35</td><td>83</td><td>14</td><td>0</td><td>1</td><td>100</td><td>27</td><td>4</td><td>1</td><td>29</td><td>0</td><td>1</td><td>36</td><td>6</td><td>13</td><td>2</td><td style="">0.268</td><td>0.328</td><td>0.323</td><td>0.651</td><td>0.096</td><td>79.6</td><td style="background-color:#F3F3F3; font-weight:bold;">1.19</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10182">최주환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.97</td><td>134</td><td>1.53</td><td>-0.56</td><td>478</td><td>474</td><td>426</td><td>48</td><td>100</td><td>24</td><td>0</td><td>20</td><td>184</td><td>63</td><td>0</td><td>0</td><td>44</td><td>4</td><td>4</td><td>94</td><td>6</td><td>1</td><td>3</td><td style="">0.235</td><td>0.310</td><td>0.432</td><td>0.742</td><td>0.120</td><td>99.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.97</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10815">한유섬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.82</td><td>109</td><td>1.44</td><td>-0.62</td><td>388</td><td>386</td><td>333</td><td>29</td><td>91</td><td>15</td><td>2</td><td>7</td><td>131</td><td>55</td><td>2</td><td>1</td><td>34</td><td>12</td><td>1</td><td>81</td><td>3</td><td>2</td><td>7</td><td style="">0.273</td><td>0.355</td><td>0.393</td><td>0.748</td><td>0.132</td><td>109.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.82</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13128">최준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.36</td><td>38</td><td>0.05</td><td>0.31</td><td>69</td><td>69</td><td>60</td><td>5</td><td>16</td><td>1</td><td>0</td><td>0</td><td>17</td><td>6</td><td>0</td><td>1</td><td>8</td><td>0</td><td>0</td><td>10</td><td>3</td><td>0</td><td>1</td><td style="">0.267</td><td>0.348</td><td>0.283</td><td>0.631</td><td>0.096</td><td>80.1</td><td style="background-color:#F3F3F3; font-weight:bold;">0.36</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10249">오태곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.33</td><td>123</td><td>0.41</td><td>-0.07</td><td>305</td><td>297</td><td>272</td><td>37</td><td>65</td><td>14</td><td>1</td><td>7</td><td>102</td><td>28</td><td>20</td><td>1</td><td>18</td><td>4</td><td>0</td><td>67</td><td>6</td><td>8</td><td>3</td><td style="">0.239</td><td>0.293</td><td>0.375</td><td>0.668</td><td>0.095</td><td>79.4</td><td style="background-color:#F3F3F3; font-weight:bold;">0.33</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13195">최상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.16</td><td>51</td><td>-0.07</td><td>0.22</td><td>41</td><td>39</td><td>34</td><td>5</td><td>8</td><td>0</td><td>0</td><td>0</td><td>8</td><td>3</td><td>2</td><td>2</td><td>4</td><td>0</td><td>0</td><td>7</td><td>0</td><td>2</td><td>1</td><td style="">0.235</td><td>0.308</td><td>0.235</td><td>0.543</td><td>0.061</td><td>51.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.16</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10108">김강민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.12</td><td>70</td><td>0.20</td><td>-0.09</td><td>166</td><td>163</td><td>137</td><td>20</td><td>31</td><td>3</td><td>0</td><td>2</td><td>40</td><td>7</td><td>2</td><td>1</td><td>23</td><td>1</td><td>1</td><td>38</td><td>2</td><td>2</td><td>3</td><td style="">0.226</td><td>0.335</td><td>0.292</td><td>0.627</td><td>0.095</td><td>78.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.12</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11148">강진성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.10</td><td>55</td><td>0.03</td><td>0.07</td><td>142</td><td>141</td><td>131</td><td>10</td><td>34</td><td>6</td><td>1</td><td>3</td><td>51</td><td>17</td><td>0</td><td>0</td><td>6</td><td>3</td><td>0</td><td>20</td><td>2</td><td>1</td><td>1</td><td style="">0.260</td><td>0.305</td><td>0.389</td><td>0.694</td><td>0.105</td><td>87.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.10</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10795">임준섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11242">이건욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10203">노경은</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10784">서진용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>3</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13126">최민준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10783">문승원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10124">고효준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14145">백승건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14153">채현우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14807">고명준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.02</td><td>2</td><td>-0.11</td><td>0.09</td><td>4</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-132.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.02</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15463">김정민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>8</td><td>0.03</td><td>-0.06</td><td>2</td><td>2</td><td>2</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.500</td><td>0.500</td><td>0.500</td><td>1.000</td><td>0.222</td><td>180.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12613">안상현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.04</td><td>58</td><td>0.08</td><td>-0.11</td><td>66</td><td>63</td><td>58</td><td>10</td><td>14</td><td>3</td><td>0</td><td>0</td><td>17</td><td>2</td><td>3</td><td>1</td><td>5</td><td>0</td><td>0</td><td>15</td><td>1</td><td>3</td><td>0</td><td style="">0.241</td><td>0.302</td><td>0.293</td><td>0.595</td><td>0.076</td><td>63.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.04</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12622">김찬형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.04</td><td>36</td><td>0.01</td><td>-0.05</td><td>53</td><td>51</td><td>48</td><td>6</td><td>11</td><td>3</td><td>0</td><td>1</td><td>17</td><td>5</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>10</td><td>1</td><td>2</td><td>0</td><td style="">0.229</td><td>0.275</td><td>0.354</td><td>0.629</td><td>0.081</td><td>67.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.04</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14586">류효승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.06</td><td>3</td><td>-0.06</td><td>0.00</td><td>4</td><td>4</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td style="">0.000</td><td>0.250</td><td>0.000</td><td>0.250</td><td>0.010</td><td>8.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.06</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15465">김건웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>1</td><td>-0.08</td><td>0.01</td><td>3</td><td>3</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-135.1</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10810">최항</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.30</td><td>21</td><td>0.07</td><td>-0.37</td><td>35</td><td>34</td><td>28</td><td>3</td><td>8</td><td>1</td><td>0</td><td>1</td><td>12</td><td>6</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>12</td><td>1</td><td>1</td><td>1</td><td style="">0.286</td><td>0.382</td><td>0.429</td><td>0.811</td><td>0.153</td><td>129.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.30</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14699">전의산</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.30</td><td>56</td><td>-0.25</td><td>-0.05</td><td>153</td><td>153</td><td>134</td><td>11</td><td>27</td><td>6</td><td>0</td><td>4</td><td>45</td><td>21</td><td>0</td><td>2</td><td>15</td><td>3</td><td>0</td><td>40</td><td>1</td><td>0</td><td>1</td><td style="">0.201</td><td>0.294</td><td>0.336</td><td>0.630</td><td>0.089</td><td>74.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.30</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11108">이흥련</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.33</td><td>16</td><td>-0.09</td><td>-0.24</td><td>17</td><td>16</td><td>14</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td><td>4</td><td>2</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>6</td><td>0</td><td>1</td><td>0</td><td style="">0.071</td><td>0.188</td><td>0.286</td><td>0.474</td><td>0.024</td><td>21.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.33</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14806">조형우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.37</td><td>62</td><td>-0.33</td><td>-0.05</td><td>133</td><td>129</td><td>119</td><td>9</td><td>22</td><td>4</td><td>1</td><td>2</td><td>34</td><td>12</td><td>0</td><td>0</td><td>8</td><td>1</td><td>0</td><td>25</td><td>2</td><td>4</td><td>1</td><td style="">0.185</td><td>0.240</td><td>0.286</td><td>0.526</td><td>0.044</td><td>36.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.37</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13194">이정범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.43</td><td>15</td><td>-0.38</td><td>-0.05</td><td>33</td><td>33</td><td>29</td><td>2</td><td>5</td><td>0</td><td>0</td><td>0</td><td>5</td><td>4</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>6</td><td>1</td><td>0</td><td>2</td><td style="">0.172</td><td>0.212</td><td>0.172</td><td>0.384</td><td>-0.009</td><td>-7.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.43</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14151">최경모</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.49</td><td>28</td><td>-0.23</td><td>-0.26</td><td>20</td><td>20</td><td>20</td><td>6</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3</td><td>1</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td style="">0.150</td><td>0.150</td><td>0.150</td><td>0.300</td><td>-0.050</td><td>-41.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.49</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10082">이재원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.77</td><td>27</td><td>-0.71</td><td>-0.06</td><td>48</td><td>47</td><td>44</td><td>3</td><td>4</td><td>1</td><td>0</td><td>0</td><td>5</td><td>2</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>8</td><td>4</td><td>1</td><td>1</td><td style="">0.091</td><td>0.128</td><td>0.114</td><td>0.242</td><td>-0.065</td><td>-53.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.77</td></tr>			</tbody>
		</table>""")

In [28]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11137">박민우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.39</td><td>124</td><td>4.03</td><td>0.36</td><td>509</td><td>501</td><td>452</td><td>76</td><td>143</td><td>20</td><td>7</td><td>2</td><td>183</td><td>46</td><td>26</td><td>7</td><td>40</td><td>9</td><td>3</td><td>57</td><td>13</td><td>5</td><td>3</td><td style="">0.316</td><td>0.381</td><td>0.405</td><td>0.786</td><td>0.146</td><td>123.4</td><td style="background-color:#F3F3F3; font-weight:bold;">4.39</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10261">손아섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.32</td><td>140</td><td>4.11</td><td>0.21</td><td>609</td><td>608</td><td>551</td><td>97</td><td>187</td><td>36</td><td>3</td><td>5</td><td>244</td><td>65</td><td>14</td><td>3</td><td>50</td><td>2</td><td>2</td><td>67</td><td>10</td><td>1</td><td>5</td><td style="">0.339</td><td>0.393</td><td>0.443</td><td>0.836</td><td>0.162</td><td>137.1</td><td style="background-color:#F3F3F3; font-weight:bold;">4.32</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10189">박건우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.93</td><td>130</td><td>4.17</td><td>-0.24</td><td>533</td><td>532</td><td>458</td><td>70</td><td>146</td><td>34</td><td>2</td><td>12</td><td>220</td><td>85</td><td>7</td><td>5</td><td>56</td><td>9</td><td>0</td><td>71</td><td>14</td><td>1</td><td>9</td><td style="">0.319</td><td>0.397</td><td>0.480</td><td>0.877</td><td>0.176</td><td>149.2</td><td style="background-color:#F3F3F3; font-weight:bold;">3.93</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15537">마틴</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.44</td><td>118</td><td>3.39</td><td>0.04</td><td>503</td><td>502</td><td>435</td><td>55</td><td>123</td><td>20</td><td>2</td><td>17</td><td>198</td><td>90</td><td>15</td><td>3</td><td>57</td><td>1</td><td>2</td><td>107</td><td>8</td><td>0</td><td>10</td><td style="">0.283</td><td>0.360</td><td>0.455</td><td>0.815</td><td>0.149</td><td>125.5</td><td style="background-color:#F3F3F3; font-weight:bold;">3.44</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14765">김주원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.23</td><td>127</td><td>2.30</td><td>-0.07</td><td>474</td><td>466</td><td>403</td><td>56</td><td>94</td><td>9</td><td>2</td><td>10</td><td>137</td><td>54</td><td>15</td><td>3</td><td>44</td><td>15</td><td>1</td><td>106</td><td>6</td><td>8</td><td>4</td><td style="">0.233</td><td>0.328</td><td>0.340</td><td>0.668</td><td>0.106</td><td>89.8</td><td style="background-color:#F3F3F3; font-weight:bold;">2.23</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14220">서호철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.23</td><td>114</td><td>1.50</td><td>0.73</td><td>435</td><td>429</td><td>397</td><td>50</td><td>114</td><td>17</td><td>3</td><td>5</td><td>152</td><td>41</td><td>4</td><td>5</td><td>20</td><td>8</td><td>0</td><td>51</td><td>9</td><td>6</td><td>4</td><td style="">0.287</td><td>0.331</td><td>0.383</td><td>0.714</td><td>0.115</td><td>97.1</td><td style="background-color:#F3F3F3; font-weight:bold;">2.23</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11172">권희동</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.00</td><td>96</td><td>2.26</td><td>-0.27</td><td>373</td><td>369</td><td>309</td><td>33</td><td>88</td><td>16</td><td>0</td><td>7</td><td>125</td><td>63</td><td>2</td><td>0</td><td>49</td><td>6</td><td>0</td><td>50</td><td>4</td><td>4</td><td>5</td><td style="">0.285</td><td>0.388</td><td>0.405</td><td>0.793</td><td>0.153</td><td>128.2</td><td style="background-color:#F3F3F3; font-weight:bold;">2.00</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12560">도태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.77</td><td>117</td><td>1.16</td><td>0.61</td><td>302</td><td>294</td><td>239</td><td>41</td><td>56</td><td>6</td><td>0</td><td>5</td><td>77</td><td>23</td><td>2</td><td>1</td><td>38</td><td>17</td><td>1</td><td>48</td><td>8</td><td>7</td><td>1</td><td style="">0.234</td><td>0.376</td><td>0.322</td><td>0.698</td><td>0.130</td><td>110.6</td><td style="background-color:#F3F3F3; font-weight:bold;">1.77</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10891">박세혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.18</td><td>88</td><td>1.05</td><td>0.13</td><td>283</td><td>277</td><td>242</td><td>35</td><td>51</td><td>9</td><td>3</td><td>6</td><td>84</td><td>32</td><td>1</td><td>1</td><td>30</td><td>4</td><td>0</td><td>43</td><td>3</td><td>6</td><td>1</td><td style="">0.211</td><td>0.307</td><td>0.347</td><td>0.654</td><td>0.099</td><td>83.5</td><td style="background-color:#F3F3F3; font-weight:bold;">1.18</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13081">김형준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.73</td><td>26</td><td>0.57</td><td>0.16</td><td>82</td><td>81</td><td>72</td><td>10</td><td>17</td><td>2</td><td>0</td><td>6</td><td>37</td><td>13</td><td>0</td><td>0</td><td>8</td><td>1</td><td>0</td><td>24</td><td>3</td><td>1</td><td>0</td><td style="">0.236</td><td>0.321</td><td>0.514</td><td>0.835</td><td>0.150</td><td>127.5</td><td style="background-color:#F3F3F3; font-weight:bold;">0.73</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11153">김성욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.42</td><td>93</td><td>0.36</td><td>0.06</td><td>204</td><td>201</td><td>179</td><td>28</td><td>40</td><td>10</td><td>0</td><td>6</td><td>68</td><td>16</td><td>6</td><td>1</td><td>16</td><td>5</td><td>0</td><td>63</td><td>7</td><td>3</td><td>1</td><td style="">0.223</td><td>0.303</td><td>0.380</td><td>0.683</td><td>0.105</td><td>89.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.42</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14221">최정원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.35</td><td>39</td><td>0.32</td><td>0.03</td><td>56</td><td>54</td><td>50</td><td>12</td><td>13</td><td>3</td><td>2</td><td>0</td><td>20</td><td>5</td><td>4</td><td>1</td><td>1</td><td>3</td><td>0</td><td>13</td><td>1</td><td>2</td><td>0</td><td style="">0.260</td><td>0.315</td><td>0.400</td><td>0.715</td><td>0.119</td><td>100.0</td><td style="background-color:#F3F3F3; font-weight:bold;">0.35</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15451">박한결</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.27</td><td>12</td><td>0.24</td><td>0.03</td><td>18</td><td>18</td><td>15</td><td>3</td><td>5</td><td>1</td><td>0</td><td>1</td><td>9</td><td>5</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>0</td><td style="">0.333</td><td>0.444</td><td>0.600</td><td>1.044</td><td>0.233</td><td>200.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.27</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11246">박대온</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.22</td><td>25</td><td>0.29</td><td>-0.07</td><td>33</td><td>33</td><td>28</td><td>6</td><td>8</td><td>3</td><td>0</td><td>0</td><td>11</td><td>3</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>8</td><td>0</td><td>0</td><td>1</td><td style="">0.286</td><td>0.364</td><td>0.393</td><td>0.757</td><td>0.137</td><td>115.5</td><td style="background-color:#F3F3F3; font-weight:bold;">0.22</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11135">윤형준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.07</td><td>82</td><td>-0.22</td><td>0.29</td><td>236</td><td>234</td><td>218</td><td>17</td><td>55</td><td>12</td><td>1</td><td>5</td><td>84</td><td>27</td><td>1</td><td>1</td><td>10</td><td>3</td><td>0</td><td>58</td><td>6</td><td>2</td><td>3</td><td style="">0.252</td><td>0.291</td><td>0.385</td><td>0.676</td><td>0.096</td><td>81.1</td><td style="background-color:#F3F3F3; font-weight:bold;">0.07</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13261">천재환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.04</td><td>78</td><td>-0.17</td><td>0.20</td><td>179</td><td>177</td><td>163</td><td>12</td><td>39</td><td>7</td><td>1</td><td>2</td><td>54</td><td>17</td><td>2</td><td>3</td><td>8</td><td>4</td><td>0</td><td>44</td><td>5</td><td>2</td><td>2</td><td style="">0.239</td><td>0.288</td><td>0.331</td><td>0.619</td><td>0.080</td><td>68.7</td><td style="background-color:#F3F3F3; font-weight:bold;">0.04</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14661">박영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.03</td><td>41</td><td>-0.14</td><td>0.17</td><td>17</td><td>15</td><td>14</td><td>11</td><td>1</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>4</td><td>2</td><td>1</td><td>0</td><td>0</td><td>6</td><td>0</td><td>2</td><td>0</td><td style="">0.071</td><td>0.133</td><td>0.143</td><td>0.276</td><td>-0.046</td><td>-38.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.03</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10217">이용찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14764">한재승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11355">류진욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14158">배민서</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>0</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13080">김시훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14767">오장한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>3</td><td>-0.02</td><td>0.01</td><td>8</td><td>8</td><td>7</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td style="">0.143</td><td>0.250</td><td>0.143</td><td>0.393</td><td>0.014</td><td>11.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14156">전사민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>1</td><td>-0.03</td><td>0.00</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-140.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14877">조현진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.11</td><td>10</td><td>-0.06</td><td>-0.05</td><td>5</td><td>5</td><td>5</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td style="">0.200</td><td>0.200</td><td>0.200</td><td>0.400</td><td>-0.011</td><td>-9.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.11</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13087">최보성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.12</td><td>12</td><td>0.01</td><td>-0.12</td><td>21</td><td>21</td><td>19</td><td>2</td><td>5</td><td>0</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td style="">0.263</td><td>0.333</td><td>0.263</td><td>0.596</td><td>0.082</td><td>68.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.12</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13082">오영수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.18</td><td>70</td><td>-0.40</td><td>0.22</td><td>238</td><td>232</td><td>208</td><td>21</td><td>49</td><td>9</td><td>1</td><td>4</td><td>72</td><td>24</td><td>3</td><td>3</td><td>17</td><td>5</td><td>1</td><td>55</td><td>5</td><td>5</td><td>3</td><td style="">0.236</td><td>0.305</td><td>0.346</td><td>0.651</td><td>0.093</td><td>78.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.18</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11329">안중열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.20</td><td>77</td><td>0.17</td><td>-0.37</td><td>177</td><td>174</td><td>154</td><td>15</td><td>30</td><td>6</td><td>0</td><td>4</td><td>48</td><td>17</td><td>0</td><td>0</td><td>16</td><td>2</td><td>0</td><td>45</td><td>6</td><td>3</td><td>2</td><td style="">0.195</td><td>0.276</td><td>0.312</td><td>0.588</td><td>0.071</td><td>60.5</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.20</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12903">김수윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.23</td><td>16</td><td>-0.07</td><td>-0.16</td><td>15</td><td>15</td><td>14</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td style="">0.214</td><td>0.267</td><td>0.214</td><td>0.481</td><td>0.033</td><td>28.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.23</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13250">한석현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.27</td><td>27</td><td>-0.41</td><td>0.15</td><td>66</td><td>64</td><td>60</td><td>5</td><td>12</td><td>1</td><td>0</td><td>0</td><td>13</td><td>2</td><td>2</td><td>1</td><td>4</td><td>0</td><td>0</td><td>20</td><td>2</td><td>2</td><td>0</td><td style="">0.200</td><td>0.250</td><td>0.217</td><td>0.467</td><td>0.026</td><td>22.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.27</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14219">박주찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.31</td><td>5</td><td>-0.19</td><td>-0.12</td><td>14</td><td>14</td><td>14</td><td>1</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.143</td><td>0.143</td><td>0.143</td><td>0.286</td><td>-0.056</td><td>-49.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.31</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14766">오태양</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.41</td><td>21</td><td>-0.22</td><td>-0.19</td><td>3</td><td>3</td><td>3</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-141.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.41</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14716">김한별</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.43</td><td>79</td><td>-0.52</td><td>0.09</td><td>105</td><td>103</td><td>97</td><td>8</td><td>21</td><td>0</td><td>1</td><td>0</td><td>23</td><td>4</td><td>0</td><td>3</td><td>4</td><td>2</td><td>0</td><td>23</td><td>6</td><td>2</td><td>0</td><td style="">0.216</td><td>0.262</td><td>0.237</td><td>0.499</td><td>0.038</td><td>32.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.43</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10322">박석민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.53</td><td>30</td><td>-0.16</td><td>-0.37</td><td>107</td><td>106</td><td>88</td><td>9</td><td>17</td><td>1</td><td>0</td><td>1</td><td>21</td><td>8</td><td>0</td><td>0</td><td>14</td><td>3</td><td>0</td><td>22</td><td>4</td><td>1</td><td>1</td><td style="">0.193</td><td>0.321</td><td>0.239</td><td>0.560</td><td>0.078</td><td>66.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.53</td></tr>			</tbody>
		</table>""")

In [29]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10165">양의지</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.99</td><td>129</td><td>5.55</td><td>0.44</td><td>510</td><td>502</td><td>439</td><td>56</td><td>134</td><td>23</td><td>0</td><td>17</td><td>208</td><td>68</td><td>8</td><td>0</td><td>57</td><td>11</td><td>8</td><td>56</td><td>20</td><td>0</td><td>3</td><td style="">0.305</td><td>0.396</td><td>0.474</td><td>0.870</td><td>0.172</td><td>151.8</td><td style="background-color:#F3F3F3; font-weight:bold;">5.99</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10195">정수빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.26</td><td>137</td><td>3.80</td><td>0.47</td><td>583</td><td>571</td><td>498</td><td>75</td><td>143</td><td>14</td><td>11</td><td>2</td><td>185</td><td>33</td><td>39</td><td>8</td><td>64</td><td>7</td><td>1</td><td>63</td><td>2</td><td>12</td><td>2</td><td style="">0.287</td><td>0.375</td><td>0.371</td><td>0.746</td><td>0.137</td><td>121.2</td><td style="background-color:#F3F3F3; font-weight:bold;">4.26</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10174">김재호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.87</td><td>91</td><td>2.56</td><td>0.32</td><td>302</td><td>287</td><td>247</td><td>32</td><td>70</td><td>13</td><td>0</td><td>3</td><td>92</td><td>29</td><td>4</td><td>0</td><td>30</td><td>8</td><td>2</td><td>24</td><td>11</td><td>15</td><td>2</td><td style="">0.283</td><td>0.376</td><td>0.372</td><td>0.748</td><td>0.137</td><td>123.0</td><td style="background-color:#F3F3F3; font-weight:bold;">2.87</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11213">양석환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.83</td><td>140</td><td>2.42</td><td>0.41</td><td>582</td><td>579</td><td>524</td><td>73</td><td>147</td><td>28</td><td>0</td><td>21</td><td>238</td><td>89</td><td>4</td><td>0</td><td>41</td><td>6</td><td>3</td><td>133</td><td>9</td><td>0</td><td>11</td><td style="">0.281</td><td>0.333</td><td>0.454</td><td>0.787</td><td>0.135</td><td>119.4</td><td style="background-color:#F3F3F3; font-weight:bold;">2.83</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15539">로하스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.51</td><td>122</td><td>3.27</td><td>-0.76</td><td>464</td><td>463</td><td>403</td><td>52</td><td>102</td><td>24</td><td>4</td><td>19</td><td>191</td><td>65</td><td>0</td><td>1</td><td>55</td><td>3</td><td>2</td><td>68</td><td>5</td><td>0</td><td>3</td><td style="">0.253</td><td>0.345</td><td>0.474</td><td>0.819</td><td>0.151</td><td>133.5</td><td style="background-color:#F3F3F3; font-weight:bold;">2.51</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10184">허경민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.07</td><td>130</td><td>1.57</td><td>0.50</td><td>475</td><td>472</td><td>429</td><td>44</td><td>115</td><td>23</td><td>1</td><td>7</td><td>161</td><td>48</td><td>9</td><td>3</td><td>35</td><td>6</td><td>3</td><td>26</td><td>6</td><td>0</td><td>5</td><td style="">0.268</td><td>0.328</td><td>0.375</td><td>0.703</td><td>0.111</td><td>98.5</td><td style="background-color:#F3F3F3; font-weight:bold;">2.07</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11087">강승호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.49</td><td>127</td><td>1.42</td><td>0.07</td><td>459</td><td>455</td><td>419</td><td>51</td><td>111</td><td>18</td><td>6</td><td>7</td><td>162</td><td>59</td><td>13</td><td>6</td><td>27</td><td>6</td><td>0</td><td>110</td><td>12</td><td>4</td><td>3</td><td style="">0.265</td><td>0.316</td><td>0.387</td><td>0.703</td><td>0.110</td><td>98.3</td><td style="background-color:#F3F3F3; font-weight:bold;">1.49</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12522">박준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.34</td><td>51</td><td>0.70</td><td>0.64</td><td>138</td><td>137</td><td>127</td><td>16</td><td>29</td><td>8</td><td>2</td><td>4</td><td>53</td><td>17</td><td>2</td><td>1</td><td>9</td><td>2</td><td>1</td><td>53</td><td>0</td><td>0</td><td>0</td><td style="">0.228</td><td>0.290</td><td>0.417</td><td>0.707</td><td>0.108</td><td>96.3</td><td style="background-color:#F3F3F3; font-weight:bold;">1.34</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12894">이유찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.85</td><td>104</td><td>0.55</td><td>0.30</td><td>239</td><td>234</td><td>210</td><td>31</td><td>51</td><td>7</td><td>2</td><td>1</td><td>65</td><td>16</td><td>12</td><td>5</td><td>20</td><td>3</td><td>0</td><td>51</td><td>0</td><td>5</td><td>1</td><td style="">0.243</td><td>0.316</td><td>0.310</td><td>0.626</td><td>0.090</td><td>79.4</td><td style="background-color:#F3F3F3; font-weight:bold;">0.85</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10643">김재환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>DH</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.44</td><td>132</td><td>0.80</td><td>-0.36</td><td>484</td><td>481</td><td>405</td><td>40</td><td>89</td><td>15</td><td>0</td><td>10</td><td>134</td><td>46</td><td>3</td><td>1</td><td>72</td><td>5</td><td>4</td><td>100</td><td>8</td><td>0</td><td>2</td><td style="">0.220</td><td>0.343</td><td>0.331</td><td>0.674</td><td>0.111</td><td>98.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.44</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11098">김인태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.36</td><td>47</td><td>0.41</td><td>-0.05</td><td>115</td><td>114</td><td>98</td><td>8</td><td>25</td><td>5</td><td>0</td><td>1</td><td>33</td><td>14</td><td>2</td><td>1</td><td>15</td><td>1</td><td>0</td><td>26</td><td>1</td><td>1</td><td>0</td><td style="">0.255</td><td>0.360</td><td>0.337</td><td>0.697</td><td>0.122</td><td>109.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.36</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14738">양찬열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.12</td><td>44</td><td>-0.03</td><td>0.15</td><td>99</td><td>99</td><td>88</td><td>15</td><td>21</td><td>2</td><td>2</td><td>0</td><td>27</td><td>6</td><td>3</td><td>2</td><td>9</td><td>1</td><td>0</td><td>23</td><td>1</td><td>0</td><td>1</td><td style="">0.239</td><td>0.313</td><td>0.307</td><td>0.620</td><td>0.087</td><td>78.0</td><td style="background-color:#F3F3F3; font-weight:bold;">0.12</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14771">안재석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.10</td><td>27</td><td>-0.11</td><td>0.21</td><td>68</td><td>68</td><td>64</td><td>8</td><td>12</td><td>2</td><td>1</td><td>1</td><td>19</td><td>5</td><td>2</td><td>0</td><td>3</td><td>0</td><td>0</td><td>12</td><td>0</td><td>0</td><td>1</td><td style="">0.188</td><td>0.221</td><td>0.297</td><td>0.518</td><td>0.035</td><td>30.9</td><td style="background-color:#F3F3F3; font-weight:bold;">0.10</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11148">강진성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.02</td><td>3</td><td>-0.02</td><td>0.04</td><td>3</td><td>3</td><td>3</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style="">0.333</td><td>0.333</td><td>0.333</td><td>0.666</td><td>0.093</td><td>82.3</td><td style="background-color:#F3F3F3; font-weight:bold;">0.02</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12892">박유연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.01</td><td>10</td><td>0.07</td><td>-0.06</td><td>16</td><td>15</td><td>15</td><td>3</td><td>4</td><td>2</td><td>0</td><td>0</td><td>6</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>1</td><td>0</td><td style="">0.267</td><td>0.267</td><td>0.400</td><td>0.667</td><td>0.090</td><td>79.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.01</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10696">홍건희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>4</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11159">이형범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13072">김민규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>0</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12850">박치국</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13071">정철원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>3</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14770">최승용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13070">박신지</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11300">박정수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13124">김정우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12524">조수행</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>126</td><td>-0.53</td><td>0.50</td><td>249</td><td>245</td><td>219</td><td>41</td><td>48</td><td>2</td><td>1</td><td>1</td><td>55</td><td>17</td><td>26</td><td>6</td><td>23</td><td>2</td><td>0</td><td>38</td><td>2</td><td>4</td><td>1</td><td style="">0.219</td><td>0.298</td><td>0.251</td><td>0.549</td><td>0.064</td><td>56.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13079">권민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.08</td><td>1</td><td>-0.04</td><td>-0.04</td><td>2</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-154.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.08</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14172">송승환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.10</td><td>30</td><td>-0.26</td><td>0.16</td><td>76</td><td>74</td><td>70</td><td>10</td><td>16</td><td>3</td><td>1</td><td>0</td><td>21</td><td>4</td><td>0</td><td>1</td><td>4</td><td>0</td><td>0</td><td>16</td><td>2</td><td>2</td><td>0</td><td style="">0.229</td><td>0.270</td><td>0.300</td><td>0.570</td><td>0.062</td><td>54.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.10</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12523">서예일</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.11</td><td>5</td><td>-0.08</td><td>-0.03</td><td>10</td><td>10</td><td>9</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td style="">0.222</td><td>0.200</td><td>0.222</td><td>0.422</td><td>-0.011</td><td>-10.1</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.11</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11492">신성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.12</td><td>12</td><td>-0.14</td><td>0.02</td><td>15</td><td>15</td><td>12</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td><td>3</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td style="">0.083</td><td>0.267</td><td>0.083</td><td>0.350</td><td>0.018</td><td>16.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.12</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12970">김민혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.21</td><td>21</td><td>-0.28</td><td>0.07</td><td>36</td><td>36</td><td>29</td><td>2</td><td>4</td><td>1</td><td>0</td><td>0</td><td>5</td><td>3</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>9</td><td>3</td><td>0</td><td>2</td><td style="">0.138</td><td>0.250</td><td>0.172</td><td>0.422</td><td>0.023</td><td>20.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.21</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14736">박지훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.21</td><td>22</td><td>-0.14</td><td>-0.07</td><td>21</td><td>21</td><td>19</td><td>2</td><td>4</td><td>1</td><td>0</td><td>0</td><td>5</td><td>2</td><td>1</td><td>0</td><td>2</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>0</td><td style="">0.211</td><td>0.286</td><td>0.263</td><td>0.549</td><td>0.062</td><td>55.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.21</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12606">홍성호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.23</td><td>21</td><td>0.16</td><td>-0.39</td><td>51</td><td>51</td><td>48</td><td>6</td><td>14</td><td>4</td><td>0</td><td>0</td><td>18</td><td>5</td><td>0</td><td>1</td><td>2</td><td>1</td><td>0</td><td>14</td><td>0</td><td>0</td><td>0</td><td style="">0.292</td><td>0.333</td><td>0.375</td><td>0.708</td><td>0.116</td><td>104.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.23</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13073">전민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.30</td><td>19</td><td>-0.15</td><td>-0.14</td><td>18</td><td>17</td><td>17</td><td>3</td><td>4</td><td>2</td><td>0</td><td>0</td><td>6</td><td>1</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3</td><td>2</td><td>1</td><td>0</td><td style="">0.235</td><td>0.235</td><td>0.353</td><td>0.588</td><td>0.059</td><td>52.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.30</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11198">박계범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.33</td><td>78</td><td>-0.06</td><td>-0.27</td><td>194</td><td>189</td><td>169</td><td>18</td><td>37</td><td>6</td><td>0</td><td>2</td><td>49</td><td>15</td><td>2</td><td>2</td><td>15</td><td>2</td><td>1</td><td>44</td><td>4</td><td>5</td><td>3</td><td style="">0.219</td><td>0.286</td><td>0.290</td><td>0.576</td><td>0.066</td><td>58.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.33</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11328">안승한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.40</td><td>22</td><td>-0.08</td><td>-0.31</td><td>27</td><td>27</td><td>24</td><td>1</td><td>5</td><td>0</td><td>0</td><td>0</td><td>5</td><td>1</td><td>1</td><td>0</td><td>2</td><td>1</td><td>0</td><td>10</td><td>0</td><td>0</td><td>0</td><td style="">0.208</td><td>0.296</td><td>0.208</td><td>0.504</td><td>0.053</td><td>46.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.40</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11097">장승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.59</td><td>76</td><td>-0.51</td><td>-0.08</td><td>158</td><td>153</td><td>139</td><td>11</td><td>22</td><td>1</td><td>0</td><td>3</td><td>32</td><td>9</td><td>1</td><td>0</td><td>6</td><td>8</td><td>0</td><td>36</td><td>2</td><td>5</td><td>0</td><td style="">0.158</td><td>0.235</td><td>0.230</td><td>0.465</td><td>0.029</td><td>26.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.59</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14175">김태근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.77</td><td>41</td><td>-0.40</td><td>-0.37</td><td>55</td><td>53</td><td>52</td><td>9</td><td>11</td><td>3</td><td>0</td><td>0</td><td>14</td><td>3</td><td>0</td><td>3</td><td>0</td><td>1</td><td>0</td><td>21</td><td>0</td><td>2</td><td>0</td><td style="">0.212</td><td>0.226</td><td>0.269</td><td>0.495</td><td>0.029</td><td>25.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.77</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14170">김대한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.87</td><td>33</td><td>-0.24</td><td>-0.63</td><td>89</td><td>89</td><td>81</td><td>10</td><td>16</td><td>3</td><td>1</td><td>1</td><td>24</td><td>7</td><td>1</td><td>3</td><td>7</td><td>1</td><td>0</td><td>21</td><td>0</td><td>0</td><td>0</td><td style="">0.198</td><td>0.270</td><td>0.296</td><td>0.566</td><td>0.064</td><td>56.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.87</td></tr>			</tbody>
		</table>""")

In [30]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Offence Wins Above Replacement, 대체선수 대비 승리 기여도 (공격)" flow="down" so="WAROff" ob="DESC">oWAR</th><th rowspan="2" class="sorting" tooltip="Defense Wins Above Replacement, 대체선수 대비 승리 기여도 (수비)" flow="down" so="WARDef" ob="DESC">dWAR</th><th rowspan="2" class="sorting" tooltip="Plate Appearance, 타석" flow="down" so="PA" ob="DESC">PA</th><th rowspan="2" class="sorting" tooltip="effective Plate Appearance, 실질타석(유효타석)" flow="down" so="ePA" ob="DESC">ePA</th><th rowspan="2" class="sorting" tooltip="At Bat, 타수" flow="down" so="AB" ob="DESC">AB</th><th rowspan="2" class="sorting" tooltip="Runs , 득점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Total Bases, 루타" flow="down" so="TB" ob="DESC">TB</th><th rowspan="2" class="sorting" tooltip="Runs Batted In, 타점" flow="down" so="RBI" ob="DESC">RBI</th><th rowspan="2" class="sorting" tooltip="Stolen Base, 도루성공" flow="down" so="SB" ob="DESC">SB</th><th rowspan="2" class="sorting" tooltip="Caught Stealing, 도루실패" flow="down" so="CS" ob="DESC">CS</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Grounded into Double Play, 병살타" flow="down" so="GDP" ob="DESC">GDP</th><th rowspan="2" class="sorting" tooltip="Sacrifice Hit, 희생타(희생번트)" flow="down" so="SH" ob="DESC">SH</th><th rowspan="2" class="sorting" tooltip="Sacrifice Fly, 희생플라이" flow="down" so="SF" ob="DESC">SF</th><th class="align_center no_border" colspan="6" tooltip="Ratio, 비율" flow="down" style="">비율</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC" style="">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
					<th class="sorting" tooltip="Average, 타율" flow="down" so="AVG" ob="DESC" style=";">AVG</th><th class="sorting" tooltip="On Base Percentage, 출루율" flow="down" so="OBP" ob="DESC">OBP</th><th class="sorting" tooltip="Slugging Average, 장타율" flow="down" so="SLG" ob="DESC">SLG</th><th class="sorting" tooltip="On base Plus Slugging, OPS, 출루율+장타율" flow="down" so="OPS" ob="DESC">OPS</th><th class="sorting" tooltip="Runs per effective Plate Appearance, R/ePA" flow="down" so="RePA" ob="DESC">R/ePA</th><th class="sorting" tooltip="Weighted Runs Created plus, 파크팩터 반영된 조정 득점 창출력" flow="down" so="wRCplus" ob="DESC">wRC+</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12905">김혜성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.90</td><td>137</td><td>5.87</td><td>0.03</td><td>621</td><td>619</td><td>556</td><td>104</td><td>186</td><td>29</td><td>6</td><td>7</td><td>248</td><td>57</td><td>25</td><td>3</td><td>57</td><td>3</td><td>3</td><td>77</td><td>6</td><td>0</td><td>5</td><td style="">0.335</td><td>0.396</td><td>0.446</td><td>0.842</td><td>0.163</td><td>141.0</td><td style="background-color:#F3F3F3; font-weight:bold;">5.90</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12906">이정후</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.22</td><td>86</td><td>3.48</td><td>0.74</td><td>387</td><td>384</td><td>330</td><td>50</td><td>105</td><td>23</td><td>2</td><td>6</td><td>150</td><td>45</td><td>6</td><td>3</td><td>49</td><td>3</td><td>7</td><td>23</td><td>1</td><td>0</td><td>5</td><td style="">0.318</td><td>0.406</td><td>0.455</td><td>0.861</td><td>0.170</td><td>146.6</td><td style="background-color:#F3F3F3; font-weight:bold;">4.22</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14591">이주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.15</td><td>51</td><td>2.15</td><td>0.01</td><td>227</td><td>223</td><td>200</td><td>30</td><td>66</td><td>11</td><td>4</td><td>6</td><td>103</td><td>34</td><td>3</td><td>1</td><td>19</td><td>4</td><td>2</td><td>48</td><td>4</td><td>2</td><td>2</td><td style="">0.330</td><td>0.396</td><td>0.515</td><td>0.911</td><td>0.184</td><td>160.1</td><td style="background-color:#F3F3F3; font-weight:bold;">2.15</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14785">김휘집</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.89</td><td>110</td><td>2.32</td><td>-0.43</td><td>435</td><td>429</td><td>369</td><td>46</td><td>92</td><td>22</td><td>0</td><td>8</td><td>138</td><td>51</td><td>0</td><td>0</td><td>48</td><td>5</td><td>0</td><td>97</td><td>8</td><td>6</td><td>7</td><td style="">0.249</td><td>0.338</td><td>0.374</td><td>0.712</td><td>0.119</td><td>102.5</td><td style="background-color:#F3F3F3; font-weight:bold;">1.89</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15652">도슨</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.71</td><td>57</td><td>2.25</td><td>-0.54</td><td>261</td><td>261</td><td>229</td><td>37</td><td>77</td><td>14</td><td>2</td><td>3</td><td>104</td><td>29</td><td>9</td><td>2</td><td>18</td><td>9</td><td>0</td><td>41</td><td>3</td><td>0</td><td>5</td><td style="">0.336</td><td>0.398</td><td>0.454</td><td>0.852</td><td>0.169</td><td>147.0</td><td style="background-color:#F3F3F3; font-weight:bold;">1.71</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15132">박수종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.02</td><td>23</td><td>0.70</td><td>0.33</td><td>50</td><td>50</td><td>45</td><td>7</td><td>19</td><td>1</td><td>2</td><td>0</td><td>24</td><td>3</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>6</td><td>1</td><td>0</td><td>1</td><td style="">0.422</td><td>0.460</td><td>0.533</td><td>0.993</td><td>0.219</td><td>191.1</td><td style="background-color:#F3F3F3; font-weight:bold;">1.02</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14742">러셀</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.99</td><td>59</td><td>1.18</td><td>-0.20</td><td>239</td><td>239</td><td>220</td><td>20</td><td>63</td><td>11</td><td>1</td><td>4</td><td>88</td><td>42</td><td>1</td><td>0</td><td>17</td><td>1</td><td>1</td><td>39</td><td>5</td><td>0</td><td>1</td><td style="">0.286</td><td>0.339</td><td>0.400</td><td>0.739</td><td>0.123</td><td>106.4</td><td style="background-color:#F3F3F3; font-weight:bold;">0.99</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11376">송성문</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.92</td><td>104</td><td>0.60</td><td>0.32</td><td>438</td><td>431</td><td>388</td><td>43</td><td>102</td><td>16</td><td>3</td><td>5</td><td>139</td><td>60</td><td>1</td><td>0</td><td>39</td><td>0</td><td>5</td><td>38</td><td>9</td><td>4</td><td>7</td><td style="">0.263</td><td>0.325</td><td>0.358</td><td>0.683</td><td>0.098</td><td>84.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.92</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15473">김동헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.61</td><td>102</td><td>0.71</td><td>-0.11</td><td>242</td><td>239</td><td>211</td><td>22</td><td>51</td><td>5</td><td>2</td><td>2</td><td>66</td><td>17</td><td>0</td><td>0</td><td>17</td><td>8</td><td>0</td><td>55</td><td>7</td><td>3</td><td>3</td><td style="">0.242</td><td>0.318</td><td>0.313</td><td>0.631</td><td>0.092</td><td>79.8</td><td style="background-color:#F3F3F3; font-weight:bold;">0.61</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10312">이지영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.51</td><td>81</td><td>0.38</td><td>0.12</td><td>237</td><td>230</td><td>217</td><td>23</td><td>54</td><td>8</td><td>1</td><td>0</td><td>64</td><td>8</td><td>1</td><td>1</td><td>12</td><td>1</td><td>0</td><td>39</td><td>2</td><td>7</td><td>0</td><td style="">0.249</td><td>0.291</td><td>0.295</td><td>0.586</td><td>0.074</td><td>63.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.51</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11226">임병욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.31</td><td>80</td><td>0.44</td><td>-0.14</td><td>223</td><td>222</td><td>208</td><td>30</td><td>54</td><td>11</td><td>1</td><td>6</td><td>85</td><td>36</td><td>4</td><td>0</td><td>10</td><td>1</td><td>0</td><td>75</td><td>1</td><td>1</td><td>3</td><td style="">0.260</td><td>0.293</td><td>0.409</td><td>0.702</td><td>0.103</td><td>88.1</td><td style="background-color:#F3F3F3; font-weight:bold;">0.31</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11225">임지열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.23</td><td>72</td><td>0.71</td><td>-0.48</td><td>246</td><td>244</td><td>212</td><td>22</td><td>55</td><td>8</td><td>0</td><td>5</td><td>78</td><td>35</td><td>1</td><td>0</td><td>28</td><td>3</td><td>0</td><td>64</td><td>3</td><td>2</td><td>1</td><td style="">0.259</td><td>0.352</td><td>0.368</td><td>0.720</td><td>0.121</td><td>104.6</td><td style="background-color:#F3F3F3; font-weight:bold;">0.23</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10730">양현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14674">김동혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14849">김성진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10452">임창민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11222">하영민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14131">윤정현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14848">김준형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10437">문성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15531">후라도</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12858">김재웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>1</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15073">이명종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11161">원종현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13092">김선기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>2</td><td>0.00</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12859">이병규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>7</td><td>-0.13</td><td>0.06</td><td>17</td><td>17</td><td>17</td><td>3</td><td>4</td><td>0</td><td>0</td><td>0</td><td>4</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td style="">0.235</td><td>0.235</td><td>0.235</td><td>0.470</td><td>0.016</td><td>14.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15477">송재선</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.09</td><td>5</td><td>0.00</td><td>-0.08</td><td>3</td><td>3</td><td>3</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td style="">0.333</td><td>0.333</td><td>0.333</td><td>0.666</td><td>0.093</td><td>82.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.09</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14851">김시앙</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.12</td><td>33</td><td>-0.17</td><td>0.05</td><td>82</td><td>82</td><td>76</td><td>6</td><td>17</td><td>1</td><td>0</td><td>0</td><td>18</td><td>7</td><td>0</td><td>0</td><td>3</td><td>3</td><td>0</td><td>18</td><td>4</td><td>0</td><td>0</td><td style="">0.224</td><td>0.280</td><td>0.237</td><td>0.517</td><td>0.049</td><td>42.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.12</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12516">이형종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.13</td><td>99</td><td>0.16</td><td>-0.28</td><td>374</td><td>370</td><td>316</td><td>35</td><td>68</td><td>22</td><td>1</td><td>3</td><td>101</td><td>37</td><td>0</td><td>0</td><td>39</td><td>14</td><td>2</td><td>78</td><td>11</td><td>3</td><td>2</td><td style="">0.215</td><td>0.326</td><td>0.320</td><td>0.646</td><td>0.102</td><td>88.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.13</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13096">김수환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.18</td><td>50</td><td>-0.02</td><td>-0.15</td><td>114</td><td>113</td><td>97</td><td>8</td><td>21</td><td>4</td><td>0</td><td>2</td><td>31</td><td>15</td><td>0</td><td>0</td><td>11</td><td>4</td><td>0</td><td>36</td><td>1</td><td>1</td><td>1</td><td style="">0.216</td><td>0.319</td><td>0.320</td><td>0.639</td><td>0.097</td><td>82.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.18</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15476">이승원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.20</td><td>4</td><td>-0.12</td><td>-0.08</td><td>5</td><td>5</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td style="">0.000</td><td>0.000</td><td>0.000</td><td>0.000</td><td>-0.167</td><td>-147.9</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.20</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11422">전병우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.20</td><td>41</td><td>-0.30</td><td>0.10</td><td>75</td><td>73</td><td>62</td><td>6</td><td>9</td><td>3</td><td>0</td><td>1</td><td>15</td><td>6</td><td>0</td><td>0</td><td>10</td><td>1</td><td>0</td><td>28</td><td>0</td><td>2</td><td>0</td><td style="">0.145</td><td>0.274</td><td>0.242</td><td>0.516</td><td>0.058</td><td>50.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.20</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15472">김건희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.23</td><td>9</td><td>-0.08</td><td>-0.15</td><td>13</td><td>13</td><td>11</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td style="">0.182</td><td>0.308</td><td>0.182</td><td>0.490</td><td>0.055</td><td>47.8</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.23</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11182">김준완</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.27</td><td>76</td><td>-0.38</td><td>0.11</td><td>225</td><td>219</td><td>189</td><td>25</td><td>42</td><td>7</td><td>0</td><td>0</td><td>49</td><td>14</td><td>0</td><td>0</td><td>26</td><td>1</td><td>0</td><td>57</td><td>2</td><td>6</td><td>3</td><td style="">0.222</td><td>0.315</td><td>0.259</td><td>0.574</td><td>0.077</td><td>66.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.27</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14577">김병휘</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.27</td><td>10</td><td>-0.24</td><td>-0.04</td><td>21</td><td>21</td><td>21</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8</td><td>0</td><td>0</td><td>0</td><td style="">0.143</td><td>0.143</td><td>0.190</td><td>0.333</td><td>-0.038</td><td>-33.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.27</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11260">박준태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.34</td><td>14</td><td>-0.16</td><td>-0.18</td><td>15</td><td>15</td><td>14</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>0</td><td style="">0.143</td><td>0.200</td><td>0.143</td><td>0.343</td><td>-0.019</td><td>-16.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.34</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14695">신준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.42</td><td>24</td><td>-0.23</td><td>-0.19</td><td>19</td><td>19</td><td>18</td><td>4</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td style="">0.111</td><td>0.158</td><td>0.111</td><td>0.269</td><td>-0.080</td><td>-69.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.42</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10870">김재현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.45</td><td>8</td><td>-0.27</td><td>-0.18</td><td>10</td><td>9</td><td>9</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>1</td><td>1</td><td>0</td><td style="">0.111</td><td>0.111</td><td>0.111</td><td>0.222</td><td>-0.080</td><td>-71.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.45</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14133">주성원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.45</td><td>25</td><td>-0.50</td><td>0.05</td><td>72</td><td>71</td><td>69</td><td>7</td><td>15</td><td>2</td><td>1</td><td>0</td><td>19</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>18</td><td>1</td><td>1</td><td>1</td><td style="">0.217</td><td>0.225</td><td>0.275</td><td>0.500</td><td>0.027</td><td>23.3</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.45</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10035">이용규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.46</td><td>50</td><td>-0.25</td><td>-0.21</td><td>178</td><td>176</td><td>154</td><td>19</td><td>36</td><td>0</td><td>3</td><td>0</td><td>42</td><td>11</td><td>2</td><td>1</td><td>19</td><td>1</td><td>0</td><td>22</td><td>3</td><td>2</td><td>2</td><td style="">0.234</td><td>0.318</td><td>0.273</td><td>0.591</td><td>0.080</td><td>70.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.46</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13093">예진원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.51</td><td>16</td><td>-0.15</td><td>-0.36</td><td>36</td><td>34</td><td>34</td><td>2</td><td>8</td><td>1</td><td>0</td><td>1</td><td>12</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>0</td><td>2</td><td>0</td><td style="">0.235</td><td>0.235</td><td>0.353</td><td>0.588</td><td>0.055</td><td>47.4</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.51</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12503">김웅빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.64</td><td>29</td><td>-0.47</td><td>-0.17</td><td>74</td><td>74</td><td>64</td><td>2</td><td>12</td><td>3</td><td>0</td><td>0</td><td>15</td><td>9</td><td>0</td><td>0</td><td>6</td><td>2</td><td>0</td><td>20</td><td>1</td><td>0</td><td>2</td><td style="">0.188</td><td>0.270</td><td>0.234</td><td>0.504</td><td>0.047</td><td>42.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.64</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14214">김주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.72</td><td>46</td><td>-0.40</td><td>-0.32</td><td>81</td><td>78</td><td>68</td><td>5</td><td>10</td><td>2</td><td>0</td><td>0</td><td>12</td><td>4</td><td>0</td><td>0</td><td>9</td><td>1</td><td>0</td><td>27</td><td>2</td><td>3</td><td>0</td><td style="">0.147</td><td>0.256</td><td>0.176</td><td>0.432</td><td>0.027</td><td>23.7</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.72</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14580">박주홍</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.73</td><td>27</td><td>-0.65</td><td>-0.08</td><td>57</td><td>56</td><td>49</td><td>5</td><td>6</td><td>0</td><td>1</td><td>0</td><td>8</td><td>2</td><td>1</td><td>0</td><td>5</td><td>0</td><td>0</td><td>26</td><td>0</td><td>1</td><td>2</td><td style="">0.122</td><td>0.196</td><td>0.163</td><td>0.359</td><td>-0.012</td><td>-10.2</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.73</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11244">김태진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.73</td><td>74</td><td>-0.34</td><td>-0.39</td><td>212</td><td>209</td><td>200</td><td>17</td><td>55</td><td>5</td><td>0</td><td>0</td><td>60</td><td>16</td><td>0</td><td>0</td><td>5</td><td>1</td><td>0</td><td>23</td><td>1</td><td>3</td><td>3</td><td style="">0.275</td><td>0.292</td><td>0.300</td><td>0.592</td><td>0.066</td><td>57.6</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.73</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15068">박찬혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.83</td><td>48</td><td>-0.83</td><td>0.00</td><td>167</td><td>167</td><td>154</td><td>13</td><td>31</td><td>7</td><td>0</td><td>1</td><td>41</td><td>8</td><td>0</td><td>0</td><td>10</td><td>3</td><td>0</td><td>41</td><td>1</td><td>0</td><td>0</td><td style="">0.201</td><td>0.263</td><td>0.266</td><td>0.529</td><td>0.051</td><td>45.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.83</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10180">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-1.90</td><td>70</td><td>-1.38</td><td>-0.53</td><td>273</td><td>272</td><td>247</td><td>16</td><td>54</td><td>6</td><td>0</td><td>1</td><td>63</td><td>20</td><td>0</td><td>0</td><td>20</td><td>3</td><td>1</td><td>59</td><td>8</td><td>1</td><td>2</td><td style="">0.219</td><td>0.283</td><td>0.255</td><td>0.538</td><td>0.053</td><td>46.0</td><td style="background-color:#F3F3F3; font-weight:bold;">-1.90</td></tr>			</tbody>
		</table>""")

In [31]:
len(team_tables)

10

In [32]:
batting = pd.DataFrame()
for i in range(len(team_tables)):
    name = team_names[i]
    team = team_tables[i]
    print(name)
    df, pids = get_team_stats_from_markup(StringIO(str(team)))
    df['팀'] = name
    df['pid'] = pids[2:]
    print(df.shape)
    print(len(pids))
    batting = pd.concat([batting, df])
    display(batting.tail())

한화 이글스
(38, 35)
40

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank  Name   Team Sort▼   G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank  Name   Team   WAR   G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
33   34  윌리엄스  23 LF -0.63  68 -0.15 -0.48  273  273  258  ...  3  0.244
34   35   유로결  23 RF -0.63  27 -0.65  0.02   53   52   48  ...  2  0.146
35   36   장진혁  23 CF -0.65  68 -0.49 -0.16  178  178  162  ...  1  0.222
36   37   권광민  23 LF -0.84  66 -0.45 -0.38   81   80   73  ...  0  0.151
37   38  오그레디  23 LF -0.98  22 -0.93 -0.05   86   86   80  ...  1  0.125

                                      WAR▼       팀    pid
      OBP    SLG    OPS  R/ePA  wRC+  WAR▼
33  0.275  0.403  0.678  0.093  78.5 -0.63  한화 이글스  15647
34  0.173  0.167  0.340 -0.029 -24.3 -0.63  한화 이글스  14126
35  0.287  0.265  0.552  0.061  52.6 -0.65  한화 이글스  12583
36  0.225  0.274  0.499  0.036  30.9 -0.84  한화 이글스  13676
37  0.174  0.163  0.337 -0.025 -20.8 -0.98  한화 이글스  15541

[5 rows x 35 columns]

LG 트윈스
(33, 35)
35

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team Sort▼   G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank Name   Team   WAR   G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
28   29  손호영  23 SS -0.36  27 -0.23 -0.14   45   45   44  ...  0  0.205
29   30  김범석  23 1B -0.47  10 -0.26 -0.21   29   29   27  ...  1  0.111
30   31  김기연   23 C -0.67  28 -0.21 -0.46   40   39   34  ...  0  0.118
31   32  정주현  23 1B -0.88  89 -0.02 -0.85  101   98   88  ...  1  0.273
32   33  서건창  23 2B -0.90  44 -0.44 -0.46  126  123  110  ...  3  0.200

                                      WAR▼       팀    pid
      OBP    SLG    OPS  R/ePA  wRC+  WAR▼
28  0.222  0.273  0.495  0.025  21.8 -0.36  LG 트윈스  14590
29  0.138  0.259  0.397 -0.018 -15.9 -0.47  LG 트윈스  15484
30  0.231  0.118  0.349 -0.002  -1.6 -0.67  LG 트윈스  12549
31  0.337  0.330  0.667  0.099  87.9 -0.88  LG 트윈스  10480
32  0.260  0.282  0.542  0.053  46.1 -0.90  LG 트윈스  10855

[5 rows x 35 columns]

롯데 자이언츠

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(33, 35)
35

   Rank Name   Team Sort▼    G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank Name   Team   WAR    G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
28   29  이학주  23 SS -0.17  104  0.14 -0.31  122  122  110  ...  0  0.209
29   30  김민수  23 3B -0.26   25 -0.04 -0.22   51   50   43  ...  0  0.209
30   31  신윤후  23 LF -0.38   28 -0.43  0.05   27   27   25  ...  0  0.040
31   32  정대선  23 2B -0.54   19 -0.36 -0.18   47   46   40  ...  2  0.150
32   33  한동희  23 3B -1.81  108 -0.94 -0.88  353  351  319  ...  5  0.223

                                      WAR▼        팀    pid
      OBP    SLG    OPS  R/ePA  wRC+  WAR▼
28  0.287  0.309  0.596  0.075  61.7 -0.17  롯데 자이언츠  14114
29  0.320  0.279  0.599  0.088  71.4 -0.26  롯데 자이언츠  12931
30  0.111  0.040  0.151 -0.086 -72.6 -0.38  롯데 자이언츠  14169
31  0.217  0.175  0.392  0.002   2.0 -0.54  롯데 자이언츠  15443
32  0.279  0.304  0.583  0.067  55.5 -1.81  롯데 자이언츠  13145

[5 rows x 35 columns]

KIA 타이거즈

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(32, 35)
34

   Rank Name   Team Sort▼   G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank Name   Team   WAR   G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
27   28  황대인  23 1B -0.27  60 -0.48  0.21  199  198  174  ...  3  0.213
28   29  변우혁  23 1B -0.33  83  0.11 -0.44  226  226  200  ...  0  0.225
29   30  김석환  23 1B -0.43  12 -0.30 -0.14   26   25   23  ...  0  0.130
30   31  주효상   23 C -0.53  19 -0.53  0.00   36   34   32  ...  0  0.063
31   32  한승택   23 C -0.58  49 -0.48 -0.11  104   98   85  ...  0  0.129

                                      WAR▼         팀    pid
      OBP    SLG    OPS  R/ePA  wRC+  WAR▼
27  0.296  0.322  0.618  0.081  70.5 -0.27  KIA 타이거즈  11306
28  0.314  0.350  0.664  0.100  88.1 -0.33  KIA 타이거즈  14124
29  0.200  0.174  0.374 -0.006  -4.7 -0.43  KIA 타이거즈  12917
30  0.118  0.063  0.181 -0.082 -72.3 -0.53  KIA 타이거즈  12567
31  0.245  0.153  0.398  0.017  15.0 -0.58  KIA 타이거즈  11119

[5 rows x 35 columns]

KT 위즈

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(39, 35)
41

   Rank Name   Team Sort▼    G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank Name   Team   WAR    G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
34   35  문상철  23 DH -0.26  112  0.15 -0.41  330  328  304  ...  6  0.260
35   36  강현우   23 C -0.27   53 -0.26 -0.02  111  110  103  ...  0  0.194
36   37  이시원  23 RF -0.33   29 -0.35  0.02   32   31   29  ...  0  0.138
37   38  류현인  23 3B -0.46   17 -0.27 -0.19   24   24   23  ...  0  0.130
38   39  이상호  23 2B -0.64   63 -0.56 -0.08   60   56   54  ...  0  0.148

                                      WAR▼      팀    pid
      OBP    SLG    OPS  R/ePA  wRC+  WAR▼
34  0.298  0.414  0.712  0.106  87.0 -0.26  KT 위즈  11333
35  0.245  0.282  0.527  0.046  38.1 -0.27  KT 위즈  14603
36  0.194  0.138  0.332 -0.024 -18.8 -0.33  KT 위즈  12526
37  0.167  0.130  0.297 -0.042 -34.0 -0.46  KT 위즈  15523
38  0.179  0.167  0.346 -0.025 -21.0 -0.64  KT 위즈  11147

[5 rows x 35 columns]

삼성 라이온즈
(42, 35)
44

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team Sort▼   G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank Name   Team   WAR   G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
37   38  공민규  23 3B -0.39  22 -0.22 -0.16   33   33   31  ...  0  0.194
38   39  김상민  23 LF -0.39   8 -0.15 -0.24   13   13   12  ...  0  0.083
39   40  김호재  23 3B -0.44  75 -0.47  0.03  127  122  116  ...  0  0.216
40   41  김태훈  23 LF -0.46  11 -0.45 -0.01   22   21   21  ...  0  0.095
41   42  류승민  23 RF -0.50  24 -0.25 -0.25   57   55   52  ...  0  0.212

                                      WAR▼        팀    pid
      OBP    SLG    OPS  R/ePA  wRC+  WAR▼
37  0.242  0.290  0.532  0.047  39.6 -0.39  삼성 라이온즈  13164
38  0.154  0.083  0.237 -0.056 -45.4 -0.39  삼성 라이온즈  15042
39  0.254  0.276  0.530  0.046  38.8 -0.44  삼성 라이온즈  13240
40  0.095  0.143  0.238 -0.075 -61.6 -0.46  삼성 라이온즈  11336
41  0.255  0.269  0.524  0.046  37.7 -0.50  삼성 라이온즈  15503

[5 rows x 35 columns]

SSG 랜더스

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(37, 35)
39

   Rank Name   Team Sort▼   G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank Name   Team   WAR   G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
32   33  이흥련   23 C -0.33  16 -0.09 -0.24   17   16   14  ...  0  0.071
33   34  조형우   23 C -0.37  62 -0.33 -0.05  133  129  119  ...  1  0.185
34   35  이정범  23 DH -0.43  15 -0.38 -0.05   33   33   29  ...  2  0.172
35   36  최경모  23 3B -0.49  28 -0.23 -0.26   20   20   20  ...  0  0.150
36   37  이재원   23 C -0.77  27 -0.71 -0.06   48   47   44  ...  1  0.091

                                      WAR▼        팀    pid
      OBP    SLG    OPS  R/ePA  wRC+  WAR▼
32  0.188  0.286  0.474  0.024  21.0 -0.33  SSG 랜더스  11108
33  0.240  0.286  0.526  0.044  36.4 -0.37  SSG 랜더스  14806
34  0.212  0.172  0.384 -0.009  -7.0 -0.43  SSG 랜더스  13194
35  0.150  0.150  0.300 -0.050 -41.8 -0.49  SSG 랜더스  14151
36  0.128  0.114  0.242 -0.065 -53.7 -0.77  SSG 랜더스  10082

[5 rows x 35 columns]

NC 다이노스
(34, 35)
36

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team Sort▼   G  oWAR  dWAR   PA  ePA  AB  ... SF     비율         \
   Rank Name   Team   WAR   G  oWAR  dWAR   PA  ePA  AB  ... SF    AVG    OBP
29   30  한석현  23 LF -0.27  27 -0.41  0.15   66   64  60  ...  0  0.200  0.250
30   31  박주찬  23 3B -0.31   5 -0.19 -0.12   14   14  14  ...  0  0.143  0.143
31   32  오태양  23 CF -0.41  21 -0.22 -0.19    3    3   3  ...  0  0.000  0.000
32   33  김한별  23 SS -0.43  79 -0.52  0.09  105  103  97  ...  0  0.216  0.262
33   34  박석민  23 3B -0.53  30 -0.16 -0.37  107  106  88  ...  1  0.193  0.321

                                WAR▼        팀    pid
      SLG    OPS  R/ePA   wRC+  WAR▼
29  0.217  0.467  0.026   22.9 -0.27  NC 다이노스  13250
30  0.143  0.286 -0.056  -49.0 -0.31  NC 다이노스  14219
31  0.000  0.000 -0.167 -141.6 -0.41  NC 다이노스  14766
32  0.237  0.499  0.038   32.2 -0.43  NC 다이노스  14716
33  0.239  0.560  0.078   66.4 -0.53  NC 다이노스  10322

[5 rows x 35 columns]

두산 베어스
(38, 35)
40

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team Sort▼   G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank Name   Team   WAR   G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
33   34  박계범  23 SS -0.33  78 -0.06 -0.27  194  189  169  ...  3  0.219
34   35  안승한   23 C -0.40  22 -0.08 -0.31   27   27   24  ...  0  0.208
35   36  장승현   23 C -0.59  76 -0.51 -0.08  158  153  139  ...  0  0.158
36   37  김태근  23 RF -0.77  41 -0.40 -0.37   55   53   52  ...  0  0.212
37   38  김대한  23 RF -0.87  33 -0.24 -0.63   89   89   81  ...  0  0.198

                                      WAR▼       팀    pid
      OBP    SLG    OPS  R/ePA  wRC+  WAR▼
33  0.286  0.290  0.576  0.066  58.0 -0.33  두산 베어스  11198
34  0.296  0.208  0.504  0.053  46.9 -0.40  두산 베어스  11328
35  0.235  0.230  0.465  0.029  26.0 -0.59  두산 베어스  11097
36  0.226  0.269  0.495  0.029  25.7 -0.77  두산 베어스  14175
37  0.270  0.296  0.566  0.064  56.9 -0.87  두산 베어스  14170

[5 rows x 35 columns]

키움 히어로즈
(47, 35)
49

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team Sort▼   G  oWAR  dWAR   PA  ePA   AB  ... SF     비율  \
   Rank Name   Team   WAR   G  oWAR  dWAR   PA  ePA   AB  ... SF    AVG
42   43  김주형  23 SS -0.72  46 -0.40 -0.32   81   78   68  ...  0  0.147
43   44  박주홍  23 1B -0.73  27 -0.65 -0.08   57   56   49  ...  2  0.122
44   45  김태진  23 3B -0.73  74 -0.34 -0.39  212  209  200  ...  3  0.275
45   46  박찬혁  23 LF -0.83  48 -0.83  0.00  167  167  154  ...  0  0.201
46   47  이원석  23 1B -1.90  70 -1.38 -0.53  273  272  247  ...  2  0.219

                                      WAR▼        팀    pid
      OBP    SLG    OPS  R/ePA  wRC+  WAR▼
42  0.256  0.176  0.432  0.027  23.7 -0.72  키움 히어로즈  14214
43  0.196  0.163  0.359 -0.012 -10.2 -0.73  키움 히어로즈  14580
44  0.292  0.300  0.592  0.066  57.6 -0.73  키움 히어로즈  11244
45  0.263  0.266  0.529  0.051  45.0 -0.83  키움 히어로즈  15068
46  0.283  0.255  0.538  0.053  46.0 -1.90  키움 히어로즈  10180

[5 rows x 35 columns]

In [33]:
batting.to_csv("2023_타격_statiz.csv", index=False)

In [34]:
team_tables = []

In [35]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15146">페냐</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.28</td><td>32</td><td>32</td><td>0</td><td>0</td><td>0</td><td>0</td><td>11</td><td>11</td><td>0</td><td>0</td><td>177.1</td><td>71</td><td>82</td><td>79.25</td><td>751</td><td>149</td><td>28</td><td>5</td><td>14</td><td>59</td><td>18</td><td>1</td><td>147</td><td>13</td><td>4</td><td>16</td><td>3.60</td><td>4.16</td><td>4.02</td><td>3.98</td><td>4.06</td><td>1.17</td><td style="background-color:#F3F3F3; font-weight:bold;">4.28</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15013">문동주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.08</td><td>23</td><td>23</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8</td><td>8</td><td>0</td><td>0</td><td>118.2</td><td>49</td><td>52</td><td>49.95</td><td>503</td><td>113</td><td>20</td><td>2</td><td>6</td><td>42</td><td>4</td><td>0</td><td>95</td><td>2</td><td>1</td><td>5</td><td>3.72</td><td>3.94</td><td>3.79</td><td>3.82</td><td>3.65</td><td>1.31</td><td style="background-color:#F3F3F3; font-weight:bold;">3.08</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15643">산체스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.59</td><td>24</td><td>24</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>8</td><td>0</td><td>0</td><td>126.0</td><td>53</td><td>62</td><td>60.80</td><td>540</td><td>136</td><td>23</td><td>0</td><td>13</td><td>28</td><td>6</td><td>2</td><td>99</td><td>7</td><td>0</td><td>3</td><td>3.79</td><td>4.43</td><td>4.34</td><td>4.29</td><td>3.92</td><td>1.30</td><td style="background-color:#F3F3F3; font-weight:bold;">2.59</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11415">주현상</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.44</td><td>55</td><td>0</td><td>55</td><td>9</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>12</td><td>59.2</td><td>13</td><td>13</td><td>14.95</td><td>228</td><td>35</td><td>6</td><td>1</td><td>2</td><td>15</td><td>3</td><td>1</td><td>45</td><td>1</td><td>0</td><td>0</td><td>1.96</td><td>1.96</td><td>2.26</td><td>2.29</td><td>3.25</td><td>0.84</td><td style="background-color:#F3F3F3; font-weight:bold;">2.44</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10609">이태양</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.78</td><td>50</td><td>12</td><td>38</td><td>6</td><td>0</td><td>0</td><td>3</td><td>3</td><td>0</td><td>2</td><td>100.1</td><td>36</td><td>44</td><td>48.50</td><td>422</td><td>100</td><td>25</td><td>6</td><td>7</td><td>21</td><td>3</td><td>2</td><td>72</td><td>9</td><td>0</td><td>1</td><td>3.23</td><td>3.95</td><td>4.35</td><td>4.33</td><td>3.60</td><td>1.21</td><td style="background-color:#F3F3F3; font-weight:bold;">1.78</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11110">윤대경</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.39</td><td>47</td><td>0</td><td>47</td><td>10</td><td>0</td><td>0</td><td>5</td><td>1</td><td>0</td><td>2</td><td>47.2</td><td>13</td><td>18</td><td>15.95</td><td>199</td><td>36</td><td>9</td><td>1</td><td>4</td><td>19</td><td>6</td><td>0</td><td>28</td><td>2</td><td>0</td><td>2</td><td>2.45</td><td>3.40</td><td>3.01</td><td>2.92</td><td>5.01</td><td>1.15</td><td style="background-color:#F3F3F3; font-weight:bold;">1.39</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14621">한승주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.85</td><td>47</td><td>6</td><td>41</td><td>12</td><td>0</td><td>0</td><td>1</td><td>4</td><td>0</td><td>2</td><td>70.2</td><td>31</td><td>34</td><td>37.65</td><td>320</td><td>81</td><td>16</td><td>2</td><td>6</td><td>31</td><td>4</td><td>2</td><td>55</td><td>1</td><td>0</td><td>5</td><td>3.95</td><td>4.33</td><td>4.80</td><td>4.75</td><td>4.45</td><td>1.58</td><td style="background-color:#F3F3F3; font-weight:bold;">0.85</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14808">김기중</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.82</td><td>37</td><td>6</td><td>31</td><td>6</td><td>0</td><td>0</td><td>1</td><td>3</td><td>0</td><td>1</td><td>56.1</td><td>29</td><td>33</td><td>29.20</td><td>253</td><td>58</td><td>9</td><td>3</td><td>4</td><td>29</td><td>9</td><td>1</td><td>46</td><td>2</td><td>0</td><td>2</td><td>4.63</td><td>5.27</td><td>4.67</td><td>4.67</td><td>4.69</td><td>1.54</td><td style="background-color:#F3F3F3; font-weight:bold;">0.82</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10453">장시환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.65</td><td>38</td><td>0</td><td>38</td><td>7</td><td>0</td><td>0</td><td>2</td><td>2</td><td>1</td><td>7</td><td>34.2</td><td>13</td><td>13</td><td>15.75</td><td>153</td><td>32</td><td>4</td><td>0</td><td>1</td><td>21</td><td>4</td><td>1</td><td>24</td><td>1</td><td>0</td><td>3</td><td>3.38</td><td>3.38</td><td>4.09</td><td>4.12</td><td>4.61</td><td>1.53</td><td style="background-color:#F3F3F3; font-weight:bold;">0.65</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14871">김규연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.53</td><td>23</td><td>0</td><td>23</td><td>14</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>19.2</td><td>6</td><td>7</td><td>6.65</td><td>85</td><td>16</td><td>2</td><td>1</td><td>0</td><td>10</td><td>2</td><td>0</td><td>20</td><td>1</td><td>0</td><td>2</td><td>2.75</td><td>3.20</td><td>3.04</td><td>3.07</td><td>3.20</td><td>1.32</td><td style="background-color:#F3F3F3; font-weight:bold;">0.53</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10156">정우람</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.34</td><td>52</td><td>0</td><td>52</td><td>7</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>8</td><td>40.1</td><td>24</td><td>24</td><td>22.20</td><td>183</td><td>45</td><td>8</td><td>2</td><td>3</td><td>17</td><td>2</td><td>0</td><td>30</td><td>2</td><td>0</td><td>3</td><td>5.36</td><td>5.36</td><td>4.95</td><td>4.98</td><td>4.34</td><td>1.54</td><td style="background-color:#F3F3F3; font-weight:bold;">0.34</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11411">김범수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.28</td><td>76</td><td>0</td><td>76</td><td>5</td><td>0</td><td>0</td><td>5</td><td>5</td><td>1</td><td>18</td><td>62.1</td><td>29</td><td>33</td><td>35.80</td><td>283</td><td>64</td><td>10</td><td>0</td><td>3</td><td>33</td><td>3</td><td>5</td><td>52</td><td>4</td><td>0</td><td>4</td><td>4.19</td><td>4.76</td><td>5.17</td><td>5.15</td><td>3.93</td><td>1.56</td><td style="background-color:#F3F3F3; font-weight:bold;">0.28</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13003">이민우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.24</td><td>17</td><td>0</td><td>17</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>2</td><td>13.2</td><td>4</td><td>6</td><td>6.15</td><td>57</td><td>8</td><td>0</td><td>0</td><td>2</td><td>6</td><td>0</td><td>0</td><td>11</td><td>3</td><td>0</td><td>1</td><td>2.63</td><td>3.95</td><td>4.05</td><td>4.24</td><td>4.94</td><td>1.02</td><td style="background-color:#F3F3F3; font-weight:bold;">0.24</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10610">장민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.11</td><td>25</td><td>13</td><td>12</td><td>6</td><td>0</td><td>0</td><td>3</td><td>8</td><td>0</td><td>1</td><td>69.0</td><td>37</td><td>46</td><td>47.55</td><td>308</td><td>79</td><td>13</td><td>2</td><td>12</td><td>22</td><td>5</td><td>2</td><td>61</td><td>4</td><td>0</td><td>5</td><td>4.83</td><td>6.00</td><td>6.20</td><td>6.20</td><td>4.83</td><td>1.46</td><td style="background-color:#F3F3F3; font-weight:bold;">0.11</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15540">스미스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.10</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.2</td><td>2</td><td>2</td><td>0.80</td><td>12</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>6.75</td><td>6.75</td><td>2.70</td><td>2.82</td><td>3.14</td><td>1.13</td><td style="background-color:#F3F3F3; font-weight:bold;">0.10</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13251">류원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.03</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.0</td><td>1</td><td>1</td><td>1.00</td><td>8</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>4.50</td><td>4.50</td><td>4.50</td><td>4.13</td><td>4.15</td><td>0.50</td><td style="background-color:#F3F3F3; font-weight:bold;">0.03</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10748">송윤준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.05</td><td>4</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4.1</td><td>4</td><td>4</td><td>4.00</td><td>19</td><td>4</td><td>2</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>3</td><td>0</td><td>1</td><td>0</td><td>8.31</td><td>8.31</td><td>8.31</td><td>7.72</td><td>3.55</td><td>1.38</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.05</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12655">류희운</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.08</td><td>3</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4.0</td><td>5</td><td>5</td><td>5.00</td><td>20</td><td>6</td><td>1</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>11.25</td><td>11.25</td><td>11.25</td><td>10.37</td><td>5.87</td><td>2.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.08</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12871">박상원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.10</td><td>55</td><td>0</td><td>55</td><td>40</td><td>0</td><td>0</td><td>5</td><td>3</td><td>16</td><td>0</td><td>61.2</td><td>25</td><td>35</td><td>37.75</td><td>277</td><td>63</td><td>9</td><td>3</td><td>2</td><td>29</td><td>3</td><td>4</td><td>57</td><td>5</td><td>0</td><td>2</td><td>3.65</td><td>5.11</td><td>5.51</td><td>5.51</td><td>3.38</td><td>1.49</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.10</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14196">윤산흠</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.12</td><td>5</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.0</td><td>2</td><td>2</td><td>2.50</td><td>18</td><td>3</td><td>1</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>6.00</td><td>6.00</td><td>7.50</td><td>7.30</td><td>7.55</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.12</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15014">박준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.16</td><td>4</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4.1</td><td>9</td><td>9</td><td>5.90</td><td>23</td><td>2</td><td>0</td><td>0</td><td>0</td><td>8</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>1</td><td>18.69</td><td>18.69</td><td>12.25</td><td>12.19</td><td>5.53</td><td>2.31</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.16</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14178">장지수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.17</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.0</td><td>4</td><td>5</td><td>5.00</td><td>11</td><td>4</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>18.00</td><td>22.50</td><td>22.50</td><td>20.63</td><td>6.95</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.17</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12547">김재영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.19</td><td>6</td><td>0</td><td>6</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8.0</td><td>9</td><td>9</td><td>8.30</td><td>40</td><td>13</td><td>2</td><td>1</td><td>2</td><td>2</td><td>2</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td>10.13</td><td>10.13</td><td>9.34</td><td>9.41</td><td>6.81</td><td>1.88</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.19</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11116">이충호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.21</td><td>11</td><td>0</td><td>11</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8.2</td><td>9</td><td>9</td><td>8.65</td><td>41</td><td>12</td><td>0</td><td>0</td><td>2</td><td>5</td><td>1</td><td>0</td><td>7</td><td>0</td><td>0</td><td>0</td><td>9.35</td><td>9.35</td><td>8.98</td><td>9.50</td><td>6.72</td><td>1.96</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.21</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14129">박윤철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.25</td><td>3</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.1</td><td>8</td><td>8</td><td>8.00</td><td>20</td><td>5</td><td>2</td><td>0</td><td>2</td><td>5</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>21.60</td><td>21.60</td><td>21.60</td><td>19.87</td><td>14.89</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.25</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14619">남지민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.26</td><td>16</td><td>7</td><td>9</td><td>5</td><td>0</td><td>0</td><td>1</td><td>7</td><td>0</td><td>0</td><td>37.2</td><td>27</td><td>31</td><td>30.15</td><td>186</td><td>54</td><td>12</td><td>0</td><td>0</td><td>13</td><td>6</td><td>1</td><td>23</td><td>5</td><td>0</td><td>3</td><td>6.45</td><td>7.41</td><td>7.20</td><td>7.03</td><td>3.80</td><td>1.78</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.26</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15421">김서현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.26</td><td>20</td><td>1</td><td>19</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>22.1</td><td>18</td><td>20</td><td>17.95</td><td>114</td><td>22</td><td>4</td><td>2</td><td>1</td><td>23</td><td>7</td><td>1</td><td>26</td><td>1</td><td>1</td><td>3</td><td>7.25</td><td>8.06</td><td>7.23</td><td>7.22</td><td>5.64</td><td>2.01</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.26</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11410">김민우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.28</td><td>12</td><td>12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>6</td><td>0</td><td>0</td><td>51.2</td><td>40</td><td>43</td><td>42.50</td><td>243</td><td>65</td><td>16</td><td>2</td><td>6</td><td>28</td><td>2</td><td>0</td><td>43</td><td>2</td><td>0</td><td>5</td><td>6.97</td><td>7.49</td><td>7.40</td><td>7.34</td><td>4.95</td><td>1.80</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.28</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10812">한승혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.30</td><td>21</td><td>7</td><td>14</td><td>4</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>1</td><td>36.1</td><td>26</td><td>27</td><td>28.90</td><td>176</td><td>48</td><td>9</td><td>0</td><td>3</td><td>21</td><td>3</td><td>0</td><td>28</td><td>2</td><td>0</td><td>4</td><td>6.44</td><td>6.69</td><td>7.16</td><td>7.12</td><td>4.95</td><td>1.90</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.30</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14708">강재민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.63</td><td>43</td><td>0</td><td>43</td><td>2</td><td>0</td><td>0</td><td>1</td><td>3</td><td>0</td><td>12</td><td>43.1</td><td>31</td><td>31</td><td>31.25</td><td>189</td><td>35</td><td>10</td><td>1</td><td>5</td><td>19</td><td>8</td><td>0</td><td>42</td><td>1</td><td>0</td><td>0</td><td>6.44</td><td>6.44</td><td>6.49</td><td>6.57</td><td>4.73</td><td>1.25</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.63</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12587">박상언</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td></td><td></td><td></td><td></td><td></td><td></td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>""")

In [36]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15003">플럿코</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.97</td><td>21</td><td>21</td><td>0</td><td>0</td><td>0</td><td>0</td><td>11</td><td>3</td><td>0</td><td>0</td><td>123.1</td><td>33</td><td>37</td><td>37.00</td><td>510</td><td>115</td><td>21</td><td>3</td><td>5</td><td>31</td><td>3</td><td>1</td><td>101</td><td>6</td><td>0</td><td>2</td><td>2.41</td><td>2.70</td><td>2.70</td><td>2.74</td><td>3.14</td><td>1.18</td><td style="background-color:#F3F3F3; font-weight:bold;">4.97</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13934">켈리</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.93</td><td>30</td><td>30</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td><td>7</td><td>0</td><td>0</td><td>178.2</td><td>76</td><td>87</td><td>81.90</td><td>746</td><td>183</td><td>31</td><td>3</td><td>10</td><td>39</td><td>6</td><td>1</td><td>129</td><td>7</td><td>0</td><td>6</td><td>3.83</td><td>4.38</td><td>4.13</td><td>4.27</td><td>3.49</td><td>1.24</td><td style="background-color:#F3F3F3; font-weight:bold;">3.93</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10652">임찬규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.78</td><td>30</td><td>26</td><td>4</td><td>1</td><td>0</td><td>0</td><td>14</td><td>3</td><td>0</td><td>1</td><td>144.2</td><td>55</td><td>63</td><td>59.75</td><td>632</td><td>142</td><td>22</td><td>2</td><td>10</td><td>54</td><td>5</td><td>1</td><td>103</td><td>10</td><td>1</td><td>1</td><td>3.42</td><td>3.92</td><td>3.72</td><td>3.91</td><td>4.16</td><td>1.35</td><td style="background-color:#F3F3F3; font-weight:bold;">3.78</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11094">함덕주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.67</td><td>57</td><td>0</td><td>57</td><td>9</td><td>0</td><td>0</td><td>4</td><td>0</td><td>4</td><td>16</td><td>55.2</td><td>10</td><td>12</td><td>13.00</td><td>222</td><td>32</td><td>9</td><td>1</td><td>1</td><td>22</td><td>2</td><td>1</td><td>59</td><td>3</td><td>0</td><td>0</td><td>1.62</td><td>1.94</td><td>2.10</td><td>2.21</td><td>2.69</td><td>0.97</td><td style="background-color:#F3F3F3; font-weight:bold;">2.67</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11166">김진성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.41</td><td>80</td><td>0</td><td>80</td><td>14</td><td>0</td><td>0</td><td>5</td><td>1</td><td>4</td><td>21</td><td>70.1</td><td>17</td><td>17</td><td>22.95</td><td>270</td><td>41</td><td>5</td><td>1</td><td>8</td><td>26</td><td>0</td><td>0</td><td>69</td><td>1</td><td>0</td><td>0</td><td>2.18</td><td>2.18</td><td>2.94</td><td>3.11</td><td>3.90</td><td>0.95</td><td style="background-color:#F3F3F3; font-weight:bold;">2.41</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13009">백승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.14</td><td>42</td><td>0</td><td>42</td><td>5</td><td>0</td><td>0</td><td>2</td><td>0</td><td>3</td><td>11</td><td>40.0</td><td>7</td><td>7</td><td>7.35</td><td>162</td><td>28</td><td>4</td><td>0</td><td>2</td><td>18</td><td>0</td><td>1</td><td>30</td><td>3</td><td>0</td><td>1</td><td>1.58</td><td>1.58</td><td>1.65</td><td>1.68</td><td>3.89</td><td>1.15</td><td style="background-color:#F3F3F3; font-weight:bold;">2.14</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14588">김윤식</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.68</td><td>17</td><td>16</td><td>1</td><td>0</td><td>0</td><td>0</td><td>6</td><td>4</td><td>0</td><td>0</td><td>74.2</td><td>35</td><td>35</td><td>33.45</td><td>320</td><td>86</td><td>13</td><td>2</td><td>4</td><td>25</td><td>3</td><td>0</td><td>42</td><td>1</td><td>0</td><td>4</td><td>4.22</td><td>4.22</td><td>4.03</td><td>4.26</td><td>4.24</td><td>1.49</td><td style="background-color:#F3F3F3; font-weight:bold;">1.68</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14669">유영찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.57</td><td>67</td><td>0</td><td>67</td><td>10</td><td>0</td><td>0</td><td>6</td><td>3</td><td>1</td><td>12</td><td>68.0</td><td>26</td><td>27</td><td>28.05</td><td>305</td><td>55</td><td>14</td><td>1</td><td>4</td><td>40</td><td>7</td><td>2</td><td>55</td><td>4</td><td>0</td><td>8</td><td>3.44</td><td>3.57</td><td>3.71</td><td>3.88</td><td>4.67</td><td>1.40</td><td style="background-color:#F3F3F3; font-weight:bold;">1.57</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14134">이정용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.13</td><td>37</td><td>13</td><td>24</td><td>9</td><td>0</td><td>0</td><td>7</td><td>2</td><td>3</td><td>1</td><td>86.2</td><td>40</td><td>45</td><td>46.40</td><td>382</td><td>100</td><td>20</td><td>1</td><td>5</td><td>19</td><td>2</td><td>0</td><td>50</td><td>9</td><td>0</td><td>3</td><td>4.15</td><td>4.67</td><td>4.82</td><td>4.88</td><td>3.84</td><td>1.37</td><td style="background-color:#F3F3F3; font-weight:bold;">1.13</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10749">이우찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.00</td><td>38</td><td>0</td><td>38</td><td>6</td><td>0</td><td>0</td><td>1</td><td>3</td><td>0</td><td>5</td><td>38.1</td><td>15</td><td>15</td><td>13.10</td><td>157</td><td>35</td><td>4</td><td>0</td><td>1</td><td>18</td><td>2</td><td>0</td><td>30</td><td>2</td><td>1</td><td>2</td><td>3.52</td><td>3.52</td><td>3.08</td><td>3.28</td><td>3.82</td><td>1.38</td><td style="background-color:#F3F3F3; font-weight:bold;">1.00</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10535">최동환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.79</td><td>45</td><td>0</td><td>45</td><td>15</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>42.1</td><td>15</td><td>18</td><td>18.50</td><td>189</td><td>42</td><td>11</td><td>0</td><td>1</td><td>17</td><td>3</td><td>2</td><td>20</td><td>5</td><td>0</td><td>0</td><td>3.19</td><td>3.83</td><td>3.93</td><td>4.08</td><td>4.41</td><td>1.39</td><td style="background-color:#F3F3F3; font-weight:bold;">0.79</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12907">고우석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.79</td><td>44</td><td>0</td><td>44</td><td>35</td><td>0</td><td>0</td><td>3</td><td>8</td><td>15</td><td>0</td><td>44.0</td><td>18</td><td>19</td><td>21.05</td><td>190</td><td>38</td><td>6</td><td>0</td><td>2</td><td>22</td><td>4</td><td>1</td><td>59</td><td>1</td><td>0</td><td>5</td><td>3.68</td><td>3.89</td><td>4.31</td><td>4.38</td><td>2.80</td><td>1.36</td><td style="background-color:#F3F3F3; font-weight:bold;">0.79</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14143">이지강</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.36</td><td>22</td><td>12</td><td>10</td><td>5</td><td>0</td><td>0</td><td>2</td><td>5</td><td>0</td><td>2</td><td>68.0</td><td>30</td><td>45</td><td>43.45</td><td>299</td><td>60</td><td>9</td><td>0</td><td>4</td><td>28</td><td>9</td><td>0</td><td>38</td><td>7</td><td>0</td><td>3</td><td>3.97</td><td>5.96</td><td>5.75</td><td>5.82</td><td>4.84</td><td>1.29</td><td style="background-color:#F3F3F3; font-weight:bold;">0.36</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13245">이상규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.24</td><td>8</td><td>0</td><td>8</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7.2</td><td>2</td><td>2</td><td>2.00</td><td>34</td><td>7</td><td>0</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>6</td><td>1</td><td>0</td><td>1</td><td>2.35</td><td>2.35</td><td>2.35</td><td>2.56</td><td>3.91</td><td>1.57</td><td style="background-color:#F3F3F3; font-weight:bold;">0.24</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14135">이상영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.15</td><td>6</td><td>2</td><td>4</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>11.0</td><td>4</td><td>5</td><td>4.50</td><td>54</td><td>12</td><td>3</td><td>0</td><td>0</td><td>8</td><td>3</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td>3.27</td><td>4.09</td><td>3.68</td><td>3.82</td><td>6.04</td><td>1.82</td><td style="background-color:#F3F3F3; font-weight:bold;">0.15</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14589">이민호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.09</td><td>5</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>19.2</td><td>11</td><td>13</td><td>13.00</td><td>91</td><td>22</td><td>4</td><td>0</td><td>1</td><td>10</td><td>0</td><td>0</td><td>7</td><td>4</td><td>0</td><td>0</td><td>5.03</td><td>5.95</td><td>5.95</td><td>6.09</td><td>5.14</td><td>1.63</td><td style="background-color:#F3F3F3; font-weight:bold;">0.09</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10075">진해수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.07</td><td>19</td><td>0</td><td>19</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>14.2</td><td>6</td><td>8</td><td>9.20</td><td>72</td><td>18</td><td>3</td><td>0</td><td>2</td><td>10</td><td>0</td><td>0</td><td>12</td><td>1</td><td>0</td><td>3</td><td>3.68</td><td>4.91</td><td>5.65</td><td>5.59</td><td>5.54</td><td>1.91</td><td style="background-color:#F3F3F3; font-weight:bold;">0.07</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11170">윤호솔</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.07</td><td>4</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.2</td><td>1</td><td>1</td><td>1.50</td><td>17</td><td>3</td><td>1</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>2.45</td><td>2.45</td><td>3.68</td><td>3.93</td><td>3.66</td><td>1.64</td><td style="background-color:#F3F3F3; font-weight:bold;">0.07</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10137">송은범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.07</td><td>4</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.2</td><td>1</td><td>1</td><td>1.70</td><td>17</td><td>6</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2.45</td><td>2.45</td><td>4.17</td><td>3.98</td><td>5.02</td><td>2.45</td><td style="background-color:#F3F3F3; font-weight:bold;">0.07</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14846">송승기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.04</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0.00</td><td>5</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>6.95</td><td>2.00</td><td style="background-color:#F3F3F3; font-weight:bold;">0.04</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11387">채지선</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.03</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.2</td><td>0</td><td>0</td><td>0.00</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>3.85</td><td>0.00</td><td style="background-color:#F3F3F3; font-weight:bold;">0.03</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12860">오석주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>9</td><td>0</td><td>9</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10.0</td><td>7</td><td>7</td><td>7.00</td><td>44</td><td>12</td><td>2</td><td>0</td><td>2</td><td>3</td><td>0</td><td>0</td><td>11</td><td>0</td><td>0</td><td>2</td><td>6.30</td><td>6.30</td><td>6.30</td><td>6.71</td><td>4.41</td><td>1.50</td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15486">박명근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>57</td><td>1</td><td>56</td><td>12</td><td>0</td><td>0</td><td>4</td><td>3</td><td>5</td><td>9</td><td>51.1</td><td>29</td><td>31</td><td>31.70</td><td>236</td><td>49</td><td>9</td><td>1</td><td>4</td><td>28</td><td>6</td><td>2</td><td>40</td><td>6</td><td>0</td><td>1</td><td>5.08</td><td>5.44</td><td>5.56</td><td>5.68</td><td>4.82</td><td>1.50</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13103">성동현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.02</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.0</td><td>1</td><td>1</td><td>1.00</td><td>6</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>9.00</td><td>9.00</td><td>9.00</td><td>9.83</td><td>4.45</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.02</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13102">김영준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.02</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0.1</td><td>1</td><td>1</td><td>0.65</td><td>3</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>27.00</td><td>27.00</td><td>17.55</td><td>16.31</td><td>13.15</td><td>6.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.02</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14780">강효종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>7</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>21.2</td><td>15</td><td>18</td><td>16.30</td><td>103</td><td>25</td><td>3</td><td>0</td><td>1</td><td>12</td><td>2</td><td>0</td><td>14</td><td>2</td><td>1</td><td>0</td><td>6.23</td><td>7.48</td><td>6.77</td><td>6.86</td><td>4.79</td><td>1.71</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12697">배재준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.0</td><td>2</td><td>2</td><td>2.00</td><td>6</td><td>2</td><td>0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>18.00</td><td>18.00</td><td>18.00</td><td>19.66</td><td>6.95</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15485">김동규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.09</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.1</td><td>1</td><td>2</td><td>2.00</td><td>6</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>27.00</td><td>54.00</td><td>54.00</td><td>53.70</td><td>41.05</td><td>9.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.09</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11379">최원태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.12</td><td>9</td><td>9</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>44.1</td><td>33</td><td>35</td><td>34.65</td><td>210</td><td>59</td><td>6</td><td>1</td><td>5</td><td>17</td><td>2</td><td>2</td><td>40</td><td>2</td><td>0</td><td>1</td><td>6.70</td><td>7.11</td><td>7.03</td><td>7.04</td><td>4.12</td><td>1.71</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.12</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12908">손주영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.16</td><td>3</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>8.2</td><td>5</td><td>7</td><td>7.85</td><td>46</td><td>12</td><td>0</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>5</td><td>3</td><td>1</td><td>0</td><td>5.19</td><td>7.27</td><td>8.15</td><td>8.79</td><td>4.55</td><td>2.08</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.16</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12532">김대현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.16</td><td>5</td><td>0</td><td>5</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.1</td><td>4</td><td>5</td><td>4.65</td><td>22</td><td>8</td><td>2</td><td>0</td><td>1</td><td>2</td><td>1</td><td>0</td><td>3</td><td>1</td><td>0</td><td>1</td><td>10.80</td><td>13.50</td><td>12.56</td><td>12.83</td><td>7.96</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.16</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10851">최성훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.54</td><td>5</td><td>0</td><td>5</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>3.0</td><td>5</td><td>5</td><td>6.90</td><td>17</td><td>7</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>15.00</td><td>15.00</td><td>20.70</td><td>22.06</td><td>3.22</td><td>2.67</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.54</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14136">정우영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.66</td><td>60</td><td>0</td><td>60</td><td>3</td><td>0</td><td>0</td><td>5</td><td>6</td><td>0</td><td>11</td><td>51.2</td><td>27</td><td>39</td><td>37.45</td><td>245</td><td>63</td><td>11</td><td>0</td><td>1</td><td>17</td><td>15</td><td>1</td><td>41</td><td>5</td><td>1</td><td>2</td><td>4.70</td><td>6.79</td><td>6.52</td><td>6.84</td><td>3.96</td><td>1.55</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.66</td></tr>			</tbody>
		</table>
""")

In [37]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15011">반즈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.49</td><td>30</td><td>30</td><td>0</td><td>0</td><td>0</td><td>0</td><td>11</td><td>10</td><td>0</td><td>0</td><td>170.1</td><td>62</td><td>68</td><td>65.40</td><td>734</td><td>171</td><td>34</td><td>1</td><td>6</td><td>56</td><td>15</td><td>1</td><td>147</td><td>7</td><td>0</td><td>7</td><td>3.28</td><td>3.59</td><td>3.46</td><td>3.41</td><td>3.40</td><td>1.33</td><td style="background-color:#F3F3F3; font-weight:bold;">5.49</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11310">박세웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.21</td><td>27</td><td>27</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9</td><td>7</td><td>0</td><td>0</td><td>154.0</td><td>59</td><td>70</td><td>67.25</td><td>657</td><td>145</td><td>24</td><td>0</td><td>8</td><td>59</td><td>4</td><td>1</td><td>129</td><td>9</td><td>0</td><td>10</td><td>3.45</td><td>4.09</td><td>3.93</td><td>3.82</td><td>3.62</td><td>1.32</td><td style="background-color:#F3F3F3; font-weight:bold;">4.21</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12930">나균안</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.34</td><td>23</td><td>23</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td><td>8</td><td>0</td><td>0</td><td>130.1</td><td>55</td><td>61</td><td>58.75</td><td>569</td><td>140</td><td>27</td><td>3</td><td>8</td><td>42</td><td>5</td><td>1</td><td>114</td><td>4</td><td>0</td><td>6</td><td>3.80</td><td>4.21</td><td>4.06</td><td>3.96</td><td>3.51</td><td>1.40</td><td style="background-color:#F3F3F3; font-weight:bold;">3.34</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12295">윌커슨</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.92</td><td>13</td><td>13</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>2</td><td>0</td><td>0</td><td>79.2</td><td>20</td><td>28</td><td>27.50</td><td>327</td><td>67</td><td>15</td><td>2</td><td>3</td><td>20</td><td>2</td><td>0</td><td>81</td><td>5</td><td>1</td><td>3</td><td>2.26</td><td>3.16</td><td>3.11</td><td>3.04</td><td>2.61</td><td>1.09</td><td style="background-color:#F3F3F3; font-weight:bold;">2.92</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10427">김상수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.73</td><td>67</td><td>0</td><td>67</td><td>7</td><td>0</td><td>0</td><td>4</td><td>2</td><td>1</td><td>18</td><td>52.0</td><td>18</td><td>22</td><td>18.55</td><td>218</td><td>45</td><td>7</td><td>1</td><td>1</td><td>21</td><td>3</td><td>0</td><td>36</td><td>5</td><td>0</td><td>1</td><td>3.12</td><td>3.81</td><td>3.21</td><td>3.17</td><td>3.78</td><td>1.27</td><td style="background-color:#F3F3F3; font-weight:bold;">1.73</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14624">최준용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.66</td><td>47</td><td>0</td><td>47</td><td>4</td><td>0</td><td>0</td><td>2</td><td>3</td><td>0</td><td>14</td><td>47.2</td><td>13</td><td>15</td><td>15.35</td><td>210</td><td>50</td><td>6</td><td>0</td><td>2</td><td>18</td><td>1</td><td>1</td><td>40</td><td>2</td><td>0</td><td>1</td><td>2.45</td><td>2.83</td><td>2.90</td><td>2.83</td><td>3.42</td><td>1.43</td><td style="background-color:#F3F3F3; font-weight:bold;">1.66</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14627">스트레일리</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.63</td><td>16</td><td>16</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>5</td><td>0</td><td>0</td><td>80.1</td><td>39</td><td>43</td><td>41.80</td><td>364</td><td>82</td><td>8</td><td>1</td><td>6</td><td>37</td><td>10</td><td>0</td><td>70</td><td>4</td><td>0</td><td>4</td><td>4.37</td><td>4.82</td><td>4.68</td><td>4.45</td><td>4.37</td><td>1.48</td><td style="background-color:#F3F3F3; font-weight:bold;">1.63</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10825">김원중</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.49</td><td>63</td><td>0</td><td>63</td><td>47</td><td>0</td><td>0</td><td>5</td><td>6</td><td>30</td><td>0</td><td>63.2</td><td>21</td><td>24</td><td>29.50</td><td>265</td><td>51</td><td>5</td><td>3</td><td>2</td><td>25</td><td>5</td><td>3</td><td>82</td><td>1</td><td>0</td><td>3</td><td>2.97</td><td>3.39</td><td>4.17</td><td>4.01</td><td>2.37</td><td>1.19</td><td style="background-color:#F3F3F3; font-weight:bold;">1.49</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11311">심재민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.19</td><td>29</td><td>6</td><td>23</td><td>6</td><td>1</td><td>0</td><td>3</td><td>1</td><td>0</td><td>6</td><td>45.2</td><td>15</td><td>18</td><td>19.80</td><td>202</td><td>49</td><td>5</td><td>0</td><td>2</td><td>16</td><td>1</td><td>1</td><td>28</td><td>4</td><td>0</td><td>1</td><td>2.96</td><td>3.55</td><td>3.90</td><td>3.77</td><td>3.92</td><td>1.42</td><td style="background-color:#F3F3F3; font-weight:bold;">1.19</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11291">구승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.98</td><td>67</td><td>0</td><td>67</td><td>8</td><td>0</td><td>0</td><td>2</td><td>6</td><td>3</td><td>22</td><td>63.2</td><td>28</td><td>32</td><td>32.85</td><td>289</td><td>65</td><td>8</td><td>0</td><td>4</td><td>29</td><td>5</td><td>0</td><td>66</td><td>2</td><td>0</td><td>2</td><td>3.96</td><td>4.52</td><td>4.64</td><td>4.53</td><td>3.66</td><td>1.48</td><td style="background-color:#F3F3F3; font-weight:bold;">0.98</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10863">한현희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.79</td><td>38</td><td>18</td><td>20</td><td>3</td><td>0</td><td>0</td><td>6</td><td>12</td><td>0</td><td>3</td><td>104.0</td><td>63</td><td>69</td><td>65.60</td><td>476</td><td>123</td><td>20</td><td>4</td><td>11</td><td>44</td><td>11</td><td>1</td><td>74</td><td>3</td><td>0</td><td>6</td><td>5.45</td><td>5.97</td><td>5.68</td><td>5.53</td><td>4.97</td><td>1.61</td><td style="background-color:#F3F3F3; font-weight:bold;">0.79</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13148">김도규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.31</td><td>36</td><td>0</td><td>36</td><td>14</td><td>0</td><td>0</td><td>0</td><td>3</td><td>1</td><td>1</td><td>29.2</td><td>15</td><td>16</td><td>17.20</td><td>132</td><td>29</td><td>5</td><td>0</td><td>1</td><td>13</td><td>1</td><td>0</td><td>26</td><td>3</td><td>0</td><td>6</td><td>4.55</td><td>4.85</td><td>5.22</td><td>4.96</td><td>3.52</td><td>1.42</td><td style="background-color:#F3F3F3; font-weight:bold;">0.31</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15445">석상호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.24</td><td>5</td><td>0</td><td>5</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5.1</td><td>0</td><td>0</td><td>0.00</td><td>22</td><td>4</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>6</td><td>1</td><td>0</td><td>1</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>2.20</td><td>1.13</td><td style="background-color:#F3F3F3; font-weight:bold;">0.24</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13147">정성종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.21</td><td>12</td><td>3</td><td>9</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>1</td><td>22.0</td><td>13</td><td>14</td><td>13.50</td><td>98</td><td>21</td><td>5</td><td>0</td><td>1</td><td>15</td><td>1</td><td>1</td><td>10</td><td>0</td><td>0</td><td>1</td><td>5.32</td><td>5.73</td><td>5.52</td><td>5.16</td><td>5.37</td><td>1.64</td><td style="background-color:#F3F3F3; font-weight:bold;">0.21</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15441">이진하</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.20</td><td>9</td><td>0</td><td>9</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8.0</td><td>3</td><td>3</td><td>2.50</td><td>31</td><td>4</td><td>3</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>2</td><td>1</td><td>0</td><td>1</td><td>3.38</td><td>3.38</td><td>2.81</td><td>2.88</td><td>4.77</td><td>0.88</td><td style="background-color:#F3F3F3; font-weight:bold;">0.20</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14793">김창훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.09</td><td>3</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4.1</td><td>1</td><td>1</td><td>1.70</td><td>17</td><td>5</td><td>0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>2.08</td><td>2.08</td><td>3.53</td><td>3.32</td><td>3.99</td><td>1.38</td><td style="background-color:#F3F3F3; font-weight:bold;">0.09</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15045">이민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.08</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.1</td><td>0</td><td>0</td><td>0.00</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>4.30</td><td>0.75</td><td style="background-color:#F3F3F3; font-weight:bold;">0.08</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12699">김강현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.08</td><td>2</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.0</td><td>1</td><td>1</td><td>1.00</td><td>13</td><td>1</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.00</td><td>3.00</td><td>3.00</td><td>2.79</td><td>6.95</td><td>1.00</td><td style="background-color:#F3F3F3; font-weight:bold;">0.08</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14164">박영완</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.04</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0.00</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>4.45</td><td>1.00</td><td style="background-color:#F3F3F3; font-weight:bold;">0.04</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13169">최이준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.04</td><td>28</td><td>0</td><td>28</td><td>9</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>29.0</td><td>22</td><td>22</td><td>20.15</td><td>143</td><td>37</td><td>11</td><td>3</td><td>1</td><td>21</td><td>0</td><td>1</td><td>20</td><td>0</td><td>0</td><td>4</td><td>6.83</td><td>6.83</td><td>6.25</td><td>6.10</td><td>4.78</td><td>2.00</td><td style="background-color:#F3F3F3; font-weight:bold;">0.04</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12923">김태욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.04</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0.00</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>3.85</td><td>0.00</td><td style="background-color:#F3F3F3; font-weight:bold;">0.04</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15047">진승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>24</td><td>0</td><td>24</td><td>8</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>1</td><td>27.2</td><td>18</td><td>20</td><td>18.45</td><td>129</td><td>34</td><td>3</td><td>0</td><td>2</td><td>16</td><td>0</td><td>3</td><td>25</td><td>2</td><td>0</td><td>1</td><td>5.86</td><td>6.51</td><td>6.00</td><td>5.93</td><td>4.13</td><td>1.81</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14816">우강훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>3</td><td>1</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6.0</td><td>4</td><td>5</td><td>3.45</td><td>29</td><td>6</td><td>1</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>5</td><td>1</td><td>0</td><td>0</td><td>6.00</td><td>7.50</td><td>5.18</td><td>5.46</td><td>4.35</td><td>1.67</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14163">박진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>4</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5.0</td><td>5</td><td>5</td><td>5.20</td><td>29</td><td>7</td><td>2</td><td>0</td><td>1</td><td>7</td><td>0</td><td>0</td><td>2</td><td>0</td><td>1</td><td>1</td><td>9.00</td><td>9.00</td><td>9.36</td><td>8.86</td><td>9.57</td><td>2.80</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15448">장세진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.09</td><td>2</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.1</td><td>2</td><td>2</td><td>2.50</td><td>8</td><td>2</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>13.50</td><td>13.50</td><td>16.88</td><td>15.88</td><td>15.55</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.09</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12935">나원탁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.13</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.2</td><td>3</td><td>3</td><td>3.00</td><td>6</td><td>3</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>40.50</td><td>40.50</td><td>40.50</td><td>40.28</td><td>22.60</td><td>6.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.13</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10516">신정락</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.14</td><td>34</td><td>0</td><td>34</td><td>9</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>1</td><td>29.0</td><td>15</td><td>15</td><td>20.70</td><td>128</td><td>32</td><td>6</td><td>0</td><td>4</td><td>11</td><td>3</td><td>3</td><td>28</td><td>1</td><td>0</td><td>0</td><td>4.66</td><td>4.66</td><td>6.42</td><td>6.15</td><td>4.47</td><td>1.48</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.14</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14792">김진욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.16</td><td>49</td><td>0</td><td>49</td><td>2</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>8</td><td>36.1</td><td>26</td><td>27</td><td>25.70</td><td>177</td><td>37</td><td>6</td><td>1</td><td>4</td><td>29</td><td>2</td><td>0</td><td>35</td><td>1</td><td>0</td><td>3</td><td>6.44</td><td>6.69</td><td>6.37</td><td>6.25</td><td>5.40</td><td>1.82</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.16</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11232">이인복</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.40</td><td>10</td><td>7</td><td>3</td><td>0</td><td>0</td><td>0</td><td>1</td><td>4</td><td>0</td><td>0</td><td>33.1</td><td>24</td><td>32</td><td>30.65</td><td>168</td><td>54</td><td>7</td><td>3</td><td>3</td><td>10</td><td>5</td><td>1</td><td>15</td><td>6</td><td>0</td><td>4</td><td>6.48</td><td>8.64</td><td>8.28</td><td>8.09</td><td>5.10</td><td>1.92</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.40</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15444">이태연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.41</td><td>15</td><td>0</td><td>15</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>5.2</td><td>10</td><td>10</td><td>10.35</td><td>37</td><td>12</td><td>3</td><td>0</td><td>1</td><td>9</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>15.88</td><td>15.88</td><td>16.44</td><td>15.90</td><td>9.11</td><td>3.71</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.41</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11276">최영환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.59</td><td>8</td><td>0</td><td>8</td><td>4</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>10.0</td><td>11</td><td>14</td><td>13.65</td><td>54</td><td>15</td><td>8</td><td>0</td><td>0</td><td>7</td><td>1</td><td>0</td><td>7</td><td>3</td><td>0</td><td>0</td><td>9.90</td><td>12.60</td><td>12.29</td><td>11.58</td><td>4.58</td><td>2.20</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.59</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11299">문경찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.68</td><td>2</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>2.0</td><td>6</td><td>6</td><td>6.00</td><td>12</td><td>6</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>27.00</td><td>27.00</td><td>27.00</td><td>27.29</td><td>19.20</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.68</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10885">윤명준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-1.10</td><td>21</td><td>0</td><td>21</td><td>8</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>5</td><td>19.1</td><td>14</td><td>14</td><td>21.95</td><td>98</td><td>31</td><td>3</td><td>1</td><td>4</td><td>10</td><td>4</td><td>2</td><td>11</td><td>0</td><td>0</td><td>5</td><td>6.52</td><td>6.52</td><td>10.22</td><td>9.94</td><td>7.13</td><td>2.12</td><td style="background-color:#F3F3F3; font-weight:bold;">-1.10</td></tr>			</tbody>
		</table>
""")

In [38]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10058">양현종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.15</td><td>29</td><td>29</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9</td><td>11</td><td>0</td><td>0</td><td>171.0</td><td>68</td><td>78</td><td>76.45</td><td>729</td><td>181</td><td>33</td><td>1</td><td>13</td><td>48</td><td>1</td><td>1</td><td>133</td><td>9</td><td>0</td><td>5</td><td>3.58</td><td>4.11</td><td>4.02</td><td>4.13</td><td>3.70</td><td>1.34</td><td style="background-color:#F3F3F3; font-weight:bold;">4.15</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14788">이의리</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.29</td><td>28</td><td>28</td><td>0</td><td>0</td><td>0</td><td>0</td><td>11</td><td>7</td><td>0</td><td>0</td><td>131.2</td><td>58</td><td>64</td><td>57.45</td><td>598</td><td>103</td><td>18</td><td>0</td><td>4</td><td>93</td><td>8</td><td>1</td><td>156</td><td>12</td><td>0</td><td>10</td><td>3.96</td><td>4.37</td><td>3.93</td><td>4.05</td><td>3.63</td><td>1.49</td><td style="background-color:#F3F3F3; font-weight:bold;">3.29</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15432">윤영철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.85</td><td>25</td><td>24</td><td>1</td><td>0</td><td>0</td><td>0</td><td>8</td><td>7</td><td>0</td><td>0</td><td>122.2</td><td>55</td><td>59</td><td>56.05</td><td>528</td><td>124</td><td>27</td><td>3</td><td>10</td><td>48</td><td>1</td><td>1</td><td>74</td><td>5</td><td>1</td><td>4</td><td>4.04</td><td>4.33</td><td>4.11</td><td>4.21</td><td>4.55</td><td>1.40</td><td style="background-color:#F3F3F3; font-weight:bold;">2.85</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10909">임기영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.35</td><td>64</td><td>0</td><td>64</td><td>9</td><td>0</td><td>0</td><td>4</td><td>4</td><td>3</td><td>16</td><td>82.0</td><td>27</td><td>29</td><td>30.95</td><td>324</td><td>56</td><td>8</td><td>3</td><td>6</td><td>19</td><td>6</td><td>1</td><td>57</td><td>2</td><td>0</td><td>1</td><td>2.96</td><td>3.18</td><td>3.40</td><td>3.48</td><td>3.93</td><td>0.91</td><td style="background-color:#F3F3F3; font-weight:bold;">2.35</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15147">파노니</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.04</td><td>16</td><td>15</td><td>1</td><td>0</td><td>0</td><td>0</td><td>6</td><td>3</td><td>0</td><td>0</td><td>82.1</td><td>39</td><td>41</td><td>36.90</td><td>351</td><td>86</td><td>14</td><td>1</td><td>6</td><td>23</td><td>2</td><td>0</td><td>66</td><td>4</td><td>0</td><td>0</td><td>4.26</td><td>4.48</td><td>4.03</td><td>4.06</td><td>3.65</td><td>1.32</td><td style="background-color:#F3F3F3; font-weight:bold;">2.04</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12537">전상현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.89</td><td>64</td><td>0</td><td>64</td><td>8</td><td>0</td><td>0</td><td>8</td><td>3</td><td>1</td><td>13</td><td>58.2</td><td>14</td><td>20</td><td>21.25</td><td>250</td><td>50</td><td>8</td><td>0</td><td>1</td><td>26</td><td>1</td><td>4</td><td>50</td><td>4</td><td>0</td><td>3</td><td>2.15</td><td>3.07</td><td>3.26</td><td>3.28</td><td>3.30</td><td>1.30</td><td style="background-color:#F3F3F3; font-weight:bold;">1.89</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15533">앤더슨</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.57</td><td>14</td><td>14</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>7</td><td>0</td><td>0</td><td>79.0</td><td>33</td><td>42</td><td>39.05</td><td>336</td><td>76</td><td>12</td><td>3</td><td>6</td><td>26</td><td>2</td><td>0</td><td>64</td><td>8</td><td>0</td><td>10</td><td>3.76</td><td>4.78</td><td>4.45</td><td>4.53</td><td>3.83</td><td>1.29</td><td style="background-color:#F3F3F3; font-weight:bold;">1.57</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14608">정해영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.48</td><td>52</td><td>0</td><td>52</td><td>40</td><td>0</td><td>0</td><td>3</td><td>4</td><td>23</td><td>1</td><td>49.1</td><td>16</td><td>18</td><td>19.55</td><td>218</td><td>53</td><td>9</td><td>1</td><td>3</td><td>20</td><td>1</td><td>3</td><td>30</td><td>2</td><td>0</td><td>0</td><td>2.92</td><td>3.28</td><td>3.57</td><td>3.59</td><td>4.25</td><td>1.48</td><td style="background-color:#F3F3F3; font-weight:bold;">1.48</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11303">이준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.97</td><td>64</td><td>0</td><td>64</td><td>4</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>10</td><td>33.2</td><td>12</td><td>12</td><td>12.65</td><td>149</td><td>26</td><td>3</td><td>1</td><td>0</td><td>23</td><td>2</td><td>2</td><td>30</td><td>3</td><td>0</td><td>1</td><td>3.21</td><td>3.21</td><td>3.38</td><td>3.46</td><td>3.74</td><td>1.46</td><td style="background-color:#F3F3F3; font-weight:bold;">0.97</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15057">최지민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.91</td><td>58</td><td>0</td><td>58</td><td>15</td><td>0</td><td>0</td><td>6</td><td>3</td><td>3</td><td>12</td><td>59.1</td><td>14</td><td>17</td><td>29.40</td><td>244</td><td>45</td><td>4</td><td>2</td><td>4</td><td>26</td><td>4</td><td>1</td><td>44</td><td>5</td><td>0</td><td>5</td><td>2.12</td><td>2.58</td><td>4.46</td><td>4.56</td><td>4.31</td><td>1.20</td><td style="background-color:#F3F3F3; font-weight:bold;">0.91</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11164">장현식</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.63</td><td>56</td><td>0</td><td>56</td><td>17</td><td>0</td><td>0</td><td>2</td><td>2</td><td>3</td><td>5</td><td>51.0</td><td>23</td><td>26</td><td>26.45</td><td>226</td><td>58</td><td>8</td><td>0</td><td>6</td><td>26</td><td>1</td><td>1</td><td>44</td><td>1</td><td>0</td><td>1</td><td>4.06</td><td>4.59</td><td>4.67</td><td>4.81</td><td>4.67</td><td>1.65</td><td style="background-color:#F3F3F3; font-weight:bold;">0.63</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13122">윤중현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.49</td><td>31</td><td>0</td><td>31</td><td>10</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>28.0</td><td>12</td><td>13</td><td>13.20</td><td>115</td><td>29</td><td>3</td><td>0</td><td>2</td><td>10</td><td>1</td><td>1</td><td>8</td><td>2</td><td>0</td><td>0</td><td>3.86</td><td>4.18</td><td>4.24</td><td>4.38</td><td>5.09</td><td>1.39</td><td style="background-color:#F3F3F3; font-weight:bold;">0.49</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15648">산체스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.27</td><td>12</td><td>11</td><td>1</td><td>1</td><td>1</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>63.2</td><td>42</td><td>46</td><td>43.60</td><td>285</td><td>79</td><td>19</td><td>1</td><td>7</td><td>15</td><td>4</td><td>1</td><td>59</td><td>3</td><td>1</td><td>1</td><td>5.94</td><td>6.50</td><td>6.16</td><td>6.10</td><td>3.77</td><td>1.48</td><td style="background-color:#F3F3F3; font-weight:bold;">0.27</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12637">김승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.19</td><td>10</td><td>0</td><td>10</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>12.2</td><td>6</td><td>6</td><td>6.00</td><td>57</td><td>11</td><td>2</td><td>0</td><td>1</td><td>10</td><td>1</td><td>0</td><td>7</td><td>1</td><td>0</td><td>1</td><td>4.26</td><td>4.26</td><td>4.26</td><td>4.41</td><td>6.10</td><td>1.66</td><td style="background-color:#F3F3F3; font-weight:bold;">0.19</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15534">메디나</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.18</td><td>12</td><td>12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>6</td><td>0</td><td>0</td><td>58.0</td><td>39</td><td>42</td><td>39.25</td><td>269</td><td>64</td><td>16</td><td>1</td><td>6</td><td>29</td><td>9</td><td>0</td><td>36</td><td>2</td><td>1</td><td>5</td><td>6.05</td><td>6.52</td><td>6.09</td><td>6.33</td><td>5.56</td><td>1.60</td><td style="background-color:#F3F3F3; font-weight:bold;">0.18</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11070">박준표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.14</td><td>33</td><td>0</td><td>33</td><td>3</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>3</td><td>28.0</td><td>14</td><td>16</td><td>17.35</td><td>118</td><td>28</td><td>3</td><td>1</td><td>3</td><td>9</td><td>0</td><td>1</td><td>13</td><td>2</td><td>0</td><td>1</td><td>4.50</td><td>5.14</td><td>5.58</td><td>5.58</td><td>4.96</td><td>1.32</td><td style="background-color:#F3F3F3; font-weight:bold;">0.14</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10706">김대유</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.10</td><td>41</td><td>0</td><td>41</td><td>4</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>4</td><td>24.2</td><td>14</td><td>15</td><td>15.00</td><td>110</td><td>26</td><td>1</td><td>1</td><td>2</td><td>8</td><td>6</td><td>1</td><td>20</td><td>1</td><td>0</td><td>0</td><td>5.11</td><td>5.47</td><td>5.47</td><td>5.62</td><td>4.42</td><td>1.38</td><td style="background-color:#F3F3F3; font-weight:bold;">0.10</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12914">유승철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.04</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0.00</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>6.95</td><td>1.00</td><td style="background-color:#F3F3F3; font-weight:bold;">0.04</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12944">김건국</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>6</td><td>5</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>16.0</td><td>12</td><td>12</td><td>11.15</td><td>70</td><td>18</td><td>6</td><td>1</td><td>0</td><td>4</td><td>1</td><td>0</td><td>9</td><td>0</td><td>0</td><td>0</td><td>6.75</td><td>6.75</td><td>6.27</td><td>6.69</td><td>3.41</td><td>1.38</td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15063">황동하</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.06</td><td>13</td><td>6</td><td>7</td><td>1</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>31.1</td><td>23</td><td>25</td><td>22.95</td><td>149</td><td>35</td><td>6</td><td>3</td><td>5</td><td>21</td><td>1</td><td>0</td><td>19</td><td>2</td><td>0</td><td>1</td><td>6.61</td><td>7.18</td><td>6.59</td><td>6.82</td><td>6.41</td><td>1.79</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.06</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15435">곽도규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.18</td><td>14</td><td>0</td><td>14</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>11.2</td><td>11</td><td>11</td><td>11.00</td><td>61</td><td>14</td><td>2</td><td>0</td><td>0</td><td>10</td><td>2</td><td>0</td><td>14</td><td>0</td><td>0</td><td>1</td><td>8.49</td><td>8.49</td><td>8.49</td><td>8.64</td><td>4.04</td><td>2.06</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.18</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13114">김유신</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.21</td><td>27</td><td>0</td><td>27</td><td>9</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>2</td><td>30.1</td><td>19</td><td>19</td><td>22.60</td><td>141</td><td>34</td><td>8</td><td>0</td><td>2</td><td>19</td><td>3</td><td>0</td><td>12</td><td>1</td><td>0</td><td>0</td><td>5.64</td><td>5.64</td><td>6.71</td><td>6.70</td><td>5.89</td><td>1.75</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.21</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14176">김기훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.26</td><td>29</td><td>0</td><td>29</td><td>12</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>31.1</td><td>16</td><td>22</td><td>23.55</td><td>156</td><td>28</td><td>6</td><td>1</td><td>0</td><td>37</td><td>2</td><td>1</td><td>26</td><td>3</td><td>1</td><td>5</td><td>4.60</td><td>6.32</td><td>6.76</td><td>6.99</td><td>5.53</td><td>2.07</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.26</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14747">김재열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.76</td><td>9</td><td>0</td><td>9</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>11.2</td><td>17</td><td>17</td><td>18.20</td><td>70</td><td>20</td><td>4</td><td>1</td><td>2</td><td>13</td><td>0</td><td>0</td><td>9</td><td>3</td><td>0</td><td>0</td><td>13.11</td><td>13.11</td><td>14.04</td><td>13.82</td><td>7.42</td><td>2.83</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.76</td></tr>			</tbody>
		</table>
""")

In [39]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11308">고영표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">6.77</td><td>28</td><td>27</td><td>1</td><td>1</td><td>0</td><td>0</td><td>12</td><td>7</td><td>0</td><td>0</td><td>174.2</td><td>54</td><td>57</td><td>57.35</td><td>706</td><td>181</td><td>27</td><td>5</td><td>7</td><td>19</td><td>9</td><td>1</td><td>114</td><td>6</td><td>0</td><td>6</td><td>2.78</td><td>2.94</td><td>2.96</td><td>2.91</td><td>3.19</td><td>1.15</td><td style="background-color:#F3F3F3; font-weight:bold;">6.77</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13942">쿠에바스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">5.19</td><td>18</td><td>18</td><td>0</td><td>0</td><td>0</td><td>0</td><td>12</td><td>0</td><td>0</td><td>0</td><td>114.1</td><td>33</td><td>33</td><td>31.65</td><td>460</td><td>95</td><td>10</td><td>2</td><td>4</td><td>24</td><td>2</td><td>1</td><td>100</td><td>2</td><td>0</td><td>5</td><td>2.60</td><td>2.60</td><td>2.49</td><td>2.39</td><td>2.78</td><td>1.04</td><td style="background-color:#F3F3F3; font-weight:bold;">5.19</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15143">벤자민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.66</td><td>29</td><td>29</td><td>0</td><td>0</td><td>0</td><td>0</td><td>15</td><td>6</td><td>0</td><td>0</td><td>160.0</td><td>63</td><td>79</td><td>76.95</td><td>684</td><td>149</td><td>23</td><td>1</td><td>12</td><td>45</td><td>3</td><td>1</td><td>157</td><td>13</td><td>0</td><td>11</td><td>3.54</td><td>4.44</td><td>4.33</td><td>4.23</td><td>3.14</td><td>1.21</td><td style="background-color:#F3F3F3; font-weight:bold;">3.66</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11318">엄상백</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.48</td><td>20</td><td>19</td><td>1</td><td>0</td><td>0</td><td>0</td><td>7</td><td>6</td><td>0</td><td>0</td><td>111.2</td><td>45</td><td>46</td><td>45.15</td><td>454</td><td>100</td><td>16</td><td>4</td><td>6</td><td>29</td><td>2</td><td>0</td><td>89</td><td>2</td><td>0</td><td>1</td><td>3.63</td><td>3.71</td><td>3.64</td><td>3.50</td><td>3.36</td><td>1.16</td><td style="background-color:#F3F3F3; font-weight:bold;">3.48</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11489">김재윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.80</td><td>59</td><td>0</td><td>59</td><td>47</td><td>0</td><td>0</td><td>5</td><td>5</td><td>32</td><td>0</td><td>65.2</td><td>19</td><td>21</td><td>21.85</td><td>262</td><td>54</td><td>5</td><td>2</td><td>2</td><td>13</td><td>1</td><td>5</td><td>60</td><td>4</td><td>0</td><td>3</td><td>2.60</td><td>2.88</td><td>2.99</td><td>2.77</td><td>2.40</td><td>1.02</td><td style="background-color:#F3F3F3; font-weight:bold;">2.80</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15089">박영현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.69</td><td>68</td><td>0</td><td>68</td><td>11</td><td>0</td><td>0</td><td>3</td><td>3</td><td>4</td><td>32</td><td>75.1</td><td>23</td><td>25</td><td>27.70</td><td>308</td><td>63</td><td>11</td><td>2</td><td>3</td><td>23</td><td>2</td><td>4</td><td>79</td><td>2</td><td>2</td><td>1</td><td>2.75</td><td>2.99</td><td>3.31</td><td>3.15</td><td>2.65</td><td>1.14</td><td style="background-color:#F3F3F3; font-weight:bold;">2.69</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11394">배제성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.66</td><td>26</td><td>24</td><td>2</td><td>0</td><td>0</td><td>0</td><td>8</td><td>10</td><td>0</td><td>0</td><td>130.1</td><td>65</td><td>72</td><td>67.55</td><td>596</td><td>144</td><td>20</td><td>1</td><td>6</td><td>77</td><td>2</td><td>0</td><td>79</td><td>6</td><td>1</td><td>9</td><td>4.49</td><td>4.97</td><td>4.66</td><td>4.46</td><td>4.76</td><td>1.70</td><td style="background-color:#F3F3F3; font-weight:bold;">2.66</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14108">손동현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.07</td><td>64</td><td>0</td><td>64</td><td>11</td><td>0</td><td>0</td><td>8</td><td>5</td><td>1</td><td>15</td><td>73.2</td><td>28</td><td>31</td><td>30.40</td><td>301</td><td>68</td><td>11</td><td>0</td><td>5</td><td>20</td><td>2</td><td>1</td><td>40</td><td>3</td><td>0</td><td>2</td><td>3.42</td><td>3.79</td><td>3.71</td><td>3.60</td><td>4.23</td><td>1.19</td><td style="background-color:#F3F3F3; font-weight:bold;">2.07</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14109">이상동</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.83</td><td>36</td><td>0</td><td>36</td><td>9</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>1</td><td>40.2</td><td>18</td><td>19</td><td>18.65</td><td>179</td><td>45</td><td>10</td><td>0</td><td>4</td><td>15</td><td>0</td><td>2</td><td>43</td><td>1</td><td>0</td><td>1</td><td>3.98</td><td>4.20</td><td>4.13</td><td>3.94</td><td>3.44</td><td>1.48</td><td style="background-color:#F3F3F3; font-weight:bold;">0.83</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15542">슐서</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.47</td><td>9</td><td>9</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>7</td><td>0</td><td>0</td><td>49.2</td><td>31</td><td>32</td><td>31.00</td><td>221</td><td>66</td><td>9</td><td>1</td><td>6</td><td>14</td><td>0</td><td>1</td><td>35</td><td>1</td><td>0</td><td>2</td><td>5.62</td><td>5.80</td><td>5.62</td><td>5.55</td><td>4.34</td><td>1.61</td><td style="background-color:#F3F3F3; font-weight:bold;">0.47</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11323">주권</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.41</td><td>42</td><td>3</td><td>39</td><td>8</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>5</td><td>47.0</td><td>23</td><td>23</td><td>28.05</td><td>205</td><td>49</td><td>7</td><td>1</td><td>4</td><td>19</td><td>2</td><td>2</td><td>17</td><td>2</td><td>0</td><td>0</td><td>4.40</td><td>4.40</td><td>5.37</td><td>5.19</td><td>5.28</td><td>1.45</td><td style="background-color:#F3F3F3; font-weight:bold;">0.41</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14111">이선우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.35</td><td>22</td><td>4</td><td>18</td><td>8</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>37.1</td><td>18</td><td>20</td><td>21.75</td><td>169</td><td>47</td><td>6</td><td>0</td><td>5</td><td>9</td><td>4</td><td>0</td><td>24</td><td>2</td><td>0</td><td>0</td><td>4.34</td><td>4.82</td><td>5.24</td><td>5.00</td><td>4.92</td><td>1.50</td><td style="background-color:#F3F3F3; font-weight:bold;">0.35</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14106">전용주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.34</td><td>15</td><td>0</td><td>15</td><td>4</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>1</td><td>10.1</td><td>5</td><td>5</td><td>3.15</td><td>43</td><td>6</td><td>4</td><td>0</td><td>0</td><td>6</td><td>1</td><td>0</td><td>9</td><td>0</td><td>0</td><td>4</td><td>4.35</td><td>4.35</td><td>2.74</td><td>2.74</td><td>3.77</td><td>1.16</td><td style="background-color:#F3F3F3; font-weight:bold;">0.34</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14869">김영현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.30</td><td>31</td><td>0</td><td>31</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>33.0</td><td>20</td><td>22</td><td>20.30</td><td>150</td><td>30</td><td>7</td><td>0</td><td>4</td><td>20</td><td>1</td><td>1</td><td>35</td><td>1</td><td>0</td><td>2</td><td>5.45</td><td>6.00</td><td>5.54</td><td>5.18</td><td>4.61</td><td>1.52</td><td style="background-color:#F3F3F3; font-weight:bold;">0.30</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15527">강건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.22</td><td>4</td><td>0</td><td>4</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>6.2</td><td>1</td><td>1</td><td>1.70</td><td>28</td><td>4</td><td>2</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>8</td><td>1</td><td>0</td><td>1</td><td>1.35</td><td>1.35</td><td>2.30</td><td>2.10</td><td>2.24</td><td>1.05</td><td style="background-color:#F3F3F3; font-weight:bold;">0.22</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12572">박세진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.06</td><td>16</td><td>0</td><td>16</td><td>3</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>1</td><td>11.2</td><td>5</td><td>8</td><td>7.65</td><td>66</td><td>15</td><td>2</td><td>0</td><td>1</td><td>14</td><td>0</td><td>0</td><td>10</td><td>3</td><td>0</td><td>2</td><td>3.86</td><td>6.17</td><td>5.90</td><td>5.52</td><td>6.45</td><td>2.49</td><td style="background-color:#F3F3F3; font-weight:bold;">0.06</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10304">하준호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.04</td><td>12</td><td>0</td><td>12</td><td>5</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>13.0</td><td>6</td><td>9</td><td>9.00</td><td>65</td><td>14</td><td>1</td><td>0</td><td>0</td><td>10</td><td>5</td><td>2</td><td>6</td><td>1</td><td>0</td><td>4</td><td>4.15</td><td>6.23</td><td>6.23</td><td>6.01</td><td>6.27</td><td>1.85</td><td style="background-color:#F3F3F3; font-weight:bold;">0.04</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15518">김정운</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.03</td><td>5</td><td>0</td><td>5</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7.0</td><td>3</td><td>4</td><td>5.20</td><td>35</td><td>6</td><td>2</td><td>0</td><td>0</td><td>6</td><td>2</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>3.86</td><td>5.14</td><td>6.69</td><td>6.13</td><td>6.32</td><td>1.71</td><td style="background-color:#F3F3F3; font-weight:bold;">0.03</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11316">조현우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.02</td><td>5</td><td>0</td><td>5</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.0</td><td>2</td><td>2</td><td>2.00</td><td>17</td><td>6</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>6.00</td><td>6.00</td><td>6.00</td><td>5.69</td><td>5.08</td><td>2.67</td><td style="background-color:#F3F3F3; font-weight:bold;">0.02</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13130">이채호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.05</td><td>25</td><td>0</td><td>25</td><td>5</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>1</td><td>24.2</td><td>19</td><td>19</td><td>18.50</td><td>110</td><td>26</td><td>6</td><td>0</td><td>6</td><td>9</td><td>3</td><td>0</td><td>8</td><td>1</td><td>0</td><td>1</td><td>6.93</td><td>6.93</td><td>6.75</td><td>6.47</td><td>7.44</td><td>1.42</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.05</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11317">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.11</td><td>14</td><td>0</td><td>14</td><td>5</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>3</td><td>13.0</td><td>10</td><td>10</td><td>9.80</td><td>58</td><td>17</td><td>5</td><td>2</td><td>1</td><td>5</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>6.92</td><td>6.92</td><td>6.78</td><td>6.59</td><td>5.19</td><td>1.69</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.11</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11311">심재민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.14</td><td>4</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.0</td><td>5</td><td>5</td><td>3.40</td><td>16</td><td>8</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>22.50</td><td>22.50</td><td>15.30</td><td>14.03</td><td>5.70</td><td>5.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.14</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13167">김민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.17</td><td>16</td><td>4</td><td>12</td><td>5</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>29.0</td><td>22</td><td>26</td><td>24.30</td><td>145</td><td>40</td><td>6</td><td>0</td><td>3</td><td>16</td><td>4</td><td>0</td><td>22</td><td>3</td><td>0</td><td>4</td><td>6.83</td><td>8.07</td><td>7.54</td><td>7.27</td><td>5.32</td><td>1.93</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.17</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12577">김태오</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.22</td><td>5</td><td>0</td><td>5</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7.1</td><td>6</td><td>6</td><td>8.05</td><td>35</td><td>10</td><td>3</td><td>0</td><td>0</td><td>4</td><td>0</td><td>1</td><td>3</td><td>1</td><td>0</td><td>0</td><td>7.36</td><td>7.36</td><td>9.88</td><td>10.19</td><td>4.09</td><td>1.91</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.22</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14600">소형준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.23</td><td>3</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>11.0</td><td>14</td><td>14</td><td>12.95</td><td>59</td><td>22</td><td>4</td><td>0</td><td>1</td><td>3</td><td>3</td><td>0</td><td>4</td><td>2</td><td>0</td><td>2</td><td>11.45</td><td>11.45</td><td>10.60</td><td>9.75</td><td>5.71</td><td>2.27</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.23</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11284">조이현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.43</td><td>18</td><td>4</td><td>14</td><td>4</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>1</td><td>35.0</td><td>26</td><td>27</td><td>31.95</td><td>170</td><td>61</td><td>14</td><td>1</td><td>3</td><td>6</td><td>2</td><td>0</td><td>17</td><td>1</td><td>1</td><td>1</td><td>6.69</td><td>6.94</td><td>8.22</td><td>7.95</td><td>4.36</td><td>1.91</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.43</td></tr>			</tbody>
		</table>
""")

In [40]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14617">뷰캐넌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">6.29</td><td>30</td><td>30</td><td>0</td><td>1</td><td>1</td><td>0</td><td>12</td><td>8</td><td>0</td><td>0</td><td>188.0</td><td>53</td><td>71</td><td>69.95</td><td>784</td><td>174</td><td>25</td><td>2</td><td>4</td><td>43</td><td>6</td><td>1</td><td>139</td><td>13</td><td>1</td><td>7</td><td>2.54</td><td>3.40</td><td>3.35</td><td>3.25</td><td>3.05</td><td>1.15</td><td style="background-color:#F3F3F3; font-weight:bold;">6.29</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14113">원태인</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.43</td><td>26</td><td>26</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>150.0</td><td>54</td><td>61</td><td>59.95</td><td>634</td><td>157</td><td>26</td><td>1</td><td>15</td><td>34</td><td>6</td><td>2</td><td>102</td><td>4</td><td>2</td><td>6</td><td>3.24</td><td>3.66</td><td>3.60</td><td>3.58</td><td>4.17</td><td>1.27</td><td style="background-color:#F3F3F3; font-weight:bold;">4.43</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10363">백정현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.92</td><td>18</td><td>18</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>5</td><td>0</td><td>0</td><td>100.2</td><td>41</td><td>44</td><td>42.10</td><td>419</td><td>100</td><td>19</td><td>2</td><td>6</td><td>30</td><td>0</td><td>2</td><td>61</td><td>1</td><td>1</td><td>5</td><td>3.67</td><td>3.93</td><td>3.76</td><td>3.63</td><td>3.91</td><td>1.29</td><td style="background-color:#F3F3F3; font-weight:bold;">2.92</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15001">수아레즈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.55</td><td>19</td><td>19</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>7</td><td>0</td><td>0</td><td>108.0</td><td>47</td><td>54</td><td>51.05</td><td>479</td><td>129</td><td>19</td><td>1</td><td>3</td><td>32</td><td>2</td><td>0</td><td>88</td><td>10</td><td>0</td><td>6</td><td>3.92</td><td>4.50</td><td>4.25</td><td>4.09</td><td>3.12</td><td>1.49</td><td style="background-color:#F3F3F3; font-weight:bold;">2.55</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10367">오승환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.99</td><td>58</td><td>1</td><td>57</td><td>49</td><td>0</td><td>0</td><td>4</td><td>5</td><td>30</td><td>2</td><td>62.2</td><td>24</td><td>26</td><td>32.00</td><td>264</td><td>57</td><td>11</td><td>1</td><td>9</td><td>15</td><td>2</td><td>1</td><td>44</td><td>5</td><td>0</td><td>0</td><td>3.45</td><td>3.73</td><td>4.60</td><td>4.50</td><td>4.59</td><td>1.15</td><td style="background-color:#F3F3F3; font-weight:bold;">0.99</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15536">와이드너</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.94</td><td>10</td><td>9</td><td>1</td><td>0</td><td>0</td><td>0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>53.1</td><td>27</td><td>30</td><td>28.80</td><td>236</td><td>61</td><td>9</td><td>0</td><td>3</td><td>17</td><td>3</td><td>0</td><td>42</td><td>4</td><td>0</td><td>2</td><td>4.56</td><td>5.06</td><td>4.86</td><td>4.63</td><td>3.71</td><td>1.46</td><td style="background-color:#F3F3F3; font-weight:bold;">0.94</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10527">이승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.69</td><td>60</td><td>0</td><td>60</td><td>8</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>14</td><td>60.0</td><td>24</td><td>29</td><td>32.45</td><td>264</td><td>68</td><td>12</td><td>1</td><td>5</td><td>15</td><td>0</td><td>1</td><td>42</td><td>5</td><td>0</td><td>2</td><td>3.60</td><td>4.35</td><td>4.87</td><td>4.78</td><td>3.81</td><td>1.38</td><td style="background-color:#F3F3F3; font-weight:bold;">0.69</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15496">이호성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.65</td><td>5</td><td>2</td><td>3</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>17.0</td><td>5</td><td>5</td><td>5.00</td><td>71</td><td>11</td><td>4</td><td>1</td><td>1</td><td>10</td><td>0</td><td>0</td><td>11</td><td>1</td><td>0</td><td>1</td><td>2.65</td><td>2.65</td><td>2.65</td><td>2.47</td><td>4.76</td><td>1.24</td><td style="background-color:#F3F3F3; font-weight:bold;">0.65</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10685">김대우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.39</td><td>44</td><td>5</td><td>39</td><td>5</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>4</td><td>64.0</td><td>32</td><td>37</td><td>39.90</td><td>277</td><td>66</td><td>9</td><td>1</td><td>7</td><td>22</td><td>3</td><td>1</td><td>49</td><td>3</td><td>0</td><td>1</td><td>4.50</td><td>5.20</td><td>5.61</td><td>5.47</td><td>4.40</td><td>1.38</td><td style="background-color:#F3F3F3; font-weight:bold;">0.39</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13244">이재익</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.29</td><td>51</td><td>0</td><td>51</td><td>5</td><td>0</td><td>0</td><td>1</td><td>3</td><td>0</td><td>11</td><td>41.0</td><td>18</td><td>19</td><td>24.50</td><td>181</td><td>46</td><td>5</td><td>1</td><td>3</td><td>17</td><td>0</td><td>3</td><td>26</td><td>3</td><td>0</td><td>3</td><td>3.95</td><td>4.17</td><td>5.38</td><td>5.20</td><td>4.27</td><td>1.54</td><td style="background-color:#F3F3F3; font-weight:bold;">0.29</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12885">문용익</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.28</td><td>14</td><td>0</td><td>14</td><td>7</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>13.0</td><td>6</td><td>6</td><td>5.50</td><td>59</td><td>8</td><td>1</td><td>0</td><td>0</td><td>12</td><td>2</td><td>0</td><td>12</td><td>0</td><td>0</td><td>5</td><td>4.15</td><td>4.15</td><td>3.81</td><td>3.62</td><td>4.88</td><td>1.54</td><td style="background-color:#F3F3F3; font-weight:bold;">0.28</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10523">우규민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.27</td><td>56</td><td>0</td><td>56</td><td>4</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>13</td><td>43.0</td><td>23</td><td>25</td><td>25.25</td><td>188</td><td>55</td><td>9</td><td>0</td><td>3</td><td>5</td><td>3</td><td>0</td><td>28</td><td>1</td><td>0</td><td>0</td><td>4.81</td><td>5.23</td><td>5.28</td><td>5.16</td><td>3.63</td><td>1.40</td><td style="background-color:#F3F3F3; font-weight:bold;">0.27</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14799">이재희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.15</td><td>2</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8.0</td><td>3</td><td>3</td><td>3.00</td><td>33</td><td>4</td><td>1</td><td>0</td><td>1</td><td>5</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>1</td><td>3.38</td><td>3.38</td><td>3.38</td><td>3.52</td><td>5.71</td><td>1.13</td><td style="background-color:#F3F3F3; font-weight:bold;">0.15</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14614">홍원표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.13</td><td>3</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.2</td><td>1</td><td>1</td><td>0.50</td><td>15</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>2.45</td><td>2.45</td><td>1.23</td><td>1.22</td><td>4.86</td><td>1.09</td><td style="background-color:#F3F3F3; font-weight:bold;">0.13</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14798">이승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.07</td><td>48</td><td>0</td><td>48</td><td>12</td><td>0</td><td>0</td><td>1</td><td>5</td><td>5</td><td>7</td><td>43.1</td><td>24</td><td>26</td><td>27.20</td><td>199</td><td>41</td><td>6</td><td>0</td><td>6</td><td>29</td><td>2</td><td>1</td><td>37</td><td>4</td><td>0</td><td>2</td><td>4.98</td><td>5.40</td><td>5.65</td><td>5.47</td><td>5.51</td><td>1.62</td><td style="background-color:#F3F3F3; font-weight:bold;">0.07</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15497">박권후</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.01</td><td>4</td><td>0</td><td>4</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.2</td><td>1</td><td>2</td><td>2.00</td><td>13</td><td>4</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>3.38</td><td>6.75</td><td>6.75</td><td>6.31</td><td>9.47</td><td>1.88</td><td style="background-color:#F3F3F3; font-weight:bold;">0.01</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13156">최채흥</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.02</td><td>15</td><td>14</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>7</td><td>0</td><td>0</td><td>63.1</td><td>47</td><td>52</td><td>46.85</td><td>295</td><td>90</td><td>13</td><td>3</td><td>9</td><td>16</td><td>3</td><td>1</td><td>33</td><td>6</td><td>1</td><td>1</td><td>6.68</td><td>7.39</td><td>6.66</td><td>6.55</td><td>5.12</td><td>1.67</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.02</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15039">김서준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>8</td><td>1</td><td>7</td><td>5</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>1</td><td>7.2</td><td>6</td><td>6</td><td>5.15</td><td>39</td><td>9</td><td>2</td><td>0</td><td>0</td><td>6</td><td>2</td><td>0</td><td>2</td><td>0</td><td>0</td><td>3</td><td>7.04</td><td>7.04</td><td>6.05</td><td>5.80</td><td>6.43</td><td>1.96</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14615">황동재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.11</td><td>7</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>31.2</td><td>25</td><td>27</td><td>25.80</td><td>155</td><td>40</td><td>14</td><td>1</td><td>6</td><td>21</td><td>2</td><td>0</td><td>27</td><td>1</td><td>0</td><td>0</td><td>7.11</td><td>7.67</td><td>7.33</td><td>7.06</td><td>6.22</td><td>1.93</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.11</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12530">최충연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.12</td><td>7</td><td>0</td><td>7</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9.1</td><td>5</td><td>8</td><td>9.05</td><td>47</td><td>10</td><td>1</td><td>0</td><td>3</td><td>7</td><td>3</td><td>0</td><td>8</td><td>1</td><td>1</td><td>0</td><td>4.82</td><td>7.71</td><td>8.73</td><td>8.31</td><td>8.85</td><td>1.82</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.12</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12932">김시현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.13</td><td>2</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.0</td><td>4</td><td>5</td><td>5.00</td><td>17</td><td>6</td><td>1</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>12.00</td><td>15.00</td><td>15.00</td><td>14.11</td><td>12.18</td><td>2.67</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.13</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12934">최지광</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.13</td><td>22</td><td>0</td><td>22</td><td>4</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td>17.1</td><td>10</td><td>10</td><td>13.75</td><td>82</td><td>17</td><td>2</td><td>0</td><td>4</td><td>9</td><td>1</td><td>0</td><td>18</td><td>1</td><td>0</td><td>0</td><td>5.19</td><td>5.19</td><td>7.14</td><td>6.69</td><td>5.79</td><td>1.50</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.13</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12651">박세웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.15</td><td>2</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.2</td><td>2</td><td>2</td><td>2.35</td><td>6</td><td>1</td><td>0</td><td>0</td><td>1</td><td>3</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>27.00</td><td>27.00</td><td>31.73</td><td>29.85</td><td>31.90</td><td>6.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.15</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14613">허윤동</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.30</td><td>7</td><td>1</td><td>6</td><td>3</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>10.2</td><td>12</td><td>12</td><td>12.70</td><td>60</td><td>16</td><td>7</td><td>0</td><td>0</td><td>12</td><td>0</td><td>0</td><td>8</td><td>1</td><td>0</td><td>0</td><td>10.13</td><td>10.13</td><td>10.72</td><td>10.64</td><td>5.46</td><td>2.63</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.30</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11144">노건우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.31</td><td>16</td><td>0</td><td>16</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>1</td><td>12.1</td><td>10</td><td>11</td><td>12.65</td><td>65</td><td>22</td><td>3</td><td>0</td><td>3</td><td>5</td><td>1</td><td>0</td><td>12</td><td>1</td><td>0</td><td>1</td><td>7.30</td><td>8.03</td><td>9.23</td><td>9.12</td><td>5.82</td><td>2.19</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.31</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11169">이상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.31</td><td>23</td><td>0</td><td>23</td><td>4</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>1</td><td>18.0</td><td>17</td><td>17</td><td>15.30</td><td>83</td><td>32</td><td>3</td><td>1</td><td>2</td><td>3</td><td>0</td><td>0</td><td>17</td><td>0</td><td>0</td><td>0</td><td>8.50</td><td>8.50</td><td>7.65</td><td>7.29</td><td>3.33</td><td>1.94</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.31</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11404">장필준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.38</td><td>17</td><td>3</td><td>14</td><td>5</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td><td>19.1</td><td>17</td><td>17</td><td>18.20</td><td>96</td><td>28</td><td>5</td><td>3</td><td>2</td><td>12</td><td>2</td><td>0</td><td>11</td><td>0</td><td>0</td><td>0</td><td>7.91</td><td>7.91</td><td>8.47</td><td>8.25</td><td>5.90</td><td>2.07</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.38</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13242">홍정우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.40</td><td>36</td><td>1</td><td>35</td><td>5</td><td>0</td><td>0</td><td>2</td><td>3</td><td>0</td><td>3</td><td>36.0</td><td>30</td><td>31</td><td>27.70</td><td>166</td><td>36</td><td>3</td><td>1</td><td>5</td><td>21</td><td>3</td><td>2</td><td>22</td><td>4</td><td>0</td><td>2</td><td>7.50</td><td>7.75</td><td>6.93</td><td>6.69</td><td>5.95</td><td>1.58</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.40</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13157">양창섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.43</td><td>15</td><td>4</td><td>11</td><td>1</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>2</td><td>28.2</td><td>29</td><td>29</td><td>27.80</td><td>141</td><td>45</td><td>5</td><td>1</td><td>7</td><td>16</td><td>1</td><td>1</td><td>12</td><td>0</td><td>0</td><td>2</td><td>9.10</td><td>9.10</td><td>8.73</td><td>8.54</td><td>7.55</td><td>2.13</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.43</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10871">김태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.60</td><td>63</td><td>0</td><td>63</td><td>16</td><td>0</td><td>0</td><td>5</td><td>7</td><td>3</td><td>8</td><td>55.2</td><td>45</td><td>48</td><td>42.20</td><td>268</td><td>65</td><td>17</td><td>1</td><td>7</td><td>37</td><td>3</td><td>3</td><td>36</td><td>2</td><td>0</td><td>1</td><td>7.28</td><td>7.76</td><td>6.82</td><td>6.58</td><td>5.90</td><td>1.83</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.60</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13152">최하늘</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.85</td><td>3</td><td>2</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>6.1</td><td>14</td><td>14</td><td>14.35</td><td>40</td><td>14</td><td>6</td><td>0</td><td>2</td><td>5</td><td>2</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>19.89</td><td>19.89</td><td>20.39</td><td>20.69</td><td>9.85</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.85</td></tr>			</tbody>
		</table>
""")

In [41]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10126">김광현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.19</td><td>30</td><td>30</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9</td><td>8</td><td>0</td><td>0</td><td>168.1</td><td>66</td><td>75</td><td>72.75</td><td>713</td><td>163</td><td>30</td><td>0</td><td>11</td><td>70</td><td>2</td><td>0</td><td>119</td><td>9</td><td>0</td><td>5</td><td>3.53</td><td>4.01</td><td>3.89</td><td>3.89</td><td>4.19</td><td>1.38</td><td style="background-color:#F3F3F3; font-weight:bold;">4.19</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15644">엘리아스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.36</td><td>22</td><td>21</td><td>1</td><td>1</td><td>0</td><td>0</td><td>8</td><td>6</td><td>0</td><td>0</td><td>131.1</td><td>54</td><td>58</td><td>56.80</td><td>548</td><td>140</td><td>22</td><td>1</td><td>12</td><td>33</td><td>6</td><td>1</td><td>93</td><td>5</td><td>0</td><td>0</td><td>3.70</td><td>3.97</td><td>3.89</td><td>3.78</td><td>4.09</td><td>1.32</td><td style="background-color:#F3F3F3; font-weight:bold;">3.36</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15528">맥카티</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.30</td><td>24</td><td>24</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9</td><td>5</td><td>0</td><td>0</td><td>130.0</td><td>49</td><td>58</td><td>56.80</td><td>543</td><td>124</td><td>19</td><td>2</td><td>10</td><td>45</td><td>1</td><td>0</td><td>116</td><td>6</td><td>1</td><td>4</td><td>3.39</td><td>4.02</td><td>3.93</td><td>3.85</td><td>3.63</td><td>1.30</td><td style="background-color:#F3F3F3; font-weight:bold;">3.30</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10784">서진용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.96</td><td>69</td><td>0</td><td>69</td><td>61</td><td>0</td><td>0</td><td>5</td><td>4</td><td>42</td><td>0</td><td>73.0</td><td>21</td><td>22</td><td>22.70</td><td>325</td><td>63</td><td>6</td><td>0</td><td>3</td><td>49</td><td>4</td><td>6</td><td>64</td><td>1</td><td>0</td><td>5</td><td>2.59</td><td>2.71</td><td>2.80</td><td>2.80</td><td>4.27</td><td>1.53</td><td style="background-color:#F3F3F3; font-weight:bold;">2.96</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10203">노경은</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.89</td><td>76</td><td>0</td><td>76</td><td>6</td><td>0</td><td>0</td><td>9</td><td>5</td><td>2</td><td>30</td><td>83.0</td><td>33</td><td>33</td><td>36.45</td><td>357</td><td>78</td><td>13</td><td>2</td><td>4</td><td>36</td><td>4</td><td>5</td><td>65</td><td>4</td><td>0</td><td>8</td><td>3.58</td><td>3.58</td><td>3.95</td><td>3.92</td><td>3.81</td><td>1.37</td><td style="background-color:#F3F3F3; font-weight:bold;">1.89</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14581">오원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.41</td><td>28</td><td>27</td><td>1</td><td>1</td><td>1</td><td>0</td><td>8</td><td>10</td><td>0</td><td>0</td><td>144.2</td><td>84</td><td>92</td><td>88.25</td><td>648</td><td>158</td><td>22</td><td>2</td><td>11</td><td>69</td><td>9</td><td>0</td><td>88</td><td>10</td><td>0</td><td>11</td><td>5.23</td><td>5.72</td><td>5.49</td><td>5.31</td><td>4.90</td><td>1.57</td><td style="background-color:#F3F3F3; font-weight:bold;">1.41</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10783">문승원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.84</td><td>50</td><td>12</td><td>38</td><td>4</td><td>0</td><td>0</td><td>5</td><td>8</td><td>1</td><td>9</td><td>105.0</td><td>61</td><td>67</td><td>64.45</td><td>479</td><td>138</td><td>27</td><td>1</td><td>12</td><td>35</td><td>6</td><td>1</td><td>65</td><td>8</td><td>0</td><td>3</td><td>5.23</td><td>5.74</td><td>5.52</td><td>5.34</td><td>4.84</td><td>1.65</td><td style="background-color:#F3F3F3; font-weight:bold;">0.84</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10124">고효준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.82</td><td>73</td><td>0</td><td>73</td><td>7</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>13</td><td>58.0</td><td>29</td><td>31</td><td>29.80</td><td>262</td><td>49</td><td>3</td><td>0</td><td>3</td><td>42</td><td>3</td><td>0</td><td>66</td><td>3</td><td>0</td><td>4</td><td>4.50</td><td>4.81</td><td>4.62</td><td>4.48</td><td>4.03</td><td>1.57</td><td style="background-color:#F3F3F3; font-weight:bold;">0.82</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11242">이건욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.72</td><td>27</td><td>1</td><td>26</td><td>10</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>38.2</td><td>9</td><td>13</td><td>16.70</td><td>169</td><td>31</td><td>7</td><td>0</td><td>0</td><td>25</td><td>2</td><td>2</td><td>31</td><td>2</td><td>0</td><td>2</td><td>2.09</td><td>3.03</td><td>3.89</td><td>3.76</td><td>4.01</td><td>1.45</td><td style="background-color:#F3F3F3; font-weight:bold;">0.72</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13126">최민준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.35</td><td>53</td><td>0</td><td>53</td><td>6</td><td>0</td><td>0</td><td>5</td><td>3</td><td>1</td><td>7</td><td>60.0</td><td>28</td><td>29</td><td>34.70</td><td>262</td><td>75</td><td>10</td><td>2</td><td>7</td><td>19</td><td>1</td><td>1</td><td>37</td><td>2</td><td>0</td><td>2</td><td>4.20</td><td>4.35</td><td>5.21</td><td>5.10</td><td>4.68</td><td>1.57</td><td style="background-color:#F3F3F3; font-weight:bold;">0.35</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14145">백승건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.34</td><td>25</td><td>2</td><td>23</td><td>3</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>3</td><td>38.0</td><td>21</td><td>24</td><td>21.75</td><td>170</td><td>41</td><td>5</td><td>0</td><td>7</td><td>17</td><td>0</td><td>0</td><td>29</td><td>2</td><td>0</td><td>0</td><td>4.97</td><td>5.68</td><td>5.15</td><td>5.01</td><td>5.52</td><td>1.53</td><td style="background-color:#F3F3F3; font-weight:bold;">0.34</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10131">박종훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.28</td><td>18</td><td>16</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>6</td><td>0</td><td>0</td><td>80.0</td><td>55</td><td>57</td><td>56.65</td><td>382</td><td>77</td><td>13</td><td>1</td><td>8</td><td>60</td><td>19</td><td>0</td><td>56</td><td>4</td><td>0</td><td>2</td><td>6.19</td><td>6.41</td><td>6.37</td><td>6.10</td><td>6.35</td><td>1.71</td><td style="background-color:#F3F3F3; font-weight:bold;">0.28</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11236">박민호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.28</td><td>10</td><td>0</td><td>10</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10.0</td><td>1</td><td>3</td><td>3.00</td><td>47</td><td>14</td><td>1</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td>0.90</td><td>2.70</td><td>2.70</td><td>2.70</td><td>3.78</td><td>1.50</td><td style="background-color:#F3F3F3; font-weight:bold;">0.28</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13191">서동민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.05</td><td>2</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0.00</td><td>6</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>10.65</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">0.05</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13125">조성훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.02</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>7.0</td><td>5</td><td>5</td><td>5.00</td><td>34</td><td>10</td><td>1</td><td>0</td><td>0</td><td>4</td><td>2</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>6.43</td><td>6.43</td><td>6.43</td><td>6.12</td><td>5.08</td><td>2.00</td><td style="background-color:#F3F3F3; font-weight:bold;">0.02</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13228">한두솔</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.01</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.0</td><td>1</td><td>1</td><td>1.00</td><td>6</td><td>1</td><td>0</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>9.00</td><td>9.00</td><td>9.00</td><td>8.57</td><td>5.05</td><td>2.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.01</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12531">김주한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.02</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>3</td><td>3</td><td>3.00</td><td>3</td><td>2</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>99.99</td><td>99.99</td><td>85.64</td><td>81.82</td><td>15003.80</td><td>99.99</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.02</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15028">이기순</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>2</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.0</td><td>3</td><td>3</td><td>3.00</td><td>16</td><td>3</td><td>0</td><td>0</td><td>1</td><td>4</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>9.00</td><td>9.00</td><td>9.00</td><td>8.57</td><td>9.45</td><td>2.33</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15024">신헌민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.06</td><td>11</td><td>0</td><td>11</td><td>11</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>12.0</td><td>8</td><td>10</td><td>10.35</td><td>62</td><td>19</td><td>6</td><td>0</td><td>1</td><td>6</td><td>0</td><td>1</td><td>8</td><td>3</td><td>0</td><td>0</td><td>6.00</td><td>7.50</td><td>7.76</td><td>7.28</td><td>4.47</td><td>2.08</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.06</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14152">서상준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.06</td><td>2</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.0</td><td>0</td><td>3</td><td>3.00</td><td>13</td><td>1</td><td>0</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>1</td><td>0.00</td><td>13.50</td><td>13.50</td><td>12.38</td><td>7.85</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.06</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15462">송영진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.08</td><td>17</td><td>9</td><td>8</td><td>1</td><td>0</td><td>0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>47.1</td><td>30</td><td>35</td><td>34.65</td><td>220</td><td>46</td><td>9</td><td>1</td><td>3</td><td>31</td><td>2</td><td>0</td><td>38</td><td>5</td><td>2</td><td>8</td><td>5.70</td><td>6.65</td><td>6.59</td><td>6.50</td><td>4.76</td><td>1.63</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.08</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15461">이로운</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.08</td><td>50</td><td>0</td><td>50</td><td>14</td><td>0</td><td>0</td><td>6</td><td>1</td><td>0</td><td>5</td><td>57.2</td><td>36</td><td>39</td><td>41.05</td><td>268</td><td>67</td><td>13</td><td>1</td><td>7</td><td>29</td><td>1</td><td>2</td><td>52</td><td>4</td><td>0</td><td>3</td><td>5.62</td><td>6.09</td><td>6.41</td><td>6.16</td><td>4.65</td><td>1.66</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.08</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13057">김주온</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.11</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.1</td><td>3</td><td>3</td><td>2.15</td><td>5</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>81.00</td><td>81.00</td><td>58.05</td><td>63.40</td><td>14.95</td><td>9.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.11</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10795">임준섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.21</td><td>41</td><td>0</td><td>41</td><td>11</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>4</td><td>32.2</td><td>21</td><td>25</td><td>24.15</td><td>155</td><td>44</td><td>6</td><td>0</td><td>1</td><td>19</td><td>1</td><td>1</td><td>26</td><td>1</td><td>0</td><td>2</td><td>5.79</td><td>6.89</td><td>6.65</td><td>6.58</td><td>4.12</td><td>1.93</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.21</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11321">정성곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.36</td><td>6</td><td>0</td><td>6</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4.1</td><td>5</td><td>9</td><td>9.85</td><td>29</td><td>8</td><td>3</td><td>0</td><td>2</td><td>7</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>10.38</td><td>18.69</td><td>20.46</td><td>19.23</td><td>12.62</td><td>3.46</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.36</td></tr>			</tbody>
		</table>
""")

In [42]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15535">페디</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">8.47</td><td>30</td><td>30</td><td>0</td><td>0</td><td>0</td><td>0</td><td>20</td><td>6</td><td>0</td><td>0</td><td>180.1</td><td>40</td><td>46</td><td>44.95</td><td>708</td><td>137</td><td>16</td><td>0</td><td>9</td><td>35</td><td>4</td><td>0</td><td>209</td><td>13</td><td>0</td><td>5</td><td>2.00</td><td>2.30</td><td>2.24</td><td>2.25</td><td>2.22</td><td>0.95</td><td style="background-color:#F3F3F3; font-weight:bold;">8.47</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11355">류진욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.72</td><td>70</td><td>0</td><td>70</td><td>9</td><td>0</td><td>0</td><td>1</td><td>4</td><td>0</td><td>22</td><td>67.0</td><td>16</td><td>19</td><td>18.95</td><td>268</td><td>41</td><td>2</td><td>2</td><td>1</td><td>32</td><td>1</td><td>1</td><td>62</td><td>5</td><td>0</td><td>5</td><td>2.15</td><td>2.55</td><td>2.55</td><td>2.50</td><td>3.24</td><td>1.09</td><td style="background-color:#F3F3F3; font-weight:bold;">2.72</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13085">신민혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.29</td><td>29</td><td>24</td><td>5</td><td>2</td><td>0</td><td>0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>122.0</td><td>54</td><td>63</td><td>63.00</td><td>519</td><td>122</td><td>27</td><td>2</td><td>14</td><td>25</td><td>6</td><td>0</td><td>97</td><td>11</td><td>0</td><td>3</td><td>3.98</td><td>4.65</td><td>4.65</td><td>4.60</td><td>4.01</td><td>1.20</td><td style="background-color:#F3F3F3; font-weight:bold;">2.29</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15653">태너</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.05</td><td>11</td><td>11</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>2</td><td>0</td><td>0</td><td>64.2</td><td>21</td><td>26</td><td>24.65</td><td>265</td><td>58</td><td>8</td><td>0</td><td>6</td><td>13</td><td>1</td><td>0</td><td>47</td><td>3</td><td>0</td><td>0</td><td>2.92</td><td>3.62</td><td>3.43</td><td>3.45</td><td>3.81</td><td>1.10</td><td style="background-color:#F3F3F3; font-weight:bold;">2.05</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11353">구창모</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.87</td><td>11</td><td>9</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>3</td><td>0</td><td>0</td><td>51.2</td><td>17</td><td>19</td><td>17.80</td><td>205</td><td>38</td><td>3</td><td>0</td><td>4</td><td>16</td><td>0</td><td>0</td><td>56</td><td>5</td><td>0</td><td>0</td><td>2.96</td><td>3.31</td><td>3.10</td><td>3.06</td><td>3.02</td><td>1.05</td><td style="background-color:#F3F3F3; font-weight:bold;">1.87</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13088">김영규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.42</td><td>63</td><td>0</td><td>63</td><td>5</td><td>0</td><td>0</td><td>2</td><td>4</td><td>0</td><td>24</td><td>61.2</td><td>21</td><td>22</td><td>26.30</td><td>247</td><td>45</td><td>6</td><td>5</td><td>2</td><td>23</td><td>1</td><td>1</td><td>48</td><td>0</td><td>2</td><td>5</td><td>3.06</td><td>3.21</td><td>3.84</td><td>3.93</td><td>3.50</td><td>1.10</td><td style="background-color:#F3F3F3; font-weight:bold;">1.42</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10220">이재학</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.26</td><td>15</td><td>13</td><td>2</td><td>0</td><td>0</td><td>0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>67.1</td><td>34</td><td>36</td><td>34.30</td><td>293</td><td>55</td><td>5</td><td>2</td><td>6</td><td>33</td><td>5</td><td>0</td><td>43</td><td>4</td><td>0</td><td>7</td><td>4.54</td><td>4.81</td><td>4.58</td><td>4.60</td><td>5.06</td><td>1.31</td><td style="background-color:#F3F3F3; font-weight:bold;">1.26</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10217">이용찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.22</td><td>60</td><td>0</td><td>60</td><td>50</td><td>0</td><td>0</td><td>4</td><td>4</td><td>29</td><td>0</td><td>61.0</td><td>28</td><td>28</td><td>28.85</td><td>254</td><td>53</td><td>6</td><td>1</td><td>5</td><td>19</td><td>3</td><td>1</td><td>51</td><td>2</td><td>0</td><td>4</td><td>4.13</td><td>4.13</td><td>4.26</td><td>4.25</td><td>3.80</td><td>1.18</td><td style="background-color:#F3F3F3; font-weight:bold;">1.22</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14155">송명기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.10</td><td>35</td><td>17</td><td>18</td><td>4</td><td>0</td><td>0</td><td>4</td><td>9</td><td>0</td><td>0</td><td>104.1</td><td>56</td><td>64</td><td>61.60</td><td>474</td><td>106</td><td>15</td><td>2</td><td>12</td><td>47</td><td>11</td><td>0</td><td>65</td><td>8</td><td>0</td><td>6</td><td>4.83</td><td>5.52</td><td>5.31</td><td>5.33</td><td>5.38</td><td>1.47</td><td style="background-color:#F3F3F3; font-weight:bold;">1.10</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12565">최성영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.08</td><td>18</td><td>13</td><td>5</td><td>0</td><td>0</td><td>0</td><td>5</td><td>4</td><td>0</td><td>0</td><td>66.2</td><td>36</td><td>37</td><td>35.30</td><td>303</td><td>77</td><td>15</td><td>2</td><td>6</td><td>32</td><td>5</td><td>0</td><td>38</td><td>2</td><td>0</td><td>1</td><td>4.86</td><td>5.00</td><td>4.77</td><td>4.76</td><td>5.22</td><td>1.64</td><td style="background-color:#F3F3F3; font-weight:bold;">1.08</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15536">와이드너</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.92</td><td>11</td><td>11</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>2</td><td>0</td><td>0</td><td>61.2</td><td>31</td><td>35</td><td>34.30</td><td>259</td><td>51</td><td>13</td><td>0</td><td>4</td><td>23</td><td>3</td><td>1</td><td>57</td><td>3</td><td>0</td><td>1</td><td>4.52</td><td>5.11</td><td>5.01</td><td>4.95</td><td>3.62</td><td>1.20</td><td style="background-color:#F3F3F3; font-weight:bold;">0.92</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14763">이용준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.71</td><td>24</td><td>12</td><td>12</td><td>3</td><td>0</td><td>0</td><td>3</td><td>4</td><td>0</td><td>0</td><td>67.0</td><td>32</td><td>39</td><td>39.65</td><td>304</td><td>60</td><td>11</td><td>0</td><td>5</td><td>44</td><td>2</td><td>0</td><td>50</td><td>7</td><td>0</td><td>1</td><td>4.30</td><td>5.24</td><td>5.33</td><td>5.30</td><td>5.00</td><td>1.55</td><td style="background-color:#F3F3F3; font-weight:bold;">0.71</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12897">김진호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.53</td><td>19</td><td>0</td><td>19</td><td>1</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>9</td><td>16.1</td><td>5</td><td>5</td><td>6.00</td><td>73</td><td>15</td><td>2</td><td>0</td><td>0</td><td>10</td><td>1</td><td>0</td><td>22</td><td>0</td><td>0</td><td>3</td><td>2.76</td><td>2.76</td><td>3.31</td><td>3.24</td><td>2.57</td><td>1.53</td><td style="background-color:#F3F3F3; font-weight:bold;">0.53</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11168">임정호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.44</td><td>65</td><td>0</td><td>65</td><td>7</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>15</td><td>50.0</td><td>26</td><td>30</td><td>27.60</td><td>216</td><td>51</td><td>9</td><td>1</td><td>3</td><td>17</td><td>4</td><td>0</td><td>49</td><td>6</td><td>1</td><td>4</td><td>4.68</td><td>5.40</td><td>4.97</td><td>5.05</td><td>3.42</td><td>1.36</td><td style="background-color:#F3F3F3; font-weight:bold;">0.44</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13115">하준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.44</td><td>57</td><td>0</td><td>57</td><td>13</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>2</td><td>49.0</td><td>25</td><td>25</td><td>27.50</td><td>215</td><td>52</td><td>6</td><td>1</td><td>4</td><td>19</td><td>2</td><td>1</td><td>49</td><td>1</td><td>0</td><td>0</td><td>4.59</td><td>4.59</td><td>5.05</td><td>5.11</td><td>3.65</td><td>1.45</td><td style="background-color:#F3F3F3; font-weight:bold;">0.44</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15119">조민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.35</td><td>35</td><td>0</td><td>35</td><td>8</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>4</td><td>31.0</td><td>14</td><td>15</td><td>17.05</td><td>137</td><td>33</td><td>9</td><td>0</td><td>2</td><td>14</td><td>3</td><td>0</td><td>28</td><td>2</td><td>0</td><td>1</td><td>4.06</td><td>4.35</td><td>4.95</td><td>4.89</td><td>4.06</td><td>1.52</td><td style="background-color:#F3F3F3; font-weight:bold;">0.35</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13080">김시훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.15</td><td>61</td><td>0</td><td>61</td><td>13</td><td>0</td><td>0</td><td>4</td><td>3</td><td>3</td><td>12</td><td>52.2</td><td>26</td><td>32</td><td>31.85</td><td>245</td><td>57</td><td>10</td><td>1</td><td>3</td><td>34</td><td>1</td><td>0</td><td>49</td><td>3</td><td>0</td><td>3</td><td>4.44</td><td>5.47</td><td>5.44</td><td>5.49</td><td>4.26</td><td>1.73</td><td style="background-color:#F3F3F3; font-weight:bold;">0.15</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12898">김태현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.10</td><td>16</td><td>0</td><td>16</td><td>9</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>20.1</td><td>10</td><td>13</td><td>13.00</td><td>90</td><td>17</td><td>1</td><td>1</td><td>4</td><td>13</td><td>1</td><td>0</td><td>14</td><td>2</td><td>0</td><td>0</td><td>4.43</td><td>5.75</td><td>5.75</td><td>5.98</td><td>6.60</td><td>1.48</td><td style="background-color:#F3F3F3; font-weight:bold;">0.10</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14156">전사민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.10</td><td>9</td><td>0</td><td>9</td><td>4</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>17.0</td><td>9</td><td>10</td><td>10.15</td><td>81</td><td>17</td><td>1</td><td>0</td><td>1</td><td>14</td><td>2</td><td>1</td><td>6</td><td>0</td><td>0</td><td>1</td><td>4.76</td><td>5.29</td><td>5.37</td><td>5.39</td><td>6.58</td><td>1.82</td><td style="background-color:#F3F3F3; font-weight:bold;">0.10</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10720">심창민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.08</td><td>5</td><td>0</td><td>5</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>3.1</td><td>1</td><td>2</td><td>1.30</td><td>18</td><td>2</td><td>0</td><td>0</td><td>0</td><td>5</td><td>1</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td>2.70</td><td>5.40</td><td>3.51</td><td>3.36</td><td>5.68</td><td>2.10</td><td style="background-color:#F3F3F3; font-weight:bold;">0.08</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14654">하준수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.04</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0.00</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>7.55</td><td>2.00</td><td style="background-color:#F3F3F3; font-weight:bold;">0.04</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15455">이준호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.03</td><td>17</td><td>2</td><td>15</td><td>5</td><td>0</td><td>0</td><td>3</td><td>2</td><td>0</td><td>0</td><td>31.2</td><td>17</td><td>22</td><td>20.80</td><td>144</td><td>32</td><td>4</td><td>1</td><td>3</td><td>15</td><td>4</td><td>0</td><td>19</td><td>2</td><td>0</td><td>2</td><td>4.83</td><td>6.25</td><td>5.91</td><td>6.07</td><td>5.34</td><td>1.48</td><td style="background-color:#F3F3F3; font-weight:bold;">0.03</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11360">이우석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.03</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.2</td><td>0</td><td>0</td><td>0.00</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>8.50</td><td>1.50</td><td style="background-color:#F3F3F3; font-weight:bold;">0.03</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14764">한재승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.00</td><td>11</td><td>0</td><td>11</td><td>5</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>9.2</td><td>5</td><td>5</td><td>6.55</td><td>44</td><td>9</td><td>1</td><td>0</td><td>2</td><td>5</td><td>0</td><td>0</td><td>10</td><td>2</td><td>0</td><td>1</td><td>4.66</td><td>4.66</td><td>6.10</td><td>6.14</td><td>5.33</td><td>1.45</td><td style="background-color:#F3F3F3; font-weight:bold;">0.00</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15115">임지민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.04</td><td>2</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.1</td><td>2</td><td>2</td><td>2.00</td><td>10</td><td>2</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>2</td><td>13.50</td><td>13.50</td><td>13.50</td><td>12.54</td><td>7.52</td><td>4.50</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.04</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11387">채지선</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.05</td><td>2</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.2</td><td>3</td><td>3</td><td>3.00</td><td>16</td><td>4</td><td>1</td><td>1</td><td>0</td><td>4</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td>10.13</td><td>10.13</td><td>10.13</td><td>10.07</td><td>6.62</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.05</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14595">정구범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.09</td><td>4</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>12.2</td><td>11</td><td>11</td><td>11.00</td><td>64</td><td>16</td><td>3</td><td>0</td><td>3</td><td>12</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>0</td><td>7.82</td><td>7.82</td><td>7.82</td><td>7.77</td><td>8.42</td><td>2.21</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.09</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14158">배민서</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.27</td><td>6</td><td>0</td><td>6</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6.2</td><td>5</td><td>8</td><td>9.55</td><td>34</td><td>10</td><td>5</td><td>2</td><td>0</td><td>2</td><td>1</td><td>0</td><td>4</td><td>1</td><td>0</td><td>2</td><td>6.75</td><td>10.80</td><td>12.89</td><td>12.52</td><td>3.74</td><td>1.80</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.27</td></tr>			</tbody>
		</table>
""")

In [43]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13941">알칸타라</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">6.08</td><td>31</td><td>31</td><td>0</td><td>0</td><td>0</td><td>0</td><td>13</td><td>9</td><td>0</td><td>0</td><td>192.0</td><td>57</td><td>67</td><td>67.00</td><td>777</td><td>171</td><td>33</td><td>0</td><td>16</td><td>35</td><td>5</td><td>1</td><td>162</td><td>11</td><td>0</td><td>3</td><td>2.67</td><td>3.14</td><td>3.14</td><td>3.34</td><td>3.38</td><td>1.07</td><td style="background-color:#F3F3F3; font-weight:bold;">6.08</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13061">곽빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">4.42</td><td>23</td><td>23</td><td>0</td><td>0</td><td>0</td><td>0</td><td>12</td><td>7</td><td>0</td><td>0</td><td>127.1</td><td>41</td><td>44</td><td>40.75</td><td>526</td><td>96</td><td>18</td><td>1</td><td>7</td><td>58</td><td>5</td><td>0</td><td>106</td><td>3</td><td>1</td><td>4</td><td>2.90</td><td>3.11</td><td>2.88</td><td>3.10</td><td>3.96</td><td>1.21</td><td style="background-color:#F3F3F3; font-weight:bold;">4.42</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15153">브랜든</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.72</td><td>18</td><td>18</td><td>0</td><td>0</td><td>0</td><td>0</td><td>11</td><td>3</td><td>0</td><td>0</td><td>104.2</td><td>29</td><td>34</td><td>33.50</td><td>427</td><td>80</td><td>13</td><td>0</td><td>4</td><td>30</td><td>12</td><td>0</td><td>100</td><td>3</td><td>0</td><td>3</td><td>2.49</td><td>2.92</td><td>2.88</td><td>3.03</td><td>3.16</td><td>1.05</td><td style="background-color:#F3F3F3; font-weight:bold;">3.72</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14770">최승용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">2.02</td><td>34</td><td>20</td><td>14</td><td>4</td><td>0</td><td>0</td><td>3</td><td>6</td><td>1</td><td>0</td><td>111.0</td><td>49</td><td>54</td><td>52.10</td><td>479</td><td>116</td><td>11</td><td>1</td><td>9</td><td>34</td><td>4</td><td>0</td><td>82</td><td>7</td><td>0</td><td>3</td><td>3.97</td><td>4.38</td><td>4.22</td><td>4.44</td><td>4.03</td><td>1.35</td><td style="background-color:#F3F3F3; font-weight:bold;">2.02</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14769">김동주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.88</td><td>18</td><td>17</td><td>1</td><td>1</td><td>0</td><td>0</td><td>3</td><td>6</td><td>0</td><td>0</td><td>78.1</td><td>36</td><td>37</td><td>33.25</td><td>334</td><td>73</td><td>14</td><td>4</td><td>5</td><td>35</td><td>4</td><td>0</td><td>59</td><td>4</td><td>1</td><td>4</td><td>4.14</td><td>4.25</td><td>3.82</td><td>3.94</td><td>4.27</td><td>1.38</td><td style="background-color:#F3F3F3; font-weight:bold;">1.88</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12852">최원준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.41</td><td>26</td><td>20</td><td>6</td><td>1</td><td>0</td><td>0</td><td>3</td><td>10</td><td>0</td><td>0</td><td>107.2</td><td>59</td><td>60</td><td>58.50</td><td>465</td><td>119</td><td>33</td><td>1</td><td>11</td><td>28</td><td>12</td><td>0</td><td>71</td><td>2</td><td>0</td><td>1</td><td>4.93</td><td>5.02</td><td>4.89</td><td>4.95</td><td>4.57</td><td>1.37</td><td style="background-color:#F3F3F3; font-weight:bold;">1.41</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12847">김명신</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.37</td><td>70</td><td>0</td><td>70</td><td>5</td><td>0</td><td>0</td><td>3</td><td>3</td><td>1</td><td>24</td><td>79.0</td><td>32</td><td>34</td><td>35.65</td><td>334</td><td>72</td><td>18</td><td>0</td><td>3</td><td>27</td><td>6</td><td>3</td><td>65</td><td>3</td><td>0</td><td>3</td><td>3.65</td><td>3.87</td><td>4.06</td><td>4.26</td><td>3.42</td><td>1.25</td><td style="background-color:#F3F3F3; font-weight:bold;">1.37</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10696">홍건희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.23</td><td>64</td><td>0</td><td>64</td><td>40</td><td>0</td><td>0</td><td>1</td><td>5</td><td>22</td><td>5</td><td>61.2</td><td>21</td><td>28</td><td>26.30</td><td>277</td><td>67</td><td>10</td><td>3</td><td>4</td><td>24</td><td>0</td><td>3</td><td>62</td><td>3</td><td>0</td><td>8</td><td>3.06</td><td>4.09</td><td>3.84</td><td>4.07</td><td>3.21</td><td>1.48</td><td style="background-color:#F3F3F3; font-weight:bold;">1.23</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12850">박치국</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.73</td><td>62</td><td>0</td><td>62</td><td>9</td><td>0</td><td>0</td><td>5</td><td>3</td><td>2</td><td>11</td><td>52.2</td><td>21</td><td>22</td><td>25.45</td><td>236</td><td>54</td><td>9</td><td>2</td><td>3</td><td>21</td><td>5</td><td>1</td><td>48</td><td>2</td><td>0</td><td>2</td><td>3.59</td><td>3.76</td><td>4.35</td><td>4.51</td><td>3.49</td><td>1.42</td><td style="background-color:#F3F3F3; font-weight:bold;">0.73</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10690">김강률</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.49</td><td>32</td><td>0</td><td>32</td><td>4</td><td>0</td><td>0</td><td>1</td><td>0</td><td>1</td><td>7</td><td>25.2</td><td>12</td><td>14</td><td>11.05</td><td>115</td><td>23</td><td>3</td><td>0</td><td>2</td><td>12</td><td>2</td><td>0</td><td>21</td><td>2</td><td>0</td><td>2</td><td>4.21</td><td>4.91</td><td>3.87</td><td>4.11</td><td>4.42</td><td>1.36</td><td style="background-color:#F3F3F3; font-weight:bold;">0.49</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15514">백승우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.17</td><td>6</td><td>0</td><td>6</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4.0</td><td>0</td><td>0</td><td>0.50</td><td>18</td><td>3</td><td>0</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0.00</td><td>1.13</td><td>1.23</td><td>6.32</td><td>1.50</td><td style="background-color:#F3F3F3; font-weight:bold;">0.17</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13071">정철원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.16</td><td>67</td><td>0</td><td>67</td><td>24</td><td>0</td><td>0</td><td>7</td><td>6</td><td>13</td><td>11</td><td>72.2</td><td>32</td><td>36</td><td>40.60</td><td>315</td><td>66</td><td>6</td><td>0</td><td>8</td><td>32</td><td>2</td><td>2</td><td>55</td><td>6</td><td>1</td><td>6</td><td>3.96</td><td>4.46</td><td>5.03</td><td>5.25</td><td>4.63</td><td>1.35</td><td style="background-color:#F3F3F3; font-weight:bold;">0.16</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11300">박정수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.16</td><td>25</td><td>0</td><td>25</td><td>11</td><td>0</td><td>0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>36.2</td><td>17</td><td>22</td><td>22.70</td><td>165</td><td>37</td><td>12</td><td>0</td><td>1</td><td>18</td><td>6</td><td>1</td><td>28</td><td>1</td><td>0</td><td>2</td><td>4.17</td><td>5.40</td><td>5.57</td><td>5.67</td><td>4.21</td><td>1.50</td><td style="background-color:#F3F3F3; font-weight:bold;">0.16</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10299">장원준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.14</td><td>11</td><td>10</td><td>1</td><td>0</td><td>0</td><td>0</td><td>3</td><td>5</td><td>0</td><td>0</td><td>41.0</td><td>24</td><td>27</td><td>26.00</td><td>183</td><td>53</td><td>8</td><td>2</td><td>4</td><td>11</td><td>2</td><td>0</td><td>24</td><td>2</td><td>0</td><td>2</td><td>5.27</td><td>5.93</td><td>5.71</td><td>6.04</td><td>4.53</td><td>1.56</td><td style="background-color:#F3F3F3; font-weight:bold;">0.14</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15127">최지강</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.13</td><td>25</td><td>0</td><td>25</td><td>4</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>2</td><td>22.0</td><td>13</td><td>13</td><td>12.50</td><td>102</td><td>16</td><td>4</td><td>0</td><td>0</td><td>20</td><td>1</td><td>0</td><td>14</td><td>2</td><td>0</td><td>0</td><td>5.32</td><td>5.32</td><td>5.11</td><td>5.34</td><td>5.22</td><td>1.64</td><td style="background-color:#F3F3F3; font-weight:bold;">0.13</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13072">김민규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.08</td><td>6</td><td>1</td><td>5</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8.1</td><td>4</td><td>5</td><td>4.30</td><td>37</td><td>6</td><td>2</td><td>1</td><td>0</td><td>4</td><td>2</td><td>0</td><td>5</td><td>0</td><td>0</td><td>2</td><td>4.32</td><td>5.40</td><td>4.64</td><td>4.93</td><td>4.58</td><td>1.20</td><td style="background-color:#F3F3F3; font-weight:bold;">0.08</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13070">박신지</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.02</td><td>15</td><td>1</td><td>14</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>26.0</td><td>16</td><td>16</td><td>16.70</td><td>129</td><td>39</td><td>13</td><td>0</td><td>1</td><td>11</td><td>3</td><td>0</td><td>15</td><td>0</td><td>0</td><td>2</td><td>5.54</td><td>5.54</td><td>5.78</td><td>5.99</td><td>4.53</td><td>1.92</td><td style="background-color:#F3F3F3; font-weight:bold;">0.02</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15538">딜런</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>9.0</td><td>8</td><td>9</td><td>6.95</td><td>45</td><td>10</td><td>1</td><td>0</td><td>2</td><td>5</td><td>0</td><td>0</td><td>2</td><td>3</td><td>0</td><td>1</td><td>8.00</td><td>9.00</td><td>6.95</td><td>7.08</td><td>7.66</td><td>1.67</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13268">김호준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.11</td><td>3</td><td>0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3.0</td><td>4</td><td>4</td><td>4.00</td><td>16</td><td>3</td><td>0</td><td>0</td><td>1</td><td>4</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td>12.00</td><td>12.00</td><td>12.00</td><td>13.11</td><td>10.28</td><td>2.33</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.11</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14573">제환유</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.11</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.0</td><td>3</td><td>4</td><td>3.65</td><td>14</td><td>3</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>1</td><td>13.50</td><td>18.00</td><td>16.43</td><td>15.26</td><td>7.55</td><td>3.50</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.11</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12678">이승진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.11</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.2</td><td>0</td><td>4</td><td>2.45</td><td>6</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0.00</td><td>54.00</td><td>33.08</td><td>36.12</td><td>9.40</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.11</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15099">이병헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.12</td><td>36</td><td>0</td><td>36</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>27.0</td><td>14</td><td>16</td><td>17.90</td><td>126</td><td>25</td><td>7</td><td>0</td><td>2</td><td>22</td><td>1</td><td>0</td><td>28</td><td>1</td><td>0</td><td>3</td><td>4.67</td><td>5.33</td><td>5.97</td><td>6.29</td><td>4.78</td><td>1.74</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.12</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12605">고봉재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.13</td><td>10</td><td>0</td><td>10</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>11.1</td><td>8</td><td>8</td><td>9.55</td><td>53</td><td>12</td><td>2</td><td>1</td><td>0</td><td>7</td><td>1</td><td>0</td><td>7</td><td>1</td><td>0</td><td>0</td><td>6.35</td><td>6.35</td><td>7.58</td><td>7.96</td><td>4.49</td><td>1.68</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.13</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15101">이원재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.13</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1.0</td><td>3</td><td>3</td><td>2.65</td><td>9</td><td>3</td><td>1</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>27.00</td><td>27.00</td><td>23.85</td><td>24.88</td><td>13.15</td><td>6.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.13</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13124">김정우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.21</td><td>7</td><td>0</td><td>7</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6.2</td><td>7</td><td>7</td><td>8.05</td><td>38</td><td>11</td><td>2</td><td>0</td><td>1</td><td>7</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>0</td><td>9.45</td><td>9.45</td><td>10.87</td><td>11.74</td><td>6.64</td><td>2.70</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.21</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12568">이영하</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.29</td><td>36</td><td>0</td><td>36</td><td>5</td><td>0</td><td>0</td><td>5</td><td>3</td><td>0</td><td>4</td><td>39.1</td><td>24</td><td>27</td><td>25.95</td><td>184</td><td>40</td><td>9</td><td>1</td><td>2</td><td>21</td><td>4</td><td>1</td><td>28</td><td>4</td><td>0</td><td>2</td><td>5.49</td><td>6.18</td><td>5.94</td><td>6.22</td><td>4.57</td><td>1.55</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.29</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15509">김유성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.33</td><td>7</td><td>0</td><td>7</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6.1</td><td>7</td><td>7</td><td>8.20</td><td>38</td><td>6</td><td>0</td><td>0</td><td>2</td><td>12</td><td>0</td><td>0</td><td>6</td><td>1</td><td>0</td><td>3</td><td>9.95</td><td>9.95</td><td>11.65</td><td>12.48</td><td>11.11</td><td>2.84</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.33</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11159">이형범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-1.02</td><td>23</td><td>0</td><td>23</td><td>4</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>27.2</td><td>20</td><td>23</td><td>28.80</td><td>134</td><td>40</td><td>10</td><td>0</td><td>2</td><td>12</td><td>3</td><td>0</td><td>13</td><td>2</td><td>0</td><td>2</td><td>6.51</td><td>7.48</td><td>9.37</td><td>9.96</td><td>4.79</td><td>1.88</td><td style="background-color:#F3F3F3; font-weight:bold;">-1.02</td></tr>			</tbody>
		</table>
""")

In [44]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAR" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Games Relief, 구원" flow="down" so="GR" ob="DESC">GR</th><th rowspan="2" class="sorting" tooltip="Games Finished, 경기의 마지막 투수" flow="down" so="GF" ob="DESC">GF</th><th rowspan="2" class="sorting" tooltip="Completed Game, 완투" flow="down" so="CG" ob="DESC">CG</th><th rowspan="2" class="sorting" tooltip="Shutout, 완봉" flow="down" so="SHO" ob="DESC">SHO</th><th rowspan="2" class="sorting" tooltip="Wins , 승" flow="down" so="W" ob="DESC">W</th><th rowspan="2" class="sorting" tooltip="Loses, 패" flow="down" so="L" ob="DESC">L</th><th rowspan="2" class="sorting" tooltip="Saves, 세이브" flow="down" so="S" ob="DESC">S</th><th rowspan="2" class="sorting" tooltip="Hold, 홀드" flow="down" so="HD" ob="DESC">HD</th><th rowspan="2" class="sorting" tooltip="Innings Pitched, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Earned Runs, 자책점" flow="down" so="ER" ob="DESC">ER</th><th rowspan="2" class="sorting" tooltip="Runs, 실점" flow="down" so="R" ob="DESC">R</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed, 책임실점" flow="down" so="rRA" ob="DESC">rRA</th><th rowspan="2" class="sorting" tooltip="Total Batters Faces, 상대한 타자 수" flow="down" so="TBF" ob="DESC">TBF</th><th rowspan="2" class="sorting" tooltip="Hits, 안타" flow="down" so="H" ob="DESC">H</th><th rowspan="2" class="sorting" tooltip="Double, 2루타" flow="down" so="2B" ob="DESC">2B</th><th rowspan="2" class="sorting" tooltip="Triple, 3루타" flow="down" so="3B" ob="DESC">3B</th><th rowspan="2" class="sorting" tooltip="Home Run, 홈런" flow="down" so="HR" ob="DESC">HR</th><th rowspan="2" class="sorting" tooltip="Based on Balls, 4구" flow="down" so="BB" ob="DESC">BB</th><th rowspan="2" class="sorting" tooltip="Hit By Pitch, 사구" flow="down" so="HP" ob="DESC">HP</th><th rowspan="2" class="sorting" tooltip="Intentional Based on Ball, 고의4구" flow="down" so="IB" ob="DESC">IB</th><th rowspan="2" class="sorting" tooltip="Strike Out, 삼진" flow="down" so="SO" ob="DESC">SO</th><th rowspan="2" class="sorting" tooltip="Reached On Error, 실책 출루 허용 횟수" flow="down" so="ROE" ob="DESC">ROE</th><th rowspan="2" class="sorting" tooltip="Balk, 보크" flow="down" so="BK" ob="DESC">BK</th><th rowspan="2" class="sorting" tooltip="Wild Pitch, 폭투" flow="down" so="WP" ob="DESC">WP</th><th rowspan="2" class="sorting" tooltip="Earned Run Average, 평균자책점" flow="down" so="ERA" ob="ASC">ERA</th><th rowspan="2" class="sorting" tooltip="Runs Allowed 9th Innings, 9이닝 당 실점" flow="down" so="RA9" ob="ASC">RA9</th><th rowspan="2" class="sorting" tooltip="responsibility Runs Allowed 9th Innings, 9이닝 당 책임실점" flow="down" so="rRA9" ob="ASC">rRA9</th><th rowspan="2" class="sorting" tooltip="Adjusted responsibility Runs Allowed 9th Innings , 파크팩터를 적용한 9이닝 당 책임실점" flow="down" so="rRA9pf" ob="ASC">rRA9pf</th><th rowspan="2" class="sorting" tooltip="Fielding Independent Pitching, 수비 무관 평균자책점" flow="down" so="FIP" ob="ASC">FIP</th><th rowspan="2" class="sorting" tooltip="Walks and Hits Per Inning Pitched, 이닝 당 출루허용률" flow="down" so="WHIP" ob="ASC">WHIP</th><th rowspan="2" class="sorting align_center" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down" so="WAR" ob="ASC">WAR▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAR" ob="ASC"><div class="th_tit" tooltip="Wins Above Replacement, 대체 선수 대비 승리 기여도" flow="down">WAR</div></th>
									</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13091">안우진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">6.61</td><td>24</td><td>24</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9</td><td>7</td><td>0</td><td>0</td><td>150.2</td><td>40</td><td>44</td><td>41.25</td><td>608</td><td>121</td><td>25</td><td>1</td><td>5</td><td>38</td><td>1</td><td>1</td><td>164</td><td>5</td><td>0</td><td>8</td><td>2.39</td><td>2.63</td><td>2.46</td><td>2.50</td><td>2.33</td><td>1.06</td><td style="background-color:#F3F3F3; font-weight:bold;">6.61</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15531">후라도</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">6.61</td><td>30</td><td>30</td><td>0</td><td>0</td><td>0</td><td>0</td><td>11</td><td>8</td><td>0</td><td>0</td><td>183.2</td><td>54</td><td>64</td><td>62.95</td><td>763</td><td>164</td><td>19</td><td>0</td><td>7</td><td>41</td><td>9</td><td>0</td><td>147</td><td>15</td><td>0</td><td>5</td><td>2.65</td><td>3.14</td><td>3.08</td><td>3.13</td><td>3.15</td><td>1.12</td><td style="background-color:#F3F3F3; font-weight:bold;">6.61</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11379">최원태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">3.45</td><td>17</td><td>17</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td><td>4</td><td>0</td><td>0</td><td>102.1</td><td>37</td><td>38</td><td>38.00</td><td>422</td><td>90</td><td>11</td><td>0</td><td>7</td><td>29</td><td>5</td><td>0</td><td>78</td><td>4</td><td>0</td><td>5</td><td>3.25</td><td>3.34</td><td>3.34</td><td>3.31</td><td>3.79</td><td>1.16</td><td style="background-color:#F3F3F3; font-weight:bold;">3.45</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12858">김재웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.34</td><td>67</td><td>0</td><td>67</td><td>11</td><td>0</td><td>0</td><td>2</td><td>3</td><td>6</td><td>18</td><td>59.2</td><td>28</td><td>29</td><td>26.25</td><td>250</td><td>56</td><td>11</td><td>0</td><td>2</td><td>24</td><td>0</td><td>1</td><td>46</td><td>2</td><td>0</td><td>0</td><td>4.22</td><td>4.37</td><td>3.96</td><td>4.03</td><td>3.52</td><td>1.34</td><td style="background-color:#F3F3F3; font-weight:bold;">1.34</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10452">임창민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.28</td><td>51</td><td>0</td><td>51</td><td>33</td><td>0</td><td>0</td><td>2</td><td>2</td><td>26</td><td>1</td><td>46.2</td><td>13</td><td>16</td><td>19.50</td><td>209</td><td>51</td><td>6</td><td>0</td><td>3</td><td>17</td><td>2</td><td>3</td><td>40</td><td>3</td><td>0</td><td>0</td><td>2.51</td><td>3.09</td><td>3.76</td><td>3.84</td><td>3.60</td><td>1.46</td><td style="background-color:#F3F3F3; font-weight:bold;">1.28</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10533">정찬헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.95</td><td>14</td><td>14</td><td>0</td><td>1</td><td>1</td><td>0</td><td>2</td><td>8</td><td>0</td><td>0</td><td>72.0</td><td>38</td><td>40</td><td>39.50</td><td>295</td><td>71</td><td>12</td><td>3</td><td>4</td><td>13</td><td>2</td><td>1</td><td>35</td><td>3</td><td>0</td><td>0</td><td>4.75</td><td>5.00</td><td>4.94</td><td>5.15</td><td>3.90</td><td>1.17</td><td style="background-color:#F3F3F3; font-weight:bold;">0.95</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14849">김성진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.87</td><td>55</td><td>0</td><td>55</td><td>16</td><td>0</td><td>0</td><td>3</td><td>3</td><td>0</td><td>7</td><td>47.0</td><td>19</td><td>19</td><td>21.35</td><td>208</td><td>44</td><td>7</td><td>0</td><td>5</td><td>25</td><td>1</td><td>2</td><td>38</td><td>1</td><td>0</td><td>0</td><td>3.64</td><td>3.64</td><td>4.09</td><td>4.23</td><td>4.74</td><td>1.47</td><td style="background-color:#F3F3F3; font-weight:bold;">0.87</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13940">요키시</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.83</td><td>12</td><td>12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>3</td><td>0</td><td>0</td><td>65.2</td><td>32</td><td>37</td><td>37.00</td><td>286</td><td>82</td><td>14</td><td>1</td><td>3</td><td>14</td><td>3</td><td>1</td><td>51</td><td>6</td><td>0</td><td>1</td><td>4.39</td><td>5.07</td><td>5.07</td><td>5.22</td><td>3.25</td><td>1.46</td><td style="background-color:#F3F3F3; font-weight:bold;">0.83</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14784">장재영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.57</td><td>23</td><td>17</td><td>6</td><td>0</td><td>0</td><td>0</td><td>1</td><td>5</td><td>0</td><td>0</td><td>71.2</td><td>44</td><td>46</td><td>43.25</td><td>339</td><td>63</td><td>15</td><td>0</td><td>4</td><td>66</td><td>8</td><td>0</td><td>67</td><td>6</td><td>2</td><td>8</td><td>5.53</td><td>5.78</td><td>5.43</td><td>5.63</td><td>5.38</td><td>1.80</td><td style="background-color:#F3F3F3; font-weight:bold;">0.57</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14132">조영건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.39</td><td>6</td><td>0</td><td>6</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>7.2</td><td>0</td><td>0</td><td>0.50</td><td>27</td><td>5</td><td>1</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0.00</td><td>0.59</td><td>0.54</td><td>2.38</td><td>0.91</td><td style="background-color:#F3F3F3; font-weight:bold;">0.39</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15073">이명종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.15</td><td>45</td><td>2</td><td>43</td><td>7</td><td>0</td><td>0</td><td>5</td><td>5</td><td>0</td><td>1</td><td>57.0</td><td>33</td><td>34</td><td>35.55</td><td>260</td><td>66</td><td>13</td><td>0</td><td>5</td><td>24</td><td>6</td><td>0</td><td>26</td><td>1</td><td>0</td><td>0</td><td>5.21</td><td>5.37</td><td>5.61</td><td>5.67</td><td>5.38</td><td>1.58</td><td style="background-color:#F3F3F3; font-weight:bold;">0.15</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14131">윤정현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.14</td><td>5</td><td>0</td><td>5</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6.0</td><td>1</td><td>2</td><td>2.00</td><td>26</td><td>5</td><td>0</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>1</td><td>1.50</td><td>3.00</td><td>3.00</td><td>2.98</td><td>6.12</td><td>1.83</td><td style="background-color:#F3F3F3; font-weight:bold;">0.14</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12865">이승호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.10</td><td>4</td><td>1</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>5.0</td><td>3</td><td>3</td><td>3.00</td><td>24</td><td>5</td><td>3</td><td>0</td><td>1</td><td>4</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>5.40</td><td>5.40</td><td>5.40</td><td>5.14</td><td>8.21</td><td>1.80</td><td style="background-color:#F3F3F3; font-weight:bold;">0.10</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14848">김준형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.05</td><td>8</td><td>0</td><td>8</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7.2</td><td>6</td><td>6</td><td>5.15</td><td>36</td><td>4</td><td>3</td><td>0</td><td>0</td><td>6</td><td>3</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td>7.04</td><td>7.04</td><td>6.05</td><td>5.82</td><td>5.86</td><td>1.30</td><td style="background-color:#F3F3F3; font-weight:bold;">0.05</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10814">홍성민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.03</td><td>2</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.0</td><td>2</td><td>2</td><td>2.00</td><td>12</td><td>5</td><td>0</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>9.00</td><td>9.00</td><td>9.00</td><td>9.83</td><td>10.10</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.03</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12854">양지율</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.04</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.2</td><td>1</td><td>1</td><td>1.00</td><td>6</td><td>1</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>13.50</td><td>13.50</td><td>13.50</td><td>14.08</td><td>10.30</td><td>6.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.04</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12989">박승주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.06</td><td>18</td><td>0</td><td>18</td><td>6</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>18.0</td><td>7</td><td>11</td><td>12.20</td><td>91</td><td>19</td><td>3</td><td>2</td><td>2</td><td>13</td><td>2</td><td>0</td><td>15</td><td>3</td><td>0</td><td>5</td><td>3.50</td><td>5.50</td><td>6.10</td><td>6.31</td><td>5.67</td><td>1.78</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.06</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10437">문성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.06</td><td>32</td><td>0</td><td>32</td><td>7</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>2</td><td>28.1</td><td>14</td><td>16</td><td>18.25</td><td>134</td><td>26</td><td>3</td><td>0</td><td>2</td><td>20</td><td>2</td><td>2</td><td>21</td><td>2</td><td>0</td><td>2</td><td>4.45</td><td>5.08</td><td>5.80</td><td>5.93</td><td>5.02</td><td>1.62</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.06</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15474">오상원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.07</td><td>11</td><td>1</td><td>10</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>15.0</td><td>11</td><td>11</td><td>11.50</td><td>74</td><td>18</td><td>5</td><td>1</td><td>0</td><td>9</td><td>3</td><td>0</td><td>7</td><td>1</td><td>0</td><td>0</td><td>6.60</td><td>6.60</td><td>6.90</td><td>7.15</td><td>5.16</td><td>1.80</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.07</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10871">김태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.10</td><td>8</td><td>0</td><td>8</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>3</td><td>7.2</td><td>5</td><td>6</td><td>5.65</td><td>38</td><td>9</td><td>1</td><td>1</td><td>1</td><td>6</td><td>0</td><td>1</td><td>4</td><td>1</td><td>0</td><td>0</td><td>5.87</td><td>7.04</td><td>6.63</td><td>6.75</td><td>6.12</td><td>1.96</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.10</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15472">김건희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.14</td><td>3</td><td>0</td><td>3</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.0</td><td>5</td><td>5</td><td>3.95</td><td>14</td><td>6</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>22.50</td><td>22.50</td><td>17.78</td><td>18.97</td><td>18.85</td><td>4.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.14</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15646">맥키니</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.16</td><td>12</td><td>12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>9</td><td>0</td><td>0</td><td>59.1</td><td>43</td><td>46</td><td>44.80</td><td>268</td><td>61</td><td>14</td><td>1</td><td>10</td><td>36</td><td>1</td><td>0</td><td>39</td><td>2</td><td>1</td><td>3</td><td>6.52</td><td>6.98</td><td>6.80</td><td>7.00</td><td>6.14</td><td>1.63</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.16</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15067">주승우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.21</td><td>11</td><td>2</td><td>9</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>16.0</td><td>17</td><td>18</td><td>14.75</td><td>90</td><td>20</td><td>7</td><td>0</td><td>1</td><td>21</td><td>2</td><td>0</td><td>8</td><td>0</td><td>0</td><td>3</td><td>9.56</td><td>10.13</td><td>8.30</td><td>8.61</td><td>7.80</td><td>2.56</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.21</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11161">원종현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.24</td><td>20</td><td>0</td><td>20</td><td>1</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>6</td><td>18.2</td><td>12</td><td>16</td><td>13.75</td><td>87</td><td>24</td><td>8</td><td>1</td><td>3</td><td>5</td><td>1</td><td>1</td><td>17</td><td>2</td><td>0</td><td>2</td><td>5.79</td><td>7.71</td><td>6.63</td><td>6.71</td><td>4.32</td><td>1.55</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.24</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15071">윤석원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.25</td><td>21</td><td>0</td><td>21</td><td>3</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>2</td><td>24.0</td><td>12</td><td>17</td><td>19.25</td><td>110</td><td>29</td><td>5</td><td>0</td><td>2</td><td>8</td><td>0</td><td>1</td><td>8</td><td>3</td><td>0</td><td>1</td><td>4.50</td><td>6.38</td><td>7.22</td><td>7.50</td><td>4.91</td><td>1.54</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.25</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12997">이영준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.29</td><td>2</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1.2</td><td>4</td><td>4</td><td>3.50</td><td>10</td><td>4</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>21.60</td><td>21.60</td><td>18.90</td><td>19.71</td><td>5.71</td><td>3.00</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.29</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14576">이종민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.29</td><td>11</td><td>2</td><td>9</td><td>4</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>13.2</td><td>11</td><td>13</td><td>13.70</td><td>72</td><td>22</td><td>7</td><td>0</td><td>0</td><td>6</td><td>1</td><td>0</td><td>10</td><td>3</td><td>0</td><td>0</td><td>7.24</td><td>8.56</td><td>9.02</td><td>9.63</td><td>3.61</td><td>2.05</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.29</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15485">김동규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.47</td><td>3</td><td>1</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>4.0</td><td>10</td><td>10</td><td>10.00</td><td>25</td><td>6</td><td>0</td><td>0</td><td>1</td><td>9</td><td>1</td><td>0</td><td>1</td><td>0</td><td>0</td><td>4</td><td>22.50</td><td>22.50</td><td>22.50</td><td>24.02</td><td>13.95</td><td>3.75</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.47</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14674">김동혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.51</td><td>35</td><td>2</td><td>33</td><td>11</td><td>0</td><td>0</td><td>1</td><td>7</td><td>0</td><td>6</td><td>39.1</td><td>32</td><td>34</td><td>32.30</td><td>192</td><td>51</td><td>9</td><td>3</td><td>1</td><td>18</td><td>6</td><td>0</td><td>24</td><td>3</td><td>2</td><td>0</td><td>7.32</td><td>7.78</td><td>7.39</td><td>7.64</td><td>4.52</td><td>1.75</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.51</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10882">변시원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.60</td><td>4</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2.1</td><td>11</td><td>11</td><td>8.25</td><td>19</td><td>6</td><td>2</td><td>0</td><td>1</td><td>4</td><td>2</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>42.43</td><td>42.43</td><td>31.82</td><td>32.41</td><td>14.78</td><td>4.29</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.60</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11222">하영민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.70</td><td>57</td><td>0</td><td>57</td><td>7</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>5</td><td>52.1</td><td>27</td><td>36</td><td>38.40</td><td>247</td><td>67</td><td>8</td><td>4</td><td>4</td><td>25</td><td>1</td><td>3</td><td>51</td><td>6</td><td>0</td><td>6</td><td>4.64</td><td>6.19</td><td>6.60</td><td>6.81</td><td>3.86</td><td>1.76</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.70</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10730">양현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.74</td><td>54</td><td>0</td><td>54</td><td>12</td><td>0</td><td>0</td><td>0</td><td>5</td><td>0</td><td>8</td><td>57.0</td><td>32</td><td>38</td><td>43.65</td><td>262</td><td>83</td><td>9</td><td>2</td><td>5</td><td>21</td><td>0</td><td>1</td><td>16</td><td>6</td><td>1</td><td>0</td><td>5.05</td><td>6.00</td><td>6.89</td><td>7.07</td><td>5.28</td><td>1.82</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.74</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13092">김선기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.80</td><td>17</td><td>7</td><td>10</td><td>6</td><td>0</td><td>0</td><td>1</td><td>3</td><td>1</td><td>0</td><td>43.2</td><td>29</td><td>37</td><td>37.85</td><td>200</td><td>56</td><td>16</td><td>2</td><td>2</td><td>15</td><td>1</td><td>0</td><td>29</td><td>4</td><td>1</td><td>0</td><td>5.98</td><td>7.63</td><td>7.80</td><td>7.94</td><td>3.87</td><td>1.63</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.80</td></tr>			</tbody>
		</table>
""")

In [45]:
len(team_tables)

10

In [47]:
pitching = pd.DataFrame()
for i in range(len(team_tables)):
    name = team_names[i]
    team = team_tables[i]
    print(name)
    df, pids = get_team_stats_from_markup(StringIO(str(team)))
    df['팀'] = name
    df['pid'] = pids[2:]
    print(df.shape)
    print(len(pids))
    pitching = pd.concat([pitching, df])
    display(pitching.tail())
pitching.info()

한화 이글스
(31, 39)
33

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
26,27,김서현,23 P,-0.26,20,1,19,1,0,0,...,3,7.25,8.06,7.23,7.22,5.64,2.01,-0.26,한화 이글스,15421
27,28,김민우,23 P,-0.28,12,12,0,0,0,0,...,5,6.97,7.49,7.40,7.34,4.95,1.80,-0.28,한화 이글스,11410
28,29,한승혁,23 P,-0.30,21,7,14,4,0,0,...,4,6.44,6.69,7.16,7.12,4.95,1.90,-0.30,한화 이글스,10812
29,30,강재민,23 P,-0.63,43,0,43,2,0,0,...,0,6.44,6.44,6.49,6.57,4.73,1.25,-0.63,한화 이글스,14708
30,31,박상언,23 C,NaN,0,0,0,0,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,한화 이글스,12587

LG 트윈스
(33, 39)
35

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
28,29,최원태,23 P,-0.12,9,9,0,0,0,0,...,1,6.70,7.11,7.03,7.04,4.12,1.71,-0.12,LG 트윈스,11379
29,30,손주영,23 P,-0.16,3,2,1,0,0,0,...,0,5.19,7.27,8.15,8.79,4.55,2.08,-0.16,LG 트윈스,12908
30,31,김대현,23 P,-0.16,5,0,5,2,0,0,...,1,10.80,13.50,12.56,12.83,7.96,3.00,-0.16,LG 트윈스,12532
31,32,최성훈,23 P,-0.54,5,0,5,1,0,0,...,0,15.00,15.00,20.70,22.06,3.22,2.67,-0.54,LG 트윈스,10851
32,33,정우영,23 P,-0.66,60,0,60,3,0,0,...,2,4.70,6.79,6.52,6.84,3.96,1.55,-0.66,LG 트윈스,14136

롯데 자이언츠
(33, 39)
35

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
28,29,이인복,23 P,-0.40,10,7,3,0,0,0,...,4,6.48,8.64,8.28,8.09,5.10,1.92,-0.40,롯데 자이언츠,11232
29,30,이태연,23 P,-0.41,15,0,15,2,0,0,...,0,15.88,15.88,16.44,15.90,9.11,3.71,-0.41,롯데 자이언츠,15444
30,31,최영환,23 P,-0.59,8,0,8,4,0,0,...,0,9.90,12.60,12.29,11.58,4.58,2.20,-0.59,롯데 자이언츠,11276
31,32,문경찬,23 P,-0.68,2,0,2,1,0,0,...,0,27.00,27.00,27.00,27.29,19.20,3.00,-0.68,롯데 자이언츠,11299
32,33,윤명준,23 P,-1.10,21,0,21,8,0,0,...,5,6.52,6.52,10.22,9.94,7.13,2.12,-1.10,롯데 자이언츠,10885

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

KIA 타이거즈
(24, 39)
26

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
19,20,황동하,23 P,-0.06,13,6,7,1,0,0,...,1,6.61,7.18,6.59,6.82,6.41,1.79,-0.06,KIA 타이거즈,15063
20,21,곽도규,23 P,-0.18,14,0,14,2,0,0,...,1,8.49,8.49,8.49,8.64,4.04,2.06,-0.18,KIA 타이거즈,15435
21,22,김유신,23 P,-0.21,27,0,27,9,0,0,...,0,5.64,5.64,6.71,6.70,5.89,1.75,-0.21,KIA 타이거즈,13114
22,23,김기훈,23 P,-0.26,29,0,29,12,0,0,...,5,4.60,6.32,6.76,6.99,5.53,2.07,-0.26,KIA 타이거즈,14176
23,24,김재열,23 P,-0.76,9,0,9,2,0,0,...,0,13.11,13.11,14.04,13.82,7.42,2.83,-0.76,KIA 타이거즈,14747

KT 위즈

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(26, 39)
28

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
21,22,심재민,23 P,-0.14,4,0,4,1,0,0,...,0,22.50,22.50,15.30,14.03,5.70,5.00,-0.14,KT 위즈,11311
22,23,김민,23 P,-0.17,16,4,12,5,0,0,...,4,6.83,8.07,7.54,7.27,5.32,1.93,-0.17,KT 위즈,13167
23,24,김태오,23 P,-0.22,5,0,5,2,0,0,...,0,7.36,7.36,9.88,10.19,4.09,1.91,-0.22,KT 위즈,12577
24,25,소형준,23 P,-0.23,3,3,0,0,0,0,...,2,11.45,11.45,10.60,9.75,5.71,2.27,-0.23,KT 위즈,14600
25,26,조이현,23 P,-0.43,18,4,14,4,0,0,...,1,6.69,6.94,8.22,7.95,4.36,1.91,-0.43,KT 위즈,11284

삼성 라이온즈
(31, 39)
33

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
26,27,장필준,23 P,-0.38,17,3,14,5,0,0,...,0,7.91,7.91,8.47,8.25,5.90,2.07,-0.38,삼성 라이온즈,11404
27,28,홍정우,23 P,-0.40,36,1,35,5,0,0,...,2,7.50,7.75,6.93,6.69,5.95,1.58,-0.40,삼성 라이온즈,13242
28,29,양창섭,23 P,-0.43,15,4,11,1,0,0,...,2,9.10,9.10,8.73,8.54,7.55,2.13,-0.43,삼성 라이온즈,13157
29,30,김태훈,23 P,-0.60,63,0,63,16,0,0,...,1,7.28,7.76,6.82,6.58,5.90,1.83,-0.60,삼성 라이온즈,10871
30,31,최하늘,23 P,-0.85,3,2,1,1,0,0,...,0,19.89,19.89,20.39,20.69,9.85,3.00,-0.85,삼성 라이온즈,13152

SSG 랜더스

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(25, 39)
27

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
20,21,송영진,23 P,-0.08,17,9,8,1,0,0,...,8,5.70,6.65,6.59,6.50,4.76,1.63,-0.08,SSG 랜더스,15462
21,22,이로운,23 P,-0.08,50,0,50,14,0,0,...,3,5.62,6.09,6.41,6.16,4.65,1.66,-0.08,SSG 랜더스,15461
22,23,김주온,23 P,-0.11,1,0,1,0,0,0,...,1,81.00,81.00,58.05,63.40,14.95,9.00,-0.11,SSG 랜더스,13057
23,24,임준섭,23 P,-0.21,41,0,41,11,0,0,...,2,5.79,6.89,6.65,6.58,4.12,1.93,-0.21,SSG 랜더스,10795
24,25,정성곤,23 P,-0.36,6,0,6,3,0,0,...,0,10.38,18.69,20.46,19.23,12.62,3.46,-0.36,SSG 랜더스,11321

NC 다이노스

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(28, 39)
30

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
23,24,한재승,23 P,0.00,11,0,11,5,0,0,...,1,4.66,4.66,6.10,6.14,5.33,1.45,0.00,NC 다이노스,14764
24,25,임지민,23 P,-0.04,2,0,2,0,0,0,...,2,13.50,13.50,13.50,12.54,7.52,4.50,-0.04,NC 다이노스,15115
25,26,채지선,23 P,-0.05,2,0,2,0,0,0,...,1,10.13,10.13,10.13,10.07,6.62,3.00,-0.05,NC 다이노스,11387
26,27,정구범,23 P,-0.09,4,2,2,0,0,0,...,0,7.82,7.82,7.82,7.77,8.42,2.21,-0.09,NC 다이노스,14595
27,28,배민서,23 P,-0.27,6,0,6,4,0,0,...,2,6.75,10.80,12.89,12.52,3.74,1.80,-0.27,NC 다이노스,14158

두산 베어스

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(28, 39)
30

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
23,24,이원재,23 P,-0.13,1,1,0,0,0,0,...,0,27.00,27.00,23.85,24.88,13.15,6.00,-0.13,두산 베어스,15101
24,25,김정우,23 P,-0.21,7,0,7,5,0,0,...,0,9.45,9.45,10.87,11.74,6.64,2.70,-0.21,두산 베어스,13124
25,26,이영하,23 P,-0.29,36,0,36,5,0,0,...,2,5.49,6.18,5.94,6.22,4.57,1.55,-0.29,두산 베어스,12568
26,27,김유성,23 P,-0.33,7,0,7,5,0,0,...,3,9.95,9.95,11.65,12.48,11.11,2.84,-0.33,두산 베어스,15509
27,28,이형범,23 P,-1.02,23,0,23,4,0,0,...,2,6.51,7.48,9.37,9.96,4.79,1.88,-1.02,두산 베어스,11159

키움 히어로즈

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(33, 39)
35

,Rank,Name,Team,Sort▼,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,팀,pid
,Rank,Name,Team,WAR,G,GS,GR,GF,CG,SHO,...,WP,ERA,RA9,rRA9,rRA9pf,FIP,WHIP,WAR▼,,
28,29,김동혁,23 P,-0.51,35,2,33,11,0,0,...,0,7.32,7.78,7.39,7.64,4.52,1.75,-0.51,키움 히어로즈,14674
29,30,변시원,23 P,-0.60,4,0,4,0,0,0,...,0,42.43,42.43,31.82,32.41,14.78,4.29,-0.60,키움 히어로즈,10882
30,31,하영민,23 P,-0.70,57,0,57,7,0,0,...,6,4.64,6.19,6.60,6.81,3.86,1.76,-0.70,키움 히어로즈,11222
31,32,양현,23 P,-0.74,54,0,54,12,0,0,...,0,5.05,6.00,6.89,7.07,5.28,1.82,-0.74,키움 히어로즈,10730
32,33,김선기,23 P,-0.80,17,7,10,6,0,0,...,0,5.98,7.63,7.80,7.94,3.87,1.63,-0.80,키움 히어로즈,13092

<class 'pandas.core.frame.DataFrame'>
Index: 292 entries, 0 to 32
Data columns (total 39 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   (Rank, Rank)      292 non-null    int64
 1   (Name, Name)      292 non-null    object
 2   (Team, Team)      292 non-null    object
 3   (Sort▼, WAR)      291 non-null    float64
 4   (G, G)            292 non-null    int64
 5   (GS, GS)          292 non-null    int64
 6   (GR, GR)          292 non-null    int64
 7   (GF, GF)          292 non-null    int64
 8   (CG, CG)          292 non-null    int64
 9   (SHO, SHO)        292 non-null    int64
 10  (W, W)            292 non-null    int64
 11  (L, L)            292 non-null    int64
 12  (S, S)            292 non-null    int64
 13  (HD, HD)          292 non-null    int64
 14  (IP, IP)          292 non-null    float64
 15  (ER, ER)          292 non-null    int64
 16  (R, R)            292 non-null    int64
 17  (rRA, rRA)        292 non-null    float64
 18  (TBF, TBF)        292 non-null    int64
 19  (H, H)            292 non-null    int64
 20  (2B, 2B)          292 non-null    int64
 21  (3B, 3B)          292 non-null    int64
 22  (HR, HR)          292 non-null    int64
 23  (BB, BB)          292 non-null    int64
 24  (HP, HP)          292 non-null    int64
 25  (IB, IB)          292 non-null    int64
 26  (SO, SO)          292 non-null    int64
 27  (ROE, ROE)        292 non-null    int64
 28  (BK, BK)          292 non-null    int64
 29  (WP, WP)          292 non-null    int64
 30  (ERA, ERA)        291 non-null    float64
 31  (RA9, RA9)        291 non-null    float64
 32  (rRA9, rRA9)      291 non-null    float64
 33  (rRA9pf, rRA9pf)  291 non-null    float64
 34  (FIP, FIP)        291 non-null    float64
 35  (WHIP, WHIP)      291 non-null    float64
 36  (WAR▼, WAR▼)      291 non-null    float64
 37  (팀, )             292 non-null    object
 38  (pid, )           292 non-null    object
dtypes: float64(10), int64(25), object(4)
memory usage: 91.2+ KB

In [48]:
pitching.to_csv("2023_투구_statiz.csv", index=False)

In [60]:
team_tables=[]

In [61]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11414">이도윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.297</td><td>97</td><td>90</td><td>746.0</td><td>368</td><td>157</td><td>203</td><td>8</td><td>97.8</td><td>4.34</td><td style="">4.29</td><td></td><td>0.76</td><td>1.31</td><td></td><td></td><td></td><td></td><td>6.37</td><td>8.66</td><td>6.34</td><td>12.71</td><td>0.650</td><td style="background-color:#F3F3F3; font-weight:bold;">1.297</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10170">최재훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.180</td><td>120</td><td>106</td><td>884.1</td><td>774</td><td>704</td><td>67</td><td>3</td><td>99.6</td><td>7.85</td><td style="">0.65</td><td></td><td>0.80</td><td></td><td>-0.02</td><td>0.36</td><td>0.23</td><td></td><td>1.95</td><td>2.24</td><td>9.62</td><td>11.57</td><td>0.199</td><td style="background-color:#F3F3F3; font-weight:bold;">1.180</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14125">노시환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.369</td><td>122</td><td>121</td><td>1065.2</td><td>361</td><td>114</td><td>228</td><td>19</td><td>94.7</td><td>2.89</td><td style="">4.55</td><td></td><td>-0.50</td><td>-0.11</td><td>-0.32</td><td></td><td></td><td></td><td>3.61</td><td>3.97</td><td>0.00</td><td>3.61</td><td>0.369</td><td style="background-color:#F3F3F3; font-weight:bold;">0.369</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12587">박상언</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.347</td><td>79</td><td>38</td><td>388.2</td><td>368</td><td>333</td><td>34</td><td>1</td><td>99.7</td><td>8.50</td><td style="">-0.39</td><td></td><td>0.51</td><td></td><td>-0.02</td><td>-0.17</td><td>-0.12</td><td></td><td>-0.15</td><td>-0.24</td><td>3.55</td><td>3.41</td><td>-0.015</td><td style="background-color:#F3F3F3; font-weight:bold;">0.347</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15422">문현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.325</td><td>54</td><td>42</td><td>358.0</td><td>184</td><td>77</td><td>102</td><td>5</td><td>97.3</td><td>4.50</td><td style="">2.34</td><td></td><td>-0.52</td><td>-0.46</td><td></td><td></td><td></td><td></td><td>1.36</td><td>1.42</td><td>1.83</td><td>3.19</td><td>0.138</td><td style="background-color:#F3F3F3; font-weight:bold;">0.325</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13137">정은원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.320</td><td>101</td><td>92</td><td>797.2</td><td>441</td><td>188</td><td>245</td><td>8</td><td>98.2</td><td>4.89</td><td style="">-2.03</td><td></td><td>0.67</td><td>0.43</td><td></td><td></td><td></td><td></td><td>-0.93</td><td>-1.09</td><td>4.06</td><td>3.13</td><td>-0.095</td><td style="background-color:#F3F3F3; font-weight:bold;">0.320</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12539">이진영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.230</td><td>80</td><td>53</td><td>509.1</td><td>140</td><td>127</td><td>9</td><td>4</td><td>97.1</td><td>2.40</td><td style="">5.24</td><td>0.51</td><td>-1.00</td><td></td><td></td><td></td><td></td><td></td><td>4.75</td><td>5.65</td><td>-2.49</td><td>2.26</td><td>0.484</td><td style="background-color:#F3F3F3; font-weight:bold;">0.230</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13138">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.180</td><td>64</td><td>25</td><td>294.1</td><td>98</td><td>93</td><td>3</td><td>2</td><td>98.0</td><td>2.94</td><td style="">1.90</td><td>-0.02</td><td>-0.12</td><td></td><td></td><td></td><td></td><td></td><td>1.76</td><td>3.13</td><td>0.00</td><td>1.76</td><td>0.180</td><td style="background-color:#F3F3F3; font-weight:bold;">0.180</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10557">오선진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.177</td><td>8</td><td>3</td><td>30.0</td><td>21</td><td>14</td><td>7</td><td>0</td><td>100.0</td><td>6.30</td><td style="">1.73</td><td></td><td>0.08</td><td>-0.17</td><td></td><td></td><td></td><td></td><td>1.64</td><td>2.62</td><td>0.10</td><td>1.74</td><td>0.167</td><td style="background-color:#F3F3F3; font-weight:bold;">0.177</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12585">김태연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.151</td><td>30</td><td>26</td><td>188.2</td><td>48</td><td>45</td><td>2</td><td>1</td><td>97.9</td><td>2.24</td><td style="">2.78</td><td>-0.20</td><td>-0.13</td><td></td><td></td><td></td><td></td><td></td><td>2.45</td><td>3.88</td><td>-0.97</td><td>1.48</td><td>0.250</td><td style="background-color:#F3F3F3; font-weight:bold;">0.151</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14707">최인호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.137</td><td>37</td><td>35</td><td>271.1</td><td>77</td><td>76</td><td>0</td><td>1</td><td>98.7</td><td>2.52</td><td style="">3.09</td><td>-0.30</td><td>-0.01</td><td></td><td></td><td></td><td></td><td></td><td>2.78</td><td>9.77</td><td>-1.44</td><td>1.34</td><td>0.284</td><td style="background-color:#F3F3F3; font-weight:bold;">0.137</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11268">노수광</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.135</td><td>7</td><td>4</td><td>41.1</td><td>10</td><td>10</td><td>0</td><td>0</td><td>100.0</td><td>2.18</td><td style="">1.48</td><td>-0.21</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>1.32</td><td>6.34</td><td>0.00</td><td>1.32</td><td>0.135</td><td style="background-color:#F3F3F3; font-weight:bold;">0.135</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11414">이도윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.133</td><td>15</td><td>2</td><td>57.0</td><td>36</td><td>14</td><td>22</td><td>0</td><td>100.0</td><td>5.68</td><td style="">0.74</td><td></td><td>0.15</td><td>0.20</td><td></td><td></td><td></td><td></td><td>1.09</td><td>1.48</td><td>0.21</td><td>1.30</td><td>0.111</td><td style="background-color:#F3F3F3; font-weight:bold;">0.133</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12585">김태연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.110</td><td>6</td><td>5</td><td>41.0</td><td>30</td><td>8</td><td>21</td><td>1</td><td>96.7</td><td>6.37</td><td style="">0.77</td><td></td><td>0.11</td><td></td><td></td><td></td><td></td><td></td><td>0.88</td><td>1.39</td><td>0.20</td><td>1.08</td><td>0.090</td><td style="background-color:#F3F3F3; font-weight:bold;">0.110</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15422">문현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.098</td><td>9</td><td>5</td><td>48.0</td><td>25</td><td>10</td><td>13</td><td>2</td><td>92.0</td><td>4.31</td><td style="">0.79</td><td></td><td>-0.38</td><td>0.16</td><td></td><td></td><td></td><td></td><td>0.56</td><td>0.59</td><td>0.40</td><td>0.96</td><td>0.057</td><td style="background-color:#F3F3F3; font-weight:bold;">0.098</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15647">윌리엄스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.097</td><td>21</td><td>21</td><td>159.0</td><td>36</td><td>33</td><td>1</td><td>2</td><td>94.4</td><td>1.92</td><td style="">3.08</td><td>-0.57</td><td>-0.68</td><td></td><td></td><td></td><td></td><td></td><td>1.82</td><td>3.86</td><td>-0.87</td><td>0.95</td><td>0.186</td><td style="background-color:#F3F3F3; font-weight:bold;">0.097</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15541">오그레디</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.083</td><td>15</td><td>15</td><td>126.2</td><td>37</td><td>36</td><td>1</td><td>0</td><td>100.0</td><td>2.63</td><td style="">0.89</td><td>0.29</td><td>0.22</td><td></td><td></td><td></td><td></td><td></td><td>1.41</td><td>9.21</td><td>-0.59</td><td>0.82</td><td>0.143</td><td style="background-color:#F3F3F3; font-weight:bold;">0.083</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12585">김태연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.078</td><td>9</td><td>4</td><td>38.0</td><td>7</td><td>3</td><td>4</td><td>0</td><td>100.0</td><td>1.66</td><td style="">0.40</td><td></td><td>0.09</td><td>0.28</td><td></td><td></td><td></td><td></td><td>0.77</td><td>1.22</td><td>0.00</td><td>0.77</td><td>0.078</td><td style="background-color:#F3F3F3; font-weight:bold;">0.078</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13676">권광민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.077</td><td>8</td><td>1</td><td>20.0</td><td>23</td><td>20</td><td>2</td><td>1</td><td>95.7</td><td>9.90</td><td style="">1.35</td><td></td><td>-0.46</td><td></td><td></td><td></td><td></td><td></td><td>0.89</td><td>1.95</td><td>-0.14</td><td>0.75</td><td>0.091</td><td style="background-color:#F3F3F3; font-weight:bold;">0.077</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10119">이명기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.062</td><td>2</td><td>1</td><td>14.0</td><td>6</td><td>5</td><td>0</td><td>1</td><td>83.3</td><td>3.21</td><td style="">1.10</td><td>0.04</td><td>-0.47</td><td></td><td></td><td></td><td></td><td></td><td>0.67</td><td>6.94</td><td>-0.07</td><td>0.60</td><td>0.069</td><td style="background-color:#F3F3F3; font-weight:bold;">0.062</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12539">이진영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.055</td><td>21</td><td>15</td><td>140.1</td><td>35</td><td>34</td><td>0</td><td>1</td><td>97.1</td><td>2.18</td><td style="">2.34</td><td>-0.90</td><td>-0.25</td><td></td><td></td><td></td><td></td><td></td><td>1.20</td><td>1.42</td><td>-0.66</td><td>0.54</td><td>0.122</td><td style="background-color:#F3F3F3; font-weight:bold;">0.055</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15423">이민준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.054</td><td>4</td><td>0</td><td>8.0</td><td>2</td><td>1</td><td>1</td><td>0</td><td>100.0</td><td>2.25</td><td style="">0.47</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.49</td><td>17.69</td><td>0.04</td><td>0.53</td><td>0.050</td><td style="background-color:#F3F3F3; font-weight:bold;">0.054</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14126">유로결</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.052</td><td>8</td><td>3</td><td>33.0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>1.91</td><td style="">0.64</td><td>-0.07</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>0.63</td><td>3.36</td><td>-0.12</td><td>0.51</td><td>0.064</td><td style="background-color:#F3F3F3; font-weight:bold;">0.052</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14704">박정현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.044</td><td>2</td><td>0</td><td>7.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.29</td><td style="">0.39</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.41</td><td>1.11</td><td>0.02</td><td>0.43</td><td>0.042</td><td style="background-color:#F3F3F3; font-weight:bold;">0.044</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11215">채은성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.039</td><td>23</td><td>22</td><td>171.1</td><td>37</td><td>34</td><td>2</td><td>1</td><td>97.3</td><td>1.89</td><td style="">1.05</td><td>0.41</td><td>-0.16</td><td></td><td></td><td></td><td></td><td></td><td>1.29</td><td>1.36</td><td>-0.91</td><td>0.38</td><td>0.132</td><td style="background-color:#F3F3F3; font-weight:bold;">0.039</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14704">박정현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.039</td><td>32</td><td>20</td><td>186.0</td><td>91</td><td>37</td><td>47</td><td>7</td><td>92.3</td><td>4.06</td><td style="">-0.41</td><td></td><td>-0.55</td><td>-0.13</td><td></td><td></td><td></td><td></td><td>-1.10</td><td>-2.98</td><td>1.48</td><td>0.38</td><td>-0.112</td><td style="background-color:#F3F3F3; font-weight:bold;">0.039</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12902">이재용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.039</td><td>2</td><td>0</td><td>4.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>4.50</td><td style="">0.00</td><td></td><td>0.01</td><td></td><td></td><td></td><td>0.46</td><td></td><td>0.33</td><td>23.90</td><td>0.05</td><td>0.38</td><td>0.034</td><td style="background-color:#F3F3F3; font-weight:bold;">0.039</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12589">김인환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.034</td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.23</td><td>0.11</td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.34</td><td>0.44</td><td>-0.01</td><td>0.33</td><td>0.035</td><td style="background-color:#F3F3F3; font-weight:bold;">0.034</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15422">문현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.030</td><td>1</td><td>0</td><td>1.0</td><td>2</td><td>1</td><td>1</td><td>0</td><td>100.0</td><td>18.00</td><td style="">0.47</td><td></td><td>0.00</td><td>-0.18</td><td></td><td></td><td></td><td></td><td>0.29</td><td>0.31</td><td>0.00</td><td>0.29</td><td>0.030</td><td style="background-color:#F3F3F3; font-weight:bold;">0.030</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14126">유로결</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.030</td><td>14</td><td>8</td><td>80.0</td><td>13</td><td>12</td><td>1</td><td>0</td><td>100.0</td><td>1.46</td><td style="">0.51</td><td>-0.07</td><td>0.15</td><td></td><td></td><td></td><td></td><td></td><td>0.59</td><td>3.16</td><td>-0.30</td><td>0.29</td><td>0.060</td><td style="background-color:#F3F3F3; font-weight:bold;">0.030</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15141">유상빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.022</td><td>1</td><td>1</td><td>8.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.13</td><td style="">0.23</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.24</td><td>11.74</td><td>-0.03</td><td>0.21</td><td>0.025</td><td style="background-color:#F3F3F3; font-weight:bold;">0.022</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12583">장진혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.011</td><td>27</td><td>17</td><td>153.2</td><td>34</td><td>32</td><td>1</td><td>1</td><td>97.1</td><td>1.93</td><td style="">0.47</td><td>0.47</td><td>-0.22</td><td></td><td></td><td></td><td></td><td></td><td>0.72</td><td>1.53</td><td>-0.61</td><td>0.11</td><td>0.074</td><td style="background-color:#F3F3F3; font-weight:bold;">0.011</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10557">오선진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.010</td><td>6</td><td>2</td><td>25.0</td><td>21</td><td>20</td><td>1</td><td>0</td><td>100.0</td><td>7.56</td><td style="">0.25</td><td></td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>0.30</td><td>0.48</td><td>-0.20</td><td>0.10</td><td>0.030</td><td style="background-color:#F3F3F3; font-weight:bold;">0.010</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10557">오선진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.001</td><td>30</td><td>13</td><td>127.0</td><td>38</td><td>12</td><td>24</td><td>2</td><td>94.7</td><td>2.55</td><td style="">-0.49</td><td></td><td>0.29</td><td>0.19</td><td></td><td></td><td></td><td></td><td>-0.01</td><td>-0.01</td><td>0.00</td><td>-0.01</td><td>-0.001</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.001</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12583">장진혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.006</td><td>17</td><td>6</td><td>79.0</td><td>17</td><td>17</td><td>0</td><td>0</td><td>100.0</td><td>1.94</td><td style="">0.65</td><td>-0.53</td><td>0.15</td><td></td><td></td><td></td><td></td><td></td><td>0.27</td><td>0.57</td><td>-0.33</td><td>-0.06</td><td>0.027</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.006</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13676">권광민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.017</td><td>3</td><td>0</td><td>4.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>2.25</td><td style="">-0.29</td><td>0.13</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.15</td><td>-0.33</td><td>-0.01</td><td>-0.16</td><td>-0.016</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.017</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14125">노시환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.018</td><td>3</td><td>0</td><td>4.0</td><td>3</td><td>2</td><td>1</td><td>0</td><td>100.0</td><td>6.75</td><td style="">-0.63</td><td></td><td>0.01</td><td></td><td>0.46</td><td></td><td></td><td></td><td>-0.16</td><td>-0.18</td><td>-0.02</td><td>-0.18</td><td>-0.016</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.018</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11122">장운호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.024</td><td>1</td><td>1</td><td>6.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.50</td><td style="">-0.22</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.21</td><td>-7.42</td><td>-0.03</td><td>-0.24</td><td>-0.021</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.024</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13138">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.025</td><td>12</td><td>2</td><td>42.1</td><td>8</td><td>8</td><td>0</td><td>0</td><td>100.0</td><td>1.70</td><td style="">-0.31</td><td>0.13</td><td>0.08</td><td></td><td></td><td></td><td></td><td></td><td>-0.10</td><td>-0.17</td><td>-0.15</td><td>-0.25</td><td>-0.010</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.025</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12585">김태연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.031</td><td>32</td><td>23</td><td>191.0</td><td>202</td><td>189</td><td>12</td><td>1</td><td>99.5</td><td>9.47</td><td style="">1.15</td><td></td><td>0.35</td><td></td><td>-0.08</td><td></td><td></td><td></td><td>1.41</td><td>2.24</td><td>-1.72</td><td>-0.31</td><td>0.144</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.031</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11414">이도윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.032</td><td>3</td><td>0</td><td>6.0</td><td>2</td><td>1</td><td>1</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-0.14</td><td></td><td>0.01</td><td>-0.18</td><td></td><td></td><td></td><td></td><td>-0.31</td><td>-0.42</td><td>0.00</td><td>-0.31</td><td>-0.032</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.032</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11206">이성곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.045</td><td>1</td><td>0</td><td>3.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">-0.43</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.42</td><td>-7.60</td><td>-0.02</td><td>-0.44</td><td>-0.043</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.045</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10119">이명기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.052</td><td>2</td><td>1</td><td>9.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-0.38</td><td>-0.10</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.46</td><td>-4.76</td><td>-0.05</td><td>-0.51</td><td>-0.047</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.052</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13676">권광민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.053</td><td>27</td><td>6</td><td>97.2</td><td>20</td><td>20</td><td>0</td><td>0</td><td>100.0</td><td>1.84</td><td style="">-1.34</td><td>0.97</td><td>0.17</td><td></td><td></td><td></td><td></td><td></td><td>-0.19</td><td>-0.42</td><td>-0.33</td><td>-0.52</td><td>-0.020</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.053</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14704">박정현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.056</td><td>12</td><td>6</td><td>53.0</td><td>16</td><td>9</td><td>5</td><td>2</td><td>87.5</td><td>2.38</td><td style="">-0.67</td><td></td><td>0.12</td><td></td><td></td><td></td><td></td><td></td><td>-0.55</td><td>-1.50</td><td>0.00</td><td>-0.55</td><td>-0.056</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.056</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14704">박정현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.066</td><td>8</td><td>1</td><td>16.0</td><td>13</td><td>13</td><td>0</td><td>0</td><td>100.0</td><td>7.31</td><td style="">-0.58</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.55</td><td>-1.49</td><td>-0.10</td><td>-0.65</td><td>-0.056</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.066</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15139">이상혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.098</td><td>2</td><td>0</td><td>6.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-0.66</td><td>-0.31</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.96</td><td>-19.72</td><td>0.00</td><td>-0.96</td><td>-0.098</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.098</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14126">유로결</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.105</td><td>5</td><td>3</td><td>21.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>2.14</td><td style="">-1.04</td><td>-0.01</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-1.03</td><td>-5.47</td><td>0.00</td><td>-1.03</td><td>-0.105</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.105</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11122">장운호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.117</td><td>3</td><td>2</td><td>22.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>2.05</td><td style="">-0.92</td><td>-0.19</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-1.07</td><td>-38.54</td><td>-0.08</td><td>-1.15</td><td>-0.109</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.117</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14204">허관회</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.136</td><td>8</td><td>0</td><td>14.2</td><td>15</td><td>14</td><td>0</td><td>1</td><td>93.3</td><td>8.59</td><td style="">-0.88</td><td></td><td>0.04</td><td></td><td></td><td>-0.19</td><td>-0.57</td><td></td><td>-1.43</td><td>-20.63</td><td>0.10</td><td>-1.34</td><td>-0.146</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.136</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10913">하주석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.154</td><td>23</td><td>4</td><td>84.0</td><td>36</td><td>11</td><td>23</td><td>2</td><td>94.4</td><td>3.64</td><td style="">-2.73</td><td></td><td>0.20</td><td>0.38</td><td></td><td></td><td></td><td></td><td>-2.15</td><td>-12.36</td><td>0.64</td><td>-1.51</td><td>-0.219</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.154</td></tr><tr><td style="text-align:center;">52</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14209">김건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.183</td><td>1</td><td>1</td><td>9.0</td><td>4</td><td>2</td><td>1</td><td>1</td><td>75.0</td><td>3.00</td><td style="">-1.26</td><td></td><td>-0.48</td><td></td><td></td><td></td><td></td><td></td><td>-1.73</td><td>-35.66</td><td>-0.06</td><td>-1.79</td><td>-0.177</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.183</td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15541">오그레디</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.199</td><td>4</td><td>2</td><td>19.0</td><td>4</td><td>3</td><td>0</td><td>1</td><td>75.0</td><td>1.42</td><td style="">-0.93</td><td>-0.49</td><td>-0.46</td><td></td><td></td><td></td><td></td><td></td><td>-1.89</td><td>-12.34</td><td>-0.07</td><td>-1.96</td><td>-0.192</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.199</td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11268">노수광</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.205</td><td>23</td><td>15</td><td>142.0</td><td>27</td><td>27</td><td>0</td><td>0</td><td>100.0</td><td>1.71</td><td style="">-1.48</td><td>-0.09</td><td>0.25</td><td></td><td></td><td></td><td></td><td></td><td>-1.32</td><td>-6.33</td><td>-0.69</td><td>-2.01</td><td>-0.134</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.205</td></tr><tr><td style="text-align:center;">55</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12539">이진영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.229</td><td>31</td><td>27</td><td>195.1</td><td>56</td><td>54</td><td>2</td><td>0</td><td>100.0</td><td>2.58</td><td style="">-2.41</td><td>-0.09</td><td>0.25</td><td></td><td></td><td></td><td></td><td></td><td>-2.25</td><td>-2.67</td><td>0.00</td><td>-2.25</td><td>-0.229</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.229</td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12583">장진혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.260</td><td>29</td><td>17</td><td>155.2</td><td>36</td><td>36</td><td>0</td><td>0</td><td>100.0</td><td>2.08</td><td style="">-2.33</td><td>-0.41</td><td>0.20</td><td></td><td></td><td></td><td></td><td></td><td>-2.55</td><td>-5.39</td><td>0.00</td><td>-2.55</td><td>-0.260</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.260</td></tr><tr><td style="text-align:center;">57</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12589">김인환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.263</td><td>58</td><td>48</td><td>420.1</td><td>392</td><td>357</td><td>30</td><td>5</td><td>98.7</td><td>8.29</td><td style="">1.09</td><td></td><td>0.27</td><td></td><td>0.06</td><td></td><td></td><td></td><td>1.42</td><td>1.83</td><td>-4.00</td><td>-2.58</td><td>0.145</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.263</td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10557">오선진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.301</td><td>40</td><td>25</td><td>219.2</td><td>86</td><td>32</td><td>52</td><td>2</td><td>97.7</td><td>3.44</td><td style="">-3.09</td><td></td><td>0.02</td><td>-1.72</td><td></td><td></td><td></td><td></td><td>-4.79</td><td>-7.66</td><td>1.84</td><td>-2.95</td><td>-0.488</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.301</td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15422">문현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.336</td><td>70</td><td>64</td><td>519.0</td><td>133</td><td>129</td><td>2</td><td>2</td><td>98.5</td><td>2.27</td><td style="">-3.59</td><td>0.63</td><td>-0.33</td><td></td><td></td><td></td><td></td><td></td><td>-3.30</td><td>-3.47</td><td>0.00</td><td>-3.30</td><td>-0.336</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.336</td></tr><tr><td style="text-align:center;">60</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13676">권광민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.440</td><td>17</td><td>4</td><td>59.0</td><td>18</td><td>16</td><td>0</td><td>2</td><td>88.9</td><td>2.44</td><td style="">-3.36</td><td>-0.54</td><td>-0.42</td><td></td><td></td><td></td><td></td><td></td><td>-4.31</td><td>-9.41</td><td>0.00</td><td>-4.31</td><td>-0.440</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.440</td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15647">윌리엄스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.818</td><td>37</td><td>36</td><td>303.0</td><td>73</td><td>70</td><td>2</td><td>1</td><td>98.6</td><td>2.14</td><td style="">-5.83</td><td>-0.74</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-6.52</td><td>-13.80</td><td>-1.50</td><td>-8.02</td><td>-0.665</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.818</td></tr><tr><td style="text-align:center;">62</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11215">채은성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.913</td><td>76</td><td>68</td><td>603.1</td><td>574</td><td>540</td><td>30</td><td>4</td><td>99.3</td><td>8.50</td><td style="">-3.57</td><td></td><td>0.60</td><td></td><td>0.14</td><td></td><td></td><td></td><td>-2.83</td><td>-2.98</td><td>-6.12</td><td>-8.95</td><td>-0.289</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.913</td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12871">박상원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>55</td><td>0</td><td>61.2</td><td>18</td><td>3</td><td>14</td><td>1</td><td>94.4</td><td>2.48</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14209">김건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.10</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.10</td><td>2.07</td><td></td><td></td><td>0.010</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14880">장지승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.38</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.38</td><td>-18.19</td><td></td><td></td><td>-0.039</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10156">정우람</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>52</td><td>0</td><td>40.1</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>0.22</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td></td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11110">윤대경</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>47</td><td>0</td><td>47.2</td><td>7</td><td>1</td><td>6</td><td>0</td><td>100.0</td><td>1.32</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10609">이태양</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>50</td><td>12</td><td>100.1</td><td>19</td><td>6</td><td>13</td><td>0</td><td>100.0</td><td>1.70</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14209">김건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.01</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.01</td><td>-0.25</td><td></td><td></td><td>-0.001</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15014">박준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>4</td><td>0</td><td>4.1</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>2.08</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15421">김서현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>20</td><td>1</td><td>22.1</td><td>4</td><td>0</td><td>4</td><td>0</td><td>100.0</td><td>1.61</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14708">강재민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#f37321;color:#fff;">23</span> <span><img src="/data/team/ci/2023/7002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>43</td><td>0</td><td>43.1</td><td>5</td><td>0</td><td>5</td><td>0</td><td>100.0</td><td>1.04</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td></td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>
""")

In [62]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10475">오지환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.360</td><td>125</td><td>115</td><td>1010.2</td><td>465</td><td>176</td><td>275</td><td>14</td><td>97.0</td><td>4.02</td><td style="">3.31</td><td></td><td>-0.59</td><td>0.68</td><td></td><td></td><td></td><td></td><td>3.40</td><td>3.88</td><td>9.94</td><td>13.34</td><td>0.346</td><td style="background-color:#F3F3F3; font-weight:bold;">1.360</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10387">박동원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.240</td><td>128</td><td>112</td><td>982.0</td><td>831</td><td>751</td><td>72</td><td>8</td><td>99.0</td><td>7.54</td><td style="">-0.64</td><td></td><td>-1.42</td><td></td><td>0.14</td><td>1.90</td><td>1.55</td><td></td><td>1.07</td><td>1.18</td><td>11.09</td><td>12.15</td><td>0.109</td><td style="background-color:#F3F3F3; font-weight:bold;">1.240</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11190">박해민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.920</td><td>142</td><td>136</td><td>1187.2</td><td>343</td><td>338</td><td>2</td><td>3</td><td>99.1</td><td>2.58</td><td style="">8.18</td><td>0.81</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>9.02</td><td>9.02</td><td>0.00</td><td>9.02</td><td>0.920</td><td style="background-color:#F3F3F3; font-weight:bold;">0.920</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10238">김민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.518</td><td>45</td><td>37</td><td>280.0</td><td>147</td><td>68</td><td>78</td><td>1</td><td>99.3</td><td>4.69</td><td style="">1.91</td><td></td><td>0.76</td><td>1.14</td><td></td><td></td><td></td><td></td><td>3.81</td><td>4.90</td><td>1.27</td><td>5.08</td><td>0.389</td><td style="background-color:#F3F3F3; font-weight:bold;">0.518</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13056">신민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.505</td><td>89</td><td>76</td><td>689.1</td><td>402</td><td>162</td><td>231</td><td>9</td><td>97.8</td><td>5.13</td><td style="">0.99</td><td></td><td>0.38</td><td>0.41</td><td></td><td></td><td></td><td></td><td>1.78</td><td>2.10</td><td>3.17</td><td>4.95</td><td>0.181</td><td style="background-color:#F3F3F3; font-weight:bold;">0.505</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10238">김민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.411</td><td>27</td><td>14</td><td>135.0</td><td>42</td><td>14</td><td>27</td><td>1</td><td>97.6</td><td>2.73</td><td style="">3.45</td><td></td><td>0.31</td><td>0.04</td><td>0.23</td><td></td><td></td><td></td><td>4.03</td><td>5.18</td><td>0.00</td><td>4.03</td><td>0.411</td><td style="background-color:#F3F3F3; font-weight:bold;">0.411</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12546">홍창기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.307</td><td>27</td><td>27</td><td>228.0</td><td>64</td><td>64</td><td>0</td><td>0</td><td>100.0</td><td>2.53</td><td style="">4.26</td><td>-0.38</td><td>0.40</td><td></td><td></td><td></td><td></td><td></td><td>4.28</td><td>4.37</td><td>-1.27</td><td>3.01</td><td>0.437</td><td style="background-color:#F3F3F3; font-weight:bold;">0.307</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10684">허도환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.195</td><td>45</td><td>21</td><td>212.0</td><td>176</td><td>168</td><td>8</td><td>0</td><td>100.0</td><td>7.47</td><td style="">-0.20</td><td></td><td>0.55</td><td></td><td></td><td>-0.63</td><td>0.48</td><td></td><td>0.06</td><td>0.18</td><td>1.85</td><td>1.91</td><td>0.006</td><td style="background-color:#F3F3F3; font-weight:bold;">0.195</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14590">손호영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.139</td><td>7</td><td>2</td><td>29.0</td><td>15</td><td>5</td><td>10</td><td>0</td><td>100.0</td><td>4.66</td><td style="">1.18</td><td></td><td>0.08</td><td>0.00</td><td></td><td></td><td></td><td></td><td>1.26</td><td>6.71</td><td>0.10</td><td>1.36</td><td>0.128</td><td style="background-color:#F3F3F3; font-weight:bold;">0.139</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12546">홍창기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.127</td><td>104</td><td>97</td><td>841.2</td><td>207</td><td>198</td><td>7</td><td>2</td><td>99.0</td><td>2.19</td><td style="">3.96</td><td>1.18</td><td>0.63</td><td></td><td></td><td></td><td></td><td></td><td>5.78</td><td>5.90</td><td>-4.53</td><td>1.25</td><td>0.589</td><td style="background-color:#F3F3F3; font-weight:bold;">0.127</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13112">문성주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.120</td><td>85</td><td>64</td><td>602.2</td><td>164</td><td>162</td><td>1</td><td>1</td><td>99.4</td><td>2.43</td><td style="">4.32</td><td>-0.84</td><td>0.57</td><td></td><td></td><td></td><td></td><td></td><td>4.05</td><td>4.28</td><td>-2.87</td><td>1.18</td><td>0.413</td><td style="background-color:#F3F3F3; font-weight:bold;">0.120</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13056">신민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.086</td><td>7</td><td>0</td><td>10.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>2.70</td><td style="">0.45</td><td>0.38</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.84</td><td>0.99</td><td>0.00</td><td>0.84</td><td>0.086</td><td style="background-color:#F3F3F3; font-weight:bold;">0.086</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13112">문성주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.080</td><td>56</td><td>43</td><td>386.2</td><td>103</td><td>97</td><td>4</td><td>2</td><td>98.1</td><td>2.35</td><td style="">2.35</td><td>0.21</td><td>0.25</td><td></td><td></td><td></td><td></td><td></td><td>2.81</td><td>2.98</td><td>-2.03</td><td>0.78</td><td>0.287</td><td style="background-color:#F3F3F3; font-weight:bold;">0.080</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14187">최승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.072</td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.71</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.71</td><td>2.70</td><td>-0.01</td><td>0.70</td><td>0.073</td><td style="background-color:#F3F3F3; font-weight:bold;">0.072</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10187">김현수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.065</td><td>10</td><td>10</td><td>68.1</td><td>66</td><td>53</td><td>11</td><td>2</td><td>97.0</td><td>8.43</td><td style="">1.83</td><td></td><td>-0.37</td><td></td><td></td><td></td><td></td><td></td><td>1.46</td><td>1.58</td><td>-0.82</td><td>0.64</td><td>0.149</td><td style="background-color:#F3F3F3; font-weight:bold;">0.065</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11347">안익훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.046</td><td>5</td><td>1</td><td>19.2</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>2.29</td><td style="">0.10</td><td>0.39</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.53</td><td>6.90</td><td>-0.08</td><td>0.45</td><td>0.054</td><td style="background-color:#F3F3F3; font-weight:bold;">0.046</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14187">최승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.043</td><td>12</td><td>1</td><td>35.0</td><td>13</td><td>13</td><td>0</td><td>0</td><td>100.0</td><td>3.34</td><td style="">1.56</td><td>-1.19</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>0.42</td><td>1.59</td><td>0.00</td><td>0.42</td><td>0.043</td><td style="background-color:#F3F3F3; font-weight:bold;">0.043</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11347">안익훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.042</td><td>1</td><td>1</td><td>6.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.50</td><td style="">0.40</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.41</td><td>5.40</td><td>0.00</td><td>0.41</td><td>0.042</td><td style="background-color:#F3F3F3; font-weight:bold;">0.042</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13056">신민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.010</td><td>10</td><td>0</td><td>19.2</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>1.83</td><td style="">-0.18</td><td>0.28</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.13</td><td>0.16</td><td>-0.04</td><td>0.09</td><td>0.014</td><td style="background-color:#F3F3F3; font-weight:bold;">0.010</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12864">전준호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.005</td><td>2</td><td>0</td><td>3.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>12.00</td><td style="">0.00</td><td></td><td>0.01</td><td></td><td></td><td>-0.04</td><td>0.08</td><td></td><td>0.02</td><td>1.51</td><td>0.02</td><td>0.05</td><td>0.002</td><td style="background-color:#F3F3F3; font-weight:bold;">0.005</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13056">신민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.001</td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.01</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.01</td><td>-0.01</td><td>0.00</td><td>-0.01</td><td>-0.001</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.001</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13104">이재원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.002</td><td>2</td><td>1</td><td>4.2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.02</td><td>-0.03</td><td>-0.02</td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.002</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13104">이재원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.011</td><td>4</td><td>2</td><td>20.0</td><td>17</td><td>14</td><td>2</td><td>1</td><td>94.1</td><td>7.20</td><td style="">0.45</td><td></td><td>-0.46</td><td></td><td>0.06</td><td></td><td></td><td></td><td>0.05</td><td>0.13</td><td>-0.16</td><td>-0.11</td><td>0.005</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.011</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13109">송찬의</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.023</td><td>5</td><td>3</td><td>20.0</td><td>17</td><td>16</td><td>1</td><td>0</td><td>100.0</td><td>7.65</td><td style="">-0.14</td><td></td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-0.11</td><td>-0.80</td><td>-0.12</td><td>-0.23</td><td>-0.011</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.023</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10238">김민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.027</td><td>21</td><td>18</td><td>145.0</td><td>78</td><td>34</td><td>40</td><td>4</td><td>94.9</td><td>4.59</td><td style="">-0.72</td><td></td><td>-0.15</td><td>-0.76</td><td></td><td></td><td></td><td></td><td>-1.64</td><td>-2.11</td><td>1.38</td><td>-0.26</td><td>-0.167</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.027</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10935">이천웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.030</td><td>2</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.29</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.28</td><td>-10.19</td><td>-0.01</td><td>-0.29</td><td>-0.029</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.030</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13056">신민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.048</td><td>6</td><td>0</td><td>11.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>1.64</td><td style="">-0.05</td><td>-0.41</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.44</td><td>-0.51</td><td>-0.03</td><td>-0.47</td><td>-0.044</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.048</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14591">이주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.060</td><td>3</td><td>0</td><td>9.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>2.00</td><td style="">-0.63</td><td>0.05</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.56</td><td>-1.16</td><td>-0.03</td><td>-0.59</td><td>-0.057</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.060</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14590">손호영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.061</td><td>13</td><td>7</td><td>66.2</td><td>41</td><td>19</td><td>18</td><td>4</td><td>90.2</td><td>5.00</td><td style="">-1.79</td><td></td><td>-0.34</td><td>0.95</td><td></td><td></td><td></td><td></td><td>-1.18</td><td>-6.29</td><td>0.58</td><td>-0.60</td><td>-0.120</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.061</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15492">송대현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.082</td><td>3</td><td>0</td><td>6.0</td><td>3</td><td>1</td><td>1</td><td>1</td><td>66.7</td><td>3.00</td><td style="">-0.86</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.84</td><td>-30.37</td><td>0.04</td><td>-0.80</td><td>-0.086</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.082</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13109">송찬의</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.084</td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0.0</td><td>0.00</td><td style="">-0.83</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.83</td><td>-6.30</td><td>0.01</td><td>-0.82</td><td>-0.085</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.084</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14590">손호영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.086</td><td>2</td><td>1</td><td>5.0</td><td>4</td><td>1</td><td>2</td><td>1</td><td>75.0</td><td>5.40</td><td style="">-0.85</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.84</td><td>-4.48</td><td>0.00</td><td>-0.84</td><td>-0.086</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.086</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11347">안익훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.093</td><td>8</td><td>2</td><td>30.1</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>2.08</td><td style="">-0.12</td><td>-0.74</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>-0.80</td><td>-10.52</td><td>-0.11</td><td>-0.91</td><td>-0.082</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.093</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12546">홍창기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.097</td><td>12</td><td>6</td><td>53.2</td><td>14</td><td>14</td><td>0</td><td>0</td><td>100.0</td><td>2.35</td><td style="">-0.62</td><td>-0.40</td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>-0.95</td><td>-0.97</td><td>0.00</td><td>-0.95</td><td>-0.097</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.097</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14187">최승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.104</td><td>8</td><td>0</td><td>16.1</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>1.10</td><td style="">-1.10</td><td>0.08</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.99</td><td>-3.76</td><td>-0.03</td><td>-1.02</td><td>-0.101</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.104</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12545">김주성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.110</td><td>7</td><td>0</td><td>18.0</td><td>7</td><td>2</td><td>3</td><td>2</td><td>71.4</td><td>2.50</td><td style="">-0.98</td><td></td><td>0.04</td><td>-0.24</td><td></td><td></td><td></td><td></td><td>-1.18</td><td>-15.41</td><td>0.10</td><td>-1.08</td><td>-0.120</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.110</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15532">오스틴</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.118</td><td>2</td><td>1</td><td>9.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>2.00</td><td style="">-0.94</td><td>-0.19</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-1.11</td><td>-1.15</td><td>-0.04</td><td>-1.15</td><td>-0.113</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.118</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14591">이주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.120</td><td>6</td><td>1</td><td>20.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>1.35</td><td style="">-1.17</td><td>0.01</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-1.13</td><td>-2.36</td><td>-0.05</td><td>-1.18</td><td>-0.115</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.120</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10480">정주현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.138</td><td>11</td><td>4</td><td>47.0</td><td>21</td><td>11</td><td>9</td><td>1</td><td>95.2</td><td>3.83</td><td style="">-1.23</td><td></td><td>0.11</td><td>-0.63</td><td></td><td></td><td></td><td></td><td>-1.75</td><td>-2.84</td><td>0.40</td><td>-1.35</td><td>-0.179</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.138</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10480">정주현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.204</td><td>18</td><td>4</td><td>57.0</td><td>32</td><td>12</td><td>16</td><td>4</td><td>87.5</td><td>4.42</td><td style="">-1.13</td><td></td><td>-0.84</td><td>-0.23</td><td></td><td></td><td></td><td></td><td>-2.20</td><td>-3.56</td><td>0.20</td><td>-2.00</td><td>-0.225</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.204</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13104">이재원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.213</td><td>36</td><td>25</td><td>180.1</td><td>53</td><td>50</td><td>2</td><td>1</td><td>98.1</td><td>2.60</td><td style="">-1.22</td><td>0.11</td><td>-0.17</td><td></td><td></td><td></td><td></td><td></td><td>-1.29</td><td>-3.26</td><td>-0.80</td><td>-2.09</td><td>-0.132</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.213</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10480">정주현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.237</td><td>47</td><td>1</td><td>100.0</td><td>97</td><td>86</td><td>10</td><td>1</td><td>99.0</td><td>8.64</td><td style="">-1.91</td><td></td><td>0.18</td><td></td><td>0.06</td><td></td><td></td><td></td><td>-1.67</td><td>-2.69</td><td>-0.66</td><td>-2.33</td><td>-0.170</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.237</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10238">김민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.240</td><td>27</td><td>10</td><td>105.2</td><td>97</td><td>85</td><td>10</td><td>2</td><td>97.9</td><td>8.09</td><td style="">-1.23</td><td></td><td>-0.30</td><td></td><td>0.06</td><td></td><td></td><td></td><td>-1.47</td><td>-1.89</td><td>-0.88</td><td>-2.35</td><td>-0.150</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.240</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15484">김범석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.251</td><td>5</td><td>5</td><td>43.0</td><td>45</td><td>38</td><td>5</td><td>2</td><td>95.6</td><td>9.00</td><td style="">-0.85</td><td></td><td>-0.42</td><td></td><td>-0.79</td><td></td><td></td><td></td><td>-2.06</td><td>-29.73</td><td>-0.40</td><td>-2.46</td><td>-0.211</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.251</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10480">정주현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.281</td><td>16</td><td>3</td><td>58.2</td><td>21</td><td>5</td><td>12</td><td>4</td><td>81.0</td><td>2.61</td><td style="">-2.37</td><td></td><td>0.14</td><td>-0.53</td><td></td><td></td><td></td><td></td><td>-2.76</td><td>-4.46</td><td>0.00</td><td>-2.76</td><td>-0.281</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.281</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14137">문보경</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.330</td><td>128</td><td>126</td><td>1090.2</td><td>308</td><td>104</td><td>184</td><td>20</td><td>93.5</td><td>2.38</td><td style="">-2.45</td><td></td><td>-0.94</td><td>0.49</td><td>-0.34</td><td></td><td></td><td></td><td>-3.24</td><td>-3.56</td><td>0.00</td><td>-3.24</td><td>-0.330</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.330</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10187">김현수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.332</td><td>27</td><td>26</td><td>204.2</td><td>46</td><td>45</td><td>1</td><td>0</td><td>100.0</td><td>2.02</td><td style="">-2.61</td><td>0.09</td><td>0.36</td><td></td><td></td><td></td><td></td><td></td><td>-2.15</td><td>-2.33</td><td>-1.10</td><td>-3.25</td><td>-0.220</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.332</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10855">서건창</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.351</td><td>35</td><td>25</td><td>237.0</td><td>123</td><td>53</td><td>61</td><td>9</td><td>92.7</td><td>4.33</td><td style="">-1.40</td><td></td><td>-1.83</td><td>-1.32</td><td></td><td></td><td></td><td></td><td>-4.55</td><td>-14.89</td><td>1.11</td><td>-3.44</td><td>-0.464</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.351</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12549">김기연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.367</td><td>27</td><td>11</td><td>96.1</td><td>96</td><td>85</td><td>7</td><td>4</td><td>95.8</td><td>8.60</td><td style="">-0.05</td><td></td><td>-1.73</td><td></td><td></td><td>-1.23</td><td>-2.12</td><td></td><td>-4.49</td><td>-23.09</td><td>0.89</td><td>-3.60</td><td>-0.458</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.367</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15532">오스틴</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.808</td><td>114</td><td>113</td><td>930.1</td><td>917</td><td>831</td><td>72</td><td>14</td><td>98.5</td><td>8.74</td><td style="">2.86</td><td></td><td>-1.28</td><td></td><td>0.18</td><td></td><td></td><td></td><td>1.76</td><td>1.82</td><td>-9.68</td><td>-7.92</td><td>0.179</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.808</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13112">문성주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.18</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.18</td><td>0.20</td><td></td><td></td><td>0.019</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12532">김대현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>5</td><td>0</td><td>3.1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15485">김동규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>0.1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12545">김주성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.01</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>-0.03</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12907">고우석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>44</td><td>0</td><td>44.0</td><td>9</td><td>3</td><td>5</td><td>1</td><td>88.9</td><td>1.64</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14590">손호영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>5</td><td>0</td><td>6.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>6.00</td><td style="">-0.60</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.59</td><td>-3.15</td><td></td><td></td><td>-0.060</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15486">박명근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>55</td><td>1</td><td>51.1</td><td>6</td><td>2</td><td>4</td><td>0</td><td>100.0</td><td>1.05</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10535">최동환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>43</td><td>0</td><td>42.1</td><td>6</td><td>1</td><td>5</td><td>0</td><td>100.0</td><td>1.28</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11387">채지선</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>0.2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12860">오석주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>9</td><td>0</td><td>10.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14134">이정용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#fc1cad;color:#fff;">23</span> <span><img src="/data/team/ci/2023/5002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>37</td><td>13</td><td>86.2</td><td>12</td><td>3</td><td>8</td><td>1</td><td>91.7</td><td>1.14</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>
""")

In [63]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10753">유강남</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.911</td><td>109</td><td>98</td><td>821.0</td><td>778</td><td>714</td><td>60</td><td>4</td><td>99.5</td><td>8.48</td><td style="">0.32</td><td></td><td>0.64</td><td></td><td>-0.03</td><td>-2.81</td><td>2.72</td><td></td><td>0.03</td><td>0.03</td><td>8.90</td><td>8.93</td><td>0.003</td><td style="background-color:#F3F3F3; font-weight:bold;">0.911</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11165">노진혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.720</td><td>107</td><td>95</td><td>827.0</td><td>373</td><td>142</td><td>220</td><td>11</td><td>97.1</td><td>3.94</td><td style="">-2.87</td><td></td><td>0.96</td><td>1.48</td><td></td><td></td><td></td><td></td><td>-0.44</td><td>-0.56</td><td>7.50</td><td>7.06</td><td>-0.045</td><td style="background-color:#F3F3F3; font-weight:bold;">0.720</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14796">손성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.407</td><td>44</td><td>20</td><td>201.2</td><td>180</td><td>166</td><td>13</td><td>1</td><td>99.4</td><td>7.99</td><td style="">1.05</td><td></td><td>0.03</td><td></td><td>-0.01</td><td>1.54</td><td>-0.74</td><td></td><td>2.09</td><td>6.70</td><td>1.90</td><td>3.99</td><td>0.213</td><td style="background-color:#F3F3F3; font-weight:bold;">0.407</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10804">박승욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.303</td><td>22</td><td>15</td><td>134.0</td><td>73</td><td>25</td><td>47</td><td>1</td><td>98.6</td><td>4.84</td><td style="">1.85</td><td></td><td>0.32</td><td>-0.39</td><td></td><td></td><td></td><td></td><td>1.77</td><td>2.08</td><td>1.20</td><td>2.97</td><td>0.181</td><td style="background-color:#F3F3F3; font-weight:bold;">0.303</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14642">황성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.235</td><td>60</td><td>36</td><td>337.0</td><td>99</td><td>96</td><td>2</td><td>1</td><td>99.0</td><td>2.62</td><td style="">3.60</td><td>0.09</td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>3.79</td><td>7.38</td><td>-1.49</td><td>2.30</td><td>0.387</td><td style="background-color:#F3F3F3; font-weight:bold;">0.235</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13154">정보근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.185</td><td>51</td><td>23</td><td>228.2</td><td>216</td><td>191</td><td>24</td><td>1</td><td>99.5</td><td>8.46</td><td style="">-0.52</td><td></td><td>0.59</td><td></td><td></td><td>1.15</td><td>-2.42</td><td></td><td>-0.47</td><td>-1.22</td><td>2.28</td><td>1.81</td><td>-0.048</td><td style="background-color:#F3F3F3; font-weight:bold;">0.185</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14571">안권수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.181</td><td>27</td><td>18</td><td>157.0</td><td>47</td><td>46</td><td>1</td><td>0</td><td>100.0</td><td>2.69</td><td style="">1.89</td><td>0.40</td><td>0.30</td><td></td><td></td><td></td><td></td><td></td><td>2.59</td><td>3.93</td><td>-0.82</td><td>1.77</td><td>0.264</td><td style="background-color:#F3F3F3; font-weight:bold;">0.181</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14642">황성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.162</td><td>2</td><td>1</td><td>9.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">1.04</td><td>0.57</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>1.63</td><td>3.17</td><td>-0.04</td><td>1.59</td><td>0.166</td><td style="background-color:#F3F3F3; font-weight:bold;">0.162</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14642">황성빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.160</td><td>14</td><td>9</td><td>68.2</td><td>21</td><td>21</td><td>0</td><td>0</td><td>100.0</td><td>2.75</td><td style="">1.00</td><td>0.48</td><td>0.09</td><td></td><td></td><td></td><td></td><td></td><td>1.56</td><td>3.04</td><td>0.00</td><td>1.56</td><td>0.160</td><td style="background-color:#F3F3F3; font-weight:bold;">0.160</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11413">지시완</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.148</td><td>2</td><td>2</td><td>15.0</td><td>15</td><td>10</td><td>5</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.38</td><td></td><td>0.04</td><td></td><td></td><td>0.40</td><td>0.71</td><td></td><td>1.31</td><td>31.49</td><td>0.14</td><td>1.46</td><td>0.134</td><td style="background-color:#F3F3F3; font-weight:bold;">0.148</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10014">안치홍</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.144</td><td>93</td><td>87</td><td>699.0</td><td>386</td><td>175</td><td>209</td><td>2</td><td>99.5</td><td>4.94</td><td style="">-3.32</td><td></td><td>1.39</td><td>-0.25</td><td></td><td></td><td></td><td></td><td>-2.17</td><td>-2.58</td><td>3.58</td><td>1.41</td><td>-0.221</td><td style="background-color:#F3F3F3; font-weight:bold;">0.144</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10804">박승욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.122</td><td>76</td><td>44</td><td>447.1</td><td>277</td><td>104</td><td>165</td><td>8</td><td>97.1</td><td>5.41</td><td style="">-0.85</td><td></td><td>-0.77</td><td>0.92</td><td></td><td></td><td></td><td></td><td>-0.70</td><td>-0.81</td><td>1.89</td><td>1.19</td><td>-0.071</td><td style="background-color:#F3F3F3; font-weight:bold;">0.122</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13155">장두성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.113</td><td>15</td><td>1</td><td>43.0</td><td>10</td><td>10</td><td>0</td><td>0</td><td>100.0</td><td>2.09</td><td style="">1.32</td><td>-0.27</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>1.10</td><td>6.36</td><td>0.00</td><td>1.10</td><td>0.113</td><td style="background-color:#F3F3F3; font-weight:bold;">0.113</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14571">안권수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.099</td><td>60</td><td>32</td><td>312.2</td><td>99</td><td>92</td><td>4</td><td>3</td><td>97.0</td><td>2.76</td><td style="">3.51</td><td>-0.05</td><td>-0.93</td><td></td><td></td><td></td><td></td><td></td><td>2.53</td><td>3.84</td><td>-1.56</td><td>0.97</td><td>0.259</td><td style="background-color:#F3F3F3; font-weight:bold;">0.099</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15625">배영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.078</td><td>10</td><td>5</td><td>43.0</td><td>19</td><td>6</td><td>12</td><td>1</td><td>94.7</td><td>3.77</td><td style="">0.78</td><td></td><td>0.10</td><td>-0.43</td><td></td><td></td><td></td><td></td><td>0.45</td><td>3.59</td><td>0.32</td><td>0.77</td><td>0.046</td><td style="background-color:#F3F3F3; font-weight:bold;">0.078</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15624">서동욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.071</td><td>5</td><td>4</td><td>25.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>1.80</td><td style="">0.87</td><td>-0.13</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>0.79</td><td>8.76</td><td>-0.09</td><td>0.70</td><td>0.081</td><td style="background-color:#F3F3F3; font-weight:bold;">0.071</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15645">김동혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.067</td><td>9</td><td>2</td><td>18.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>2.00</td><td style="">0.90</td><td>-0.22</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.71</td><td>6.81</td><td>-0.05</td><td>0.66</td><td>0.072</td><td style="background-color:#F3F3F3; font-weight:bold;">0.067</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14169">신윤후</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.058</td><td>4</td><td>1</td><td>12.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>3.75</td><td style="">0.97</td><td>-0.41</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.57</td><td>2.93</td><td>0.00</td><td>0.57</td><td>0.058</td><td style="background-color:#F3F3F3; font-weight:bold;">0.058</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14571">안권수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.046</td><td>30</td><td>18</td><td>143.2</td><td>49</td><td>48</td><td>1</td><td>0</td><td>100.0</td><td>3.07</td><td style="">0.29</td><td>-0.02</td><td>0.18</td><td></td><td></td><td></td><td></td><td></td><td>0.45</td><td>0.68</td><td>0.00</td><td>0.45</td><td>0.046</td><td style="background-color:#F3F3F3; font-weight:bold;">0.046</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15625">배영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.043</td><td>2</td><td>0</td><td>2.0</td><td>2</td><td>1</td><td>1</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.42</td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td></td><td></td><td>0.42</td><td>3.38</td><td>0.00</td><td>0.42</td><td>0.043</td><td style="background-color:#F3F3F3; font-weight:bold;">0.043</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15627">윤수녕</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.017</td><td>1</td><td>0</td><td>3.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">0.17</td><td>0.00</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.17</td><td>8.35</td><td>-0.01</td><td>0.16</td><td>0.018</td><td style="background-color:#F3F3F3; font-weight:bold;">0.017</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14160">고승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.013</td><td>30</td><td>15</td><td>141.2</td><td>24</td><td>24</td><td>0</td><td>0</td><td>100.0</td><td>1.52</td><td style="">0.72</td><td>-0.28</td><td>0.27</td><td></td><td></td><td></td><td></td><td></td><td>0.71</td><td>1.09</td><td>-0.59</td><td>0.12</td><td>0.073</td><td style="background-color:#F3F3F3; font-weight:bold;">0.013</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10172">국해성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.010</td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.10</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.11</td><td>2.58</td><td>-0.01</td><td>0.10</td><td>0.011</td><td style="background-color:#F3F3F3; font-weight:bold;">0.010</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13155">장두성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.001</td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.01</td><td>-0.01</td><td>-0.01</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.001</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14114">이학주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.011</td><td>53</td><td>13</td><td>162.2</td><td>54</td><td>16</td><td>35</td><td>3</td><td>94.4</td><td>2.82</td><td style="">0.87</td><td></td><td>-0.61</td><td>-0.45</td><td>0.09</td><td></td><td></td><td></td><td>-0.11</td><td>-0.16</td><td>0.00</td><td>-0.11</td><td>-0.011</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.011</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14114">이학주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.020</td><td>53</td><td>16</td><td>178.1</td><td>91</td><td>30</td><td>56</td><td>5</td><td>94.5</td><td>4.34</td><td style="">-0.60</td><td></td><td>-0.08</td><td>-0.76</td><td></td><td></td><td></td><td></td><td>-1.44</td><td>-1.99</td><td>1.24</td><td>-0.20</td><td>-0.147</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.020</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15048">윤동희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.025</td><td>94</td><td>79</td><td>716.1</td><td>161</td><td>156</td><td>2</td><td>3</td><td>98.1</td><td>1.99</td><td style="">3.23</td><td>0.28</td><td>-0.10</td><td></td><td></td><td></td><td></td><td></td><td>3.41</td><td>4.59</td><td>-3.65</td><td>-0.24</td><td>0.348</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.025</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14169">신윤후</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.033</td><td>17</td><td>5</td><td>60.0</td><td>15</td><td>13</td><td>0</td><td>2</td><td>86.7</td><td>1.95</td><td style="">0.76</td><td>0.01</td><td>-0.88</td><td></td><td></td><td></td><td></td><td></td><td>-0.12</td><td>-0.61</td><td>-0.20</td><td>-0.32</td><td>-0.012</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.033</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15627">윤수녕</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.042</td><td>2</td><td>1</td><td>10.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>0.90</td><td style="">-0.06</td><td>-0.34</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.38</td><td>-18.35</td><td>-0.03</td><td>-0.41</td><td>-0.039</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.042</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15624">서동욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.042</td><td>1</td><td>1</td><td>6.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>7.50</td><td style="">0.00</td><td></td><td>0.02</td><td></td><td></td><td>-0.29</td><td>-0.27</td><td></td><td>-0.46</td><td>-5.13</td><td>0.05</td><td>-0.41</td><td>-0.047</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.042</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12931">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.055</td><td>1</td><td>0</td><td>2.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>4.50</td><td style="">-0.56</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.55</td><td>-3.19</td><td>0.01</td><td>-0.54</td><td>-0.056</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.055</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15651">구드럼</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.089</td><td>38</td><td>29</td><td>274.0</td><td>80</td><td>21</td><td>51</td><td>8</td><td>90.0</td><td>2.36</td><td style="">-1.10</td><td></td><td>-0.36</td><td>0.47</td><td>0.12</td><td></td><td></td><td></td><td>-0.87</td><td>-2.51</td><td>0.00</td><td>-0.87</td><td>-0.089</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.089</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12931">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.090</td><td>9</td><td>6</td><td>48.0</td><td>40</td><td>39</td><td>1</td><td>0</td><td>100.0</td><td>7.50</td><td style="">-0.59</td><td></td><td>0.09</td><td></td><td></td><td></td><td></td><td></td><td>-0.50</td><td>-2.91</td><td>-0.38</td><td>-0.88</td><td>-0.051</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.090</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10804">박승욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.091</td><td>2</td><td>0</td><td>2.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>4.50</td><td style="">-0.88</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.87</td><td>-1.02</td><td>-0.02</td><td>-0.89</td><td>-0.089</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.091</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15048">윤동희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.103</td><td>8</td><td>2</td><td>23.1</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>1.54</td><td style="">-1.09</td><td>0.11</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-0.93</td><td>-1.25</td><td>-0.08</td><td>-1.01</td><td>-0.095</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.103</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15651">구드럼</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.108</td><td>1</td><td>1</td><td>6.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-1.03</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-1.02</td><td>-2.95</td><td>-0.04</td><td>-1.06</td><td>-0.104</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.108</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12931">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.112</td><td>11</td><td>8</td><td>69.0</td><td>19</td><td>5</td><td>12</td><td>2</td><td>89.5</td><td>2.22</td><td style="">-0.71</td><td></td><td>-0.34</td><td>-0.15</td><td>0.10</td><td></td><td></td><td></td><td>-1.09</td><td>-6.30</td><td>0.00</td><td>-1.09</td><td>-0.112</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.112</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15651">구드럼</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.120</td><td>1</td><td>1</td><td>8.0</td><td>4</td><td>2</td><td>1</td><td>1</td><td>75.0</td><td>3.38</td><td style="">-1.24</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-1.22</td><td>-3.52</td><td>0.04</td><td>-1.18</td><td>-0.124</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.120</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15651">구드럼</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.122</td><td>1</td><td>1</td><td>5.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>5.40</td><td style="">-0.85</td><td>-0.32</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-1.16</td><td>-3.35</td><td>-0.03</td><td>-1.19</td><td>-0.119</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.122</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14160">고승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.125</td><td>2</td><td>2</td><td>14.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>1.93</td><td style="">-0.81</td><td>-0.35</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-1.13</td><td>-1.73</td><td>-0.09</td><td>-1.22</td><td>-0.115</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.125</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15625">배영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.127</td><td>5</td><td>0</td><td>6.0</td><td>3</td><td>1</td><td>1</td><td>1</td><td>66.7</td><td>3.00</td><td style="">-0.77</td><td></td><td>-0.48</td><td></td><td></td><td></td><td></td><td></td><td>-1.25</td><td>-10.02</td><td>0.01</td><td>-1.24</td><td>-0.128</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.127</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12916">이정훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.130</td><td>3</td><td>2</td><td>17.0</td><td>18</td><td>15</td><td>3</td><td>0</td><td>100.0</td><td>9.53</td><td style="">-1.12</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-1.09</td><td>-2.66</td><td>-0.18</td><td>-1.27</td><td>-0.111</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.130</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15443">정대선</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.136</td><td>18</td><td>11</td><td>101.0</td><td>40</td><td>14</td><td>26</td><td>0</td><td>100.0</td><td>3.56</td><td style="">-1.36</td><td></td><td>0.27</td><td>-0.68</td><td></td><td></td><td></td><td></td><td>-1.77</td><td>-13.40</td><td>0.43</td><td>-1.34</td><td>-0.180</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.136</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14114">이학주</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.150</td><td>4</td><td>1</td><td>9.0</td><td>8</td><td>5</td><td>2</td><td>1</td><td>87.5</td><td>7.00</td><td style="">-1.51</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-1.49</td><td>-2.06</td><td>0.02</td><td>-1.47</td><td>-0.152</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.150</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10266">전준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.169</td><td>3</td><td>3</td><td>26.2</td><td>30</td><td>27</td><td>2</td><td>1</td><td>96.7</td><td>9.79</td><td style="">-1.08</td><td></td><td>0.05</td><td></td><td>-0.37</td><td></td><td></td><td></td><td>-1.39</td><td>-1.45</td><td>-0.26</td><td>-1.65</td><td>-0.142</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.169</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15152">렉스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.189</td><td>18</td><td>17</td><td>134.0</td><td>31</td><td>30</td><td>1</td><td>0</td><td>100.0</td><td>2.08</td><td style="">-1.47</td><td>0.11</td><td>0.24</td><td></td><td></td><td></td><td></td><td></td><td>-1.12</td><td>-2.93</td><td>-0.73</td><td>-1.85</td><td>-0.114</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.189</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12916">이정훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.224</td><td>11</td><td>9</td><td>63.0</td><td>19</td><td>18</td><td>0</td><td>1</td><td>94.7</td><td>2.57</td><td style="">-0.76</td><td>-0.73</td><td>-0.38</td><td></td><td></td><td></td><td></td><td></td><td>-1.87</td><td>-4.57</td><td>-0.32</td><td>-2.19</td><td>-0.191</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.224</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15651">구드럼</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.224</td><td>14</td><td>13</td><td>90.0</td><td>43</td><td>13</td><td>26</td><td>4</td><td>90.7</td><td>3.90</td><td style="">-2.94</td><td></td><td>-0.28</td><td>0.10</td><td></td><td></td><td></td><td></td><td>-3.12</td><td>-8.99</td><td>0.92</td><td>-2.20</td><td>-0.318</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.224</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15048">윤동희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.241</td><td>14</td><td>8</td><td>69.1</td><td>23</td><td>22</td><td>0</td><td>1</td><td>95.7</td><td>2.86</td><td style="">-1.76</td><td>-0.19</td><td>-0.41</td><td></td><td></td><td></td><td></td><td></td><td>-2.36</td><td>-3.18</td><td>0.00</td><td>-2.36</td><td>-0.241</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.241</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10804">박승욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.242</td><td>39</td><td>22</td><td>190.2</td><td>39</td><td>8</td><td>29</td><td>2</td><td>94.9</td><td>1.75</td><td style="">-2.26</td><td></td><td>-0.05</td><td>-0.15</td><td>0.09</td><td></td><td></td><td></td><td>-2.37</td><td>-2.78</td><td>0.00</td><td>-2.37</td><td>-0.242</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.242</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15152">렉스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.266</td><td>23</td><td>23</td><td>189.1</td><td>33</td><td>31</td><td>0</td><td>2</td><td>93.9</td><td>1.47</td><td style="">-1.05</td><td>0.05</td><td>-0.62</td><td></td><td></td><td></td><td></td><td></td><td>-1.62</td><td>-4.25</td><td>-0.99</td><td>-2.61</td><td>-0.165</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.266</td></tr><tr><td style="text-align:center;">52</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10266">전준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.360</td><td>44</td><td>40</td><td>309.1</td><td>77</td><td>74</td><td>2</td><td>1</td><td>98.7</td><td>2.21</td><td style="">-1.71</td><td>-0.26</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>-1.91</td><td>-1.99</td><td>-1.62</td><td>-3.53</td><td>-0.195</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.360</td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13145">한동희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.445</td><td>77</td><td>72</td><td>574.0</td><td>148</td><td>43</td><td>96</td><td>9</td><td>93.9</td><td>2.18</td><td style="">-5.06</td><td></td><td>0.34</td><td>0.29</td><td>0.08</td><td></td><td></td><td></td><td>-4.36</td><td>-5.82</td><td>0.00</td><td>-4.36</td><td>-0.445</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.445</td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10014">안치홍</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.452</td><td>34</td><td>22</td><td>211.0</td><td>214</td><td>201</td><td>11</td><td>2</td><td>99.1</td><td>9.04</td><td style="">-2.32</td><td></td><td>-0.11</td><td></td><td>0.06</td><td></td><td></td><td></td><td>-2.37</td><td>-2.83</td><td>-2.06</td><td>-4.43</td><td>-0.242</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.452</td></tr><tr><td style="text-align:center;">55</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13145">한동희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.528</td><td>22</td><td>10</td><td>107.2</td><td>107</td><td>99</td><td>5</td><td>3</td><td>97.2</td><td>8.69</td><td style="">-3.51</td><td></td><td>-0.79</td><td></td><td>0.06</td><td></td><td></td><td></td><td>-4.24</td><td>-5.65</td><td>-0.94</td><td>-5.18</td><td>-0.432</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.528</td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14160">고승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.548</td><td>62</td><td>54</td><td>449.2</td><td>429</td><td>390</td><td>37</td><td>2</td><td>99.5</td><td>8.55</td><td style="">-1.83</td><td></td><td>0.81</td><td></td><td>0.15</td><td></td><td></td><td></td><td>-0.87</td><td>-1.33</td><td>-4.50</td><td>-5.37</td><td>-0.089</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.548</td></tr><tr><td style="text-align:center;">57</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15253">김민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.629</td><td>125</td><td>107</td><td>933.2</td><td>247</td><td>243</td><td>3</td><td>1</td><td>99.6</td><td>2.37</td><td style="">-7.19</td><td>-0.17</td><td>1.19</td><td></td><td></td><td></td><td></td><td></td><td>-6.17</td><td>-6.89</td><td>0.00</td><td>-6.17</td><td>-0.629</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.629</td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10253">정훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.896</td><td>65</td><td>47</td><td>410.1</td><td>372</td><td>344</td><td>23</td><td>5</td><td>98.7</td><td>8.05</td><td style="">-5.25</td><td></td><td>0.74</td><td></td><td>-0.25</td><td></td><td></td><td></td><td>-4.76</td><td>-8.58</td><td>-4.02</td><td>-8.78</td><td>-0.486</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.896</td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15645">김동혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.02</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13155">장두성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>6</td><td>0</td><td>7.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>2.57</td><td style="">0.56</td><td>0.30</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.87</td><td>5.00</td><td></td><td></td><td>0.089</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10427">김상수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>65</td><td>0</td><td>52.0</td><td>8</td><td>2</td><td>5</td><td>1</td><td>87.5</td><td>1.21</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11276">최영환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>8</td><td>0</td><td>10.0</td><td>4</td><td>1</td><td>3</td><td>0</td><td>100.0</td><td>3.60</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15645">김동혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.02</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10825">김원중</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#888888;color:#fff;">23</span> <span><img src="/data/team/ci/2023/3001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>63</td><td>0</td><td>63.2</td><td>11</td><td>4</td><td>7</td><td>0</td><td>100.0</td><td>1.55</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>
""")

In [64]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11261">박찬호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.623</td><td>128</td><td>121</td><td>1042.2</td><td>523</td><td>206</td><td>303</td><td>14</td><td>97.3</td><td>4.39</td><td style="">5.08</td><td></td><td>1.46</td><td>-0.75</td><td></td><td></td><td></td><td></td><td>5.79</td><td>6.42</td><td>10.12</td><td>15.91</td><td>0.591</td><td style="background-color:#F3F3F3; font-weight:bold;">1.623</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15056">김도영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.647</td><td>81</td><td>81</td><td>695.1</td><td>219</td><td>68</td><td>140</td><td>11</td><td>95.0</td><td>2.69</td><td style="">5.09</td><td></td><td>0.12</td><td>0.89</td><td>0.24</td><td></td><td></td><td></td><td>6.34</td><td>10.87</td><td>0.00</td><td>6.34</td><td>0.647</td><td style="background-color:#F3F3F3; font-weight:bold;">0.647</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11298">김호령</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.552</td><td>68</td><td>22</td><td>288.1</td><td>98</td><td>97</td><td>0</td><td>1</td><td>99.0</td><td>3.03</td><td style="">5.75</td><td>-0.22</td><td>-0.13</td><td></td><td></td><td></td><td></td><td></td><td>5.41</td><td>10.25</td><td>0.00</td><td>5.41</td><td>0.552</td><td style="background-color:#F3F3F3; font-weight:bold;">0.552</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12540">김규성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.513</td><td>33</td><td>20</td><td>187.1</td><td>110</td><td>45</td><td>63</td><td>2</td><td>98.2</td><td>5.19</td><td style="">2.53</td><td></td><td>-0.05</td><td>1.22</td><td></td><td></td><td></td><td></td><td>3.69</td><td>5.37</td><td>1.34</td><td>5.03</td><td>0.377</td><td style="background-color:#F3F3F3; font-weight:bold;">0.513</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13113">한준수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.418</td><td>45</td><td>22</td><td>208.2</td><td>166</td><td>151</td><td>15</td><td>0</td><td>100.0</td><td>7.16</td><td style="">-0.20</td><td></td><td>0.54</td><td></td><td>-0.23</td><td>0.71</td><td>1.68</td><td></td><td>1.99</td><td>5.97</td><td>2.11</td><td>4.10</td><td>0.203</td><td style="background-color:#F3F3F3; font-weight:bold;">0.418</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14996">소크라테스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.409</td><td>113</td><td>106</td><td>827.1</td><td>253</td><td>249</td><td>2</td><td>2</td><td>99.2</td><td>2.73</td><td style="">4.01</td><td>-0.07</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>4.01</td><td>4.07</td><td>0.00</td><td>4.01</td><td>0.409</td><td style="background-color:#F3F3F3; font-weight:bold;">0.409</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10459">김태군</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.353</td><td>63</td><td>52</td><td>438.0</td><td>374</td><td>334</td><td>36</td><td>4</td><td>98.9</td><td>7.60</td><td style="">0.19</td><td></td><td>-0.85</td><td></td><td>0.01</td><td>1.16</td><td>-2.37</td><td></td><td>-1.15</td><td>-1.45</td><td>4.61</td><td>3.46</td><td>-0.117</td><td style="background-color:#F3F3F3; font-weight:bold;">0.353</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12541">신범수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.280</td><td>35</td><td>26</td><td>238.0</td><td>201</td><td>191</td><td>10</td><td>0</td><td>100.0</td><td>7.60</td><td style="">0.68</td><td></td><td>0.61</td><td></td><td>0.39</td><td>-1.02</td><td>-0.37</td><td></td><td>0.41</td><td>1.65</td><td>2.33</td><td>2.74</td><td>0.042</td><td style="background-color:#F3F3F3; font-weight:bold;">0.280</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10008">김선빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.260</td><td>114</td><td>111</td><td>895.1</td><td>457</td><td>180</td><td>270</td><td>7</td><td>98.5</td><td>4.52</td><td style="">-3.19</td><td></td><td>1.43</td><td>-0.33</td><td></td><td></td><td></td><td></td><td>-2.10</td><td>-2.54</td><td>4.65</td><td>2.55</td><td>-0.214</td><td style="background-color:#F3F3F3; font-weight:bold;">0.260</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11119">한승택</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.141</td><td>48</td><td>32</td><td>273.1</td><td>243</td><td>223</td><td>18</td><td>2</td><td>99.2</td><td>7.94</td><td style="">-1.00</td><td></td><td>0.21</td><td></td><td>0.00</td><td>-0.83</td><td>0.80</td><td></td><td>-1.06</td><td>-3.12</td><td>2.45</td><td>1.39</td><td>-0.108</td><td style="background-color:#F3F3F3; font-weight:bold;">0.141</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12869">박정우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.130</td><td>13</td><td>1</td><td>28.1</td><td>6</td><td>6</td><td>0</td><td>0</td><td>100.0</td><td>1.91</td><td style="">0.68</td><td>0.61</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>1.34</td><td>9.19</td><td>-0.06</td><td>1.28</td><td>0.137</td><td style="background-color:#F3F3F3; font-weight:bold;">0.130</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11233">이창진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.124</td><td>16</td><td>13</td><td>96.1</td><td>21</td><td>18</td><td>3</td><td>0</td><td>100.0</td><td>1.96</td><td style="">0.94</td><td>0.60</td><td>0.19</td><td></td><td></td><td></td><td></td><td></td><td>1.73</td><td>2.40</td><td>-0.52</td><td>1.21</td><td>0.177</td><td style="background-color:#F3F3F3; font-weight:bold;">0.124</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11407">최정용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.121</td><td>37</td><td>4</td><td>85.1</td><td>48</td><td>13</td><td>34</td><td>1</td><td>97.9</td><td>4.96</td><td style="">0.50</td><td></td><td>0.23</td><td>0.22</td><td></td><td></td><td></td><td></td><td>0.96</td><td>2.46</td><td>0.23</td><td>1.19</td><td>0.097</td><td style="background-color:#F3F3F3; font-weight:bold;">0.121</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11407">최정용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.121</td><td>9</td><td>3</td><td>38.0</td><td>22</td><td>8</td><td>14</td><td>0</td><td>100.0</td><td>5.21</td><td style="">1.12</td><td></td><td>0.09</td><td>-0.44</td><td>0.42</td><td></td><td></td><td></td><td>1.18</td><td>3.05</td><td>0.00</td><td>1.18</td><td>0.121</td><td style="background-color:#F3F3F3; font-weight:bold;">0.121</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14822">김선우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.115</td><td>5</td><td>1</td><td>21.0</td><td>19</td><td>18</td><td>1</td><td>0</td><td>100.0</td><td>8.14</td><td style="">0.00</td><td></td><td>0.05</td><td></td><td></td><td>0.19</td><td>1.03</td><td></td><td>0.96</td><td>27.67</td><td>0.17</td><td>1.13</td><td>0.098</td><td style="background-color:#F3F3F3; font-weight:bold;">0.115</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11099">이우성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.084</td><td>69</td><td>54</td><td>429.2</td><td>106</td><td>102</td><td>4</td><td>0</td><td>100.0</td><td>2.22</td><td style="">2.00</td><td>0.02</td><td>0.83</td><td></td><td></td><td></td><td></td><td></td><td>2.85</td><td>3.26</td><td>-2.03</td><td>0.82</td><td>0.291</td><td style="background-color:#F3F3F3; font-weight:bold;">0.084</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12567">주효상</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.082</td><td>18</td><td>11</td><td>90.0</td><td>95</td><td>88</td><td>7</td><td>0</td><td>100.0</td><td>9.50</td><td style="">0.30</td><td></td><td>0.23</td><td></td><td>0.19</td><td>-0.20</td><td>-0.76</td><td></td><td>-0.02</td><td>-0.12</td><td>0.82</td><td>0.80</td><td>-0.002</td><td style="background-color:#F3F3F3; font-weight:bold;">0.082</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12534">최원준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.074</td><td>7</td><td>5</td><td>43.0</td><td>8</td><td>8</td><td>0</td><td>0</td><td>100.0</td><td>1.67</td><td style="">0.87</td><td>0.00</td><td>0.08</td><td></td><td></td><td></td><td></td><td></td><td>0.95</td><td>2.05</td><td>-0.23</td><td>0.72</td><td>0.097</td><td style="background-color:#F3F3F3; font-weight:bold;">0.074</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14612">홍종표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.071</td><td>13</td><td>1</td><td>25.0</td><td>9</td><td>2</td><td>7</td><td>0</td><td>100.0</td><td>3.24</td><td style="">0.55</td><td></td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>0.62</td><td>2.23</td><td>0.08</td><td>0.70</td><td>0.063</td><td style="background-color:#F3F3F3; font-weight:bold;">0.071</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11233">이창진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.047</td><td>1</td><td>0</td><td>3.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>3.00</td><td style="">0.46</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.46</td><td>0.64</td><td>0.00</td><td>0.46</td><td>0.047</td><td style="background-color:#F3F3F3; font-weight:bold;">0.047</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12540">김규성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.035</td><td>17</td><td>5</td><td>61.2</td><td>65</td><td>62</td><td>3</td><td>0</td><td>100.0</td><td>9.49</td><td style="">0.61</td><td></td><td>0.11</td><td></td><td>0.06</td><td></td><td></td><td></td><td>0.78</td><td>1.14</td><td>-0.44</td><td>0.34</td><td>0.080</td><td style="background-color:#F3F3F3; font-weight:bold;">0.035</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12534">최원준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.021</td><td>21</td><td>13</td><td>125.0</td><td>47</td><td>46</td><td>0</td><td>1</td><td>97.9</td><td>3.31</td><td style="">1.23</td><td>-0.69</td><td>-0.34</td><td></td><td></td><td></td><td></td><td></td><td>0.20</td><td>0.43</td><td>0.00</td><td>0.20</td><td>0.021</td><td style="background-color:#F3F3F3; font-weight:bold;">0.021</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12534">최원준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.019</td><td>3</td><td>3</td><td>22.0</td><td>6</td><td>6</td><td>0</td><td>0</td><td>100.0</td><td>2.45</td><td style="">-0.48</td><td>0.40</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-0.04</td><td>-0.10</td><td>-0.14</td><td>-0.18</td><td>-0.005</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.019</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12917">김석환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.033</td><td>5</td><td>1</td><td>17.1</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>1.04</td><td style="">-0.13</td><td>-0.17</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.28</td><td>-3.33</td><td>-0.05</td><td>-0.33</td><td>-0.028</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.033</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15058">윤도현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.037</td><td>1</td><td>0</td><td>5.0</td><td>2</td><td>1</td><td>0</td><td>1</td><td>50.0</td><td>1.80</td><td style="">0.12</td><td></td><td>-0.48</td><td></td><td></td><td></td><td></td><td></td><td>-0.36</td><td>-51.61</td><td>0.00</td><td>-0.36</td><td>-0.037</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.037</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10894">류지혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.054</td><td>5</td><td>2</td><td>18.0</td><td>13</td><td>13</td><td>0</td><td>0</td><td>100.0</td><td>6.50</td><td style="">-0.35</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.31</td><td>-0.34</td><td>-0.22</td><td>-0.53</td><td>-0.032</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.054</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11233">이창진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.065</td><td>5</td><td>3</td><td>26.1</td><td>8</td><td>8</td><td>0</td><td>0</td><td>100.0</td><td>2.73</td><td style="">-0.73</td><td>0.06</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.63</td><td>-0.88</td><td>0.00</td><td>-0.63</td><td>-0.065</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.065</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14612">홍종표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.065</td><td>8</td><td>0</td><td>9.0</td><td>7</td><td>5</td><td>2</td><td>0</td><td>100.0</td><td>7.00</td><td style="">-0.44</td><td></td><td>0.02</td><td>-0.23</td><td></td><td></td><td></td><td></td><td>-0.65</td><td>-2.36</td><td>0.02</td><td>-0.63</td><td>-0.067</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.065</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12540">김규성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.077</td><td>7</td><td>0</td><td>15.1</td><td>3</td><td>2</td><td>1</td><td>0</td><td>100.0</td><td>1.76</td><td style="">-0.79</td><td></td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-0.76</td><td>-1.10</td><td>0.00</td><td>-0.76</td><td>-0.077</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.077</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14996">소크라테스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.084</td><td>54</td><td>22</td><td>261.0</td><td>67</td><td>63</td><td>1</td><td>3</td><td>95.5</td><td>2.21</td><td style="">1.50</td><td>-0.08</td><td>-0.98</td><td></td><td></td><td></td><td></td><td></td><td>0.44</td><td>0.45</td><td>-1.27</td><td>-0.83</td><td>0.045</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.084</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11099">이우성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.088</td><td>59</td><td>39</td><td>363.2</td><td>76</td><td>75</td><td>0</td><td>1</td><td>98.7</td><td>1.86</td><td style="">0.50</td><td>0.19</td><td>0.15</td><td></td><td></td><td></td><td></td><td></td><td>0.84</td><td>0.96</td><td>-1.70</td><td>-0.86</td><td>0.085</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.088</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12540">김규성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.102</td><td>48</td><td>21</td><td>208.1</td><td>102</td><td>42</td><td>54</td><td>6</td><td>94.1</td><td>4.15</td><td style="">-1.73</td><td></td><td>-0.43</td><td>0.39</td><td></td><td></td><td></td><td></td><td>-1.77</td><td>-2.58</td><td>0.77</td><td>-1.00</td><td>-0.181</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.102</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15056">김도영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.116</td><td>4</td><td>3</td><td>27.0</td><td>11</td><td>3</td><td>6</td><td>2</td><td>81.8</td><td>3.00</td><td style="">-0.77</td><td></td><td>-0.43</td><td>-0.24</td><td></td><td></td><td></td><td></td><td>-1.44</td><td>-2.47</td><td>0.30</td><td>-1.14</td><td>-0.147</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.116</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11261">박찬호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.132</td><td>1</td><td>0</td><td>3.0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0.0</td><td>0.00</td><td style="">-0.81</td><td></td><td>-0.49</td><td></td><td></td><td></td><td></td><td></td><td>-1.30</td><td>-1.44</td><td>0.01</td><td>-1.29</td><td>-0.133</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.132</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14996">소크라테스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.140</td><td>33</td><td>12</td><td>118.2</td><td>35</td><td>33</td><td>0</td><td>2</td><td>94.3</td><td>2.50</td><td style="">-0.57</td><td>0.01</td><td>-0.28</td><td></td><td></td><td></td><td></td><td></td><td>-0.84</td><td>-0.86</td><td>-0.53</td><td>-1.37</td><td>-0.086</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.140</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12917">김석환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.141</td><td>4</td><td>4</td><td>34.1</td><td>32</td><td>31</td><td>1</td><td>0</td><td>100.0</td><td>8.39</td><td style="">-1.13</td><td></td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>-1.07</td><td>-12.80</td><td>-0.32</td><td>-1.39</td><td>-0.109</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.141</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10894">류지혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.147</td><td>7</td><td>7</td><td>52.0</td><td>29</td><td>11</td><td>18</td><td>0</td><td>100.0</td><td>5.02</td><td style="">-1.55</td><td></td><td>0.14</td><td>-0.28</td><td></td><td></td><td></td><td></td><td>-1.69</td><td>-1.85</td><td>0.25</td><td>-1.44</td><td>-0.173</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.147</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14181">오선우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.156</td><td>29</td><td>4</td><td>82.2</td><td>93</td><td>89</td><td>3</td><td>1</td><td>98.9</td><td>10.02</td><td style="">-1.22</td><td></td><td>0.15</td><td></td><td>0.06</td><td></td><td></td><td></td><td>-1.00</td><td>-4.38</td><td>-0.52</td><td>-1.52</td><td>-0.102</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.156</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11306">황대인</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.157</td><td>54</td><td>50</td><td>389.1</td><td>391</td><td>355</td><td>33</td><td>3</td><td>99.2</td><td>8.97</td><td style="">2.69</td><td></td><td>-0.28</td><td></td><td>-0.33</td><td></td><td></td><td></td><td>2.08</td><td>4.99</td><td>-3.62</td><td>-1.54</td><td>0.212</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.157</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14124">변우혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.198</td><td>20</td><td>12</td><td>104.2</td><td>28</td><td>6</td><td>18</td><td>4</td><td>85.7</td><td>2.06</td><td style="">-1.36</td><td></td><td>-0.75</td><td>0.15</td><td>0.02</td><td></td><td></td><td></td><td>-1.94</td><td>-3.36</td><td>0.00</td><td>-1.94</td><td>-0.198</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.198</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10659">고종욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.259</td><td>45</td><td>35</td><td>248.1</td><td>59</td><td>54</td><td>3</td><td>2</td><td>96.6</td><td>2.07</td><td style="">-0.63</td><td>-0.52</td><td>-0.05</td><td></td><td></td><td></td><td></td><td></td><td>-1.20</td><td>-1.51</td><td>-1.34</td><td>-2.54</td><td>-0.122</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.259</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11233">이창진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.355</td><td>69</td><td>40</td><td>392.0</td><td>95</td><td>92</td><td>2</td><td>1</td><td>98.9</td><td>2.16</td><td style="">-1.43</td><td>-0.39</td><td>0.20</td><td></td><td></td><td></td><td></td><td></td><td>-1.62</td><td>-2.24</td><td>-1.86</td><td>-3.48</td><td>-0.165</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.355</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10894">류지혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.418</td><td>55</td><td>48</td><td>402.2</td><td>114</td><td>38</td><td>72</td><td>4</td><td>96.5</td><td>2.46</td><td style="">-2.93</td><td></td><td>-0.06</td><td>-0.93</td><td>-0.18</td><td></td><td></td><td></td><td>-4.10</td><td>-4.47</td><td>0.00</td><td>-4.10</td><td>-0.418</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.418</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10344">최형우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.442</td><td>15</td><td>14</td><td>107.0</td><td>19</td><td>18</td><td>0</td><td>1</td><td>94.7</td><td>1.51</td><td style="">-3.20</td><td>-0.26</td><td>-0.31</td><td></td><td></td><td></td><td></td><td></td><td>-3.76</td><td>-4.47</td><td>-0.57</td><td>-4.33</td><td>-0.383</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.442</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11162">나성범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.531</td><td>50</td><td>49</td><td>410.2</td><td>93</td><td>88</td><td>4</td><td>1</td><td>98.9</td><td>2.02</td><td style="">-4.09</td><td>0.27</td><td>0.79</td><td></td><td></td><td></td><td></td><td></td><td>-3.03</td><td>-7.53</td><td>-2.17</td><td>-5.20</td><td>-0.309</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.531</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14124">변우혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.562</td><td>55</td><td>44</td><td>358.0</td><td>340</td><td>311</td><td>24</td><td>5</td><td>98.5</td><td>8.42</td><td style="">-1.88</td><td></td><td>-0.34</td><td></td><td>-0.15</td><td></td><td></td><td></td><td>-2.37</td><td>-4.12</td><td>-3.14</td><td>-5.51</td><td>-0.242</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.562</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12534">최원준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.564</td><td>39</td><td>35</td><td>321.0</td><td>311</td><td>289</td><td>15</td><td>7</td><td>97.7</td><td>8.52</td><td style="">-1.17</td><td></td><td>-0.90</td><td></td><td></td><td></td><td></td><td></td><td>-2.07</td><td>-4.44</td><td>-3.46</td><td>-5.53</td><td>-0.211</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.564</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14608">정해영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>52</td><td>0</td><td>49.1</td><td>11</td><td>3</td><td>7</td><td>1</td><td>90.9</td><td>1.82</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11407">최정용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>4.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>6.75</td><td style="">0.70</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.71</td><td>1.83</td><td></td><td></td><td>0.073</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13122">윤중현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>30</td><td>0</td><td>28.0</td><td>5</td><td>2</td><td>3</td><td>0</td><td>100.0</td><td>1.61</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15063">황동하</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>12</td><td>6</td><td>31.1</td><td>8</td><td>3</td><td>5</td><td>0</td><td>100.0</td><td>2.30</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11070">박준표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>33</td><td>0</td><td>28.0</td><td>5</td><td>0</td><td>5</td><td>0</td><td>100.0</td><td>1.61</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11407">최정용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.32</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.33</td><td>0.84</td><td></td><td></td><td>0.033</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12869">박정우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>2.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>4.50</td><td style="">0.65</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.65</td><td>4.45</td><td></td><td></td><td>0.066</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14176">김기훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>27</td><td>0</td><td>31.1</td><td>2</td><td>0</td><td>2</td><td>0</td><td>100.0</td><td>0.57</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10008">김선빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.01</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14612">홍종표</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#ed1c24;color:#fff;">23</span> <span><img src="/data/team/ci/2023/2002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>3</td><td>0</td><td>5.0</td><td>3</td><td>1</td><td>2</td><td>0</td><td>100.0</td><td>5.40</td><td style="">0.18</td><td></td><td>0.01</td><td>0.33</td><td></td><td></td><td></td><td></td><td>0.52</td><td>1.88</td><td></td><td></td><td>0.053</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>
""")

In [65]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10235">장성우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.178</td><td>116</td><td>104</td><td>886.0</td><td>768</td><td>719</td><td>43</td><td>6</td><td>99.2</td><td>7.74</td><td style="">0.72</td><td></td><td>-0.19</td><td></td><td>0.01</td><td>-0.06</td><td>1.28</td><td></td><td>1.37</td><td>1.51</td><td>10.18</td><td>11.55</td><td>0.140</td><td style="background-color:#F3F3F3; font-weight:bold;">1.178</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10320">김상수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.613</td><td>129</td><td>123</td><td>1020.1</td><td>441</td><td>176</td><td>259</td><td>6</td><td>98.6</td><td>3.84</td><td style="">-3.58</td><td></td><td>0.92</td><td>-1.50</td><td></td><td></td><td></td><td></td><td>-4.17</td><td>-4.65</td><td>10.18</td><td>6.01</td><td>-0.425</td><td style="background-color:#F3F3F3; font-weight:bold;">0.613</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10407">황재균</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.366</td><td>107</td><td>103</td><td>895.0</td><td>255</td><td>82</td><td>162</td><td>11</td><td>95.7</td><td>2.45</td><td style="">3.16</td><td></td><td>1.08</td><td>-0.52</td><td>-0.13</td><td></td><td></td><td></td><td>3.59</td><td>4.74</td><td>0.00</td><td>3.59</td><td>0.366</td><td style="background-color:#F3F3F3; font-weight:bold;">0.366</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14603">강현우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.366</td><td>46</td><td>24</td><td>235.1</td><td>187</td><td>175</td><td>11</td><td>1</td><td>99.5</td><td>7.11</td><td style="">0.25</td><td></td><td>0.11</td><td></td><td>0.19</td><td>-0.41</td><td>1.38</td><td></td><td>1.11</td><td>3.03</td><td>2.47</td><td>3.59</td><td>0.114</td><td style="background-color:#F3F3F3; font-weight:bold;">0.366</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11342">송민섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.344</td><td>42</td><td>1</td><td>83.0</td><td>27</td><td>27</td><td>0</td><td>0</td><td>100.0</td><td>2.93</td><td style="">2.77</td><td>0.56</td><td>0.16</td><td></td><td></td><td></td><td></td><td></td><td>3.49</td><td>7.29</td><td>-0.12</td><td>3.37</td><td>0.356</td><td style="background-color:#F3F3F3; font-weight:bold;">0.344</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15519">정준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.283</td><td>14</td><td>2</td><td>31.0</td><td>12</td><td>11</td><td>1</td><td>0</td><td>100.0</td><td>3.48</td><td style="">1.95</td><td>0.85</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>2.86</td><td>12.10</td><td>-0.08</td><td>2.78</td><td>0.291</td><td style="background-color:#F3F3F3; font-weight:bold;">0.283</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13151">이호연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.262</td><td>64</td><td>52</td><td>370.1</td><td>213</td><td>80</td><td>125</td><td>8</td><td>96.2</td><td>4.98</td><td style="">-0.13</td><td></td><td>-0.48</td><td>1.48</td><td></td><td></td><td></td><td></td><td>0.87</td><td>1.47</td><td>1.70</td><td>2.57</td><td>0.089</td><td style="background-color:#F3F3F3; font-weight:bold;">0.262</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11214">장준원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.216</td><td>26</td><td>12</td><td>109.1</td><td>22</td><td>5</td><td>17</td><td>0</td><td>100.0</td><td>1.81</td><td style="">1.45</td><td></td><td>0.25</td><td>0.33</td><td>0.09</td><td></td><td></td><td></td><td>2.12</td><td>4.43</td><td>0.00</td><td>2.12</td><td>0.216</td><td style="background-color:#F3F3F3; font-weight:bold;">0.216</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11339">김민혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.204</td><td>46</td><td>42</td><td>288.0</td><td>66</td><td>64</td><td>0</td><td>2</td><td>97.0</td><td>2.00</td><td style="">4.11</td><td>0.01</td><td>-0.43</td><td></td><td></td><td></td><td></td><td></td><td>3.69</td><td>4.70</td><td>-1.69</td><td>2.00</td><td>0.376</td><td style="background-color:#F3F3F3; font-weight:bold;">0.204</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15144">알포드</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.180</td><td>112</td><td>109</td><td>858.0</td><td>217</td><td>209</td><td>5</td><td>3</td><td>98.6</td><td>2.24</td><td style="">6.41</td><td>-0.16</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>6.29</td><td>6.81</td><td>-4.52</td><td>1.77</td><td>0.641</td><td style="background-color:#F3F3F3; font-weight:bold;">0.180</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10840">신본기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.169</td><td>19</td><td>6</td><td>70.1</td><td>32</td><td>11</td><td>19</td><td>2</td><td>93.8</td><td>3.84</td><td style="">0.76</td><td></td><td>0.17</td><td>0.21</td><td></td><td></td><td></td><td></td><td>1.13</td><td>4.08</td><td>0.52</td><td>1.65</td><td>0.116</td><td style="background-color:#F3F3F3; font-weight:bold;">0.169</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11339">김민혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.160</td><td>30</td><td>28</td><td>204.0</td><td>59</td><td>58</td><td>0</td><td>1</td><td>98.3</td><td>2.56</td><td style="">2.04</td><td>-0.24</td><td>-0.24</td><td></td><td></td><td></td><td></td><td></td><td>1.57</td><td>2.00</td><td>0.00</td><td>1.57</td><td>0.160</td><td style="background-color:#F3F3F3; font-weight:bold;">0.160</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15519">정준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.154</td><td>11</td><td>3</td><td>44.0</td><td>11</td><td>10</td><td>1</td><td>0</td><td>100.0</td><td>2.25</td><td style="">1.05</td><td>0.56</td><td>0.08</td><td></td><td></td><td></td><td></td><td></td><td>1.70</td><td>7.20</td><td>-0.19</td><td>1.51</td><td>0.173</td><td style="background-color:#F3F3F3; font-weight:bold;">0.154</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11214">장준원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.146</td><td>43</td><td>14</td><td>167.1</td><td>86</td><td>32</td><td>52</td><td>2</td><td>97.7</td><td>4.52</td><td style="">-1.25</td><td></td><td>0.39</td><td>1.13</td><td></td><td></td><td></td><td></td><td>0.27</td><td>0.57</td><td>1.16</td><td>1.43</td><td>0.028</td><td style="background-color:#F3F3F3; font-weight:bold;">0.146</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12941">홍현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.142</td><td>8</td><td>4</td><td>32.1</td><td>9</td><td>9</td><td>0</td><td>0</td><td>100.0</td><td>2.51</td><td style="">1.61</td><td>-0.17</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>1.50</td><td>4.92</td><td>-0.11</td><td>1.39</td><td>0.153</td><td style="background-color:#F3F3F3; font-weight:bold;">0.142</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14191">강민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.136</td><td>10</td><td>7</td><td>57.0</td><td>20</td><td>4</td><td>14</td><td>2</td><td>90.0</td><td>2.84</td><td style="">1.97</td><td></td><td>-0.36</td><td>-0.28</td><td></td><td></td><td></td><td></td><td>1.33</td><td>16.00</td><td>0.00</td><td>1.33</td><td>0.136</td><td style="background-color:#F3F3F3; font-weight:bold;">0.136</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11147">이상호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.128</td><td>31</td><td>6</td><td>93.0</td><td>39</td><td>16</td><td>22</td><td>1</td><td>97.4</td><td>3.68</td><td style="">0.71</td><td></td><td>0.25</td><td></td><td></td><td></td><td></td><td></td><td>0.96</td><td>2.19</td><td>0.30</td><td>1.26</td><td>0.098</td><td style="background-color:#F3F3F3; font-weight:bold;">0.128</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10840">신본기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.108</td><td>17</td><td>6</td><td>71.2</td><td>48</td><td>20</td><td>28</td><td>0</td><td>100.0</td><td>6.03</td><td style="">1.04</td><td></td><td>0.19</td><td>-0.41</td><td></td><td></td><td></td><td></td><td>0.82</td><td>2.95</td><td>0.24</td><td>1.06</td><td>0.083</td><td style="background-color:#F3F3F3; font-weight:bold;">0.108</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15097">김병준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.103</td><td>1</td><td>1</td><td>5.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>5.40</td><td style="">0.66</td><td>0.34</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>1.01</td><td>48.41</td><td>0.00</td><td>1.01</td><td>0.103</td><td style="background-color:#F3F3F3; font-weight:bold;">0.103</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13151">이호연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.092</td><td>10</td><td>2</td><td>32.2</td><td>35</td><td>33</td><td>2</td><td>0</td><td>100.0</td><td>9.64</td><td style="">1.14</td><td></td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>1.20</td><td>2.03</td><td>-0.30</td><td>0.90</td><td>0.122</td><td style="background-color:#F3F3F3; font-weight:bold;">0.092</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11397">오윤석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.089</td><td>7</td><td>0</td><td>11.2</td><td>3</td><td>0</td><td>3</td><td>0</td><td>100.0</td><td>2.31</td><td style="">0.84</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.87</td><td>1.53</td><td>0.00</td><td>0.87</td><td>0.089</td><td style="background-color:#F3F3F3; font-weight:bold;">0.089</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10469">박경수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.087</td><td>101</td><td>52</td><td>503.0</td><td>301</td><td>118</td><td>179</td><td>4</td><td>98.7</td><td>5.31</td><td style="">-2.08</td><td></td><td>0.86</td><td>0.03</td><td></td><td></td><td></td><td></td><td>-1.19</td><td>-1.60</td><td>2.04</td><td>0.85</td><td>-0.121</td><td style="background-color:#F3F3F3; font-weight:bold;">0.087</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11339">김민혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.082</td><td>46</td><td>28</td><td>275.2</td><td>70</td><td>68</td><td>1</td><td>1</td><td>98.6</td><td>2.25</td><td style="">3.03</td><td>-0.81</td><td>-0.01</td><td></td><td></td><td></td><td></td><td></td><td>2.22</td><td>2.83</td><td>-1.41</td><td>0.81</td><td>0.226</td><td style="background-color:#F3F3F3; font-weight:bold;">0.082</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11147">이상호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.082</td><td>11</td><td>4</td><td>46.1</td><td>16</td><td>6</td><td>10</td><td>0</td><td>100.0</td><td>3.11</td><td style="">0.92</td><td></td><td>0.11</td><td>-0.23</td><td></td><td></td><td></td><td></td><td>0.80</td><td>1.83</td><td>0.00</td><td>0.80</td><td>0.082</td><td style="background-color:#F3F3F3; font-weight:bold;">0.082</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11330">김병희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.077</td><td>3</td><td>1</td><td>14.0</td><td>3</td><td>0</td><td>3</td><td>0</td><td>100.0</td><td>1.93</td><td style="">0.73</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.76</td><td>21.85</td><td>0.00</td><td>0.76</td><td>0.077</td><td style="background-color:#F3F3F3; font-weight:bold;">0.077</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10407">황재균</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.076</td><td>2</td><td>0</td><td>5.0</td><td>4</td><td>1</td><td>3</td><td>0</td><td>100.0</td><td>7.20</td><td style="">0.36</td><td></td><td>0.01</td><td>0.31</td><td></td><td></td><td></td><td></td><td>0.68</td><td>0.90</td><td>0.06</td><td>0.74</td><td>0.069</td><td style="background-color:#F3F3F3; font-weight:bold;">0.076</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15520">손민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.072</td><td>6</td><td>3</td><td>27.0</td><td>18</td><td>6</td><td>12</td><td>0</td><td>100.0</td><td>6.00</td><td style="">0.54</td><td></td><td>0.07</td><td>0.00</td><td></td><td></td><td></td><td></td><td>0.62</td><td>9.85</td><td>0.09</td><td>0.71</td><td>0.063</td><td style="background-color:#F3F3F3; font-weight:bold;">0.072</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15520">손민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.059</td><td>5</td><td>0</td><td>7.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>5.14</td><td style="">0.53</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.54</td><td>8.69</td><td>0.04</td><td>0.58</td><td>0.055</td><td style="background-color:#F3F3F3; font-weight:bold;">0.059</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12526">이시원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.049</td><td>15</td><td>5</td><td>59.0</td><td>21</td><td>21</td><td>0</td><td>0</td><td>100.0</td><td>3.20</td><td style="">1.09</td><td>-0.53</td><td>0.11</td><td></td><td></td><td></td><td></td><td></td><td>0.67</td><td>3.32</td><td>-0.19</td><td>0.48</td><td>0.068</td><td style="background-color:#F3F3F3; font-weight:bold;">0.049</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11342">송민섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.044</td><td>17</td><td>0</td><td>37.2</td><td>14</td><td>14</td><td>0</td><td>0</td><td>100.0</td><td>3.35</td><td style="">0.48</td><td>-0.10</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>0.43</td><td>0.90</td><td>0.00</td><td>0.43</td><td>0.044</td><td style="background-color:#F3F3F3; font-weight:bold;">0.044</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12943">조용호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.042</td><td>11</td><td>2</td><td>31.0</td><td>6</td><td>5</td><td>1</td><td>0</td><td>100.0</td><td>1.74</td><td style="">-0.72</td><td>1.21</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>0.54</td><td>1.23</td><td>-0.13</td><td>0.41</td><td>0.055</td><td style="background-color:#F3F3F3; font-weight:bold;">0.042</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12943">조용호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.041</td><td>1</td><td>0</td><td>2.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>4.50</td><td style="">0.48</td><td>-0.07</td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.41</td><td>0.93</td><td>0.00</td><td>0.41</td><td>0.041</td><td style="background-color:#F3F3F3; font-weight:bold;">0.041</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14191">강민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.030</td><td>1</td><td>0</td><td>3.0</td><td>4</td><td>3</td><td>1</td><td>0</td><td>100.0</td><td>12.00</td><td style="">-0.15</td><td></td><td>0.01</td><td></td><td>0.46</td><td></td><td></td><td></td><td>0.32</td><td>3.78</td><td>-0.02</td><td>0.30</td><td>0.032</td><td style="background-color:#F3F3F3; font-weight:bold;">0.030</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13006">안치영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.027</td><td>4</td><td>2</td><td>15.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">0.25</td><td>0.00</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.26</td><td>0.50</td><td>0.00</td><td>0.26</td><td>0.027</td><td style="background-color:#F3F3F3; font-weight:bold;">0.027</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13006">안치영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.025</td><td>10</td><td>0</td><td>14.2</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>2.45</td><td style="">0.50</td><td>-0.23</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.29</td><td>0.55</td><td>-0.05</td><td>0.24</td><td>0.030</td><td style="background-color:#F3F3F3; font-weight:bold;">0.025</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11397">오윤석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.018</td><td>52</td><td>34</td><td>308.2</td><td>308</td><td>276</td><td>32</td><td>0</td><td>100.0</td><td>8.98</td><td style="">2.14</td><td></td><td>0.56</td><td></td><td>0.06</td><td></td><td></td><td></td><td>2.76</td><td>4.85</td><td>-2.58</td><td>0.18</td><td>0.281</td><td style="background-color:#F3F3F3; font-weight:bold;">0.018</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13151">이호연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.012</td><td>12</td><td>6</td><td>60.0</td><td>16</td><td>3</td><td>12</td><td>1</td><td>93.8</td><td>2.25</td><td style="">-0.22</td><td></td><td>0.14</td><td>0.10</td><td>0.10</td><td></td><td></td><td></td><td>0.11</td><td>0.19</td><td>0.00</td><td>0.11</td><td>0.012</td><td style="background-color:#F3F3F3; font-weight:bold;">0.012</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11212">배정대</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.011</td><td>97</td><td>93</td><td>800.0</td><td>253</td><td>246</td><td>6</td><td>1</td><td>99.6</td><td>2.84</td><td style="">-2.66</td><td>1.75</td><td>1.02</td><td></td><td></td><td></td><td></td><td></td><td>0.11</td><td>0.16</td><td>0.00</td><td>0.11</td><td>0.011</td><td style="background-color:#F3F3F3; font-weight:bold;">0.011</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11330">김병희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.014</td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.15</td><td></td><td>0.01</td><td>0.00</td><td></td><td></td><td></td><td></td><td>-0.14</td><td>-4.17</td><td>0.01</td><td>-0.13</td><td>-0.015</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.014</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11214">장준원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.018</td><td>6</td><td>0</td><td>12.0</td><td>5</td><td>2</td><td>3</td><td>0</td><td>100.0</td><td>3.75</td><td style="">-0.24</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.21</td><td>-0.44</td><td>0.03</td><td>-0.18</td><td>-0.021</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.018</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13227">문상인</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.018</td><td>1</td><td>0</td><td>3.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>6.00</td><td style="">0.00</td><td></td><td>0.01</td><td></td><td></td><td></td><td>-0.30</td><td></td><td>-0.20</td><td>-29.50</td><td>0.02</td><td>-0.18</td><td>-0.021</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.018</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12526">이시원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.024</td><td>7</td><td>0</td><td>17.1</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>2.08</td><td style="">-0.32</td><td>0.11</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.19</td><td>-0.93</td><td>-0.05</td><td>-0.24</td><td>-0.019</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.024</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12526">이시원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.027</td><td>3</td><td>1</td><td>13.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>2.08</td><td style="">-0.09</td><td>-0.19</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.27</td><td>-1.32</td><td>0.00</td><td>-0.27</td><td>-0.027</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.027</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10470">박병호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.030</td><td>92</td><td>89</td><td>730.1</td><td>735</td><td>669</td><td>61</td><td>5</td><td>99.3</td><td>9.00</td><td style="">6.20</td><td></td><td>1.32</td><td></td><td>-0.16</td><td></td><td></td><td></td><td>7.37</td><td>8.03</td><td>-7.66</td><td>-0.29</td><td>0.751</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.030</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11333">문상철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.046</td><td>2</td><td>1</td><td>7.2</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>4.70</td><td style="">-0.32</td><td>-0.12</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.42</td><td>-0.54</td><td>-0.03</td><td>-0.45</td><td>-0.043</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.046</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15523">류현인</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.051</td><td>8</td><td>1</td><td>22.0</td><td>12</td><td>3</td><td>9</td><td>0</td><td>100.0</td><td>4.91</td><td style="">-0.65</td><td></td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>-0.59</td><td>-5.00</td><td>0.09</td><td>-0.50</td><td>-0.060</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.051</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12941">홍현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.060</td><td>10</td><td>0</td><td>16.1</td><td>6</td><td>6</td><td>0</td><td>0</td><td>100.0</td><td>3.31</td><td style="">-0.84</td><td>0.26</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.55</td><td>-1.79</td><td>-0.04</td><td>-0.59</td><td>-0.056</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.060</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11147">이상호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.062</td><td>2</td><td>0</td><td>3.0</td><td>3</td><td>1</td><td>2</td><td>0</td><td>100.0</td><td>9.00</td><td style="">-0.65</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.65</td><td>-1.48</td><td>0.04</td><td>-0.61</td><td>-0.066</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.062</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14720">문상준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.066</td><td>1</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.67</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.67</td><td>-48.04</td><td>0.02</td><td>-0.65</td><td>-0.068</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.066</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14110">박민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.072</td><td>1</td><td>1</td><td>9.0</td><td>4</td><td>1</td><td>2</td><td>1</td><td>75.0</td><td>3.00</td><td style="">-0.90</td><td></td><td>0.02</td><td>0.09</td><td></td><td></td><td></td><td></td><td>-0.79</td><td>-28.41</td><td>0.08</td><td>-0.71</td><td>-0.080</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.072</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11397">오윤석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.079</td><td>28</td><td>23</td><td>176.0</td><td>95</td><td>33</td><td>60</td><td>2</td><td>97.9</td><td>4.76</td><td style="">-0.96</td><td></td><td>0.47</td><td>-1.10</td><td></td><td></td><td></td><td></td><td>-1.59</td><td>-2.79</td><td>0.81</td><td>-0.78</td><td>-0.162</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.079</td></tr><tr><td style="text-align:center;">52</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15520">손민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.080</td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0.0</td><td>0.00</td><td style="">-0.79</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.79</td><td>-12.59</td><td>0.00</td><td>-0.79</td><td>-0.080</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.080</td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10835">김준태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.082</td><td>35</td><td>16</td><td>162.2</td><td>123</td><td>108</td><td>11</td><td>4</td><td>96.7</td><td>6.58</td><td style="">0.26</td><td></td><td>-1.56</td><td></td><td>-0.01</td><td>0.48</td><td>-2.36</td><td></td><td>-2.48</td><td>-5.18</td><td>1.68</td><td>-0.80</td><td>-0.253</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.082</td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13168">강백호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.084</td><td>6</td><td>6</td><td>51.0</td><td>49</td><td>43</td><td>6</td><td>0</td><td>100.0</td><td>8.65</td><td style="">-0.42</td><td></td><td>0.09</td><td></td><td></td><td></td><td></td><td></td><td>-0.32</td><td>-0.66</td><td>-0.50</td><td>-0.82</td><td>-0.033</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.084</td></tr><tr><td style="text-align:center;">55</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11333">문상철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.105</td><td>7</td><td>3</td><td>39.0</td><td>12</td><td>11</td><td>0</td><td>1</td><td>91.7</td><td>2.54</td><td style="">-0.62</td><td>0.20</td><td>-0.43</td><td></td><td></td><td></td><td></td><td></td><td>-0.85</td><td>-1.10</td><td>-0.18</td><td>-1.03</td><td>-0.087</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.105</td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14720">문상준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.124</td><td>2</td><td>1</td><td>8.0</td><td>2</td><td>1</td><td>0</td><td>1</td><td>50.0</td><td>1.13</td><td style="">-0.78</td><td></td><td>-0.47</td><td></td><td></td><td></td><td></td><td></td><td>-1.25</td><td>-90.31</td><td>0.04</td><td>-1.21</td><td>-0.128</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.124</td></tr><tr><td style="text-align:center;">57</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14603">강현우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.135</td><td>1</td><td>0</td><td>1.0</td><td>2</td><td>1</td><td>0</td><td>1</td><td>50.0</td><td>9.00</td><td style="">-0.81</td><td></td><td>-0.49</td><td></td><td></td><td></td><td></td><td></td><td>-1.30</td><td>-3.53</td><td>-0.02</td><td>-1.32</td><td>-0.132</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.135</td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15523">류현인</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.141</td><td>6</td><td>4</td><td>35.0</td><td>9</td><td>3</td><td>5</td><td>1</td><td>88.9</td><td>2.06</td><td style="">-0.98</td><td></td><td>0.08</td><td>0.28</td><td>-0.76</td><td></td><td></td><td></td><td>-1.38</td><td>-11.71</td><td>0.00</td><td>-1.38</td><td>-0.141</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.141</td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12941">홍현빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.144</td><td>27</td><td>16</td><td>151.2</td><td>48</td><td>47</td><td>1</td><td>0</td><td>100.0</td><td>2.85</td><td style="">-1.50</td><td>-0.10</td><td>0.19</td><td></td><td></td><td></td><td></td><td></td><td>-1.41</td><td>-4.62</td><td>0.00</td><td>-1.41</td><td>-0.144</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.144</td></tr><tr><td style="text-align:center;">60</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10840">신본기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.149</td><td>13</td><td>7</td><td>56.2</td><td>17</td><td>11</td><td>5</td><td>1</td><td>94.1</td><td>2.54</td><td style="">-1.42</td><td></td><td>-0.36</td><td>0.33</td><td></td><td></td><td></td><td></td><td>-1.46</td><td>-5.25</td><td>0.00</td><td>-1.46</td><td>-0.149</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.149</td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13168">강백호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.179</td><td>23</td><td>20</td><td>159.0</td><td>35</td><td>33</td><td>1</td><td>1</td><td>97.1</td><td>1.92</td><td style="">-0.21</td><td>-0.93</td><td>0.31</td><td></td><td></td><td></td><td></td><td></td><td>-0.84</td><td>-1.70</td><td>-0.92</td><td>-1.76</td><td>-0.086</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.179</td></tr><tr><td style="text-align:center;">62</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11147">이상호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.207</td><td>17</td><td>0</td><td>29.1</td><td>24</td><td>22</td><td>2</td><td>0</td><td>100.0</td><td>7.36</td><td style="">-1.96</td><td></td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>-1.91</td><td>-4.36</td><td>-0.12</td><td>-2.03</td><td>-0.194</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.207</td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15144">알포드</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.242</td><td>1</td><td>1</td><td>5.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-1.31</td><td>-1.07</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-2.37</td><td>-2.57</td><td>0.00</td><td>-2.37</td><td>-0.242</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.242</td></tr><tr><td style="text-align:center;">64</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15519">정준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.246</td><td>11</td><td>2</td><td>53.2</td><td>21</td><td>20</td><td>0</td><td>1</td><td>95.2</td><td>3.35</td><td style="">-1.44</td><td>-0.55</td><td>-0.43</td><td></td><td></td><td></td><td></td><td></td><td>-2.41</td><td>-10.22</td><td>0.00</td><td>-2.41</td><td>-0.246</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.246</td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13006">안치영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.276</td><td>57</td><td>31</td><td>300.0</td><td>57</td><td>53</td><td>2</td><td>2</td><td>96.5</td><td>1.65</td><td style="">-1.57</td><td>0.44</td><td>-0.41</td><td></td><td></td><td></td><td></td><td></td><td>-1.54</td><td>-2.91</td><td>-1.17</td><td>-2.71</td><td>-0.157</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.276</td></tr><tr><td style="text-align:center;">66</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12943">조용호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.381</td><td>49</td><td>37</td><td>312.0</td><td>59</td><td>56</td><td>2</td><td>1</td><td>98.3</td><td>1.67</td><td style="">-2.27</td><td>-0.04</td><td>0.11</td><td></td><td></td><td></td><td></td><td></td><td>-2.20</td><td>-5.03</td><td>-1.54</td><td>-3.74</td><td>-0.224</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.381</td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11333">문상철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.404</td><td>27</td><td>13</td><td>131.0</td><td>130</td><td>120</td><td>9</td><td>1</td><td>99.2</td><td>8.86</td><td style="">-3.04</td><td></td><td>0.24</td><td></td><td>0.06</td><td></td><td></td><td></td><td>-2.74</td><td>-3.52</td><td>-1.22</td><td>-3.96</td><td>-0.280</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.404</td></tr><tr><td style="text-align:center;">68</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10304">하준호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>12</td><td>0</td><td>13.0</td><td>2</td><td>0</td><td>2</td><td>0</td><td>100.0</td><td>1.38</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">68</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14110">박민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>2.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>4.50</td><td style="">0.22</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.22</td><td>8.10</td><td></td><td></td><td>0.023</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">68</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13167">김민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>16</td><td>4</td><td>29.0</td><td>6</td><td>3</td><td>3</td><td>0</td><td>100.0</td><td>1.86</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">68</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11147">이상호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">68</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11333">문상철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">68</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15523">류현인</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>3.0</td><td>4</td><td>2</td><td>2</td><td>0</td><td>100.0</td><td>12.00</td><td style="">0.36</td><td></td><td>0.01</td><td>-0.25</td><td></td><td></td><td></td><td></td><td>0.12</td><td>1.03</td><td></td><td></td><td>0.012</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">68</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14869">김영현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>31</td><td>0</td><td>33.0</td><td>9</td><td>1</td><td>6</td><td>2</td><td>77.8</td><td>1.91</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">68</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11342">송민섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>5</td><td>0</td><td>4.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>2.25</td><td style="">0.03</td><td>0.11</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.15</td><td>0.31</td><td></td><td></td><td>0.015</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">68</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13130">이채호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>21</td><td>0</td><td>24.2</td><td>4</td><td>3</td><td>0</td><td>1</td><td>75.0</td><td>1.09</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">68</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14109">이상동</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>36</td><td>0</td><td>40.2</td><td>6</td><td>2</td><td>4</td><td>0</td><td>100.0</td><td>1.33</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">68</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11489">김재윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>59</td><td>0</td><td>65.2</td><td>13</td><td>5</td><td>7</td><td>1</td><td>92.3</td><td>1.64</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">68</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14111">이선우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>22</td><td>4</td><td>37.1</td><td>6</td><td>1</td><td>5</td><td>0</td><td>100.0</td><td>1.45</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">68</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15089">박영현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#000000;color:#fff;">23</span> <span><img src="/data/team/ci/2023/12001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>67</td><td>0</td><td>75.1</td><td>12</td><td>5</td><td>7</td><td>0</td><td>100.0</td><td>1.43</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>
""")

In [66]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15034">이재현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.301</td><td>140</td><td>135</td><td>1156.1</td><td>583</td><td>222</td><td>341</td><td>20</td><td>96.6</td><td>4.38</td><td style="">1.82</td><td></td><td>0.74</td><td>-0.44</td><td></td><td></td><td></td><td></td><td>2.11</td><td>2.13</td><td>10.64</td><td>12.75</td><td>0.216</td><td style="background-color:#F3F3F3; font-weight:bold;">1.301</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10232">강민호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.646</td><td>101</td><td>94</td><td>786.2</td><td>631</td><td>579</td><td>49</td><td>3</td><td>99.5</td><td>7.18</td><td style="">-0.60</td><td></td><td>0.55</td><td></td><td>-0.56</td><td>-1.84</td><td>-0.71</td><td></td><td>-2.95</td><td>-3.40</td><td>9.29</td><td>6.34</td><td>-0.301</td><td style="background-color:#F3F3F3; font-weight:bold;">0.646</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10459">김태군</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.408</td><td>24</td><td>20</td><td>181.0</td><td>139</td><td>128</td><td>11</td><td>0</td><td>100.0</td><td>6.91</td><td style="">-0.28</td><td></td><td>0.47</td><td></td><td>-0.01</td><td>0.44</td><td>1.95</td><td></td><td>1.98</td><td>2.51</td><td>2.02</td><td>4.00</td><td>0.202</td><td style="background-color:#F3F3F3; font-weight:bold;">0.408</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11344">김재성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.407</td><td>40</td><td>18</td><td>191.1</td><td>144</td><td>134</td><td>10</td><td>0</td><td>100.0</td><td>6.77</td><td style="">0.24</td><td></td><td>0.49</td><td></td><td></td><td>1.13</td><td>0.16</td><td></td><td>1.98</td><td>5.00</td><td>2.02</td><td>3.99</td><td>0.202</td><td style="background-color:#F3F3F3; font-weight:bold;">0.407</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14863">김동진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.393</td><td>37</td><td>23</td><td>236.0</td><td>146</td><td>55</td><td>87</td><td>4</td><td>97.3</td><td>5.42</td><td style="">2.52</td><td></td><td>-0.35</td><td>0.64</td><td></td><td></td><td></td><td></td><td>2.81</td><td>9.18</td><td>1.05</td><td>3.86</td><td>0.286</td><td style="background-color:#F3F3F3; font-weight:bold;">0.393</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12562">이성규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.261</td><td>33</td><td>25</td><td>218.2</td><td>70</td><td>68</td><td>1</td><td>1</td><td>98.6</td><td>2.84</td><td style="">2.81</td><td>-0.04</td><td>-0.22</td><td></td><td></td><td></td><td></td><td></td><td>2.56</td><td>3.38</td><td>0.00</td><td>2.56</td><td>0.261</td><td style="background-color:#F3F3F3; font-weight:bold;">0.261</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11255">강한울</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.242</td><td>58</td><td>48</td><td>415.2</td><td>117</td><td>34</td><td>77</td><td>6</td><td>94.9</td><td>2.40</td><td style="">2.08</td><td></td><td>0.47</td><td>0.02</td><td>-0.20</td><td></td><td></td><td></td><td>2.37</td><td>4.74</td><td>0.00</td><td>2.37</td><td>0.242</td><td style="background-color:#F3F3F3; font-weight:bold;">0.242</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15035">김영웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.188</td><td>14</td><td>1</td><td>36.0</td><td>22</td><td>8</td><td>13</td><td>1</td><td>95.5</td><td>5.25</td><td style="">1.25</td><td></td><td>0.08</td><td>0.22</td><td></td><td></td><td></td><td></td><td>1.56</td><td>4.08</td><td>0.28</td><td>1.84</td><td>0.159</td><td style="background-color:#F3F3F3; font-weight:bold;">0.188</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15035">김영웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.172</td><td>38</td><td>20</td><td>215.1</td><td>56</td><td>11</td><td>40</td><td>5</td><td>91.1</td><td>2.13</td><td style="">1.91</td><td></td><td>0.00</td><td>0.14</td><td>-0.36</td><td></td><td></td><td></td><td>1.69</td><td>4.43</td><td>0.00</td><td>1.69</td><td>0.172</td><td style="background-color:#F3F3F3; font-weight:bold;">0.172</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12936">김성윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.160</td><td>39</td><td>33</td><td>274.2</td><td>69</td><td>65</td><td>2</td><td>2</td><td>97.1</td><td>2.20</td><td style="">2.83</td><td>0.60</td><td>-0.46</td><td></td><td></td><td></td><td></td><td></td><td>2.97</td><td>4.24</td><td>-1.40</td><td>1.57</td><td>0.303</td><td style="background-color:#F3F3F3; font-weight:bold;">0.160</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13161">윤정빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.113</td><td>8</td><td>1</td><td>23.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>1.96</td><td style="">1.18</td><td>-0.09</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>1.13</td><td>5.83</td><td>-0.03</td><td>1.10</td><td>0.116</td><td style="background-color:#F3F3F3; font-weight:bold;">0.113</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13240">김호재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.111</td><td>3</td><td>0</td><td>6.0</td><td>4</td><td>1</td><td>3</td><td>0</td><td>100.0</td><td>6.00</td><td style="">1.05</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>1.07</td><td>2.05</td><td>0.02</td><td>1.09</td><td>0.109</td><td style="background-color:#F3F3F3; font-weight:bold;">0.111</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12936">김성윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.102</td><td>33</td><td>10</td><td>132.1</td><td>38</td><td>37</td><td>1</td><td>0</td><td>100.0</td><td>2.58</td><td style="">1.17</td><td>0.17</td><td>0.23</td><td></td><td></td><td></td><td></td><td></td><td>1.57</td><td>2.24</td><td>-0.57</td><td>1.00</td><td>0.160</td><td style="background-color:#F3F3F3; font-weight:bold;">0.102</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15040">조민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.100</td><td>8</td><td>6</td><td>44.0</td><td>50</td><td>47</td><td>3</td><td>0</td><td>100.0</td><td>10.23</td><td style="">1.26</td><td></td><td>0.08</td><td></td><td></td><td></td><td></td><td></td><td>1.34</td><td>12.83</td><td>-0.36</td><td>0.98</td><td>0.136</td><td style="background-color:#F3F3F3; font-weight:bold;">0.100</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10894">류지혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.098</td><td>11</td><td>6</td><td>56.0</td><td>31</td><td>13</td><td>18</td><td>0</td><td>100.0</td><td>4.98</td><td style="">0.74</td><td></td><td>0.15</td><td>-0.22</td><td></td><td></td><td></td><td></td><td>0.67</td><td>0.73</td><td>0.29</td><td>0.96</td><td>0.068</td><td style="background-color:#F3F3F3; font-weight:bold;">0.098</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12562">이성규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.095</td><td>20</td><td>8</td><td>77.2</td><td>71</td><td>68</td><td>3</td><td>0</td><td>100.0</td><td>8.23</td><td style="">1.33</td><td></td><td>0.14</td><td></td><td>0.06</td><td></td><td></td><td></td><td>1.53</td><td>2.03</td><td>-0.60</td><td>0.93</td><td>0.157</td><td style="background-color:#F3F3F3; font-weight:bold;">0.095</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11255">강한울</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.083</td><td>3</td><td>1</td><td>11.0</td><td>6</td><td>2</td><td>4</td><td>0</td><td>100.0</td><td>4.91</td><td style="">0.69</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.72</td><td>1.44</td><td>0.10</td><td>0.82</td><td>0.073</td><td style="background-color:#F3F3F3; font-weight:bold;">0.083</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14863">김동진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.082</td><td>7</td><td>4</td><td>31.0</td><td>10</td><td>3</td><td>7</td><td>0</td><td>100.0</td><td>2.90</td><td style="">1.20</td><td></td><td>0.07</td><td>-0.47</td><td></td><td></td><td></td><td></td><td>0.80</td><td>2.63</td><td>0.00</td><td>0.80</td><td>0.082</td><td style="background-color:#F3F3F3; font-weight:bold;">0.082</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13240">김호재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.081</td><td>20</td><td>9</td><td>84.0</td><td>47</td><td>25</td><td>22</td><td>0</td><td>100.0</td><td>5.04</td><td style="">-0.59</td><td></td><td>0.23</td><td>0.81</td><td></td><td></td><td></td><td></td><td>0.45</td><td>0.86</td><td>0.35</td><td>0.80</td><td>0.046</td><td style="background-color:#F3F3F3; font-weight:bold;">0.081</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10892">구자욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.079</td><td>22</td><td>22</td><td>182.0</td><td>55</td><td>53</td><td>2</td><td>0</td><td>100.0</td><td>2.72</td><td style="">1.36</td><td>0.07</td><td>0.32</td><td></td><td></td><td></td><td></td><td></td><td>1.76</td><td>2.13</td><td>-0.98</td><td>0.78</td><td>0.179</td><td style="background-color:#F3F3F3; font-weight:bold;">0.079</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11255">강한울</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.077</td><td>11</td><td>7</td><td>63.2</td><td>33</td><td>12</td><td>20</td><td>1</td><td>97.0</td><td>4.52</td><td style="">0.71</td><td></td><td>0.17</td><td>-0.41</td><td></td><td></td><td></td><td></td><td>0.47</td><td>0.93</td><td>0.29</td><td>0.76</td><td>0.047</td><td style="background-color:#F3F3F3; font-weight:bold;">0.077</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14863">김동진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.076</td><td>7</td><td>4</td><td>35.1</td><td>17</td><td>7</td><td>8</td><td>2</td><td>88.2</td><td>3.82</td><td style="">-0.53</td><td></td><td>0.08</td><td>0.89</td><td></td><td></td><td></td><td></td><td>0.45</td><td>1.46</td><td>0.30</td><td>0.75</td><td>0.046</td><td style="background-color:#F3F3F3; font-weight:bold;">0.076</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13161">윤정빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.076</td><td>4</td><td>3</td><td>17.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>2.65</td><td style="">0.59</td><td>0.13</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.74</td><td>3.82</td><td>0.00</td><td>0.74</td><td>0.076</td><td style="background-color:#F3F3F3; font-weight:bold;">0.076</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15501">강준서</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.073</td><td>6</td><td>2</td><td>21.2</td><td>6</td><td>6</td><td>0</td><td>0</td><td>100.0</td><td>2.49</td><td style="">0.77</td><td>-0.07</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.72</td><td>10.37</td><td>0.00</td><td>0.72</td><td>0.073</td><td style="background-color:#F3F3F3; font-weight:bold;">0.073</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15499">김재상</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.061</td><td>4</td><td>1</td><td>13.0</td><td>4</td><td>2</td><td>2</td><td>0</td><td>100.0</td><td>2.77</td><td style="">0.56</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.59</td><td>5.03</td><td>0.00</td><td>0.59</td><td>0.061</td><td style="background-color:#F3F3F3; font-weight:bold;">0.061</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11200">송준석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.053</td><td>2</td><td>1</td><td>3.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">0.43</td><td>0.11</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.54</td><td>11.08</td><td>-0.02</td><td>0.52</td><td>0.055</td><td style="background-color:#F3F3F3; font-weight:bold;">0.053</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11336">김태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.049</td><td>5</td><td>1</td><td>12.0</td><td>17</td><td>15</td><td>2</td><td>0</td><td>100.0</td><td>12.75</td><td style="">1.30</td><td></td><td>0.02</td><td></td><td>-0.79</td><td></td><td></td><td></td><td>0.53</td><td>6.88</td><td>-0.04</td><td>0.49</td><td>0.054</td><td style="background-color:#F3F3F3; font-weight:bold;">0.049</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13164">공민규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.044</td><td>10</td><td>1</td><td>28.1</td><td>33</td><td>33</td><td>0</td><td>0</td><td>100.0</td><td>10.48</td><td style="">0.58</td><td></td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>0.63</td><td>4.13</td><td>-0.20</td><td>0.43</td><td>0.064</td><td style="background-color:#F3F3F3; font-weight:bold;">0.044</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14867">김현준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.044</td><td>1</td><td>1</td><td>8.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>2.25</td><td style="">0.68</td><td>-0.22</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.47</td><td>0.62</td><td>-0.04</td><td>0.43</td><td>0.048</td><td style="background-color:#F3F3F3; font-weight:bold;">0.044</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14115">김도환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.034</td><td>8</td><td>3</td><td>31.0</td><td>25</td><td>24</td><td>1</td><td>0</td><td>100.0</td><td>7.26</td><td style="">-0.09</td><td></td><td>0.08</td><td></td><td></td><td>-0.10</td><td>0.38</td><td></td><td>0.16</td><td>2.58</td><td>0.17</td><td>0.33</td><td>0.016</td><td style="background-color:#F3F3F3; font-weight:bold;">0.034</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14121">이해승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.029</td><td>5</td><td>0</td><td>10.1</td><td>6</td><td>3</td><td>3</td><td>0</td><td>100.0</td><td>5.23</td><td style="">0.16</td><td></td><td>0.02</td><td></td><td>0.10</td><td></td><td></td><td></td><td>0.28</td><td>4.51</td><td>0.00</td><td>0.28</td><td>0.029</td><td style="background-color:#F3F3F3; font-weight:bold;">0.029</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12936">김성윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.025</td><td>28</td><td>12</td><td>141.0</td><td>45</td><td>45</td><td>0</td><td>0</td><td>100.0</td><td>2.87</td><td style="">0.42</td><td>-0.35</td><td>0.18</td><td></td><td></td><td></td><td></td><td></td><td>0.25</td><td>0.35</td><td>0.00</td><td>0.25</td><td>0.025</td><td style="background-color:#F3F3F3; font-weight:bold;">0.025</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14121">이해승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.024</td><td>3</td><td>1</td><td>8.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>1.13</td><td style="">0.39</td><td></td><td>0.02</td><td>-0.22</td><td></td><td></td><td></td><td></td><td>0.19</td><td>3.05</td><td>0.04</td><td>0.23</td><td>0.019</td><td style="background-color:#F3F3F3; font-weight:bold;">0.024</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10180">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.023</td><td>5</td><td>4</td><td>28.0</td><td>27</td><td>23</td><td>4</td><td>0</td><td>100.0</td><td>8.68</td><td style="">0.38</td><td></td><td>0.05</td><td></td><td>0.06</td><td></td><td></td><td></td><td>0.49</td><td>0.79</td><td>-0.26</td><td>0.23</td><td>0.050</td><td style="background-color:#F3F3F3; font-weight:bold;">0.023</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15503">류승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.017</td><td>3</td><td>0</td><td>3.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.01</td><td>0.17</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.17</td><td>1.04</td><td>-0.01</td><td>0.16</td><td>0.018</td><td style="background-color:#F3F3F3; font-weight:bold;">0.017</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14117">이병헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.012</td><td>21</td><td>9</td><td>85.1</td><td>66</td><td>63</td><td>3</td><td>0</td><td>100.0</td><td>6.96</td><td style="">-0.09</td><td></td><td>0.22</td><td></td><td></td><td>0.56</td><td>-1.84</td><td></td><td>-0.61</td><td>-3.79</td><td>0.72</td><td>0.11</td><td>-0.062</td><td style="background-color:#F3F3F3; font-weight:bold;">0.012</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11169">이상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.000</td><td>23</td><td>0</td><td>18.0</td><td>3</td><td>1</td><td>2</td><td>0</td><td>100.0</td><td>1.50</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">0.000</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10640">김헌곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.001</td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td>-0.01</td><td>-0.01</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.001</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13240">김호재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.011</td><td>33</td><td>17</td><td>157.2</td><td>42</td><td>11</td><td>31</td><td>0</td><td>100.0</td><td>2.40</td><td style="">0.17</td><td></td><td>0.36</td><td>-0.47</td><td>-0.17</td><td></td><td></td><td></td><td>-0.11</td><td>-0.22</td><td>0.00</td><td>-0.11</td><td>-0.011</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.011</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11266">김민수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.012</td><td>2</td><td>0</td><td>3.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.00</td><td></td><td>0.01</td><td></td><td></td><td>-0.19</td><td>0.06</td><td></td><td>-0.14</td><td>-10.18</td><td>0.02</td><td>-0.12</td><td>-0.014</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.012</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15035">김영웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.013</td><td>4</td><td>0</td><td>9.0</td><td>2</td><td>0</td><td>2</td><td>0</td><td>100.0</td><td>2.00</td><td style="">-0.18</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.16</td><td>-0.41</td><td>0.03</td><td>-0.13</td><td>-0.016</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.013</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12562">이성규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.021</td><td>2</td><td>0</td><td>5.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>3.60</td><td style="">-0.49</td><td>0.28</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.20</td><td>-0.26</td><td>-0.01</td><td>-0.21</td><td>-0.020</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.021</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15042">김상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.024</td><td>3</td><td>0</td><td>8.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.13</td><td style="">-0.62</td><td>0.39</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.21</td><td>-3.84</td><td>-0.02</td><td>-0.23</td><td>-0.022</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.024</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12988">안주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.043</td><td>18</td><td>12</td><td>113.1</td><td>75</td><td>35</td><td>38</td><td>2</td><td>97.3</td><td>5.80</td><td style="">-1.93</td><td></td><td>0.31</td><td>0.72</td><td></td><td></td><td></td><td></td><td>-0.91</td><td>-2.47</td><td>0.49</td><td>-0.42</td><td>-0.093</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.043</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15499">김재상</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.043</td><td>4</td><td>2</td><td>19.0</td><td>14</td><td>7</td><td>6</td><td>1</td><td>92.9</td><td>6.16</td><td style="">-0.55</td><td></td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>-0.50</td><td>-4.20</td><td>0.07</td><td>-0.43</td><td>-0.051</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.043</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10400">오재일</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.077</td><td>88</td><td>80</td><td>700.0</td><td>717</td><td>656</td><td>53</td><td>8</td><td>98.9</td><td>9.12</td><td style="">4.85</td><td></td><td>0.28</td><td></td><td>0.64</td><td></td><td></td><td></td><td>5.77</td><td>7.84</td><td>-6.52</td><td>-0.75</td><td>0.588</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.077</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11336">김태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.078</td><td>5</td><td>5</td><td>40.0</td><td>9</td><td>8</td><td>1</td><td>0</td><td>100.0</td><td>2.03</td><td style="">-0.70</td><td>0.03</td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>-0.60</td><td>-7.91</td><td>-0.16</td><td>-0.76</td><td>-0.062</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.078</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11200">송준석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.079</td><td>2</td><td>1</td><td>6.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.36</td><td>-0.41</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.76</td><td>-15.54</td><td>-0.02</td><td>-0.78</td><td>-0.077</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.079</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10892">구자욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.085</td><td>70</td><td>69</td><td>590.2</td><td>124</td><td>121</td><td>3</td><td>0</td><td>100.0</td><td>1.89</td><td style="">1.56</td><td>-0.48</td><td>1.14</td><td></td><td></td><td></td><td></td><td></td><td>2.22</td><td>2.68</td><td>-3.05</td><td>-0.83</td><td>0.226</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.085</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10180">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.085</td><td>12</td><td>11</td><td>84.0</td><td>22</td><td>7</td><td>13</td><td>2</td><td>90.9</td><td>2.14</td><td style="">-1.04</td><td></td><td>-0.30</td><td>1.11</td><td>-0.61</td><td></td><td></td><td></td><td>-0.83</td><td>-1.35</td><td>0.00</td><td>-0.83</td><td>-0.085</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.085</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10894">류지혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.086</td><td>44</td><td>35</td><td>288.0</td><td>72</td><td>18</td><td>52</td><td>2</td><td>97.2</td><td>2.19</td><td style="">-1.17</td><td></td><td>0.67</td><td>-0.75</td><td>0.41</td><td></td><td></td><td></td><td>-0.84</td><td>-0.92</td><td>0.00</td><td>-0.84</td><td>-0.086</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.086</td></tr><tr><td style="text-align:center;">52</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15042">김상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.092</td><td>2</td><td>1</td><td>8.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>3.38</td><td style="">-0.76</td><td>-0.15</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.90</td><td>-16.16</td><td>0.00</td><td>-0.90</td><td>-0.092</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.092</td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11255">강한울</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.092</td><td>2</td><td>2</td><td>17.0</td><td>13</td><td>12</td><td>1</td><td>0</td><td>100.0</td><td>6.88</td><td style="">-0.78</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.74</td><td>-1.49</td><td>-0.16</td><td>-0.90</td><td>-0.076</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.092</td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15501">강준서</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.095</td><td>3</td><td>2</td><td>18.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>1.00</td><td style="">-1.05</td><td>0.16</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.85</td><td>-12.26</td><td>-0.08</td><td>-0.93</td><td>-0.087</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.095</td></tr><tr><td style="text-align:center;">55</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15040">조민성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.108</td><td>1</td><td>0</td><td>3.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-1.03</td><td>-0.02</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-1.05</td><td>-10.05</td><td>-0.01</td><td>-1.06</td><td>-0.107</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.108</td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11344">김재성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.108</td><td>8</td><td>5</td><td>44.2</td><td>40</td><td>38</td><td>2</td><td>0</td><td>100.0</td><td>8.06</td><td style="">-0.74</td><td></td><td>0.08</td><td></td><td></td><td></td><td></td><td></td><td>-0.66</td><td>-1.67</td><td>-0.40</td><td>-1.06</td><td>-0.067</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.108</td></tr><tr><td style="text-align:center;">57</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13161">윤정빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.122</td><td>7</td><td>2</td><td>21.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>1.29</td><td style="">-1.03</td><td>-0.12</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-1.11</td><td>-5.70</td><td>-0.09</td><td>-1.20</td><td>-0.113</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.122</td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12988">안주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.122</td><td>4</td><td>2</td><td>16.1</td><td>2</td><td>0</td><td>2</td><td>0</td><td>100.0</td><td>1.10</td><td style="">-1.66</td><td></td><td>0.04</td><td>0.42</td><td></td><td></td><td></td><td></td><td>-1.20</td><td>-3.26</td><td>0.00</td><td>-1.20</td><td>-0.122</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.122</td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15042">김상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.130</td><td>3</td><td>2</td><td>15.0</td><td>10</td><td>10</td><td>0</td><td>0</td><td>100.0</td><td>6.00</td><td style="">-1.34</td><td>0.09</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-1.22</td><td>-21.91</td><td>-0.06</td><td>-1.28</td><td>-0.124</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.130</td></tr><tr><td style="text-align:center;">60</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12988">안주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.132</td><td>13</td><td>2</td><td>25.2</td><td>7</td><td>5</td><td>2</td><td>0</td><td>100.0</td><td>2.45</td><td style="">-1.17</td><td></td><td>0.06</td><td>-0.44</td><td></td><td></td><td></td><td></td><td>-1.56</td><td>-4.23</td><td>0.26</td><td>-1.30</td><td>-0.159</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.132</td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13161">윤정빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.158</td><td>9</td><td>5</td><td>42.0</td><td>41</td><td>39</td><td>2</td><td>0</td><td>100.0</td><td>8.79</td><td style="">-1.33</td><td></td><td>0.08</td><td></td><td>0.06</td><td></td><td></td><td></td><td>-1.19</td><td>-6.13</td><td>-0.36</td><td>-1.55</td><td>-0.122</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.158</td></tr><tr><td style="text-align:center;">62</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14618">김지찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.160</td><td>91</td><td>85</td><td>696.1</td><td>410</td><td>170</td><td>224</td><td>16</td><td>96.1</td><td>5.09</td><td style="">-3.87</td><td></td><td>0.39</td><td>-1.53</td><td></td><td></td><td></td><td></td><td>-5.00</td><td>-7.28</td><td>3.43</td><td>-1.57</td><td>-0.510</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.160</td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10894">류지혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.163</td><td>26</td><td>20</td><td>176.0</td><td>171</td><td>160</td><td>11</td><td>0</td><td>100.0</td><td>8.74</td><td style="">-0.23</td><td></td><td>0.32</td><td></td><td>0.06</td><td></td><td></td><td></td><td>0.15</td><td>0.16</td><td>-1.74</td><td>-1.59</td><td>0.015</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.163</td></tr><tr><td style="text-align:center;">64</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12562">이성규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.166</td><td>41</td><td>3</td><td>104.2</td><td>26</td><td>22</td><td>2</td><td>2</td><td>92.3</td><td>2.06</td><td style="">-1.45</td><td>0.37</td><td>-0.29</td><td></td><td></td><td></td><td></td><td></td><td>-1.37</td><td>-1.81</td><td>-0.26</td><td>-1.63</td><td>-0.140</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.166</td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13160">이태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.167</td><td>7</td><td>3</td><td>22.2</td><td>18</td><td>17</td><td>0</td><td>1</td><td>94.4</td><td>6.75</td><td style="">-1.02</td><td></td><td>-0.45</td><td></td><td></td><td></td><td></td><td></td><td>-1.48</td><td>-17.72</td><td>-0.16</td><td>-1.64</td><td>-0.151</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.167</td></tr><tr><td style="text-align:center;">66</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13240">김호재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.168</td><td>20</td><td>9</td><td>86.0</td><td>81</td><td>70</td><td>9</td><td>2</td><td>97.5</td><td>8.27</td><td style="">-1.33</td><td></td><td>0.16</td><td></td><td>0.06</td><td></td><td></td><td></td><td>-1.11</td><td>-2.13</td><td>-0.54</td><td>-1.65</td><td>-0.113</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.168</td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13164">공민규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.229</td><td>9</td><td>6</td><td>47.0</td><td>8</td><td>3</td><td>5</td><td>0</td><td>100.0</td><td>1.53</td><td style="">-1.59</td><td></td><td>0.11</td><td></td><td>-0.76</td><td></td><td></td><td></td><td>-2.24</td><td>-14.69</td><td>0.00</td><td>-2.24</td><td>-0.229</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.229</td></tr><tr><td style="text-align:center;">68</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12548">김동엽</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.271</td><td>8</td><td>6</td><td>44.0</td><td>11</td><td>10</td><td>0</td><td>1</td><td>90.9</td><td>2.05</td><td style="">-1.48</td><td>-0.51</td><td>-0.42</td><td></td><td></td><td></td><td></td><td></td><td>-2.41</td><td>-5.02</td><td>-0.25</td><td>-2.66</td><td>-0.246</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.271</td></tr><tr><td style="text-align:center;">69</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14867">김현준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.277</td><td>104</td><td>101</td><td>872.0</td><td>310</td><td>301</td><td>4</td><td>5</td><td>98.4</td><td>3.15</td><td style="">-2.20</td><td>0.84</td><td>-1.36</td><td></td><td></td><td></td><td></td><td></td><td>-2.72</td><td>-3.59</td><td>0.00</td><td>-2.72</td><td>-0.277</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.277</td></tr><tr><td style="text-align:center;">70</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14757">피렐라</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.297</td><td>19</td><td>19</td><td>141.0</td><td>33</td><td>32</td><td>0</td><td>1</td><td>97.0</td><td>2.04</td><td style="">-1.93</td><td>0.03</td><td>-0.22</td><td></td><td></td><td></td><td></td><td></td><td>-2.12</td><td>-2.20</td><td>-0.79</td><td>-2.91</td><td>-0.216</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.297</td></tr><tr><td style="text-align:center;">71</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15503">류승민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.319</td><td>18</td><td>16</td><td>120.1</td><td>23</td><td>22</td><td>0</td><td>1</td><td>95.7</td><td>1.65</td><td style="">-1.90</td><td>-0.44</td><td>-0.26</td><td></td><td></td><td></td><td></td><td></td><td>-2.60</td><td>-15.60</td><td>-0.53</td><td>-3.13</td><td>-0.265</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.319</td></tr><tr><td style="text-align:center;">72</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14757">피렐라</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-1.172</td><td>99</td><td>95</td><td>809.0</td><td>178</td><td>171</td><td>6</td><td>1</td><td>99.4</td><td>1.97</td><td style="">-6.95</td><td>-1.28</td><td>0.94</td><td></td><td></td><td></td><td></td><td></td><td>-7.29</td><td>-7.55</td><td>-4.20</td><td>-11.49</td><td>-0.743</td><td style="background-color:#F3F3F3; font-weight:bold;">-1.172</td></tr><tr><td style="text-align:center;">73</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14798">이승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>45</td><td>0</td><td>43.1</td><td>7</td><td>2</td><td>5</td><td>0</td><td>100.0</td><td>1.45</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">73</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10367">오승환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>58</td><td>1</td><td>62.2</td><td>16</td><td>4</td><td>12</td><td>0</td><td>100.0</td><td>2.30</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">73</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10527">이승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>60</td><td>0</td><td>60.0</td><td>8</td><td>4</td><td>4</td><td>0</td><td>100.0</td><td>1.20</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">73</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10685">김대우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>44</td><td>5</td><td>64.0</td><td>13</td><td>3</td><td>8</td><td>2</td><td>84.6</td><td>1.55</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">73</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10640">김헌곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>4</td><td>0</td><td>4.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-1.19</td><td>0.19</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.99</td><td>-23.72</td><td></td><td></td><td>-0.101</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">73</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13244">이재익</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>49</td><td>0</td><td>41.0</td><td>9</td><td>3</td><td>5</td><td>1</td><td>88.9</td><td>1.76</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">73</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10871">김태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>63</td><td>0</td><td>55.2</td><td>17</td><td>4</td><td>13</td><td>0</td><td>100.0</td><td>2.75</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">73</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14121">이해승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>2</td><td>1</td><td>1</td><td>0</td><td>100.0</td><td>18.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.04</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">73</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15039">김서준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#0061AA;color:#fff;">23</span> <span><img src="/data/team/ci/2023/1001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>8</td><td>1</td><td>7.2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>
""")

In [67]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12922">박성한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.447</td><td>128</td><td>124</td><td>1090.1</td><td>605</td><td>218</td><td>368</td><td>19</td><td>96.9</td><td>4.84</td><td style="">5.62</td><td></td><td>-0.90</td><td>-1.10</td><td></td><td></td><td></td><td></td><td>3.62</td><td>4.08</td><td>10.56</td><td>14.18</td><td>0.370</td><td style="background-color:#F3F3F3; font-weight:bold;">1.447</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10707">김민식</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.249</td><td>121</td><td>87</td><td>786.2</td><td>664</td><td>601</td><td>62</td><td>1</td><td>99.8</td><td>7.59</td><td style="">0.99</td><td></td><td>1.54</td><td></td><td>0.11</td><td>1.90</td><td>0.39</td><td></td><td>4.81</td><td>5.67</td><td>7.44</td><td>12.25</td><td>0.490</td><td style="background-color:#F3F3F3; font-weight:bold;">1.249</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10636">김성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.418</td><td>69</td><td>44</td><td>426.0</td><td>272</td><td>122</td><td>144</td><td>6</td><td>97.8</td><td>5.62</td><td style="">3.29</td><td></td><td>-0.33</td><td>-0.66</td><td></td><td></td><td></td><td></td><td>2.30</td><td>2.95</td><td>1.80</td><td>4.10</td><td>0.234</td><td style="background-color:#F3F3F3; font-weight:bold;">0.418</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13128">최준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.347</td><td>23</td><td>13</td><td>99.0</td><td>60</td><td>26</td><td>34</td><td>0</td><td>100.0</td><td>5.45</td><td style="">2.69</td><td></td><td>0.27</td><td>0.01</td><td></td><td></td><td></td><td></td><td>2.98</td><td>11.28</td><td>0.43</td><td>3.41</td><td>0.304</td><td style="background-color:#F3F3F3; font-weight:bold;">0.347</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10636">김성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.344</td><td>26</td><td>19</td><td>179.0</td><td>97</td><td>40</td><td>53</td><td>4</td><td>95.9</td><td>4.68</td><td style="">0.66</td><td></td><td>0.42</td><td>0.67</td><td></td><td></td><td></td><td></td><td>1.75</td><td>2.25</td><td>1.62</td><td>3.37</td><td>0.179</td><td style="background-color:#F3F3F3; font-weight:bold;">0.344</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14806">조형우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.254</td><td>55</td><td>38</td><td>312.2</td><td>293</td><td>258</td><td>30</td><td>5</td><td>98.3</td><td>8.29</td><td style="">0.19</td><td></td><td>-1.17</td><td></td><td>-0.01</td><td>0.62</td><td>-0.14</td><td></td><td>-0.47</td><td>-1.08</td><td>2.95</td><td>2.49</td><td>-0.047</td><td style="background-color:#F3F3F3; font-weight:bold;">0.254</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13195">최상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.201</td><td>14</td><td>3</td><td>56.2</td><td>23</td><td>23</td><td>0</td><td>0</td><td>100.0</td><td>3.65</td><td style="">2.10</td><td>-0.20</td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>1.98</td><td>5.58</td><td>0.00</td><td>1.98</td><td>0.201</td><td style="background-color:#F3F3F3; font-weight:bold;">0.201</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14147">하재훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.149</td><td>41</td><td>24</td><td>253.0</td><td>67</td><td>63</td><td>3</td><td>1</td><td>98.5</td><td>2.35</td><td style="">2.64</td><td>0.02</td><td>-0.05</td><td></td><td></td><td></td><td></td><td></td><td>2.61</td><td>4.88</td><td>-1.15</td><td>1.46</td><td>0.266</td><td style="background-color:#F3F3F3; font-weight:bold;">0.149</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12622">김찬형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.143</td><td>3</td><td>1</td><td>9.0</td><td>11</td><td>4</td><td>7</td><td>0</td><td>100.0</td><td>11.00</td><td style="">1.22</td><td></td><td>0.02</td><td>0.10</td><td></td><td></td><td></td><td></td><td>1.34</td><td>5.35</td><td>0.06</td><td>1.40</td><td>0.136</td><td style="background-color:#F3F3F3; font-weight:bold;">0.143</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12622">김찬형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.128</td><td>8</td><td>3</td><td>31.2</td><td>26</td><td>9</td><td>17</td><td>0</td><td>100.0</td><td>7.39</td><td style="">0.79</td><td></td><td>0.09</td><td>0.25</td><td></td><td></td><td></td><td></td><td>1.13</td><td>4.51</td><td>0.13</td><td>1.26</td><td>0.115</td><td style="background-color:#F3F3F3; font-weight:bold;">0.128</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10249">오태곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.105</td><td>14</td><td>6</td><td>62.0</td><td>15</td><td>13</td><td>1</td><td>1</td><td>93.3</td><td>2.03</td><td style="">1.35</td><td>0.32</td><td>-0.38</td><td></td><td></td><td></td><td></td><td></td><td>1.28</td><td>1.50</td><td>-0.25</td><td>1.03</td><td>0.131</td><td style="background-color:#F3F3F3; font-weight:bold;">0.105</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15530">에레디아</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.086</td><td>13</td><td>11</td><td>94.1</td><td>22</td><td>21</td><td>1</td><td>0</td><td>100.0</td><td>2.10</td><td style="">0.86</td><td>-0.14</td><td>0.12</td><td></td><td></td><td></td><td></td><td></td><td>0.84</td><td>0.99</td><td>0.00</td><td>0.84</td><td>0.086</td><td style="background-color:#F3F3F3; font-weight:bold;">0.086</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14807">고명준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.083</td><td>1</td><td>1</td><td>5.0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>12.60</td><td style="">0.87</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.88</td><td>63.01</td><td>-0.06</td><td>0.82</td><td>0.089</td><td style="background-color:#F3F3F3; font-weight:bold;">0.083</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10082">이재원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.059</td><td>27</td><td>15</td><td>134.0</td><td>118</td><td>105</td><td>12</td><td>1</td><td>99.2</td><td>7.86</td><td style="">0.30</td><td></td><td>-0.15</td><td></td><td>-0.01</td><td>-1.54</td><td>1.20</td><td></td><td>-0.55</td><td>-2.94</td><td>1.13</td><td>0.58</td><td>-0.056</td><td style="background-color:#F3F3F3; font-weight:bold;">0.059</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14147">하재훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.047</td><td>28</td><td>23</td><td>208.0</td><td>47</td><td>44</td><td>2</td><td>1</td><td>97.9</td><td>1.99</td><td style="">1.50</td><td>-0.01</td><td>-0.09</td><td></td><td></td><td></td><td></td><td></td><td>1.39</td><td>2.61</td><td>-0.93</td><td>0.46</td><td>0.142</td><td style="background-color:#F3F3F3; font-weight:bold;">0.047</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13195">최상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.041</td><td>23</td><td>2</td><td>46.2</td><td>13</td><td>13</td><td>0</td><td>0</td><td>100.0</td><td>2.51</td><td style="">0.50</td><td>-0.07</td><td>0.09</td><td></td><td></td><td></td><td></td><td></td><td>0.52</td><td>1.48</td><td>-0.12</td><td>0.40</td><td>0.053</td><td style="background-color:#F3F3F3; font-weight:bold;">0.041</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13194">이정범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.029</td><td>3</td><td>3</td><td>18.0</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>1.50</td><td style="">0.29</td><td>0.06</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.38</td><td>3.65</td><td>-0.10</td><td>0.28</td><td>0.039</td><td style="background-color:#F3F3F3; font-weight:bold;">0.029</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12613">안상현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.020</td><td>45</td><td>14</td><td>169.0</td><td>94</td><td>38</td><td>54</td><td>2</td><td>97.9</td><td>4.90</td><td style="">0.24</td><td></td><td>-0.04</td><td>-0.55</td><td></td><td></td><td></td><td></td><td>-0.35</td><td>-0.88</td><td>0.55</td><td>0.20</td><td>-0.036</td><td style="background-color:#F3F3F3; font-weight:bold;">0.020</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10108">김강민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.019</td><td>33</td><td>22</td><td>202.1</td><td>60</td><td>57</td><td>3</td><td>0</td><td>100.0</td><td>2.67</td><td style="">-0.67</td><td>0.60</td><td>0.26</td><td></td><td></td><td></td><td></td><td></td><td>0.19</td><td>0.39</td><td>0.00</td><td>0.19</td><td>0.019</td><td style="background-color:#F3F3F3; font-weight:bold;">0.019</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12613">안상현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.016</td><td>6</td><td>0</td><td>10.0</td><td>3</td><td>1</td><td>2</td><td>0</td><td>100.0</td><td>2.70</td><td style="">-0.27</td><td></td><td>0.02</td><td>0.33</td><td></td><td></td><td></td><td></td><td>0.08</td><td>0.20</td><td>0.08</td><td>0.16</td><td>0.008</td><td style="background-color:#F3F3F3; font-weight:bold;">0.016</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15465">김건웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.006</td><td>1</td><td>1</td><td>9.0</td><td>6</td><td>6</td><td>0</td><td>0</td><td>100.0</td><td>6.00</td><td style="">0.10</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.11</td><td>16.46</td><td>-0.06</td><td>0.05</td><td>0.012</td><td style="background-color:#F3F3F3; font-weight:bold;">0.006</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11148">강진성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.001</td><td>2</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.01</td><td>-0.01</td><td>-0.01</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.001</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14807">고명준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.002</td><td>1</td><td>0</td><td>1.1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.02</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.02</td><td>-1.55</td><td>0.00</td><td>-0.02</td><td>-0.002</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.002</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10815">한유섬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.025</td><td>11</td><td>9</td><td>69.0</td><td>17</td><td>16</td><td>0</td><td>1</td><td>94.1</td><td>2.09</td><td style="">1.16</td><td>-0.69</td><td>-0.37</td><td></td><td></td><td></td><td></td><td></td><td>0.10</td><td>0.13</td><td>-0.34</td><td>-0.24</td><td>0.010</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.025</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14587">최지훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.029</td><td>19</td><td>9</td><td>87.0</td><td>25</td><td>23</td><td>2</td><td>0</td><td>100.0</td><td>2.59</td><td style="">-0.40</td><td>0.36</td><td>0.17</td><td></td><td></td><td></td><td></td><td></td><td>0.14</td><td>0.17</td><td>-0.42</td><td>-0.28</td><td>0.014</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.029</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13195">최상민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.034</td><td>5</td><td>1</td><td>11.1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.44</td><td>0.11</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.31</td><td>-0.87</td><td>-0.03</td><td>-0.34</td><td>-0.031</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.034</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15463">김정민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.035</td><td>5</td><td>0</td><td>8.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>2.25</td><td style="">-0.27</td><td>-0.07</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.33</td><td>-5.88</td><td>-0.02</td><td>-0.35</td><td>-0.033</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.035</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10182">최주환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.046</td><td>78</td><td>69</td><td>540.2</td><td>306</td><td>131</td><td>168</td><td>7</td><td>97.7</td><td>4.98</td><td style="">-3.95</td><td></td><td>-0.03</td><td>0.71</td><td></td><td></td><td></td><td></td><td>-3.26</td><td>-3.50</td><td>2.81</td><td>-0.45</td><td>-0.332</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.046</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11148">강진성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.055</td><td>29</td><td>27</td><td>219.1</td><td>233</td><td>217</td><td>15</td><td>1</td><td>99.6</td><td>9.52</td><td style="">1.08</td><td></td><td>0.40</td><td></td><td>0.06</td><td></td><td></td><td></td><td>1.54</td><td>3.82</td><td>-2.08</td><td>-0.54</td><td>0.157</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.055</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14147">하재훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.080</td><td>1</td><td>1</td><td>7.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.79</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.79</td><td>-1.47</td><td>0.00</td><td>-0.79</td><td>-0.080</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.080</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12613">안상현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.086</td><td>1</td><td>0</td><td>3.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-0.61</td><td></td><td>0.01</td><td>-0.24</td><td></td><td></td><td></td><td></td><td>-0.85</td><td>-2.10</td><td>0.00</td><td>-0.85</td><td>-0.086</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.086</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13194">이정범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.093</td><td>3</td><td>2</td><td>7.1</td><td>3</td><td>2</td><td>1</td><td>0</td><td>100.0</td><td>3.68</td><td style="">-0.68</td><td>-0.21</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.88</td><td>-8.41</td><td>-0.04</td><td>-0.92</td><td>-0.089</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.093</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11148">강진성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.099</td><td>8</td><td>4</td><td>33.0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>1.91</td><td style="">-1.09</td><td>0.19</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>-0.84</td><td>-2.09</td><td>-0.13</td><td>-0.97</td><td>-0.086</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.099</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14151">최경모</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.100</td><td>10</td><td>1</td><td>21.0</td><td>18</td><td>9</td><td>7</td><td>2</td><td>88.9</td><td>6.86</td><td style="">-0.79</td><td></td><td>-0.44</td><td>0.23</td><td></td><td></td><td></td><td></td><td>-1.00</td><td>-5.14</td><td>0.02</td><td>-0.98</td><td>-0.102</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.100</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10108">김강민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.113</td><td>4</td><td>1</td><td>13.2</td><td>3</td><td>3</td><td>0</td><td>0</td><td>100.0</td><td>1.98</td><td style="">-0.65</td><td>-0.40</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-1.03</td><td>-2.12</td><td>-0.08</td><td>-1.11</td><td>-0.105</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.113</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14587">최지훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.140</td><td>1</td><td>1</td><td>8.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.13</td><td style="">-1.35</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-1.33</td><td>-1.64</td><td>-0.04</td><td>-1.37</td><td>-0.136</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.140</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10810">최항</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.141</td><td>3</td><td>2</td><td>15.0</td><td>7</td><td>3</td><td>2</td><td>2</td><td>71.4</td><td>3.00</td><td style="">-1.51</td><td></td><td>0.03</td><td></td><td>0.10</td><td></td><td></td><td></td><td>-1.38</td><td>-9.46</td><td>0.00</td><td>-1.38</td><td>-0.141</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.141</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14151">최경모</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.162</td><td>12</td><td>3</td><td>48.0</td><td>15</td><td>4</td><td>8</td><td>3</td><td>80.0</td><td>2.25</td><td style="">-1.11</td><td></td><td>-0.38</td><td>-0.09</td><td></td><td></td><td></td><td></td><td>-1.58</td><td>-8.15</td><td>0.00</td><td>-1.58</td><td>-0.162</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.162</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10249">오태곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.180</td><td>12</td><td>7</td><td>56.1</td><td>17</td><td>16</td><td>0</td><td>1</td><td>94.1</td><td>2.56</td><td style="">-1.61</td><td>0.27</td><td>-0.42</td><td></td><td></td><td></td><td></td><td></td><td>-1.76</td><td>-2.06</td><td>0.00</td><td>-1.76</td><td>-0.180</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.180</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10249">오태곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.195</td><td>23</td><td>14</td><td>124.0</td><td>30</td><td>26</td><td>2</td><td>2</td><td>93.3</td><td>2.03</td><td style="">-0.85</td><td>0.23</td><td>-0.75</td><td></td><td></td><td></td><td></td><td></td><td>-1.36</td><td>-1.60</td><td>-0.55</td><td>-1.91</td><td>-0.139</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.195</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11108">이흥련</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.202</td><td>16</td><td>4</td><td>55.0</td><td>48</td><td>45</td><td>2</td><td>1</td><td>97.9</td><td>7.69</td><td style="">0.00</td><td></td><td>-0.35</td><td></td><td>-0.01</td><td>-0.98</td><td>-1.45</td><td></td><td>-2.36</td><td>-21.25</td><td>0.38</td><td>-1.98</td><td>-0.241</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.202</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10810">최항</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.220</td><td>7</td><td>4</td><td>32.1</td><td>31</td><td>28</td><td>1</td><td>2</td><td>93.5</td><td>8.07</td><td style="">-1.46</td><td></td><td>-0.44</td><td></td><td></td><td></td><td></td><td></td><td>-1.89</td><td>-12.98</td><td>-0.26</td><td>-2.15</td><td>-0.193</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.220</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14587">최지훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.234</td><td>109</td><td>100</td><td>871.2</td><td>231</td><td>225</td><td>3</td><td>3</td><td>98.7</td><td>2.35</td><td style="">-2.23</td><td>0.32</td><td>-0.38</td><td></td><td></td><td></td><td></td><td></td><td>-2.29</td><td>-2.82</td><td>0.00</td><td>-2.29</td><td>-0.234</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.234</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10106">최정</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.256</td><td>114</td><td>112</td><td>934.1</td><td>258</td><td>70</td><td>175</td><td>13</td><td>95.0</td><td>2.36</td><td style="">-4.87</td><td></td><td>1.67</td><td>0.69</td><td>0.01</td><td></td><td></td><td></td><td>-2.51</td><td>-2.82</td><td>0.00</td><td>-2.51</td><td>-0.256</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.256</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10249">오태곤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.265</td><td>80</td><td>40</td><td>433.2</td><td>452</td><td>413</td><td>37</td><td>2</td><td>99.6</td><td>9.34</td><td style="">0.27</td><td></td><td>0.79</td><td></td><td>0.06</td><td></td><td></td><td></td><td>1.12</td><td>1.31</td><td>-3.72</td><td>-2.60</td><td>0.114</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.265</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10636">김성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.277</td><td>26</td><td>21</td><td>185.2</td><td>50</td><td>14</td><td>32</td><td>4</td><td>92.0</td><td>2.23</td><td style="">-1.98</td><td></td><td>-0.56</td><td>-0.27</td><td>0.09</td><td></td><td></td><td></td><td>-2.72</td><td>-3.49</td><td>0.00</td><td>-2.72</td><td>-0.277</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.277</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15530">에레디아</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.302</td><td>101</td><td>97</td><td>843.2</td><td>216</td><td>201</td><td>10</td><td>5</td><td>97.7</td><td>2.25</td><td style="">2.75</td><td>-0.54</td><td>-0.98</td><td></td><td></td><td></td><td></td><td></td><td>1.23</td><td>1.46</td><td>-4.20</td><td>-2.97</td><td>0.126</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.302</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12622">김찬형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.306</td><td>25</td><td>6</td><td>100.0</td><td>22</td><td>5</td><td>14</td><td>3</td><td>86.4</td><td>1.71</td><td style="">-1.89</td><td></td><td>-0.76</td><td>-0.09</td><td>-0.27</td><td></td><td></td><td></td><td>-3.00</td><td>-12.00</td><td>0.00</td><td>-3.00</td><td>-0.306</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.306</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14699">전의산</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.322</td><td>45</td><td>37</td><td>296.0</td><td>292</td><td>268</td><td>20</td><td>4</td><td>98.6</td><td>8.76</td><td style="">-1.10</td><td></td><td>0.54</td><td></td><td>0.06</td><td></td><td></td><td></td><td>-0.50</td><td>-1.29</td><td>-2.66</td><td>-3.16</td><td>-0.051</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.322</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14888">추신수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.324</td><td>25</td><td>24</td><td>187.1</td><td>43</td><td>42</td><td>1</td><td>0</td><td>100.0</td><td>2.07</td><td style="">-2.66</td><td>0.21</td><td>0.36</td><td></td><td></td><td></td><td></td><td></td><td>-2.09</td><td>-2.69</td><td>-1.08</td><td>-3.17</td><td>-0.213</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.324</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10182">최주환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.538</td><td>47</td><td>34</td><td>293.0</td><td>294</td><td>265</td><td>27</td><td>2</td><td>99.3</td><td>8.97</td><td style="">-2.01</td><td></td><td>-0.46</td><td></td><td>0.20</td><td></td><td></td><td></td><td>-2.28</td><td>-2.45</td><td>-3.00</td><td>-5.28</td><td>-0.232</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.538</td></tr><tr><td style="text-align:center;">52</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10815">한유섬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.923</td><td>79</td><td>68</td><td>593.2</td><td>114</td><td>106</td><td>5</td><td>3</td><td>97.4</td><td>1.68</td><td style="">-6.44</td><td>0.56</td><td>-0.34</td><td></td><td></td><td></td><td></td><td></td><td>-6.22</td><td>-8.22</td><td>-2.83</td><td>-9.05</td><td>-0.634</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.923</td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10783">문승원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>50</td><td>12</td><td>105.0</td><td>28</td><td>6</td><td>21</td><td>1</td><td>96.4</td><td>2.31</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13128">최준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.00</td><td></td><td>0.00</td><td></td><td>0.10</td><td></td><td></td><td></td><td>0.10</td><td>0.37</td><td></td><td></td><td>0.010</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10784">서진용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>69</td><td>0</td><td>73.0</td><td>5</td><td>1</td><td>4</td><td>0</td><td>100.0</td><td>0.62</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10124">고효준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>70</td><td>0</td><td>58.0</td><td>11</td><td>1</td><td>8</td><td>2</td><td>81.8</td><td>1.40</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10810">최항</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.36</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.36</td><td>-2.46</td><td></td><td></td><td>-0.037</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11242">이건욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>27</td><td>1</td><td>38.2</td><td>7</td><td>1</td><td>5</td><td>1</td><td>85.7</td><td>1.40</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13126">최민준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>52</td><td>0</td><td>60.0</td><td>9</td><td>3</td><td>6</td><td>0</td><td>100.0</td><td>1.35</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14145">백승건</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>24</td><td>2</td><td>38.0</td><td>6</td><td>0</td><td>5</td><td>1</td><td>83.3</td><td>1.18</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10203">노경은</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>74</td><td>0</td><td>83.0</td><td>15</td><td>6</td><td>8</td><td>1</td><td>93.3</td><td>1.52</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10795">임준섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>39</td><td>0</td><td>32.2</td><td>3</td><td>1</td><td>2</td><td>0</td><td>100.0</td><td>0.83</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15463">김정민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#cf152d;color:#fff;">23</span> <span><img src="/data/team/ci/2023/9002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.26</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.26</td><td>-4.69</td><td></td><td></td><td>-0.027</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>
""")

In [68]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14765">김주원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.877</td><td>127</td><td>122</td><td>1030.0</td><td>519</td><td>177</td><td>313</td><td>29</td><td>94.4</td><td>4.28</td><td style="">1.47</td><td></td><td>-2.53</td><td>0.32</td><td></td><td></td><td></td><td></td><td>-0.74</td><td>-0.84</td><td>9.34</td><td>8.60</td><td>-0.075</td><td style="background-color:#F3F3F3; font-weight:bold;">0.877</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11137">박민우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.840</td><td>114</td><td>108</td><td>874.2</td><td>475</td><td>196</td><td>264</td><td>15</td><td>96.8</td><td>4.73</td><td style="">5.73</td><td></td><td>-1.10</td><td>-1.10</td><td></td><td></td><td></td><td></td><td>3.53</td><td>4.10</td><td>4.71</td><td>8.24</td><td>0.360</td><td style="background-color:#F3F3F3; font-weight:bold;">0.840</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10891">박세혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.809</td><td>86</td><td>72</td><td>620.0</td><td>566</td><td>524</td><td>41</td><td>1</td><td>99.8</td><td>8.20</td><td style="">0.38</td><td></td><td>1.11</td><td></td><td>0.28</td><td>-1.17</td><td>0.99</td><td></td><td>1.29</td><td>2.10</td><td>6.65</td><td>7.93</td><td>0.131</td><td style="background-color:#F3F3F3; font-weight:bold;">0.809</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14220">서호철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.488</td><td>96</td><td>78</td><td>690.0</td><td>209</td><td>66</td><td>133</td><td>10</td><td>95.2</td><td>2.60</td><td style="">3.91</td><td></td><td>-0.38</td><td>0.85</td><td>0.40</td><td></td><td></td><td></td><td>4.78</td><td>6.04</td><td>0.00</td><td>4.78</td><td>0.488</td><td style="background-color:#F3F3F3; font-weight:bold;">0.488</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13081">김형준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.350</td><td>24</td><td>19</td><td>180.0</td><td>169</td><td>160</td><td>7</td><td>2</td><td>98.8</td><td>8.35</td><td style="">0.12</td><td></td><td>-0.52</td><td></td><td></td><td>0.16</td><td>2.62</td><td></td><td>1.59</td><td>8.80</td><td>1.85</td><td>3.44</td><td>0.162</td><td style="background-color:#F3F3F3; font-weight:bold;">0.350</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14220">서호철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.321</td><td>30</td><td>23</td><td>190.2</td><td>112</td><td>44</td><td>64</td><td>4</td><td>96.4</td><td>5.10</td><td style="">0.96</td><td></td><td>0.51</td><td>0.62</td><td></td><td></td><td></td><td></td><td>2.10</td><td>2.65</td><td>1.05</td><td>3.15</td><td>0.214</td><td style="background-color:#F3F3F3; font-weight:bold;">0.321</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14716">김한별</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.320</td><td>47</td><td>22</td><td>232.1</td><td>101</td><td>24</td><td>74</td><td>3</td><td>97.0</td><td>3.80</td><td style="">1.52</td><td></td><td>0.05</td><td>-0.18</td><td></td><td></td><td></td><td></td><td>1.40</td><td>2.55</td><td>1.74</td><td>3.14</td><td>0.143</td><td style="background-color:#F3F3F3; font-weight:bold;">0.320</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13261">천재환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.255</td><td>15</td><td>2</td><td>46.0</td><td>15</td><td>15</td><td>0</td><td>0</td><td>100.0</td><td>2.93</td><td style="">1.91</td><td>0.70</td><td>0.08</td><td></td><td></td><td></td><td></td><td></td><td>2.68</td><td>4.96</td><td>-0.18</td><td>2.50</td><td>0.274</td><td style="background-color:#F3F3F3; font-weight:bold;">0.255</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13250">한석현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.203</td><td>20</td><td>6</td><td>77.0</td><td>20</td><td>20</td><td>0</td><td>0</td><td>100.0</td><td>2.34</td><td style="">2.51</td><td>-0.33</td><td>0.14</td><td></td><td></td><td></td><td></td><td></td><td>2.32</td><td>12.39</td><td>-0.33</td><td>1.99</td><td>0.237</td><td style="background-color:#F3F3F3; font-weight:bold;">0.203</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12560">도태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.189</td><td>56</td><td>36</td><td>347.2</td><td>91</td><td>26</td><td>62</td><td>3</td><td>96.7</td><td>2.28</td><td style="">2.36</td><td></td><td>-0.19</td><td>-0.42</td><td>0.09</td><td></td><td></td><td></td><td>1.85</td><td>2.28</td><td>0.00</td><td>1.85</td><td>0.189</td><td style="background-color:#F3F3F3; font-weight:bold;">0.189</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11153">김성욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.171</td><td>31</td><td>19</td><td>167.2</td><td>37</td><td>37</td><td>0</td><td>0</td><td>100.0</td><td>1.99</td><td style="">1.88</td><td>0.28</td><td>0.30</td><td></td><td></td><td></td><td></td><td></td><td>2.46</td><td>3.81</td><td>-0.79</td><td>1.67</td><td>0.251</td><td style="background-color:#F3F3F3; font-weight:bold;">0.171</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13261">천재환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.162</td><td>37</td><td>27</td><td>259.2</td><td>74</td><td>72</td><td>2</td><td>0</td><td>100.0</td><td>2.56</td><td style="">1.29</td><td>-0.03</td><td>0.33</td><td></td><td></td><td></td><td></td><td></td><td>1.59</td><td>2.94</td><td>0.00</td><td>1.59</td><td>0.162</td><td style="background-color:#F3F3F3; font-weight:bold;">0.162</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12560">도태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.148</td><td>17</td><td>7</td><td>79.1</td><td>46</td><td>26</td><td>20</td><td>0</td><td>100.0</td><td>5.22</td><td style="">0.34</td><td></td><td>0.21</td><td>0.54</td><td></td><td></td><td></td><td></td><td>1.09</td><td>1.35</td><td>0.36</td><td>1.45</td><td>0.112</td><td style="background-color:#F3F3F3; font-weight:bold;">0.148</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14221">최정원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.147</td><td>11</td><td>5</td><td>62.0</td><td>34</td><td>11</td><td>23</td><td>0</td><td>100.0</td><td>4.94</td><td style="">1.55</td><td></td><td>0.17</td><td>-0.58</td><td></td><td></td><td></td><td></td><td>1.14</td><td>4.20</td><td>0.30</td><td>1.44</td><td>0.116</td><td style="background-color:#F3F3F3; font-weight:bold;">0.147</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15537">마틴</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.146</td><td>29</td><td>26</td><td>232.1</td><td>55</td><td>53</td><td>1</td><td>1</td><td>98.2</td><td>2.09</td><td style="">1.80</td><td>0.84</td><td>-0.08</td><td></td><td></td><td></td><td></td><td></td><td>2.56</td><td>3.12</td><td>-1.13</td><td>1.43</td><td>0.261</td><td style="background-color:#F3F3F3; font-weight:bold;">0.146</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14716">김한별</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.122</td><td>29</td><td>1</td><td>49.2</td><td>20</td><td>6</td><td>13</td><td>1</td><td>95.0</td><td>3.44</td><td style="">0.94</td><td></td><td>0.13</td><td></td><td></td><td></td><td></td><td></td><td>1.07</td><td>1.96</td><td>0.12</td><td>1.19</td><td>0.110</td><td style="background-color:#F3F3F3; font-weight:bold;">0.122</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14661">박영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.096</td><td>6</td><td>0</td><td>9.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>4.00</td><td style="">0.93</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.95</td><td>3.33</td><td>-0.01</td><td>0.94</td><td>0.097</td><td style="background-color:#F3F3F3; font-weight:bold;">0.096</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14661">박영빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.078</td><td>15</td><td>0</td><td>25.0</td><td>8</td><td>8</td><td>0</td><td>0</td><td>100.0</td><td>2.88</td><td style="">0.64</td><td>0.09</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.76</td><td>2.69</td><td>0.00</td><td>0.76</td><td>0.078</td><td style="background-color:#F3F3F3; font-weight:bold;">0.078</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12560">도태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.067</td><td>59</td><td>23</td><td>287.0</td><td>280</td><td>260</td><td>19</td><td>1</td><td>99.6</td><td>8.75</td><td style="">2.58</td><td></td><td>0.52</td><td></td><td>-0.16</td><td></td><td></td><td></td><td>2.94</td><td>3.62</td><td>-2.28</td><td>0.66</td><td>0.300</td><td style="background-color:#F3F3F3; font-weight:bold;">0.067</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11153">김성욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.058</td><td>45</td><td>5</td><td>119.2</td><td>24</td><td>23</td><td>1</td><td>0</td><td>100.0</td><td>1.81</td><td style="">-0.28</td><td>1.04</td><td>0.23</td><td></td><td></td><td></td><td></td><td></td><td>0.99</td><td>1.53</td><td>-0.42</td><td>0.57</td><td>0.101</td><td style="background-color:#F3F3F3; font-weight:bold;">0.058</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11329">안중열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.036</td><td>74</td><td>50</td><td>411.2</td><td>399</td><td>373</td><td>21</td><td>5</td><td>98.7</td><td>8.61</td><td style="">-0.22</td><td></td><td>-1.41</td><td></td><td>-0.30</td><td>1.06</td><td>-3.93</td><td></td><td>-3.63</td><td>-6.78</td><td>3.98</td><td>0.36</td><td>-0.370</td><td style="background-color:#F3F3F3; font-weight:bold;">0.036</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13087">최보성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.030</td><td>2</td><td>0</td><td>4.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>2.25</td><td style="">0.28</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.29</td><td>3.45</td><td>0.01</td><td>0.30</td><td>0.029</td><td style="background-color:#F3F3F3; font-weight:bold;">0.030</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14220">서호철</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.027</td><td>2</td><td>0</td><td>4.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>2.25</td><td style="">0.22</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.23</td><td>0.29</td><td>0.04</td><td>0.27</td><td>0.023</td><td style="background-color:#F3F3F3; font-weight:bold;">0.027</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14767">오장한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.026</td><td>3</td><td>1</td><td>9.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>2.00</td><td style="">0.15</td><td>0.13</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.29</td><td>14.10</td><td>-0.04</td><td>0.25</td><td>0.030</td><td style="background-color:#F3F3F3; font-weight:bold;">0.026</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15451">박한결</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.022</td><td>5</td><td>1</td><td>14.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>3.21</td><td style="">0.91</td><td>-0.64</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.30</td><td>3.57</td><td>-0.08</td><td>0.22</td><td>0.030</td><td style="background-color:#F3F3F3; font-weight:bold;">0.022</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11172">권희동</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.020</td><td>7</td><td>4</td><td>37.0</td><td>8</td><td>8</td><td>0</td><td>0</td><td>100.0</td><td>1.95</td><td style="">0.68</td><td>-0.36</td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>0.39</td><td>0.59</td><td>-0.20</td><td>0.19</td><td>0.040</td><td style="background-color:#F3F3F3; font-weight:bold;">0.020</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10261">손아섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.014</td><td>49</td><td>43</td><td>343.1</td><td>76</td><td>73</td><td>1</td><td>2</td><td>97.4</td><td>1.94</td><td style="">2.31</td><td>0.10</td><td>-0.33</td><td></td><td></td><td></td><td></td><td></td><td>2.09</td><td>2.15</td><td>-1.95</td><td>0.14</td><td>0.213</td><td style="background-color:#F3F3F3; font-weight:bold;">0.014</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14765">김주원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.011</td><td>6</td><td>0</td><td>15.0</td><td>20</td><td>10</td><td>9</td><td>1</td><td>95.0</td><td>11.40</td><td style="">-0.49</td><td></td><td>0.04</td><td>0.51</td><td></td><td></td><td></td><td></td><td>0.07</td><td>0.07</td><td>0.04</td><td>0.11</td><td>0.007</td><td style="background-color:#F3F3F3; font-weight:bold;">0.011</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14766">오태양</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.002</td><td>4</td><td>1</td><td>7.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.29</td><td style="">0.07</td><td>-0.06</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.10</td><td>0.00</td><td>0.01</td><td>0.002</td><td style="background-color:#F3F3F3; font-weight:bold;">0.002</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14156">전사민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.000</td><td>9</td><td>0</td><td>17.0</td><td>7</td><td>3</td><td>3</td><td>1</td><td>85.7</td><td>3.18</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;">0.000</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11246">박대온</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.004</td><td>24</td><td>3</td><td>69.2</td><td>71</td><td>64</td><td>4</td><td>3</td><td>95.8</td><td>8.78</td><td style="">-0.09</td><td></td><td>-0.81</td><td></td><td></td><td>-0.04</td><td>0.33</td><td></td><td>-0.71</td><td>-4.10</td><td>0.67</td><td>-0.04</td><td>-0.073</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.004</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14767">오장한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.027</td><td>1</td><td>1</td><td>8.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>2.25</td><td style="">-0.45</td><td>0.20</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.23</td><td>-11.28</td><td>-0.03</td><td>-0.26</td><td>-0.024</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.027</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14219">박주찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.032</td><td>3</td><td>3</td><td>24.0</td><td>5</td><td>1</td><td>3</td><td>1</td><td>80.0</td><td>1.50</td><td style="">-0.36</td><td></td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>-0.31</td><td>-8.90</td><td>0.00</td><td>-0.31</td><td>-0.032</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.032</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10261">손아섭</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.035</td><td>9</td><td>9</td><td>66.1</td><td>16</td><td>16</td><td>0</td><td>0</td><td>100.0</td><td>2.17</td><td style="">-0.43</td><td>0.30</td><td>0.12</td><td></td><td></td><td></td><td></td><td></td><td>-0.01</td><td>-0.02</td><td>-0.33</td><td>-0.34</td><td>-0.002</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.035</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14877">조현진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.064</td><td>7</td><td>0</td><td>13.0</td><td>5</td><td>1</td><td>4</td><td>0</td><td>100.0</td><td>3.46</td><td style="">-0.58</td><td></td><td>0.03</td><td>-0.14</td><td></td><td></td><td></td><td></td><td>-0.69</td><td>-9.95</td><td>0.06</td><td>-0.63</td><td>-0.070</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.064</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13087">최보성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.072</td><td>6</td><td>3</td><td>27.0</td><td>6</td><td>1</td><td>4</td><td>1</td><td>83.3</td><td>1.67</td><td style="">-0.77</td><td></td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>-0.71</td><td>-8.50</td><td>0.00</td><td>-0.71</td><td>-0.072</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.072</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13250">한석현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.089</td><td>9</td><td>7</td><td>68.2</td><td>26</td><td>24</td><td>0</td><td>2</td><td>92.3</td><td>3.15</td><td style="">0.26</td><td>-0.23</td><td>-0.90</td><td></td><td></td><td></td><td></td><td></td><td>-0.87</td><td>-4.66</td><td>0.00</td><td>-0.87</td><td>-0.089</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.089</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13087">최보성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.090</td><td>4</td><td>1</td><td>13.0</td><td>11</td><td>11</td><td>0</td><td>0</td><td>100.0</td><td>7.62</td><td style="">-0.81</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.78</td><td>-9.40</td><td>-0.10</td><td>-0.88</td><td>-0.080</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.090</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10322">박석민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.093</td><td>2</td><td>2</td><td>8.0</td><td>9</td><td>8</td><td>0</td><td>1</td><td>88.9</td><td>9.00</td><td style="">-0.81</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.79</td><td>-3.80</td><td>-0.12</td><td>-0.91</td><td>-0.081</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.093</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14219">박주찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.097</td><td>3</td><td>0</td><td>11.0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>5.73</td><td style="">-0.89</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.87</td><td>-24.95</td><td>-0.08</td><td>-0.95</td><td>-0.088</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.097</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14221">최정원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.120</td><td>12</td><td>4</td><td>43.1</td><td>10</td><td>10</td><td>0</td><td>0</td><td>100.0</td><td>2.08</td><td style="">-1.35</td><td>0.12</td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>-1.18</td><td>-4.36</td><td>0.00</td><td>-1.18</td><td>-0.120</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.120</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12903">김수윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.138</td><td>9</td><td>3</td><td>29.0</td><td>11</td><td>7</td><td>3</td><td>1</td><td>90.9</td><td>3.10</td><td style="">-1.20</td><td></td><td>0.07</td><td>-0.22</td><td></td><td></td><td></td><td></td><td>-1.35</td><td>-12.14</td><td>0.00</td><td>-1.35</td><td>-0.138</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.138</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11135">윤형준</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.150</td><td>74</td><td>57</td><td>476.0</td><td>470</td><td>431</td><td>35</td><td>4</td><td>99.1</td><td>8.81</td><td style="">3.63</td><td></td><td>-0.62</td><td></td><td>-0.16</td><td></td><td></td><td></td><td>2.85</td><td>5.01</td><td>-4.32</td><td>-1.47</td><td>0.291</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.150</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10189">박건우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.152</td><td>6</td><td>5</td><td>41.2</td><td>14</td><td>14</td><td>0</td><td>0</td><td>100.0</td><td>3.02</td><td style="">-0.78</td><td>-0.76</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>-1.49</td><td>-1.65</td><td>0.00</td><td>-1.49</td><td>-0.152</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.152</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14716">김한별</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.159</td><td>4</td><td>0</td><td>7.2</td><td>3</td><td>2</td><td>0</td><td>1</td><td>66.7</td><td>2.35</td><td style="">-1.58</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-1.56</td><td>-2.84</td><td>0.00</td><td>-1.56</td><td>-0.159</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.159</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14766">오태양</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.188</td><td>5</td><td>0</td><td>5.0</td><td>3</td><td>0</td><td>2</td><td>1</td><td>66.7</td><td>3.60</td><td style="">-1.37</td><td></td><td>-0.48</td><td></td><td></td><td></td><td></td><td></td><td>-1.85</td><td>-12.70</td><td>0.01</td><td>-1.84</td><td>-0.189</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.188</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15537">마틴</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.219</td><td>84</td><td>83</td><td>681.2</td><td>189</td><td>187</td><td>0</td><td>2</td><td>98.9</td><td>2.47</td><td style="">-2.87</td><td>0.84</td><td>-0.12</td><td></td><td></td><td></td><td></td><td></td><td>-2.15</td><td>-2.62</td><td>0.00</td><td>-2.15</td><td>-0.219</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.219</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13082">오영수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.243</td><td>66</td><td>61</td><td>482.0</td><td>450</td><td>417</td><td>25</td><td>8</td><td>98.2</td><td>8.25</td><td style="">2.37</td><td></td><td>-0.12</td><td></td><td>-0.06</td><td></td><td></td><td></td><td>2.20</td><td>4.52</td><td>-4.58</td><td>-2.38</td><td>0.224</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.243</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13261">천재환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.263</td><td>30</td><td>4</td><td>85.1</td><td>15</td><td>14</td><td>1</td><td>0</td><td>100.0</td><td>1.58</td><td style="">-1.68</td><td>-0.75</td><td>0.16</td><td></td><td></td><td></td><td></td><td></td><td>-2.27</td><td>-4.19</td><td>-0.31</td><td>-2.58</td><td>-0.231</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.263</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11153">김성욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.288</td><td>26</td><td>17</td><td>154.1</td><td>38</td><td>38</td><td>0</td><td>0</td><td>100.0</td><td>2.22</td><td style="">-3.13</td><td>0.11</td><td>0.20</td><td></td><td></td><td></td><td></td><td></td><td>-2.82</td><td>-4.37</td><td>0.00</td><td>-2.82</td><td>-0.288</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.288</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10322">박석민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.290</td><td>23</td><td>21</td><td>156.0</td><td>35</td><td>11</td><td>22</td><td>2</td><td>94.3</td><td>1.90</td><td style="">-2.49</td><td></td><td>-0.13</td><td>-0.22</td><td></td><td></td><td></td><td></td><td>-2.84</td><td>-13.65</td><td>0.00</td><td>-2.84</td><td>-0.290</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.290</td></tr><tr><td style="text-align:center;">52</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10189">박건우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.453</td><td>87</td><td>87</td><td>686.0</td><td>136</td><td>133</td><td>3</td><td>0</td><td>100.0</td><td>1.78</td><td style="">-2.51</td><td>0.31</td><td>1.32</td><td></td><td></td><td></td><td></td><td></td><td>-0.87</td><td>-0.97</td><td>-3.57</td><td>-4.44</td><td>-0.089</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.453</td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11172">권희동</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.646</td><td>85</td><td>80</td><td>660.0</td><td>157</td><td>153</td><td>2</td><td>2</td><td>98.7</td><td>2.11</td><td style="">-2.57</td><td>-0.61</td><td>0.18</td><td></td><td></td><td></td><td></td><td></td><td>-3.00</td><td>-4.50</td><td>-3.33</td><td>-6.33</td><td>-0.306</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.646</td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14877">조현진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.19</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.20</td><td>2.83</td><td></td><td></td><td>0.020</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12560">도태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>2.0</td><td>2</td><td>1</td><td>1</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.13</td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td></td><td></td><td>0.14</td><td>0.17</td><td></td><td></td><td>0.014</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14158">배민서</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>6</td><td>0</td><td>6.2</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>2.70</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td></td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13080">김시훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>60</td><td>0</td><td>52.2</td><td>8</td><td>1</td><td>6</td><td>1</td><td>87.5</td><td>1.20</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13250">한석현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11355">류진욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>70</td><td>0</td><td>67.0</td><td>16</td><td>2</td><td>14</td><td>0</td><td>100.0</td><td>2.15</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14764">한재승</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>10</td><td>0</td><td>9.2</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12903">김수윤</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>4</td><td>0</td><td>4.1</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>14.54</td><td style="">-0.20</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.19</td><td>-1.71</td><td></td><td></td><td>-0.019</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10217">이용찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>60</td><td>0</td><td>61.0</td><td>17</td><td>7</td><td>9</td><td>1</td><td>94.1</td><td>2.36</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11387">채지선</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>2.2</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>3.38</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14221">최정원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#002b69;color:#fff;">23</span> <span><img src="/data/team/ci/2023/11001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.34</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.34</td><td>1.25</td><td></td><td></td><td>0.034</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>
""")

In [69]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10165">양의지</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.361</td><td>97</td><td>94</td><td>773.0</td><td>686</td><td>635</td><td>48</td><td>3</td><td>99.6</td><td>7.95</td><td style="">0.14</td><td></td><td>1.50</td><td></td><td>-0.08</td><td>1.63</td><td>1.62</td><td></td><td>4.32</td><td>4.82</td><td>9.02</td><td>13.34</td><td>0.440</td><td style="background-color:#F3F3F3; font-weight:bold;">1.361</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10174">김재호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">1.007</td><td>86</td><td>71</td><td>611.1</td><td>294</td><td>119</td><td>166</td><td>9</td><td>96.9</td><td>4.20</td><td style="">3.96</td><td></td><td>-0.05</td><td>0.13</td><td></td><td></td><td></td><td></td><td>4.05</td><td>6.41</td><td>5.82</td><td>9.87</td><td>0.413</td><td style="background-color:#F3F3F3; font-weight:bold;">1.007</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10184">허경민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.499</td><td>126</td><td>116</td><td>997.2</td><td>250</td><td>90</td><td>155</td><td>5</td><td>98.0</td><td>2.21</td><td style="">3.33</td><td></td><td>1.81</td><td>-0.43</td><td>0.18</td><td></td><td></td><td></td><td>4.90</td><td>5.42</td><td>0.00</td><td>4.90</td><td>0.499</td><td style="background-color:#F3F3F3; font-weight:bold;">0.499</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12522">박준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.473</td><td>20</td><td>13</td><td>114.1</td><td>67</td><td>21</td><td>44</td><td>2</td><td>97.0</td><td>5.12</td><td style="">2.73</td><td></td><td>-0.23</td><td>1.22</td><td></td><td></td><td></td><td></td><td>3.72</td><td>10.51</td><td>0.92</td><td>4.64</td><td>0.380</td><td style="background-color:#F3F3F3; font-weight:bold;">0.473</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10195">정수빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.469</td><td>135</td><td>131</td><td>1111.0</td><td>326</td><td>318</td><td>8</td><td>0</td><td>100.0</td><td>2.64</td><td style="">2.32</td><td>0.86</td><td>1.41</td><td></td><td></td><td></td><td></td><td></td><td>4.60</td><td>4.83</td><td>0.00</td><td>4.60</td><td>0.469</td><td style="background-color:#F3F3F3; font-weight:bold;">0.469</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12894">이유찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.355</td><td>30</td><td>21</td><td>181.1</td><td>92</td><td>34</td><td>54</td><td>4</td><td>95.7</td><td>4.37</td><td style="">1.54</td><td></td><td>0.43</td><td>0.14</td><td></td><td></td><td></td><td></td><td>2.10</td><td>2.91</td><td>1.38</td><td>3.48</td><td>0.214</td><td style="background-color:#F3F3F3; font-weight:bold;">0.355</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12522">박준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.354</td><td>29</td><td>20</td><td>178.2</td><td>51</td><td>17</td><td>32</td><td>2</td><td>96.1</td><td>2.47</td><td style="">3.20</td><td></td><td>-0.08</td><td>0.26</td><td>0.09</td><td></td><td></td><td></td><td>3.47</td><td>9.80</td><td>0.00</td><td>3.47</td><td>0.354</td><td style="background-color:#F3F3F3; font-weight:bold;">0.354</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11087">강승호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.299</td><td>93</td><td>85</td><td>724.0</td><td>410</td><td>187</td><td>210</td><td>13</td><td>96.8</td><td>4.94</td><td style="">-0.91</td><td></td><td>-0.03</td><td>0.49</td><td></td><td></td><td></td><td></td><td>-0.45</td><td>-0.51</td><td>3.38</td><td>2.93</td><td>-0.046</td><td style="background-color:#F3F3F3; font-weight:bold;">0.299</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11097">장승현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.298</td><td>75</td><td>37</td><td>390.1</td><td>343</td><td>312</td><td>29</td><td>2</td><td>99.4</td><td>7.86</td><td style="">-0.86</td><td></td><td>0.51</td><td></td><td>-0.01</td><td>-0.32</td><td>-0.21</td><td></td><td>-0.82</td><td>-1.55</td><td>3.74</td><td>2.93</td><td>-0.083</td><td style="background-color:#F3F3F3; font-weight:bold;">0.298</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11198">박계범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.257</td><td>20</td><td>14</td><td>125.0</td><td>73</td><td>33</td><td>39</td><td>1</td><td>98.6</td><td>5.18</td><td style="">2.36</td><td></td><td>-0.16</td><td>-0.23</td><td></td><td></td><td></td><td></td><td>1.98</td><td>3.65</td><td>0.54</td><td>2.52</td><td>0.201</td><td style="background-color:#F3F3F3; font-weight:bold;">0.257</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14771">안재석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.233</td><td>13</td><td>10</td><td>88.0</td><td>53</td><td>19</td><td>33</td><td>1</td><td>98.1</td><td>5.32</td><td style="">0.24</td><td></td><td>0.21</td><td>1.02</td><td></td><td></td><td></td><td></td><td>1.47</td><td>7.83</td><td>0.82</td><td>2.29</td><td>0.150</td><td style="background-color:#F3F3F3; font-weight:bold;">0.233</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12894">이유찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.204</td><td>67</td><td>41</td><td>394.0</td><td>242</td><td>107</td><td>123</td><td>12</td><td>95.0</td><td>5.25</td><td style="">3.25</td><td></td><td>-2.90</td><td>0.02</td><td></td><td></td><td></td><td></td><td>0.37</td><td>0.51</td><td>1.63</td><td>2.00</td><td>0.038</td><td style="background-color:#F3F3F3; font-weight:bold;">0.204</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14172">송승환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.157</td><td>14</td><td>12</td><td>97.0</td><td>32</td><td>31</td><td>1</td><td>0</td><td>100.0</td><td>2.97</td><td style="">1.44</td><td>0.37</td><td>0.17</td><td></td><td></td><td></td><td></td><td></td><td>1.99</td><td>9.54</td><td>-0.45</td><td>1.54</td><td>0.203</td><td style="background-color:#F3F3F3; font-weight:bold;">0.157</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11098">김인태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.153</td><td>10</td><td>6</td><td>58.0</td><td>17</td><td>17</td><td>0</td><td>0</td><td>100.0</td><td>2.64</td><td style="">0.96</td><td>0.71</td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>1.77</td><td>5.43</td><td>-0.27</td><td>1.50</td><td>0.181</td><td style="background-color:#F3F3F3; font-weight:bold;">0.153</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12524">조수행</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.144</td><td>61</td><td>34</td><td>316.1</td><td>76</td><td>72</td><td>2</td><td>2</td><td>97.4</td><td>2.11</td><td style="">1.90</td><td>1.27</td><td>-0.38</td><td></td><td></td><td></td><td></td><td></td><td>2.80</td><td>3.20</td><td>-1.38</td><td>1.42</td><td>0.285</td><td style="background-color:#F3F3F3; font-weight:bold;">0.144</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12524">조수행</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.128</td><td>48</td><td>3</td><td>113.2</td><td>33</td><td>33</td><td>0</td><td>0</td><td>100.0</td><td>2.61</td><td style="">1.19</td><td>0.19</td><td>0.20</td><td></td><td></td><td></td><td></td><td></td><td>1.58</td><td>1.81</td><td>-0.33</td><td>1.25</td><td>0.162</td><td style="background-color:#F3F3F3; font-weight:bold;">0.128</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12524">조수행</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.052</td><td>35</td><td>12</td><td>150.2</td><td>54</td><td>54</td><td>0</td><td>0</td><td>100.0</td><td>3.23</td><td style="">0.48</td><td>-0.15</td><td>0.19</td><td></td><td></td><td></td><td></td><td></td><td>0.51</td><td>0.59</td><td>0.00</td><td>0.51</td><td>0.052</td><td style="background-color:#F3F3F3; font-weight:bold;">0.052</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12894">이유찬</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.049</td><td>3</td><td>0</td><td>7.0</td><td>6</td><td>2</td><td>4</td><td>0</td><td>100.0</td><td>7.71</td><td style="">0.10</td><td></td><td>0.02</td><td>0.36</td><td></td><td></td><td></td><td></td><td>0.48</td><td>0.67</td><td>0.00</td><td>0.48</td><td>0.049</td><td style="background-color:#F3F3F3; font-weight:bold;">0.049</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12606">홍성호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.047</td><td>1</td><td>0</td><td>3.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">0.50</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>0.50</td><td>3.46</td><td>-0.04</td><td>0.46</td><td>0.051</td><td style="background-color:#F3F3F3; font-weight:bold;">0.047</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14771">안재석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.045</td><td>4</td><td>2</td><td>21.0</td><td>8</td><td>4</td><td>4</td><td>0</td><td>100.0</td><td>3.43</td><td style="">0.32</td><td></td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>0.37</td><td>1.99</td><td>0.07</td><td>0.44</td><td>0.038</td><td style="background-color:#F3F3F3; font-weight:bold;">0.045</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14738">양찬열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.045</td><td>6</td><td>0</td><td>10.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>1.80</td><td style="">0.59</td><td>-0.14</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.47</td><td>1.54</td><td>-0.03</td><td>0.44</td><td>0.048</td><td style="background-color:#F3F3F3; font-weight:bold;">0.045</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11148">강진성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.037</td><td>2</td><td>0</td><td>2.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>18.00</td><td style="">0.40</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.40</td><td>1.00</td><td>-0.04</td><td>0.36</td><td>0.041</td><td style="background-color:#F3F3F3; font-weight:bold;">0.037</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12970">김민혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.024</td><td>12</td><td>5</td><td>56.0</td><td>57</td><td>52</td><td>4</td><td>1</td><td>98.2</td><td>9.00</td><td style="">1.02</td><td></td><td>-0.39</td><td></td><td>0.06</td><td></td><td></td><td></td><td>0.69</td><td>4.73</td><td>-0.46</td><td>0.23</td><td>0.070</td><td style="background-color:#F3F3F3; font-weight:bold;">0.024</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14771">안재석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.021</td><td>6</td><td>3</td><td>30.0</td><td>9</td><td>4</td><td>5</td><td>0</td><td>100.0</td><td>2.70</td><td style="">0.13</td><td></td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>0.20</td><td>1.08</td><td>0.00</td><td>0.20</td><td>0.021</td><td style="background-color:#F3F3F3; font-weight:bold;">0.021</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12523">서예일</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.015</td><td>2</td><td>0</td><td>8.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>2.25</td><td style="">0.13</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.15</td><td>4.32</td><td>0.00</td><td>0.15</td><td>0.015</td><td style="background-color:#F3F3F3; font-weight:bold;">0.015</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14738">양찬열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.008</td><td>34</td><td>22</td><td>212.2</td><td>53</td><td>50</td><td>3</td><td>0</td><td>100.0</td><td>2.24</td><td style="">0.58</td><td>-0.01</td><td>0.41</td><td></td><td></td><td></td><td></td><td></td><td>0.98</td><td>3.20</td><td>-0.90</td><td>0.08</td><td>0.100</td><td style="background-color:#F3F3F3; font-weight:bold;">0.008</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11492">신성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.006</td><td>5</td><td>1</td><td>17.1</td><td>15</td><td>14</td><td>1</td><td>0</td><td>100.0</td><td>7.79</td><td style="">0.15</td><td></td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>0.18</td><td>2.15</td><td>-0.12</td><td>0.06</td><td>0.018</td><td style="background-color:#F3F3F3; font-weight:bold;">0.006</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13073">전민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.005</td><td>2</td><td>0</td><td>3.2</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>2.45</td><td style="">0.00</td><td></td><td>0.01</td><td></td><td>0.06</td><td></td><td></td><td></td><td>0.07</td><td>0.51</td><td>-0.02</td><td>0.05</td><td>0.007</td><td style="background-color:#F3F3F3; font-weight:bold;">0.005</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13073">전민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.002</td><td>3</td><td>0</td><td>3.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.03</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.03</td><td>-0.19</td><td>0.01</td><td>-0.02</td><td>-0.003</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.002</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14736">박지훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.013</td><td>12</td><td>3</td><td>41.2</td><td>37</td><td>36</td><td>1</td><td>0</td><td>100.0</td><td>7.99</td><td style="">0.10</td><td></td><td>0.08</td><td></td><td></td><td></td><td></td><td></td><td>0.18</td><td>1.15</td><td>-0.30</td><td>-0.12</td><td>0.018</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.013</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14175">김태근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.019</td><td>19</td><td>8</td><td>103.1</td><td>23</td><td>21</td><td>2</td><td>0</td><td>100.0</td><td>2.00</td><td style="">-0.66</td><td>0.68</td><td>0.20</td><td></td><td></td><td></td><td></td><td></td><td>0.22</td><td>0.76</td><td>-0.40</td><td>-0.18</td><td>0.022</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.019</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14736">박지훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.020</td><td>3</td><td>1</td><td>6.1</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>1.42</td><td style="">-0.21</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.20</td><td>-1.30</td><td>0.00</td><td>-0.20</td><td>-0.020</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.020</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13073">전민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.022</td><td>3</td><td>2</td><td>16.0</td><td>10</td><td>7</td><td>3</td><td>0</td><td>100.0</td><td>5.63</td><td style="">-0.71</td><td></td><td>0.04</td><td>0.35</td><td></td><td></td><td></td><td></td><td>-0.32</td><td>-2.41</td><td>0.10</td><td>-0.22</td><td>-0.032</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.022</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12892">박유연</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.028</td><td>10</td><td>5</td><td>41.1</td><td>38</td><td>36</td><td>1</td><td>1</td><td>97.4</td><td>8.06</td><td style="">-0.09</td><td></td><td>-0.39</td><td></td><td>-0.01</td><td>0.32</td><td>-0.67</td><td></td><td>-0.64</td><td>-9.15</td><td>0.36</td><td>-0.28</td><td>-0.065</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.028</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11492">신성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.034</td><td>1</td><td>1</td><td>8.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>1.13</td><td style="">-0.43</td><td>0.12</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.30</td><td>-3.58</td><td>-0.03</td><td>-0.33</td><td>-0.030</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.034</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13079">권민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.034</td><td>1</td><td>0</td><td>2.1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.12</td><td></td><td>0.01</td><td>-0.26</td><td></td><td></td><td></td><td></td><td>-0.37</td><td>-53.73</td><td>0.04</td><td>-0.33</td><td>-0.038</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.034</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11198">박계범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.040</td><td>8</td><td>3</td><td>30.0</td><td>7</td><td>1</td><td>6</td><td>0</td><td>100.0</td><td>2.10</td><td style="">-0.27</td><td></td><td>0.07</td><td>-0.19</td><td></td><td></td><td></td><td></td><td>-0.39</td><td>-0.72</td><td>0.00</td><td>-0.39</td><td>-0.040</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.040</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12523">서예일</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.042</td><td>2</td><td>2</td><td>13.0</td><td>7</td><td>2</td><td>4</td><td>1</td><td>85.7</td><td>4.15</td><td style="">-0.51</td><td></td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-0.47</td><td>-13.61</td><td>0.06</td><td>-0.41</td><td>-0.048</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.042</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14175">김태근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.056</td><td>6</td><td>1</td><td>15.0</td><td>8</td><td>7</td><td>0</td><td>1</td><td>87.5</td><td>4.20</td><td style="">-0.12</td><td>0.05</td><td>-0.48</td><td></td><td></td><td></td><td></td><td></td><td>-0.55</td><td>-1.94</td><td>0.00</td><td>-0.55</td><td>-0.056</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.056</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14170">김대한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.064</td><td>1</td><td>0</td><td>6.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-0.58</td><td>-0.06</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.63</td><td>-2.75</td><td>0.00</td><td>-0.63</td><td>-0.064</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.064</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14172">송승환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.066</td><td>8</td><td>6</td><td>44.1</td><td>9</td><td>9</td><td>0</td><td>0</td><td>100.0</td><td>1.83</td><td style="">-0.18</td><td>-0.32</td><td>0.09</td><td></td><td></td><td></td><td></td><td></td><td>-0.41</td><td>-1.98</td><td>-0.23</td><td>-0.64</td><td>-0.042</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.066</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14736">박지훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.070</td><td>2</td><td>0</td><td>4.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.45</td><td></td><td>0.01</td><td>-0.26</td><td></td><td></td><td></td><td></td><td>-0.71</td><td>-4.63</td><td>0.02</td><td>-0.69</td><td>-0.072</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.070</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12522">박준영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.089</td><td>1</td><td>0</td><td>3.0</td><td>2</td><td>1</td><td>1</td><td>0</td><td>100.0</td><td>6.00</td><td style="">-0.62</td><td></td><td>0.01</td><td>-0.28</td><td></td><td></td><td></td><td></td><td>-0.89</td><td>-2.52</td><td>0.02</td><td>-0.87</td><td>-0.091</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.089</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10174">김재호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.094</td><td>1</td><td>0</td><td>2.0</td><td>2</td><td>0</td><td>1</td><td>1</td><td>50.0</td><td>4.50</td><td style="">-0.43</td><td></td><td>-0.49</td><td></td><td></td><td></td><td></td><td></td><td>-0.93</td><td>-1.46</td><td>0.00</td><td>-0.93</td><td>-0.094</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.094</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12606">홍성호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.096</td><td>3</td><td>3</td><td>22.0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>2.86</td><td style="">-0.17</td><td>-0.71</td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>-0.84</td><td>-5.77</td><td>-0.10</td><td>-0.94</td><td>-0.086</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.096</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11087">강승호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.101</td><td>42</td><td>24</td><td>240.1</td><td>229</td><td>209</td><td>17</td><td>3</td><td>98.7</td><td>8.46</td><td style="">1.14</td><td></td><td>-0.06</td><td></td><td>0.06</td><td></td><td></td><td></td><td>1.15</td><td>1.30</td><td>-2.14</td><td>-0.99</td><td>0.117</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.101</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13073">전민재</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.116</td><td>9</td><td>1</td><td>25.0</td><td>4</td><td>1</td><td>3</td><td>0</td><td>100.0</td><td>1.44</td><td style="">-1.20</td><td></td><td>0.06</td><td></td><td></td><td></td><td></td><td></td><td>-1.14</td><td>-8.62</td><td>0.00</td><td>-1.14</td><td>-0.116</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.116</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11198">박계범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.189</td><td>48</td><td>27</td><td>267.1</td><td>121</td><td>38</td><td>75</td><td>8</td><td>93.4</td><td>3.80</td><td style="">-1.01</td><td></td><td>-0.86</td><td>-2.34</td><td></td><td></td><td></td><td></td><td>-4.21</td><td>-7.77</td><td>2.36</td><td>-1.85</td><td>-0.429</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.189</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11328">안승한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.256</td><td>21</td><td>8</td><td>80.0</td><td>57</td><td>52</td><td>3</td><td>2</td><td>96.5</td><td>6.19</td><td style="">-0.15</td><td></td><td>-0.78</td><td></td><td>-0.01</td><td>-1.63</td><td>-0.73</td><td></td><td>-3.08</td><td>-20.17</td><td>0.58</td><td>-2.51</td><td>-0.314</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.256</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11098">김인태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.289</td><td>20</td><td>15</td><td>126.0</td><td>29</td><td>28</td><td>0</td><td>1</td><td>96.6</td><td>2.00</td><td style="">-2.11</td><td>0.13</td><td>-0.25</td><td></td><td></td><td></td><td></td><td></td><td>-2.23</td><td>-6.85</td><td>-0.60</td><td>-2.83</td><td>-0.228</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.289</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14175">김태근</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.345</td><td>13</td><td>2</td><td>36.0</td><td>9</td><td>6</td><td>0</td><td>3</td><td>66.7</td><td>1.50</td><td style="">-1.61</td><td>-0.25</td><td>-1.42</td><td></td><td></td><td></td><td></td><td></td><td>-3.29</td><td>-11.55</td><td>-0.09</td><td>-3.38</td><td>-0.335</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.345</td></tr><tr><td style="text-align:center;">52</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12606">홍성호</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.385</td><td>10</td><td>7</td><td>61.0</td><td>10</td><td>9</td><td>0</td><td>1</td><td>90.0</td><td>1.33</td><td style="">-2.10</td><td>-1.00</td><td>-0.38</td><td></td><td></td><td></td><td></td><td></td><td>-3.48</td><td>-23.87</td><td>-0.29</td><td>-3.77</td><td>-0.355</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.385</td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15539">로하스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.495</td><td>31</td><td>30</td><td>230.0</td><td>50</td><td>47</td><td>1</td><td>2</td><td>96.0</td><td>1.88</td><td style="">-3.20</td><td>-0.45</td><td>-0.05</td><td></td><td></td><td></td><td></td><td></td><td>-3.70</td><td>-4.37</td><td>-1.15</td><td>-4.85</td><td>-0.377</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.495</td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11213">양석환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.519</td><td>111</td><td>111</td><td>920.2</td><td>859</td><td>785</td><td>64</td><td>10</td><td>98.8</td><td>8.30</td><td style="">4.03</td><td></td><td>0.18</td><td></td><td>-0.18</td><td></td><td></td><td></td><td>4.03</td><td>4.15</td><td>-9.12</td><td>-5.09</td><td>0.411</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.519</td></tr><tr><td style="text-align:center;">55</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10643">김재환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.590</td><td>58</td><td>55</td><td>440.0</td><td>118</td><td>114</td><td>3</td><td>1</td><td>99.2</td><td>2.39</td><td style="">-3.12</td><td>-0.70</td><td>0.29</td><td></td><td></td><td></td><td></td><td></td><td>-3.53</td><td>-3.85</td><td>-2.26</td><td>-5.79</td><td>-0.360</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.590</td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14170">김대한</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.647</td><td>30</td><td>21</td><td>183.0</td><td>37</td><td>33</td><td>1</td><td>3</td><td>91.9</td><td>1.67</td><td style="">-3.69</td><td>-0.70</td><td>-1.13</td><td></td><td></td><td></td><td></td><td></td><td>-5.52</td><td>-24.07</td><td>-0.83</td><td>-6.35</td><td>-0.563</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.647</td></tr><tr><td style="text-align:center;">57</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15539">로하스</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.654</td><td>69</td><td>63</td><td>508.0</td><td>115</td><td>112</td><td>3</td><td>0</td><td>100.0</td><td>2.04</td><td style="">-4.95</td><td>0.26</td><td>0.90</td><td></td><td></td><td></td><td></td><td></td><td>-3.79</td><td>-4.48</td><td>-2.62</td><td>-6.41</td><td>-0.387</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.654</td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13070">박신지</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>14</td><td>1</td><td>26.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10696">홍건희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>64</td><td>0</td><td>61.2</td><td>10</td><td>1</td><td>7</td><td>2</td><td>80.0</td><td>1.17</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14770">최승용</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>34</td><td>20</td><td>111.0</td><td>23</td><td>3</td><td>19</td><td>1</td><td>95.7</td><td>1.78</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13071">정철원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>67</td><td>0</td><td>72.2</td><td>17</td><td>6</td><td>9</td><td>2</td><td>88.2</td><td>1.86</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13124">김정우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>7</td><td>0</td><td>6.2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13079">권민석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.02</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.02</td><td>-2.83</td><td></td><td></td><td>-0.002</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11300">박정수</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>25</td><td>0</td><td>36.2</td><td>9</td><td>2</td><td>7</td><td>0</td><td>100.0</td><td>2.21</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12850">박치국</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>60</td><td>0</td><td>52.2</td><td>5</td><td>2</td><td>3</td><td>0</td><td>100.0</td><td>0.85</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13072">김민규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>6</td><td>1</td><td>8.1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td></td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11159">이형범</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>23</td><td>0</td><td>27.2</td><td>5</td><td>2</td><td>1</td><td>2</td><td>60.0</td><td>0.98</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11492">신성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#042071;color:#fff;">23</span> <span><img src="/data/team/ci/2023/6002.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>2.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>4.50</td><td style="">0.27</td><td>0.04</td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.31</td><td>3.75</td><td></td><td></td><td>0.032</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>
""")

In [70]:
team_tables.append("""<table>
			<tbody>
							<tr>
					<th rowspan="2">Rank</th>
					<th rowspan="2">Name</th>
					<th rowspan="2" style="width:8rem;min-width:8rem;">Team</th>
					<th class="align_center sorting no_border" so="WAAwithPOS" ob="ASC">Sort▼</th>
					<th rowspan="2" class="sorting" tooltip="Games Played, 출장" flow="down" so="G" ob="DESC">G</th><th rowspan="2" class="sorting" tooltip="Games Started, 선발" flow="down" so="GS" ob="DESC">GS</th><th rowspan="2" class="sorting" tooltip="Innings, 이닝" flow="down" so="IP" ob="DESC">IP</th><th rowspan="2" class="sorting" tooltip="Total Chances, 수비 기회 (자살+보살+실책)" flow="down" so="TC" ob="DESC">TC</th><th rowspan="2" class="sorting" tooltip="Putouts, 자살" flow="down" so="PO" ob="DESC">PO</th><th rowspan="2" class="sorting" tooltip="Assists, 보살" flow="down" so="Ass" ob="DESC">Ass</th><th rowspan="2" class="sorting" tooltip="Errors, 실책" flow="down" so="E" ob="DESC">E</th><th rowspan="2" class="sorting" tooltip="Fielding percentage, 수비율 (자살+보살)/(자살+보살+실책)" flow="down" so="Fp" ob="DESC">F%</th><th rowspan="2" class="sorting" tooltip="Range factor 9, 9이닝 당 레인지 팩터" flow="down" so="RF9" ob="DESC">RF9</th><th class="align_center no_border" colspan="10" flow="down" style="">수비 관련 득점 기여도</th><th rowspan="2" class="sorting" tooltip="Positional Adjustment, 포지션 조정" flow="down" so="POSAdj" ob="DESC">POSAdj</th><th rowspan="2" class="sorting" tooltip="Fielding Runs Above Average (with POSAdj), 평균 대비 수비 득점 기여 (포지션 조정 포함)" flow="down" so="RAAwithPOS" ob="DESC">RAAwithPOS</th><th rowspan="2" class="sorting" tooltip="Fielding Wins Above Avergae (without PosAdj), 평균 대비 수비 승리 기여 (포지션 조정 제외)" flow="down" so="WAAwoPOS" ob="DESC">WAAwoPOS</th><th rowspan="2" class="sorting align_center" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down" so="WAAwithPOS" ob="ASC">WAAwithPOS▼</th>				</tr>
				<tr>
					<th class="sorting" so="WAAwithPOS" ob="ASC"><div class="th_tit" tooltip="Fielding Runs Above Average (with PosAdj), \A 평균 대비 수비 승리 기여 (포지션 조정 포함)" flow="down">WAAwithPOS</div></th>
					<th class="sorting" tooltip="Fielding Runs (Range), 수비 범위 관련 득점 기여" flow="down" so="RAA_RangeAdj" ob="DESC" style=";">Range RAA</th><th class="sorting" tooltip="Fielding Runs (Arm), 외야 추가 진루/보살 관련 득점 기여" flow="down" so="RAA_ArmAdj" ob="DESC">Arm RAA</th><th class="sorting" tooltip="Fielding Runs (Error), 실책 관련 득점 기여" flow="down" so="RAA_ErrAdj" ob="DESC">Err RAA</th><th class="sorting" tooltip="Fielding Runs (Double Play), 병살 수비 관련 득점 기여" flow="down" so="RAA_DPAdj" ob="DESC">DP RAA</th><th class="sorting" tooltip="Fielding Runs (Bunt), 번트 수비 관련 득점 기여" flow="down" so="RAA_BTDAdj" ob="DESC">Bt RAA</th><th class="sorting" tooltip="Fielding Runs (CS), 도루 저지 관련 득점 기여" flow="down" so="RAA_CSAdj" ob="DESC">CS RAA</th><th class="sorting" tooltip="Fielding Runs (Blocking), 블로킹 관련 득점 기여" flow="down" so="RAA_BLKAdj" ob="DESC">Blk RAA</th><th class="sorting" tooltip="Fielding Runs (Framing), 프레이밍 관련 득점 기여" flow="down" so="RAA_FrmAdj" ob="DESC">Frm RAA</th><th class="sorting" tooltip="Fielding Runs Above Average, 평균 대비 수비 득점 기여" flow="down" so="RAA_FieldingAdj" ob="DESC">종합 RAA</th><th class="sorting" tooltip="Fielding Runs Above Average/144 Games, 평균 대비 수비 득점 기여 (144경기 기준)" flow="down" so="RAA_144" ob="DESC">/144</th>				</tr>
			<tr><td style="text-align:center;">1</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12905">김혜성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.832</td><td>126</td><td>124</td><td>1067.0</td><td>635</td><td>246</td><td>374</td><td>15</td><td>97.6</td><td>5.23</td><td style="">0.80</td><td></td><td>1.40</td><td>0.32</td><td></td><td></td><td></td><td></td><td>2.51</td><td>2.64</td><td>5.64</td><td>8.15</td><td>0.256</td><td style="background-color:#F3F3F3; font-weight:bold;">0.832</td></tr><tr><td style="text-align:center;">2</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12906">이정후</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.739</td><td>81</td><td>80</td><td>698.0</td><td>210</td><td>204</td><td>5</td><td>1</td><td>99.5</td><td>2.69</td><td style="">5.52</td><td>1.34</td><td>0.39</td><td></td><td></td><td></td><td></td><td></td><td>7.25</td><td>12.14</td><td>0.00</td><td>7.25</td><td>0.739</td><td style="background-color:#F3F3F3; font-weight:bold;">0.739</td></tr><tr><td style="text-align:center;">3</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10312">이지영</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.691</td><td>78</td><td>69</td><td>539.0</td><td>503</td><td>467</td><td>32</td><td>4</td><td>99.2</td><td>8.33</td><td style="">-0.26</td><td></td><td>-0.59</td><td></td><td>0.02</td><td>0.92</td><td>1.60</td><td></td><td>1.20</td><td>2.14</td><td>5.57</td><td>6.77</td><td>0.123</td><td style="background-color:#F3F3F3; font-weight:bold;">0.691</td></tr><tr><td style="text-align:center;">4</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15473">김동헌</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.457</td><td>100</td><td>48</td><td>522.0</td><td>424</td><td>377</td><td>43</td><td>4</td><td>99.1</td><td>7.24</td><td style="">-0.53</td><td></td><td>-0.14</td><td></td><td>-0.02</td><td>0.29</td><td>-0.96</td><td></td><td>-1.07</td><td>-1.50</td><td>5.54</td><td>4.48</td><td>-0.109</td><td style="background-color:#F3F3F3; font-weight:bold;">0.457</td></tr><tr><td style="text-align:center;">5</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15132">박수종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.388</td><td>14</td><td>11</td><td>102.2</td><td>36</td><td>35</td><td>1</td><td>0</td><td>100.0</td><td>3.16</td><td style="">3.77</td><td>0.33</td><td>0.20</td><td></td><td></td><td></td><td></td><td></td><td>4.29</td><td>26.88</td><td>-0.49</td><td>3.80</td><td>0.438</td><td style="background-color:#F3F3F3; font-weight:bold;">0.388</td></tr><tr><td style="text-align:center;">6</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11376">송성문</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.285</td><td>88</td><td>74</td><td>685.2</td><td>209</td><td>73</td><td>128</td><td>8</td><td>96.2</td><td>2.64</td><td style="">2.55</td><td></td><td>0.10</td><td>-0.19</td><td>0.33</td><td></td><td></td><td></td><td>2.80</td><td>3.87</td><td>0.00</td><td>2.80</td><td>0.285</td><td style="background-color:#F3F3F3; font-weight:bold;">0.285</td></tr><tr><td style="text-align:center;">7</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14851">김시앙</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.252</td><td>32</td><td>24</td><td>198.1</td><td>147</td><td>134</td><td>13</td><td>0</td><td>100.0</td><td>6.67</td><td style="">-0.06</td><td></td><td>0.51</td><td></td><td>-0.01</td><td>-0.64</td><td>0.99</td><td></td><td>0.51</td><td>2.20</td><td>1.97</td><td>2.47</td><td>0.052</td><td style="background-color:#F3F3F3; font-weight:bold;">0.252</td></tr><tr><td style="text-align:center;">8</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14742">러셀</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.220</td><td>51</td><td>49</td><td>407.2</td><td>184</td><td>68</td><td>113</td><td>3</td><td>98.4</td><td>4.00</td><td style="">-3.31</td><td></td><td>0.46</td><td>0.92</td><td></td><td></td><td></td><td></td><td>-1.93</td><td>-4.70</td><td>4.08</td><td>2.15</td><td>-0.196</td><td style="background-color:#F3F3F3; font-weight:bold;">0.220</td></tr><tr><td style="text-align:center;">9</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11244">김태진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.147</td><td>24</td><td>13</td><td>139.1</td><td>88</td><td>41</td><td>46</td><td>1</td><td>98.9</td><td>5.62</td><td style="">1.43</td><td></td><td>-0.12</td><td>-0.54</td><td></td><td></td><td></td><td></td><td>0.78</td><td>1.51</td><td>0.66</td><td>1.44</td><td>0.079</td><td style="background-color:#F3F3F3; font-weight:bold;">0.147</td></tr><tr><td style="text-align:center;">10</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11422">전병우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.125</td><td>6</td><td>0</td><td>9.0</td><td>3</td><td>0</td><td>3</td><td>0</td><td>100.0</td><td>3.00</td><td style="">0.83</td><td></td><td>0.02</td><td>0.37</td><td></td><td></td><td></td><td></td><td>1.22</td><td>4.29</td><td>0.00</td><td>1.22</td><td>0.125</td><td style="background-color:#F3F3F3; font-weight:bold;">0.125</td></tr><tr><td style="text-align:center;">11</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14785">김휘집</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.117</td><td>43</td><td>35</td><td>295.1</td><td>79</td><td>19</td><td>56</td><td>4</td><td>94.9</td><td>2.29</td><td style="">1.00</td><td></td><td>-0.31</td><td>0.37</td><td>0.08</td><td></td><td></td><td></td><td>1.14</td><td>1.50</td><td>0.00</td><td>1.14</td><td>0.117</td><td style="background-color:#F3F3F3; font-weight:bold;">0.117</td></tr><tr><td style="text-align:center;">12</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14133">주성원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.112</td><td>4</td><td>4</td><td>29.0</td><td>8</td><td>8</td><td>0</td><td>0</td><td>100.0</td><td>2.48</td><td style="">1.06</td><td>0.11</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>1.22</td><td>7.02</td><td>-0.12</td><td>1.10</td><td>0.124</td><td style="background-color:#F3F3F3; font-weight:bold;">0.112</td></tr><tr><td style="text-align:center;">13</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11226">임병욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.112</td><td>18</td><td>13</td><td>124.0</td><td>42</td><td>40</td><td>1</td><td>1</td><td>97.6</td><td>2.98</td><td style="">0.59</td><td>0.84</td><td>-0.34</td><td></td><td></td><td></td><td></td><td></td><td>1.10</td><td>1.97</td><td>0.00</td><td>1.10</td><td>0.112</td><td style="background-color:#F3F3F3; font-weight:bold;">0.112</td></tr><tr><td style="text-align:center;">14</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11182">김준완</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.102</td><td>44</td><td>31</td><td>281.1</td><td>71</td><td>69</td><td>2</td><td>0</td><td>100.0</td><td>2.27</td><td style="">1.76</td><td>0.09</td><td>0.50</td><td></td><td></td><td></td><td></td><td></td><td>2.34</td><td>4.44</td><td>-1.34</td><td>1.00</td><td>0.239</td><td style="background-color:#F3F3F3; font-weight:bold;">0.102</td></tr><tr><td style="text-align:center;">15</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14591">이주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.095</td><td>25</td><td>24</td><td>207.0</td><td>75</td><td>75</td><td>0</td><td>0</td><td>100.0</td><td>3.26</td><td style="">1.42</td><td>-0.76</td><td>0.26</td><td></td><td></td><td></td><td></td><td></td><td>0.93</td><td>1.94</td><td>0.00</td><td>0.93</td><td>0.095</td><td style="background-color:#F3F3F3; font-weight:bold;">0.095</td></tr><tr><td style="text-align:center;">16</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14580">박주홍</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.084</td><td>9</td><td>9</td><td>55.0</td><td>53</td><td>51</td><td>2</td><td>0</td><td>100.0</td><td>8.67</td><td style="">1.26</td><td></td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>1.36</td><td>7.25</td><td>-0.54</td><td>0.82</td><td>0.139</td><td style="background-color:#F3F3F3; font-weight:bold;">0.084</td></tr><tr><td style="text-align:center;">17</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14695">신준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.073</td><td>8</td><td>0</td><td>14.0</td><td>7</td><td>2</td><td>5</td><td>0</td><td>100.0</td><td>4.50</td><td style="">0.43</td><td></td><td>0.04</td><td>0.19</td><td></td><td></td><td></td><td></td><td>0.66</td><td>3.94</td><td>0.06</td><td>0.72</td><td>0.067</td><td style="background-color:#F3F3F3; font-weight:bold;">0.073</td></tr><tr><td style="text-align:center;">18</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14214">김주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.070</td><td>3</td><td>1</td><td>9.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>2.00</td><td style="">0.66</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.68</td><td>2.14</td><td>0.00</td><td>0.68</td><td>0.070</td><td style="background-color:#F3F3F3; font-weight:bold;">0.070</td></tr><tr><td style="text-align:center;">19</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12859">이병규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.040</td><td>4</td><td>3</td><td>24.0</td><td>23</td><td>22</td><td>1</td><td>0</td><td>100.0</td><td>8.63</td><td style="">0.57</td><td></td><td>0.04</td><td></td><td></td><td></td><td></td><td></td><td>0.62</td><td>12.67</td><td>-0.22</td><td>0.40</td><td>0.063</td><td style="background-color:#F3F3F3; font-weight:bold;">0.040</td></tr><tr><td style="text-align:center;">20</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14785">김휘집</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.039</td><td>74</td><td>64</td><td>578.0</td><td>273</td><td>102</td><td>157</td><td>14</td><td>94.9</td><td>4.03</td><td style="">-7.68</td><td></td><td>0.37</td><td>1.91</td><td></td><td></td><td></td><td></td><td>-5.40</td><td>-7.06</td><td>5.78</td><td>0.38</td><td>-0.550</td><td style="background-color:#F3F3F3; font-weight:bold;">0.039</td></tr><tr><td style="text-align:center;">21</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14577">김병휘</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.035</td><td>3</td><td>0</td><td>11.0</td><td>8</td><td>4</td><td>3</td><td>1</td><td>87.5</td><td>5.73</td><td style="">0.95</td><td></td><td>-0.47</td><td>-0.20</td><td></td><td></td><td></td><td></td><td>0.28</td><td>4.02</td><td>0.06</td><td>0.34</td><td>0.028</td><td style="background-color:#F3F3F3; font-weight:bold;">0.035</td></tr><tr><td style="text-align:center;">22</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11376">송성문</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.021</td><td>26</td><td>18</td><td>145.2</td><td>148</td><td>134</td><td>12</td><td>2</td><td>98.6</td><td>9.02</td><td style="">1.83</td><td></td><td>-0.23</td><td></td><td></td><td></td><td></td><td></td><td>1.60</td><td>2.22</td><td>-1.40</td><td>0.20</td><td>0.163</td><td style="background-color:#F3F3F3; font-weight:bold;">0.021</td></tr><tr><td style="text-align:center;">23</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15652">도슨</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.013</td><td>22</td><td>19</td><td>159.2</td><td>47</td><td>45</td><td>0</td><td>2</td><td>95.7</td><td>2.54</td><td style="">1.70</td><td>-0.04</td><td>-0.71</td><td></td><td></td><td></td><td></td><td></td><td>0.95</td><td>2.40</td><td>-0.82</td><td>0.13</td><td>0.097</td><td style="background-color:#F3F3F3; font-weight:bold;">0.013</td></tr><tr><td style="text-align:center;">24</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11182">김준완</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">0.004</td><td>5</td><td>1</td><td>16.0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>100.0</td><td>3.94</td><td style="">-0.40</td><td>0.41</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>0.04</td><td>0.07</td><td>0.00</td><td>0.04</td><td>0.004</td><td style="background-color:#F3F3F3; font-weight:bold;">0.004</td></tr><tr><td style="text-align:center;">25</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15068">박찬혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.002</td><td>27</td><td>24</td><td>203.0</td><td>52</td><td>50</td><td>1</td><td>1</td><td>98.1</td><td>2.26</td><td style="">0.57</td><td>0.06</td><td>0.36</td><td></td><td></td><td></td><td></td><td></td><td>0.98</td><td>2.95</td><td>-1.00</td><td>-0.02</td><td>0.100</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.002</td></tr><tr><td style="text-align:center;">26</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14580">박주홍</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.003</td><td>1</td><td>0</td><td>0.2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.03</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.03</td><td>-0.14</td><td>0.00</td><td>-0.03</td><td>-0.003</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.003</td></tr><tr><td style="text-align:center;">27</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14214">김주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.025</td><td>4</td><td>0</td><td>7.0</td><td>4</td><td>1</td><td>3</td><td>0</td><td>100.0</td><td>5.14</td><td style="">-0.29</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.27</td><td>-0.84</td><td>0.02</td><td>-0.25</td><td>-0.027</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.025</td></tr><tr><td style="text-align:center;">28</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14591">이주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.028</td><td>6</td><td>6</td><td>52.0</td><td>14</td><td>14</td><td>0</td><td>0</td><td>100.0</td><td>2.42</td><td style="">0.72</td><td>-0.81</td><td>0.10</td><td></td><td></td><td></td><td></td><td></td><td>0.01</td><td>0.03</td><td>-0.29</td><td>-0.28</td><td>0.001</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.028</td></tr><tr><td style="text-align:center;">29</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11244">김태진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.032</td><td>1</td><td>0</td><td>2.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>4.50</td><td style="">-0.30</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>-0.29</td><td>-0.57</td><td>-0.02</td><td>-0.31</td><td>-0.030</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.032</td></tr><tr><td style="text-align:center;">30</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14577">김병휘</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.046</td><td>7</td><td>6</td><td>44.1</td><td>20</td><td>10</td><td>10</td><td>0</td><td>100.0</td><td>4.06</td><td style="">-1.12</td><td></td><td>0.12</td><td>0.37</td><td></td><td></td><td></td><td></td><td>-0.63</td><td>-9.12</td><td>0.18</td><td>-0.45</td><td>-0.065</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.046</td></tr><tr><td style="text-align:center;">31</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15476">이승원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.069</td><td>4</td><td>2</td><td>11.0</td><td>6</td><td>2</td><td>3</td><td>1</td><td>83.3</td><td>4.09</td><td style="">-0.63</td><td></td><td>-0.47</td><td>0.36</td><td></td><td></td><td></td><td></td><td>-0.74</td><td>-26.66</td><td>0.06</td><td>-0.68</td><td>-0.076</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.069</td></tr><tr><td style="text-align:center;">32</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11260">박준태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.080</td><td>8</td><td>4</td><td>41.0</td><td>6</td><td>6</td><td>0</td><td>0</td><td>100.0</td><td>1.32</td><td style="">-0.52</td><td>-0.21</td><td>0.08</td><td></td><td></td><td></td><td></td><td></td><td>-0.65</td><td>-6.65</td><td>-0.14</td><td>-0.79</td><td>-0.066</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.080</td></tr><tr><td style="text-align:center;">33</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13093">예진원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.091</td><td>5</td><td>3</td><td>25.0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>100.0</td><td>1.80</td><td style="">-1.17</td><td>0.35</td><td>0.05</td><td></td><td></td><td></td><td></td><td></td><td>-0.78</td><td>-6.99</td><td>-0.12</td><td>-0.90</td><td>-0.079</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.091</td></tr><tr><td style="text-align:center;">34</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14591">이주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.094</td><td>1</td><td>1</td><td>9.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>2.00</td><td style="">-0.90</td><td></td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-0.88</td><td>-1.84</td><td>-0.04</td><td>-0.92</td><td>-0.090</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.094</td></tr><tr><td style="text-align:center;">35</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15132">박수종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.100</td><td>3</td><td>0</td><td>5.0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>100.0</td><td>3.60</td><td style="">-0.98</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.98</td><td>-6.12</td><td>0.00</td><td>-0.98</td><td>-0.100</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.100</td></tr><tr><td style="text-align:center;">36</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11225">임지열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.102</td><td>21</td><td>10</td><td>101.0</td><td>28</td><td>26</td><td>2</td><td>0</td><td>100.0</td><td>2.50</td><td style="">-1.76</td><td>1.07</td><td>0.18</td><td></td><td></td><td></td><td></td><td></td><td>-0.51</td><td>-1.03</td><td>-0.49</td><td>-1.00</td><td>-0.052</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.102</td></tr><tr><td style="text-align:center;">37</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15068">박찬혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.102</td><td>2</td><td>2</td><td>15.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>0.60</td><td style="">-0.98</td><td>0.01</td><td>0.03</td><td></td><td></td><td></td><td></td><td></td><td>-0.94</td><td>-2.83</td><td>-0.06</td><td>-1.00</td><td>-0.096</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.102</td></tr><tr><td style="text-align:center;">38</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15477">송재선</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.109</td><td>2</td><td>1</td><td>10.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.86</td><td>-0.21</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-1.04</td><td>-30.08</td><td>-0.02</td><td>-1.06</td><td>-0.107</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.109</td></tr><tr><td style="text-align:center;">39</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11226">임병욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.110</td><td>23</td><td>15</td><td>150.0</td><td>31</td><td>29</td><td>1</td><td>1</td><td>96.8</td><td>1.80</td><td style="">-0.16</td><td>-0.03</td><td>-0.23</td><td></td><td></td><td></td><td></td><td></td><td>-0.42</td><td>-0.75</td><td>-0.66</td><td>-1.08</td><td>-0.043</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.110</td></tr><tr><td style="text-align:center;">40</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10035">이용규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.111</td><td>4</td><td>2</td><td>12.0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>100.0</td><td>3.00</td><td style="">-0.28</td><td>-0.75</td><td>0.02</td><td></td><td></td><td></td><td></td><td></td><td>-1.01</td><td>-2.91</td><td>-0.08</td><td>-1.09</td><td>-0.103</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.111</td></tr><tr><td style="text-align:center;">41</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11260">박준태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.112</td><td>4</td><td>0</td><td>7.2</td><td>2</td><td>1</td><td>0</td><td>1</td><td>50.0</td><td>1.17</td><td style="">-0.55</td><td>-0.54</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-1.08</td><td>-11.15</td><td>-0.01</td><td>-1.09</td><td>-0.111</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.112</td></tr><tr><td style="text-align:center;">42</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13096">김수환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.113</td><td>4</td><td>1</td><td>7.2</td><td>2</td><td>0</td><td>1</td><td>1</td><td>50.0</td><td>1.17</td><td style="">-0.63</td><td></td><td>-0.48</td><td></td><td></td><td></td><td></td><td></td><td>-1.10</td><td>-3.18</td><td>0.00</td><td>-1.10</td><td>-0.113</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.113</td></tr><tr><td style="text-align:center;">43</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13093">예진원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.118</td><td>7</td><td>4</td><td>38.2</td><td>10</td><td>9</td><td>1</td><td>0</td><td>100.0</td><td>2.33</td><td style="">-1.27</td><td>0.22</td><td>0.07</td><td></td><td></td><td></td><td></td><td></td><td>-0.98</td><td>-8.85</td><td>-0.17</td><td>-1.15</td><td>-0.100</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.118</td></tr><tr><td style="text-align:center;">44</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11376">송성문</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>2B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.122</td><td>6</td><td>1</td><td>16.2</td><td>5</td><td>4</td><td>1</td><td>0</td><td>100.0</td><td>2.70</td><td style="">-0.98</td><td></td><td>0.04</td><td>-0.33</td><td></td><td></td><td></td><td></td><td>-1.27</td><td>-1.76</td><td>0.07</td><td>-1.20</td><td>-0.129</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.122</td></tr><tr><td style="text-align:center;">45</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14133">주성원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.128</td><td>17</td><td>16</td><td>115.0</td><td>30</td><td>27</td><td>2</td><td>1</td><td>96.7</td><td>2.27</td><td style="">0.34</td><td>-0.78</td><td>-0.27</td><td></td><td></td><td></td><td></td><td></td><td>-0.71</td><td>-4.07</td><td>-0.55</td><td>-1.26</td><td>-0.072</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.128</td></tr><tr><td style="text-align:center;">46</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11422">전병우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.147</td><td>32</td><td>11</td><td>143.0</td><td>153</td><td>144</td><td>7</td><td>2</td><td>98.7</td><td>9.50</td><td style="">-0.52</td><td></td><td>0.26</td><td></td><td>0.06</td><td></td><td></td><td></td><td>-0.20</td><td>-0.70</td><td>-1.24</td><td>-1.44</td><td>-0.020</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.147</td></tr><tr><td style="text-align:center;">47</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10870">김재현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>C</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.152</td><td>8</td><td>3</td><td>29.0</td><td>16</td><td>16</td><td>0</td><td>0</td><td>100.0</td><td>4.97</td><td style="">-0.09</td><td></td><td>0.07</td><td></td><td></td><td>-0.57</td><td>-1.64</td><td></td><td>-1.73</td><td>-31.20</td><td>0.24</td><td>-1.49</td><td>-0.177</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.152</td></tr><tr><td style="text-align:center;">48</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15472">김건희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.173</td><td>7</td><td>3</td><td>28.1</td><td>26</td><td>22</td><td>3</td><td>1</td><td>96.2</td><td>7.94</td><td style="">-1.03</td><td></td><td>-0.44</td><td></td><td></td><td></td><td></td><td></td><td>-1.48</td><td>-23.64</td><td>-0.22</td><td>-1.70</td><td>-0.151</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.173</td></tr><tr><td style="text-align:center;">49</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13093">예진원</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.182</td><td>3</td><td>0</td><td>5.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-1.47</td><td>-0.32</td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-1.79</td><td>-16.07</td><td>0.00</td><td>-1.79</td><td>-0.182</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.182</td></tr><tr><td style="text-align:center;">50</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12905">김혜성</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.184</td><td>5</td><td>5</td><td>37.1</td><td>26</td><td>12</td><td>12</td><td>2</td><td>92.3</td><td>5.79</td><td style="">-1.58</td><td></td><td>0.09</td><td>-0.73</td><td></td><td></td><td></td><td></td><td>-2.23</td><td>-2.34</td><td>0.42</td><td>-1.81</td><td>-0.227</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.184</td></tr><tr><td style="text-align:center;">51</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11182">김준완</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.191</td><td>23</td><td>12</td><td>116.2</td><td>26</td><td>25</td><td>1</td><td>0</td><td>100.0</td><td>2.01</td><td style="">-2.03</td><td>0.47</td><td>0.22</td><td></td><td></td><td></td><td></td><td></td><td>-1.33</td><td>-2.52</td><td>-0.54</td><td>-1.87</td><td>-0.136</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.191</td></tr><tr><td style="text-align:center;">52</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11244">김태진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.197</td><td>1</td><td>1</td><td>8.0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0.0</td><td>0.00</td><td style="">-1.41</td><td></td><td>-0.48</td><td></td><td></td><td></td><td></td><td></td><td>-1.89</td><td>-3.68</td><td>-0.04</td><td>-1.93</td><td>-0.193</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.197</td></tr><tr><td style="text-align:center;">53</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14214">김주형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.210</td><td>35</td><td>20</td><td>206.1</td><td>86</td><td>19</td><td>65</td><td>2</td><td>97.7</td><td>3.66</td><td style="">-1.18</td><td></td><td>-0.01</td><td>-2.35</td><td></td><td></td><td></td><td></td><td>-3.54</td><td>-11.07</td><td>1.48</td><td>-2.06</td><td>-0.361</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.210</td></tr><tr><td style="text-align:center;">54</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10180">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.221</td><td>6</td><td>5</td><td>47.2</td><td>12</td><td>6</td><td>5</td><td>1</td><td>91.7</td><td>2.08</td><td style="">-1.78</td><td></td><td>-0.38</td><td></td><td></td><td></td><td></td><td></td><td>-2.17</td><td>-3.51</td><td>0.00</td><td>-2.17</td><td>-0.221</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.221</td></tr><tr><td style="text-align:center;">55</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14695">신준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>SS</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.231</td><td>14</td><td>4</td><td>37.0</td><td>24</td><td>9</td><td>13</td><td>2</td><td>91.7</td><td>5.35</td><td style="">-2.17</td><td></td><td>-0.41</td><td>0.09</td><td></td><td></td><td></td><td></td><td>-2.49</td><td>-14.92</td><td>0.22</td><td>-2.27</td><td>-0.254</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.231</td></tr><tr><td style="text-align:center;">56</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10035">이용규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.237</td><td>33</td><td>28</td><td>244.2</td><td>49</td><td>49</td><td>0</td><td>0</td><td>100.0</td><td>1.80</td><td style="">-1.66</td><td>0.15</td><td>0.43</td><td></td><td></td><td></td><td></td><td></td><td>-1.08</td><td>-3.11</td><td>-1.24</td><td>-2.32</td><td>-0.110</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.237</td></tr><tr><td style="text-align:center;">57</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13096">김수환</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.238</td><td>39</td><td>24</td><td>214.2</td><td>203</td><td>194</td><td>9</td><td>0</td><td>100.0</td><td>8.51</td><td style="">-1.03</td><td></td><td>0.39</td><td></td><td>0.25</td><td></td><td></td><td></td><td>-0.39</td><td>-1.14</td><td>-1.94</td><td>-2.33</td><td>-0.040</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.238</td></tr><tr><td style="text-align:center;">58</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12503">김웅빈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.241</td><td>13</td><td>9</td><td>73.2</td><td>76</td><td>68</td><td>6</td><td>2</td><td>97.4</td><td>9.04</td><td style="">-1.66</td><td></td><td>0.13</td><td></td><td>-0.16</td><td></td><td></td><td></td><td>-1.68</td><td>-8.35</td><td>-0.68</td><td>-2.36</td><td>-0.171</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.241</td></tr><tr><td style="text-align:center;">59</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14580">박주홍</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.241</td><td>10</td><td>7</td><td>51.0</td><td>10</td><td>10</td><td>0</td><td>0</td><td>100.0</td><td>1.76</td><td style="">-2.55</td><td>0.30</td><td>0.09</td><td></td><td></td><td></td><td></td><td></td><td>-2.15</td><td>-11.48</td><td>-0.21</td><td>-2.36</td><td>-0.219</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.241</td></tr><tr><td style="text-align:center;">60</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11244">김태진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.243</td><td>37</td><td>28</td><td>233.0</td><td>72</td><td>28</td><td>38</td><td>6</td><td>91.7</td><td>2.55</td><td style="">-2.41</td><td></td><td>0.04</td><td>-0.56</td><td>0.54</td><td></td><td></td><td></td><td>-2.38</td><td>-4.63</td><td>0.00</td><td>-2.38</td><td>-0.243</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.243</td></tr><tr><td style="text-align:center;">61</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11225">임지열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.263</td><td>7</td><td>6</td><td>46.1</td><td>9</td><td>9</td><td>0</td><td>0</td><td>100.0</td><td>1.75</td><td style="">-2.22</td><td>-0.21</td><td>0.09</td><td></td><td></td><td></td><td></td><td></td><td>-2.34</td><td>-4.67</td><td>-0.24</td><td>-2.58</td><td>-0.238</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.263</td></tr><tr><td style="text-align:center;">62</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11226">임병욱</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.287</td><td>27</td><td>20</td><td>180.0</td><td>46</td><td>45</td><td>0</td><td>1</td><td>97.8</td><td>2.25</td><td style="">-2.03</td><td>0.17</td><td>-0.15</td><td></td><td></td><td></td><td></td><td></td><td>-2.00</td><td>-3.60</td><td>-0.81</td><td>-2.81</td><td>-0.204</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.287</td></tr><tr><td style="text-align:center;">63</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11225">임지열</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.467</td><td>43</td><td>30</td><td>278.2</td><td>281</td><td>255</td><td>20</td><td>6</td><td>97.9</td><td>8.88</td><td style="">-0.62</td><td></td><td>-0.98</td><td></td><td>-0.28</td><td></td><td></td><td></td><td>-1.88</td><td>-3.76</td><td>-2.70</td><td>-4.58</td><td>-0.192</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.467</td></tr><tr><td style="text-align:center;">64</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12516">이형종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.575</td><td>77</td><td>61</td><td>571.2</td><td>123</td><td>117</td><td>4</td><td>2</td><td>98.4</td><td>1.90</td><td style="">-3.42</td><td>0.52</td><td>0.11</td><td></td><td></td><td></td><td></td><td></td><td>-2.79</td><td>-4.05</td><td>-2.85</td><td>-5.64</td><td>-0.284</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.575</td></tr><tr><td style="text-align:center;">65</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10180">이원석</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>1B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.629</td><td>42</td><td>37</td><td>323.1</td><td>332</td><td>299</td><td>26</td><td>7</td><td>97.9</td><td>9.05</td><td style="">-3.18</td><td></td><td>0.09</td><td></td><td>0.08</td><td></td><td></td><td></td><td>-3.01</td><td>-4.87</td><td>-3.16</td><td>-6.17</td><td>-0.307</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.629</td></tr><tr><td style="text-align:center;">66</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15652">도슨</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;">-0.640</td><td>26</td><td>26</td><td>230.2</td><td>59</td><td>57</td><td>0</td><td>2</td><td>96.6</td><td>2.22</td><td style="">-5.10</td><td>-0.48</td><td>-0.70</td><td></td><td></td><td></td><td></td><td></td><td>-6.28</td><td>-15.86</td><td>0.00</td><td>-6.28</td><td>-0.640</td><td style="background-color:#F3F3F3; font-weight:bold;">-0.640</td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15132">박수종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>4</td><td>0</td><td>3.1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">-0.09</td><td></td><td>0.01</td><td></td><td></td><td></td><td></td><td></td><td>-0.09</td><td>-0.54</td><td></td><td></td><td>-0.009</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15477">송재선</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>100.0</td><td>9.00</td><td style="">0.20</td><td>0.01</td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.21</td><td>6.08</td><td></td><td></td><td>0.022</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11161">원종현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>20</td><td>0</td><td>18.2</td><td>4</td><td>2</td><td>2</td><td>0</td><td>100.0</td><td>1.93</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11260">박준태</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>CF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12859">이병규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>RF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.04</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14674">김동혁</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>35</td><td>2</td><td>39.1</td><td>8</td><td>1</td><td>6</td><td>1</td><td>87.5</td><td>1.60</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14849">김성진</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>55</td><td>0</td><td>47.0</td><td>7</td><td>1</td><td>5</td><td>1</td><td>85.7</td><td>1.15</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15472">김건희</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15531">후라도</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>30</td><td>30</td><td>183.2</td><td>50</td><td>13</td><td>37</td><td>0</td><td>100.0</td><td>2.45</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10437">문성현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>31</td><td>0</td><td>28.1</td><td>5</td><td>2</td><td>3</td><td>0</td><td>100.0</td><td>1.59</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=12858">김재웅</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>66</td><td>0</td><td>59.2</td><td>9</td><td>1</td><td>8</td><td>0</td><td>100.0</td><td>1.36</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10452">임창민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>51</td><td>0</td><td>46.2</td><td>4</td><td>2</td><td>2</td><td>0</td><td>100.0</td><td>0.77</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=11222">하영민</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>57</td><td>0</td><td>52.1</td><td>15</td><td>1</td><td>11</td><td>3</td><td>80.0</td><td>2.06</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=13092">김선기</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>17</td><td>7</td><td>43.2</td><td>14</td><td>3</td><td>9</td><td>2</td><td>85.7</td><td>2.47</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15073">이명종</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>45</td><td>2</td><td>57.0</td><td>10</td><td>2</td><td>8</td><td>0</td><td>100.0</td><td>1.58</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15477">송재선</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>LF</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>2</td><td>0</td><td>2.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.10</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10871">김태훈</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>8</td><td>0</td><td>7.2</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>1.17</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14848">김준형</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>7</td><td>0</td><td>7.2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=15485">김동규</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>3</td><td>1</td><td>4.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14131">윤정현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>4</td><td>0</td><td>6.0</td><td>1</td><td>0</td><td>1</td><td>0</td><td>100.0</td><td>1.50</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=14695">신준우</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>3B</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>1</td><td>0</td><td>1.0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.0</td><td>0.00</td><td style="">0.00</td><td></td><td>0.00</td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>-0.01</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr><tr><td style="text-align:center;">67</td><td style="text-align:left;"><div><a href="/player/?m=playerinfo&amp;p_no=10730">양현</a></div></td><td style="text-align:left;"><div class="teams"><span style="background:#86001f;color:#fff;">23</span> <span><img src="/data/team/ci/2023/10001.svg" style="width:20px;"></span> <span>P</span></div></td><td style="font-weight:bold;background-color:#F3F3F3;"><span></span></td><td>54</td><td>0</td><td>57.0</td><td>14</td><td>3</td><td>11</td><td>0</td><td>100.0</td><td>2.21</td><td style=""></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.00</td><td>0.00</td><td></td><td></td><td>0.000</td><td style="background-color:#F3F3F3; font-weight:bold;"></td></tr>			</tbody>
		</table>
""")

In [71]:
len(team_tables)

10

In [73]:
fielding = pd.DataFrame()
for i in range(len(team_tables)):
    name = team_names[i]
    team = team_tables[i]
    print(name)
    df, pids = get_team_stats_from_markup(StringIO(str(team)))
    df['팀'] = name
    df['pid'] = pids[2:]
    print(df.shape)
    print(len(pids))
    fielding = pd.concat([fielding, df])
    display(fielding.tail())
fielding.describe()

한화 이글스
(72, 29)
74

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team      Sort▼   G  GS     IP  TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G  GS     IP  TC PO Ass  ...      Blk RAA
67   63  이태양   23 P        NaN  50  12  100.1  19  6  13  ...          NaN
68   63   김건  23 3B        NaN   1   0    1.0   0  0   0  ...          NaN
69   63  박준영   23 P        NaN   4   0    4.1   1  0   1  ...          NaN
70   63  김서현   23 P        NaN  20   1   22.1   4  0   4  ...          NaN
71   63  강재민   23 P        NaN  43   0   43.1   5  0   5  ...          NaN

                        POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼       팀    pid
   Frm RAA 종합 RAA  /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
67     NaN   0.00  0.00    NaN        NaN    0.000         NaN  한화 이글스  10609
68     NaN  -0.01 -0.25    NaN        NaN   -0.001         NaN  한화 이글스  14209
69     NaN   0.00  0.00    NaN        NaN    0.000         NaN  한화 이글스  15014
70     NaN   0.00  0.00    NaN        NaN    0.000         NaN  한화 이글스  15421
71     NaN   0.00   NaN    NaN        NaN    0.000         NaN  한화 이글스  14708

[5 rows x 29 columns]

LG 트윈스
(61, 29)
63

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name  Team      Sort▼   G  GS    IP  TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name  Team WAAwithPOS   G  GS    IP  TC PO Ass  ...      Blk RAA
56   51  박명근  23 P        NaN  55   1  51.1   6  2   4  ...          NaN
57   51  최동환  23 P        NaN  43   0  42.1   6  1   5  ...          NaN
58   51  채지선  23 P        NaN   1   0   0.2   0  0   0  ...          NaN
59   51  오석주  23 P        NaN   9   0  10.0   0  0   0  ...          NaN
60   51  이정용  23 P        NaN  37  13  86.2  12  3   8  ...          NaN

                       POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼       팀    pid
   Frm RAA 종합 RAA /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
56     NaN    0.0  0.0    NaN        NaN      0.0         NaN  LG 트윈스  15486
57     NaN    0.0  0.0    NaN        NaN      0.0         NaN  LG 트윈스  10535
58     NaN    0.0  0.0    NaN        NaN      0.0         NaN  LG 트윈스  11387
59     NaN    0.0  0.0    NaN        NaN      0.0         NaN  LG 트윈스  12860
60     NaN    0.0  0.0    NaN        NaN      0.0         NaN  LG 트윈스  14134

[5 rows x 29 columns]

롯데 자이언츠
(64, 29)
66

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team      Sort▼   G GS    IP  TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G GS    IP  TC PO Ass  ...      Blk RAA
59   59  장두성  23 LF        NaN   6  0   7.0   2  2   0  ...          NaN
60   59  김상수   23 P        NaN  65  0  52.0   8  2   5  ...          NaN
61   59  최영환   23 P        NaN   8  0  10.0   4  1   3  ...          NaN
62   59  김동혁  23 CF        NaN   2  0   2.0   0  0   0  ...          NaN
63   59  김원중   23 P        NaN  63  0  63.2  11  4   7  ...          NaN

                        POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼        팀    pid
   Frm RAA 종합 RAA  /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
59     NaN   0.87  5.00    NaN        NaN    0.089         NaN  롯데 자이언츠  13155
60     NaN   0.00  0.00    NaN        NaN    0.000         NaN  롯데 자이언츠  10427
61     NaN   0.00  0.00    NaN        NaN    0.000         NaN  롯데 자이언츠  11276
62     NaN   0.00  0.02    NaN        NaN    0.000         NaN  롯데 자이언츠  15645
63     NaN   0.00  0.00    NaN        NaN    0.000         NaN  롯데 자이언츠  10825

[5 rows x 29 columns]

KIA 타이거즈
(57, 29)
59

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team      Sort▼   G GS    IP TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G GS    IP TC PO Ass  ...      Blk RAA
52   48  최정용  23 SS        NaN   1  0   1.0  1  0   1  ...          NaN
53   48  박정우  23 CF        NaN   1  0   2.0  1  1   0  ...          NaN
54   48  김기훈   23 P        NaN  27  0  31.1  2  0   2  ...          NaN
55   48  김선빈  23 SS        NaN   2  0   2.0  0  0   0  ...          NaN
56   48  홍종표  23 3B        NaN   3  0   5.0  3  1   2  ...          NaN

                        POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼         팀  \
   Frm RAA 종합 RAA  /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
52     NaN   0.33  0.84    NaN        NaN    0.033         NaN  KIA 타이거즈
53     NaN   0.65  4.45    NaN        NaN    0.066         NaN  KIA 타이거즈
54     NaN   0.00  0.00    NaN        NaN    0.000         NaN  KIA 타이거즈
55     NaN   0.00  0.00    NaN        NaN    0.000         NaN  KIA 타이거즈
56     NaN   0.52  1.88    NaN        NaN    0.053         NaN  KIA 타이거즈

      pid

52  11407
53  12869
54  14176
55  10008
56  14612

[5 rows x 29 columns]

KT 위즈

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(80, 29)
82

   Rank Name  Team      Sort▼   G GS    IP  TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name  Team WAAwithPOS   G GS    IP  TC PO Ass  ...      Blk RAA
75   68  이채호  23 P        NaN  21  0  24.2   4  3   0  ...          NaN
76   68  이상동  23 P        NaN  36  0  40.2   6  2   4  ...          NaN
77   68  김재윤  23 P        NaN  59  0  65.2  13  5   7  ...          NaN
78   68  이선우  23 P        NaN  22  4  37.1   6  1   5  ...          NaN
79   68  박영현  23 P        NaN  67  0  75.1  12  5   7  ...          NaN

                       POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼      팀    pid
   Frm RAA 종합 RAA /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
75     NaN    0.0  0.0    NaN        NaN      0.0         NaN  KT 위즈  13130
76     NaN    0.0  0.0    NaN        NaN      0.0         NaN  KT 위즈  14109
77     NaN    0.0  0.0    NaN        NaN      0.0         NaN  KT 위즈  11489
78     NaN    0.0  0.0    NaN        NaN      0.0         NaN  KT 위즈  14111
79     NaN    0.0  0.0    NaN        NaN      0.0         NaN  KT 위즈  15089

[5 rows x 29 columns]

삼성 라이온즈

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(81, 29)
83

   Rank Name   Team      Sort▼   G GS    IP  TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G GS    IP  TC PO Ass  ...      Blk RAA
76   73  김헌곤  23 LF        NaN   4  0   4.0   0  0   0  ...          NaN
77   73  이재익   23 P        NaN  49  0  41.0   9  3   5  ...          NaN
78   73  김태훈   23 P        NaN  63  0  55.2  17  4  13  ...          NaN
79   73  이해승  23 2B        NaN   1  0   1.0   2  1   1  ...          NaN
80   73  김서준   23 P        NaN   8  1   7.2   0  0   0  ...          NaN

                         POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼        팀  \
   Frm RAA 종합 RAA   /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
76     NaN  -0.99 -23.72    NaN        NaN   -0.101         NaN  삼성 라이온즈
77     NaN   0.00   0.00    NaN        NaN    0.000         NaN  삼성 라이온즈
78     NaN   0.00   0.00    NaN        NaN    0.000         NaN  삼성 라이온즈
79     NaN   0.00   0.04    NaN        NaN    0.000         NaN  삼성 라이온즈
80     NaN   0.00   0.00    NaN        NaN    0.000         NaN  삼성 라이온즈

      pid

76  10640
77  13244
78  10871
79  14121
80  15039

[5 rows x 29 columns]

SSG 랜더스
(63, 29)
65

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team      Sort▼   G GS    IP  TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G GS    IP  TC PO Ass  ...      Blk RAA
58   53  최민준   23 P        NaN  52  0  60.0   9  3   6  ...          NaN
59   53  백승건   23 P        NaN  24  2  38.0   6  0   5  ...          NaN
60   53  노경은   23 P        NaN  74  0  83.0  15  6   8  ...          NaN
61   53  임준섭   23 P        NaN  39  0  32.2   3  1   2  ...          NaN
62   53  김정민  23 LF        NaN   1  0   1.0   0  0   0  ...          NaN

                        POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼        팀    pid
   Frm RAA 종합 RAA  /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
58     NaN   0.00  0.00    NaN        NaN    0.000         NaN  SSG 랜더스  13126
59     NaN   0.00  0.00    NaN        NaN    0.000         NaN  SSG 랜더스  14145
60     NaN   0.00  0.00    NaN        NaN    0.000         NaN  SSG 랜더스  10203
61     NaN   0.00  0.00    NaN        NaN    0.000         NaN  SSG 랜더스  10795
62     NaN  -0.26 -4.69    NaN        NaN   -0.027         NaN  SSG 랜더스  15463

[5 rows x 29 columns]

NC 다이노스
(64, 29)
66

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team      Sort▼   G GS    IP  TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G GS    IP  TC PO Ass  ...      Blk RAA
59   54  한재승   23 P        NaN  10  0   9.2   1  0   0  ...          NaN
60   54  김수윤  23 1B        NaN   4  0   4.1   7  7   0  ...          NaN
61   54  이용찬   23 P        NaN  60  0  61.0  17  7   9  ...          NaN
62   54  채지선   23 P        NaN   2  0   2.2   1  1   0  ...          NaN
63   54  최정원  23 LF        NaN   1  0   1.0   1  1   0  ...          NaN

                        POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼        팀    pid
   Frm RAA 종합 RAA  /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
59     NaN   0.00  0.00    NaN        NaN    0.000         NaN  NC 다이노스  14764
60     NaN  -0.19 -1.71    NaN        NaN   -0.019         NaN  NC 다이노스  12903
61     NaN   0.00  0.00    NaN        NaN    0.000         NaN  NC 다이노스  10217
62     NaN   0.00  0.00    NaN        NaN    0.000         NaN  NC 다이노스  11387
63     NaN   0.34  1.25    NaN        NaN    0.034         NaN  NC 다이노스  14221

[5 rows x 29 columns]

두산 베어스
(68, 29)
70

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team      Sort▼   G GS    IP TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G GS    IP TC PO Ass  ...      Blk RAA
63   58  박정수   23 P        NaN  25  0  36.2  9  2   7  ...          NaN
64   58  박치국   23 P        NaN  60  0  52.2  5  2   3  ...          NaN
65   58  김민규   23 P        NaN   6  1   8.1  0  0   0  ...          NaN
66   58  이형범   23 P        NaN  23  0  27.2  5  2   1  ...          NaN
67   58  신성현  23 CF        NaN   1  0   2.0  1  1   0  ...          NaN

                        POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼       팀    pid
   Frm RAA 종합 RAA  /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
63     NaN   0.00  0.00    NaN        NaN    0.000         NaN  두산 베어스  11300
64     NaN   0.00  0.00    NaN        NaN    0.000         NaN  두산 베어스  12850
65     NaN   0.00   NaN    NaN        NaN    0.000         NaN  두산 베어스  13072
66     NaN   0.00  0.00    NaN        NaN    0.000         NaN  두산 베어스  11159
67     NaN   0.31  3.75    NaN        NaN    0.032         NaN  두산 베어스  11492

[5 rows x 29 columns]

키움 히어로즈
(88, 29)
90

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

   Rank Name   Team      Sort▼   G GS    IP  TC PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G GS    IP  TC PO Ass  ...      Blk RAA
83   67  김준형   23 P        NaN   7  0   7.2   0  0   0  ...          NaN
84   67  김동규   23 P        NaN   3  1   4.0   0  0   0  ...          NaN
85   67  윤정현   23 P        NaN   4  0   6.0   1  0   1  ...          NaN
86   67  신준우  23 3B        NaN   1  0   1.0   0  0   0  ...          NaN
87   67   양현   23 P        NaN  54  0  57.0  14  3  11  ...          NaN

                        POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼        팀    pid
   Frm RAA 종합 RAA  /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
83     NaN    0.0  0.00    NaN        NaN      0.0         NaN  키움 히어로즈  14848
84     NaN    0.0  0.00    NaN        NaN      0.0         NaN  키움 히어로즈  15485
85     NaN    0.0  0.00    NaN        NaN      0.0         NaN  키움 히어로즈  14131
86     NaN    0.0 -0.01    NaN        NaN      0.0         NaN  키움 히어로즈  14695
87     NaN    0.0  0.00    NaN        NaN      0.0         NaN  키움 히어로즈  10730

[5 rows x 29 columns]

             Rank       Sort▼           G          GS           IP  \
             Rank  WAAwithPOS           G          GS           IP
count  698.000000  584.000000  698.000000  698.000000   698.000000
mean    35.101719    0.007426   27.032951   16.686246   151.669771
std     19.897289    0.303594   31.198173   28.256417   238.108800
min      1.000000   -1.172000    1.000000    0.000000     0.100000
25%     18.000000   -0.122000    4.000000    0.000000    11.000000
50%     35.000000   -0.012500   14.000000    3.500000    46.600000
75%     51.000000    0.097250   40.000000   20.000000   180.775000
max     73.000000    1.623000  142.000000  136.000000  1187.200000

               TC          PO         Ass           E          F%  ...  \
               TC          PO         Ass           E          F%  ...
count  698.000000  698.000000  698.000000  698.000000  698.000000  ...
mean    73.902579   54.550143   17.911175    1.441261   88.814040  ...
std    140.182518  114.531450   48.286931    2.992121   27.390047  ...
min      0.000000    0.000000    0.000000    0.000000    0.000000  ...
25%      4.000000    2.000000    0.000000    0.000000   94.900000  ...
50%     16.000000   10.000000    2.000000    0.000000   99.400000  ...
75%     68.500000   47.000000   10.000000    2.000000  100.000000  ...
max    917.000000  831.000000  374.000000   29.000000  100.000000  ...

      수비 관련 득점 기여도                                                        \
            Bt RAA     CS RAA    Blk RAA Frm RAA      종합 RAA        /144
count   108.000000  43.000000  45.000000     0.0  698.000000  694.000000
mean     -0.000556   0.000465   0.000222     NaN   -0.029943   -1.134553
std       0.254653   1.021821   1.413843     NaN    1.876328    9.067234
min      -0.790000  -2.810000  -3.930000     NaN   -7.290000  -90.310000
25%      -0.080000  -0.600000  -0.730000     NaN   -0.947500   -3.077500
50%       0.060000  -0.040000   0.080000     NaN    0.000000    0.000000
75%       0.100000   0.590000   0.990000     NaN    0.735000    2.227500
max       0.640000   1.900000   2.720000     NaN    9.020000   63.010000

           POSAdj  RAAwithPOS    WAAwoPOS WAAwithPOS▼
           POSAdj  RAAwithPOS    WAAwoPOS WAAwithPOS▼
count  584.000000  584.000000  698.000000  584.000000
mean     0.112295    0.072671   -0.003042    0.007426
std      2.127840    2.976377    0.191353    0.303594
min     -9.680000  -11.490000   -0.743000   -1.172000
25%     -0.242500   -1.200000   -0.096750   -0.122000
50%      0.000000   -0.120000    0.000000   -0.012500
75%      0.040000    0.952500    0.075500    0.097250
max     11.090000   15.910000    0.920000    1.623000

[8 rows x 25 columns]

In [74]:
fielding.to_csv("2023_수비_statiz.csv", index=False)

In [75]:
team_table = []

In [76]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=11215">채은성</a></td><td>180,000</td><td>2.36</td><td>76,221</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10170">최재훈</a></td><td>80,000</td><td>3.90</td><td>20,492</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15540">스미스</a></td><td>70,000</td><td>0.09</td><td>756,875</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15541">오그레디</a></td><td>70,000</td><td>-0.87</td><td>-80,365</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10609">이태양</a></td><td>66,000</td><td>1.44</td><td>45,702</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15146">페냐</a></td><td>55,000</td><td>4.20</td><td>13,083</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10156">정우람</a></td><td>50,000</td><td>0.26</td><td>193,563</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15643">산체스</a></td><td>40,000</td><td>2.51</td><td>15,960</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10453">장시환</a></td><td>28,000</td><td>0.52</td><td>53,948</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15647">윌리엄스</a></td><td>25,000</td><td>-0.81</td><td>-30,701</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11410">김민우</a></td><td>22,800</td><td>-0.46</td><td>-49,756</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13137">정은원</a></td><td>21,800</td><td>1.03</td><td>21,251</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14708">강재민</a></td><td>15,000</td><td>-0.64</td><td>-23,513</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11411">김범수</a></td><td>14,100</td><td>0.17</td><td>84,338</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12871">박상원</a></td><td>13,300</td><td>-0.18</td><td>-75,459</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14125">노시환</a></td><td>13,100</td><td>6.82</td><td>1,920</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10610">장민재</a></td><td>11,500</td><td>0.05</td><td>223,567</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11268">노수광</a></td><td>10,900</td><td>-0.12</td><td>-88,193</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10557">오선진</a></td><td>10,000</td><td>0.02</td><td>472,498</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10913">하주석</a></td><td>10,000</td><td>-0.58</td><td>-17,260</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11110">윤대경</a></td><td>9,000</td><td>1.08</td><td>8,310</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11117">김종수</a></td><td>8,900</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12589">김인환</a></td><td>6,400</td><td>0.23</td><td>27,855</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10812">한승혁</a></td><td>6,200</td><td>-0.26</td><td>-23,712</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12583">장진혁</a></td><td>6,000</td><td>-0.44</td><td>-13,624</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12585">김태연</a></td><td>6,000</td><td>1.41</td><td>4,268</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11415">주현상</a></td><td>5,800</td><td>2.21</td><td>2,621</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12547">김재영</a></td><td>5,300</td><td>-0.14</td><td>-38,416</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13003">이민우</a></td><td>5,100</td><td>0.16</td><td>32,490</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10119">이명기</a></td><td>5,000</td><td>-0.29</td><td>-17,008</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11122">장운호</a></td><td>5,000</td><td>-0.08</td><td>-63,382</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11206">이성곤</a></td><td>4,800</td><td>-0.20</td><td>-24,185</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14196">윤산흠</a></td><td>4,800</td><td>-0.14</td><td>-34,278</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14619">남지민</a></td><td>4,300</td><td>-0.14</td><td>-31,683</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14704">박정현</a></td><td>4,200</td><td>-0.33</td><td>-12,799</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12539">이진영</a></td><td>3,900</td><td>3.60</td><td>1,083</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14707">최인호</a></td><td>3,800</td><td>1.49</td><td>2,545</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12587">박상언</a></td><td>3,600</td><td>-0.30</td><td>-12,106</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14808">김기중</a></td><td>3,600</td><td>0.67</td><td>5,394</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10748">송윤준</a></td><td>3,500</td><td>-0.04</td><td>-99,340</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13251">류원석</a></td><td>3,500</td><td>0.02</td><td>198,876</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11414">이도윤</a></td><td>3,400</td><td>2.27</td><td>1,501</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14129">박윤철</a></td><td>3,400</td><td>-0.09</td><td>-39,271</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12655">류희운</a></td><td>3,300</td><td>-0.06</td><td>-59,419</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13138">이원석</a></td><td>3,300</td><td>0.25</td><td>12,947</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14126">유로결</a></td><td>3,300</td><td>-0.45</td><td>-7,413</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14204">허관회</a></td><td>3,300</td><td>-0.27</td><td>-12,371</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15013">문동주</a></td><td>3,300</td><td>2.96</td><td>1,115</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15141">유상빈</a></td><td>3,300</td><td>-0.03</td><td>-127,240</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11116">이충호</a></td><td>3,200</td><td>-0.10</td><td>-32,240</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14178">장지수</a></td><td>3,200</td><td>-0.05</td><td>-58,276</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14880">장지승</a></td><td>3,200</td><td>-0.06</td><td>-53,377</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12872">원혁재</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12902">이재용</a></td><td>3,100</td><td>0.04</td><td>76,581</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13135">이승관</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13676">권광민</a></td><td>3,100</td><td>-1.03</td><td>-2,999</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14209">김건</a></td><td>3,100</td><td>-0.35</td><td>-8,914</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14620">신지후</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14621">한승주</a></td><td>3,100</td><td>0.57</td><td>5,440</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14813">정민규</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14871">김규연</a></td><td>3,100</td><td>0.46</td><td>6,801</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15014">박준영</a></td><td>3,100</td><td>-0.08</td><td>-37,897</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15020">이재민</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13140">이성원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13141">김민기</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14127">정이황</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14166">김현우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14710">김범준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14835">오세훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14876">안진</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15017">양경모</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15018">김겸재</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15022">노석진</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15137">민승기</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15139">이상혁</a></td><td>3,000</td><td>-0.16</td><td>-18,204</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15421">김서현</a></td><td>3,000</td><td>-0.24</td><td>-12,563</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15422">문현빈</a></td><td>3,000</td><td>1.87</td><td>1,606</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15423">이민준</a></td><td>3,000</td><td>0.05</td><td>63,253</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15424">김관우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15425">김해찬</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15426">한서구</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15427">송성훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15428">최원준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15429">박재규</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15430">천보웅</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15431">김예준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15628">이정재</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15629">고영재</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15630">이석제</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15631">성지훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15632">김석훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15633">한경빈</a></td><td>3,000</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [77]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=13934">켈리</a></td><td>105,000</td><td>3.41</td><td>30,748</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10187">김현수</a></td><td>100,000</td><td>2.19</td><td>45,737</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15003">플럿코</a></td><td>80,000</td><td>4.58</td><td>17,476</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10475">오지환</a></td><td>60,000</td><td>5.14</td><td>11,668</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11190">박해민</a></td><td>60,000</td><td>4.80</td><td>12,494</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12907">고우석</a></td><td>43,000</td><td>0.53</td><td>81,646</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14136">정우영</a></td><td>40,000</td><td>-0.74</td><td>-54,168</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15532">오스틴</a></td><td>40,000</td><td>5.74</td><td>6,973</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11379">최원태</a></td><td>35,000</td><td>3.20</td><td>10,921</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10387">박동원</a></td><td>30,000</td><td>2.92</td><td>10,290</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12546">홍창기</a></td><td>30,000</td><td>7.91</td><td>3,793</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10075">진해수</a></td><td>25,000</td><td>-0.01</td><td>-3,024,251</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14134">이정용</a></td><td>24,000</td><td>0.87</td><td>27,693</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10855">서건창</a></td><td>20,000</td><td>-0.53</td><td>-37,703</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11166">김진성</a></td><td>20,000</td><td>2.03</td><td>9,842</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10238">김민성</a></td><td>18,000</td><td>1.92</td><td>9,358</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10652">임찬규</a></td><td>17,000</td><td>3.40</td><td>4,999</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14137">문보경</a></td><td>17,000</td><td>4.45</td><td>3,822</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14588">김윤식</a></td><td>15,000</td><td>1.48</td><td>10,148</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10137">송은범</a></td><td>14,000</td><td>0.04</td><td>390,910</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14589">이민호</a></td><td>14,000</td><td>-0.01</td><td>-2,750,156</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10851">최성훈</a></td><td>13,000</td><td>-0.18</td><td>-73,985</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10749">이우찬</a></td><td>12,000</td><td>0.78</td><td>15,421</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10535">최동환</a></td><td>10,500</td><td>0.52</td><td>20,064</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10684">허도환</a></td><td>10,000</td><td>-0.58</td><td>-17,113</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11094">함덕주</a></td><td>10,000</td><td>2.35</td><td>4,250</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11229">김유영</a></td><td>9,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13112">문성주</a></td><td>9,500</td><td>4.76</td><td>1,995</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11170">윤호솔</a></td><td>8,700</td><td>0.04</td><td>248,452</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13104">이재원</a></td><td>8,500</td><td>0.15</td><td>57,852</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10935">이천웅</a></td><td>8,000</td><td>0.14</td><td>57,237</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12697">배재준</a></td><td>7,500</td><td>-0.02</td><td>-316,248</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10480">정주현</a></td><td>6,500</td><td>-0.81</td><td>-7,997</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12532">김대현</a></td><td>6,200</td><td>-0.08</td><td>-73,558</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11347">안익훈</a></td><td>5,100</td><td>0.12</td><td>41,979</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14135">이상영</a></td><td>5,000</td><td>0.11</td><td>46,617</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13056">신민재</a></td><td>4,800</td><td>1.43</td><td>3,365</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14590">손호영</a></td><td>4,700</td><td>-0.53</td><td>-8,895</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13009">백승현</a></td><td>4,600</td><td>2.02</td><td>2,279</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12908">손주영</a></td><td>4,100</td><td>-0.08</td><td>-50,109</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10713">임정우</a></td><td>4,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13109">송찬의</a></td><td>4,000</td><td>-0.32</td><td>-12,647</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13102">김영준</a></td><td>3,800</td><td>-0.01</td><td>-595,577</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12860">오석주</a></td><td>3,700</td><td>-0.02</td><td>-151,073</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13245">이상규</a></td><td>3,600</td><td>0.19</td><td>18,571</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14143">이지강</a></td><td>3,600</td><td>0.17</td><td>21,420</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12549">김기연</a></td><td>3,500</td><td>-0.73</td><td>-4,780</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14846">송승기</a></td><td>3,500</td><td>0.04</td><td>88,615</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12545">김주성</a></td><td>3,400</td><td>-0.09</td><td>-35,979</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11351">최민창</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14187">최승민</a></td><td>3,300</td><td>-0.12</td><td>-27,513</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14780">강효종</a></td><td>3,300</td><td>-0.12</td><td>-28,143</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15078">조원태</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15083">허준혁</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12863">김태형</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12864">전준호</a></td><td>3,200</td><td>-0.04</td><td>-71,907</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14667">성재헌</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12909">이찬혁</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13103">성동현</a></td><td>3,100</td><td>-0.01</td><td>-284,117</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13105">최현준</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14669">유영찬</a></td><td>3,100</td><td>1.05</td><td>2,962</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15079">김주완</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12911">김성협</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13108">김의준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14141">김성진</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14675">김태우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14680">함창건</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14841">김단우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14845">박민호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15084">최원영</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15085">김성우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15087">양진혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15088">엄태경</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15484">김범석</a></td><td>3,000</td><td>-0.37</td><td>-8,055</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15486">박명근</a></td><td>3,000</td><td>-0.31</td><td>-9,820</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15487">이준서</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15488">원상훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15489">임정균</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15490">권동혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15491">허용주</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15492">송대현</a></td><td>3,000</td><td>-0.13</td><td>-23,886</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15493">이철민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15494">곽민호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15495">강민균</a></td><td>3,000</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [78]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=11310">박세웅</a></td><td>150,000</td><td>4.63</td><td>32,381</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14627">스트레일리</a></td><td>100,000</td><td>1.78</td><td>56,200</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15152">렉스</a></td><td>100,000</td><td>0.17</td><td>594,643</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15011">반즈</a></td><td>85,000</td><td>5.74</td><td>14,802</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10753">유강남</a></td><td>60,000</td><td>4.09</td><td>14,661</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10014">안치홍</a></td><td>50,000</td><td>1.99</td><td>25,091</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10266">전준우</a></td><td>50,000</td><td>3.79</td><td>13,190</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11165">노진혁</a></td><td>50,000</td><td>2.56</td><td>19,565</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15651">구드럼</a></td><td>40,000</td><td>0.14</td><td>281,684</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10253">정훈</a></td><td>30,000</td><td>0.22</td><td>137,349</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10825">김원중</a></td><td>25,200</td><td>1.36</td><td>18,560</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12295">윌커슨</a></td><td>25,000</td><td>3.03</td><td>8,248</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11291">구승민</a></td><td>24,860</td><td>0.90</td><td>27,634</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10863">한현희</a></td><td>20,000</td><td>0.95</td><td>21,134</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13145">한동희</a></td><td>19,260</td><td>-2.48</td><td>-7,760</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14624">최준용</a></td><td>15,800</td><td>1.55</td><td>10,183</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11232">이인복</a></td><td>14,500</td><td>-0.27</td><td>-53,772</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10427">김상수</a></td><td>11,000</td><td>1.58</td><td>6,951</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12930">나균안</a></td><td>10,900</td><td>3.40</td><td>3,207</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13148">김도규</a></td><td>9,500</td><td>0.21</td><td>45,957</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14159">서준원</a></td><td>9,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11311">심재민</a></td><td>8,300</td><td>1.03</td><td>8,054</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14571">안권수</a></td><td>8,000</td><td>1.84</td><td>4,355</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11413">지시완</a></td><td>7,600</td><td>0.10</td><td>78,656</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14160">고승민</a></td><td>7,300</td><td>0.27</td><td>27,300</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11299">문경찬</a></td><td>7,200</td><td>-0.19</td><td>-37,857</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14114">이학주</a></td><td>7,200</td><td>0.00</td><td>-3,290,180</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14642">황성빈</a></td><td>7,200</td><td>0.40</td><td>17,876</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10516">신정락</a></td><td>7,000</td><td>-0.10</td><td>-71,487</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10804">박승욱</a></td><td>7,000</td><td>1.92</td><td>3,638</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12931">김민수</a></td><td>6,300</td><td>-0.23</td><td>-27,418</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10885">윤명준</a></td><td>6,000</td><td>-0.65</td><td>-9,233</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13154">정보근</a></td><td>5,900</td><td>1.86</td><td>3,175</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14792">김진욱</a></td><td>5,600</td><td>-0.07</td><td>-81,697</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14169">신윤후</a></td><td>5,300</td><td>-0.35</td><td>-15,273</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15045">이민석</a></td><td>4,100</td><td>0.09</td><td>47,305</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11276">최영환</a></td><td>4,000</td><td>-0.28</td><td>-14,162</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11483">김재유</a></td><td>4,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12916">이정훈</a></td><td>4,000</td><td>0.49</td><td>8,125</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15046">조세진</a></td><td>4,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11388">강태율</a></td><td>3,900</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13155">장두성</a></td><td>3,800</td><td>0.15</td><td>25,597</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15051">한태양</a></td><td>3,800</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13147">정성종</a></td><td>3,600</td><td>0.15</td><td>24,658</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12570">김주현</a></td><td>3,400</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12935">나원탁</a></td><td>3,400</td><td>-0.02</td><td>-142,499</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13004">최민재</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15048">윤동희</a></td><td>3,300</td><td>0.88</td><td>3,771</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14163">박진</a></td><td>3,200</td><td>-0.06</td><td>-56,635</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14164">박영완</a></td><td>3,200</td><td>0.05</td><td>66,999</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14793">김창훈</a></td><td>3,200</td><td>0.07</td><td>42,936</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15047">진승현</a></td><td>3,200</td><td>-0.01</td><td>-462,918</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12928">윤성빈</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13149">김동우</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14625">홍민기</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14640">엄태호</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14796">손성빈</a></td><td>3,100</td><td>0.49</td><td>6,364</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10172">국해성</a></td><td>3,000</td><td>-0.02</td><td>-153,748</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12699">김강현</a></td><td>3,000</td><td>0.06</td><td>47,010</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12923">김태욱</a></td><td>3,000</td><td>0.04</td><td>72,688</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13169">최이준</a></td><td>3,000</td><td>0.02</td><td>173,303</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14678">이정우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14816">우강훈</a></td><td>3,000</td><td>-0.01</td><td>-240,292</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14819">이주찬</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14820">최종은</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14861">박형준</a></td><td>3,000</td><td>-0.02</td><td>-196,596</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14995">정대혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15053">김서진</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15135">민성우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15253">김민석</a></td><td>3,000</td><td>-0.21</td><td>-14,168</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15441">이진하</a></td><td>3,000</td><td>0.18</td><td>17,085</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15442">김기준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15443">정대선</a></td><td>3,000</td><td>-0.38</td><td>-7,884</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15444">이태연</a></td><td>3,000</td><td>-0.15</td><td>-19,665</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15445">석상호</a></td><td>3,000</td><td>0.26</td><td>11,574</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15446">조경민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15447">정재환</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15448">장세진</a></td><td>3,000</td><td>-0.04</td><td>-81,268</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15449">배인혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15623">조준혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15624">서동욱</a></td><td>3,000</td><td>-0.12</td><td>-26,058</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15625">배영빈</a></td><td>3,000</td><td>0.26</td><td>11,696</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15626">박건</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15627">윤수녕</a></td><td>3,000</td><td>-0.05</td><td>-59,773</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15645">김동혁</a></td><td>3,000</td><td>0.03</td><td>104,051</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13271">현도훈</a></td><td>1,500</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [79]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=10344">최형우</a></td><td>90,000</td><td>3.93</td><td>22,875</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11162">나성범</a></td><td>80,000</td><td>3.68</td><td>21,736</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15533">앤더슨</a></td><td>60,000</td><td>1.34</td><td>44,722</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10058">양현종</a></td><td>50,000</td><td>3.54</td><td>14,142</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14996">소크라테스</a></td><td>50,000</td><td>4.60</td><td>10,872</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10008">김선빈</a></td><td>45,000</td><td>2.69</td><td>16,746</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15147">파노니</a></td><td>35,000</td><td>1.73</td><td>20,229</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15534">메디나</a></td><td>30,000</td><td>-0.07</td><td>-444,450</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15648">산체스</a></td><td>25,000</td><td>0.12</td><td>217,065</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14608">정해영</a></td><td>23,000</td><td>1.06</td><td>21,682</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12534">최원준</a></td><td>22,000</td><td>0.82</td><td>26,903</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10459">김태군</a></td><td>20,000</td><td>0.59</td><td>34,171</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11261">박찬호</a></td><td>20,000</td><td>4.71</td><td>4,249</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11164">장현식</a></td><td>19,000</td><td>0.25</td><td>76,665</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10706">김대유</a></td><td>16,000</td><td>-0.03</td><td>-620,023</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10909">임기영</a></td><td>15,000</td><td>1.54</td><td>9,740</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14788">이의리</a></td><td>15,000</td><td>2.78</td><td>5,399</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11233">이창진</a></td><td>14,000</td><td>1.94</td><td>7,198</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11303">이준영</a></td><td>14,000</td><td>0.68</td><td>20,735</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12537">전상현</a></td><td>13,500</td><td>1.44</td><td>9,370</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11306">황대인</a></td><td>13,000</td><td>-0.22</td><td>-59,558</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11070">박준표</a></td><td>10,500</td><td>0.01</td><td>947,158</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11119">한승택</a></td><td>8,000</td><td>-0.45</td><td>-17,741</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13122">윤중현</a></td><td>7,900</td><td>0.24</td><td>32,519</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10659">고종욱</a></td><td>7,000</td><td>1.29</td><td>5,412</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11298">김호령</a></td><td>7,000</td><td>0.90</td><td>7,787</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14747">김재열</a></td><td>6,000</td><td>-0.37</td><td>-16,236</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11099">이우성</a></td><td>5,500</td><td>2.66</td><td>2,068</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11068">고영창</a></td><td>5,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14176">김기훈</a></td><td>5,000</td><td>-0.34</td><td>-14,867</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15056">김도영</a></td><td>5,000</td><td>3.88</td><td>1,289</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12567">주효상</a></td><td>4,800</td><td>-0.40</td><td>-11,877</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12540">김규성</a></td><td>4,500</td><td>0.86</td><td>5,214</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12637">김승현</a></td><td>4,500</td><td>0.13</td><td>35,693</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11407">최정용</a></td><td>4,000</td><td>0.34</td><td>11,858</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13114">김유신</a></td><td>3,900</td><td>-0.26</td><td>-14,911</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12914">유승철</a></td><td>3,800</td><td>0.04</td><td>96,829</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11364">김사윤</a></td><td>3,600</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12541">신범수</a></td><td>3,600</td><td>-0.32</td><td>-11,308</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12869">박정우</a></td><td>3,600</td><td>0.25</td><td>14,423</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12535">남하준</a></td><td>3,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12917">김석환</a></td><td>3,500</td><td>-0.40</td><td>-8,647</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14124">변우혁</a></td><td>3,500</td><td>-0.28</td><td>-12,698</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14612">홍종표</a></td><td>3,300</td><td>0.12</td><td>28,438</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12612">임석진</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13113">한준수</a></td><td>3,100</td><td>0.63</td><td>4,930</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12618">최수빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12866">강이준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12867">송후섭</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12944">김건국</a></td><td>3,000</td><td>0.05</td><td>62,153</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13095">배현호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13117">오정환</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14177">홍원빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14179">이태규</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14181">오선우</a></td><td>3,000</td><td>-0.22</td><td>-13,510</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14183">김민수</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14186">나용기</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14607">유지성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14645">김양수</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14822">김선우</a></td><td>3,000</td><td>0.04</td><td>73,273</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14824">장시현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15054">김용완</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15057">최지민</a></td><td>3,000</td><td>0.37</td><td>8,055</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15058">윤도현</a></td><td>3,000</td><td>-0.07</td><td>-44,356</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15060">김찬민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15061">이성주</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15063">황동하</a></td><td>3,000</td><td>-0.14</td><td>-20,853</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15432">윤영철</a></td><td>3,000</td><td>2.27</td><td>1,322</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15433">정해원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15435">곽도규</a></td><td>3,000</td><td>-0.15</td><td>-19,656</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15436">이송찬</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15437">이도현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15438">박일훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15439">김도월</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15440">김재현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15620">김주섭</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15641">박승훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15642">손호원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15737">이중석</a></td><td>3,000</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [80]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=10407">황재균</a></td><td>100,000</td><td>3.24</td><td>30,823</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15143">벤자민</a></td><td>100,000</td><td>2.90</td><td>34,443</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15144">알포드</a></td><td>100,000</td><td>4.82</td><td>20,750</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10470">박병호</a></td><td>70,000</td><td>4.15</td><td>16,852</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15542">슐서</a></td><td>65,000</td><td>0.33</td><td>197,251</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10235">장성우</a></td><td>50,000</td><td>3.43</td><td>14,562</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10320">김상수</a></td><td>50,000</td><td>2.53</td><td>19,726</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13942">쿠에바스</a></td><td>45,000</td><td>4.57</td><td>9,846</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11308">고영표</a></td><td>43,000</td><td>5.91</td><td>7,279</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11489">김재윤</a></td><td>36,000</td><td>2.05</td><td>17,519</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11212">배정대</a></td><td>34,000</td><td>1.82</td><td>18,650</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12943">조용호</a></td><td>32,000</td><td>0.03</td><td>962,730</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14600">소형준</a></td><td>32,000</td><td>-0.19</td><td>-166,189</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11323">주권</a></td><td>29,500</td><td>0.15</td><td>197,607</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13168">강백호</a></td><td>29,000</td><td>0.98</td><td>29,489</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11317">김민수</a></td><td>25,000</td><td>-0.18</td><td>-138,189</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10469">박경수</a></td><td>20,000</td><td>0.38</td><td>52,744</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11318">엄상백</a></td><td>20,000</td><td>2.91</td><td>6,878</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11394">배제성</a></td><td>20,000</td><td>1.95</td><td>10,266</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11339">김민혁</a></td><td>15,000</td><td>3.85</td><td>3,901</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10840">신본기</a></td><td>13,000</td><td>0.15</td><td>86,604</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11397">오윤석</a></td><td>12,000</td><td>0.76</td><td>15,748</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10835">김준태</a></td><td>10,000</td><td>0.72</td><td>13,842</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10737">박시영</a></td><td>9,800</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11316">조현우</a></td><td>7,600</td><td>0.01</td><td>993,178</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11147">이상호</a></td><td>7,000</td><td>-0.17</td><td>-42,056</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11284">조이현</a></td><td>6,500</td><td>-0.29</td><td>-22,442</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11342">송민섭</a></td><td>6,500</td><td>0.42</td><td>15,366</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15089">박영현</a></td><td>6,100</td><td>1.98</td><td>3,078</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13130">이채호</a></td><td>6,000</td><td>-0.14</td><td>-42,155</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13167">김민</a></td><td>6,000</td><td>-0.29</td><td>-21,040</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13151">이호연</a></td><td>5,700</td><td>1.14</td><td>5,014</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11333">문상철</a></td><td>5,600</td><td>0.11</td><td>50,805</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11214">장준원</a></td><td>5,000</td><td>0.16</td><td>31,895</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14108">손동현</a></td><td>5,000</td><td>1.30</td><td>3,857</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12941">홍현빈</a></td><td>4,800</td><td>0.18</td><td>26,737</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11330">김병희</a></td><td>4,700</td><td>-0.07</td><td>-63,686</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10304">하준호</a></td><td>4,500</td><td>0.00</td><td>-2,184,339</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12577">김태오</a></td><td>3,500</td><td>-0.18</td><td>-19,991</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12937">이정현</a></td><td>3,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12526">이시원</a></td><td>3,300</td><td>-0.27</td><td>-12,187</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12569">박선우</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12572">박세진</a></td><td>3,300</td><td>-0.01</td><td>-378,608</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12939">조병욱</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13227">문상인</a></td><td>3,300</td><td>0.02</td><td>158,511</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14191">강민성</a></td><td>3,300</td><td>0.26</td><td>12,908</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13233">양승혁</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14109">이상동</a></td><td>3,200</td><td>0.55</td><td>5,868</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14189">김성훈</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12938">이종혁</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13171">고명성</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13173">신병률</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13177">조대현</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14720">문상준</a></td><td>3,100</td><td>-0.22</td><td>-14,114</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15090">이상우</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13006">안치영</a></td><td>3,000</td><td>0.32</td><td>9,296</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13170">박시윤</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13172">윤강찬</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13174">백선기</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13232">박준혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14106">전용주</a></td><td>3,000</td><td>0.28</td><td>10,713</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14107">이정훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14110">박민석</a></td><td>3,000</td><td>-0.08</td><td>-37,214</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14111">이선우</a></td><td>3,000</td><td>0.00</td><td>-1,900,623</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14192">지강혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14603">강현우</a></td><td>3,000</td><td>-0.07</td><td>-46,111</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14604">한지용</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14717">서경찬</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14869">김영현</a></td><td>3,000</td><td>0.04</td><td>71,998</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14870">최성민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15093">우종휘</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15094">최동희</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15095">정정우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15096">권성준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15097">김병준</a></td><td>3,000</td><td>0.00</td><td>-10,681,440</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15518">김정운</a></td><td>3,000</td><td>-0.01</td><td>-312,870</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15519">정준영</a></td><td>3,000</td><td>0.38</td><td>7,818</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15520">손민석</a></td><td>3,000</td><td>-0.04</td><td>-77,748</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15521">김건웅</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15522">이준희</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15523">류현인</a></td><td>3,000</td><td>-0.43</td><td>-6,902</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15524">황의준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15525">정진호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15526">이준명</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15527">강건</a></td><td>3,000</td><td>0.16</td><td>19,023</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15616">백현수</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15617">이동관</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15618">정우성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15619">최정태</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16144">한민우</a></td><td>3,000</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [81]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=10892">구자욱</a></td><td>200,000</td><td>5.44</td><td>36,791</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10367">오승환</a></td><td>140,000</td><td>0.77</td><td>182,641</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14757">피렐라</a></td><td>120,000</td><td>0.70</td><td>171,965</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14617">뷰캐넌</a></td><td>110,000</td><td>6.31</td><td>17,428</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15001">수아레즈</a></td><td>90,000</td><td>2.52</td><td>35,762</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10232">강민호</a></td><td>60,000</td><td>2.61</td><td>22,999</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15536">와이드너</a></td><td>59,800</td><td>1.71</td><td>34,903</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10400">오재일</a></td><td>50,000</td><td>0.99</td><td>50,317</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10363">백정현</a></td><td>40,000</td><td>3.09</td><td>12,953</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14113">원태인</a></td><td>35,000</td><td>4.48</td><td>7,820</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10523">우규민</a></td><td>25,000</td><td>0.15</td><td>164,780</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10871">김태훈</a></td><td>18,000</td><td>-0.62</td><td>-28,892</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14618">김지찬</a></td><td>16,000</td><td>2.46</td><td>6,513</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10894">류지혁</a></td><td>15,500</td><td>0.38</td><td>41,156</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11255">강한울</a></td><td>15,000</td><td>-0.16</td><td>-95,223</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13156">최채흥</a></td><td>15,000</td><td>0.21</td><td>73,083</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12934">최지광</a></td><td>14,000</td><td>-0.12</td><td>-116,044</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10527">이승현</a></td><td>12,000</td><td>0.55</td><td>21,832</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10640">김헌곤</a></td><td>12,000</td><td>-0.18</td><td>-65,249</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12548">김동엽</a></td><td>9,000</td><td>0.03</td><td>259,899</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11404">장필준</a></td><td>8,000</td><td>-0.26</td><td>-30,359</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14798">이승현</a></td><td>8,000</td><td>0.05</td><td>166,778</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14867">김현준</a></td><td>8,000</td><td>1.24</td><td>6,431</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11169">이상민</a></td><td>7,500</td><td>-0.20</td><td>-37,130</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11344">김재성</a></td><td>7,500</td><td>0.27</td><td>27,365</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10685">김대우</a></td><td>7,000</td><td>0.29</td><td>23,829</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12885">문용익</a></td><td>6,300</td><td>0.23</td><td>26,998</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13242">홍정우</a></td><td>6,300</td><td>-0.33</td><td>-19,132</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15034">이재현</a></td><td>6,000</td><td>2.98</td><td>2,010</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13244">이재익</a></td><td>5,700</td><td>0.29</td><td>19,540</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13240">김호재</a></td><td>5,600</td><td>-0.20</td><td>-27,958</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12530">최충연</a></td><td>5,500</td><td>-0.09</td><td>-59,554</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14613">허윤동</a></td><td>5,400</td><td>-0.15</td><td>-35,223</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11266">김민수</a></td><td>5,200</td><td>-0.03</td><td>-187,570</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14115">김도환</a></td><td>5,000</td><td>-0.13</td><td>-38,208</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11144">노건우</a></td><td>4,800</td><td>-0.18</td><td>-27,227</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13157">양창섭</a></td><td>4,800</td><td>-0.42</td><td>-11,318</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11200">송준석</a></td><td>4,500</td><td>-0.07</td><td>-63,970</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12562">이성규</a></td><td>4,500</td><td>-0.03</td><td>-130,769</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11336">김태훈</a></td><td>4,300</td><td>-0.43</td><td>-9,997</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12936">김성윤</a></td><td>4,300</td><td>2.23</td><td>1,926</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14121">이해승</a></td><td>4,200</td><td>0.01</td><td>307,977</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14615">황동재</a></td><td>4,100</td><td>-0.07</td><td>-58,072</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13164">공민규</a></td><td>4,000</td><td>-0.42</td><td>-9,540</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12988">안주형</a></td><td>3,800</td><td>-0.36</td><td>-10,514</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14668">박주혁</a></td><td>3,800</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12932">김시현</a></td><td>3,700</td><td>-0.06</td><td>-63,090</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12651">박세웅</a></td><td>3,600</td><td>-0.03</td><td>-106,149</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13152">최하늘</a></td><td>3,600</td><td>-0.32</td><td>-11,188</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14799">이재희</a></td><td>3,600</td><td>0.12</td><td>30,311</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13160">이태훈</a></td><td>3,500</td><td>-0.09</td><td>-37,911</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14117">이병헌</a></td><td>3,400</td><td>-0.31</td><td>-11,082</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14116">양우현</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14863">김동진</a></td><td>3,300</td><td>1.04</td><td>3,185</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15039">김서준</a></td><td>3,300</td><td>-0.07</td><td>-46,533</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15040">조민성</a></td><td>3,300</td><td>-0.30</td><td>-10,888</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13158">김태우</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13161">윤정빈</a></td><td>3,200</td><td>-0.12</td><td>-26,551</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14664">한연욱</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14800">홍무원</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15035">김영웅</a></td><td>3,200</td><td>0.21</td><td>15,598</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15042">김상민</a></td><td>3,200</td><td>-0.39</td><td>-8,223</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13159">김용하</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13163">박용민</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14119">김준우</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14614">홍원표</a></td><td>3,100</td><td>0.12</td><td>26,380</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14698">정진수</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15038">신정환</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15044">윤정훈</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13165">서주원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13166">맹성주</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14801">오현석</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14864">홍승원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15043">장재혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15496">이호성</a></td><td>3,000</td><td>0.62</td><td>4,873</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15497">박권후</a></td><td>3,000</td><td>0.00</td><td>12,211,801</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15498">서현원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15499">김재상</a></td><td>3,000</td><td>-0.02</td><td>-120,535</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15500">신윤호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15501">강준서</a></td><td>3,000</td><td>-0.07</td><td>-41,715</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15502">김시온</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15503">류승민</a></td><td>3,000</td><td>-0.41</td><td>-7,346</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15504">김민호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15505">박시원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15506">박장민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15507">박진우</a></td><td>3,000</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [82]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=14888">추신수</a></td><td>170,000</td><td>1.46</td><td>116,584</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10106">최정</a></td><td>100,000</td><td>4.85</td><td>20,613</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10126">김광현</a></td><td>100,000</td><td>4.48</td><td>22,341</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15530">에레디아</a></td><td>90,000</td><td>4.11</td><td>21,918</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15529">로메로</a></td><td>80,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10783">문승원</a></td><td>70,000</td><td>0.78</td><td>89,613</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10182">최주환</a></td><td>65,000</td><td>1.04</td><td>62,554</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15528">맥카티</a></td><td>60,000</td><td>3.38</td><td>17,736</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15644">엘리아스</a></td><td>54,000</td><td>3.54</td><td>15,247</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10131">박종훈</a></td><td>50,000</td><td>0.39</td><td>129,359</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10815">한유섬</a></td><td>50,000</td><td>0.35</td><td>142,766</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14587">최지훈</a></td><td>30,000</td><td>1.55</td><td>19,355</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12922">박성한</a></td><td>27,000</td><td>4.36</td><td>6,188</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10784">서진용</a></td><td>26,500</td><td>2.84</td><td>9,330</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10203">노경은</a></td><td>17,000</td><td>1.64</td><td>10,340</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10108">김강민</a></td><td>16,000</td><td>0.41</td><td>39,043</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10636">김성현</a></td><td>15,000</td><td>1.55</td><td>9,673</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10707">김민식</a></td><td>15,000</td><td>1.70</td><td>8,833</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14581">오원석</a></td><td>14,000</td><td>1.64</td><td>8,512</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13126">최민준</a></td><td>13,000</td><td>0.28</td><td>46,713</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10082">이재원</a></td><td>10,000</td><td>-0.81</td><td>-12,395</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10249">오태곤</a></td><td>10,000</td><td>0.56</td><td>17,794</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11236">박민호</a></td><td>9,500</td><td>0.24</td><td>39,923</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14699">전의산</a></td><td>9,000</td><td>-0.22</td><td>-41,025</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10124">고효준</a></td><td>8,500</td><td>0.78</td><td>10,840</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11148">강진성</a></td><td>8,000</td><td>0.20</td><td>39,361</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10133">김태훈</a></td><td>7,800</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11108">이흥련</a></td><td>7,000</td><td>-0.35</td><td>-20,262</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13191">서동민</a></td><td>6,000</td><td>0.05</td><td>120,132</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11321">정성곤</a></td><td>5,500</td><td>-0.11</td><td>-49,758</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14147">하재훈</a></td><td>5,500</td><td>2.79</td><td>1,972</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12622">김찬형</a></td><td>5,000</td><td>0.00</td><td>-3,061,025</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14151">최경모</a></td><td>5,000</td><td>-0.45</td><td>-11,017</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13128">최준우</a></td><td>4,500</td><td>0.64</td><td>6,992</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10795">임준섭</a></td><td>4,000</td><td>-0.12</td><td>-33,228</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12613">안상현</a></td><td>4,000</td><td>-0.04</td><td>-111,946</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11369">이현석</a></td><td>3,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13129">전경원</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14806">조형우</a></td><td>3,200</td><td>0.04</td><td>83,006</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15032">전영준</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10810">최항</a></td><td>3,100</td><td>-0.19</td><td>-16,028</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11242">이건욱</a></td><td>3,100</td><td>0.60</td><td>5,130</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13228">한두솔</a></td><td>3,100</td><td>0.00</td><td>-790,540</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12531">김주한</a></td><td>3,000</td><td>-0.02</td><td>-196,947</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12571">정동윤</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12920">이원준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13057">김주온</a></td><td>3,000</td><td>-0.01</td><td>-244,111</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13125">조성훈</a></td><td>3,000</td><td>0.02</td><td>153,301</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13127">유호식</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13194">이정범</a></td><td>3,000</td><td>-0.34</td><td>-8,785</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13195">최상민</a></td><td>3,000</td><td>0.34</td><td>8,914</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14145">백승건</a></td><td>3,000</td><td>0.30</td><td>10,004</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14148">최수호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14149">허민혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14152">서상준</a></td><td>3,000</td><td>-0.03</td><td>-92,477</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14153">채현우</a></td><td>3,000</td><td>0.00</td><td>-7,767,332</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14154">전진우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14200">김규남</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14586">류효승</a></td><td>3,000</td><td>-0.09</td><td>-32,810</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14682">양선률</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14687">박시후</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14692">이거연</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14807">고명준</a></td><td>3,000</td><td>-0.02</td><td>-157,745</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15023">윤태현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15024">신헌민</a></td><td>3,000</td><td>-0.05</td><td>-55,918</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15025">김도현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15026">박상후</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15028">이기순</a></td><td>3,000</td><td>-0.01</td><td>-283,645</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15029">강매성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15033">최유빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15461">이로운</a></td><td>3,000</td><td>-0.15</td><td>-20,115</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15462">송영진</a></td><td>3,000</td><td>0.08</td><td>39,439</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15463">김정민</a></td><td>3,000</td><td>0.00</td><td>-611,799</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15464">안현서</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15465">김건웅</a></td><td>3,000</td><td>-0.09</td><td>-32,298</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15466">박세직</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15467">김민준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15468">류현곤</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15469">이승훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15470">김건이</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15471">김준영</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15615">조강희</a></td><td>3,000</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [83]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=11137">박민우</a></td><td>110,000</td><td>5.25</td><td>20,953</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10189">박건우</a></td><td>90,000</td><td>3.92</td><td>22,940</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15535">페디</a></td><td>80,000</td><td>7.95</td><td>10,059</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15537">마틴</a></td><td>72,000</td><td>3.28</td><td>21,973</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10891">박세혁</a></td><td>70,000</td><td>0.88</td><td>79,265</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11353">구창모</a></td><td>60,000</td><td>1.70</td><td>35,313</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10261">손아섭</a></td><td>50,000</td><td>4.62</td><td>10,826</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10217">이용찬</a></td><td>40,000</td><td>0.72</td><td>55,281</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10220">이재학</a></td><td>20,000</td><td>1.16</td><td>17,179</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10720">심창민</a></td><td>15,000</td><td>0.06</td><td>260,282</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15653">태너</a></td><td>15,000</td><td>1.94</td><td>7,723</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13088">김영규</a></td><td>14,000</td><td>1.06</td><td>13,157</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13085">신민혁</a></td><td>13,500</td><td>1.91</td><td>7,073</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14155">송명기</a></td><td>13,000</td><td>0.86</td><td>15,174</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11153">김성욱</a></td><td>10,000</td><td>0.34</td><td>29,013</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11168">임정호</a></td><td>9,000</td><td>0.18</td><td>49,071</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11172">권희동</a></td><td>9,000</td><td>2.18</td><td>4,137</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11248">배재환</a></td><td>9,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13080">김시훈</a></td><td>9,000</td><td>-0.10</td><td>-94,156</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14765">김주원</a></td><td>9,000</td><td>2.22</td><td>4,049</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11355">류진욱</a></td><td>7,500</td><td>2.36</td><td>3,182</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13115">하준영</a></td><td>7,500</td><td>0.16</td><td>47,675</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12565">최성영</a></td><td>7,200</td><td>0.94</td><td>7,686</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14221">최정원</a></td><td>6,600</td><td>0.47</td><td>14,015</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11329">안중열</a></td><td>6,000</td><td>-0.83</td><td>-7,267</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12897">김진호</a></td><td>6,000</td><td>0.38</td><td>15,704</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13082">오영수</a></td><td>6,000</td><td>-0.04</td><td>-169,936</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14158">배민서</a></td><td>5,100</td><td>-0.13</td><td>-38,762</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10322">박석민</a></td><td>5,000</td><td>-0.83</td><td>-6,023</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11151">이민호</a></td><td>5,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12560">도태훈</a></td><td>5,000</td><td>2.38</td><td>2,101</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13081">김형준</a></td><td>5,000</td><td>0.90</td><td>5,557</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10717">정진기</a></td><td>4,700</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14220">서호철</a></td><td>4,500</td><td>2.85</td><td>1,581</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11135">윤형준</a></td><td>4,000</td><td>0.40</td><td>10,119</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11246">박대온</a></td><td>4,000</td><td>0.14</td><td>28,094</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12529">권정웅</a></td><td>4,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13250">한석현</a></td><td>3,900</td><td>-0.18</td><td>-22,228</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11387">채지선</a></td><td>3,800</td><td>-0.02</td><td>-201,036</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14763">이용준</a></td><td>3,500</td><td>0.36</td><td>9,674</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15119">조민석</a></td><td>3,500</td><td>0.13</td><td>26,129</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11360">이우석</a></td><td>3,300</td><td>0.03</td><td>124,338</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14171">전루건</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14767">오장한</a></td><td>3,300</td><td>-0.01</td><td>-331,987</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14764">한재승</a></td><td>3,200</td><td>-0.04</td><td>-87,452</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12903">김수윤</a></td><td>3,100</td><td>-0.18</td><td>-16,950</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13261">천재환</a></td><td>3,100</td><td>0.31</td><td>10,129</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14156">전사민</a></td><td>3,100</td><td>0.01</td><td>286,973</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14654">하준수</a></td><td>3,100</td><td>0.04</td><td>78,983</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14716">김한별</a></td><td>3,100</td><td>-0.51</td><td>-6,029</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14766">오태양</a></td><td>3,100</td><td>-0.40</td><td>-7,819</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12574">서의태</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12621">최우재</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12898">김태현</a></td><td>3,000</td><td>0.03</td><td>100,147</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13083">김철호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13084">김재균</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13087">최보성</a></td><td>3,000</td><td>-0.15</td><td>-19,455</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13090">이인혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13175">박주현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14157">최시혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14219">박주찬</a></td><td>3,000</td><td>-0.24</td><td>-12,715</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14222">김범준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14594">임형원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14595">정구범</a></td><td>3,000</td><td>-0.10</td><td>-30,318</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14649">노시훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14656">한건희</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14659">한재환</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14661">박영빈</a></td><td>3,000</td><td>0.13</td><td>23,239</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14827">김준상</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14877">조현진</a></td><td>3,000</td><td>-0.12</td><td>-25,248</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15110">박성재</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15111">이준혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15113">김녹원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15114">이한</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15115">임지민</a></td><td>3,000</td><td>-0.02</td><td>-138,769</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15116">이주형</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15117">이현우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15120">서준교</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15450">신영우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15451">박한결</a></td><td>3,000</td><td>0.29</td><td>10,341</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15452">신용석</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15453">목지훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15454">강건준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15455">이준호</a></td><td>3,000</td><td>-0.18</td><td>-16,725</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15456">신성호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15458">서동욱</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15459">배상호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15460">김주환</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15621">박찬희</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15622">김택우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14597">박시원</a></td><td>-</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [84]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=10643">김재환</a></td><td>150,000</td><td>0.48</td><td>309,878</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10184">허경민</a></td><td>120,000</td><td>2.35</td><td>50,978</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15539">로하스</a></td><td>85,000</td><td>2.41</td><td>35,224</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10195">정수빈</a></td><td>60,000</td><td>4.87</td><td>12,325</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10174">김재호</a></td><td>50,000</td><td>3.30</td><td>15,174</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13941">알칸타라</a></td><td>50,000</td><td>5.79</td><td>8,635</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15538">딜런</a></td><td>45,000</td><td>-0.08</td><td>-541,797</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11213">양석환</a></td><td>40,000</td><td>3.33</td><td>12,016</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12852">최원준</a></td><td>33,000</td><td>1.23</td><td>26,893</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10165">양의지</a></td><td>30,000</td><td>6.10</td><td>4,914</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10696">홍건희</a></td><td>30,000</td><td>0.84</td><td>35,541</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15153">브랜든</a></td><td>23,000</td><td>3.61</td><td>6,369</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10690">김강률</a></td><td>20,000</td><td>0.40</td><td>50,245</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11087">강승호</a></td><td>20,000</td><td>1.98</td><td>10,125</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12847">김명신</a></td><td>14,500</td><td>0.95</td><td>15,275</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13061">곽빈</a></td><td>14,000</td><td>4.36</td><td>3,210</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12568">이영하</a></td><td>12,000</td><td>-0.31</td><td>-38,465</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12850">박치국</a></td><td>10,500</td><td>0.50</td><td>20,931</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11098">김인태</a></td><td>10,000</td><td>0.38</td><td>26,394</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13071">정철원</a></td><td>10,000</td><td>-0.05</td><td>-214,404</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11198">박계범</a></td><td>9,700</td><td>-0.06</td><td>-154,543</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12678">이승진</a></td><td>8,800</td><td>-0.02</td><td>-420,564</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12524">조수행</a></td><td>7,800</td><td>0.49</td><td>16,074</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11159">이형범</a></td><td>7,000</td><td>-0.62</td><td>-11,363</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10747">김지용</a></td><td>6,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11097">장승현</a></td><td>6,000</td><td>-0.93</td><td>-6,450</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12522">박준영</a></td><td>6,000</td><td>1.88</td><td>3,184</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12894">이유찬</a></td><td>6,000</td><td>1.43</td><td>4,192</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14770">최승용</a></td><td>6,000</td><td>1.94</td><td>3,098</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13072">김민규</a></td><td>5,500</td><td>0.04</td><td>146,643</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14771">안재석</a></td><td>5,300</td><td>0.25</td><td>21,170</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10299">장원준</a></td><td>5,000</td><td>0.10</td><td>49,587</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11300">박정수</a></td><td>4,500</td><td>0.05</td><td>99,144</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11328">안승한</a></td><td>4,500</td><td>-0.41</td><td>-11,105</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12970">김민혁</a></td><td>4,500</td><td>-0.14</td><td>-31,463</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14170">김대한</a></td><td>4,500</td><td>-0.94</td><td>-4,770</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14738">양찬열</a></td><td>4,300</td><td>0.25</td><td>17,228</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11491">박소준</a></td><td>4,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11492">신성현</a></td><td>4,000</td><td>-0.10</td><td>-42,068</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13070">박신지</a></td><td>3,600</td><td>-0.04</td><td>-85,608</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13073">전민재</a></td><td>3,600</td><td>-0.32</td><td>-11,285</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14736">박지훈</a></td><td>3,600</td><td>-0.17</td><td>-21,280</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14172">송승환</a></td><td>3,500</td><td>0.22</td><td>16,156</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12523">서예일</a></td><td>3,400</td><td>-0.09</td><td>-36,930</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12605">고봉재</a></td><td>3,300</td><td>-0.11</td><td>-29,690</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12892">박유연</a></td><td>3,300</td><td>-0.06</td><td>-56,936</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12606">홍성호</a></td><td>3,100</td><td>-0.26</td><td>-11,880</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13079">권민석</a></td><td>3,100</td><td>-0.08</td><td>-40,842</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14572">이주엽</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14769">김동주</a></td><td>3,100</td><td>1.81</td><td>1,713</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14838">박성재</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15099">이병헌</a></td><td>3,100</td><td>-0.08</td><td>-36,906</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12608">신창희</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12848">문원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13074">배창현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13106">조선명</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13124">김정우</a></td><td>3,000</td><td>-0.10</td><td>-30,321</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13268">김호준</a></td><td>3,000</td><td>-0.05</td><td>-61,108</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14174">이민혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14175">김태근</a></td><td>3,000</td><td>-0.74</td><td>-4,042</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14570">장규빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14573">제환유</a></td><td>3,000</td><td>-0.05</td><td>-61,039</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14652">전형근</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14733">최종인</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14836">이상연</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14837">장빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15101">이원재</a></td><td>3,000</td><td>-0.06</td><td>-50,863</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15102">신민철</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15103">전희범</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15105">정유석</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15108">김시완</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15127">최지강</a></td><td>3,000</td><td>0.01</td><td>333,572</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15508">최준호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15509">김유성</a></td><td>3,000</td><td>-0.15</td><td>-19,572</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15511">임서준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15512">윤준호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15513">한충희</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15514">백승우</a></td><td>3,000</td><td>0.16</td><td>18,521</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15515">박민준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15516">김문수</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15517">남율</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15611">이정원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15613">이기석</a></td><td>3,000</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [85]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=13940">요키시</a></td><td>120,000</td><td>0.94</td><td>128,200</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12906">이정후</a></td><td>110,000</td><td>5.18</td><td>21,222</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15531">후라도</a></td><td>85,000</td><td>7.12</td><td>11,938</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14742">러셀</a></td><td>55,000</td><td>1.08</td><td>50,965</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10312">이지영</a></td><td>50,000</td><td>0.86</td><td>58,404</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11161">원종현</a></td><td>50,000</td><td>-0.17</td><td>-301,827</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12905">김혜성</a></td><td>42,000</td><td>6.98</td><td>6,021</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13091">안우진</a></td><td>35,000</td><td>6.86</td><td>5,100</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10035">이용규</a></td><td>30,000</td><td>-0.43</td><td>-70,236</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12858">김재웅</a></td><td>22,000</td><td>1.25</td><td>17,538</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10180">이원석</a></td><td>20,000</td><td>-0.99</td><td>-20,171</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10814">홍성민</a></td><td>15,000</td><td>-0.01</td><td>-1,243,915</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12865">이승호</a></td><td>12,800</td><td>0.09</td><td>140,999</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11244">김태진</a></td><td>12,000</td><td>0.04</td><td>267,985</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11376">송성문</a></td><td>12,000</td><td>1.95</td><td>6,149</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12516">이형종</a></td><td>12,000</td><td>-0.21</td><td>-57,844</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10452">임창민</a></td><td>10,000</td><td>1.26</td><td>7,923</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10533">정찬헌</a></td><td>10,000</td><td>1.27</td><td>7,905</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15646">맥키니</a></td><td>10,000</td><td>0.11</td><td>92,461</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11182">김준완</a></td><td>9,000</td><td>-0.05</td><td>-166,729</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10730">양현</a></td><td>8,500</td><td>-0.56</td><td>-15,256</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15652">도슨</a></td><td>8,500</td><td>1.75</td><td>4,851</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11422">전병우</a></td><td>8,000</td><td>-0.05</td><td>-164,681</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14785">김휘집</a></td><td>7,400</td><td>1.12</td><td>6,613</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13092">김선기</a></td><td>7,300</td><td>-0.48</td><td>-15,171</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10437">문성현</a></td><td>7,000</td><td>-0.02</td><td>-301,722</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12997">이영준</a></td><td>7,000</td><td>-0.10</td><td>-73,546</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10870">김재현</a></td><td>6,500</td><td>-0.55</td><td>-11,720</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11222">하영민</a></td><td>6,500</td><td>-0.44</td><td>-14,749</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14674">김동혁</a></td><td>6,500</td><td>-0.46</td><td>-14,189</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12503">김웅빈</a></td><td>6,000</td><td>-0.64</td><td>-9,324</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11226">임병욱</a></td><td>5,800</td><td>0.44</td><td>13,102</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14214">김주형</a></td><td>5,500</td><td>-0.73</td><td>-7,513</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11225">임지열</a></td><td>5,000</td><td>0.45</td><td>11,108</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11260">박준태</a></td><td>5,000</td><td>-0.20</td><td>-25,419</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14695">신준우</a></td><td>4,800</td><td>-0.40</td><td>-11,894</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12989">박승주</a></td><td>4,500</td><td>-0.04</td><td>-125,171</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13096">김수환</a></td><td>4,500</td><td>-0.13</td><td>-33,655</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14131">윤정현</a></td><td>4,500</td><td>0.13</td><td>33,367</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14849">김성진</a></td><td>4,500</td><td>0.84</td><td>5,378</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15073">이명종</a></td><td>4,500</td><td>0.14</td><td>33,130</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14848">김준형</a></td><td>4,200</td><td>0.00</td><td>1,510,520</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15068">박찬혁</a></td><td>4,200</td><td>-0.45</td><td>-9,357</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10882">변시원</a></td><td>4,000</td><td>-0.14</td><td>-28,982</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14580">박주홍</a></td><td>4,000</td><td>-0.71</td><td>-5,624</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13093">예진원</a></td><td>3,900</td><td>-0.42</td><td>-9,317</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14130">박주성</a></td><td>3,700</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14855">이주형</a></td><td>3,700</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11531">김정인</a></td><td>3,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12859">이병규</a></td><td>3,500</td><td>-0.04</td><td>-83,411</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14132">조영건</a></td><td>3,400</td><td>0.42</td><td>8,020</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14591">이주형</a></td><td>3,300</td><td>2.55</td><td>1,292</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14577">김병휘</a></td><td>3,200</td><td>-0.26</td><td>-12,401</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14601">이강준</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14784">장재영</a></td><td>3,200</td><td>0.85</td><td>3,743</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14133">주성원</a></td><td>3,100</td><td>-0.47</td><td>-6,657</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14576">이종민</a></td><td>3,100</td><td>-0.27</td><td>-11,457</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14851">김시앙</a></td><td>3,100</td><td>-0.37</td><td>-8,330</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15027">노운현</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15067">주승우</a></td><td>3,100</td><td>-0.18</td><td>-16,757</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15069">송정인</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11375">박주현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12854">양지율</a></td><td>3,000</td><td>-0.02</td><td>-188,477</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12856">오윤성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14211">박준형</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14216">정현민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14218">김신회</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14681">김동욱</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14850">정연제</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14853">양경식</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14854">이재홍</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15071">윤석원</a></td><td>3,000</td><td>-0.19</td><td>-15,431</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15072">주승빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15074">김리안</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15075">이세호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15132">박수종</a></td><td>3,000</td><td>1.45</td><td>2,075</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15472">김건희</a></td><td>3,000</td><td>-0.24</td><td>-12,690</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15473">김동헌</a></td><td>3,000</td><td>0.48</td><td>6,292</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15474">오상원</a></td><td>3,000</td><td>-0.09</td><td>-33,749</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15475">박윤성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15476">이승원</a></td><td>3,000</td><td>-0.17</td><td>-17,183</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15477">송재선</a></td><td>3,000</td><td>-0.09</td><td>-34,371</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15478">우승원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15479">박성빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15480">이호열</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15481">변헌성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15482">안겸</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15483">서유신</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15485">김동규</a></td><td>3,000</td><td>-0.17</td><td>-17,377</td></tr>							</tbody>
						</table>
""")

In [86]:
len(team_table)

10

In [90]:
earning = pd.DataFrame()
for i in range(len(team_table)):
    name = team_names[i]
    team = team_table[i]
    print(name)
    df, pids = get_team_stats_from_markup(StringIO(str(team)))
    df['팀'] = name
    df['pid'] = pids[1:]
    print(df.shape)
    print(len(pids))
    earning = pd.concat([earning, df])
    display(earning.tail())
earning.isna().sum()

한화 이글스
(92, 6)
93

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

     선수  연봉(만원) WAR WAR당 연봉       팀    pid
87  고영재    3000   -       -  한화 이글스  15629
88  이석제    3000   -       -  한화 이글스  15630
89  성지훈    3000   -       -  한화 이글스  15631
90  김석훈    3000   -       -  한화 이글스  15632
91  한경빈    3000   -       -  한화 이글스  15633

LG 트윈스
(84, 6)
85

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

     선수  연봉(만원)    WAR WAR당 연봉       팀    pid
79  허용주    3000      -       -  LG 트윈스  15491
80  송대현    3000  -0.13  -23886  LG 트윈스  15492
81  이철민    3000      -       -  LG 트윈스  15493
82  곽민호    3000      -       -  LG 트윈스  15494
83  강민균    3000      -       -  LG 트윈스  15495

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

롯데 자이언츠
(86, 6)
87

     선수  연봉(만원)    WAR WAR당 연봉        팀    pid
81  배영빈    3000   0.26   11696  롯데 자이언츠  15625
82   박건    3000      -       -  롯데 자이언츠  15626
83  윤수녕    3000  -0.05  -59773  롯데 자이언츠  15627
84  김동혁    3000   0.03  104051  롯데 자이언츠  15645
85  현도훈    1500      -       -  롯데 자이언츠  13271

KIA 타이거즈

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(79, 6)
80

     선수  연봉(만원) WAR WAR당 연봉         팀    pid
74  김재현    3000   -       -  KIA 타이거즈  15440
75  김주섭    3000   -       -  KIA 타이거즈  15620
76  박승훈    3000   -       -  KIA 타이거즈  15641
77  손호원    3000   -       -  KIA 타이거즈  15642
78  이중석    3000   -       -  KIA 타이거즈  15737

KT 위즈
(90, 6)
91

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

     선수  연봉(만원) WAR WAR당 연봉      팀    pid
85  백현수    3000   -       -  KT 위즈  15616
86  이동관    3000   -       -  KT 위즈  15617
87  정우성    3000   -       -  KT 위즈  15618
88  최정태    3000   -       -  KT 위즈  15619
89  한민우    3000   -       -  KT 위즈  16144

삼성 라이온즈
(86, 6)
87

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

     선수  연봉(만원)    WAR WAR당 연봉        팀    pid
81  류승민    3000  -0.41   -7346  삼성 라이온즈  15503
82  김민호    3000      -       -  삼성 라이온즈  15504
83  박시원    3000      -       -  삼성 라이온즈  15505
84  박장민    3000      -       -  삼성 라이온즈  15506
85  박진우    3000      -       -  삼성 라이온즈  15507

SSG 랜더스

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(82, 6)
83

     선수  연봉(만원) WAR WAR당 연봉        팀    pid
77  류현곤    3000   -       -  SSG 랜더스  15468
78  이승훈    3000   -       -  SSG 랜더스  15469
79  김건이    3000   -       -  SSG 랜더스  15470
80  김준영    3000   -       -  SSG 랜더스  15471
81  조강희    3000   -       -  SSG 랜더스  15615

NC 다이노스

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(91, 6)
92

     선수 연봉(만원) WAR WAR당 연봉        팀    pid
86  배상호   3000   -       -  NC 다이노스  15459
87  김주환   3000   -       -  NC 다이노스  15460
88  박찬희   3000   -       -  NC 다이노스  15621
89  김택우   3000   -       -  NC 다이노스  15622
90  박시원      -   -       -  NC 다이노스  14597

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

두산 베어스
(83, 6)
84

     선수 연봉(만원) WAR WAR당 연봉       팀    pid
78  박민준   3000   -       -  두산 베어스  15515
79  김문수   3000   -       -  두산 베어스  15516
80   남율   3000   -       -  두산 베어스  15517
81  이정원   3000   -       -  두산 베어스  15611
82  이기석   3000   -       -  두산 베어스  15613

키움 히어로즈
(89, 6)
90

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

     선수 연봉(만원)    WAR WAR당 연봉        팀    pid
84  이호열   3000      -       -  키움 히어로즈  15480
85  변헌성   3000      -       -  키움 히어로즈  15481
86   안겸   3000      -       -  키움 히어로즈  15482
87  서유신   3000      -       -  키움 히어로즈  15483
88  김동규   3000  -0.17  -17377  키움 히어로즈  15485

선수         0
연봉(만원)     0
WAR        0
WAR당 연봉    0
팀          0
pid        0
dtype: int64

In [91]:
earning.to_csv("2023_연봉_statiz.csv", index=False)

In [92]:
team_table = []

In [93]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=10590">류현진</a></td><td>200,000</td><td>2.77</td><td>72,322</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16313">폰세</a></td><td>112,000</td><td>5.86</td><td>19,116</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16312">플로리얼</a></td><td>98,000</td><td>1.96</td><td>50,070</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11318">엄상백</a></td><td>90,000</td><td>-0.11</td><td>-783,140</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16153">와이스</a></td><td>84,000</td><td>3.42</td><td>24,584</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11215">채은성</a></td><td>60,000</td><td>1.73</td><td>34,667</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10014">안치홍</a></td><td>50,000</td><td>-1.17</td><td>-42,635</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10170">최재훈</a></td><td>50,000</td><td>2.62</td><td>19,096</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11334">심우준</a></td><td>50,000</td><td>0.16</td><td>320,587</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14125">노시환</a></td><td>33,000</td><td>1.97</td><td>16,764</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16396">리베라토</a></td><td>28,700</td><td>1.18</td><td>24,220</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10609">이태양</a></td><td>27,000</td><td>0.05</td><td>516,439</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11415">주현상</a></td><td>25,000</td><td>-0.07</td><td>-358,015</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12871">박상원</a></td><td>22,000</td><td>1.16</td><td>19,041</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10453">장시환</a></td><td>15,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10610">장민재</a></td><td>15,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12585">김태연</a></td><td>14,600</td><td>0.25</td><td>58,459</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11411">김범수</a></td><td>14,300</td><td>0.74</td><td>19,196</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11410">김민우</a></td><td>13,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11414">이도윤</a></td><td>11,000</td><td>0.47</td><td>23,199</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15013">문동주</a></td><td>10,000</td><td>2.30</td><td>4,357</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10082">이재원</a></td><td>10,000</td><td>0.11</td><td>88,731</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10812">한승혁</a></td><td>9,400</td><td>1.70</td><td>5,519</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13003">이민우</a></td><td>9,400</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10913">하주석</a></td><td>9,000</td><td>2.03</td><td>4,433</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15422">문현빈</a></td><td>8,800</td><td>1.74</td><td>5,062</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16110">황영묵</a></td><td>8,300</td><td>0.34</td><td>24,381</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11110">윤대경</a></td><td>7,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14707">최인호</a></td><td>6,800</td><td>0.15</td><td>44,444</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12539">이진영</a></td><td>6,200</td><td>2.38</td><td>2,605</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14808">김기중</a></td><td>6,000</td><td>0.31</td><td>19,506</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15421">김서현</a></td><td>5,600</td><td>2.38</td><td>2,353</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12589">김인환</a></td><td>5,500</td><td>-0.30</td><td>-18,530</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11117">김종수</a></td><td>5,500</td><td>0.38</td><td>14,456</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14871">김규연</a></td><td>5,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13138">이원석</a></td><td>5,000</td><td>1.23</td><td>4,072</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13245">이상규</a></td><td>4,800</td><td>-0.23</td><td>-20,767</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16107">황준서</a></td><td>4,500</td><td>0.71</td><td>6,337</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12587">박상언</a></td><td>4,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14158">배민서</a></td><td>4,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16108">조동욱</a></td><td>4,000</td><td>1.26</td><td>3,175</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13676">권광민</a></td><td>3,800</td><td>-0.12</td><td>-32,057</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14196">윤산흠</a></td><td>3,800</td><td>-0.04</td><td>-103,378</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14706">임종찬</a></td><td>3,700</td><td>-0.12</td><td>-31,331</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14704">박정현</a></td><td>3,700</td><td>-0.02</td><td>-180,849</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14210">조한민</a></td><td>3,600</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15139">이상혁</a></td><td>3,500</td><td>-0.36</td><td>-9,610</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14126">유로결</a></td><td>3,500</td><td>-0.31</td><td>-11,252</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14178">장지수</a></td><td>3,400</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11116">이충호</a></td><td>3,400</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14809">배동현</a></td><td>3,400</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14204">허관회</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13136">박성웅</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14811">장규현</a></td><td>3,300</td><td>0.06</td><td>52,038</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14209">김건</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14711">김승일</a></td><td>3,200</td><td>-0.05</td><td>-62,000</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14812">송호정</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14813">정민규</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15633">한경빈</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15015">허인서</a></td><td>3,100</td><td>0.10</td><td>29,929</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16118">김도빈</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16303">한지윤</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16302">권민규</a></td><td>3,000</td><td>-0.03</td><td>-97,063</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16301">정우주</a></td><td>3,000</td><td>0.08</td><td>37,671</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16304">배승수</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16306">박상현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16311">이민재</a></td><td>3,000</td><td>-0.17</td><td>-18,171</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16310">최주원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16309">엄요셉</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16308">엄상현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16307">이지성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16305">이동영</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16372">이승현</a></td><td>3,000</td><td>0.13</td><td>23,411</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15014">박준영</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14876">안진</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14874">문승진</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15016">유민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15019">이성민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14127">정이황</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14710">김범준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16114">원종혁</a></td><td>3,000</td><td>-0.04</td><td>-69,660</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16112">최준서</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16111">이기창</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16109">정안석</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15426">한서구</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15631">성지훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16011">신우재</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16373">박부성</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14682">양선률</a></td><td>-</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [94]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=15532">오스틴</a></td><td>168,000</td><td>3.05</td><td>55,006</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10387">박동원</a></td><td>120,000</td><td>4.38</td><td>27,387</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16160">에르난데스</a></td><td>112,000</td><td>0.92</td><td>121,512</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16286">치리노스</a></td><td>112,000</td><td>2.69</td><td>41,679</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12546">홍창기</a></td><td>65,000</td><td>0.73</td><td>88,999</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11190">박해민</a></td><td>60,000</td><td>3.29</td><td>18,232</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10187">김현수</a></td><td>50,000</td><td>2.43</td><td>20,606</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14137">문보경</a></td><td>41,000</td><td>3.58</td><td>11,468</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11166">김진성</a></td><td>33,000</td><td>-0.04</td><td>-817,072</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10475">오지환</a></td><td>30,000</td><td>1.32</td><td>22,660</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14134">이정용</a></td><td>27,000</td><td>0.22</td><td>124,346</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14669">유영찬</a></td><td>21,000</td><td>-0.08</td><td>-252,431</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10652">임찬규</a></td><td>20,000</td><td>3.36</td><td>5,953</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11094">함덕주</a></td><td>20,000</td><td>-0.04</td><td>-454,960</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11164">장현식</a></td><td>20,000</td><td>0.92</td><td>21,641</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13056">신민재</a></td><td>20,000</td><td>1.20</td><td>16,654</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14136">정우영</a></td><td>18,000</td><td>-0.07</td><td>-271,651</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13112">문성주</a></td><td>18,000</td><td>2.26</td><td>7,972</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12908">손주영</a></td><td>17,200</td><td>1.59</td><td>10,815</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14140">구본혁</a></td><td>13,500</td><td>2.41</td><td>5,605</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13156">최채흥</a></td><td>13,000</td><td>-0.18</td><td>-70,348</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11229">김유영</a></td><td>10,500</td><td>-0.11</td><td>-93,816</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10749">이우찬</a></td><td>10,000</td><td>0.38</td><td>26,465</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10690">김강률</a></td><td>10,000</td><td>0.32</td><td>31,099</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14143">이지강</a></td><td>8,300</td><td>-0.12</td><td>-69,809</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10720">심창민</a></td><td>8,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10835">김준태</a></td><td>7,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12532">김대현</a></td><td>7,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14606">천성호</a></td><td>7,100</td><td>1.19</td><td>5,948</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13009">백승현</a></td><td>7,000</td><td>0.33</td><td>20,986</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14783">이영빈</a></td><td>6,000</td><td>-0.01</td><td>-476,395</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15486">박명근</a></td><td>6,000</td><td>0.16</td><td>36,428</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12931">김민수</a></td><td>6,000</td><td>-0.04</td><td>-170,731</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11347">안익훈</a></td><td>5,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15484">김범석</a></td><td>4,700</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12697">배재준</a></td><td>4,500</td><td>0.02</td><td>264,111</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14187">최승민</a></td><td>4,300</td><td>-0.02</td><td>-213,979</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13102">김영준</a></td><td>4,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14651">이종준</a></td><td>4,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15084">최원영</a></td><td>4,000</td><td>0.60</td><td>6,656</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14816">우강훈</a></td><td>3,600</td><td>-0.01</td><td>-342,176</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14781">김진수</a></td><td>3,600</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14846">송승기</a></td><td>3,600</td><td>2.80</td><td>1,286</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16017">정지헌</a></td><td>3,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13109">송찬의</a></td><td>3,500</td><td>0.43</td><td>8,135</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12545">김주성</a></td><td>3,500</td><td>0.11</td><td>33,306</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13103">성동현</a></td><td>3,400</td><td>-0.21</td><td>-16,581</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16015">진우영</a></td><td>3,400</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15083">허준혁</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15081">이주헌</a></td><td>3,300</td><td>0.72</td><td>4,592</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14141">김성진</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16013">김현종</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14680">함창건</a></td><td>3,200</td><td>0.19</td><td>16,931</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16014">손용준</a></td><td>3,100</td><td>-0.22</td><td>-14,023</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15086">문정빈</a></td><td>3,100</td><td>0.14</td><td>22,267</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14675">김수인</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15085">김성우</a></td><td>3,100</td><td>0.01</td><td>364,849</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13108">김의준</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16283">안시후</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16282">우정안</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16281">김종운</a></td><td>3,000</td><td>-0.04</td><td>-76,979</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16280">박시원</a></td><td>3,000</td><td>0.04</td><td>76,411</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16389">박건우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16279">박관우</a></td><td>3,000</td><td>-0.01</td><td>-281,397</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16278">서영준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16277">이태훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16276">이한림</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16275">추세현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16274">김영우</a></td><td>3,000</td><td>0.37</td><td>8,063</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16284">고영웅</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16285">성준서</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14845">박민호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14782">조건희</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13174">백선기</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13129">전경원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13057">김주온</a></td><td>3,000</td><td>-0.02</td><td>-142,368</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15491">허용주</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16022">심규빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16021">김도윤</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15265">코엔 윈</a></td><td>1,600</td><td>-0.13</td><td>-12,502</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16388">김웅</a></td><td>-</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [95]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=11310">박세웅</a></td><td>135,000</td><td>1.51</td><td>89,584</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15011">반즈</a></td><td>133,000</td><td>0.29</td><td>462,866</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16106">레이예스</a></td><td>112,000</td><td>3.26</td><td>34,365</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10825">김원중</a></td><td>110,000</td><td>1.86</td><td>59,103</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10753">유강남</a></td><td>110,000</td><td>1.78</td><td>61,710</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10863">한현희</a></td><td>100,000</td><td>0.09</td><td>1,127,913</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16273">데이비슨</a></td><td>70,000</td><td>3.46</td><td>20,222</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11165">노진혁</a></td><td>70,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10266">전준우</a></td><td>40,000</td><td>1.22</td><td>32,687</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16391">감보아</a></td><td>35,000</td><td>2.11</td><td>16,610</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11291">구승민</a></td><td>30,000</td><td>-0.15</td><td>-205,634</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10427">김상수</a></td><td>24,000</td><td>-0.48</td><td>-50,124</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15048">윤동희</a></td><td>20,000</td><td>2.32</td><td>8,627</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10253">정훈</a></td><td>20,000</td><td>0.25</td><td>80,977</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10238">김민성</a></td><td>20,000</td><td>-0.29</td><td>-68,250</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14160">고승민</a></td><td>18,500</td><td>2.28</td><td>8,114</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10804">박승욱</a></td><td>17,000</td><td>-0.17</td><td>-100,979</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14642">황성빈</a></td><td>15,500</td><td>0.44</td><td>35,095</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14590">손호영</a></td><td>12,500</td><td>0.09</td><td>143,332</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14797">나승엽</a></td><td>12,000</td><td>0.05</td><td>237,709</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12930">나균안</a></td><td>12,000</td><td>1.62</td><td>7,411</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13071">정철원</a></td><td>12,000</td><td>0.83</td><td>14,456</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14624">최준용</a></td><td>11,000</td><td>0.29</td><td>38,257</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14792">김진욱</a></td><td>10,000</td><td>-0.58</td><td>-17,198</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13154">정보근</a></td><td>7,700</td><td>0.13</td><td>59,778</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13073">전민재</a></td><td>7,500</td><td>0.55</td><td>13,657</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10075">진해수</a></td><td>7,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14796">손성빈</a></td><td>6,800</td><td>0.01</td><td>714,076</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14163">박진</a></td><td>6,000</td><td>-0.37</td><td>-16,028</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11425">박진형</a></td><td>5,600</td><td>-0.06</td><td>-89,812</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11311">심재민</a></td><td>5,400</td><td>0.05</td><td>113,467</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10810">최항</a></td><td>5,000</td><td>-0.03</td><td>-184,891</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10737">박시영</a></td><td>5,000</td><td>-0.26</td><td>-19,235</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14169">신윤후</a></td><td>4,800</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13155">장두성</a></td><td>4,600</td><td>1.53</td><td>3,006</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15047">진승현</a></td><td>4,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15045">이민석</a></td><td>4,000</td><td>1.40</td><td>2,862</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13148">김도규</a></td><td>4,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15046">조세진</a></td><td>4,000</td><td>-0.15</td><td>-26,546</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12699">김강현</a></td><td>4,000</td><td>0.81</td><td>4,925</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16090">정현수</a></td><td>4,000</td><td>0.58</td><td>6,878</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15051">한태양</a></td><td>3,800</td><td>0.80</td><td>4,734</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12572">박세진</a></td><td>3,700</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15624">서동욱</a></td><td>3,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15645">김동혁</a></td><td>3,300</td><td>1.21</td><td>2,733</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13271">현도훈</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14795">정우준</a></td><td>3,200</td><td>0.06</td><td>52,623</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14794">송재영</a></td><td>3,200</td><td>0.05</td><td>58,439</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14819">이주찬</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16091">이호준</a></td><td>3,100</td><td>0.18</td><td>17,000</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16101">백두산</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16093">강성우</a></td><td>3,100</td><td>-0.04</td><td>-73,810</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12928">윤성빈</a></td><td>3,100</td><td>-0.19</td><td>-16,204</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16092">박준우</a></td><td>3,100</td><td>-0.23</td><td>-13,513</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16102">강승구</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14690">이인한</a></td><td>3,100</td><td>0.01</td><td>465,161</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13173">신병률</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14625">홍민기</a></td><td>3,100</td><td>1.16</td><td>2,674</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16263">김태현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16271">김태균</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16270">한승현</a></td><td>3,000</td><td>0.01</td><td>321,175</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16269">최민규</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16268">이영재</a></td><td>3,000</td><td>-0.01</td><td>-256,990</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16267">김동현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16266">박재엽</a></td><td>3,000</td><td>0.21</td><td>14,523</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16265">김현우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16264">박세현</a></td><td>3,000</td><td>-0.16</td><td>-19,274</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16272">조영우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16395">박찬형</a></td><td>3,000</td><td>-0.09</td><td>-34,679</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16377">이태경</a></td><td>3,000</td><td>-0.01</td><td>-211,953</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14817">이병준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15052">엄장윤</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14165">김동규</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16104">김대현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16100">배세종</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16379">박준기</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16383">오창현</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16382">박지훈</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16376">유태웅</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16378">박건우</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16380">이상화</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16381">정선우</a></td><td>-</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [96]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=16088">네일</a></td><td>168,000</td><td>4.86</td><td>34,546</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16262">위즈덤</a></td><td>112,000</td><td>3.59</td><td>31,218</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10344">최형우</a></td><td>100,000</td><td>3.86</td><td>25,915</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16261">올러</a></td><td>84,000</td><td>3.09</td><td>27,166</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11162">나성범</a></td><td>80,000</td><td>-0.23</td><td>-352,822</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10459">김태군</a></td><td>70,000</td><td>1.27</td><td>54,987</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10008">김선빈</a></td><td>60,000</td><td>0.89</td><td>67,790</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15056">김도영</a></td><td>50,000</td><td>1.70</td><td>29,397</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10058">양현종</a></td><td>50,000</td><td>0.75</td><td>66,395</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11261">박찬호</a></td><td>45,000</td><td>3.27</td><td>13,781</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12534">최원준</a></td><td>40,000</td><td>-0.94</td><td>-42,739</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11126">조상우</a></td><td>40,000</td><td>0.68</td><td>58,892</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14608">정해영</a></td><td>36,000</td><td>0.17</td><td>213,937</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10909">임기영</a></td><td>30,000</td><td>-0.22</td><td>-138,590</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12537">전상현</a></td><td>30,000</td><td>0.91</td><td>33,036</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14788">이의리</a></td><td>17,000</td><td>0.07</td><td>249,408</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11099">이우성</a></td><td>17,000</td><td>-0.48</td><td>-35,249</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11303">이준영</a></td><td>17,000</td><td>-0.06</td><td>-295,854</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10659">고종욱</a></td><td>15,000</td><td>0.88</td><td>17,112</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13113">한준수</a></td><td>14,000</td><td>0.80</td><td>17,474</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11233">이창진</a></td><td>14,000</td><td>-0.07</td><td>-186,976</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10855">서건창</a></td><td>12,000</td><td>0.00</td><td>4,244,047</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10706">김대유</a></td><td>12,000</td><td>-0.08</td><td>-143,534</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15432">윤영철</a></td><td>12,000</td><td>0.31</td><td>38,969</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15435">곽도규</a></td><td>12,000</td><td>-0.13</td><td>-90,111</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15057">최지민</a></td><td>12,000</td><td>0.36</td><td>32,996</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15063">황동하</a></td><td>10,000</td><td>-0.07</td><td>-151,808</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14128">김도현</a></td><td>9,000</td><td>2.23</td><td>4,031</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14124">변우혁</a></td><td>8,500</td><td>0.10</td><td>84,841</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11298">김호령</a></td><td>8,000</td><td>1.04</td><td>7,713</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11070">박준표</a></td><td>7,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11306">황대인</a></td><td>7,000</td><td>0.06</td><td>122,598</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12540">김규성</a></td><td>6,500</td><td>0.99</td><td>6,557</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11119">한승택</a></td><td>6,500</td><td>0.12</td><td>52,126</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14612">홍종표</a></td><td>6,500</td><td>0.31</td><td>21,309</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11159">이형범</a></td><td>6,500</td><td>-0.30</td><td>-21,579</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12869">박정우</a></td><td>6,500</td><td>0.51</td><td>12,672</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13122">윤중현</a></td><td>6,000</td><td>0.05</td><td>129,886</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14176">김기훈</a></td><td>5,500</td><td>0.03</td><td>170,723</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12637">김승현</a></td><td>4,600</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14162">김현수</a></td><td>4,500</td><td>0.11</td><td>40,826</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12944">김건국</a></td><td>4,500</td><td>-0.19</td><td>-23,985</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11407">최정용</a></td><td>4,500</td><td>-0.03</td><td>-160,746</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12567">주효상</a></td><td>4,400</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11364">김사윤</a></td><td>4,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12917">김석환</a></td><td>4,000</td><td>0.09</td><td>43,648</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13093">예진원</a></td><td>4,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12914">유승철</a></td><td>3,800</td><td>0.02</td><td>204,429</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14611">박민</a></td><td>3,800</td><td>0.20</td><td>19,397</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14789">장민기</a></td><td>3,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14181">오선우</a></td><td>3,400</td><td>1.02</td><td>3,346</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14607">유지성</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15058">윤도현</a></td><td>3,200</td><td>0.34</td><td>9,469</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16083">김민재</a></td><td>3,100</td><td>0.08</td><td>36,756</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16082">김민주</a></td><td>3,100</td><td>-0.07</td><td>-43,415</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16086">김두현</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14786">박건우</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15433">정해원</a></td><td>3,100</td><td>0.19</td><td>16,586</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14657">장재혁</a></td><td>3,100</td><td>-0.02</td><td>-171,830</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16260">박헌</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16259">이성원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16258">엄준현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16254">김정엽</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16252">박재현</a></td><td>3,000</td><td>-0.70</td><td>-4,310</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16251">이호민</a></td><td>3,000</td><td>0.15</td><td>20,619</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16250">김태형</a></td><td>3,000</td><td>0.09</td><td>31,955</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16257">임다온</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16256">나연우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16255">최건희</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16253">양수호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14826">이영재</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14824">장시현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14823">이준범</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15065">신명승</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14177">홍원빈</a></td><td>3,000</td><td>-0.05</td><td>-66,412</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12866">강이준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13117">오정환</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16077">조대현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16085">성영탁</a></td><td>3,000</td><td>0.96</td><td>3,130</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16084">강민제</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16080">강동훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16078">이상준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15440">김재현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15125">박상준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15437">이도현</a></td><td>3,000</td><td>-0.10</td><td>-28,644</td></tr>							</tbody>
						</table>
""")

In [97]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=12995">로하스</a></td><td>210,000</td><td>1.48</td><td>141,707</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11308">고영표</a></td><td>200,000</td><td>3.08</td><td>64,884</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13942">쿠에바스</a></td><td>140,000</td><td>0.42</td><td>329,505</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16138">헤이수스</a></td><td>112,000</td><td>1.95</td><td>57,568</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13168">강백호</a></td><td>70,000</td><td>0.36</td><td>196,578</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10407">황재균</a></td><td>50,000</td><td>1.05</td><td>47,432</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10235">장성우</a></td><td>50,000</td><td>1.94</td><td>25,726</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16401">패트릭</a></td><td>38,400</td><td>0.27</td><td>141,753</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11212">배정대</a></td><td>34,000</td><td>0.63</td><td>53,961</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10320">김상수</a></td><td>30,000</td><td>1.32</td><td>22,658</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11339">김민혁</a></td><td>30,000</td><td>0.28</td><td>105,994</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10184">허경민</a></td><td>30,000</td><td>0.73</td><td>41,374</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11394">배제성</a></td><td>25,000</td><td>0.56</td><td>44,454</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15089">박영현</a></td><td>24,000</td><td>0.14</td><td>175,773</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14600">소형준</a></td><td>22,000</td><td>3.54</td><td>6,223</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11317">김민수</a></td><td>21,000</td><td>0.28</td><td>74,741</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11323">주권</a></td><td>20,000</td><td>0.17</td><td>114,781</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10523">우규민</a></td><td>20,000</td><td>0.68</td><td>29,223</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11333">문상철</a></td><td>17,000</td><td>0.40</td><td>42,459</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11397">오윤석</a></td><td>16,000</td><td>0.58</td><td>27,597</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10400">오재일</a></td><td>15,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14581">오원석</a></td><td>14,000</td><td>3.39</td><td>4,129</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12583">장진혁</a></td><td>11,500</td><td>0.04</td><td>296,361</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10535">최동환</a></td><td>11,000</td><td>-0.22</td><td>-49,433</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14108">손동현</a></td><td>10,000</td><td>1.51</td><td>6,626</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13151">이호연</a></td><td>7,000</td><td>0.22</td><td>32,493</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12916">이정훈</a></td><td>6,500</td><td>0.70</td><td>9,311</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11342">송민섭</a></td><td>6,000</td><td>0.03</td><td>239,900</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14109">이상동</a></td><td>5,900</td><td>0.53</td><td>11,041</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12885">문용익</a></td><td>5,800</td><td>0.07</td><td>78,480</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11284">조이현</a></td><td>5,700</td><td>0.18</td><td>32,166</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14142">임준형</a></td><td>5,500</td><td>-0.06</td><td>-92,223</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11214">장준원</a></td><td>5,100</td><td>-0.41</td><td>-12,516</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14603">강현우</a></td><td>5,000</td><td>0.14</td><td>34,995</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13130">이채호</a></td><td>5,000</td><td>-0.04</td><td>-129,878</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14777">권동진</a></td><td>4,600</td><td>0.67</td><td>6,860</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13006">안치영</a></td><td>4,500</td><td>-0.03</td><td>-175,754</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13177">조대현</a></td><td>4,300</td><td>0.32</td><td>13,611</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16027">원상현</a></td><td>4,000</td><td>0.93</td><td>4,310</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14111">이선우</a></td><td>3,800</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14191">강민성</a></td><td>3,700</td><td>-0.52</td><td>-7,166</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14106">전용주</a></td><td>3,600</td><td>0.45</td><td>8,052</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14667">성재헌</a></td><td>3,600</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15097">김병준</a></td><td>3,600</td><td>-0.02</td><td>-206,761</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16028">육청명</a></td><td>3,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15527">강건</a></td><td>3,500</td><td>-0.10</td><td>-35,100</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12577">김태오</a></td><td>3,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14776">한차현</a></td><td>3,500</td><td>-0.03</td><td>-109,845</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12937">이정현</a></td><td>3,500</td><td>-0.05</td><td>-70,646</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14605">윤준혁</a></td><td>3,500</td><td>-0.16</td><td>-22,180</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14110">박민석</a></td><td>3,400</td><td>0.22</td><td>15,283</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15092">안현민</a></td><td>3,300</td><td>5.04</td><td>655</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14779">김건형</a></td><td>3,300</td><td>-0.07</td><td>-44,306</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14870">최성민</a></td><td>3,200</td><td>0.09</td><td>33,917</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14775">지명성</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14720">문상준</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15090">이상우</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16354">박준혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16355">박민석</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16356">오서진</a></td><td>3,000</td><td>-0.03</td><td>-90,460</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16357">이용현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16358">윤상인</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16359">이정환</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16360">정영웅</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16351">김동현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16352">박건우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16353">김재원</a></td><td>3,000</td><td>-0.05</td><td>-61,824</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16361">이승준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14833">김주완</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15096">권성준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15094">최동희</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15093">우종휘</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15091">한지웅</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14778">유준규</a></td><td>3,000</td><td>-0.31</td><td>-9,761</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14774">신범준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14179">이태규</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13083">김철호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13127">유호식</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14658">최용준</a></td><td>3,000</td><td>0.23</td><td>12,959</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12938">이종혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16159">이현민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15526">이준명</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16036">이승언</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16035">김민석</a></td><td>3,000</td><td>0.00</td><td>4,654,518</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16034">이승현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16033">박태완</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16031">신호준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16386">장민호</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16387">정운교</a></td><td>-</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [98]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=10892">구자욱</a></td><td>200,000</td><td>1.81</td><td>110,724</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15861">레예스</a></td><td>98,000</td><td>1.12</td><td>87,890</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15531">후라도</a></td><td>98,000</td><td>4.40</td><td>22,295</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10367">오승환</a></td><td>80,000</td><td>-0.12</td><td>-654,557</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11489">김재윤</a></td><td>80,000</td><td>-0.39</td><td>-202,678</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16162">디아즈</a></td><td>70,000</td><td>3.83</td><td>18,292</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14113">원태인</a></td><td>63,000</td><td>2.93</td><td>21,496</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10894">류지혁</a></td><td>60,000</td><td>2.04</td><td>29,362</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16397">가라비토</a></td><td>49,000</td><td>0.98</td><td>49,849</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10232">강민호</a></td><td>40,000</td><td>2.28</td><td>17,568</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10363">백정현</a></td><td>40,000</td><td>1.33</td><td>30,120</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10470">박병호</a></td><td>38,000</td><td>0.85</td><td>44,675</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14618">김지찬</a></td><td>28,000</td><td>-0.14</td><td>-207,150</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10871">김태훈</a></td><td>24,000</td><td>0.94</td><td>25,437</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10527">이승현</a></td><td>24,000</td><td>-0.21</td><td>-112,626</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15034">이재현</a></td><td>21,000</td><td>3.59</td><td>5,856</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11379">최원태</a></td><td>20,000</td><td>1.51</td><td>13,222</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10452">임창민</a></td><td>20,000</td><td>-0.17</td><td>-116,575</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12934">최지광</a></td><td>17,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15035">김영웅</a></td><td>15,000</td><td>1.34</td><td>11,225</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12562">이성규</a></td><td>13,000</td><td>0.54</td><td>24,082</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14798">이승현</a></td><td>12,000</td><td>1.64</td><td>7,305</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10640">김헌곤</a></td><td>10,000</td><td>-0.10</td><td>-104,275</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10685">김대우</a></td><td>10,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11169">이상민</a></td><td>8,500</td><td>0.04</td><td>205,055</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10851">최성훈</a></td><td>7,800</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11422">전병우</a></td><td>7,500</td><td>0.64</td><td>11,687</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13161">윤정빈</a></td><td>7,400</td><td>-0.81</td><td>-9,095</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12936">김성윤</a></td><td>7,000</td><td>2.66</td><td>2,631</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13162">김무신</a></td><td>7,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11255">강한울</a></td><td>7,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12988">안주형</a></td><td>7,000</td><td>-0.30</td><td>-23,584</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10730">양현</a></td><td>7,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14117">이병헌</a></td><td>6,500</td><td>-0.14</td><td>-45,452</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14615">황동재</a></td><td>6,200</td><td>0.01</td><td>691,337</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13244">이재익</a></td><td>6,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13152">최하늘</a></td><td>6,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10137">송은범</a></td><td>6,000</td><td>0.05</td><td>115,486</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11344">김재성</a></td><td>5,500</td><td>-0.46</td><td>-11,838</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14122">박승규</a></td><td>5,200</td><td>0.41</td><td>12,597</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14616">이승민</a></td><td>5,000</td><td>-0.02</td><td>-259,180</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13157">양창섭</a></td><td>4,800</td><td>0.09</td><td>54,531</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14115">김도환</a></td><td>4,700</td><td>0.03</td><td>166,412</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11266">김민수</a></td><td>4,600</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11336">김태훈</a></td><td>4,500</td><td>0.06</td><td>69,700</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12941">홍현빈</a></td><td>4,500</td><td>-0.01</td><td>-328,541</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14175">김태근</a></td><td>4,500</td><td>0.02</td><td>218,111</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12530">최충연</a></td><td>4,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13164">공민규</a></td><td>4,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14121">이해승</a></td><td>4,200</td><td>0.00</td><td>950,033</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15496">이호성</a></td><td>4,000</td><td>0.08</td><td>47,478</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14116">양우현</a></td><td>4,000</td><td>0.01</td><td>443,588</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14668">박주혁</a></td><td>3,800</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14799">이재희</a></td><td>3,600</td><td>0.35</td><td>10,394</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14614">홍원표</a></td><td>3,550</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15875">양도근</a></td><td>3,500</td><td>1.54</td><td>2,269</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15864">육선엽</a></td><td>3,500</td><td>0.17</td><td>20,862</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15036">김재혁</a></td><td>3,500</td><td>-0.17</td><td>-20,945</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15040">조민성</a></td><td>3,400</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14866">이창용</a></td><td>3,300</td><td>-0.02</td><td>-203,121</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14801">오현석</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15882">김대호</a></td><td>3,300</td><td>0.18</td><td>18,360</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15868">김호진</a></td><td>3,250</td><td>0.00</td><td>-3,091,469</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15874">김동현</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15870">이현준</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15867">김성경</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15506">박장민</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15507">박진우</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16239">배찬승</a></td><td>3,000</td><td>0.10</td><td>29,962</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16240">심재훈</a></td><td>3,000</td><td>-0.03</td><td>-105,791</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16245">홍준영</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16246">천겸</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16247">우승완</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16248">강민성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16241">차승준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16242">함수호</a></td><td>3,000</td><td>-0.02</td><td>-158,567</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16243">권현우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16244">이진용</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16249">진희성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14802">주한울</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15037">차동영</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15869">신경민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15873">유병선</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15865">박준용</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15866">정민성</a></td><td>3,000</td><td>-0.06</td><td>-48,093</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16368">김백산</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16369">김유현</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16370">최예한</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16371">김상준</a></td><td>-</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [99]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=10126">김광현</a></td><td>300,000</td><td>2.18</td><td>137,692</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15530">에레디아</a></td><td>224,000</td><td>1.22</td><td>184,174</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10106">최정</a></td><td>170,000</td><td>0.24</td><td>723,057</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16146">앤더슨</a></td><td>161,000</td><td>4.51</td><td>35,687</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16324">화이트</a></td><td>140,000</td><td>3.30</td><td>42,485</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10131">박종훈</a></td><td>110,000</td><td>-0.04</td><td>-2,869,987</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10815">한유섬</a></td><td>90,000</td><td>1.23</td><td>73,304</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10783">문승원</a></td><td>80,000</td><td>1.07</td><td>75,038</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10203">노경은</a></td><td>40,000</td><td>1.18</td><td>33,788</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10784">서진용</a></td><td>38,000</td><td>-0.01</td><td>-3,094,841</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12922">박성한</a></td><td>37,000</td><td>3.83</td><td>9,665</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14587">최지훈</a></td><td>30,000</td><td>1.22</td><td>24,560</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10707">김민식</a></td><td>25,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11373">김택형</a></td><td>20,500</td><td>0.31</td><td>67,162</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10249">오태곤</a></td><td>15,000</td><td>0.22</td><td>68,345</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10312">이지영</a></td><td>15,000</td><td>-0.22</td><td>-69,485</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10636">김성현</a></td><td>15,000</td><td>0.37</td><td>40,774</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14805">조병현</a></td><td>13,500</td><td>2.29</td><td>5,903</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14804">장지훈</a></td><td>13,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13167">김민</a></td><td>11,000</td><td>0.51</td><td>21,779</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16390">맥브룸</a></td><td>10,500</td><td>-0.05</td><td>-229,338</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13126">최민준</a></td><td>10,000</td><td>0.60</td><td>16,674</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11153">김성욱</a></td><td>10,000</td><td>-0.46</td><td>-21,957</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14147">하재훈</a></td><td>9,000</td><td>-0.29</td><td>-31,460</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13228">한두솔</a></td><td>8,000</td><td>0.03</td><td>269,755</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14807">고명준</a></td><td>8,000</td><td>1.18</td><td>6,807</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16042">정준재</a></td><td>7,500</td><td>0.80</td><td>9,390</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15461">이로운</a></td><td>7,400</td><td>1.87</td><td>3,953</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16038">박지환</a></td><td>6,200</td><td>-0.85</td><td>-7,321</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15462">송영진</a></td><td>5,500</td><td>0.14</td><td>38,356</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14806">조형우</a></td><td>4,000</td><td>0.77</td><td>5,223</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15024">신헌민</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16139">허진</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13128">최준우</a></td><td>3,200</td><td>0.12</td><td>27,001</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12622">김찬형</a></td><td>3,200</td><td>-0.40</td><td>-8,079</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12613">안상현</a></td><td>3,200</td><td>-0.34</td><td>-9,362</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14145">백승건</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11242">이건욱</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12903">김수윤</a></td><td>3,200</td><td>-0.14</td><td>-22,714</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13195">최상민</a></td><td>3,200</td><td>-0.08</td><td>-38,354</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13194">이정범</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11246">박대온</a></td><td>3,200</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15032">전영준</a></td><td>3,200</td><td>0.72</td><td>4,459</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12541">신범수</a></td><td>3,200</td><td>0.32</td><td>9,932</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15030">김태윤</a></td><td>3,100</td><td>0.02</td><td>128,864</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14687">박시후</a></td><td>3,100</td><td>0.31</td><td>9,982</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16044">박성빈</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14146">김창평</a></td><td>3,100</td><td>0.00</td><td>679,454</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14586">류효승</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15121">석정우</a></td><td>3,100</td><td>-0.35</td><td>-8,882</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16400">장현진</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16317">이원준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16318">최윤석</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16316">천범석</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16315">신지환</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16314">이율예</a></td><td>3,000</td><td>-0.04</td><td>-73,688</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16319">김현재</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16320">이도우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16322">한지헌</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16321">홍대인</a></td><td>3,000</td><td>-0.03</td><td>-116,817</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16323">도재현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14862">박정빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14803">김건우</a></td><td>3,000</td><td>0.95</td><td>3,158</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11351">최민창</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14153">채현우</a></td><td>3,000</td><td>0.15</td><td>19,538</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14148">최수호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12571">정동윤</a></td><td>3,000</td><td>-0.25</td><td>-12,142</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14585">김성민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14584">현원회</a></td><td>3,000</td><td>-0.20</td><td>-14,666</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16047">김규민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16045">백준서</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16043">정현승</a></td><td>3,000</td><td>0.03</td><td>99,423</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16041">최현석</a></td><td>3,000</td><td>0.02</td><td>123,599</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16040">박기호</a></td><td>3,000</td><td>0.31</td><td>9,574</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15122">임근우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16039">이승민</a></td><td>3,000</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [100]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=16066">데이비슨</a></td><td>168,000</td><td>1.35</td><td>124,888</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11137">박민우</a></td><td>90,000</td><td>4.34</td><td>20,759</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16350">로건</a></td><td>78,400</td><td>2.52</td><td>31,159</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16349">라일리</a></td><td>72,800</td><td>3.11</td><td>23,391</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10189">박건우</a></td><td>70,000</td><td>1.33</td><td>52,483</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10891">박세혁</a></td><td>60,000</td><td>-0.55</td><td>-108,905</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10261">손아섭</a></td><td>50,000</td><td>2.06</td><td>24,225</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11172">권희동</a></td><td>22,500</td><td>1.74</td><td>12,939</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10217">이용찬</a></td><td>20,000</td><td>-0.16</td><td>-126,049</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13088">김영규</a></td><td>20,000</td><td>0.13</td><td>158,607</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14765">김주원</a></td><td>20,000</td><td>3.00</td><td>6,657</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11168">임정호</a></td><td>20,000</td><td>-0.35</td><td>-56,426</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13085">신민혁</a></td><td>18,000</td><td>1.75</td><td>10,273</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10220">이재학</a></td><td>18,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14785">김휘집</a></td><td>17,500</td><td>1.31</td><td>13,396</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14220">서호철</a></td><td>17,500</td><td>-0.63</td><td>-27,831</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11355">류진욱</a></td><td>13,500</td><td>0.52</td><td>25,881</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13080">김시훈</a></td><td>13,500</td><td>-0.26</td><td>-50,995</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14747">김재열</a></td><td>12,000</td><td>-0.44</td><td>-27,436</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14597">박시원</a></td><td>12,000</td><td>-0.44</td><td>-27,354</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13081">김형준</a></td><td>11,000</td><td>1.44</td><td>7,661</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11353">구창모</a></td><td>10,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12560">도태훈</a></td><td>8,000</td><td>0.00</td><td>3,512,947</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12565">최성영</a></td><td>8,000</td><td>-0.33</td><td>-24,060</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13261">천재환</a></td><td>7,600</td><td>0.28</td><td>27,168</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14764">한재승</a></td><td>7,500</td><td>0.33</td><td>22,734</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14221">최정원</a></td><td>7,000</td><td>1.03</td><td>6,791</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11329">안중열</a></td><td>6,600</td><td>-0.38</td><td>-17,208</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11248">배재환</a></td><td>5,500</td><td>0.72</td><td>7,643</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13082">오영수</a></td><td>5,100</td><td>0.12</td><td>43,600</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12897">김진호</a></td><td>5,000</td><td>0.89</td><td>5,640</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14593">김태경</a></td><td>5,000</td><td>-0.27</td><td>-18,289</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15119">조민석</a></td><td>5,000</td><td>0.13</td><td>37,471</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14716">김한별</a></td><td>3,800</td><td>0.39</td><td>9,832</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14156">전사민</a></td><td>3,800</td><td>-0.12</td><td>-31,023</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13250">한석현</a></td><td>3,700</td><td>0.32</td><td>11,560</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16053">임상현</a></td><td>3,700</td><td>-0.02</td><td>-150,884</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15451">박한결</a></td><td>3,500</td><td>-0.07</td><td>-52,977</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12898">김태현</a></td><td>3,500</td><td>-0.02</td><td>-192,599</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15112">박동수</a></td><td>3,400</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14767">오장한</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14172">송승환</a></td><td>3,200</td><td>-0.19</td><td>-16,736</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14766">오태양</a></td><td>3,100</td><td>-0.06</td><td>-53,461</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14171">전루건</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12900">소이현</a></td><td>3,100</td><td>0.23</td><td>13,716</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13087">최보성</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14661">박영빈</a></td><td>3,100</td><td>0.09</td><td>35,618</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16341">홍재문</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16342">유재현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16340">김태훈</a></td><td>3,000</td><td>-0.06</td><td>-50,114</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16343">이세민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16346">장창훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16347">양가온솔</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16348">조창연</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16345">신민우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16344">정현창</a></td><td>3,000</td><td>-0.11</td><td>-26,341</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15113">김녹원</a></td><td>3,000</td><td>0.00</td><td>754,578</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15111">이준혁</a></td><td>3,000</td><td>-0.19</td><td>-15,583</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15055">조효원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13175">박주현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14219">박주찬</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14222">김범준</a></td><td>3,000</td><td>-0.02</td><td>-137,356</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14659">한재환</a></td><td>3,000</td><td>0.04</td><td>79,425</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14650">박지한</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12574">서의태</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14598">안인산</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16063">김준원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16061">고승완</a></td><td>3,000</td><td>-0.12</td><td>-24,663</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16060">조현민</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16059">원종해</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16058">김세훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16057">손주환</a></td><td>3,000</td><td>0.95</td><td>3,154</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16056">최우석</a></td><td>3,000</td><td>-0.06</td><td>-52,324</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16052">김휘건</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16051">박인우</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16050">김태호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16049">김민규</a></td><td>3,000</td><td>-0.11</td><td>-26,338</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15120">서준교</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15456">신성호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14829">김정호</a></td><td>3,000</td><td>0.17</td><td>18,157</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15453">목지훈</a></td><td>3,000</td><td>0.21</td><td>14,585</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15452">신용석</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15450">신영우</a></td><td>3,000</td><td>-0.06</td><td>-49,139</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16012">노재원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16374">최윤혁</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16375">김동현</a></td><td>-</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [101]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=10165">양의지</a></td><td>160,000</td><td>3.93</td><td>40,752</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16300">케이브</a></td><td>112,000</td><td>3.52</td><td>31,799</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16298">콜어빈</a></td><td>112,000</td><td>1.66</td><td>67,399</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10643">김재환</a></td><td>100,000</td><td>1.54</td><td>65,036</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16299">잭로그</a></td><td>98,000</td><td>3.44</td><td>28,516</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10195">정수빈</a></td><td>60,000</td><td>2.55</td><td>23,567</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13061">곽빈</a></td><td>38,000</td><td>0.89</td><td>42,931</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11087">강승호</a></td><td>37,000</td><td>1.59</td><td>23,268</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11213">양석환</a></td><td>30,000</td><td>0.96</td><td>31,202</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10696">홍건희</a></td><td>30,000</td><td>0.03</td><td>1,042,499</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12852">최원준</a></td><td>22,500</td><td>0.97</td><td>23,214</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12524">조수행</a></td><td>20,000</td><td>-0.31</td><td>-64,098</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12568">이영하</a></td><td>18,000</td><td>0.61</td><td>29,714</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12847">김명신</a></td><td>16,500</td><td>-0.16</td><td>-102,747</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16067">김택연</a></td><td>14,000</td><td>0.64</td><td>21,887</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15099">이병헌</a></td><td>13,000</td><td>-0.02</td><td>-598,477</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12850">박치국</a></td><td>11,000</td><td>0.20</td><td>54,748</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12549">김기연</a></td><td>11,000</td><td>0.50</td><td>22,160</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12894">이유찬</a></td><td>10,500</td><td>0.70</td><td>14,960</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15127">최지강</a></td><td>9,500</td><td>-0.50</td><td>-19,075</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14770">최승용</a></td><td>8,500</td><td>0.73</td><td>11,592</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12522">박준영</a></td><td>8,500</td><td>0.20</td><td>42,106</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10124">고효준</a></td><td>8,000</td><td>-0.35</td><td>-22,543</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15253">김민석</a></td><td>7,500</td><td>-0.74</td><td>-10,161</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11098">김인태</a></td><td>7,200</td><td>0.71</td><td>10,208</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11198">박계범</a></td><td>6,800</td><td>0.08</td><td>87,794</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13094">추재현</a></td><td>6,000</td><td>-0.21</td><td>-28,736</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15508">최준호</a></td><td>5,800</td><td>-0.23</td><td>-25,745</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11300">박정수</a></td><td>5,200</td><td>-0.08</td><td>-68,441</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11097">장승현</a></td><td>4,800</td><td>-0.12</td><td>-41,718</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12678">이승진</a></td><td>4,400</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13072">김민규</a></td><td>4,200</td><td>0.28</td><td>14,994</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14170">김대한</a></td><td>4,200</td><td>-0.13</td><td>-31,872</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14173">이교훈</a></td><td>3,800</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13665">권휘</a></td><td>3,700</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16072">전다민</a></td><td>3,500</td><td>-0.17</td><td>-20,910</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14139">남호</a></td><td>3,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14733">최종인</a></td><td>3,500</td><td>0.00</td><td>-1,112,609</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12970">김민혁</a></td><td>3,420</td><td>0.17</td><td>19,863</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12606">홍성호</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13268">김호준</a></td><td>3,300</td><td>-0.19</td><td>-17,616</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15509">김유성</a></td><td>3,300</td><td>-0.13</td><td>-25,210</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14731">박웅</a></td><td>3,300</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16068">여동건</a></td><td>3,300</td><td>-0.05</td><td>-61,750</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14736">박지훈</a></td><td>3,240</td><td>-0.12</td><td>-27,228</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13070">박신지</a></td><td>3,200</td><td>0.22</td><td>14,270</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15515">박민준</a></td><td>3,100</td><td>-0.05</td><td>-57,614</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14838">박성재</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14768">김도윤</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16069">임종성</a></td><td>3,100</td><td>0.77</td><td>4,038</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16071">박지호</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16076">류현준</a></td><td>3,100</td><td>-0.23</td><td>-13,339</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14737">오명진</a></td><td>3,100</td><td>2.45</td><td>1,265</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14570">장규빈</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16074">손율기</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16399">이한별</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16297">최우혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16296">연서준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16295">주양준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16294">김성재</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16293">양재훈</a></td><td>3,000</td><td>0.06</td><td>48,194</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16292">한다현</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16291">이선우</a></td><td>3,000</td><td>-0.20</td><td>-14,728</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16363">김준상</a></td><td>3,000</td><td>-0.13</td><td>-23,002</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16290">황희천</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16365">김한중</a></td><td>3,000</td><td>0.01</td><td>329,272</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16289">홍민규</a></td><td>3,000</td><td>-0.19</td><td>-15,621</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16288">최민석</a></td><td>3,000</td><td>1.02</td><td>2,954</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16287">박준순</a></td><td>3,000</td><td>0.79</td><td>3,821</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14840">양현진</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14818">최우인</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15106">강동형</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15104">윤태호</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15102">신민철</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15100">김동준</a></td><td>3,000</td><td>-0.34</td><td>-8,875</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14192">지강혁</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13124">김정우</a></td><td>3,000</td><td>-0.08</td><td>-38,733</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14773">강현구</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14732">조제영</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14574">최세창</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14573">제환유</a></td><td>3,000</td><td>-0.02</td><td>-133,362</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14572">이주엽</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16073">김무빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16075">김태완</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15128">천현재</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15129">이민석</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16362">김민호</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16364">김지윤</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16366">박민제</a></td><td>-</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16367">박연준</a></td><td>-</td><td>-</td><td>-</td></tr>							</tbody>
						</table>
""")

In [102]:
team_table.append("""<table>
							<thead>
								<tr>
									<th>선수</th>
									<th>연봉(만원)</th>
									<th>WAR</th>
									<th>WAR당 연봉</th>
								</tr>
							</thead>
							<tbody>
							<tr><td><a href="/player/?m=playerinfo&amp;p_no=15004">푸이그</a></td><td>140,000</td><td>-0.05</td><td>-2,672,470</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16339">로젠버그</a></td><td>98,000</td><td>2.40</td><td>40,821</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16156">카디네스</a></td><td>63,000</td><td>-0.26</td><td>-243,277</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12516">이형종</a></td><td>60,000</td><td>0.19</td><td>319,022</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11161">원종현</a></td><td>50,000</td><td>-0.61</td><td>-81,844</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16393">스톤</a></td><td>49,000</td><td>-0.92</td><td>-53,452</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13941">알칸타라</a></td><td>35,000</td><td>1.55</td><td>22,610</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11376">송성문</a></td><td>30,000</td><td>5.11</td><td>5,868</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10180">이원석</a></td><td>30,000</td><td>-0.07</td><td>-405,093</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10182">최주환</a></td><td>30,000</td><td>-0.62</td><td>-48,121</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10035">이용규</a></td><td>20,000</td><td>-0.16</td><td>-123,634</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11222">하영민</a></td><td>16,500</td><td>1.97</td><td>8,356</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12918">김성민</a></td><td>11,000</td><td>-0.19</td><td>-57,597</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14591">이주형</a></td><td>11,000</td><td>3.62</td><td>3,040</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10870">김재현</a></td><td>10,000</td><td>-0.11</td><td>-92,591</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11244">김태진</a></td><td>9,000</td><td>-0.34</td><td>-26,409</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13092">김선기</a></td><td>8,400</td><td>0.18</td><td>46,764</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15067">주승우</a></td><td>7,700</td><td>1.52</td><td>5,064</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15071">윤석원</a></td><td>6,000</td><td>-0.27</td><td>-22,118</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11226">임병욱</a></td><td>6,000</td><td>-0.52</td><td>-11,519</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11225">임지열</a></td><td>5,800</td><td>2.20</td><td>2,632</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=13223">변상권</a></td><td>5,500</td><td>-0.13</td><td>-40,744</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11148">강진성</a></td><td>5,500</td><td>-0.21</td><td>-26,111</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15472">김건희</a></td><td>5,200</td><td>0.31</td><td>16,537</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12548">김동엽</a></td><td>5,000</td><td>-0.11</td><td>-45,326</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14784">장재영</a></td><td>4,600</td><td>-0.26</td><td>-17,792</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15132">박수종</a></td><td>4,500</td><td>-0.10</td><td>-42,980</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14480">김인범</a></td><td>4,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16128">고영우</a></td><td>4,500</td><td>-0.24</td><td>-18,892</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16123">김윤하</a></td><td>4,500</td><td>-0.08</td><td>-54,953</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16398">웰스</a></td><td>4,200</td><td>0.60</td><td>7,059</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11404">장필준</a></td><td>4,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16136">원성준</a></td><td>4,000</td><td>0.10</td><td>39,176</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12503">김웅빈</a></td><td>4,000</td><td>-0.21</td><td>-19,063</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=10557">오선진</a></td><td>4,000</td><td>-0.18</td><td>-22,589</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12860">오석주</a></td><td>3,900</td><td>-0.06</td><td>-62,428</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16127">김연주</a></td><td>3,800</td><td>-0.06</td><td>-67,384</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15473">김동헌</a></td><td>3,800</td><td>0.23</td><td>16,876</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14133">주성원</a></td><td>3,800</td><td>0.49</td><td>7,777</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14132">조영건</a></td><td>3,800</td><td>0.00</td><td>-1,418,789</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14580">박주홍</a></td><td>3,700</td><td>-0.34</td><td>-10,856</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14130">박주성</a></td><td>3,700</td><td>0.24</td><td>15,323</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14855">이주형</a></td><td>3,700</td><td>0.16</td><td>22,746</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14576">이종민</a></td><td>3,600</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15475">박윤성</a></td><td>3,500</td><td>-0.15</td><td>-22,895</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=12854">양지율</a></td><td>3,500</td><td>-0.36</td><td>-9,763</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14577">김병휘</a></td><td>3,500</td><td>0.03</td><td>105,378</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16122">전준표</a></td><td>3,200</td><td>-0.22</td><td>-14,270</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16124">이재상</a></td><td>3,200</td><td>-0.08</td><td>-41,178</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14601">이강준</a></td><td>3,200</td><td>-0.17</td><td>-18,590</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15476">이승원</a></td><td>3,200</td><td>-0.12</td><td>-26,687</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15485">김동규</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16125">손현기</a></td><td>3,100</td><td>-0.12</td><td>-26,780</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16133">박범준</a></td><td>3,100</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16337">오혜성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16335">정세영</a></td><td>3,000</td><td>-0.04</td><td>-82,605</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16334">권혁빈</a></td><td>3,000</td><td>-0.20</td><td>-14,642</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16330">박정훈</a></td><td>3,000</td><td>-0.03</td><td>-119,888</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16338">정동준</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16336">임진묵</a></td><td>3,000</td><td>-0.04</td><td>-74,236</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16329">여동욱</a></td><td>3,000</td><td>-0.14</td><td>-21,745</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16331">윤현</a></td><td>3,000</td><td>-0.74</td><td>-4,031</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16332">전태현</a></td><td>3,000</td><td>0.06</td><td>51,120</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16328">어준서</a></td><td>3,000</td><td>-1.61</td><td>-1,869</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16384">이준우</a></td><td>3,000</td><td>-0.37</td><td>-8,027</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16325">정현우</a></td><td>3,000</td><td>0.04</td><td>83,762</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16326">김서준</a></td><td>3,000</td><td>-0.14</td><td>-20,926</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16327">염승원</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16333">양현종</a></td><td>3,000</td><td>-0.20</td><td>-15,332</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=14853">양경식</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16135">심휘윤</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16132">박채울</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16131">김지성</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16130">송지후</a></td><td>3,000</td><td>-0.34</td><td>-8,727</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16129">김주훈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15483">서유신</a></td><td>3,000</td><td>-0.24</td><td>-12,551</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=15479">박성빈</a></td><td>3,000</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=11360">이우석</a></td><td>1,500</td><td>-</td><td>-</td></tr><tr><td><a href="/player/?m=playerinfo&amp;p_no=16385">손힘찬</a></td><td>-</td><td>-0.07</td><td>-</td></tr>							</tbody>
						</table>
""")

In [103]:
len(team_table)

10

In [104]:
earning = pd.DataFrame()
for i in range(len(team_table)):
    name = team_names[i]
    team = team_table[i]
    print(name)
    df, pids = get_team_stats_from_markup(StringIO(str(team)))
    df['팀'] = name
    df['pid'] = pids[1:]
    print(df.shape)
    print(len(pids))
    earning = pd.concat([earning, df])
    display(earning.tail())
earning.isna().sum()

한화 이글스
(89, 6)
90

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

     선수 연봉(만원) WAR WAR당 연봉       팀    pid
84  한서구   3000   -       -  한화 이글스  15426
85  성지훈   3000   -       -  한화 이글스  15631
86  신우재   3000   -       -  한화 이글스  16011
87  박부성      -   -       -  한화 이글스  16373
88  양선률      -   -       -  한화 이글스  14682

LG 트윈스
(81, 6)
82

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

      선수 연봉(만원)    WAR WAR당 연봉       팀    pid
76   허용주   3000      -       -  LG 트윈스  15491
77   심규빈   3000      -       -  LG 트윈스  16022
78   김도윤   3000      -       -  LG 트윈스  16021
79  코엔 윈   1600  -0.13  -12502  LG 트윈스  15265
80    김웅      -      -       -  LG 트윈스  16388

롯데 자이언츠
(82, 6)
83

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

     선수 연봉(만원) WAR WAR당 연봉        팀    pid
77  박지훈      -   -       -  롯데 자이언츠  16382
78  유태웅      -   -       -  롯데 자이언츠  16376
79  박건우      -   -       -  롯데 자이언츠  16378
80  이상화      -   -       -  롯데 자이언츠  16380
81  정선우      -   -       -  롯데 자이언츠  16381

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

KIA 타이거즈
(85, 6)
86

     선수 연봉(만원)    WAR WAR당 연봉         팀    pid
80  강동훈   3000      -       -  KIA 타이거즈  16080
81  이상준   3000      -       -  KIA 타이거즈  16078
82  김재현   3000      -       -  KIA 타이거즈  15440
83  박상준   3000      -       -  KIA 타이거즈  15125
84  이도현   3000  -0.10  -28644  KIA 타이거즈  15437

KT 위즈

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(89, 6)
90

     선수 연봉(만원) WAR WAR당 연봉      팀    pid
84  이승현   3000   -       -  KT 위즈  16034
85  박태완   3000   -       -  KT 위즈  16033
86  신호준   3000   -       -  KT 위즈  16031
87  장민호      -   -       -  KT 위즈  16386
88  정운교      -   -       -  KT 위즈  16387

삼성 라이온즈
(89, 6)
90

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

     선수 연봉(만원)    WAR WAR당 연봉        팀    pid
84  정민성   3000  -0.06  -48093  삼성 라이온즈  15866
85  김백산      -      -       -  삼성 라이온즈  16368
86  김유현      -      -       -  삼성 라이온즈  16369
87  최예한      -      -       -  삼성 라이온즈  16370
88  김상준      -      -       -  삼성 라이온즈  16371

SSG 랜더스
(76, 6)
77

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

     선수 연봉(만원)   WAR WAR당 연봉        팀    pid
71  정현승   3000  0.03   99423  SSG 랜더스  16043
72  최현석   3000  0.02  123599  SSG 랜더스  16041
73  박기호   3000  0.31    9574  SSG 랜더스  16040
74  임근우   3000     -       -  SSG 랜더스  15122
75  이승민   3000     -       -  SSG 랜더스  16039

NC 다이노스

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(86, 6)
87

     선수 연봉(만원)    WAR WAR당 연봉        팀    pid
81  신용석   3000      -       -  NC 다이노스  15452
82  신영우   3000  -0.06  -49139  NC 다이노스  15450
83  노재원   3000      -       -  NC 다이노스  16012
84  최윤혁      -      -       -  NC 다이노스  16374
85  김동현      -      -       -  NC 다이노스  16375

두산 베어스

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

(90, 6)
91

     선수 연봉(만원) WAR WAR당 연봉       팀    pid
85  이민석   3000   -       -  두산 베어스  15129
86  김민호      -   -       -  두산 베어스  16362
87  김지윤      -   -       -  두산 베어스  16364
88  박민제      -   -       -  두산 베어스  16366
89  박연준      -   -       -  두산 베어스  16367

/tmp/ipython-input-3-4266666629.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

키움 히어로즈
(79, 6)
80

     선수 연봉(만원)    WAR WAR당 연봉        팀    pid
74  김주훈   3000      -       -  키움 히어로즈  16129
75  서유신   3000  -0.24  -12551  키움 히어로즈  15483
76  박성빈   3000      -       -  키움 히어로즈  15479
77  이우석   1500      -       -  키움 히어로즈  11360
78  손힘찬      -  -0.07       -  키움 히어로즈  16385

선수         0
연봉(만원)     0
WAR        0
WAR당 연봉    0
팀          0
pid        0
dtype: int64

In [105]:
earning.to_csv("2025_연봉_statiz.csv", index=False)

In [106]:
fielding

   Rank Name   Team      Sort▼    G   GS      IP   TC   PO  Ass  ...  \
   Rank Name   Team WAAwithPOS    G   GS      IP   TC   PO  Ass  ...
0     1  이도윤  23 SS      1.297   97   90   746.0  368  157  203  ...
1     2  최재훈   23 C      1.180  120  106   884.1  774  704   67  ...
2     3  노시환  23 3B      0.369  122  121  1065.2  361  114  228  ...
3     4  박상언   23 C      0.347   79   38   388.2  368  333   34  ...
4     5  문현빈  23 2B      0.325   54   42   358.0  184   77  102  ...
..  ...  ...    ...        ...  ...  ...     ...  ...  ...  ...  ...
83   67  김준형   23 P        NaN    7    0     7.2    0    0    0  ...
84   67  김동규   23 P        NaN    3    1     4.0    0    0    0  ...
85   67  윤정현   23 P        NaN    4    0     6.0    1    0    1  ...
86   67  신준우  23 3B        NaN    1    0     1.0    0    0    0  ...
87   67   양현   23 P        NaN   54    0    57.0   14    3   11  ...

   수비 관련 득점 기여도                      POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼  \
        Blk RAA Frm RAA 종합 RAA  /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
0           NaN     NaN   6.37  8.66   6.34      12.71    0.650       1.297
1          0.23     NaN   1.95  2.24   9.62      11.57    0.199       1.180
2           NaN     NaN   3.61  3.97   0.00       3.61    0.369       0.369
3         -0.12     NaN  -0.15 -0.24   3.55       3.41   -0.015       0.347
4           NaN     NaN   1.36  1.42   1.83       3.19    0.138       0.325
..          ...     ...    ...   ...    ...        ...      ...         ...
83          NaN     NaN   0.00  0.00    NaN        NaN    0.000         NaN
84          NaN     NaN   0.00  0.00    NaN        NaN    0.000         NaN
85          NaN     NaN   0.00  0.00    NaN        NaN    0.000         NaN
86          NaN     NaN   0.00 -0.01    NaN        NaN    0.000         NaN
87          NaN     NaN   0.00  0.00    NaN        NaN    0.000         NaN

          팀    pid

0    한화 이글스  11414
1    한화 이글스  10170
2    한화 이글스  14125
3    한화 이글스  12587
4    한화 이글스  15422
..      ...    ...
83  키움 히어로즈  14848
84  키움 히어로즈  15485
85  키움 히어로즈  14131
86  키움 히어로즈  14695
87  키움 히어로즈  10730

[698 rows x 29 columns]

In [107]:
fielding['pid'].value_counts()

pid
10894    6
14591    5
15651    5
13056    5
11147    5
        ..
13092    1
15073    1
14848    1
14131    1
10730    1
Name: count, Length: 364, dtype: int64

In [109]:
fielding[fielding['pid'] == '10894']

   Rank Name   Team      Sort▼   G  GS     IP   TC   PO Ass  ... 수비 관련 득점 기여도  \
   Rank Name   Team WAAwithPOS   G  GS     IP   TC   PO Ass  ...      Blk RAA
25   26  류지혁  23 1B     -0.054   5   2   18.0   13   13   0  ...          NaN
36   37  류지혁  23 2B     -0.147   7   7   52.0   29   11  18  ...          NaN
42   43  류지혁  23 3B     -0.418  55  48  402.2  114   38  72  ...          NaN
14   15  류지혁  23 2B      0.098  11   6   56.0   31   13  18  ...          NaN
50   51  류지혁  23 3B     -0.086  44  35  288.0   72   18  52  ...          NaN
62   63  류지혁  23 1B     -0.163  26  20  176.0  171  160  11  ...          NaN

                        POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼         팀  \
   Frm RAA 종합 RAA  /144 POSAdj RAAwithPOS WAAwoPOS WAAwithPOS▼
25     NaN  -0.31 -0.34  -0.22      -0.53   -0.032      -0.054  KIA 타이거즈
36     NaN  -1.69 -1.85   0.25      -1.44   -0.173      -0.147  KIA 타이거즈
42     NaN  -4.10 -4.47   0.00      -4.10   -0.418      -0.418  KIA 타이거즈
14     NaN   0.67  0.73   0.29       0.96    0.068       0.098   삼성 라이온즈
50     NaN  -0.84 -0.92   0.00      -0.84   -0.086      -0.086   삼성 라이온즈
62     NaN   0.15  0.16  -1.74      -1.59    0.015      -0.163   삼성 라이온즈

      pid

25  10894
36  10894
42  10894
14  10894
50  10894
62  10894

[6 rows x 29 columns]

In [110]:
team_names

['한화 이글스',
 'LG 트윈스',
 '롯데 자이언츠',
 'KIA 타이거즈',
 'KT 위즈',
 '삼성 라이온즈',
 'SSG 랜더스',
 'NC 다이노스',
 '두산 베어스',
 '키움 히어로즈']

In [111]:
raw = {
    '팀명': team_names,
    '2021': [415241, 949698, 887000, 540325, 726567, 1040517, 1125489, 1001734, 814760, 674831],
    '2022': [509546, 1053200, 769886, 1156339, 789087, 1276395, 2487512, 1248634, 1077800, 499422],
    '2023': [853100, 1079750, 1064667, 987771, 948300, 1044073, 1084647, 1008812, 1118175, 645200],
    '2024': [1071046, 1385616, 1115018, 1124900, 1051641, 1118100, 1045700, 947275, 1119436, 567876]
}

pd.DataFrame(raw).to_csv("구단별연봉상위40인(2021~2024).csv", index=False)